### ISSUE TITLE
Building bullet

### ISSUE THREAD

**Issue by watfuk** [kripken/emscripten#1001]
I apologize if this is a stupid issue, (nearly certain it is...) but I'm having problems building and linking bullet with emscripten.  Building and installing native bullet was simple, so I then followed the instructions here,  https://github.com/kripken/emscripten/wiki/Building-Projects which made me end up doing ```./autogen.sh``` along with proper use of ```emconfigure```/```emmake```.  It seems to build successfully, however no instances of ```.bc``` exist in the names of any files anywhere in the project folder.

Where did it actually build to?  Again, apologies if I'm being a massive idiot.

**Comment by juj** [comment]
Nowadays we definitely recommend using CMake to build Bullet, which should work out of the box for Emscripten. I believe the output will be `.a` to accommodate for similar linking behavior as native code. I'll close this as old, but if you are still working on Bullet builds and have any issues, feel free to open a new but item on that.
