### ISSUE TITLE
Allocation failed - process out of memory

### ISSUE THREAD

**Issue by timprepscius** [kripken/emscripten#1018]
I'm just wondering whether a work-around for this 'Allocation failed - process out of memory' has been found.

  emscript: phase 1 took 11.5666928291 seconds
  emscript: phase 2 working on 1 chunks  (intended chunk size: 1630.17 MB, meta: 506.76 MB, forwarded: 2.75 MB, total: 544.91 MB)
FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory

Code base is medium -> smallish.  I am using -g because I need debugging.  I've read everything I can find on the interwebs, and it seems like this is due to some restriction in V8?

Is there anything I can do?

Thanks

**Comment by kripken** [comment]
Closing since this is before several compiler updates, and the issues an workarounds here are no longer relevant.
