### ISSUE TITLE
Use FileSystem API 

### ISSUE THREAD

**Issue by ghost** [kripken/emscripten#129]
There is a API available to access the [FileSystem](http://dev.w3.org/2009/dap/file-system/pub/FileSystem/) via JavaScript. Since currently the filesystem data is stored in memory it is fast but won't allow larger file sizes. Also there is no way for the user to prevent a WebApp to store too much data (to have quotas).
For this the `FS` library should make use of the _FileSystem_ API when available and fallback to an emulation (which is similar to the current), if it's not.

_EDIT:_ Reading further into this the `LocalFileSystemSync` interface is sadly only available for _WebWorker_ contexts, not for _Window_. Thus to handle this, one would have to send a message to a _WebWorker_ and then to wait till it processes the File operation, which is far from ideal.

**Comment by saschanaz** [comment]
I think it's safe to close this, as the FileSystem API has been discontinued. Feel free to reopen if anyone disagree.
