### ISSUE TITLE
glGetVertexAttribiv problems with vertex attrib array buffer binding

### ISSUE THREAD

**Issue by thekend** [kripken/emscripten#1330]
<code>unsigned vb;
glGenBuffers(1, &vb);
glBindBuffer(GL_ARRAY_BUFFER, vb);
glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, 0);
int vb2;
glGetVertexAttribiv(0, GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING, &vb2;</code>

Now, vb and vb2 should be the same, in a native C++ app it's the same. Unfortunately with emscripten it's different. 
Our rendering system does some consistency check that cheks if the state in our system and the state of GL are match. But with emscripten we cannot use this because of this (and maybe some similar) problem.

edit: it works with -g compiler flags instead of -o2

**Comment by BrunoLevy** [comment]
This is because in that case, the result is a WebGLBuffer instead of an integer, and one needs to extract its identifier as in glGetIntegerv. In glGetVertexAttribiv implementation, the following code block is missing:

```
else if (data instanceof WebGLBuffer) {
          {{{ makeSetValue('p', '0', 'data.name | 0', 'i32') }}};
```

Needs to be inserted right after:

```
if (typeof data == 'number' || typeof data == 'boolean') {
      {{{ makeSetValue('params', '0', 'data', 'i32') }}};
}
```

Rem: in a C/C++ program, without patching the lib, one can use instead inline JavaScript as follows:

   ```
         GLuint buffer_binding = EM_ASM_INT({
               var buffer = Module.ctx.getVertexAttrib(
                   $0, $1
               );
               return ((buffer == null) ? 0 : buffer.name);
            },index,GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING);

```

**Comment by juj** [comment]
Thanks, this was a good and clear bug report, but for some reason it hadn't registered until now that I was scraping through the backlog of GL issues. Fixed in the above commit and added the suggested test snippet from comment 0.
