### ISSUE TITLE
Support `glLogicOp` and the `GL_COLOR_LOGIC_OP` constant

### ISSUE THREAD

**Issue by michaeljbishop** [kripken/emscripten#1416]
Emscripten applications throw an "missing function" error if they call `glLogicOp` .

Sample code below.

		glEnable(GL_COLOR_LOGIC_OP);
		glLogicOp(GL_XOR);

**Comment by juj** [comment]
I'm thinking that this is not possible to emulate at all - Regal was not able to do it in https://github.com/p3/regal/issues/137, so doubt there is much we could do either. Closing this as unsupportable.
