### ISSUE TITLE
Support WebGL2 for OGL ES 3.0 C projects

### ISSUE THREAD

**Issue by oscarbg** [kripken/emscripten#1553]
Hi seems Webgl2 effort to bring OGL ES 3.0 support to web is coming fast (https://wiki.mozilla.org/Platform/GFX/WebGL2) seems already we have transform feedback and lot more functionality not present in current webgl..
since there are still no demos released I would like to see support in emscripten to support webgl2 via a command line flag of C ES 3.0 projects:
it would create webgl2 contexts( canvas.getContext("experimental-webgl2")) and support ogl es 3.0 apis-> webgl2 apis.
This way we can generate webgl2 from existing OGL ES 3.0 demos for example in Adreno SDK, Mali OGL ES 3.0 SDK and Powervr new sdks..

**Comment by juj** [comment]
This is implemented now and shipping with Emscripten, only thing is to wait for WebGL 2 to ship in stable versions (Firefox Nightly and Chrome Canary have had experimental WebGL 2 for a while now). Closing as done.
