### ISSUE TITLE
dom access from python

### ISSUE THREAD

**Issue by glyph** [kripken/emscripten#158]
I've seen the emscripten python interpreter demo, and it's cool, but what would be *really* cool is if I could actually build a real client-side web app using CPython.  That would necessitate access to DOM APIs, and possibly the ability to invoke javascript via some kind of FFI (so one could use, i.e. jQuery).

**Comment by juj** [comment]
Let me close this, looks like nothing to do here specifically. We have since created the WebIDL binder and embind. Developing a JS <-> python binding generator looks to be suitable to be tracked in the above repository issue rather than Emscripten itself.
