### ISSUE TITLE
AL_PITCH is possible to support

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#1734]
AudioBufferSourceNode has a 'playbackRate' property that lets you multiply the playback rate of the node to achieve playback at lower/higher sampling rates (though I think it might produce artifacts, given how you're using it?) So it might be worth providing it in your implementation instead of spitting out the warnings you do now. You'd just need to retain the pitch value in the AL_PITCH setter then apply it when creating sourcenodes.

**Comment by juj** [comment]
Support for AL_PITCH was added in above PR quite some time ago, forgot to close this earlier.
