### ISSUE TITLE
Missing OpenAL functions

### ISSUE THREAD

**Issue by jamesu** [kripken/emscripten#1923]
During porting of an app, I noticed the following useful OpenAL functions are missing completely (i.e. there is not even a stub). Looking at the code, these should be fairly trivial to implement. For AL_GAIN on the listener a master gain control needs to be added.
- alIsBuffer(bufferId)
- alGetSourcefv(source, param, values) (AL_POSITION, AL_VELOCITY)
- alGetListenerf(param, values) (AL_GAIN)
- alGetListeneri(param, values) (don't think this has any valid params)
- alListenerf(param, value) (AL_GAIN)
- alEnable(param)
- alDisable(param)

In relation to "alEnable", I noticed "alDistanceModel" is stubbed out and doesn't do anything useful, though for most cases one can probably live without it.

In addition there are a few other slightly less useful functions such as alGetBoolean, alIsEnabled, et. However I haven't seen any code which makes use of them (yet).

**Comment by juj** [comment]
The last functions were resolved in #5235.
