### ISSUE TITLE
SDL mouse events are not handled on Firefox OS

### ISSUE THREAD

**Issue by thp** [kripken/emscripten#1968]
When using Emscripten 1.7.8 and its SDL compatibility library, mouse events are
only working on the Desktop. Mouse events are not properly emulated for touch
devices such as Firefox OS or Desktop Firefox when touch emulation is on.

A minimal example demonstrating this bug is available here:
https://github.com/thp/emscriptentouchbug

Preparation:
1. "make" (or use the files in prebuilt/, which have been compiled with
           Emscripten 1.7.8)

Working case:
1. Open in Desktop Firefox (tested with Firefox 26 on OS X)
2. Click and drag with the mouse on the black canvas - a white square
   should appear while dragging and follow the mouse coordinates

Broken case 1:
1. Open in Desktop Firefox
2. "Tools" -> "Web Developer" -> "Responsive Design View"
3. Observe that interaction still works with the mouse (white square)
4. Enable "Simulate Touch Events" (second-to-last button in the buttons
   that appear at the top of the webpage view
5. Reload the page when asked by Firefox to do so
6. Try interacting with the screen as before - no white square appears

Broken case 2:
1. Deploy to a Firefox OS device using e.g. about:app-manager
   (a .zip file is in prebuilt/, or use "make package")
2. Open the application in Firefox OS
3. Observe that touch events are not working (no white square)

**Comment by juj** [comment]
SDL has touch-mouse emulation now, and Firefox OS is no longer on radar, so this can be closed.
