### ISSUE TITLE
Issues with javascript handling glut events

### ISSUE THREAD

**Issue by AlexPerrot** [kripken/emscripten#1989]
I'm having issues with the way javascript events are processed to be passed to the glut callbacks defined in the C++ code.

You can see in library_glut.js that the javascript listeners are attached to the window :

```
    window.addEventListener("keydown", GLUT.onKeydown, true);
    window.addEventListener("keyup", GLUT.onKeyup, true);
    if (isTouchDevice) {
      window.addEventListener("touchmove", GLUT.onMousemove, true);
      window.addEventListener("touchstart", GLUT.onMouseButtonDown, true);
      window.addEventListener("touchend", GLUT.onMouseButtonUp, true);
    } else {
      window.addEventListener("mousemove", GLUT.onMousemove, true);
      window.addEventListener("mousedown", GLUT.onMouseButtonDown, true);
      window.addEventListener("mouseup", GLUT.onMouseButtonUp, true);
      // IE9, Chrome, Safari, Opera
      window.addEventListener("mousewheel", GLUT.onMouseWheel, true);
      // Firefox
      window.addEventListener("DOMMouseScroll", GLUT.onMouseWheel, true);
    }
```

This causes several issues :
First, the mousewheel listeners prevent the page from scrolling, even when the mouse is not directly over the canvas.
Another issue arises when the canvas is not dispayed (i'm using jquery mobile's page system) : the mousewheel events are fired with coordinates inside the canvas (in my case resulting in a zoomin/zoomout while the canvas is not displayed).
These two issues are easily fixed by attaching the mousewheel listeners directly to the canvas.

The biggest issue however is about the keyboard events. They are always processed and transformed to glut events, even when the focus is in a text input somewhere else on the page. This is very annoying, since it prevents the user from typing anything into the input field.

To conclude, it seems reasonable to me that the javascript events should only be passed to glut if they target the canvas, not other elements in the page.

**Comment by AlexPerrot** [comment]
Closing this, since this is super old.
I'm not using glut anymore, I handle the context creation and event listeners myself, it is much more flexible and simple.

**Comment by dwn** [comment]
Sad that this got closed, effectively with the statement that one person is personally not using GLUT, so everyone who is doesn't matter. The blacklist sounded like a great idea, and one that I'd think wouldn't have been too difficult to implement.
