### ISSUE TITLE
Improve Code Readability and Aesthetics

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#20]
Help with making the code prettier would be great. It is really easy to improve this, just changing function names would be a good start. Bigger refactorings are also possible of course.

Emscripten has tons of automatic tests, so we can make these changes with no risk of regressions.

The reason I don't do more of this myself, is I am too used to the code to know what stands out as unreadable and in need of cleanup.

**Comment by juj** [comment]
I'd prefer closing this, since this is not a clear bug that can be ever called as fixed?

**Comment by kripken** [comment]
Sure.
