### ISSUE TITLE
OpenAL missing function

### ISSUE THREAD

**Issue by wolfviking0** [kripken/emscripten#2064]
Hi, with the recent push on the library openal, I try to build Unigine with OpenAL, I still have missing function (but less than before) :

warning: unresolved symbol: alGetEnumValue
warning: unresolved symbol: alcGetIntegerv
warning: unresolved symbol: alIsSource
warning: unresolved symbol: alListener3f
warning: unresolved symbol: alSpeedOfSound
warning: unresolved symbol: alSource3i

**Comment by juj** [comment]
The last functions were resolved in #5235.
