### ISSUE TITLE
Linking to static library containing duplicate filename fails

### ISSUE THREAD

**Issue by AerialX** [kripken/emscripten#2142]
When emcc links to a static library, it first runs `LLVM_AR x f` to extract the objects to a temporary directory (in tools/shared.py:link). If the archive contains a duplicate filename, it will be overwritten during the extraction process and linking will fail due to missing symbols in the file(s) that were destroyed.

GNU ar seems have a specific option to get around this, `ar xN count archive filename`, though it doesn't seem that llvm-ar has the same feature. To work around the issue personally I've replaced LLVM_AR with the following replacement extractor, which simply extracts an archive while ignoring the original filenames:
https://gist.github.com/AerialX/5f6763559769bf9c30e6

I'm not sure of the best approach for emscripten to take, but is it possible for this to be somehow fixed?

**Comment by kripken** [comment]
I pushed a commit to add hashing to each object in `.a` files, as suggested in https://github.com/kripken/emscripten/issues/2619#issuecomment-84847161 , which should fix this.

This will break people that expect to be able to read the objects themselves. We'll see if this is a problem on incoming. If it is, we might need to put it behind a flag.

**Comment by kripken** [comment]
No problems were reported, this has been merged to master.
