### ISSUE TITLE
Unreal Engine Demo is down

### ISSUE THREAD

**Issue by coolwanglu** [kripken/emscripten#2318]
http://www.unrealengine.com/html5/

Got a 404.

**Comment by SkylarLeroy** [comment]
It's up can Close
https://www.unrealengine.com/html5/

**Comment by juj** [comment]
Now that Unreal Engine 4.7 is out, people can export their own content for UE4.7 editor. Their documentation for that is supposed to live here https://docs.unrealengine.com/latest/INT/Platforms/HTML5/GettingStarted/index.html , although that still has not been updated and it's pointing to old UE4.5 beta stub version. Let's close this as resolved however.
