### ISSUE TITLE
Call syncfs() on IDBFS when the C fsync() is called

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#2492]
This seems reasonable to do, as IDBFS does have the a concept of writing out to storage. However, it is asynchronous which may be confusing.

**Comment by timdream** [comment]
I would like to take on this issue, as part of approach to fix dreamlayers/em-dosbox#4. Not able to block `fsync` call is worse than ignoring it, so I think we should hook it up even if we can't return synchronously. My proposed fix will hook the call. 

There is one problem though on item 3: whether or not to sync the entire file system. I am open to either option but I would like to know what's acceptable before I work on a patch. @kripken what's your opinion here?

(Without reading the patch my previous approach was to [implement a AUTO_SYNCFS feature](https://github.com/timdream/emscripten/commit/97b64e4932d6470f9c6d9593e0f6d10ea0269cd0), if that's acceptable I will submit a pull request.)

**Comment by kripken** [comment]
I think syncfs works on a single mount? Sounds ok to sync a whole mount at a time, people can split them up if they want to sync separately.

Note btw that em-dosbox has experimented with using emterpreter+sync, which allows synchronous fsync. I don't think fsync is hooked up yet, but it would be easy, see recent work on `emscripten_idb_*` sync versions.

**Comment by timdream** [comment]
@kripken I assume your opinion is that using emterpreter+sync and call `syncfs()` on the mount is the acceptable impl? I will try to submit a patch to do that.

**Comment by timdream** [comment]
Hum, after reading `EmterpreterAsync.handle()` I can't figured out how `fsync` call could return an real error code asynchronously. I will finish up the tests and submit my original patch first.

**Comment by timdream** [comment]
Fixed by #3398? Should this issue be closed?

**Comment by kripken** [comment]
Yes, thanks.
