### ISSUE TITLE
rebase emscripten-fastcomp on clang 3.4.2 (or latest) to support mergefunc

### ISSUE THREAD

**Issue by chadaustin** [kripken/emscripten#2504]
clang 3.3's mergefunc is broken, but it works in clang 3.4.2.  emscripten-fastcomp is based on clang 3.3, and mergefunc doesn't work there.  We ought to have emscripten-fastcomp rebased on upstream LLVM.

cc @sunfishcode

**Comment by waywardmonkeys** [comment]
This was addressed long ago and can be closed now.
