### ISSUE TITLE
EM_ASM() et al. should not eval()

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#2596]
Remembering a discussion from while back with @kripken and I now notice we don't yet have an issue about this. Currently the EM_ASM() family of macros generate statements that use `eval()`, but this is not ideal, since
  - it's against Chrome Security Policies, and privileged applications cannot eval.
  - it gives slower performance compared to just statically calling to a generated function.

We should make EM_ASM() perform a normal function call instead out of asm.js.

Also, @kripken, can you remind the biggest hurdles against making EM_ASM() allow the user to write actual inline asm.js code (if he had super-wizard skills)?

**Comment by juj** [comment]
I was profiling one of the GDC demos today, and I'm seeing that this produces a large performance hit in the demo. C code reads

    int ScreenManagerWebGL::GetWidth () const
    {
        int width = EM_ASM_INT_V(return Module['canvas'].clientWidth);
        return width;
    }

which turns into a `_emscripten_asm_const_int` call, which does

    function _emscripten_asm_const_int(code) {
        var args = Array.prototype.slice.call(arguments, 1);
        return Runtime.getAsmConst(code, args.length).apply(null, args) | 0;
    }

![em_asm](https://cloud.githubusercontent.com/assets/225351/6968468/d0f80ba6-d96f-11e4-85f1-6da843c74baa.png)

This call site ends up being the largest individual function and 6.35% of total execution time, and it allocates a garbage collected object every time it is called. So there would be definite wins in optimizing this so that all EM_ASM_* blocks would become actual `function xxx()` calls in the generated output, since that would be faster, not trash, and not to also mention that the code would be browseable in the compiled .js code and show up as actual functions in the browser profilers.

**Comment by kripken** [comment]
The cost isn't in an eval (since we just eval once), I guess the cost here is due to using `arguments` and/or `apply`? If so that means it isn't enough to just avoid eval, we'd need to design this to avoid use of `arguments` as well.

**Comment by kripken** [comment]
Working on this now.

**Comment by kripken** [comment]
Work is on `-no-eval` branches. Hopefully done, running tests. This just removes eval, it still uses arguments.

**Comment by kripken** [comment]
Landed on incoming.

One concern that came up is that now EM_ASM contents are raw JS, which means that closure can optimize them. It's actually not clear to me if that is good or bad - probably good - but it's a change from before. A few tests had to be modified.

So with that done, that leaves the issue of avoiding arguments use. @juj , can you please measure if we still need to do that? I wonder if the slowness is not going to be less bad now.

**Comment by juj** [comment]
Thanks for working on this! Unfortunately I don't have access to build the original code, so I had to test it synthetically. I wrote the following test to measure:

	#include <emscripten.h>

	void tick()
	{
		int totalWidth = 0;
		double d = emscripten_get_now();
		for(int i = 0; i < 100000; ++i)
			totalWidth += EM_ASM_INT_V(return Module['canvas'].clientWidth);
		double g = emscripten_get_now();
	    printf("%d: %g\n", totalWidth, (g-d));
	}

	int main()
	{
		emscripten_set_main_loop(tick, 0, 0);
	}

The old generated code looked like this:

    function _emscripten_asm_const_int(code) {
     var args = Array.prototype.slice.call(arguments, 1);
     return Runtime.getAsmConst(code, args.length).apply(null, args) | 0;
    }
    function __Z4tickv() {
      ...
      i1 = (_emscripten_asm_const_int(8) | 0) + i1 | 0;
      ...
    }

and that clocks in about 82 msecs when running. The new code looks like this:

    Runtime.asmConsts = [ (function() {
     return Module["canvas"].clientWidth;
    }) ];
    function _emscripten_asm_const_int(code) {
     var args = Array.prototype.slice.call(arguments, 1);
     return Runtime.asmConsts[code].apply(null, args) | 0;
    }
    function __Z4tickv() {
      ...
      i1 = (_emscripten_asm_const_int(0) | 0) + i1 | 0;
      ...
    }

which does not seem to have much effect, and it prints 78 msecs on average. I then hand-edited the code to the ideal form that the compiler could generate:

    function _emscripten_em_asm_code() {
     return Module["canvas"].clientWidth;  
    }

    Module.asmLibraryArg = {
       ...
        "_emscripten_em_asm_code": _emscripten_em_asm_code,
       ...

    var asm = (function(global,env,buffer) {
       ...
       var _emscripten_em_asm_code=env._emscripten_em_asm_code;
       ...

    function __Z4tickv() {
      ...
      i1 = (_emscripten_em_asm_code() | 0) + i1 | 0;
      ...
    }
       
and running that gives a result of 8 msecs! So it looks like accessing arguments, slicing and memory allocation are the costly parts here.

**Comment by kripken** [comment]
Ok, thanks for the data, I'll look into optimizing the rest then, looks like we definitely want that.

**Comment by kripken** [comment]
Optimized, looks fast on your benchmark.

**Comment by juj** [comment]
Works great, thanks! Also now the allocation logger is showing zero memory allocations coming from EM_ASM blocks, so this should be super-fast now.
