### ISSUE TITLE
Research the idea of optimized binary asm.js representation.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#2831]
A collaborator on IRC asked about being able to store compiled asm.js code as a binary representation, instead of a JS ascii representation, in order to compress down the output file sizes.

This is an interesting thought, which has also been discussed before: a binary representation is naturally smaller than an ascii one, and one could xhr in a binary data blob that had the asm.js code, and we could spawn a background web worker to decode it to back to javascript before running the main page. This could serve as a basis for possible future official binary asm.js representation, where the browsers could AoT-compile the binary representation directly, without needing to parse the ascii representation at all.

Currently we rely on gzipping the contents, which is very effective. However experience shows that running a domain-specific compression (binary representation can be seen as such) first before a generic compressor always improves compression ratios - for example the crunch library, or binary mesh formats vs collada. The questions to consider here are:

  - how much of an improvement in disk sizes could this scheme give?
  - how long would the decoding at startup take? The decoder could of course itself be implemented in asm.js for best performance.
  - how much extra memory impact would this create at startup?

If anyone's interested in owning this project, do give a shout!

**Comment by juj** [comment]
The PR https://github.com/kripken/emscripten/pull/3766 will resolve this.

**Comment by aidanhs** [comment]
@juj that PR has been merged now, might be worth closing?

**Comment by kripken** [comment]
Yes, thanks. Basically WebAssembly is implementing this, and emscripten will support that of course.
