### ISSUE TITLE
DOM IDBDatabase Exception in Safari 7

### ISSUE THREAD

**Issue by cwoffenden** [kripken/emscripten#2977]
If I use the `file_packager` to bundle files using the `--use-preload-cache` option, I get this in the latest Safari on both OS X and iOS:

```
NotFoundError: DOM IDBDatabase Exception 8: An operation failed because the requested database object could not be found.
```

With older versions of Safari there was no problem. The same packaged files work in Firefox, Chrome and IE. An example page with [cached files is here](http://www.numfum.com/cw/emscripten/).

**Comment by keithjohnston** [comment]
I see the same error.

**Comment by cwoffenden** [comment]
The workaround for Safari (which is still valid) is to not use `--use-preload-cache` and to rely on the browser's own cache (`--preload` will do this anyway) . In use I found it worked quite well (although for my project at the time I didn't go with the `file_packer`, instead preloading the content in batches in the background).
