### ISSUE TITLE
Moonlight JS - C# / .NET Runtime for Javascript

### ISSUE THREAD

**Issue by rdkhatch** [kripken/emscripten#30]
Moonlight is the open source, client-side .NET runtime.

http://www.mono-project.com/Moonlight

Moonlight is currently being compiled by Xamarin @ http://xamarin.com (Miguel de lcaza) to iPhone, iPad, & Android devices.

However, the most important platform - is the browser.  Our goal is to have a .NET runtime for Javascript.  This would open the flood gates for rich-client business applications of all kinds to be deployed to the browser, to run on any operating system or device.

Ryan

PS.  Mono compiler has full, built-in LLVM output support.  http://www.mono-project.com/Mono_LLVM

**Comment by juj** [comment]
Hey, this is a very old item, and probably not useful to track its port as a github bug, so I'll close this to clean up. If this is being worked on, let's focus on any individual bugs arising during the porting process as separate items.
