### ISSUE TITLE
Emscripten eats MouseDown event

### ISSUE THREAD

**Issue by salos1982** [kripken/emscripten#3040]
http://pastebin.com/fPepBAMS

compile with emcc -s USE_SDL=2 sdl2_mouse.c -o sdl2_mouse.html
emcc version 1.27

Slightly modified sd2_mouse.c test case.
When press and release mouse button inside red rectangle everything is good I have 2 messages button down and button up.
However if I press mouse button inside red rectangle then move cursor out of red rectangle and then release mouse. I will see only one message (button down). It is correct. **But if I press again inside rect rectangle no messages appears but have to**. When I release mouse button I got message about mouse up. It also correct.

**Comment by fabiosantoscode** [comment]
You can actually see event listeners and jump to their code using the inspector in firefox. Look for the `ev` markings to the right of every tag.

**Comment by TheKK** [comment]
This bug has already fixed in 1.34.5, everything works fine now!
