### ISSUE TITLE
SSE1 support does not have prefetch.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3050]
SSE1 xmmintrin.h contains the following data prefetch instructions:

	_mm_prefetch(data, _MM_HINT_T0);
	_mm_prefetch(data, _MM_HINT_T1);
	_mm_prefetch(data, _MM_HINT_T2);
	_mm_prefetch(data, _MM_HINT_NTA);

We can easily enough implement a dummy no-op function to allow ported code to compile, but is there a way or plans to properly support these in SIMD-JS?

**Comment by duanyao** [comment]
+1 for no-op. Just hit this issue when [porting libmp3lame](https://github.com/bgrins/videoconverter.js/pull/30/files#diff-1ea18fda65f3c64946a6995227be96b9R9)

**Comment by sunfishcode** [comment]
There are no present plans to support these in SIMD.js. No-op implementations would be fine.

**Comment by juj** [comment]
This was no-opped:

    // No NTA cache hint available.
    #define _mm_stream_ps _mm_store_ps

    #define _MM_HINT_T0 3
    #define _MM_HINT_T1 2
    #define _MM_HINT_T2 1
    #define _MM_HINT_NTA 0
    // No prefetch available, dummy it out.
    #define _mm_prefetch(a, sel) ((void)0)
