### ISSUE TITLE
Disable test_simd7 due to breakage

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3103]
Looks like

commit 112d26e53e79d53d99dc18f2823cd2a343847139
Author: Dan Gohman <sunfish@mozilla.com>
Date:   Thu Dec 18 11:42:11 2014 -0800

    Remove the SIMD signMask polyfill hack.

broke test_simd7. The commit makes it use signMask instead of signMaskPolyfill, and there isn't such a method, it appears.

cc @sunfishcode

**Comment by juj** [comment]
This is fixed in current incoming.
