### ISSUE TITLE
Sharing Embind Classes among Projects

### ISSUE THREAD

**Issue by Planeshifter** [kripken/emscripten#3110]
I have two projects which expose a C++ class to JS as a node.js module using Embind. Consider the following minimal example (the same happens with all other exported classes besides the vector wrappers):

Project1.cpp:
```cpp
#include <emscripten/bind.h>
using namespace emscripten;

EMSCRIPTEN_BINDINGS(my_module) {
  register_vector<int>("VectorInt");
}
```

Project2.cpp:
```cpp
#include <emscripten/bind.h>
using namespace emscripten;

int sum(std::vector<int> input){
  int sum_of_elems = 0;
  for(std::vector<int>::iterator j=input.begin(); j!=input.end(); ++j){
    sum_of_elems += *j;
  }
  return sum_of_elems;
}

EMSCRIPTEN_BINDINGS(my_module) {
  register_vector<int>("VectorInt");
  function("sum", &sum);
}

```

Using the second project, I am able to create vectors and calculate their sum, as in
```js 
var proj2 = require("./project2.js");
var x = new proj2.VectorInt();
for (var i = 1; i <= 3; i++){
  x.push_back(i);
}
console.log(proj2.sum(x));
```

which will print the correct result, 6. However, it is not possible to create an integer vector using via the first project and passing it to the `sum` function of the second one:

```js
var proj1 = require("./project1.js")
var y = new proj1.VectorInt();
for (var i = 1; i <= 3; i++){
  y.push_back(i);
}
console.log(proj2.sum(y));
```

This will result in the following error message:
`BindingError: Expected null or instance of VectorInt, got an instance of VectorInt`.

Apparently, the error is thrown because the constructor function of the vector is different from the expected one, as it lives in a different project. However, I would like to be able to pass JS objects created via one project to functions of another project. For example, I would like to transpile a linear algebra library to JS (armadillo) and  a machine-learning library (MLPACK) whose functions have armadillo vectors and matrices as parameters. Is this possible? 
Thanks in advance,
Philipp

**Comment by SBRK** [comment]
Hi @Planeshifter I know this topic is almost almost 9 years old, but I am myself trying to compile to wasm code that uses mlpack/armadillo, and so far I'm just pulling my hair out.

I know it's a bit different than transpiling the lib itself, but did you ever succeed ?

**Comment by jmarcosfer** [comment]
Also interested in this @Planeshifter, if you could provide some feedback on how you solved it (if you managed)
