### ISSUE TITLE
USE_SDL=2 fails with em++

### ISSUE THREAD

**Issue by Bigpet** [kripken/emscripten#3112]
If the `~/.emscripten_ports/sdl2` is not build yet then it will try to complie the `*.c` files in SDL2 as C++ which fails.

To reproduce delete the folder `~/.emscripten_ports/sdl2` and then do 

    touch empty.cpp
    em++ -s USE_SDL=2 empty.cpp

this will generate SDL2 compile errors (like disallowed implicit conversions between `bool` and the enum `SDL_bool`)

This is the same behavior that this user was experiencing: https://groups.google.com/d/msg/emscripten-discuss/mxZNrNgha9A/0no48whWAtgJ

**Comment by kripken** [comment]
Hmm, but how can you reach that state, except by manually breaking it by deleting that directory? If you do `emcc --clear-cache` and then build, does it not work (that should build all cached stuff including ports from scratch)?

**Comment by Bigpet** [comment]
Yes, the same thing happens with 

    emcc --clear-cache
    em++ -s USE_SDL=2 empty.cpp

**Comment by Bigpet** [comment]
Oh, I should be really a lot more explicit. 

This doesn't work : `em++ -s USE_SDL=2 empty.cpp`

This works `emcc -s USE_SDL=2 empty.c`

**Comment by kripken** [comment]
Ok, that looks like a bug with our c++ invocation handling affecting ports building. Should be fixed on incoming now, please verify.

**Comment by kripken** [comment]
Also added testing in 3af15fd320665f3c32e17ff27dac50257fe89b79

**Comment by Bigpet** [comment]
emscripten-incoming indeed fixed this for me (although compiling took quite a while)
