### ISSUE TITLE
Working with additional javascript libraries

### ISSUE THREAD

**Issue by fjallraven** [kripken/emscripten#3113]
This is a question and not an issue so apologies if this is posted in the wrong section.

Compiling with -O2
I have additional javascripts which is using jQuery.

Without adding jquery to "--js-library" emcc reports: "jQuery is not defined"

If I add jQuery: "TypeError: Object TypeError: Cannot call method 'createElement' of undefined"

Is js-library the best way of dealing with this scenario? Any other way of sourcing additional javascripts with -O2 enabled?

Thank you!

**Comment by kripken** [comment]
You can do `--pre-js jQuery.js`, which will include that file together with your code. (`--js-library` also assumes the file is in a specific format, an emscripten JS library, which jQuery isn't.)

**Comment by fjallraven** [comment]
Many thanks, working great
