### ISSUE TITLE
"unaligned array in packed struct" issue

### ISSUE THREAD

**Issue by wothke** [kripken/emscripten#3115]
As discussed in the forum I have created a testcase for my problem.

I am using emsdk for win32 (i.e. version 1.12). I compiled the below code using this WinXP batch script:

```javascript
setlocal enabledelayedexpansion

SET ERRORLEVEL
VERIFY > NUL

set "OPT=  -Wcast-align -fno-strict-aliasing -s VERBOSE=0 -s SAFE_HEAP=0 -s DISABLE_EXCEPTION_CATCHING=0  -DBLOODY_HACK -Wno-pointer-sign  -Os -O3"

call emcc.bat %OPT% -s TOTAL_MEMORY=33554432  testcase.cpp  -s EXPORTED_FUNCTIONS="['_alloc', '_main']"  -o test_packed.html && del test_packed.html
```
--------------------------------- testcase.cpp ----------------------------------------------------
```javascript
#include <emscripten.h>
#include <stdio.h>
#include <stdlib.h>    

#include <exception>
#include <iostream>
#include <fstream>
#include <array>


#ifdef EMSCRIPTEN
#define EMSCRIPTEN_KEEPALIVE __attribute__((used))
#else
#define EMSCRIPTEN_KEEPALIVE
#endif

// for some reason my old Emscripten version DOES NOT provide std:exception
// with its stdlib... if you are building with a better version then disable this 
// BLOODY_HACK
#ifdef BLOODY_HACK 
namespace std
{
exception::~exception() _NOEXCEPT
{
}

const char* exception::what() const _NOEXCEPT
{
  return "std::exception";
}
}
#endif

std::string toHex(unsigned char val)
{
	val = val&0xf;
	return std::string(1, val >= 10 ? (val - 10 + 'A') : val + '0');
}

void printHex(uint16_t in) {
	std::cout << toHex(in >>12) << toHex(in >>8) <<toHex(in >>4) <<toHex(in);
}

#define PACK_PRE
#define PACK_POST __attribute__((packed)) __attribute__((aligned(1)))
typedef uint16_t __attribute__((aligned(1))) a1_uint16_t;
typedef std::array<a1_uint16_t, 3>  a1_array_uint16_t __attribute__((aligned(1)));


PACK_PRE struct __attribute__((packed))  RawPattern
{
	a1_array_uint16_t  Offsets;
} PACK_POST;


#define OFFSET 21
const int size= OFFSET + 6;
unsigned char rawdata[size] = {	0,0,0,0,0,0,0,0,0,0,
								0,0,0,0,0,0,0,0,0,0,
								0x11,	// if this byte is used then something is wrong
								// the relevant data starts here									
								0x10, 0x00, 0x20, 0x00, 0x30, 0x00 };	 

unsigned char * unaligneddata;

extern "C" int main() __attribute__((noinline));
extern "C" EMSCRIPTEN_KEEPALIVE int main()
{
	std::cerr << "starting test" << std::endl;
	unaligneddata= (unsigned char*)malloc(size);	// get an aligned buffer so that the relavant data within will be unaligned
	memcpy(unaligneddata, rawdata, size);


    const RawPattern& pat = *((RawPattern*)(unaligneddata+OFFSET));

	std::cout << "First array element read from original buf: ";
	printHex(pat.Offsets[0]);	
	std::cout << std::endl;

	std::cout << "First array element read from aligned buf: ";
	const RawPattern copy= pat;
	printHex(copy.Offsets[0]);	
	std::cout << std::endl;

	return 0;
}
```

on my machine I am getting this output:
```javascript
starting test
First array element read from original buf: 1011
First array element read from aligned buf: 0010
```
i.e. when reading from the unaligned memory buffer the byte in front of the buffer is actually accessed

**Comment by kripken** [comment]
Building with `-s SAFE_HEAP=1`, this faults on `alignment error loading from address 5260141, which was expected to be aligned to a multiple of 2`.

I suspect that it is undefined behavior in C to do a C-style cast like that, of raw bytes into something with 16-bit values - even if it is marked as just having alignment 1. But, it does seem inconsistent for LLVM to not track the alignment, which it normally does well.

cc @sunfishcode - is this actually a bug in LLVM, do you think?

**Comment by wothke** [comment]
PS: From what I've read elsewhere I would expect that the "aligned(1)" should not really matter because it's supposed to be used to increase aligment requirements - not to relax them.

But the struct is "packed" and that alone tells the compiler that element values may not be aligned. Also it seems that the compiler has no problem generating code to access unaligned 16bit array content (I tried it by adding a 'char' in my test struct)... as long as the start of the struct is aligned it works, 

Apparently the code that I am trying to build has been previously used under various windows/linux and Android configurations. (I suspect that these might all have used CPUs that support unaligned memory access..)

**Comment by sunfishcode** [comment]
No, it's technically a bug in the code, though it's subtle. One of the
rules of packed structs is that you have to access them directly through
the packed struct type. In other words, you can't, in general, take the
address of a packed field and then access the field through that pointer,
because the pointer type won't reflect the packed attribute.

In the given testcase, this happens when methods are invoked on std::array.
The 'this' argument to the std::array functions is misaligned, but the
std::array functions themselves don't know this.

One way to fix this bug would be to replace usage of std::array with a
builtin array, as in:

typedef a1_uint16_t a1_array_uint16_t[3];

**Comment by wothke** [comment]
that explains it! thanks :-)

**Comment by sunfishcode** [comment]
One other random thought:

Part of the reason the behavior here is surprising is that the packed attribute does not participate in the type system in the same way that const or volatile do. The compiler issues an error if you try to implicitly convert from const T* to T*, but there's no analogous error for packed. This isn't Emscripten-specific though.
