### ISSUE TITLE
inline assembly support

### ISSUE THREAD

**Issue by skrana** [kripken/emscripten#3118]
Does Emscripten support inline assembly? I am getting error for "invalid output constraint =<gp>" whenever i use a general purpose register constraint on output parameter. Is there any other way to leverage SIMD instructions with emscripten. i am trying to convert a c project with inline assembly to javascript and hoping to leverage SIMD in generated code.

**Comment by kripken** [comment]
You can use EM_ASM to write inline JS, but not x86 or ARM or some other inline assembly.

For SIMD, you can use C intrinsics (see `system/include/emscripten/vector.h` and `*intrin.h`). There is a SIMD.js API that emscripten compiles those into. It is not fully implemented in browsers yet though.

**Comment by skrana** [comment]
Thanks, EM_ASM seems viable.
