### ISSUE TITLE
Optimize SSE1 partial load and store intrinsics

### ISSUE THREAD

**Issue by huningxin** [kripken/emscripten#3119]

**Comment by juj** [comment]
This was implemented in full in the PR above and can be closed?

**Comment by sunfishcode** [comment]
Actually, I had to temporarily disable this optimization, since it's causing #3123.

**Comment by huningxin** [comment]
Thanks for the testing. I've fixed the issues by https://github.com/kripken/emscripten/pull/3130 and verify them with test_sse1 and benchmark_sse1. Please take another look. Thanks.

**Comment by juj** [comment]
Currently we have the following:

    _mm_load_ss: emscripten_float32x4_load1
    _mm_loadl_pi: __builtin_shufflevector(emscripten_float32x4_load2(__p), __a, 0, 1, 6, 7)
    _mm_loadh_pi: __builtin_shufflevector(__a, emscripten_float32x4_load2(__p), 0, 1, 4, 5)
    _mm_store_ss: ((struct __unaligned *)__p)->__v = __a[0];
    _mm_storel_pi: emscripten_float32x4_store2(__p, __a);
    _mm_storeh_pi: emscripten_float32x4_store2(__p, __builtin_shufflevector(__a, __a, 2, 3, 0, 1));

so those look optimal in that sense, and this issue can be closed. The reason why `_mm_store_ss` looks peculiar is due to alignment. Issue #3737 is specifically for that.
