### ISSUE TITLE
SSE1 regressions in benchmark_sse1.py

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3123]
Running `python tests/benchmark_sse1.py` on current incoming gives the following regressions:

	TypeError: asm.js type error: double is not a subtype of floatish or doublelit benchmark_sse1_html.js:5:1888
	"pre-main prep time: 49 ms" benchmark_sse1_html.html:1245:12

	"{ "workload": 2097152, "results": [" benchmark_sse1_html.html:1233:12
	"{ "chart": "load", "category": "_mm_load_ps", "scalar": 1.947769, "simd": 0.546113 }" benchmark_sse1_html.html:1233:12
	",{ "chart": "load", "category": "_mm_load_ps1", "scalar": 1.947769, "simd": 47.754440 }" benchmark_sse1_html.html:1233:12
	"exception thrown: ReferenceError: SIMD_float32x4_loadX is not defined,nc@http://localhost:6931/benchmark_sse1_html.js:5:2384
	callMain@http://localhost:6931/benchmark_sse1_html.js:12:25672
	doRun@http://localhost:6931/benchmark_sse1_html.js:12:26494
	run/<@http://localhost:6931/benchmark_sse1_html.js:12:26662
	" benchmark_sse1_html.html:1245:12

	ReferenceError: SIMD_float32x4_loadX is not defined

**Comment by sunfishcode** [comment]
I fixed this by backing out the optimization in #3119.
