### ISSUE TITLE
Uncaught 5300312 (after successfully compiling libsass)

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3126]
I've compiled libsass using emscripten (1.8.2) without an error raised (but there were some warnings [1]). When [loading the compiled JS](http://medialize.github.io/sass.js/console.html), I get the following error thrown:

```
Uncaught 5300312      in libsass.js:1369
___resumeException    in libsass.js:6723
u9                    in libsass.js:1211
__ATINIT__.push.func  in libsass.js:1008
callRuntimeCallbacks  in libsass.js:1031
ensureInitRuntime     in libsass.js:8294
doRun                 in libsass.js:8311
run                   in libsass.js:8354
(anonymous function)
```
What's that code mean? how do I go about investigating this issue?

[1] warnings during emmake make:
```
sass_context.cpp:507:47: warning: use of logical '||' with constant operand [-Wconstant-logical-operand]
    catch (...) { return handle_errors(c_ctx) || 1; }
                                              ^  ~
sass_context.cpp:507:47: note: use '|' for a bitwise operation
    catch (...) { return handle_errors(c_ctx) || 1; }
                                              ^~
                                              |
sass_context.cpp:523:47: warning: use of logical '||' with constant operand [-Wconstant-logical-operand]
    catch (...) { return handle_errors(c_ctx) || 1; }
                                              ^  ~
sass_context.cpp:523:47: note: use '|' for a bitwise operation
    catch (...) { return handle_errors(c_ctx) || 1; }
                                              ^~
                                              |
sass_context.cpp:560:57: warning: use of logical '||' with constant operand [-Wconstant-logical-operand]
    catch (...) { return handle_errors(compiler->c_ctx) || 1; }
                                                        ^  ~
sass_context.cpp:560:57: note: use '|' for a bitwise operation
    catch (...) { return handle_errors(compiler->c_ctx) || 1; }
```

**Comment by juj** [comment]
Can you try compiling with latest Emscripten? The exception handling code has been updated several times since Emscripten 1.8.2, which is ancient by now.

**Comment by rodneyrehm** [comment]
darn. I did run the emsdk update earlier, but my env was still hard-wired to use the old version. go figure. After properly updating I'm getting a different error: `Uncaught could not load memory initializer libsass.js.mem`. I have not yet figured out what has changed in emscripten and what I need to change in my setup. I consider the original problem invalid, thus close this issue now. thank you!

**Comment by kripken** [comment]
The memory initializer is a `.mem` file with binary data that is generated along with the `.js` file, and should be in the same directory so it can find it.

**Comment by rodneyrehm** [comment]
yep, just found it in the [optimize code](http://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#memory-initialization) section. thank you! 

Something is still going wrong, though:

```
emcc -O2 lib/libsass.a -o lib/libsass.js -s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" -s DISABLE_EXCEPTION_CATCHING=0 --memory-init-file 0
/usr/local/bin/emscripten/clang/e1.27.0_64bit/llvm-nm: : Invalid data was encountered while parsing the file.
/usr/local/bin/emscripten/clang/e1.27.0_64bit/llvm-ar: error loading '/Users/rrehm/Projekte/test.dev/htdocs/medialize/sass.js/libsass/libsass/lib/libsass.a': Ran out of data reading vbr_uint for symtab offset!!
```

[full output](https://gist.github.com/rodneyrehm/46ba468aa8b56b8986ed)

**Comment by NekR** [comment]
> Uncaught 5300312

I'm getting same kind of error in `1.35.0`. Were there recently fixes regarding this thing? e.g. should I update to `1.36.*`?

**Comment by juj** [comment]
Does the uncaught exception message have a callstack? If not, we should probably first figure out why it doesn't have one in the print, because it would be best if we always were able to print out the callstacks. Here the exception number doesn't mean much, although if #4456 is fixed, it might possibly improve this, assuming libsass was using C++ exceptions.

If there is an call stack printed, but it is unreadable, try doing a -O0 build (or a -g2 build) to obtain a readable callstack.
