### ISSUE TITLE
The performance of SIMD.js benchmark decreases after upgrading to llvm 3.5

### ISSUE THREAD

**Issue by huningxin** [kripken/emscripten#3127]
When I use emscripten at https://github.com/kripken/emscripten/commit/d07af0a924ff248aaa3a4d9c9369c16070fe5377 of incoming branch to build benchcpp (https://github.com/PeterJensen/benchcpp), the performance of kernels except AverageFloat32x4 decrease significantly comparing to 1.28.3.

The initial investigation shows, e.g. for MatrixMultiplication kernel (https://github.com/PeterJensen/benchcpp/blob/master/matrix_multiplication.h), the `_mm_load_ps` should generate `SIMD_float32x4_load`, however emscripten generates 4 `HEAPF32[index]` loads with a 'SIMD_float32x4` constructor. And the `_mm_shuffle_ps` API generates the 'SIMD_float32x4` constructor with lanes access instead of `SIMD_float32x4_swizzle` or `SIMD_float32x4_shuffle`. 

@sunfishcode , any insights of this issue? Thanks!

**Comment by sunfishcode** [comment]
It looks like in the merge to LLVM 3.5, several PNaCl lowering passes which we don't want, including ExpandShuffleVectorPass, got accidentally re-enabled. We should disable them again.

**Comment by kripken** [comment]
It actually crashes for me when I do `emcc -O3 *.cpp` on benchcpp. Looking into this now. But I wonder why you two appear to see it compile ok, but run more slowly?

**Comment by kripken** [comment]
Ah, I should probably build with `-s SIMD=1`. But I still get a compile-time error,

````
  %19 = mul i128 %14, %18
llc: /media/alon/2f9a30d7-6124-42d9-87c5-3c80cb70ec54/home/alon/Dev/fastcomp/lib/Target/JSBackend/ExpandI64.cpp:549: bool {anonymous}::ExpandI64::splitInst(llvm::Instruction*): Assertion `I->getOpcode() == Instruction::LShr || I->getOpcode() == Instruction::AShr || I->getOpcode() == Instruction::Shl' failed.
````

How are you building?

**Comment by sunfishcode** [comment]
The code contains an odd construct which is triggering a very obscure bug in Emscripten. The patch in https://github.com/PeterJensen/benchcpp/issues/1 fixes the oddness, and also happens to sidestep the bug.

I have now filed https://github.com/kripken/emscripten/issues/3128 to track the actual bug in Emscripten.

**Comment by kripken** [comment]
Thanks, workaround works.

**Comment by sunfishcode** [comment]
I've disabled the unnecessary PNaCl lowering passes in 22a277c5f8a3d1dc58eb08ee8462c0372649795f.

**Comment by kripken** [comment]
(in fastcomp repo, https://github.com/kripken/emscripten-fastcomp/commit/22a277c5f8a3d1dc58eb08ee8462c0372649795f )

**Comment by huningxin** [comment]
It works for me. Thanks for the fix. I am closing this issue.
