### ISSUE TITLE
llvm-nm: "Invalid data was encountered while parsing the file."

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3137]
After upgrading emscripten emmake fails with the following error:

```
/usr/local/bin/emscripten/clang/e1.27.0_64bit/llvm-nm: : Invalid data was encountered while parsing the file.
/usr/local/bin/emscripten/clang/e1.27.0_64bit/llvm-ar: error loading '/Users/rrehm/Projekte/test.dev/htdocs/medialize/sass.js/libsass/libsass/lib/libsass.a': Ran out of data reading vbr_uint for symtab offset!!
```
this can be reproduced by

```bash
git clone https://github.com/medialize/sass.js.git sass.js
cd sass.js/libsass
/bin/bash build-libsass.sh 3.1.0
```

---

emscripten reports to be up to date:

```
➜  emsdk list
The following individual tools exist:
     *     clang-e1.27.0-64bit      	INSTALLED
     *     node-0.10.18-64bit       	INSTALLED
     *     emscripten-1.27.0        	INSTALLED

The following Emscripten SDK versions are available:
    *    sdk-1.27.0-64bit         	INSTALLED

➜  which clang
/usr/local/bin/emscripten/clang/e1.27.0_64bit/clang
➜  clang --version
clang version 3.3
Target: x86_64-apple-darwin12.5.0
Thread model: posix
```

**Comment by kripken** [comment]
Steps don't work for me,

````
patching file ./libsass/Makefile
Hunk #1 succeeded at 43 (offset -54 lines).
Hunk #2 succeeded at 97 with fuzz 2 (offset -71 lines).
Hunk #3 FAILED at 221.
1 out of 3 hunks FAILED -- saving rejects to file ./libsass/Makefile.rej
````

But anyhow, which file does it fail on? What command is being run?

**Comment by rodneyrehm** [comment]
yeah, that happens when you run `build-libsass.sh` without specifying the target version "3.1.0".
Anyway, here's the [full output](https://gist.github.com/rodneyrehm/46ba468aa8b56b8986ed)

**Comment by kripken** [comment]
Oh, sorry. Ok, I did it again in a fresh checkout. It works for me on 1.29.3, https://gist.github.com/kripken/8c1355af6e444fccb4bb Perhaps try on latest emscripten?

If that doesn't help, seeing your output with `EMCC_DEBUG=1` in the env (like in my gist) might help.

**Comment by rodneyrehm** [comment]
Since my MacBook died on Monday I've moved to a new system and installed emscripten via homebrew `brew install emscripten --HEAD` and I'm happy to report compilation succeeded.

Maybe thinking about how to make the version / env more accessible / debuggable would help avoid these, arguably stupid, questions in the future? `emmake --version` doesn't do anything useful, I've no idea what version is installed right now and there is no `emsdk` to check…

**Comment by kripken** [comment]
`emmake` is just a `make` wrapper. run `emcc --version`

**Comment by rodneyrehm** [comment]
see what I mean by "stupid questions"? thanks! I'm running `emcc (Emscripten GCC-like replacement) 1.29.4` and the compiled JavaScript works fine! 

Thank you!
\o/
