### ISSUE TITLE
Initialization of union with bitfields causes optimizer to fail

### ISSUE THREAD

**Issue by dreamlayers** [kripken/emscripten#3142]
The following thing causes the optimizer to fail when compiled with `em++ -O2 breakcpu.cpp -s EXPORT_ALL=1 -o breakcpu.js` using 1.29.3 7e894e0. It is based on DOSBox src/cpu/cpu.cpp plus relevant parts of include/cpu.h. This is not a problem for DOSBox, because it works without `EXPORT_ALL=1`, which I do not need.
```C++
typedef unsigned int Bit32u;

struct S_Descriptor {
	Bit32u limit_0_15	:16;
	Bit32u base_0_15	:16;
	Bit32u base_16_23	:8;
};

class Descriptor
{
public:
	Descriptor() { saved.fill[0]=saved.fill[1]=0; }
	union {
		S_Descriptor seg;
		Bit32u fill[2];
	} saved;
};

Descriptor desc;
```

**Comment by kripken** [comment]
Thanks, fixed. fastcomp was not sanitizing LLVM names for the export list.
