### ISSUE TITLE
After longjmp, setjmp on the same jum_buf would create a new item in jump table

### ISSUE THREAD

**Issue by xxuejie** [kripken/emscripten#3151]
Sorry I'm here to report a (maybe) bug on setjmp again...

First of all, [here](http://cl.ly/3u2m012J0R0I) is an archive containing bitcode, JS file(with a few console.log debug line I added) and the log file generate. To create JS from bitcode, run:

```
emcc mrbtest.bc -o mrbtest.js -s TOTAL_MEMORY=33554432 -O0 -s MAX_SETJMPS=700
```

The `MAX_SETJMPS` set is needed, otherwise errors would occur(which I guess may due to the bug here).

The problem happens in `mrb_context_run` function, this function mainly works like this:

```
jmp_buf buf;
RETRY_BLOCK:
if (setjmp(&jmp_buf) == 0) {
  // may call longjmp here
} else {
  goto RETRY_BLOCK;
}
```

This is the main loop for the mruby interpreter, whenever some function throws a Ruby exception, longjmp may be called, then we will go back to RETRY_BLOCK and do setjmp again.

The problem is: based on my assumption(please correct me if this is wrong), each time we called [_saveSetjmp](https://github.com/kripken/emscripten/blob/master/src/library.js#L5785) in emscripten with the same `jmp_buf`, we should be able to locate the same item in `setjmp_table` and reuse it. However, as we can see from the log file attached, this is not the case right now:

```
setjmp in mrb_context_run cjmp:  404856  table:  405024
setjmp id:  3  table:  405024  i:  0
(contents skipped...)
Longjump:  404856
setjmp in mrb_context_run cjmp:  404856  table:  405024
setjmp id:  24  table:  405024  i:  1
Longjump:  404856
setjmp in mrb_context_run cjmp:  404856  table:  405024
setjmp id:  26  table:  405024  i:  2
(contents skipped...)
Longjump:  404856
setjmp in mrb_context_run cjmp:  404856  table:  405024
setjmp id:  42  table:  405024  i:  8
(contents skipped...)
Longjump:  404856
setjmp in mrb_context_run cjmp:  404856  table:  405024
setjmp id:  1735  table:  405024  i:  600
```

Each time we call `setjmp` immediately after due to a `longjmp`(the goto RETRY_BLOCK in the code), we will create a new item in the `setjmp_table`. This will eventually lead to `too many setjmps in a function call, build with a higher value for MAX_SETJMPS` errors.

So, can we consider this a bug? Any chance we can fix it?

Thanks a lot!

**Comment by xxuejie** [comment]
I manage to narrow everything down to a single file, if that helps:

```
#include <stdio.h>
#include <setjmp.h>

void work(int *x, jmp_buf env){
  (*x)++;
  longjmp(env, 1);
}

int loop() {
  jmp_buf env;
  int x = 0;
  const int ITERATIONS = 100;
RETRY_BLOCK:
  if (setjmp(env) == 0) {
    if (x >= ITERATIONS) {
      return x;
    }
    work(&x, env);
  } else {
    goto RETRY_BLOCK;
  }
  return -1;
}

int main()
{
  printf("Result: %d\n", loop());
  return 0;
}
```

**Comment by kripken** [comment]
Thanks for the testcase. I rewrote some of the setjmp support to remove the need for MAX_SETJMPS, it will now grow the space dynamically. This adds a little overhead but I guess it's better to do it that way, than to make it fail on things like this. Please verify if it now works.

**Comment by xxuejie** [comment]
The testcase now passes, thanks for the help!

However, in the above test case, after a longjmp, a new item will be created in the `setjmp` table, even if we are calling on the same `jmp_buf`. Is there any limitation that we have to do this way? I'm worried in the long run, this may lead to a memory leak.

On the other hand, I can see that at [here](https://github.com/kripken/emscripten/blob/master/src/library.js#L5786) you mentioned that `setjmp` prevents relooping and is not fast. If I want to replace `setjmp` with some other control mechanisms, what do you recommend here? Will it help by switching to C++ exceptions?

Thanks again for your generous help!

**Comment by kripken** [comment]
It won't reuse the "slots" on the stack for setjmps. In theory that could be optimized, but it would slow down the common case, I suspect - not many people do multiple setjmps on the same stack frame. But, in any case it won't leak them, just they will be wasted until that function returns and the stack frame is unwound.

That comment is out of date. Currently C++ exceptions and setjmp should be of similar speed, setjmp perhaps being a little faster.

**Comment by xxuejie** [comment]
Okay, that makes sense. My original worry is that if the code continues executing in `mrb_context_run` and does not exit, this may waste memory to create a lot of stack frame, but a second thought is that it has to exit after some time, otherwise browser would complain about unresponsive scripts :)

Thanks again for the help! I will close this issue in this case.

**Comment by kripken** [comment]
Yeah, browsers require you to exit frequently anyhow, otherwise this could be a problem.

Btw, thanks as always for the nicely-written testcases.
