### ISSUE TITLE
glGenTextures can incorrectly return GL_INVALID_VALUE

### ISSUE THREAD

**Issue by mlogan** [kripken/emscripten#3163]
Since glGenTextures (`library_gl.js`) returns a monotonically increasing id, it will eventually return 0x0501, which is the value of GL_INVALID_VALUE.

It seems that the correct fix is to skip GL_INVALID_VALUE in `getNewId()` in `library_gl.js`, but I'd like confirmation on that before I take the time to write a patch.

**Comment by juj** [comment]
The namespace of texture IDs is not the same as the namespace of GL errors. `glGenTextures` does not return GL error codes in the output array and it is incorrect to test the generated IDs against GL error codes. Instead use glGetError() to test for errors from `glGenTextures`. The value `0x0501` is a valid identifier for a GL texture ID.

**Comment by mlogan** [comment]
Ah, I misread https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGenTextures.xml

Thanks!
