### ISSUE TITLE
Canvas API to render text into WebGL texture

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3175]
Hi,
I am about to port a small OpenGL ES 2.0 / WebGL 1.0 application from JavaScript to C++ to be compiled via emscripten, and I was wondering how to access the Canvas API under emscripten to render text into a texture, as that seems to be the definite way of doing that in WebGL.
And glTexImage2d also takes a canvas element as parameter from which it will blit its content into the OpenGL texture.
I just don't know how to do it with emscripten's API, though, as the documentation also does not seem to contain a canvas API.

**Comment by juj** [comment]
I am not aware of any codebases out there that would use Canvas2D to rasterize fonts and then move those over to WebGL textures, although that is certainly doable. The common solution is to use either FreeType, see http://www.freetype.org , or offline pregenerated font textures. That has the advantage that font rasterization will be guaranteed to occur identically across all browsers and native code, so the code path is bug-free from browser-specific glitches and has similar performance footprint across each.

If you want to use the JS canvas 2D API with Emscripten, you'll want to just write JS code that you embed as a --js-library to the main application, and perform the calls normally like you would do in JavaScript. Marshalling the data over to WebGL will possibly involve interacting with the `src/library_gl.js` file or by moving the canvas pixels over to the Emscripten heap and using the C GLES2 API to perform the text upload.

**Comment by httpdigest** [comment]
Thank you very much for your answer. Just for your information, the Babylon.js framework does text rendering like that with the canvas 2d API.
I will use an C-external JavaScript function then. Thanks!
