### ISSUE TITLE
Ver 1.29 crash on IE11

### ISSUE THREAD

**Issue by GregSlazinski** [kripken/emscripten#3180]
Hi,

Since I've updated to Emscripten 1.29 from 1.21, I started having this error on IE11 (Chrome/Firefox work ok)
![capture-1](https://cloud.githubusercontent.com/assets/7143443/6139847/76a0911a-b1f5-11e4-9cc4-0ec7712e5410.png)

This was compiled with 1.21 - http://esenthel.com/App/Web%20App.html (works ok)
This was compiled with 1.29 - http://esenthel.com/App/Web%20App2.html (crashes on IE11)

**Comment by kripken** [comment]
This is a memory-growth specific problem, looks like. The q() called there
is generated by

#if ALLOW_MEMORY_GROWTH
var byteLength;
try {
  byteLength =
Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,
'byteLength').get);
} catch(e) { // can fail on older node/v8
  byteLength = function(buffer) { return buffer.byteLength; };
}
#endif

in src/preamble.js

Can you please see if adding a line inside the try, like, this, fixes it?

try {
  byteLength =
Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,
'byteLength').get);
  byteLength(new ArrayBuffer(4)); // this is the new line
} catch(e) { // can fail on older node/v8

(I don't have an IE11 machine here to test on.)

- Alon

**Comment by kripken** [comment]
Fixed on incoming, based on confirmation from the mailing list.
