### ISSUE TITLE
Building fastcomp from source fails with Visual Studio 2015 Preview

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3184]
I just tried to follow http://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_using_the_sdk.html to build emscripten from source. I have cmake 3.1.2 and git installed and it's in %PATH%.
Now I wanted to build emscripten with Visual Studio 2015 Preview, so I entered the "Developer Command Prompt for VS2014" (2014 is actually 2015..., because the internal version of Visual Studio 2015 is VS.14....)

I first tried it with:
  emsdk install sdk-incoming-64bit
and after it downloaded fastcomp it failed with the following message:

Running CMake: ['cmake', '-G', 'Visual Studio 12 Win64', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF',
NG_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_TESTS=OFF', .... 'somepath/clang/fastcomp\\src']
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:19 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:19 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!

Why does it use the "Visual Studio 12 Win64" cmake generator, when it should be using "Visual Studio 14 2015 Win64"? I tried using Visual Studio 2015 on several other C projects, like glfw, and that detects VS2015 just fine and generates the config files using it.

Then, I read that warning notice to use under Windows instead this:
  emsdk install clang-incoming-64bit node-0.10.17-64bit python-2.7.5.3-64bit java-7.45-64bit emscripten-incoming

That gave me the exact same errors as above.

What could be the issue there?
Thanks!

**Comment by juj** [comment]
The issue is that Visual Studio 2015 Preview is not supported, and emsdk does not attempt to build using this unsupported compiler.

You may try hacking the `emsdk` script to force your custom make generator, but success is not guaranteed.

**Comment by httpdigest** [comment]
I thought cmake would abstract away all that nitty-gritty details of how to support a new compiler, so that a user building a cmake makefile does only use the abstract constructs provided by cmake, which are not specific to a certain compiler? And cmake does support VS 2015.
But I did not know that even with using cmake one still has to also explicitly support a specific compiler.
Thanks.

**Comment by juj** [comment]
Yes it does, but it does not mean that cmake would be able to make the right choice. I believe cmake's detection logic is simply "use the latest one available". For a long while, LLVM did not support building with VS2012 or newer, but cmake does not know that, so one must disable the cmake auto detection for that case. `emsdk` build script limits to building with tested compilers only, which are VS2013 and VS2012, and prefers them in that order.

**Comment by httpdigest** [comment]
Okay, thank you for the clarification. I will use VS2013 then.
