### ISSUE TITLE
Option to load memoryInitializer from a typed array?

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#3187]
We're loading memoryInitializer ourselves because we want to integrate it into our progress bar. I wrote a simple --js-transform that swaps in our Uint8Array and bypasses the built-in HTTP fetch, but I just learned that custom transforms disable source maps. Is there a supported way to load the memory file from an existing typed array?

**Comment by kripken** [comment]
Hmm, wouldn't it be simpler to use the tracking hooks already in emscripten? When the memory init file arrives, we call removeRunDependency, which will call `Module['monitorRunDependencies']` (if defined). You can use that to tell your progress bar what to show.

We could add the name of the dependency as a parameter to that callback, then you would get called with `'memory initializer'` and would have a clear signal of when it arrives?

**Comment by evanw** [comment]
We are downloading both the js and the mem files in parallel for speed. So the js file isn't around yet. In fact, the js file is bigger than the mem file so the mem file finishes first. The approach you're describing would serialize the downloads and make them take longer.

**Comment by kripken** [comment]
Got it. Well, let's add an option for this, sounds like it would generally useful. How about if `Module.manualMemoryInitializer` is set, then we don't autoload it, and you can manually call `Module.applyMemoryInitializer` with the typed array?

**Comment by kripken** [comment]
cc @chadaustin as this is related to the irc discussion about how you handle memory inits.

**Comment by evanw** [comment]
It seems simpler for our use case just to let Module.manualMemoryInitializer be the memory:

```
function load(code, memory) {
  var script = document.createElement('script');
  script.textContent = code;
  Module = { manualMemoryInitializer: memory };
  document.body.appendChild(script);
}
```

Assigning true to Module.manualMemoryInitializer and then calling Module.applyMemoryInitializer() makes sense, except you would then need to delay calling main() and that doesn't seem to work right now. You can assign true to Module.noInitialRun but that permanently breaks Module.run() due to issue 1396. It looks like the intent of Module.noInitialRun is that you can assign true to shouldRunNow before calling Module.run() to run main() at a later time, but that doesn't work after minification since closure compiler renames shouldRunNow to some random two-letter name.

**Comment by kripken** [comment]
But in that case, you need the memory before you start to load the script? i.e. you can't download them in parallel?

**Comment by kripken** [comment]
I think the best approach here is to provide a *request*. This could be just an xhr, or it could be an object that happens to look like one. This gives maximum flexibility, and also handles the corner cases of the mem init file arriving earlier, or later, than other stuff. See above commit, let me know what you think.

**Comment by evanw** [comment]
We're actually caching our files locally using the HTML5 FileSystem API at the moment. That should still work with your commit though, as long as we wrap it in an object with a "response" property. Thanks for the quick fix!

I'm not sure what you meant about not being able to download the resources in parallel. If our cache is out of date, we just do two parallel XHRs, then inject a script element into the DOM containing the downloaded code and pass it the downloaded memory in a global variable.

**Comment by kripken** [comment]
Oh, I missed `textContent` before, now I see.

Just fyi, FileSystem is not a standard API (and won't be standardized), and just works in chrome. IndexedDB is a better API as it works everywhere.

**Comment by evanw** [comment]
Yup, I know. I would love to use IndexedDB but I was having some intermittent data corruption issues with Firefox's IndexedDB implementation and haven't had time to look into it. We're using appcache for caching for non-Chrome browsers instead at the moment. Definitely not ideal :)

**Comment by kripken** [comment]
I saw IndexedDB corruption myself recently - what I saw seems to be caused by moving with a single profile between versions of Firefox. It's being fixed, but a new profile (or one per version) would work around it

**Comment by kripken** [comment]
Btw, any chance you'll have time to look into that IndexedDB error? We should try to file a bug report so it can get fixed. (If you don't have time, but are ok with sending a zip of your profile dir, that would also be enough to file a bug.)

**Comment by evanw** [comment]
That sounds like probably what was happening to me. I test in both Firefox and Nightly so it's very likely that Nightly messed up my profile. Chrome has separate user profiles for its stable and development builds, which is definitely the way to go in my opinion.

I don't have time to try to reproduce the issue at the moment and that corrupted user profile is long gone. I was experiencing these issues many months ago and our code base has changed significantly since then too, so I'm not even sure I could reproduce it. Thanks for the offer though! I'll definitely follow through if it comes up again.
