### ISSUE TITLE
Simple CMake under Windows not finding size_t

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3190]
I have been trying to build a very simple CMake-based build with Emscripten under Windows so far without success.

I have a single C++ library using OpenGL header GL/gl.h.
To make things simple I used the very simple CMakeLists.txt file:

cmake_minimum_required(VERSION 2.8)
project(mylibrary)
file(GLOB mylibrary_SRC
    "*.h"
    "*.cpp"
)
add_definitions(-DGLM_FORCE_PURE)
add_library(mylibrary STATIC ${mylibrary_SRC})
target_include_directories(mylibrary PRIVATE .)

When I create a folder "built" and invoke inside it "cmake .." the .sln solution file gets created correctly and MSBuild on it builds fine and creates a .lib file using msvc.

When I now however just use: emconfigure cmake .. -G "MinGW Makefiles"
(I also used emcmake instead of emconfigure before, but it was told somewhere that I should be using emconfigure instead)
some Makefile is generated with the output being:

-- Configuring done
-- Generating done
-- Build files have been written to: somepath/built

This is the only output. The output from the .sln configure was substantially larger.

Now, when I do "emmake make" I get the output:

somepath/somefile.h:17:14: error: unknown type name 'size_t'

Does it not include the Emscripten system header files there?

Thanks for any help!

**Comment by juj** [comment]
Without knowing the code, I guess you are missing an include, or an include is being taken from somewhere else incorrectly. http://en.cppreference.com/w/c/types/size_t lists headers where `size_t` can be found in. Try including one or more of those files to see if it resolves the problem.

**Comment by httpdigest** [comment]
Wow. I feel so stupid right now... Have included stdint.h and now it is working....
Makes me feel a bit angry about msvc always defaultly including all of that stuff without me knowing. :)
Thank you for your help, again.. :)
Now it creates the BC files correctly and also the .a file.
