### ISSUE TITLE
Sample programs on tutorial are not C++

### ISSUE THREAD

**Issue by gregoire-astruc** [kripken/emscripten#3201]
On the *[Getting Started](https://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html)* tutorial page, the sample programs are not C++: they are plain C.

Possible fixes:

- replace C++ by C, leave the program unchanged.
- change headers `<stdio.h>` to `<cstdio>`

**Comment by juj** [comment]
Should be clearer after the above commit.
