### ISSUE TITLE
Improve error message when attempting to run with unsupported python 3 version.

### ISSUE THREAD

**Issue by ddyer0** [kripken/emscripten#3216]
I installed enscriptin on windows using the installer.  From all appearances, nothing
works.  After a little investigation, I found that my default python 3.4 (in my system path)
was taking precedence over the python 2.7 in the installed software.   For some reason,
python 3.4 doesn't work.  Most likely it's easy to fix, but lacking that, checking for it and
complaining in a friendly way would help the next novice. 

Removing python 3.4 from my system path got me off square 1.
## 

Setting environment variables:
EM_CONFIG = C:\Users\Ddyer.emscripten

C:\Program Files\Emscripten>emcc -v
  File "C:\Program Files\Emscripten\emscripten\1.29.0\emcc", line 147
    ''' % (open(shared.path_from_root('site', 'build', 'text', 'docs', 'tools_reference', 'emcc.txt')).read())
      ^
SyntaxError: invalid syntax

C:\Program Files\Emscripten>which python
c:\programs\python3.4\python.EXE

C:\Program Files\Emscripten>

**Comment by juj** [comment]
Supporting python 3 is from what I understand quite a bit of work, and not a small transformation. I recall it was investigated briefly by a contributor roughly a year ago, and I think the conclusion was that it's more work than worth. If someone has more insight to this matter though, let's discuss it here.

**Comment by ddyer0** [comment]
Re: python 3;  You should either allow it, or avoid it and use the version you like explicly,
or reject it explicitly.  Just crashing and burning is not a good state of affairs.

**Comment by juj** [comment]
Agreed. Let me reopen with updated title.

**Comment by meawoppl** [comment]
That random contributor is me!  It is indeed quite a chore to get emscripten py3k compliant for three reasons:
 * The unittests used to be quite hard to setup and run (now possibly much smoother with buildbot)
 * There was some talk about needing to continue to support 2.6, which adds more friction that you would anticipate.
 * Its a really big piece of code!  Just cleaning up all the print statements took me the better part of a day :)  

At the very least it should pop a warning if sys.version > (2, 7) as a hint.  Let me throw in a quick PR for this to get back in the swing of working in this repo!

**Comment by sbc100** [comment]
IIUC we now support python
