### ISSUE TITLE
The output sequence is wrong.

### ISSUE THREAD

**Issue by PinZhang** [kripken/emscripten#3227]
The sample codes is here:
```c
#include <stdio.h>                                                                                                                                             
#include <emscripten.h>
int main() {
  printf("output1");
  EM_ASM(
    console.log('output2');
  );
}
```
After compiling and runing:
```
$ emcc test.c
$ node a.out.js
```
the output is:
```
output2
output1
```

but if we print `output1` with `\n`:
```c
printf("output1\n");
```
then the result is right:
```
output1
output2
```

**Comment by croes** [comment]
This is expected C++ behavior, the `stdout` stream is buffered. It only flushes when it reaches a newline character. For more information, see [this StackOverflow question](http://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin).

**Comment by PinZhang** [comment]
@croes  thanks for your information.
