### ISSUE TITLE
Feature request for file_packager.py to produce immutable JS output file

### ISSUE THREAD

**Issue by weitjong** [kripken/emscripten#3232]
First, sorry for my bad English. Currently the packager tool seems to produce package with unique UUID each time. As I understand it, the package UUID, the corresponding data file names (that the taget package contained) and their files sizes are then substituted into the template JS file to generate the JS output file by the packager. This has caused the JS output file to be mutable. Since the JS output file is supposed to be ```--pre-js``` into the final HTML file in the link phase, a mutable JS output file would in turn cause a re-link unnecessarily.

An immutable JS output file is possible, I think, when those variables that currently being substituted into the template are stored externally in the target package file itself instead. The start of the target package file could be reserved for storing such metadata. The first few bytes for package UUID, followed by number of data files, and their names and sizes. The JS output file could then be programmed to fetch this metadata to decide whether the local cache is good or new data requests need to be made to fetch further from the target package. In summary, the metadata that are unique to the package are stored in the package itself; the JS output file is immutable to the metadata changes.

I am neither familiar enough with Emscripten nor proficient in python scripting, so I can only raise this feature request as an issue, instead of contributing it as a PR. Let me know if I need to explain my idea further or that you need to have a concrete use case for this. Thanks.

**Comment by kripken** [comment]
If your goal is to avoid a re-link, you can achieve that by running the file packager separately. Just run `tools/file_packager.py` to generate the js and binary files, and then load the js in your HTML file in a script tag, before the main compiled project. See http://kripken.github.io/emscripten-site/docs/porting/files/packaging_files.html?#packaging-using-the-file-packager-tool

**Comment by weitjong** [comment]
Thanks for the response. I have already read and followed the instruction on the page that you link to invoke the file_packager.py separarately and to use the js file in the link phase. In fact we have used this approach to share the same binary file by linking the same js file to multiple sample-app targets in our project. It all works beautifully, except that one minor hiccup that I reported in this issue. That is, re-invocation of the file_packager.py would result in both js and binary files to have new package UUID (among other metadata changes). Actually any change in the js file timestamp is sufficient to trigger a relink on these multiple sample-app targets. However, I feel that some of the relink is unnecessary and can be avoided. For example, if I just change a single pixel color of a texture file then only the shared binary file need to be updated when all the metadata is self-contained in the binary file itself. Currently this example would change the js file and it's timestamp and the build system detects that and relink dutifully.

**Comment by weitjong** [comment]
> and then load the js in your HTML file in a script tag, before the main compiled project. 

Hi Alon. Sorry for not reading your reply properly the first time. I think you want me to try to *manually* insert the script tag in front of the ```{{{ SCRIPT }}}``` instead of using ```pre-js``` as normal. Actually I have already tried that "hack" too :). Although it works, I don't think it is a proper solution and decided to raise it as an issue upstream.

We can also see this issue differently. We can see it in a more general way. The Makefile rule triggering a relink is not the actual problem here when emcc is smart enough to realize that the re-generation of the compiled code is not necessary in this case. Take the following CMake-generated Makefile rule, for example:
```
*In build.make*
bin/21_AngelScriptIntegration.html: Source/Samples/21_AngelScriptIntegration/CMakeFiles/21_AngelScriptIntegration.dir/AngelScriptIntegration.cpp.o
bin/21_AngelScriptIntegration.html: Source/Samples/21_AngelScriptIntegration/CMakeFiles/21_AngelScriptIntegration.dir/build.make
bin/21_AngelScriptIntegration.html: lib/libUrho3D.a
bin/21_AngelScriptIntegration.html: Source/shell.html
bin/21_AngelScriptIntegration.html: bin/Urho3D.js
bin/21_AngelScriptIntegration.html: include/Urho3D/ThirdParty/JavaScript/libraries/as_callfunc_emscripten.js
bin/21_AngelScriptIntegration.html: Source/Samples/21_AngelScriptIntegration/CMakeFiles/21_AngelScriptIntegration.dir/link.txt
    @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../../../bin/21_AngelScriptIntegration.html"
    cd /home/weitjong/SDKs/urho3d/emscripten-Build/Source/Samples/21_AngelScriptIntegration && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/21_AngelScriptIntegration.dir/link.txt --verbose=$(VERBOSE)

*In link.txt*
/home/weitjong/SDKs/emsdk_portable/emscripten/master/em++    -Wno-invalid-offsetof -ffast-math -m32 -Wno-warn-absolute-paths -Wno-unknown-warning-option -O3 -DNDEBUG  -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s TOTAL_MEMORY=33554432 -s USE_SDL=2 --shell-file /home/weitjong/SDKs/urho3d/emscripten-Build/Source/shell.html --pre-js /home/weitjong/SDKs/urho3d/emscripten-Build/bin/Urho3D.js --js-library /home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/ThirdParty/JavaScript/libraries/as_callfunc_emscripten.js -s AGGRESSIVE_VARIABLE_ELIMINATION=1 CMakeFiles/21_AngelScriptIntegration.dir/AngelScriptIntegration.cpp.o  -o ../../../bin/21_AngelScriptIntegration.html -rdynamic ../../../lib/libUrho3D.a -lGL
```
In this case, when only the pre-js file (Urho3D.js) or shell file or js-library file changes then IMHO the re-generation of the compiled code is not necessary during linking. Only when the object file or bytecode library file (libUrho3D.a) changes then it is necessary.

If this is doable then the relink would be fast for my above use case, and so it does not really matter anymore when file_packager.py producing mutable js file each time. The requested feature to have an immutable js file becomes just a nice to have though.

**Comment by kripken** [comment]
I guess I'm not sure why we have the UUID there. @modeswitch , do you remember?

**Comment by weitjong** [comment]
As stated earlier, I am not proficient with Python scripting. But from what I can understand in the file_packager.py script, the package UUID is used as some kind of metadata to invalidate the binary data cached in the indexedDB. Still, instead 'baked' that UUID in the js file, all the metadata should be fetched remotely as I proposed in the feature request above.

**Comment by weitjong** [comment]
Hi, I have just submitted a PR to implement my own feature request. I have to change my idea slightly. Instead of stuffing the metadata at the beginning of the package file, I store them in an external file. This is because I could not find a generic way just to read the metadata "chunk" out of the package file in xhr. It seems only FF support "moz-chunked-arraybuffer" at the moment.

**Comment by weitjong** [comment]
Closing this issue as the PR #3410 has been merged.
