### ISSUE TITLE
installation in Ubuntu 14.04: Inconsistency detected by ld.so: dl-version.c: 224

### ISSUE THREAD

**Issue by terios** [kripken/emscripten#3235]
so am trying to install emscriten in my Ubuntu 14.04. i followed to steps from the website, but when i execute this command : ./emsdk install latest

i get this result: 

Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!
CMake invocation failed due to exception!
Working directory: /home/terios/Bureau/emscripten/emsdk_portable/clang/fastcomp/build_master_64
Command '['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=Release', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_TESTS=OFF', '/home/terios/Bureau/emscripten/emsdk_portable/clang/fastcomp/src']' returned non-zero exit status 127
Installation failed!

**Comment by SkylarLeroy** [comment]
Can it help?

http://choorucode.com/2014/07/14/inconsistency-error-with-libgl-so/

**Comment by terios** [comment]
from the article you sent me it seems that they are talking about Nvidia graphic card ,my machine doesn't have an nvidia nor ati graphic card. does emscripten require some minimum configuration ?

for information, i would like to use emscripten on Tesseract OCR in order to be able to use it in the browser. (is this even possible ?)

**Comment by terios** [comment]
i found that to solve this issue you need to downgrade libselinux1 to 2.1.13-3 i will try it and keep you posted if anyone has this probleme.

**Comment by leoheck** [comment]
Good @terios, how is your progress downgrading the libselinux1? Did it work?

**Comment by juj** [comment]
Oh dear, this sounds annoying :(

@terios: do you have a command line to post here on what you did to do the downgrade? That would help if other people run into the same error.

**Comment by terios** [comment]
sorry, until now i didnt found a way to downgrade that library. am thinking you using another VM and see if the probleme is still there, 
also i have a question about emscripten, let say in a program i want to export to Javascript there are system command lines how does emscripten handel them ?

**Comment by juj** [comment]
Emscripten cannot handle the C `system("cmd");` function call in browser environment. It might be possible to emulate that in e.g. a node.js shell environment, but I don't think anyone has worked on that. Patches are welcome though.

**Comment by terios** [comment]
ok i also thought so. thank you for you help. i will keep you posted once i get something new.

**Comment by juj** [comment]
Sounds like this issue was resolved by apt-get workaround, so let me close this. Feel free to reopen or create a new issue for discussion on the other topics.
