### ISSUE TITLE
GLFW3 and LEGACY_GL_EMULATION=1 

### ISSUE THREAD

**Issue by SkylarLeroy** [kripken/emscripten#3242]
Hello,

My objective:
- Use glfw3 library for it's simplicity and well documented
- Use emcripten to build all in js for web

My problem:
- Find a clear way to do it

My questions:

- In order to compile this code https://github.com/IcyTesseract/Emscripten-GLFW3-Basic-Program these two options are needed:
 - USE_GLFW=3
   - Ok I see it used in the source code to branch ome js files
 - LEGACY_GL_EMULATION=1
   - As GLFW support Opengles 3 why should we use this option?
   - http://www.glfw.org/docs/latest/build.html

- Should I do a by hand directly with opengles creation?
  - I see many more exampleon in the Tests folder
  - If yes then it's nearly as close as to code it in native Opengles and the mobile devices NDK no?

Thank you all for your advices.

**Comment by juj** [comment]
The linker flag `-s USE_GLFW=3` should be passed when you want to use the GLFW 3 API. If that flag is not passed, Emscripten will link to the older GLFW2 API by default.

The linker flag `-s LEGACY_GL_EMULATION=1` is orthogonal to the GLFW flag. You can use any combination of those two. If your application code targets OpenGL ES 2.0, you do not need to pass the `-s LEGACY_GL_EMULATION=1` flag. If your code utilizes desktop OpenGL, especially with fixed pipeline or version 1.5 or older, then this linker flag will add some amount of emulation for that.

**Comment by SkylarLeroy** [comment]
Thank you so much for this explanation, better understanding now.
