### ISSUE TITLE
Non-fastcomp code should be removed

### ISSUE THREAD

**Issue by aidanhs** [kripken/emscripten#3243]
```
20:39 < brucem> azakai: when can we kill non-fastcomp and all related code?
20:40 < azakai> it's basically deprecated now, it's not being used. we could rip out the code if we have the time to do that
```

This is a tracking issue. I might start a bunch of PRs if I get chance.

**Comment by aidanhs** [comment]
Thoughts on a todo list:
 - [ ] Prevent people using non-fastcomp.
 - [ ] Eliminate references to `EMCC_FAST_COMPILER` in tests, by removing/modifying tests.
 - [ ] Eliminate references to `EMCC_FAST_COMPILER` in python code, simplifying where appropriate, and retaining informative errors when people try to use non-fastcomp.
 - [ ] Fix docs.

Longer term thoughts:
 - [ ] Look into simplification based on assuming `ASM_JS` is always > 0 (inspired by seeing `assert shared.Settings.ASM_JS > 0, 'ASM_JS must be enabled in fastcomp'`).
 - [ ] Check for other settings which don't work in fastcomp and make simplifications per above.
 - [ ] More thorough dead-code check.

I don't know what to do about TODOs found in the process (e.g. "TODO: this test doesn't work in fastcomp") - I guess we could retain them in this issue?

**Comment by kripken** [comment]
Sounds great.

Let's keep tests marked as not working in fastcomp, we should eventually make them work. Or, decide the functionality is not needed and remove them on a case by case basis.

**Comment by aidanhs** [comment]
Checked off first item on the list. Will let that cook in at least 1 release before continuing.

**Comment by aidanhs** [comment]
After some stumbles, second item done.

**Comment by aidanhs** [comment]
#3362 #3367 are targeting item 3.

**Comment by aidanhs** [comment]
@waywardmonkeys has very efficiently cut down the list to "minor cleanup remains".
Don't think we need an issue to track this any more :)
