### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3245]
cc @waywardmonkeys, @juj 

I am fairly sure we could run almost all tests in parallel now. The test suite has only fastcomp in it, and there should be no emscripten cache invalidations anymore. This could lead to massive speedups in bot times.

The only possible issue is use of `EMCC_DEBUG` which has a canonical temp dir. We use it sometimes like in `openjpeg` to peek through the code. We could perhaps refactor those things out to `test_other.py` (or somewhere else if we want to run `other` in parallel too).

Python's nosetests can run tests in parallel, so that might be an option here. If it has a "locking" feature for running certain tests not in parallel, that could be an easier solution to the last paragraph.

Otherwise, we could write a python script with a process pool that runs `default, asm1, asm2, asm3` etc. each in a separate process.

**Comment by kripken** [comment]
With that commit, only asm2g uses `EMCC_DEBUG` in the main test suite (`test_core.py`). I am pretty sure that means it is safe to run `default, asm1, asm2 etc.` in parallel, each in a separate process.

**Comment by kripken** [comment]
That commits adds a script that runs the core test modes in parallel, using all available cores. I ran for a short while and it looks fine, but I didn't do a full run yet.

**Comment by kripken** [comment]
I ran all the core test suite in an 1 hour and 20 minutes now. Run sequentially, on the same machine it takes 4 hours and 30 minutes.

**Comment by kripken** [comment]
@juj , would this be useful for the bots? If so, what form should the output be in? (Right now that script generates a separate `*.err` file for each mode.)

**Comment by juj** [comment]
This is definitely useful. I think it we need some kind of stdout output
from the processed, synced in some manner. Otherwise if there are no prints
in a long time, the run might time out.

**Comment by kripken** [comment]
Ok, the script now monitors the output files, and reports every second if the total output has increased. So if all builds are stuck, no output will happen, and otherwise we will get constant output to keep the bot alive. At the end when all builds are complete, the script stops the watcher and prints out all the outputs in sequence.

How is that?

**Comment by juj** [comment]
Oh, that looks neat, thanks for adding that! I'll work on migrating the bots to this once we get the current runs clear and the merge done.

**Comment by kripken** [comment]
Ok, merges are done. Let me know if I can help any more here. Looking forward to faster bot times with this :)

**Comment by kripken** [comment]
ping on this, just wanted to be sure you're not waiting on me for anything.

**Comment by juj** [comment]
Working on this now, see PR #3322.

**Comment by juj** [comment]
The bots are now running the default suite in parallel. Timings:

Before:
Windows - 6 hrs, 10 secs
OSX - 3 hrs, 35 mins, 4 secs
Linux - 4 hrs, 50 mins, 2 secs

After:
Windows - 2 hrs, 53 mins, 49 secs (-51.7%)
OSX - 53 mins, 57 secs (-74.9%)
Linux - 2 hrs, 26 mins, 16 secs (-49.6%)

The Windows bot is a Q3 2008 2.7GHz 4-core Core 2 Quad Q9400 (4 logical cores, no HT) with 4GB of RAM.
The OSX bot is a Late 2013 Mac Pro with 3.5 GHz 6-core Intel Xeon E5 (12 logical cores with HT) with 32GB of RAM
The Linux bot is a Q2 2012 Giada MiniPC 1.7GHz 2-core Core i5-3317U (4 logical cores with HT) with 4GB or RAM (http://www.giadapc.com/products/minipc/slim%20series/i53-i5.html)

Windows and OSX boxes have a SSD, the linux box has a spinning HDD. Looks very nice! It may be possible to run into issues with the potential quadratic job multiplication, e.g. if by bad scheduling it occurs that on the OSX bot 12*12 simultaneous processes get spawned and they hog all RAM, but unless we ever see that in practice, not really a thing to worry about.

I think at some point it may be worthwhile to make the logger be more intelligent and print the test results as they come in, but not critical at this point.

**Comment by juj** [comment]
The difference in Windows vs Linux bot times looks interesting, in singlethreaded it is 1 hr 10 minutes, and in multithreaded it is 27 minutes, both in favor of the Linux bot. Granted, the CPU on the Windows box is four years older than the Linux one, though comparing the CPU power in http://www.cpubenchmark.net/compare.php?cmp[]=1045&cmp[]=2066&cmp[]=816 suggests that the CPUs should be very similar in terms of performance, slightly in favor of the Q9400 on the Windows bot.

**Comment by kripken** [comment]
Nice!

Tiny surprise on the results. Linux speedup is as expected (2 cores, 2x speedup), Mac speedup is reasonable (6 cores, 4x speedup, linear speedup can't always be achieved...) but the Windows speedup of 2x given 4 cores is disappointing. But maybe that's just a windows issue, or something to do with the Python process pool on windows?

Anyhow, ~1 hour turnaround on the OS X bot should make a world of difference here! :)

**Comment by juj** [comment]
Oh note though that these reported times are just for the default suite, so there's still the `other.` (15 minutes on OSX bot) and `browser.` (17 minutes x 4) suites that take time, so OSX should finish in roughly 2 hours and 20 minutes of total time.
