### ISSUE TITLE
Test asm3i.test_globaldoubles fails on OSX and Windows.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3250]
Running the test asm3i.test_globaldoubles fails on OSX and Windows fails on both OS X and Windows bots, with the error

	======================================================================
	ERROR: test_globaldoubles (test_core.asm3i)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "G:\slaves\emcc\win-incoming\build\emscripten\tests\test_core.py", line 844, in test_globaldoubles
	    self.do_run_from_file(src, output)
	  File "G:\slaves\emcc\win-incoming\build\emscripten\tests\runner.py", line 470, in do_run_from_file
	    includes, force_c, build_ll_hook, extra_emscripten_args)
	  File "G:\slaves\emcc\win-incoming\build\emscripten\tests\runner.py", line 498, in do_run
	    raise e
	Exception: Expected to find 'BUG?
	Display: Vu=465.100000  Vv=465.200000  Wu=160.300000  Wv=111.400000' in 'BUG?
	Display: Vu=465.200000  Vv=465.200000  Wu=111.400000  Wv=111.400000
	 
	', diff:

	--- expected
	+++ actual
	@@ -1,2 +1,4 @@
	 BUG?
	-Display: Vu=465.100000  Vv=465.200000  Wu=160.300000  Wv=111.400000
	+Display: Vu=465.200000  Vv=465.200000  Wu=111.400000  Wv=111.400000
	+
	+

The failure occurs when building the globaldoubles.in code with `-O2 -s EMTERPRETIFY=1`, but `-O1 -s EMTERPRETIFY=1` does not exhibit the issue. A zip file of the Windows build results is at https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/globaldoubles/globaldoubles.zip if that is helpful, though the OS X system also generates the faulty compilation.

**Comment by juj** [comment]
I'm also seeing that on OSX, the test `test_constglobalstructs` fails with

	======================================================================
	ERROR: test_constglobalstructs (test_core.asm3i)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/Users/clb/slaves/emscripten/osx-incoming/build/emscripten/tests/test_core.py", line 2090, in test_constglobalstructs
	    self.do_run_from_file(src, output)
	  File "/Users/clb/slaves/emscripten/osx-incoming/build/emscripten/tests/runner.py", line 470, in do_run_from_file
	    includes, force_c, build_ll_hook, extra_emscripten_args)
	  File "/Users/clb/slaves/emscripten/osx-incoming/build/emscripten/tests/runner.py", line 498, in do_run
	    raise e
	Exception: Expected to find '*97,15,3,10*' in '*97,0,3,10*
	 
	', diff:

	--- expected
	+++ actual
	@@ -1 +1,3 @@
	-*97,15,3,10*
	+*97,0,3,10*
	+
	+

which I assume might be due to the same reason.

**Comment by kripken** [comment]
Very strange. A `HEAPF64[256]` seems to turn into `HEAPF64[128]`, and the next is just 4 above it, not 8. As if it parses `HEAPF64` as `HEAPF32` somehow (as 32 would indeed be half the size of the true pointer value, and the value size only of 4).

Perhaps there is a platform difference in `parseHeap` in `optimize.cpp`? I don't see how though. Perhaps adding some debug printouts there could help. Might also need them in the same method in `js-optimizer.js`.

Does the problem reproduce in `EMCC_DEBUG=1` or even better, `2`? That might help as well.

**Comment by juj** [comment]
I an not sure if this is a bug in optimizer? Because if I diff the bad and good output from building `tests/test_globaldoubles.in`, I see that the `test_globaldoubles.js.orig.js` are identical modulo choices for variable names (there seems to be some variables that are symmetrically renamed, e.g. other has `i10` and `i11` where the other has `i11` and `i10`, but the code is good) and it executes correctly.

To me the bug looks like it's somewhere in `tools/emterpretify.py`, since it is that pass that introduces the bug, after it takes `test_globaldoubles.js.orig.js` and turns it into an emterpreted version.

**Comment by juj** [comment]
Temp files from a build on Windows are available at https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/globaldoubles/emscripten_temp_test_globaldoubles.zip , which look all ok to me up until these final passes:

	running emterpretify on ['/home/clb/emsdk/emscripten/incoming/tools/emterpretify.py', 'test_globaldoubles.js', '/tmp/emscripten_temp/tmpHd_rigtmpIrcHJD.jsfunc_0.js.jo.js.jo.js.em.js', 'test_globaldoubles.js.mem', '[]', '[]', '[]', '0']
	DEBUG    root: saving original (non-emterpreted) code to test_globaldoubles.js.orig.js
	chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 48192 - 48192
	['node', '/home/clb/emsdk/emscripten/incoming/tools/js-optimizer.js', '/tmp/emscripten_temp/tmpGqbZz6.jsfunc_0.js', 'noPrintMetadata', 'findReachable']
	.
	chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 48192 - 48192
	['node', '/home/clb/emsdk/emscripten/incoming/tools/js-optimizer.js', '/tmp/emscripten_temp/tmpK89Jdy.jsfunc_0.js', 'noPrintMetadata', 'emterpretify']
	.
	DEBUG    root: finalizing emterpreted code
	DEBUG    root: applying js optimization passes: asm cleanup
	chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 51577 - 51577
	DEBUG    root: js optimizer using native
	['/home/clb/.emscripten_cache/optimizer.exe', '/tmp/emscripten_temp/tmpw_W_9P.jsfunc_0.js', 'asm']
	.
	running cleanup on shell code
	DEBUG    root: applying js optimization passes: asm last
	chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 49617 - 49617
	DEBUG    root: js optimizer using native
	['/home/clb/.emscripten_cache/optimizer.exe', '/tmp/emscripten_temp/tmpW9ax_v.jsfunc_0.js', 'asm', 'last']
	.
	DEBUG    root: emcc step "final emitting" took 0.86 seconds
	DEBUG    root: total time: 1.83 seconds

**Comment by kripken** [comment]
Yes, it's a bug in the emterpreter code, which is implemented using the (non-native) js optimizer.

**Comment by juj** [comment]
Oh right, by "optimizer" above I was just thinking about the new native optimizer executable, and not the js optimizer one.

The issue does reproduce with both `EMCC_DEBUG=1` and `EMCC_DEBUG=2`.

**Comment by kripken** [comment]
I should probably just ask you for direct login access to the bots, but if you don't mind, I think running on the bot where this fails with this patch will clarify exactly what's going on,

````
diff --git a/tools/js-optimizer.js b/tools/js-optimizer.js
index def32e0..4e591d8 100644
--- a/tools/js-optimizer.js
+++ b/tools/js-optimizer.js
@@ -6154,6 +6154,18 @@ function trample(x, y) { // x = y, by trampling it
 
 // Converts functions into binary format to be run by an emterpreter
 function emterpretify(ast) {
+
+  parseHeap = function(name, out) { // monkeypatch this for debugging purposes
+    out = out || parseHeapTemp;
+    if (name.substr(0, 4) != 'HEAP') return false;
+    out.unsigned = name[4] === 'U';
+    out.float = name[4] === 'F';
+    out.bits = parseInt(name.substr(out.unsigned || out.float ? 5 : 4));
+    out.type = !out.float ? ASM_INT : (out.bits === 64 ? ASM_DOUBLE : ASM_FLOAT);
+    printErr('parseHeap ' + [name, JSON.stringify(out)]);
+    return true;
+  }
+
   emitAst = false;
 
   var EMTERPRETED_FUNCS = set(extraInfo.emterpretedFuncs);
@@ -7223,11 +7235,11 @@ function emterpretify(ast) {
       stats.forEach(function(stat) {
         var before = freeLocals.length;
         var raw = getReg(stat, true);
-        //printErr('raw: ' + JSON.stringify(raw));
+        printErr('raw: ' + JSON.stringify(stat)); // raw => stat!
         releaseIfFree(raw[0]);
         if (freeLocals.length !== before) assert(0, [before, freeLocals.length] + ' due to ' + astToSrc(stat)); // the statement is done - n
         var curr = raw[1];
-        //printErr('stat: ' + JSON.stringify(curr));
+        printErr('stat: ' + JSON.stringify(curr));
         verifyCode(curr, stat);
         ret = ret.concat(curr);
       });
````

The debug output (in `EMCC_DEBUG=1` mode) should look like this

````
DEBUG    root: saving original (non-emterpreted) code to /tmp/emscripten_test_asm3i_3leGsF/src.cpp.o.js.orig.js
chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 44134 - 44134
.
chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 44134 - 44134
raw: ["var",[["i1"],["i2"],["i3"],["d4"],["d5"],["d6"]]]
stat: []
raw: ["stat",["assign",true,["name","i1"],["name","STACKTOP"]]]
stat: ["GETST",6,0,0,"SET",0,6,0]
raw: ["stat",["assign",true,["name","STACKTOP"],["binary","|",["binary","+",["name","STACKTOP"],["num",32]],["num",0]]]]
stat: ["GETST",6,0,0,"ADDV",6,6,32,"SETST",6,0,0]
raw: ["stat",["assign",true,["name","i2"],["name","i1"]]]
stat: ["SET",1,0,0]
parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
raw: ["stat",["assign",true,["sub",["name","HEAPF64"],["num",256]],["unary-prefix","+",["num",465.1]]]]
stat: ["SETVI",6,0,8,"SETVDD",7,0,0,154,153,153,153,153,17,125,64,"STOREF64",6,7,0]
````

The last 3 lines are the crucial bit. The `HEAPF64` access is parsed as 64-bit, and we read `HEAPF64[256]` so the `SETVI` has as the value there `0,8`, which is `low,high` bytes, so `2048`. Which is correct and equivalent to `HEAPF64[2048 >> 3]`.

But, in the bot, we get `1024`, not `2048`, for some reason (as I can see from looking through the emitted bytecode from the builds you sent). Either `parseHeap` failed, or something else, and we have `SETVI,?,0,4` instead.

**Comment by juj** [comment]
Ok, I applied the patch and ran `em++ test_globaldoubles.cpp -O2 -s EMTERPRETIFY=1 -o a.js`, which gives something quite different from your print

	DEBUG    root: emterpretifying
	running emterpretify on ['C:\\code\\emsdk\\emscripten\\incoming\\tools\\emterpretify.py', 'a.js', 'C:\\code\\emsdk\\.tmp\\emscripten_temp\\tmpeluoa7tmpumtxeb.jsfunc_0.js.jo.js.j
	, '[]', '[]', '[]', '0']
	DEBUG    root: saving original (non-emterpreted) code to a.js.orig.js
	chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 48192 - 48192
	chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 48192 - 48192
	raw: [-1,[]]
	stat: []
	raw: [0,["GETST",6,0,0,"SET",0,6,0]]
	stat: ["GETST",6,0,0,"SET",0,6,0]
	raw: [6,["GETST",6,0,0,"ADDV",6,6,32,"SETST",6,0,0]]
	stat: ["GETST",6,0,0,"ADDV",6,6,32,"SETST",6,0,0]
	raw: [1,["SET",1,0,0]]
	stat: ["SET",1,0,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["SETVI",6,0,4,"SETVDD",7,0,0,154,153,153,153,153,17,125,64,"STOREF64",6,7,0]]
	stat: ["SETVI",6,0,4,"SETVDD",7,0,0,154,153,153,153,153,17,125,64,"STOREF64",6,7,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["SETVI",7,4,4,"SETVDD",6,0,0,51,51,51,51,51,19,125,64,"STOREF64",7,6,0]]
	stat: ["SETVI",7,4,4,"SETVDD",6,0,0,51,51,51,51,51,19,125,64,"STOREF64",7,6,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["SETVI",6,8,4,"SETVDD",7,0,0,154,153,153,153,153,9,100,64,"STOREF64",6,7,0]]
	stat: ["SETVI",6,8,4,"SETVDD",7,0,0,154,153,153,153,153,9,100,64,"STOREF64",6,7,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["SETVI",7,12,4,"SETVDD",6,0,0,154,153,153,153,153,217,91,64,"STOREF64",7,6,0]]
	stat: ["SETVI",7,12,4,"SETVDD",6,0,0,154,153,153,153,153,217,91,64,"STOREF64",7,6,0]
	raw: [6,["SETVI",7,72,8,"EXTCALL",6,"_puts","ii",7,0,0,0]]
	stat: ["SETVI",7,72,8,"EXTCALL",6,"_puts","ii",7,0,0,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [2,["SETVI",6,4,4,"LOADF64",2,6,0]]
	stat: ["SETVI",6,4,4,"LOADF64",2,6,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [3,["SETVI",6,8,4,"LOADF64",3,6,0]]
	stat: ["SETVI",6,8,4,"LOADF64",3,6,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [4,["SETVI",6,12,4,"LOADF64",4,6,0]]
	stat: ["SETVI",6,12,4,"LOADF64",4,6,0]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["GETTDP",6,0,0,"SETVI",7,0,4,"LOADF64",7,7,0,"STOREF64",6,7,0]]
	stat: ["GETTDP",6,0,0,"SETVI",7,0,4,"LOADF64",7,7,0,"STOREF64",6,7,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",7,0,0,"STORE32C",1,7,0]]
	stat: ["GETTDP",7,0,0,"STORE32C",1,7,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",6,0,0,"LOAD32AV",6,6,4,"STORE32AV",1,4,6]]
	stat: ["GETTDP",6,0,0,"LOAD32AV",6,6,4,"STORE32AV",1,4,6]
	raw: [5,["ADDV",5,1,8]]
	stat: ["ADDV",5,1,8]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["GETTDP",6,0,0,"STOREF64",6,2,0]]
	stat: ["GETTDP",6,0,0,"STOREF64",6,2,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",6,0,0,"STORE32C",5,6,0]]
	stat: ["GETTDP",6,0,0,"STORE32C",5,6,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",7,0,0,"LOAD32AV",7,7,4,"STORE32AV",5,4,7]]
	stat: ["GETTDP",7,0,0,"LOAD32AV",7,7,4,"STORE32AV",5,4,7]
	raw: [5,["ADDV",5,1,16]]
	stat: ["ADDV",5,1,16]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["GETTDP",7,0,0,"STOREF64",7,3,0]]
	stat: ["GETTDP",7,0,0,"STOREF64",7,3,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",7,0,0,"STORE32C",5,7,0]]
	stat: ["GETTDP",7,0,0,"STORE32C",5,7,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",6,0,0,"LOAD32AV",6,6,4,"STORE32AV",5,4,6]]
	stat: ["GETTDP",6,0,0,"LOAD32AV",6,6,4,"STORE32AV",5,4,6]
	raw: [5,["ADDV",5,1,24]]
	stat: ["ADDV",5,1,24]
	parseHeap HEAPF64,{"unsigned":false,"float":true,"bits":64,"type":1}
	raw: [-1,["GETTDP",6,0,0,"STOREF64",6,4,0]]
	stat: ["GETTDP",6,0,0,"STOREF64",6,4,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",6,0,0,"STORE32C",5,6,0]]
	stat: ["GETTDP",6,0,0,"STORE32C",5,6,0]
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	parseHeap HEAP32,{"unsigned":false,"float":false,"bits":32,"type":0}
	raw: [-1,["GETTDP",7,0,0,"LOAD32AV",7,7,4,"STORE32AV",5,4,7]]
	stat: ["GETTDP",7,0,0,"LOAD32AV",7,7,4,"STORE32AV",5,4,7]
	raw: [7,["SETVI",6,32,8,"EXTCALL",7,"_printf","iii",6,1,0,0]]
	stat: ["SETVI",6,32,8,"EXTCALL",7,"_printf","iii",6,1,0,0]
	raw: [0,["SETST",0,0,0]]
	stat: ["SETST",0,0,0]
	raw: [-1,["SETVI",7,0,0,"RET",7,0,0]]
	stat: ["SETVI",7,0,0,"RET",7,0,0]
	DEBUG    root: finalizing emterpreted code
	DEBUG    root: applying js optimization passes: asm minifyNames cleanup last minifyWhitespace
	chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 51577 - 51577
	DEBUG    root: js optimizer using native
	running cleanup on shell code
	DEBUG    root: emcc step "final emitting" took 1.55 seconds
	DEBUG    root: total time: 3.00 seconds

Sorry about the bots, they don't actually have access from outside world, since I don't have a public IP allocated to them.

**Comment by juj** [comment]
Fixed by Alon in above commit.
