### ISSUE TITLE
Support for large memory handling?

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#3253]
The memory system that emscripten uses seems poorly suited for managing large amounts of memory. Dynamic growth via enlargeMemory() has several undesirable properties:
- If memory growth is disabled, it aborts immediately. This prevents our code from handling out-of-memory errors by checking for NULL from malloc().
- If memory growth is enabled, it causes an infinite loop after growing past 1gb (it tries to grow memory to 1 << 31 bytes which is negative). This is obviously a bad user experience. Ideally it would grow from 1gb to something around 1.9gb if possible, otherwise it would return NULL.
- When the reserved memory is exhausted, we would like the chance to free some of our cached data first and only then call enlargeMemory() if there still isn't enough memory.

How have other people been dealing with these issues? Should we be compiling our own malloc() implementation? If so, how easy is this to integrate with the rest of emscripten?

**Comment by kripken** [comment]
I think most people are not using heaps of that size. For example evan Unreal strongly recommends people use a 512MB heap and no larger, because browsers often can't load any bigger.

 * We could add an option for malloc to be fallible, if that would be useful.
 * We should fix growing to get closer to the current 2GB limit.
 * Do native libcs have any functionality like that? I'd like to use something standard if there is. But, it would be trivial to add - our `sbrk()` could call into `Module.memoryPressureWarning()` or such.
 * You can also compile in your own malloc. Just build it and it will override the system malloc/free. You just need to make sure it calls `sbrk()` properly. But, we should just fix the above 3 issues for everyone, I don't think people need a custom malloc for this (might need one for other reasons of course).

**Comment by evanw** [comment]
We're mostly using heaps of that size because we need to enable dynamic memory growth for startup speed, and once dynamic memory growth is on it just keeps on growing without any hooks for us to stop it :)

My impression was that libc just supports this by malloc() returning NULL on failure instead of calling abort() although I'm not too familiar with libc so I'm probably not the best person to ask. Just from looking around I don't see anything standard:

* Android uses a Java method onLowMemory() and doesn't seem to have anything for NDK
* iOS uses an Objective-C notification UIApplicationDidReceiveMemoryWarningNotification and doesn't seem to have anything for C
* Linux apparently optimistically commits memory and malloc() only fails on address space exhaustion, otherwise you just get a segfault on access instead
* Windows uses VirtualAlloc() which returns NULL on failure, with GetLastError() giving more info

Making malloc() fallible would be great. We still want a custom hook though because when malloc() fails we want to retry it several times and try to release more memory at each step. For example: the first step would release easily-reconstructed data, then data that can be reconstructed but would be more expensive, then data that can be reloaded from the network, then finally user old data as a last resort.

**Comment by kripken** [comment]
I fixed memory growth so that it can continue above 1GB in smaller increments, and get close to 2GB, but not reach it. Note that node doesn't let you allocate >1GB arrays on my machine at least; not sure about browsers.

**Comment by evanw** [comment]
Cool, thanks!

It seems like this could still infinite-loop though. Are you relying on the ArrayBuffer constructor to throw an allocation failure when the size approaches the 2gb limit? When I checked last year, most implementations will throw for lengths a few pages less than 2^31 - 1 bytes but I'm not sure if that can be relied on since it's not in the spec. Otherwise, you may end up in a situation where TOTAL_MEMORY is a page away from LIMIT so the next increment ends up causing an infinite loop with TOTAL_MEMORY == LIMIT because alignMemoryPage() rounds up.

**Comment by kripken** [comment]
The loop has an assert though, to avoid that.

**Comment by kripken** [comment]
I also pushed a commit to make malloc fallible. This only works if `ALLOW_MEMORY_GROWTH` as I don't want to change the semantics in the default mode, at least not without more discussion.

Using this, you can call a malloc wrapper that if it sees a failure, will try to free some stuff, then call malloc again. That seems the safest way to do things, as a callback from inside malloc or such would require that malloc be reentrant, which is not necessarily true.

I think that addresses all the issues reported here?

**Comment by evanw** [comment]
Thanks, this looks great! I can't try it out yet because clang is segfaulting on our codebase in the latest emscripten release, but I'll try to file a bug report about that soon. Getting a reduced test case may be challenging.

**Comment by evanw** [comment]
The segfault in clang is now fixed but I wasn't able to update our code base past 1.29.0 because doing that unfortunately causes a 3x slowdown in our app initialization time in Chrome (Firefox is unaffected). Given that our initialization time is already significant, cherry-picking your changes from this issue seems like a better idea than taking a 3x perf hit.

I realize this is unhelpful and I'm sorry I don't have more useful info. The profile data seems to indicate that our app uniformly slows down, likely because V8's heuristics are tickled differently. I'd likely have to bisect the entire emscripten repo to figure out what caused the slowdown if it's even caused by one individual commit at all, and that's not something I'm going to have time for right now. I can log a bug about this if you'd like though.

These changes do work after patching them in a post-build JavaScript transform pass, so feel free to close this bug. Thanks again for fixing this!

**Comment by kripken** [comment]
Which version of chrome is that? On 41+, it notices asm.js and optimizes differently. Trying to remove "use asm" and see if that changes perf.

If that's not it, bisecting on emscripten versions would be best, if you have the time.

**Comment by evanw** [comment]
Wait, actually there might be a bug with the code for this issue. Should [Runtime.dynamicAlloc()](https://github.com/kripken/emscripten/blob/01d531a5fabc58d9f83a628df5c5b43ecc5950d5/src/runtime.js#L65) only be updating DYNAMICTOP if enlargeMemory() succeeds? Right now it always increases DYNAMICTOP, which in my current tests means that DYNAMICTOP keeps inching above TOTAL_MEMORY if memory can't be enlarged. I can't find any documentation on those two variables but it seems like all of the code tries to maintain the invariant that DYNAMICTOP < TOTAL_MEMORY at all times.

**Comment by evanw** [comment]
Just tried removing "use asm" but strangely the very repeatable 3x performance difference has disappeared overnight. Now there is no difference between 1.29.0 and 1.31.2. Changing "use asm" also has no effect. I swear it was a huge problem yesterday...

**Comment by kripken** [comment]
Yeah, that was a bug about DYNAMICTOP (oops!). Fixed.

**Comment by evanw** [comment]
This has been fixed.
