### ISSUE TITLE
test_fuzz fails on all OSes.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3255]
On all slaves, `test_fuzz` is failing after https://github.com/kripken/emscripten/compare/06c1f1c0c4f0c14f7209483c581606f880120ea6...3d8cc051dc5b073308d57150c669e7f7017b24d9 .

**Comment by sunfishcode** [comment]
I believe this is fixed with 694d1abe148ca276ba27da35feb48156a9ed424e.

**Comment by juj** [comment]
Bots agree that `test_fuzz` works now. Thanks!
