### ISSUE TITLE
other.test_simplify_ifs fails on OSX.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3257]
Running `other.test_simplify_ifs` fails on the OSX bot, but seems to pass on the Linux bot.

    ======================================================================
    FAIL: test_simplify_ifs (test_other.other)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/clb/slaves/emscripten/osx-incoming/build/emscripten/tests/test_other.py", line 3044, in test_simplify_ifs
        ''', [2, 1, 1])
      File "/Users/clb/slaves/emscripten/osx-incoming/build/emscripten/tests/test_other.py", line 2972, in test
        assert ifs == actual_ifs, main + ' : ' + str([ifs, actual_ifs])
    AssertionError: function _main(i1, i2) {
     i1 = i1 | 0;
     i2 = i2 | 0;
     var i3 = 0;
     if (!(_getenv(8) | 0)) {
      if (_getenv(16) | 0) i3 = 3;
     } else i3 = 3;
     if ((i3 | 0) == 3) _puts(40) | 0;
     _puts(24) | 0;
     return 0; : [2, 3]

**Comment by kripken** [comment]
Fixed. The important part of that test is the `1` stuff on `--profiling`; in `-g2` we don't guarantee anything. Although I am a little puzzled why it differs by OS.
