### ISSUE TITLE
LLVM 3.6 code quality regression

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3263]
At the top of `fannkuch_worker` in `fannkuch.cpp`, we used to have this:

````
function __Z15fannkuch_workerPv(i2) {
 i2 = i2 | 0;
 var i1 = 0, i3 = 0, i4 = 0, i5 = 0, i6 = 0, i7 = 0, i8 = 0, i9 = 0, i10 = 0, i11 = 0, i12 = 0, i13 = 0, i14 = 0, i15 = 0, i16 = 0, i17 = 0, i18 = 0, i19 = 0;
 i1 = HEAP32[i2 + 4 >> 2] | 0;
 i15 = i1 << 2;
 i13 = _malloc(i15) | 0;
 i14 = _malloc(i15) | 0;
 i15 = _malloc(i15) | 0;
 i4 = (i1 | 0) > 0;
 if (i4) {
  i3 = 0;
  do {
   HEAP32[i13 + (i3 << 2) >> 2] = i3;
   i3 = i3 + 1 | 0;
  } while ((i3 | 0) != (i1 | 0));
````

but in LLVM 3.6 we have this

````
function __Z15fannkuch_workerPv(i3) {
 i3 = i3 | 0;
 var i1 = 0, i2 = 0, i4 = 0, i5 = 0, i6 = 0, i7 = 0, i8 = 0, i9 = 0, i10 = 0, i11 = 0, i12 = 0, i13 = 0, i14 = 0, i15 = 0, i16 = 0, i17 = 0, i18 = 0;
 i1 = HEAP32[i3 + 4 >> 2] | 0;
 i15 = i1 << 2;
 i13 = _malloc(i15) | 0;
 i14 = _malloc(i15) | 0;
 i15 = _malloc(i15) | 0;
 i4 = (i1 | 0) > 0;
 i11 = i1 + -1 | 0;
 if (i4) {
  i2 = 0;
  while (1) {
   HEAP32[i13 + (i2 << 2) >> 2] = i2;
   if ((i2 | 0) == (i11 | 0)) break; else i2 = i2 + 1 | 0;
  }
````

Note that the happy do-while has turned into a sad while. The reason is that LLVM is being clever and moved things around - before the loop, it now subtracts 1 from the comparison value (`i11`).

The same thing happens a few more times in that function, with less obvious results but in general it increases code size due to the extra `-1` and later a `+1` to offset it.

Any ideas, @sunfishcode ?

**Comment by kripken** [comment]
To be more specific, before we used to have

````
l++
if l == x: break
````

and now LLVM prefers to emit

````
if l == (x-1): break
l++
````

This seems like it "avoids" the very last increment. But it's offset by doing the decrement of the test value before the loop, and increases code size. I don't see why LLVM 3.6 thinks this is better :(

**Comment by sunfishcode** [comment]
I don't have any ideas offhand. The second form looks worse, even from LLVM's generic perspective.

**Comment by kripken** [comment]
Further investigation didn't find anything here that we can do; looks like LLVM just got worse on this pattern, but the principles likely help it out elsewhere. We'll just ignore this issue.
