### ISSUE TITLE
Emscripten SDK Manager script needs additional error checking on install

### ISSUE THREAD

**Issue by dtig** [kripken/emscripten#3267]
On a failed install the emsdk script prints 'Installation failed!' but does not return with an error. Compilation fails at a later stage because the install script does not indicate that the install was not completed successfully.

**Comment by juj** [comment]
Can you post a log?

**Comment by dtig** [comment]
The errors are due to the git configuration, the problem here is only that the error is not propagated and is not caught when the installation is unsuccessful. Log below - 
 
Cloning into '/b/build/src/out/emsdk_portable/clang/fastcomp/src'...
fatal: repository 'https://github.com/kripken/emscripten-fastcomp/' not found
Cloning into '/b/build/src/out/emsdk_portable/clang/fastcomp/src/tools/clang'...
fatal: repository 'https://github.com/kripken/emscripten-fastcomp-clang/' not found
CMake Error: The source directory "/b/build/src/out/emsdk_portable/clang/fastcomp/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
CMake invocation failed due to exception!
Working directory: /b/build/src/out/emsdk_portable/clang/fastcomp/build_master_64
Command '['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=Release', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_TESTS=OFF', '/b/build/src/out/emsdk_portable/clang/fastcomp/src']' returned non-zero exit status 1
Installing 'sdk-master-64bit'..
Installing 'clang-master-64bit'..
['/usr/bin/git', 'clone', 'https://github.com/kripken/emscripten-fastcomp', '/b/build/src/out/emsdk_portable/clang/fastcomp/src'] failed with error code 128!
['/usr/bin/git', 'clone', 'https://github.com/kripken/emscripten-fastcomp-clang', '/b/build/src/out/emsdk_portable/clang/fastcomp/src/tools/clang'] failed with error code 128!
Running CMake: ['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=Release', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_TESTS=OFF', '/b/build/src/out/emsdk_portable/clang/fastcomp/src']
Installation failed!
Writing .emscripten configuration file to user home directory /home/
The SDK/tool 'clang-master-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'emscripten-master' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'sdk-master-64bit' cannot be activated since it is not installed! Skipping this tool...
The Emscripten configuration file /home/.emscripten has been rewritten with the following contents:

import os
SPIDERMONKEY_ENGINE = ''
NODE_JS = 'node'
V8_ENGINE = ''
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.

**Comment by juj** [comment]
Oh, I see now, thanks for reporting, I'll improve this flow.

**Comment by juj** [comment]
Thanks, I see your PR fixed the return code already. I also added a commit which now fails the install process earlier if errors occur.

**Comment by dtig** [comment]
Great! Thanks.
