### ISSUE TITLE
Module.allocate() and Module._free()

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3286]
Hey there,

as described in [Call compiled C/C++ code “directly” from JavaScript](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#call-compiled-c-c-code-directly-from-javascript) I'm using `var pointer = Module.allocate([0], 'i8', ALLOC_STACK);` that I then pass to `Module.ccall()` to be able to read the content written to a `char **some_string` after the function executed. I can retrieve the value without problems. But when cleaning up after myself, (naively) assuming `Module._free(Module.getValue(pointer, '*')); Module._free(pointer);` would do the job, I get an error thrown:

```
abort() at Error
    at jsStackTrace (…/libsass.js:1:20866)
    at stackTrace (…/libsass.js:1:21049)
    at Object.abort (…/libsass.js:34:30942)
    at _abort (…/libsass.js:1:302070)
    at Object.W8 [as _free] (…/libsass.js:25:15989)
    at Object.Sass._cleanPointerPointer (…/sass.js:163:12)
    at Object.Sass.compile (…/sass.js:262:12)
    at <anonymous>:4:6
    at Object.InjectedScript._evaluateOn (<anonymous>:847:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:780:34)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

What am I missing here?

**Comment by kripken** [comment]
`free` is the sibling of `malloc`. Stack allocation works entirely differently - you have `stackSave` and `stackRestore` for those.

**Comment by rodneyrehm** [comment]
As far as I can tell, the docs only mention the following

> `Module.Runtime` gives access to low-level runtime functionality. Some of these, for example `Runtime.stackSave()` and `Runtime.stackRestore()` may be useful for advanced users.

Since I'm everything but "advanced user" and I can't find any more info than above, please confirm I got this right:

```js
var _stack = Runtime.stackSave();
var pointer = Module.allocate([0], 'i8', ALLOC_STACK);
var result = Module.ccall(…);
var _pointer = Module.getValue(pointer, '*');
// no need to Module._free(_pointer);
var text = Module.Pointer_stringify(_pointer);
Runtime.stackRestore(_stack);
// all done, memory clean, no surprises waiting to bite me
```

**Comment by kripken** [comment]
Looks right.

In general, you can just read through the emitted js file from emscripten - the implementations of stackSave etc. are all in there, as plain js.

**Comment by rodneyrehm** [comment]
thank you!

**Comment by aaron-michaux** [comment]
I cannot for the life of me find documentation on `Runtime.stacksave()`. Is it deprecated?

**Comment by kripken** [comment]
The Runtime object was deprecated, but `stackSave` still exists as a toplevel function.
