### ISSUE TITLE
documentation linking to source in master ran out of sync

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3287]
Hey there,

is it possible the documentation, or rather the therein contained links to chunks of code, has run out of sync with the actual code base?

[test_add_function in tests/test_core.py](https://github.com/kripken/emscripten/blob/master/tests/test_core.py#L5904) points line 5904, which now seems to be somewhere within `test_corruption`, while `test_add_function` has shifted to [line 6150](https://github.com/kripken/emscripten/blob/master/tests/test_core.py#L6150). You may want to link to a specific tag rather than master… I've seen this in [Interacting With Code](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript), but guess the problem appears elsewhere, too.

**Comment by kripken** [comment]
Thanks, we should indeed use a specific revision. Fixed on incoming.
