### ISSUE TITLE
"emsdk install latest" fails on Mac OS 10.6

### ISSUE THREAD

**Issue by Robotic-Brain** [kripken/emscripten#3289]
Hello,

I just wanted to try emscripten, however it refuses to install and yells at me when following the installation instructions.

when i run: ```./emsdk install latest```
I get this error: ```Error: No tool or SDK found by name 'None'.```

Interestingly: ```./emsdk install foo```
gives me: ```Error: No tool or SDK found by name 'foo'.```

Also running: ```./emsdk install emscripten-1.29.0```
works fine too... (Is this the correct package?)

Could you please tell me what might be causing this, (seems to me like some auto-detection function is broken) and if I chose the right version?

Thank you
Robotic-Brain

**Comment by juj** [comment]
I tried this on my computer, but I was unable to reproduce. Can you try running

    ./emsdk update
    ./emsdk install latest

or if the second line still fails with that error, try

    ./emsdk install sdk-1.29.0-64bit

if that gives the same error?

**Comment by Robotic-Brain** [comment]
I tried it with a fresh working dir, but still nothing :(
the 2nd version worked :)

however now i get strange warnings whenever i run ./emcc in any way
```
$ ./emcc -v
WARNING  root: (Emscripten: unknown: cannot concatenate 'str' and 'NoneType' objects, clearing cache)
WARNING  root: Could not verify LLVM version: argument of type 'NoneType' is not iterable
WARNING  root: could not check fastcomp: need more than 1 value to unpack
INFO     root: (Emscripten: Running sanity checks)
WARNING: sanity check failed to run cannot concatenate 'str' and 'NoneType' objects
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.29.0
WARNING  root: (Emscripten: unknown: cannot concatenate 'str' and 'NoneType' objects, clearing cache)
WARNING  root: Could not verify LLVM version: argument of type 'NoneType' is not iterable
WARNING  root: could not check fastcomp: need more than 1 value to unpack
INFO     root: (Emscripten: Running sanity checks)
WARNING: sanity check failed to run cannot concatenate 'str' and 'NoneType' objects
$ ./emcc --clear-cache
WARNING  root: (Emscripten: unknown: cannot concatenate 'str' and 'NoneType' objects, clearing cache)
WARNING  root: Could not verify LLVM version: argument of type 'NoneType' is not iterable
WARNING  root: could not check fastcomp: need more than 1 value to unpack
INFO     root: (Emscripten: Running sanity checks)
WARNING: sanity check failed to run cannot concatenate 'str' and 'NoneType' objects
WARNING  root: clearing cache
WARNING  root: (Emscripten: unknown: cannot concatenate 'str' and 'NoneType' objects, clearing cache)
WARNING  root: Could not verify LLVM version: argument of type 'NoneType' is not iterable
WARNING  root: could not check fastcomp: need more than 1 value to unpack
INFO     root: (Emscripten: Running sanity checks)
WARNING: sanity check failed to run cannot concatenate 'str' and 'NoneType' objects
```

Also OS X gives me a crash report for python?!
my python version is 2.6.1 and i used the symlink trick from the wiki

**Comment by juj** [comment]
What does your `~/.emscripten` look like?

**Comment by Robotic-Brain** [comment]
```
$ cat ~/.emscripten
import os
SPIDERMONKEY_ENGINE = ''
NODE_JS = 'node'
LLVM_ROOT='/Users/Robotic-Brain/Downloads/emsdk_portable/clang/e1.29.0_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/Users/Robotic-Brain/Downloads/emsdk_portable/clang/e1.29.0_64bit/optimizer'
NODE_JS='/Users/Robotic-Brain/Downloads/emsdk_portable/node/0.10.18_64bit/bin/node'
EMSCRIPTEN_ROOT='/Users/Robotic-Brain/Downloads/emsdk_portable/emscripten/1.29.0'
V8_ENGINE = ''
TEMP_DIR = '/var/folders/ed/edE45rsuGeK3E19-iJVYb++++TQ/-Tmp-'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

**Comment by juj** [comment]
I wonder if this was an issue with python2 vs python3. There is a new Emscripten SDK release out today, see https://groups.google.com/forum/#!topic/emscripten-discuss/b06iW6T2uSw , which has support for using Emscripten SDK when python 3 is installed. Let me know how that works for you.

**Comment by Robotic-Brain** [comment]
Same error as before...
With Python 3.2.2 and Python 3.4.3

What really bothers me is Python "SEGFAULTing"
Shouldn't it be impossible to access invalid memory in Python?

Meanwhile i experimented a bit on a koding.com VM where everything worked fine...

**Comment by juj** [comment]
Strange. Emscripten itself does not support python 3, only python 2 works (but the emsdk manager does support python 3 for compatibility). Python segfault does suggest an internal python bug, so perhaps you are able to reduce that down to a small test case and report it to python bug tracker?

**Comment by Robotic-Brain** [comment]
Unfortunately i wouldn't even know where to start since i'm not a python programmer...

**Comment by Robotic-Brain** [comment]
I just updated to 10.10 (unwillingly - but long overdue) and everything works fine.
I guess something was seriously messed up with my old system...
