### ISSUE TITLE
incoming clang has wrong version number in file name

### ISSUE THREAD

**Issue by waywardmonkeys** [kripken/emscripten#3292]
When I build with current incoming llvm-fastcomp, etc, I end up with a ``clang-3.5`` binary. If I run it, I see that it claims to be an LLVM 3.6.0 binary, so it is just a cosmetic issue.

If it matters, I build with ninja via cmake.

**Comment by kripken** [comment]
How do you see it is 3.5?

What does `emcc -v` say?

**Comment by waywardmonkeys** [comment]
````
batavia:build bruce (virtual-issues) $ ls -l bin/clang*
lrwxr-xr-x  1 bruce  staff         9 Mar 31 18:29 bin/clang -> clang-3.5
lrwxr-xr-x  1 bruce  staff         5 Mar 31 18:29 bin/clang++ -> clang
-rwxr-xr-x  1 bruce  staff  41415888 Mar 31 18:29 bin/clang-3.5
-rwxr-xr-x  1 bruce  staff  18364440 Mar 31 18:29 bin/clang-check
lrwxr-xr-x  1 bruce  staff         5 Mar 31 18:29 bin/clang-cl -> clang
-rwxr-xr-x  1 bruce  staff   1643984 Mar 31 18:29 bin/clang-format
-rwxr-xr-x  1 bruce  staff   1075240 Mar 31 18:22 bin/clang-tblgen
````

**Comment by kripken** [comment]
Strange. My build with cmake has `clang-3.6` in the output. My build with configure doesn't seem to have emitted any `clang-x.y`.

Does `emcc -v` give you the proper result?

**Comment by waywardmonkeys** [comment]
Yes?

````
batavia:emscripten bruce (incoming) $ ./emcc -v
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.30.1
clang version 3.6.0 (git@github.com:kripken/emscripten-fastcomp-clang.git 3804f85cdc5fb506c617aef22a8ccf855b5e007d) (git@github.com:waywardmonkeys/emscripten-fastcomp.git 4d6f14209b7476b751cc9f033d46e169b40693ec)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
INFO     root: (Emscripten: Running sanity checks)
````

**Comment by kripken** [comment]
Looks right. No idea then why it made `clang-3.5` for you. No chance it's left over from a previous build? (timestamp seems to show that's not the case)

**Comment by waywardmonkeys** [comment]
This was due to having an old value in my ``CMakeCache.text`` ... (an advanced mode cached value, so you'll have to turn on advanced mode in ``ccmake`` to see it).
