### ISSUE TITLE
emsdk fails to install latest on ubuntu-14.04.1-desktop-amd64 in Sun VirtualBox

### ISSUE THREAD

**Issue by dayo7116** [kripken/emscripten#3295]
I tried to port box2d with Visual Studio 10 on windows, but no luck. So I move to linux after failing many times.
I use ubuntu-14.04.1-desktop-amd64.iso in Sun VirtualBox on Win7.

I followed the instructions in http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#all-os-installation-instructions-portable-sdk.

But every time I ran ./emsdk install latest, it stopped and said fail to clone Emscripten master because of git timed out.

Finally, I find the reason, it used git://github.com/kripken/emscripten.git to clone Emscripten repo.
After I change it to https://github.com/kripken/emscripten.git. It worked.

Not sure it will happen for others, so I create an issue here.

And is there anyone who succeeds to port box2d with VS2010 on window? Any suggestions will be   appreciated. Thanks and sorry for my pool English.

**Comment by juj** [comment]
Does your network probably block the git:// protocol? http://stackoverflow.com/questions/4891527/git-protocol-blocked-by-company-how-can-i-get-around-that

**Comment by dayo7116** [comment]
OK, it's my network's fault.... Thanks.
