### ISSUE TITLE
NODE_JS = 'node' on ubuntu-14.04.1-desktop-amd64

### ISSUE THREAD

**Issue by dayo7116** [kripken/emscripten#3296]
After I install emscripten successfully on ubuntu(following all the instructions on http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html), I ran emcc -v.
And get WARNING root: cannot check node version: invalid literal for int() with base 10: ''
Checking JS engine ['node'] failed.
After I check ~/.emscripten, I find NODE_JS='node'.
Isn't it supposed to be NODE_JS='nodejs' on linux?
Anyway, after I change it to NODE_JS='nodejs', emcc -v works.

**Comment by juj** [comment]
This is a somewhat annoying thing. If people download node.js off the website, the executable will have the name `node` or `node.exe` on Windows. On several linux distros the executable is named `node` as well, e.g. on my Ubuntu it is just `node`. Apparently however on some linuxes they decided that node.js executable should be renamed to `nodejs` to make room for some other application named `ax25-node`, see here: https://github.com/juj/emsdk/issues/20 for more information where @floooh identified this bug.

I think we should figure out a way to invoke the `node` executable with a certain set of command line parameters to identify whether the node we are seeing is in fact node.js, and not, then try to autofind using `nodejs`. Do you know what parameters would be a good way to call `node` executable from the command line to identify whether the executable we called was indeed node.js?

**Comment by dayo7116** [comment]
Sorry, I am not familiar with node.js, so I don't know.

**Comment by Annonomus-Penguin** [comment]
Yes. It is confusing because the docs say to install the `nodejs` package. I might submit a PR on the docs to indicate that you need to change the config as that wasted a few hours of my day today :/

**Comment by Annonomus-Penguin** [comment]
Update: Sphinx is confusing me :D

**Comment by Annonomus-Penguin** [comment]
Update: Sphinx is confusing me :)

I am still having this issue--if we can't fix it, we should at least fix the docs somehow (although I have no idea how to). Should this issue be reopened?

**Comment by kripken** [comment]
Definitely let's update the docs if we can make this clearer. PR would be great.

**Comment by Annonomus-Penguin** [comment]
Ok, done!

To help future visitors, this is the error that occurs (at least for me)... hopefully Google will point a few people with this error to this issue as there's nothing else online for this:

```
WARNING  root: (Emscripten: settings file has changed, clearing cache)
WARNING  root: cannot check node version: [Errno 2] No such file or directory
INFO     root: (Emscripten: Running sanity checks)
Checking JS engine ['node'] failed. Check ~/.emscripten. Details: [Errno 2] No such file or directory
CRITICAL root: The JavaScript shell used for compiling (['node']) does not seem to work, check the paths in ~/.emscripten
```

**Comment by jedie** [comment]
Same here:
```
~/emsdk_portable $ emcc -v
WARNING  root: cannot check node version: [Errno 2] No such file or directory
INFO     root: (Emscripten: Running sanity checks)
Checking JS engine ['node'] failed. Check ~/.emscripten. Details: [Errno 2] No such file or directory
CRITICAL root: The JavaScript shell used for compiling (['node']) does not seem to work, check the paths in ~/.emscripten
```
I have to change in **~/.emscripten** the line **NODE_JS = 'node'** to **NODE_JS = 'nodejs'**
Then it works.
