### ISSUE TITLE
Literal wide string lost after a memory growth

### ISSUE THREAD

**Issue by canning-duck** [kripken/emscripten#3299]
Hi all,

I have an issue with a literal (wide) string that is corrupted after a memory growth.
  
You can reproduce the problem by compiling this code ("issue.cc"):

    #include <emscripten/bind.h>

    #include <string>
    #include <memory>

    using namespace emscripten;

    static std::unique_ptr<std::vector<char>> buffer_;

    std::string getString() {
      return "Embind is used to bind C++ functions and classes to JavaScript.";
    }

    std::wstring getWideString() {
      return L"Embind is used to bind C++ functions and classes to JavaScript.";
    }

    void createBuffer() {
      buffer_.reset(new std::vector<char>(16 * 1024 * 1024));
    }

    void destroyBuffer() {
      buffer_.reset();
    }

    EMSCRIPTEN_BINDINGS(Issue) {
        function("getString", &getString);
        function("getWideString", &getWideString);
        function("createBuffer", &createBuffer);
        function("destroyBuffer", &destroyBuffer);
    }

...with:

    emcc --bind -s TOTAL_MEMORY=16777216 -s ALLOW_MEMORY_GROWTH=1 -o issue.html issue.cc

Then, in a web browser:

    Module.getString() // "Embind is used (...)" OK
    Module.getWideString() // "Embind is used (...)" OK
    Module.createBuffer() // Get a warning about growing the heap, OK
    Module.getString() // Still OK
    Module.getWideString() // "" empty string, KO !

Strange fact: if I release the buffer with Module.destroyBuffer() then getWideString() returns the right string again.

Did I miss a compilation option ? Is it a known issue ?

PS. Tested on Mac in Safari with Emscripten 1.29.0.

**Comment by kripken** [comment]
I can confirm the problem.

Do you think it's an embind issue? Can you reproduce it without embind?

**Comment by canning-duck** [comment]
I cannot use std::string and std::wstring without embind, can I? In this case, the "C" version of the code would be (and it works fine, by the way):

    #include <stdlib.h>

    extern "C" {

      static void *buffer_ = NULL;

      const char * getString() {
        return "Embind is used to bind C++ functions and classes to JavaScript.";
      }

      const wchar_t * getWideString() {
        return L"Embind is used to bind C++ functions and classes to JavaScript.";
      }

      void createBuffer() {
        if (!buffer_) buffer_ = malloc(16 * 1024 * 1024);
      }

      void destroyBuffer() {
        if (buffer_) free(buffer_);
      }

    }

Compiled with:

    emcc issue.cc -s TOTAL_MEMORY=16777216 -s ALLOW_MEMORY_GROWTH=1 -o issue.html -s EXPORTED_FUNCTIONS="['_getString','_getWideString','_createBuffer','_destroyBuffer']"

Tested with:

    Module.Pointer_stringify(Module._getString()) // "Embind is used (...)"
    Module.UTF32ToString(Module._getWideString()) // "Embind is used (...)"
    Module._createBuffer() // Memory growth warning
    Module.Pointer_stringify(Module._getString()) // "Embind is used (...)"
    Module.UTF32ToString(Module._getWideString()) // "Embind is used (...)", Still OK

**Comment by kripken** [comment]
ok, sounds like an embind bug then. perhaps something with the serialization/deserialization. It might put something on the stack or heap during a memory growth perhaps?

**Comment by kripken** [comment]
cc @chadaustin

**Comment by chadaustin** [comment]
Ah, I see the issue in here: https://github.com/kripken/emscripten/blob/master/src/embind/embind.js#L650

That code saves a local reference to HEAP, where it should just use HEAPU16 or HEAPU32, in case HEAPU16 or HEAPU32 changes value.

The appropriate fix is to either use HEAPU16 or HEAPU32 in context or register some hook that recreates the appropriate marshaling function when memory is resized.  The former approach is probably easier.  :)

Care to submit a pull request, @canning-duck?

Cheers,
Chad

**Comment by waywardmonkeys** [comment]
This is a great find. If needed, I'll be happy to do the pull request if @canning-duck lacks the time.

**Comment by canning-duck** [comment]
Thanks @waywardmonkeys but I'll take time to look into it this week.

**Comment by canning-duck** [comment]
@chadaustin I've taken the easy approach. The pull request is over there : #3318.

**Comment by waywardmonkeys** [comment]
This can be closed now that the fix has been merged, right?
