### ISSUE TITLE
EMULATE_FUNCTION_POINTER_CASTS=1 seems to generate invalid asm.js

### ISSUE THREAD

**Issue by aidanhs** [kripken/emscripten#3300]
.a file at http://aidanhs.com/libtcl8.5.a

By compiling this with
"emcc --memory-init-file 0 -s INCLUDE_FULL_LIBRARY=0 -s EMULATE_FUNCTION_POINTER_CASTS=1 -O3 -g0 --js-opts 1 --llvm-opts 3 --llvm-lto 3 -s ASSERTIONS=0 -s EXPORTED_FUNCTIONS="['_Tcl_EvalObjEx']" -o lp.js libtcl8.5.a"
I get a file which Firefox complains about: "TypeError: asm.js type error: all functions in table must have same signature".

By changing EMULATE_FUNCTION_POINTER_CASTS to be 0, it seems to be fine.

**Comment by kripken** [comment]
Thanks, fixed on incoming.
