### ISSUE TITLE
OpenAL source ids.

### ISSUE THREAD

**Issue by perneky** [kripken/emscripten#3303]
Hello,

While porting some OpenAL relatied code to Emscripten, I have discovered that alGenSources returns 0 for the first source. While this could be OK for the OpenAL specification, it makes hard to detect uninitialized AL sources easily (you can't use if ( source == 0 ) { it is uninitialized } ).

A simple soulution would be to start AL.newSrcId from 1 in library_openal.js.

My Emscripten version is 1.29.0.

Thank you.

**Comment by kripken** [comment]
@juj, any opposition to starting from 1?

**Comment by perneky** [comment]
For a reference, the OpenAL Soft implementation starts ide from One. This behaviour conforms with the khronos API.

**Comment by juj** [comment]
I encourage starting from `1`, that is a good idea.

**Comment by kripken** [comment]
Done.
