### ISSUE TITLE
emscripten_GetProcAddress should strip ANGLE suffix

### ISSUE THREAD

**Issue by rdb** [kripken/emscripten#3304]
Even though support for ANGLE extensions is reported, calling emscripten_GetProcAddress fails on functions with ANGLE suffix, like glDrawElementsInstancedANGLE.

Looking at its source code in system/lib/gl.c, it seems to strip off ARB, EXT and OES suffixes, but not ANGLE.  Fixing this would ease porting of existing GLES2 applications that make use of ANGLE extensions.

**Comment by kripken** [comment]
cc @juj and @jdashg - thoughts?

**Comment by juj** [comment]
I am all ok with supporting ANGLE suffixes with direct mappings, so pull requests are welcome. In general though if we do find there are spec differences, then we should fall back to not giving the support, but document in https://github.com/kripken/emscripten/blob/master/site/source/docs/porting/multimedia_and_graphics/OpenGL-support.rst why a certain extension is not being supported.

**Comment by rdb** [comment]
Thank you.  Filed PR #3315 .
