### ISSUE TITLE
"warning: unresolved symbol" when using std::experimental::optional<T>

### ISSUE THREAD

**Issue by jplatte** [kripken/emscripten#3306]
... or, more specifially, `std::experimental::optional<T>::value()`. This happens as soon as I use this function on optional objects, without it everything is fine. The problem is that the `bad_optional_access` exception class implementation seems to miss a few bits. Here are the three lines of error messages I get:

    warning: unresolved symbol: _ZNSt12experimental19bad_optional_accessD1Ev
    warning: unresolved symbol: _ZTINSt12experimental19bad_optional_accessE
    warning: unresolved symbol: _ZTVNSt12experimental19bad_optional_accessE

These are the unmangled symbol names:

    std::experimental::bad_optional_access::~bad_optional_access()
    typeinfo for std::experimental::bad_optional_access
    vtable for std::experimental::bad_optional_access

I'm using emcc / em++ 1.30.2 (clang 3.6.0). I tested building natively with both gcc / g++ 4.9.2 and clang / clang++ 3.6.0 and didn't have the same problem there (though this might have to do with which standard library implementation they are using, I don't know a lot about that).

**Comment by kripken** [comment]
Perhaps this experimental feature is not fully or properly supported in libc++?

**Comment by jplatte** [comment]
Right, that's the info I wanted. I now installed the native libc++, but I couldn't get things to work with it. There is one library I built myself which suddenly has a lot of undefined references when I change the standard library I use. I guess I'll have to rebuild that with libc++ too. I'll try that when I've got more time.

**Comment by jplatte** [comment]
This issue is about a program I no longer work on and is probably completely outdated as well, closing.
