### ISSUE TITLE
Linux compilation error: "fatal: cannot start proxy git-proxy"

### ISSUE THREAD

**Issue by wiseoldman95** [kripken/emscripten#3314]
I am trying to use Emscripten on Linux. I installed all the required dependencies:
`sudo apt-get install python2.7 nodejs default-jre git-core default-jre`
I also installed these, just in case:
`sudo apt-get install libxml2-dev git-all`

Next, I executed `./emsdk update && ./emsdk install latest`
After a long wait, I got the following error:

```
...
[100%] Built target llvm-c-test
[100%] Built target LTO
[100%] Built target llvm-lto
[100%] Built target clang
Done.
Done.
Installing 'emscripten-master'..
Cloning into '<hidden>/emscripten/emsdk_portable/emscripten/master'...
error: cannot run git-proxy: No such file or directory
fatal: cannot start proxy git-proxy
['/usr/bin/git', 'clone', 'git://github.com/kripken/emscripten.git', '<hidden>/emscripten/emsdk_portable/emscripten/master'] failed with error code 128!
Installation failed!
```

Help is appreciated.

**Comment by juj** [comment]
For some reason the `git://` protocol doesn't seem to be supported. Try editing `emsdk_manifest.json` locally and search-replace the `git://` urls to `https://` urls. Does that work around the issue?

I suppose we should change permanently to using `https://` now that the Windows deployment of git has fixed their https handling - the git protocol seems to be problematic for a lot of users.

**Comment by wiseoldman95** [comment]
Alright, will test this. 

I am already manually compiling fascomp, which already took an hour or so. Can I somehow make the sdk "take it from here" instead of re-compiling back from the start?

**Comment by wiseoldman95** [comment]
By the way, I obtained the sdk [from here](https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz), fixing that file by converting `git://` to `https://` should be easy.

**Comment by juj** [comment]
Unfortunately if you are compiling emscripten-fastcomp from a manual git clone to a custom directory, it is not sensible to attempt to move that around to embed it to emsdk, because CMake uses absolute paths, and does not allow moving directories.

**Comment by wiseoldman95** [comment]
My current setup (Manual installation) is working just fine, and to be honest I am hesitant to play around with stuff and break things any more and I just want this to work, I will not be testing your proposed emsdk fix any time soon. Consider this resolved.

**Comment by wiseoldman95** [comment]
I eventually did test it. And it worked. Note that in addition to editing `emsdk_manifest.json`, there was also a single git link inside `emsdk`, which I also changed to https.

**Comment by wiseoldman95** [comment]
I'm gonna re-open this as a reminder to fix https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz

**Comment by juj** [comment]
Fixed in https://github.com/juj/emsdk/commit/12213e4d59113e7de24c09c98f690234fe165d19 , the download URLs will reflect once those go live for the next version.
