### ISSUE TITLE
test_python fails on Windows.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3317]
The test `test_python` has regressed on the Windows slave: http://clb.demon.fi:8112/builders/win-incoming/builds/776/steps/Tests-default/logs/stdio

Last good build for that test was 754: http://clb.demon.fi:8112/builders/win-incoming/builds/754

First bad build where the breakage was observed was 756: http://clb.demon.fi:8112/builders/win-incoming/builds/756

The intermediate build 755 in between was very broken and uncertain which way it went. Diffs:

Emscripten: https://github.com/kripken/emscripten/compare/eaedf00c1c4ab266fad31fa9aafc8b02399b2fd4...c27211238d4ccd184efa5df4d96a9321ed281771

fastcomp: https://github.com/kripken/emscripten-fastcomp/compare/694d1abe148ca276ba27da35feb48156a9ed424e...411c4516bf16feceff7c086cf6088fb3ac492d98

fastcomp-clang: https://github.com/kripken/emscripten-fastcomp-clang/compare/b53bb36c6e22dc2bbee81579f42267067f9194de...3804f85cdc5fb506c617aef22a8ccf855b5e007d

So it looks like this occurred in the LLVM 3.6 migration.

**Comment by kripken** [comment]
The python test is somewhat invalid in that we have some LLVM bitcode that we test on. It's old by now, so I could see a problem where newer LLVM fails to load it or to load it correctly. However, it's puzzling that it would fail only on windows. Maybe building with assertions and safe heap can help figure this out?

**Comment by juj** [comment]
Hmm, running with ASSERTIONS and SAFE_HEAP, I am seeing a crash on alignment: `alignment error loading from address 11, which was expected to be aligned to a multiple of 4`, but if I run the current master branch with SAFE_HEAP enabled, there is no such error. That sounds very odd that suddenly alignment on the generated code would break, and only on Windows.

Do we have a way to recreate this test from sources so we would not depend on LLVM bitcode?

**Comment by juj** [comment]
The above error in full:

    C:\code\emsdk\emscripten\incoming>node c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js
    alignment error loading from address 11, which was expected to be aligned to a multiple of 4
    alignment error loading from address 11, which was expected to be aligned to a multiple of 4

    c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:86
          throw ex;
                ^
    abort("alignment error loading from address 11, which was expected to be aligned to a multiple of 4") at Error
        at jsStackTrace (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:1223:13)
        at stackTrace (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:1240:22)
        at abort (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:444610:44)
        at SAFE_HEAP_LOAD (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:356:27)
        at _PyDict_SetItem (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:380003:7)
        at _PyDict_SetItemString (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:395465:8)
        at __PySys_Init (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:79543:2)
        at _Py_InitializeEx (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:96294:9)
        at _Py_Initialize (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:442394:2)
        at _Py_Main (c:\users\clb\appdata\local\temp\emscripten_temp\src.cpp.o.js:82487:2)

**Comment by juj** [comment]
Here's the temp files the build generated when failing: https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/test_python_emscripten_temp.zip , in case that gives any clues.

**Comment by kripken** [comment]
The problem with building from source is (1) it's very slow to build, and (2) it actually requires serious hackery, as it is a self-hosting build system. I never managed to automate it myself.

I pushed a new bitcode file now, that was re-processed by the current LLVM, so it is valid bitcode in the current format, and passes module verification. Hopefully that will fix the windows bot. If not, we can consider other options (build from source, or perhaps just disable it on windows).

**Comment by kripken** [comment]
No such luck.

**Comment by kripken** [comment]
Interestingly `default` passes, but `asm1` fails. There are fairly few differences between those two, as we are not optimizing source code in this test.

To rule it out, can you try multiple JS engines on the asm1 output? Could in theory be a JS engine bug.

If that's not it, can you please disable the lto part of that test (so it doesn't confuse us - it isn't what is failing, if I am reading the bot log correctly), build `default` and `asm1` each with `EMCC_DEBUG=1`, and send me the log output + the test dir outputs?

**Comment by aidanhs** [comment]
> The python test is somewhat invalid in that we have some LLVM bitcode that we test on. It's old by now, so I could see a problem where newer LLVM fails to load it or to load it correctly.

I can build a python .bc file from source - the current one is broken anyway for a slightly extended test case, so I've been meaning to replace it for a while with one that uses function pointer cast emulation.

**Comment by kripken** [comment]
@juj - the bots look ok now - any idea what's going on?

@aidanhs - thanks, if this is still a problem that would be useful.

**Comment by juj** [comment]
@kripken : that is a false positive, fixed the reporting in https://github.com/kripken/emscripten/pull/3343 

I'll dig into debugging this a bit further in a moment and cross-reference between Windows and OSX builds and runs, that should show where things go different.

**Comment by juj** [comment]
Actually, testing out @aidanhs 's pull request https://github.com/kripken/emscripten/pull/3337 , I see that it fixes the on Windows in all modes. It does sound odd though that we got different behavior on Windows compared to other platforms, especially that running on Windows would generate code with unaligned pointer accesses. @aidanhs : did you figure out how that kind of cross platform difference might come out?

**Comment by aidanhs** [comment]
If there's a pipeline of
```
bitcode -> emscripten/llvm -> js
```
and the first two pieces of the pipeline are the same but the third isn't, something sounds either non-deterministic or environment-dependent (I'd hope the latter).

All I can offer is wild speculation. Maybe the bitcode @kripken regenerated has some strange sequence of instructions which windows doesn't like...? I really have no idea. But I guess it must be a bug because emscripten shouldn't be generating unaligned pointer accesses at all?

**Comment by kripken** [comment]
Well, the old bitcode was built with a previous version of emscripten, using a different triple, and also older versions of the MUSL headers. So there are a bunch of things that could be different. Good to know that the update fixes them. It is still puzzling that something is different on windows, I can only guess that it is some sort of cross-compilation bug in LLVM, where despite us using a non-system triple, it does something windows-ey.

**Comment by kripken** [comment]
I merged that pull, so I think we can close this once we verify on the bot.

**Comment by kripken** [comment]
Looks good I think.
