### ISSUE TITLE
MOZ_ prefixed WebGL extension strings are deprecated

### ISSUE THREAD

**Issue by wiseoldman95** [kripken/emscripten#3324]
SDL2 applications are throwing the following warning on Firefox:
```
Error: WebGL: getExtension('MOZ_WEBGL_compressed_texture_s3tc'):
MOZ_ prefixed WebGL extension strings are deprecated.
Support for them will be removed in the future.
Use unprefixed extension strings.
To get draft extensions, set the webgl.enable-draft-extensions preference.
```
The applications still work though, this is just a warning.

**Comment by wiseoldman95** [comment]
Does this belong to https://github.com/emscripten-ports/SDL2/issues ?

**Comment by juj** [comment]
Thanks, feel free to ignore the warning, it's just noise basically. A commit that cleans up the warning is in above pull request.
