### ISSUE TITLE
emscripten_GetProcAddress calls fprintf(stderr, ...), requiring FS to be enabled

### ISSUE THREAD

**Issue by floooh** [kripken/emscripten#3327]
See here: https://github.com/kripken/emscripten/blob/incoming/system/lib/gl.c#L1731

The fprintf(stderr, ...) call seems to require the emscripten FS module to be enabled. It would be good if this dependency could be removed (e.g. in Oryol I am linking with -s NO_FILESYSTEM=1 in order to reduce client size).

Background discussion: https://github.com/floooh/fips-bgfx/pull/4#issuecomment-91080557

**Comment by kripken** [comment]
Makes sense, done on incoming. Will need to clear cache (I didn't bump the version yet).
