### ISSUE TITLE
Small source file yields incorrect output when compiled to JS via Emscripten

### ISSUE THREAD

**Issue by lelandbatey** [kripken/emscripten#3334]
Never raised an issue before, I've tried to gather as much information as possible, as outlined by the [contribution guide](http://kripken.github.io/emscripten-site/docs/contributing/contributing.html). I hope I'm in-line with community procedures, and if not please help me learn how best to participate.	

### Problem

When compiling this[[0]](http://nacr.us/media/text/emscripten_broken/break_emscripten_raytracer.cpp) C++ file with Emscripten, the compiled javascript file produces incorrect output when run (using node v0.12.0 on all platforms). This is not "serious" code, it is a toy minified raytracer, [as posted by Fabien Sanglard[1]](http://fabiensanglard.net/rayTracing_back_of_business_card/). I have tried to find any information on the Emscripten website regarding less-than-compatible behavior this source file might be doing which makes it run incorrectly, but I have had no luck.

In attempting to narrow the problem, I also constructed a small program which seems to break in a similar way, which [can be found here[6]](http://nacr.us/media/text/emscripten_broken/break_emscripten_minimal.cpp).

I come here hoping that it is simply an oversight by me in how this code is written or how I'm compiling it.

### Steps to reproduce:

Assuming you've downloaded the source for both the [raytracer[0]](http://nacr.us/media/text/emscripten_broken/break_emscripten_raytracer.cpp) and the [minimal black image creator[6]](http://nacr.us/media/text/emscripten_broken/break_emscripten_minimal.cpp), the following is the script I'm using to test compilation (it can also be [found here[5]](http://nacr.us/media/text/emscripten_broken/compile_broken_sources.sh)):

	#!/bin/bash

	# Compile with normal C++ compiler
	clang break_emscripten_minimal.cpp -lm -o c_minimal
	./c_minimal > c_minimal_raw.ppm
	convert c_minimal_raw.ppm c_minimal_black.png
	# rm c_minimal

	clang break_emscripten_raytracer.cpp -lm -o c_raytracer
	./c_raytracer > c_ray_raw.ppm
	convert c_ray_raw.ppm c_raytraced_img.png
	# rm c_raytracer

	# Compile with Emscripten
	export EMCC_DEBUG=1
	emcc break_emscripten_minimal.cpp -lm -o js_minimal.js
	node js_minimal.js > js_minimal_raw.ppm
	convert js_minimal_raw.ppm js_minimal_black.png
	# rm js_minimal.js
	mv /tmp/emscripten_temp /tmp/emscripten_temp_minimal
	tar -czf emcc_debug_minimal_temp.tar.gz -C /tmp emscripten_temp_minimal
	rm -r /tmp/emscripten_temp_minimal/

	emcc break_emscripten_raytracer.cpp -lm -o js_raytracer.js
	node js_raytracer.js > js_ray_raw.ppm
	convert js_ray_raw.ppm js_raytraced_img.png
	# rm js_raytracer.js
	mv /tmp/emscripten_temp /tmp/emscripten_temp_raytracer
	tar -czf emcc_debug_raytracer_temp.tar.gz -C /tmp emscripten_temp_raytracer
	rm -r /tmp/emscripten_temp_raytracer/

This script will attempt to compile and run both source files (the raytracer and the simple black image generator) and have them output PPM files. It then tries to convert those images to PNG (for easy viewing).

I've had intermittent results. On all the platforms I've tested this on, Emscripten compiles the code fine, but the data written to stdout varies. For example, on OS X the generated image is a valid image, it's just very corrupted[[2]](http://nacr.us/media/text/emscripten_broken/osx_js_raytracer_broken_output.png). On Ubuntu 14.04, the data output is not even a valid image.

Additionally, on OS X the progress written to `stderr` has corrupted characters:

	ï¿½ï¿½.41 complete
	97.46 complete
	ï¿½ï¿½.51 complete
	97.56 complete
	ï¿½ï¿½.61 complete
	ï¿½ï¿½.66 complete
	ï¿½ï¿½71 complete
	ï¿½ï¿½.75 complete
	97.80 complete
	ï¿½ï¿½.85 complete
	97.90 complete
	ï¿½ï¿½7.95 complete
	ï¿½ï¿½.00 complete
	ï¿½ï¿½8.05 complete
	ï¿½ï¿½8.10 complete
	ï¿½ï¿½.14 complete
	ï¿½ï¿½19 complete

### Platform Information:

The OS X information, as reported by `emcc -v`:

	emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.29.0
	clang version 3.4 
	Target: x86_64-apple-darwin14.1.0
	Thread model: posix
	INFO     root: (Emscripten: Running sanity checks)

The Ubuntu 14.04 information, as reported by `emcc -v`:

	emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.30.0
	clang version 3.5.0
	Target: x86_64-unknown-linux-gnu
	Thread model: posix
	Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
	Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
	Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
	Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.0
	Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
	Candidate multilib: .;@m64
	Selected multilib: .;@m64
	INFO     root: (Emscripten: Running sanity checks)

Output of `node --version`:

	v0.12.0

I only have the naked compiled js file from OS X, found here[[3]](http://nacr.us/media/text/emscripten_broken/osx_raytracer.js). The contents of the `/tmp/emscripten_temp` compiled JS from Ubuntu is here:

- [Debug from compilation of `break_emscripten_minimal.cpp`[7]](http://nacr.us/media/text/emscripten_broken/emcc_debug_minimal_temp.tar.gz)
- [Debug from compilation of `break_emscripten_raytracer.cpp`[8]](http://nacr.us/media/text/emscripten_broken/emcc_debug_raytracer_temp.tar.gz)

[0] - http://nacr.us/media/text/emscripten_broken/break_emscripten_raytracer.cpp
[1] - http://fabiensanglard.net/rayTracing_back_of_business_card/
[2] - http://nacr.us/media/text/emscripten_broken/osx_js_raytracer_broken_output.png
[3] - http://nacr.us/media/text/emscripten_broken/osx_raytracer.js
[4] - http://nacr.us/media/text/emscripten_broken/ubuntu_ray.js
[5] - http://nacr.us/media/text/emscripten_broken/compile_broken_sources.sh
[6] - http://nacr.us/media/text/emscripten_broken/break_emscripten_minimal.cpp
[7] - http://nacr.us/media/text/emscripten_broken/emcc_debug_minimal_temp.tar.gz
[8] - http://nacr.us/media/text/emscripten_broken/emcc_debug_raytracer_temp.tar.gz

**Comment by kripken** [comment]
Does building with [assertions and/or safe heap](http://kripken.github.io/emscripten-site/docs/porting/Debugging.html#compiler-settings) show anything?

**Comment by juj** [comment]
Without looking closer, that sounds like you are writing binary data to the stdout stream. I think that will break, since printing to stdout assumes the data is utf-8 and it will try to decode that to strings to output. Try debugging if you are able to get the correct data from the raytracer e.g. by writing it to a file (see the NODEFS filesystem (or `emrun_file_dump` and `--emrun` build flag) on how to output a file from node.js or a browser to disk, or try using html to view the contents.

**Comment by lelandbatey** [comment]
After struggling with the Emscripten/Node file IO system for a while, I did finally get a working example (by printing the binary output formatted as hex, then using another program to convert the hex back to a raw binary file). After doing all that, the Emscripten output is the exact same as the original C.

Thank you @kripken and @juj, your advice guided me in the correct direction.
