### ISSUE TITLE
How to create WebGL 2.0 context

### ISSUE THREAD

**Issue by TrionProg** [kripken/emscripten#3338]
I'm gonna use OpenGL 3.3 shading language and FBO. And as I guess i must use WebGL 2.0 . So I'm trying to create the context width this code

//GL headers 
#include <GLES3/gl3.h>
#include <GLES3/gl2ext.h>

//main() function
EmscriptenWebGLContextAttributes attrs;
emscripten_webgl_init_context_attributes(&attrs);
attrs.depth = 1;
attrs.stencil = 1;
attrs.antialias = 1;
attrs.majorVersion=2;
attrs.minorVersion=0;

assert(emscripten_webgl_get_current_context() == 0);
context = emscripten_webgl_create_context("canvas", &attrs);
assert(context > 0);

And compile with this flags: -s ASYNCIFY=1 -s USE_WEBGL2=1 -s FULL_ES3=1

And I catch an error at assert(context > 0); witch description:
Could not create canvas: ?,:(,{"alpha":true,"depth":true,"stencil":true,"antialias":true,"premultipliedAlpha":true,"preserveDrawingBuffer":false,"preferLowPowerToHighPerformance":false,"failIfMajorPerformanceCaveat":false,"majorVersion":2,"minorVersion":0}
game.js:2009 Uncaught Assertion failed: context > 0, at: ./engine.hpp,44,initGL at Error
at jsStackTrace (http://game.my/game.js:1161:13)
at stackTrace (http://game.my/game.js:1178:22)
at ___assert_fail (http://game.my/game.js:2009:210)
at __ZN6Engine6initGLEv [Engine::initGL()] (http://game.my/game.js:9246:3)
at Array._main__async_cb (http://game.my/game.js:14166:2)
at dynCall_vi (http://game.my/game.js:14434:29)
at _emscripten_async_resume (http://game.my/game.js:14360:7)
at asm._emscripten_async_resume (http://game.my/game.js:14488:38)
at finish (http://game.my/game.js:4601:25)
at HTMLImageElement.img_onload (http://game.my/game.js:6378:25)

About my system:
Arch linux, x64, OpenGL 4.5 supported(nvidia) ,Chromium

Sorry, I don't know how format this text yet =)

**Comment by juj** [comment]
WebGL 2.0 is not supported in stable versions of browsers yet!

In any case, you can use FBOs in WebGL 1.0 as well (although with fewer features). In Firefox Nightly, you have the following experimental options to set in about:config prefs: https://wiki.mozilla.org/Platform/GFX/WebGL2 . In Chromium they might have similar experimental support available. Try first checking in other JS pages that your browser does have WebGL 2 support available, and let's continue this issue for Emscripten after that, if it works in plain JS but not in Emscripten.

**Comment by TrionProg** [comment]
It works!
But FBO is not tested yet.

and how to install firefox-nightly for arch users (gor newbies =) )
http://www.eightytwo.com.au/notes/linux/installing-from-aur/

**Comment by alecazam** [comment]
It "barely" works.  I think transform feedback one of the few new working features.  There are significant chunks to WebGL 2 that are still stubs.  For example, FF only takes ES3 shaders, but Chrome takes ES2 in their WebGL 2 impls.  The syntax and functionality are quite different.  You'll have to update library_gl.js to account for all of the new calls as well.  You can still do a lot with WebGL 1 in the meantime.

**Comment by juj** [comment]
That is to be expected. WebGL 2 is still in development and it is not a shipping feature yet. Nevertheless, closing this issue as resolved.
