### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character … ordinal not in range(128)

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3348]
I have a habit of typing `…` ("HORIZONTAL ELLIPSIS", U+2026) instead of `...` (three dots) that just brought emscripten down. This can be avoided by replacing the `…` in the JS string by `String.fromCodePoint(0x2026)` (using `"\u2026"` won't do).

I'm not sure I understand why UTF8 should be a problem in 2015. But I believe the error message here can be improved quite a bit, though. For starters a file (and line) of the source file the error occurred in might help.

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 20: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/emcc", line 1340, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/local/Cellar/emscripten/1.30.5/libexec/tools/shared.py", line 1569, in emscripten
    assert os.path.exists(filename + '.o.js'), 'Emscripten failed to generate .js'
AssertionError: Emscripten failed to generate .js
```

Not exactly a show stopper for me, but worth mentioning all the same…

**Comment by kripken** [comment]
Not sure how to test that - do you have a full testcase I can just compile to see the problem?

**Comment by rodneyrehm** [comment]
sure, [here you go](https://gist.github.com/rodneyrehm/e4e7bdbc02be6196f50b). remove the `…` from [test.cpp#7](https://gist.github.com/rodneyrehm/e4e7bdbc02be6196f50b#file-test-cpp-L7) and it will compile just fine

**Comment by kripken** [comment]
Thanks, I see. I suppose this is a unicode issue in the C source code then. I don't know if there is a way to declare the encoding of a C source file? Even if there is though, `EM_ASM` will convert to a string, and that might not be a unicode-friendly operation.

You might have to pass `EM_ASM` a string, in this case.

**Comment by ckruse** [comment]
There is no way of declaring the encoding of a C source file. The encoding is either specified by compiler flags (`-finput-charset`) or, when not specified, derived from the locale. Fallback is UTF-8.

That said: C strings itself can be in any encoding, even UTF-8. They're just byte arrays.

**Comment by rodneyrehm** [comment]
> You might have to pass EM_ASM a string, in this case.

doesn't change a thing.

As this is not important to me right now, I'd suggest to add a note to the EM_ASM* docs and revisit when necessry.

**Comment by kripken** [comment]
Actually this turns out to be easy to resolve, once I read a little about unicode in python ;) Fixed on incoming.

**Comment by rodneyrehm** [comment]
sweet! thank you!
