### ISSUE TITLE
hard to debug JS errors within EM_ASM_INT()

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3349]
Emscripten is quite cryptic about what is failing exactly. The following source

```js
bool foo = (bool)EM_ASM_INT({
  console.log("hello world")
  return 1;
}, 0);
```

will make emcc fail with

```
emcc {…}

emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
        throw new JS_Parse_Error(message, line, col, pos);
              ^
TypeError: object is not a function
    at new JS_Parse_Error (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
    at js_error (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
    at croak (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
    at token_error (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
    at unexpected (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
    at Object.semicolon [as 1] (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:775:51)
    at prog1 (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
    at simple_statement (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:906:35)
    at emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:816:35
    at block_ (emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:999:32)
    at emscripten/1.30.5/libexec/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:821:52
```

Add a semicolon to the first line of JS in EM_ASM_INT() and you're good. I'm not sure If there's a bug in the error handling itself or this is the intended output?! Also the process seems to be exiting with status `0`.

(I'm using empterpreter async, if that makes a difference)

**Comment by kripken** [comment]
I tried to make a full testcase of that,

````
#include <emscripten.h>

int main()
{
  bool foo = (bool)EM_ASM_INT({
    console.log("hello world")
    return 1;
  }, 0);
}
````

and on incoming, I get

````
Runtime.asmConsts = [function() { { console.log("hello world") return 1; } }];
                                                               ^^^^^^
SyntaxError: Unexpected token return
````

Looks like the newlines are lost, so automatic semicolon insertion doesn't work.

I'm not sure if this is the issue you saw, because maybe something else in your file mattered. Also, this is very different on older emscripten, we only just recently on latest incoming started to emit EM_ASMs that way.

Looks like we should handle newlines better, I'll look into that.

**Comment by rodneyrehm** [comment]
> and on incoming, I get

I'm on the 1.30.5 tags. I only now realized that I could make homebrew build from the incoming branch as well, since it's also [downloadable as tarball](https://github.com/kripken/emscripten/archive/incoming.tar.gz).

> I'm not sure if this is the issue you saw, because maybe something else in your file mattered.

no, that's what I figured as well after realizing that adding a semicolon fixed it. I don't even know why I omitted semicolons in EM_ASM() calls - I *know* that I'm not smart enough for ASI…

**Comment by kripken** [comment]
This improvement was really recent, could be after 1.30.5 actually.

Ok, looks like there isn't much to do here. If `EM_ASM` accepts text, as opposed to quoted C strings, then this is just what happens to that code when the C macro does `#input` on it to turn it into a string. This is indeed bad, but at least now that we emit `EM_ASM`s clearly, the problems should be obvious as in the error I saw.

**Comment by rodneyrehm** [comment]
>  If EM_ASM accepts text, as opposed to quoted C strings, then this is just what happens to that code when the C macro does #input on it to turn it into a string.

I have no idea what I'm talking about, but not afraid of asking stupid questions:

* possibly hackable by a `\` at the end of the source line?
* does it simply swallow a single `\n` or all of them?

> This is indeed bad, but at least now that we emit EM_ASMs clearly, the problems should be obvious as in the error I saw.

Clean error is fine by me. Thank you!

**Comment by kripken** [comment]
Hmm, I'm not sure really about how C quotes multiline strings. Neither of those seems to help, but I've no idea how to find something that might ;)

Anyhow I guess we can close this.

**Comment by juj** [comment]
C++11 has raw string literals, see http://stackoverflow.com/questions/20508534/c-multiline-string-raw-literal . Otherwise there is no way to get endlines except to write `\n` manually at the end of each line.

**Comment by kripken** [comment]
Interesting, I didn't know that. For us though that's a C header and macro, so I guess we're stuck with the current situation.
