### ISSUE TITLE
`exit` does not terminate Emterpreter

### ISSUE THREAD

**Issue by coolwanglu** [kripken/emscripten#3360]
I'm not sure if `exit` is supposed to terminate Emterpreter, but otherwise there could be unexpected behaviours.

The following code failed on both js(node) and html output when build without `-O` or with `-O1`, but it works with `-O2` or `-O3`. If I manually inline `f()` into `main()`, it works.

Also note that `world` is never printed even when the program failed.

```
#include <stdio.h>
#include <stdlib.h>
#include <emscripten.h>

void f()
{
    emscripten_sleep(1);
    printf("hello\n");
    if(rand() % 3 == 0) {
        printf("exit\n");
        exit(0);
        printf("world\n");
    }
}

int main() {
    while(1) {
        f();
    }
    return 0;
}
```

**Comment by kripken** [comment]
Fixed on incoming. We should make calls to `exit` always halt execution, it's just the implicit exit from `main()` that we can ignore if `noExitRuntime` (which is turned on when async operations happen, so the runtime remains alive).
