### ISSUE TITLE
Windows web installer is hosed

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#3372]
I tried running the web SDK installer on one of my machines, that had a previous Emscripten install from feb (1.29, I think). The end result was a hosed emscripten install where emcc had mismatching versions and couldn't compile a test cpp with an empty int main (...) {}.

I nuked the emscripten folder, ran the web SDK installer again, no dice. The PATH variables were messed up so emcc couldn't even be found by cmd.

Some more fiddling and my best guesses here:
The web SDK's filename is emsdk-1.29.0-web but it seems to be pulling down some 1.30 files. That's likely part of the problem.
Upgrade mechanism doesn't seem to work right, it seems like it hadn't blown away the PATH entries from my old install and just left them there (pointing to the wrong version).

**Comment by juj** [comment]
Thanks for reporting - I'm able to verify. For now I recommend using the emsdk script to update (`emsdk update` followed by `emsdk install` and `emsdk activate`) instead of using the NSIS installer to install on top of an existing installation.

If updating using the NSIS script, the issue can be worked around for now by first uninstalling the previous SDK before installing the new version.

**Comment by juj** [comment]
New emsdk packages went live today, https://groups.google.com/d/msg/emscripten-discuss/TW-AvHt-lc4/_59T4YBxBQAJ . In the new update, the web installer was fixed to not attempt to always install latest, but it installs the specific version the installer was crafted for. Let me know if new web installer runs into any issues.

Also, set the NSIS installer to erase old entries from PATH, but in general if one wants to use NSIS installer to upgrade, it's best to first uninstall the old version before reinstalling new, or better yet, use the `emsdk update` command followed by `emsdk install latest` to update an existing installation. Closing this as resolved now.
