### ISSUE TITLE
Cryptic error message when building from source if SDK can't find cmake

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#3373]
If the SDK can't find cmake when building from source, the error message is relatively cryptic. It took me a little while to realize that it wasn't able to find cmake instead of it being some other problem.

**Comment by juj** [comment]
Thanks, I'll improve the message for the next release!

**Comment by juj** [comment]
This was implemented in https://github.com/juj/emsdk/commit/0b2638d59d82bf762186a2be7c84b291d8389584.
