### ISSUE TITLE
Can't successfully build from incoming or master using emsdk on windows with VS2013 and latest cmake/sdk

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#3382]
```emsdk install sdk-incoming-64bit``` ```emsdk install sdk-master-64bit``` both fail on win8.1-x64 with VS2013 and latest cmake near the end of the build process, with this error message:

```
LINK : fatal error LNK1181: cannot open input file 'Files/Emscripten/clang/fastcomp/build_master_vs2013_64/tools/lto/LTO.def' [C:\Program Files\Emscripten\clang\fastcomp\build_master_vs2013_64\tools\lto\LTO.vcxproj]
```

The error appears to be caused by cmake generating an incorrect project file, specifically LTO.vcxproj. At line ~126:

```
    <Link>
      <AdditionalOptions> /machine:x64 /debug Files/Emscripten/clang/fastcomp/build_incoming_vs2013_64/tools/lto/LTO.def %(AdditionalOptions)</AdditionalOptions>
      <AdditionalDependencies>kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.
```
You can see it's inlining the path 'Files/Emscripten' and there are no quotes - it appears some part of this pipeline parsed 'Program Files/Emscripten/...' as two paths and truncated it.

I haven't been able to figure out where this is getting generated (it's definitely not the CMakeLists.txt in tools/lto; I don't know my cmake very well.)

**Comment by kg** [comment]
This is indeed a spaces-in-path issue. A workaround:

```
CD \
junction PF "C:\Program Files"
cd PF
emsdk install sdk-incoming-64bit
```

**Comment by juj** [comment]
Thanks. This is an upstream LLVM bug, reported in https://llvm.org/bugs/show_bug.cgi?id=23313 .

**Comment by juj** [comment]
Pushed a local fix to fastcomp for this issue: https://github.com/kripken/emscripten-fastcomp/commit/e0a47860d3addff9e23230453db50da47129b0d4 .
