### ISSUE TITLE
cmake fails to find python in some scenarios during emsdk install

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#3388]
On my laptop, emsdk install fails because cmake can't find python. It shouts at me about setting a variable but I can't set the variable in my environment.

From glancing at their docs I think what needs to happen is for emsdk to invoke cmake with an additional argument:

```-DPYTHON_EXECUTABLE {path_to_emscripten}/python/{version}/python.exe```

EDIT: Having 'python' in my PATH doesn't seem to be sufficient either. I can just type 'python' to open 2.7.6 but cmake isn't having it.

**Comment by kg** [comment]
Changing cmake_configure does the trick:

```python
    else: generator = []
    cmdline = ['cmake'] + generator +  ['-DCMAKE_BUILD_TYPE='+build_type] + ['-DPYTHON_EXECUTABLE=' + sys.executable] + extra_cmake_args + [src_root]
    print 'Running CMake: ' + str(cmdline)
```

**Comment by juj** [comment]
Having to pass that variable in each invocation of CMake doesn't feel sustainable, but no harm adding it here though.
