### ISSUE TITLE
emrun strips certain characters from output

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#3394]
```javascript
Module.print("test: 'asdf -+/*%20%21'\n");
```
Should produce the output ```test: 'asdf -+/*%20%21'```.
On my machine, it produces this in the command line: ```test: 'asdf - /* !'```
Looks like the HTML/HTTP encoding/decoding isn't happening quite correctly.

**Comment by juj** [comment]
Thanks, fixed.
