### ISSUE TITLE
Unable to generate source map using Emscripten 1.30 (used to work on Emscripten 1.29)

### ISSUE THREAD

**Issue by weitjong** [kripken/emscripten#3401]
Here is the stack trace. It was built in Debug build configuration without supplying any optimization flag. 
```
Linking CXX executable ../../../bin/01_HelloWorld.html
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')

/home/weitjong/SDKs/emsdk_portable/emscripten/master/tools/node_modules/source-map/lib/source-map/source-map-generator.js:250
        throw new Error('Invalid mapping.');
        ^
Error: Invalid mapping.
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/weitjong/SDKs/emsdk_portable/emscripten/master/tools/node_modules/source-map/lib/source-map/source-map-generator.js:250:15)
    at SourceMapGenerator_addMapping [as addMapping] (/home/weitjong/SDKs/emsdk_portable/emscripten/master/tools/node_modules/source-map/lib/source-map/source-map-generator.js:99:12)
    at generateMap (/home/weitjong/SDKs/emsdk_portable/emscripten/master/tools/source-maps/sourcemapper.js:130:15)
    at Object.<anonymous> (/home/weitjong/SDKs/emsdk_portable/emscripten/master/tools/source-maps/sourcemapper.js:204:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
Traceback (most recent call last):
  File "/home/weitjong/SDKs/emsdk_portable/emscripten/master/emcc", line 1701, in <module>
    generate_source_map(target)
  File "/home/weitjong/SDKs/emsdk_portable/emscripten/master/emcc", line 1673, in generate_source_map
    '--offset', str(offset)])
  File "/home/weitjong/SDKs/emsdk_portable/emscripten/master/tools/jsrun.py", line 75, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['node', '/home/weitjong/SDKs/emsdk_portable/emscripten/master/tools/source-maps/sourcemapper.js', '/home/weitjong/tmp/tmp4MwqzS/01_HelloWorld.bc.o.js.pp.js', '--sourceRoot', '/home/weitjong/SDKs/urho3d/emscripten-Build/Source/Samples/01_HelloWorld', '--mapFileBaseName', '../../../bin/01_HelloWorld.html', '--offset', '0'] to finish with return code 0, but it returned with code 8 instead! Output: 
Source/Samples/01_HelloWorld/CMakeFiles/01_HelloWorld.dir/build.make:89: recipe for target 'bin/01_HelloWorld.html' failed
```

The target is built with these compiler flags.
- at compilation phase: ```-Wno-invalid-offsetof -ffast-math -m32 -Wno-warn-absolute-paths -Wno-unknown-warning-option -std=c++03 -fcolor-diagnostics -Qunused-arguments -g -DDEBUG -D_DEBUG```
- at linking phase: ```-Wno-invalid-offsetof -ffast-math -m32 -Wno-warn-absolute-paths -Wno-unknown-warning-option -std=c++03 -fcolor-diagnostics -Qunused-arguments -g -DDEBUG -D_DEBUG    -s TOTAL_MEMORY=33554432 -s USE_SDL=2 -s NO_EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --shell-file /home/weitjong/SDKs/urho3d/emscripten-Build/Source/shell.html --preload-file /home/weitjong/SDKs/urho3d/emscripten-Build/bin/CoreData.pak@/CoreData.pak --use-preload-cache --preload-file /home/weitjong/SDKs/urho3d/emscripten-Build/bin/Data.pak@/Data.pak --use-preload-cache  -g4 CMakeFiles/01_HelloWorld.dir/HelloWorld.cpp.o  -o ../../../bin/01_HelloWorld.html -rdynamic ../../../lib/libUrho3D.a -lGL```

The libUrho3D.a is build with similar compiler flags at compilation phase: ```-Wno-invalid-offsetof -ffast-math -m32 -Wno-warn-absolute-paths -Wno-unknown-warning-option -std=c++03 -fcolor-diagnostics -Qunused-arguments -g -DDEBUG -D_DEBUG```

At explained in the subject. This used to work with Emscripten 1.29. Any idea what has been changed since then? How should I proceed to troubleshoot this? Thanks.

**Comment by croes** [comment]
I have a similar problem on 1.29.12. Could it be that the file passed to the sourcemapper ('/home/weitjong/tmp/tmp4MwqzS/01_HelloWorld.bc.o.js.pp.js' in the issue description above) is invalid?

**Comment by weitjong** [comment]
Thanks for your reply. I have a chance today to perform an assert on emcc to verify that js_transform_tempfiles[0] (this list contains the '/home/weitjong/tmp/tmp4MwqzS/01_HelloWorld.bc.o.js.pp.js' in my issue description above). The assert passed, i.e. the file exists. I think the issue was/is the mapping in that file some how does not conform with what is being expected by ```SourceMapGenerator_validateMapping```.

**Comment by weitjong** [comment]
The ```SourceMapGenerator_validateMapping``` function throws an exception due to invalid pattern alright. For my case, it was caused by aOriginal.line = 0. For some reasons I have a lot of those. Below are just example.
```
function __GLOBAL__sub_I_HelloWorld_cpp() {
 var label = 0, sp = 0;
 sp = STACKTOP;
 ___cxx_global_var_init(); //@line 0 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/UI/../Graphics/../Math/Color.h"
 ___cxx_global_var_init1(); //@line 0 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/UI/../Graphics/../Math/Color.h"
 ___cxx_global_var_init3(); //@line 0 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/UI/../Graphics/../Math/Color.h"
 ___cxx_global_var_init5(); //@line 0 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/UI/../Graphics/../Math/Color.h"
 ___cxx_global_var_init7(); //@line 0 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/UI/../Graphics/../Math/Color.h"
 ___cxx_global_var_init8(); //@line 0 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/UI/../Graphics/../Math/Color.h"
 ```
There are plenty more from where it comes from. I am still new in Emscripten, so any pointer is much appreciated in how to trace this further. As said it worked fine in 1.29.

**Comment by weitjong** [comment]
I figured out how to configure the ```emsdk_manifest.json``` to install and activate ```sdk-1.29.0-64bit``` on my Linux box. I can confirm that this version indeed is able to generate source map for my sample project. Below is the corresponding snippet of the generated js file (without causing the issue as line number is greater than 0).
```
function __GLOBAL__I_a() {
 var label = 0, sp = 0;
 sp = STACKTOP;
 ___cxx_global_var_init(); //@line 55 "/home/weitjong/SDKs/urho3d/Urho3D/Source/Samples/01_HelloWorld/HelloWorld.cpp"
 ___cxx_global_var_init1(); //@line 55 "/home/weitjong/SDKs/urho3d/Urho3D/Source/Samples/01_HelloWorld/HelloWorld.cpp"
 ___cxx_global_var_init3(); //@line 55 "/home/weitjong/SDKs/urho3d/Urho3D/Source/Samples/01_HelloWorld/HelloWorld.cpp"
 ___cxx_global_var_init5(); //@line 55 "/home/weitjong/SDKs/urho3d/Urho3D/Source/Samples/01_HelloWorld/HelloWorld.cpp"
 ___cxx_global_var_init7(); //@line 55 "/home/weitjong/SDKs/urho3d/Urho3D/Source/Samples/01_HelloWorld/HelloWorld.cpp"
 ___cxx_global_var_init8(); //@line 55 "/home/weitjong/SDKs/urho3d/Urho3D/Source/Samples/01_HelloWorld/HelloWorld.cpp"
```

Comparing one of the function, ```___cxx_global_var_init()```, between 1.29.0 and 1.30.0 (or incoming) shows that they are almost identical.

**1.29.0**
```
function ___cxx_global_var_init() {
 var label = 0, sp = 0;
 sp = STACKTOP;
 __ZN6Urho3D10StringHashC2EPKc(8,84008); //@line 31 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/Core/CoreEvents.h"
 return; //@line 31 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/Core/CoreEvents.h"
}
```

**1.30.0**
```
function ___cxx_global_var_init() {
 var label = 0, sp = 0;
 sp = STACKTOP;
 __ZN6Urho3D10StringHashC2EPKc(8,16); //@line 31 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/Core/CoreEvents.h"
 STACKTOP = sp;return; //@line 31 "/home/weitjong/SDKs/urho3d/emscripten-Build/include/Urho3D/Core/CoreEvents.h"
}
```

This is where it gets difficult for me to investigate further without pointers from the experts.

**Comment by weitjong** [comment]
[Line 55 in "Source/Samples/01_HelloWorld/HelloWorld.cpp"](https://github.com/urho3d/Urho3D/blob/master/Source/Samples/01_HelloWorld/HelloWorld.cpp#L55)  is actually a comment lines, so ```1.29.0``` is not entirely correct either in this case. Since in ```1.30.0``` and above, the emitted debug info has line number equals to 0, I have taken advantage of that in my patch in the PR https://github.com/kripken/emscripten-fastcomp/pull/97. The patch makes the debug info only emits when the line number is greater than 0.
