### ISSUE TITLE
Add support for sysconf(_SC_PHYS_PAGES)

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3405]
Please add support for the `sysconf` argument `_SC_PHYS_PAGES` defined in `sys/sysinfo.h`.
The value returned could be `totalMemory` (as defined by preamble.js) divided by `PAGE_SIZE` (also defined by preamble.js).
Because there are programs that compute the available physical memory via `sysconf(_SC_PHYS_PAGES) * sysconf(_SC_PAGESIZE)`.

**Comment by kripken** [comment]
Fixed by that pull.
