### ISSUE TITLE
Accidentally printing the Module object to the node console takes AGES

### ISSUE THREAD

**Issue by fabiosantoscode** [kripken/emscripten#3416]
Since Module becomes very large even in small programs, accidentally logging Module to the console (which is too easy to do in an interactive session) takes a long time. I have to kill the node process, because I never actually saw it finish.

```
$ node
> // get Module somehow...
> Module  // Just typing this, pressing enter, will make your CPU fan spin up, while node appears to be frozen.
```

Node has a way to fix this, which am currently integrating in require-emscripten:

`Module.inspect = function () { return '[Object Module]' }`

This stops console.log and The above accidental log example from freezing everything and just show '[Object Module]'.

I would send a pull request but I'm not sure how to do this, because AFAIK the module's name is customizable (so it's not always Module).

**Comment by kripken** [comment]
I think you can just add that code in the NODE section in `src/shell.js`, on the `Module` object (it might have another name, but that one will always exist there).

**Comment by waywardmonkeys** [comment]
This can be closed I think. It was fixed by https://github.com/kripken/emscripten/pull/3426.
