### ISSUE TITLE
emcc 1.32.0 may generate invalid js code when compiling recent ffmpeg

### ISSUE THREAD

**Issue by duanyao** [kripken/emscripten#3430]
You can reproduce this issue as follows:

Download the llvm byte code of ffmpeg `ffmpeg.bc` [from here](https://github.com/duanyao/videoconverter.js/blob/em_bug/build_edge/dist_bad/ffmpeg.bc).

Compile to js with `-O3` or `-O2`, and run it with node.js:

```
emcc -O3 -o ffmpeg.js ffmpeg.bc
node ffmpeg.js
```
error output:
```
ffmpeg.js:15
608|0)==0;t=Hc+64|0;if(!(Z&65536)){o=tc;z=0}else{x=tc;z=0;while(1){(,)|0;(,)|0
                                                                    ^
SyntaxError: Unexpected token ,
```

If compile the `ffmpeg.bc` with `-O1`, this problem doesn't occur.

This `ffmpeg.bc` was compiled from latest ffmpeg source with almost all optional features enabled, and compiled with some third party libraries. If I disable large amount of features (third party libraries still enabled), this problem is also gone. However, I haven't figure out exactly which ffmpeg features trigger this problem.

Can you have a look at this?

**Comment by kripken** [comment]
Thanks for filing, I fixed this on incoming now. Was a strange corner case with eliminatable non-side-effect math calls. I'm surprised we didn't see it earlier in fuzzing, but somehow it went unnoticed.

**Comment by duanyao** [comment]
Thanks for the quick fix. Now latest ffmpeg run smoothly :).
