### ISSUE TITLE
Test failure: other.test_llvm_nativizer

### ISSUE THREAD

**Issue by ehsan** [kripken/emscripten#344]
$ EM_SAVE_DIR=1 EMCC_DEBUG=1 tests/runner.py other.test_llvm_nativizer
Running Emscripten tests...
(Emscripten: Running sanity checks)
test_llvm_nativizer (**main**.other) ... 
emcc invocation:  /home/ehsan/moz/emscripten/emcc /tmp/emscripten_temp/files.cpp -c 
emcc: compiling to bitcode
emcc: compiling source file:  /tmp/emscripten_temp/files.cpp
emcc running: /home/ehsan/clang+llvm-3.0-x86_64-linux-Ubuntu-11_10/bin/clang++ -c -m32 -U__i386__ -U__x86_64__ -U__i386 -U__x86_64 -U__SSE__ -U__SSE2__ -U__MMX__ -UX87_DOUBLE_ROUNDING -UHAVE_GCC_ASM_FOR_X87 -DEMSCRIPTEN -U__STRICT_ANSI__ -U__CYGWIN__ -D__STDC__ -Xclang -triple=i386-pc-linux-gnu -nostdinc -nostdinc++ -Xclang -nobuiltininc -Xclang -nostdinc++ -Xclang -nostdsysteminc -Xclang -isystem/home/ehsan/moz/emscripten/system/include -Xclang -isystem/home/ehsan/moz/emscripten/system/include/bsd -Xclang -isystem/home/ehsan/moz/emscripten/system/include/libc -Xclang -isystem/home/ehsan/moz/emscripten/system/include/libcxx -Xclang -isystem/home/ehsan/moz/emscripten/system/include/gfx -Xclang -isystem/home/ehsan/moz/emscripten/system/include/net -Xclang -isystem/home/ehsan/moz/emscripten/system/include/SDL -U__APPLE__ -emit-llvm -c /tmp/emscripten_temp/files.cpp -o /tmp/tmpGgDxWQ/files.o
bc => clean bc
bc => s
s => o
/tmp/emscripten_temp/files.o.s: Assembler messages:
/tmp/emscripten_temp/files.o.s:10: Error: invalid instruction suffix for `push'
/tmp/emscripten_temp/files.o.s:13: Error: invalid instruction suffix for`push'
/tmp/emscripten_temp/files.o.s:16: Error: invalid instruction suffix for `push'
/tmp/emscripten_temp/files.o.s:23: Error: bad register expression
/tmp/emscripten_temp/files.o.s:25: Error: bad register expression
/tmp/emscripten_temp/files.o.s:25: Error: register save offset not a multiple of 8
/tmp/emscripten_temp/files.o.s:27: Error: bad register expression
/tmp/emscripten_temp/files.o.s:31: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:40: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:46: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:49: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:53: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:57: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:60: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:69: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:78: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:87: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:93: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:103: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:111: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:114: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:117: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:119: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:122: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:131: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:137: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:146: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:150: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:156: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:158: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:160: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:162: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:165: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:171: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:177: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:181: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:185: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:190: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:197: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:200: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:203: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:210: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:214: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:228: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:231: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:240: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:248: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:253: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:258: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:264: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:269: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:274: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:280: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:285: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:290: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:296: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:301: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:304: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:307: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:311: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:314: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:317: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:325: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:329: Error: invalid instruction suffix for`call'
/tmp/emscripten_temp/files.o.s:334: Error: invalid instruction suffix for `call'
/tmp/emscripten_temp/files.o.s:337: Error: invalid instruction suffix for`pop'
/tmp/emscripten_temp/files.o.s:338: Error: invalid instruction suffix for `pop'
/tmp/emscripten_temp/files.o.s:339: Error: invalid instruction suffix for`pop'
o => runnable
g++-4.6.real: error: /tmp/emscripten_temp/files.o.o: No such file or directory
ERROR
# 
## ERROR: test_llvm_nativizer (**main**.other)

Traceback (most recent call last):
  File "tests/runner.py", line 6498, in test_llvm_nativizer
    output = Popen([os.path.join(self.get_dir(), 'files.o.run')], stdin=open(os.path.join(self.get_dir(), 'stdin')), stdout=PIPE, stderr=PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1239, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

---

Ran 1 test in 0.165s

FAILED (errors=1)

/tmp/emscripten_temp/files.o.s is https://gist.github.com/2293830

**Comment by juj** [comment]
Closing this as old.
