### ISSUE TITLE
LLVM intrinsic `llvm.assume` not lowered correctly

### ISSUE THREAD

**Issue by e45lee** [kripken/emscripten#3440]
When compiling clang against emscripten, I got a linker warning:
`warning: unresolved symbol: llvm_assume`

From the LLVM documentation: (http://llvm.org/docs/LangRef.html#llvm-assume-intrinsic)
"The llvm.assume allows the optimizer to assume that the provided condition is true. This information can then be used in simplifying other parts of the code."

I'm guessing that emscripten does not clear out llvm.assume calls when generating code.

I'm not able to give C/C++ code that will generate this linker error (as clang is large), but here's some LLVM assembly that does:

<pre>
; ModuleID = 'foo.bc'
target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

; Function Attrs: nounwind
define i32 @main() {
  %1 = call i8* @malloc(i32 4)
  %2 = ptrtoint i8* %1 to i1
  call void @llvm.assume(i1 %2)
  ret i32 5
}

declare i8* @malloc(i32)
declare void @llvm.assume(i1 %cond)
</pre>

Output when compiling through emcc: `warning: unresolved symbol: llvm_assume`

**Comment by kripken** [comment]
I'm curious how you got that to be emitted - it's the first I've heard about it actually. Are you using a new special builtin or something like that?

**Comment by e45lee** [comment]
Yeah, `llvm.assume` seems to be a new special builtin intrinsic introduced in 3.6 (the 3.5 docs don't mention it, the 3.6 docs do).

It's generated by a few optimization passes in llvm, it seems:
<pre>
./lib/Transforms/Utils/InlineFunction.cpp:626:/// add @llvm.assume-based alignment assumptions to preserve this information.
./lib/Transforms/Utils/PromoteMemoryToRegister.cpp:241:  /// A cache of @llvm.assume intrinsics used by SimplifyInstruction.
./lib/Transforms/Vectorize/LoopVectorize.cpp:963:  /// Values used only by @llvm.assume calls.
./lib/Transforms/Vectorize/SLPVectorizer.cpp:562:  /// Values used only by @llvm.assume calls.
</pre>

**Comment by kripken** [comment]
Got it, thanks. Ok, I fixed this on incoming, the backend will remove all uses of llvm.assume.
