### ISSUE TITLE
Rename {load,store}{X,XY,XYZ} to {load,store}{1,2,3} for SIMD?

### ISSUE THREAD

**Issue by duanyao** [kripken/emscripten#3444]
SIMD.js recently [renamed `{load,store}{X,XY,XYZ}` to `{load,store}{1,2,3}`](https://github.com/johnmccutchan/ecmascript_simd/commit/0a4ddf3252c67b01f793471a775a81d09b9346f8), and Firefox nightly implemented `{load,store}{1,2,3}` recently but not `{load,store}{X,XY,XYZ}`, so emscripten generated SIMD codes are no longer valid asm.js codes. Is it time to update?

**Comment by kripken** [comment]
cc @sunfishcode

**Comment by sunfishcode** [comment]
Yes, and the lane accessors are being changed, and movemask is being replaced with allTrue and friends. We have a bunch of things to do to get everything in sync with recent spec changes. I'm hoping we'll get everything updated soon.

**Comment by juj** [comment]
This was implemented a while back.
