### ISSUE TITLE
Feature request: store emcc compiler flags in js output

### ISSUE THREAD

**Issue by jvail** [kripken/emscripten#3448]
I seems to me that it would sometimes be helpful to have an option to query the build flags (memory limits, optimization flags etc.) in the compiled js file. Is that possible and potentially useful?

Thank you
Jan

**Comment by kripken** [comment]
There is `RETAIN_COMPILER_SETTINGS`, I don't remember exactly what it does, but look at `settings.js` and there might be a test too.

**Comment by jvail** [comment]
That's it! Thank you.
