### ISSUE TITLE
Event/callback when async operation is complete

### ISSUE THREAD

**Issue by bzwheeler** [kripken/emscripten#3451]
I am working on a fork of the [rfk/pypyjs](https://github.com/rfk/pypyjs) project (pypy in the browser) and have managed to compile it with the emterpreter-async option.  This lets me use emscripten_sleep to implement pythons `time.sleep` method without blocking the event loop however what I now need is a way to determine when the async code has completed and the 'asyncState' flag has been reset to 0.

The project creates a REPL style interface that lets a user execute python code which is done using a method in the exported module.  I need to know when the code has completed so I can know when it is safe to restart the REPL prompt.  I hacked in a solution by adding a getter for the asyncState variable and polling it until it is reset:

``` js
var res = Module._pypy_execute_source(code_ptr);
return new Promise(function(done, failed) {
  function checkAsyncState() {
    if (!Module.getAsyncState()) {
      Module._free(code_ptr);
      return done(res);
    }
    setTimeout(checkAsyncState, 10);
  }
  checkAsyncState();
});
```

While it works, what I'd really like is for some event to be triggered or some callback to fire whenever the emterpreter has finished.  Is this already possible?  Is there another approach I should be taking?

**Comment by kripken** [comment]
There is an internal API for this, append a function to `EmterpreterAsync.asyncFinalizers`. Those are called the next time that we finish all async operations.

Another option could be to add a little code at the end of `pypy_execute code`,

````
void pypy_execute_code() {
  // ... the normal code ..
  EM_ASM( PyPy.System.callback() );
}
````

which will call `PyPy.System.callback`, a JS function.
