### ISSUE TITLE
llvm.ctlz.i64 called with 3 arguments, instead of two.

### ISSUE THREAD

**Issue by e45lee** [kripken/emscripten#3458]
The intrinsic llvm.ctlz.i64 is lowered with 3 arguments, instead of two. 

This code:
<pre>
; ModuleID = 'tests/hello_world.bc'
target datalayout = "e-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-p:32:32:32-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

@.str = private unnamed_addr constant [19 x i8] c"hello, world %ld!\0A\00", align 1

define i32 @main() {
entry:
  %retval = alloca i32, align 4
  store i32 0, i32* %retval
  %call = call i64 @llvm.ctlz.i64(i64 109, i1 0)
  %call2 = call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([19 x i8]* @.str, i32 0, i32 0), i64 %call)
  ret i32 0
}

declare i32 @printf(i8*, ...)

declare i64 @llvm.ctlz.i64(i64, i1)
</pre>

Produces:
<pre>
function _main() {
 var $0 = 0, $1 = 0, $2 = 0, $3 = 0, $4 = 0, $5 = 0, $retval = 0, $vararg_buffer = 0, label = 0, sp = 0;
 sp = STACKTOP;
 STACKTOP = STACKTOP + 16|0; if ((STACKTOP|0) >= (STACK_MAX|0)) abort();
 $vararg_buffer = sp;
 $retval = 0;
 $0 = (_llvm_ctlz_i64(109,0,0)|0);
 $1 = tempRet0;
 $2 = $vararg_buffer;
 $3 = $2;
 HEAP32[$3>>2] = $0;
 $4 = (($2) + 4)|0;
 $5 = $4;
 HEAP32[$5>>2] = $1;
 (_printf((8|0),($vararg_buffer|0))|0);
 STACKTOP = sp;return 0;
}
</pre>

**Comment by e45lee** [comment]
I'm guessing this is the case as llvm.ctlz.i64 can take an optional second argument, and this isn't currently handed properly...

**Comment by kripken** [comment]
Thanks for filing, fixed on incoming and added this test.
