### ISSUE TITLE
WebIDL Binder not working quite as documented

### ISSUE THREAD

**Issue by rodneyrehm** [kripken/emscripten#3459]
For the following WebIDL

```idl
interface Emscripten_Sass_String : Emscripten_Sass {
  void Emscripten_Sass_String(DOMString value);
  attribute DOMString value;
};

```

`tools/webidl_binder.py` produces a glue.cpp that contains

```cpp
char* EMSCRIPTEN_KEEPALIVE emscripten_bind_Emscripten_Sass_String_get_value_0(Emscripten_Sass_String* self) {
  return self->value;
}
```

which fails compilation with the following error

```
emscripten_sass_values_glue.cpp:160:9: error: no viable conversion from 'string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'char *'
        return self->value;
               ^~~~~~~~~~~
```

Compilation succeeds only after fixing the glue.cpp as follows

```cpp
char* EMSCRIPTEN_KEEPALIVE emscripten_bind_Emscripten_Sass_String_get_value_0(Emscripten_Sass_String* self) {
  return strdup(self->value.c_str());
}
```

I can then instantiate that object by `var s = new Module.Emscripten_Sass_String("gustav");`, however cannot access the property `value` as expected (`s.value`) but have to go through the accessors `s.set_value("igor")` and `s.get_value()`.

Also I could not make the glue_wrapper.cpp thing work as [suggested in the docs](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#compiling-the-project-using-the-bindings-glue-code). First of all the compiler said it cannot find the file with angle includes and I should use quotes instead. Then I got duplicate symbol error for `array_bounds_check`. The only way I got it working was by adding the `#include`s to the glue.cpp itself.

What am I doing wrong here?

**Comment by kripken** [comment]
The original and the fixed glue look char-for-char identical?

We don't support `s.value` access, we've preferred to require a function call, to make it clear that it isn't a fast property access. However, we've considered changing that, I don't mind much either way.

It is expected that you need to add includes to the glue cpp file. We don't know where to find the headers. Typically you would write

````
#include my header
#include my other header

#include <glue.cpp>
````

**Comment by rodneyrehm** [comment]
> The original and the fixed glue look char-for-char identical?

I don't understand the question. Of course they don't, since I "fixed" the return type.

> We don't support s.value access, we've preferred to require a function call, to make it clear that it isn't a fast property access. However, we've considered changing that, I don't mind much either way.

accessing the attribute seems nicer, but I don't mind. I just did not expect it. As I have to pass the data from the worker to the main thread, I'll have to convert to different objects anyway…

> It is expected that you need to add includes to the glue cpp file

My glue_wrapper.cpp looked as follows:

```
#include "sass_values.h"
#include "emscripten_sass_values.hpp"
#include "emscripten_sass_values_glue.cpp"
```

**Comment by kripken** [comment]
Maybe I am losing my eyesight :) Is the return type not `char*` in both?

**Comment by rodneyrehm** [comment]
your eyesight is fine, but my copy-n-paste skills suck. I'm sorry, the original post was meant to say I changed the generated

```c
char* EMSCRIPTEN_KEEPALIVE emscripten_bind_Emscripten_Sass_String_get_value_0(Emscripten_Sass_String* self) {
  return self->value;
}
```

to the fixed

```c
char* EMSCRIPTEN_KEEPALIVE emscripten_bind_Emscripten_Sass_String_get_value_0(Emscripten_Sass_String* self) {
  return strdup(self->value.c_str());
}
```

i.e. turning `self->value` into `strdup(self->value.c_str())`.

**Comment by kripken** [comment]
I see. For us to do that automatically, we would need to be able to say in WebIDL, "this is a DOMString, and in the class it is not a `char*` but rather an `std::string`". We could add that in theory. But it leaks as you wrote it, and I'm not sure I can think of a good way to avoid that. It might be better for the class to manually convert to `char*`.

**Comment by rodneyrehm** [comment]
It's a good thing I don't feel embarassed about not having a clue what I'm doing. I finally understand what *I* was doing wrong, thank you! On to figuring out the next thing that is likely blaring obvious to anyone who actually knows what they're doing. Sorry for wasting your time, again.

**Comment by kripken** [comment]
No problem! Btw, if you have ideas for how the improve the docs, pulls for that that would be very much appreciated.

**Comment by rodneyrehm** [comment]
> Btw, if you have ideas for how to improve the docs, pulls for that would be very much appreciated.

I guess that depends on your target audience. If the goal is to make things accessible to people like me (knowing JS, having trouble with C/C++), a whole lot of example code might make things much less painful. But honestly, I'd tackle that later, when emscripten sort of matured a bit.

I was planning on writing up the stuff I learned from the libsass/sass.js thing, once I actually got things working the way I want it to. Maybe that'll yield something for the docs…

**Comment by jo-m** [comment]
I have worked around this problem by creating a string_wrapper class. This allows passing `std::string` as arguments as well as receiving them as return values. I believe its also leak-free (correct me if I'm wrong).

I am using the same file names as in [the docs](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#compiling-the-project-using-the-bindings-glue-code) for demonstration purposes.

`my_glue_wrapper.cpp`:

```
class string_wrapper: public std::string {
public:
	string_wrapper() {}

	string_wrapper(const char* s) {
		assign(s);
	}

	string_wrapper &operator=(const std::string &input) {
		assign(input);
		return *this;
	}
};

#include "glue.cpp"

```

In my `my_classes.idl`:

```
interface string_wrapper {
	void string_wrapper();
	void string_wrapper(DOMString s);
	[Const] DOMString c_str();
};

interface X {
    [Value] string_wrapper to_string();
};
```

C++ methods which take a `std::string` now need a wrapper which takes a `string_wrapper` instead. In Javascript, you can then receive and pass strings like this:
```

var fname = new Module.string_wrapper("Hello")
BlahWrapper.load(fname) // BlahWrapper was before defined in `my_glue_wrapper.cpp` and calls Blah.load(..)
console.log(X_instance.to_string().c_str())
```

**Comment by mmarczell-graphisoft** [comment]
> I see. For us to do that automatically, we would need to be able to say in WebIDL, "this is a DOMString, and in the class it is not a `char*` but rather an `std::string`". We could add that in theory. But it leaks as you wrote it, and I'm not sure I can think of a good way to avoid that. It might be better for the class to manually convert to `char*`.

Since Embind already has automatic conversion to/from std::string, how difficult it would be to do that now in WebIDL Binder?
