### ISSUE TITLE
"Too many open files" with llvm-ar

### ISSUE THREAD

**Issue by warrenseine** [kripken/emscripten#3460]
Hi,

I'm statically compiling DevIL (an image loader library), which has _many_ source files. I'm compiling on OS X with Emscripten 1.29.

Here's the command line: `/usr/local/emsdk/emscripten/1.29.0/emar rcs bin/html5/release/libminko-plugin-devil.a obj/html5/release/cmscam02.o obj/html5/release/cmscgats.o ...`

There are a total of 298 .o files to link.

Here's what I get: `/usr/local/emsdk/clang/e1.29.0_64bit/llvm-ar: obj/html5/release/il_rot.o: Too many open files.`

DevIL has always been pesky to compile but linking on OS X with Emscripten has never been an issue. I started noticing this today, but it may have been an issue for some time.

I will upgrade Emscripten and see if that's still an issue with recent builds.

**Comment by weitjong** [comment]
We had this error too when archiving Lua object files in our project. We solved it by increasing the soft limit in OS X host/build system with ```ulimit -Sn 512```. On OS X the default is only 256, while on Linux is 1024 (I think).

**Comment by warrenseine** [comment]
I confirm this works for me. Thanks a lot!
