### ISSUE TITLE
Read UTF-8 characters from a file

### ISSUE THREAD

**Issue by adenaman** [kripken/emscripten#3463]
Hi
We were having a problem reading characters with fscanf.

Code Example
```C
int main(){
	FILE* file;
	int i;
	char str[50], str2[50];
	file = fopen("data.txt", "r+");
	fscanf(file, "%i %s %s", &i, str, str2);
	printf("I got %i, then %s and %s", i, str, str2);
}
```

data.txt
```
10 € Lòr€mÍp$üm

```

Returning text:
```
I got 10, then â¬ and LÃ²râ¬mÃp$Ã¼m

```

This is because the file is parsed using String.fromCharCode()
https://github.com/kripken/emscripten/blob/master/src/library.js#L1842
````
          while ((curr < max_ || isNaN(max_)) && next > 0) {
            if (!(next in __scanString.whiteSpace) && // stop on whitespace
                (type == 's' ||
                 ((type === 'd' || type == 'u' || type == 'i') && ((next >= {{{ charCode('0') }}} && next <= {{{ charCode('9') }}}) ||
                                                                   (first && next == {{{ charCode('-') }}}))) ||
                 ((type === 'x' || type === 'X') && (next >= {{{ charCode('0') }}} && next <= {{{ charCode('9') }}} ||
                                   next >= {{{ charCode('a') }}} && next <= {{{ charCode('f') }}} ||
                                   next >= {{{ charCode('A') }}} && next <= {{{ charCode('F') }}}))) &&
                (formatIndex >= format.length || next !== format[formatIndex].charCodeAt(0))) { // Stop when we read something that is coming up
              buffer.push(String.fromCharCode(next));
              next = get();
              curr++;
              first = false;
            } else {
              break;
            }
```

The solution i found is:

```
          var bufferUTF = [];
          while ((curr < max_ || isNaN(max_)) && next > 0) {
            if (!(next in __scanString.whiteSpace) && // stop on whitespace
                (type == 's' ||
                 ((type === 'd' || type == 'u' || type == 'i') && ((next >= {{{ charCode('0') }}} && next <= {{{ charCode('9') }}}) ||
                                                                   (first && next == {{{ charCode('-') }}}))) ||
                 ((type === 'x' || type === 'X') && (next >= {{{ charCode('0') }}} && next <= {{{ charCode('9') }}} ||
                                   next >= {{{ charCode('a') }}} && next <= {{{ charCode('f') }}} ||
                                   next >= {{{ charCode('A') }}} && next <= {{{ charCode('F') }}}))) &&
                (formatIndex >= format.length || next !== format[formatIndex].charCodeAt(0))) { // Stop when we read something that is coming up
              bufferUTF.push(next);
              next = get();
              curr++;
              first = false;
            } else {
              buffer = buffer.concat(Module['UTF8ArrayToString'](bufferUTF, 0));
              break;
            }
          }
```
Result:
```
I got 10, then € and Lòr€mÍp$üm
```

This works, but don't check correctly the `curr`. '€' will count as 2 characters 
Also i guess there is a way to increase the performance, without the second buffer or `concat`

**Comment by kripken** [comment]
Perhaps `curr` could be decremented after calling `UTF8ArrayToString`?

**Comment by adenaman** [comment]
`curr` is used to stop the loop and don't read too many characters. So if i want to read 1 character of "€" I will only read 1 byte, not the complete character

The other option is to increase `curr` after the `UTF8ArrayToString` or just concat the number of characters needed.
Then there will be a chance to read too many characters when you only need few. 
For example: I want to read 2 characters of a big big big string. This will read all the string parse it to UTF8 and only then add the first two and ignore others.

There is also the get() and unget() functions that we need to control, so we don't read too much, use few and forget about others.

Maybe a solution will be:
Loop
-try `UTF8ArrayToString` ( 1 byte )
-if that returns a character then:
--add character to return buffer
--curr++
--break loop
-else (it is not a good character):
--`UTF8ArrayToString` with 1 more byte

Still not a good performance solution at all.

Also `UTF8ArrayToString` only work with well formed arrays?
https://github.com/kripken/emscripten/blob/master/src/preamble.js#L496

```
    u0 = u8Array[idx++];
    if (!u0) return str;
```
with an incorrect array without `'\0'` ending, this will loop out of bounds of array.
So that maybe will need to check
`if (idx > array length) return "";`

**Comment by kripken** [comment]
Another option here is for emscripten to use more musl code for file access. An experiment with that is happening in #2701. I tested the `musl-syscall` branch being worked on there, and it can run this testcase properly.

**Comment by kripken** [comment]
That merged to incoming, so this should now be ok.
