### ISSUE TITLE
emscripten_async_wget2() does not overwrite files

### ISSUE THREAD

**Issue by elvissteinjr** [kripken/emscripten#3469]
Despite what the documentation claims, emscripten_async_wget2() does not overwrite already existing files. Instead, it throws an exception with the message "Error: File exists".

emscripten_async_wget() also throws, but does overwrite the file.

**Comment by kripken** [comment]
Thanks for filing, this should be fixed on incoming. Please verify.

**Comment by elvissteinjr** [comment]
Everything appears to be fixed on incoming. Thanks.
