### ISSUE TITLE
Cannot compile zlib from upstream

### ISSUE THREAD

**Issue by socketpair** [kripken/emscripten#3470]
I'm trying to compile zlib-1.2.8 downloaded from zlib.net

$ emmake make
..../src/jsqemu/emsdk_portable/emscripten/master/emcc -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -o libz.so.1.2.8 adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo zutil.lo compress.lo uncompr.lo gzclose.lo gzlib.lo gzread.lo gzwrite.lo  -lc 
ERROR    root: adler32.lo: Input file has an unknown suffix, don't know what to do with it!

$ ls -l adler32.*o
-rw-r--r-- 1 anya anya 3632 мая   24 10:21 adler32.lo
-rw-r--r-- 1 anya anya 3576 мая   24 10:21 adler32.o

$ file adler32.*o
adler32.lo: LLVM IR bitcode
adler32.o:  LLVM IR bitcode

$ emcc --version
emcc (Emscripten GCC-like replacement) 1.32.0 (commit b3efd9328f940034e1cab45af23bf29541e0d8ff (HEAD, tag: refs/tags/1.32.0, refs/remotes/origin/master, refs/remotes/origin/HEAD, refs/heads/master))

**Comment by socketpair** [comment]
Exactly the same when compiling https://github.com/emscripten-ports/zlib

**Comment by kripken** [comment]
What is an `.lo` file? I wonder why it is emitting those...

**Comment by socketpair** [comment]
I dont know. I just follow instructions from documentation to setup emscripten. Is it reproducible on your machine?

**Comment by ZengruiWang** [comment]
Same issue. I found that .lo files are generate in Makefile.in

**Comment by kripken** [comment]
Are `.lo` files something to do with translations? Might need to disable that feature. Otherwise, I'm still confused why `.lo` files get sent into `emcc` - does `gcc` know how to do something with them?

**Comment by ZengruiWang** [comment]
I am not very familiar with Linux and I search the `.lo` file and found that .lo file is a library object, which may be built into a shared library. 
And also when I use the flag `USE_ZLIB=1` there is also errors which may indicated failure of building zlib.

INFO     root: (Emscripten: Running sanity checks)
WARNING  root: building port: zlib...
Traceback (most recent call last):
  File "/home/zewang/emsdk_portable/emscripten/master/emcc", line 1067, in <module>
    args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
  File "/home/zewang/emsdk_portable/emscripten/master/emcc", line 1050, in get_bitcode_args
    args = system_libs.process_args(args, shared.Settings)
  File "/home/zewang/emsdk_portable/emscripten/master/tools/system_libs.py", line 894, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "/home/zewang/emsdk_portable/emscripten/master/tools/ports/zlib.py", line 16, in process_args
    get(ports, settings, shared)
  File "/home/zewang/emsdk_portable/emscripten/master/tools/ports/zlib.py", line 10, in get
    ['libz.a'])]
  File "/home/zewang/emsdk_portable/emscripten/master/tools/system_libs.py", line 871, in build_project
    return shared.Cache.get(name, create)
  File "/home/zewang/emsdk_portable/emscripten/master/tools/cache.py", line 38, in get
    shutil.copyfile(temp, cachename)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/zewang/.emscripten_cache/ports-builds/zlib/libz.a'

**Comment by kripken** [comment]
Ok, looks like `.lo` files are PIC objects. Always something new to learn about in unix-land I guess :) To get emcc to support them, we just need

````
diff --git a/emcc b/emcc
index 0559dd6..4b9caf2 100755
--- a/emcc
+++ b/emcc
@@ -59,7 +59,7 @@ CXX_ENDINGS = ('.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.i
 OBJC_ENDINGS = ('.m', '.mi')
 OBJCXX_ENDINGS = ('.mm', '.mii')
 SOURCE_ENDINGS = C_ENDINGS + CXX_ENDINGS + OBJC_ENDINGS + OBJCXX_ENDINGS
-BITCODE_ENDINGS = ('.bc', '.o', '.obj')
+BITCODE_ENDINGS = ('.bc', '.o', '.obj', '.lo')
 DYNAMICLIB_ENDINGS = ('.dylib', '.so') # Windows .dll suffix is not included in this list, since those are never linked to directly on the command line.
 STATICLIB_ENDINGS = ('.a',)
 ASSEMBLY_ENDINGS = ('.ll',)
````

I'll push that to incoming later today with a test; right now I am trying to stabilize incoming to merge to master.

**Comment by kripken** [comment]
Pushed.

**Comment by ZengruiWang** [comment]
Hi, I just updated my emscripten this morning. I could build the zlib in /master/zlib successfully. But when I am still having trouble of installing the lib.using ./embuilder.py build zlib. The error message is as follows:

/home/zewang/.emscripten_cache/ports-builds/zlib/compress.c:9:10: fatal error: 'zlib.h' file not found
#include "zlib.h"
         ^
1 error generated.
/home/zewang/.emscripten_cache/ports-builds/zlib/adler32.c:8:10: fatal error: 'zutil.h' file not found
#include "zutil.h"
         ^
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
1 error generated.

**Comment by kripken** [comment]
That command works for me on latest incoming, and on the bots. Which
version are you on?

- Alon

**Comment by ZengruiWang** [comment]
The Emscripten version is:
emcc (Emscripten gcc/clang-like replacement) 1.33.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 2a66b5ffba63f1e36458d41fafc2874a1abf63fe) (https://github.com/kripken/emscripten-fastcomp/ e2939f6878307899c17d1a23f51ba3fe5afbe6af)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)

I updated my emscripten using 
./emsdk update
./emsdk install latest
./emsdk activate latest
Thank you!

**Comment by kripken** [comment]
Strange. Perhaps try emcc --clear-cache --clear-ports ?

- Alon

**Comment by ZengruiWang** [comment]
It works! Thank you!
