### ISSUE TITLE
OpenGL ES 3.0 / core desktop GL way of retrieving extension information

### ISSUE THREAD

**Issue by mosra** [kripken/emscripten#3472]
In OpenGL ES 3.0 (and GL 3.0+) it is possible to retrieve extension list like this:

    GLint count;
    glGetIntegerv(GL_NUM_EXTENSIONS, &count);
    for(int i = 0; i != count; ++i)
        extensions.add(glGetStringi(GL_EXTENSIONS, i));

Looking at the current code in [library_gl.js](https://github.com/kripken/emscripten/blob/615a04ef4deadc99b25d0d7e47659d6593761946/src/library_gl.js#L950) it looks like WebGL is indeed providing the extension list as an array, but the code then joins it to one large string to support ES2/GL2.1 usage via `glGetString(GL_EXTENSIONS)`. Would it be possible to support also the above usage for better compatibility with ES 3.0 code that's being ported to WebGL 2?

One reason `glGetStringi()` is used instead of the original `glGetString(GL_EXTENSIONS)` is that the original way is no longer available in core desktop OpenGL and thus using it harms portability.

Thank you!

**Comment by juj** [comment]
Your comments are accurate, this is a feature we haven't implemented yet. For GLES3/WebGL2 support we will have to implement that form of extension querying. However this will not be available when targeting GLES2/WebGL1, although that is probably not a concern for you?

**Comment by mosra** [comment]
I still need to use `glGetString(GL_EXTENSIONS)` in GLES2/WebGL1 path to stay compatible with native GLES2 implementations, so yes, that's not a concern for me.

**Comment by gouletr** [comment]
Bump, I'm running into the same issue. Would prefer to have `glGetStringi` available if this is possible. Thanks!

**Comment by juj** [comment]
@gouletr: Are you building a WebGL2/GLES3 targeting application? Native GLES2/WebGL1 does not have the function `glGetStringi`.

**Comment by gouletr** [comment]
Yes, we are targeting WebGL2/GLES3.

**Comment by gouletr** [comment]
@juj Thanks for the fix! I will use it right away! :+1:

**Comment by mosra** [comment]
@juj Awesome! Thank you! :+1:

**Comment by juj** [comment]
This was merged in the above PR.
