### ISSUE TITLE
TypeError: callback is undefined

### ISSUE THREAD

**Issue by michaKFromParis** [kripken/emscripten#3474]
Hi,

In between switching to SDL and upgrading to the incoming branch,
our builds stop working and I get a **TypeError: callback is undefined** at initialization.
Indeed, callRuntimeCallbacks receives an array containing a single undefined element. 

```javascript
function callRuntimeCallbacks(callbacks) {
  while(callbacks.length > 0) {
    var callback = callbacks.shift();
    if (typeof callback == 'function') {
      callback();
      continue;
    }
    var func = callback.func;
```

Any idea where I should look ?

Best,

M

**Comment by juj** [comment]
Try printing a stack trace e.g. with `console.error(new Error().stack);` in that function when it receives the bad array to see which array has the bad data, and trace it up from there. Does that help?

**Comment by michaKFromParis** [comment]
Thanks for your help. I juste investigated a bit more and realized my own preMain callback was badly registered and the reason why I didn't have any rendering was completely unrelated.
