### ISSUE TITLE
streaming audio broken with SDL2?

### ISSUE THREAD

**Issue by jarikomppa** [kripken/emscripten#3477]
Hi, I'm using SDL's audio callback mechanism to stream audio. It used to work (http://sol.gfxile.net/ld30/full/ld30.html), but when I try to compile with the current head version I get no sound (apart from random clicks) on firefox, and broken audio on chrome (playing too fast?). I get the same result if I use SDL or SDL2.

**Comment by kripken** [comment]
Do you see this across multiple browsers?

If yes, then we might have broken something not tested in our test suite. Do you have a testcase?

**Comment by jarikomppa** [comment]
My test case currently is rather large, I'll build a smaller one sometime today.

**Comment by jarikomppa** [comment]
Minimal test worked, I'll have to divide and conquer to find what's causing the problem - I'll close this for now.

**Comment by jarikomppa** [comment]
Okay, I found the issue: if I remove "-s USE_SDL=2" from the project, audio starts working. So, I'm unsure whether this bug belongs here or somewhere else..

Build command:
```
emcc -o test.html main.cpp -O2 -s USE_SDL=2
```

Source:
```
#include <stdlib.h>
#if defined(_MSC_VER)
#include "SDL.h"
#else
#include "SDL2/SDL.h"
#endif
#include <math.h>
#include <stdio.h>

#ifdef __EMSCRIPTEN__
#include "emscripten.h"
#endif

void audiomixer(void *userdata, Uint8 *stream, int len)
{
	int samples = len / 4;
	short *buf = (short*)stream;

	int i;
	for (i = 0; i < samples*2; i++)
	{
		buf[i] = i * 655;
	}
}

int sdlstatic_init(unsigned int aSamplerate, unsigned int aBuffer)
{
	SDL_AudioSpec as;
	as.freq = aSamplerate;
	as.format = AUDIO_S16;
	as.channels = 2;
	as.samples = aBuffer;
	as.callback = audiomixer;

	SDL_AudioSpec as2;
	if (SDL_OpenAudio(&as, &as2) < 0)
	{
		return -1;
	}

	SDL_PauseAudio(0);

	return 0;
}	

void mainloop()
{
	// Poll for events, and handle the ones we care about.
	SDL_Event event;
	while (SDL_PollEvent(&event)) 
	{
		switch (event.type) 
		{
		case SDL_KEYUP:
			// If escape is pressed, return (and thus, quit)
			switch (event.key.keysym.sym)
			{
			case SDLK_ESCAPE:
				{
					exit(0);
				}
				break;
			}
			break;
		case SDL_QUIT:
		    SDL_CloseAudio();
			exit(0);
		}
	}
}

int main(int argc, char *argv[])
{	
	if ( SDL_Init(SDL_INIT_EVERYTHING) < 0 ) 
	{
		fprintf(stderr, "Unable to init SDL: %s\n", SDL_GetError());
		exit(1);
	}	

	atexit(SDL_Quit);	
	
	sdlstatic_init(44100, 1024);

#ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(mainloop, 60, 0);
#else
    while (1)
    {
        mainloop();
    }
#endif

	return 0;
}
```
As I said, if SDL2 is changed to SDL ("SDL2/SDL.h" -> "SDL/SDL.h" and "-s USE_SDL=2" removed), audio works.

**Comment by jarikomppa** [comment]
Is there a workaround - can I use SDL2 but not SDL2's audio somehow?

**Comment by Daft-Freak** [comment]
Test is working for me. I did have to change `SDL_INIT_EVERYTHING` though (no thread support, so timer subsystem fails to init)

**Comment by jarikomppa** [comment]
That's odd. I'm building under ubuntu with emsdk updated & activated to latest.

**Comment by jarikomppa** [comment]
Tried:
- emsdk update
- emsdk install latest
- emsdk activate latest
- source emsdk_env.sh
- changed the SDL_INIT_EVERYTHING to SDL_INIT_AUDIO
- recompiled
Still doesn't work.

**Comment by Daft-Freak** [comment]
Strange. I've just tried exactly that and it worked. (https://db.tt/gFD3vCp1).

emcc --version: 1.32.0

**Comment by jarikomppa** [comment]
I get the same version from emcc, but on the "positive" side, your
generated page doesn't work for me in firefox, and the tone is too high in
chrome (win7 64bit).

**Comment by Daft-Freak** [comment]
The different tone in chrome is because when the second argument to SDL_OpenAudio is non-NULL, SDL is allowed to chose a different frequency than the one specified and it chooses to match chrome's default.

**Comment by jarikomppa** [comment]
Facts:
- Audio works fine across browsers with emscripten's SDL1 audio.
- My actual application takes whatever sample rate SDL2 reports as the actual sample rate and runs with it, and it plays too fast (and 'broken', as in 'not cleanly') on chrome.
- On firefox, SDL2 doesn't seem to play anything, except for random clicks that mess up windows' audio (causing other programs to go silent for a while and then fade back). There seems to be some correlation between sample values played and the frequency of these clicks, but I don't know exactly what it is (quiet sounds 'click' less than sounds that use the whole sample range). In any case, the 'clicks' occur about once per second or less frequently.
- The same behavior can be seen whether I compile the app or you do, so it's not just my system building it.
- This reminds me of how emscripten's streaming audio was broken early on, and my stance then was to just wait it out, and it did get fixed eventually - whether it was browsers getting fixed and/or emscripten, I don't know.
- Desktop SDL2 builds of these applications play audio just fine - I use SDL2 as my primary audio back-end at the moment.

So I reiterate - is there a workaround? Can I use emscripten-SDL2 otherwise but use audio either using emscripten's SDL1 or through some separate API? If the answer is "no", I'll just write a simple sdl1 example for emscripten use and move on.

**Comment by Daft-Freak** [comment]
No, you can't use SDL1 audio with SDL2. What might be happening is that it might be returning a different format to what was requested. To prevent it from doing that you could try `SDL_OpenAudioDevice(NULL, 0, &want, &have, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE);` to only allow freq changes.

**Comment by jarikomppa** [comment]
I peeked at the emscripten-sdl2 source, and noticed that web audio wants floats. So, I changed the test to feed floats to sdl2 instead, and firefox audio works. This suggests that something is off in the conversion side.

**Comment by jarikomppa** [comment]
..and yeah, it's possible that sdl2 returns that it wants some other format, like float, and who knows what the audio sinks in browsers do when they've fed random data as floats..

**Comment by Daft-Freak** [comment]
Yeah, it's switching the format to floats. I have no idea how it was working here. Something like

```
int sdlstatic_init(unsigned int aSamplerate, unsigned int aBuffer)
{
    SDL_AudioSpec as;
    as.freq = aSamplerate;
    as.format = AUDIO_S16;
    as.channels = 2;
    as.samples = aBuffer;
    as.callback = audiomixer;

    SDL_AudioSpec as2;
    //if (SDL_OpenAudio(&as, &as2) < 0)
    int dev = SDL_OpenAudioDevice(NULL, 0, &as, &as2, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE);
    if(dev == 0)
    {
        printf("Err %s\n", SDL_GetError());
        return -1;
    }

    printf("freq %i, %i\n", as.freq, as2.freq);
    printf("format %i, %i\n", as.format, as2.format);
    printf("channels %i, %i\n", as.channels, as2.channels);
    printf("samples %i, %i\n", as.samples, as2.samples);

    //SDL_PauseAudio(0);
    SDL_PauseAudioDevice(dev, 0);

    return 0;
}   
```

works consistently.

**Comment by jarikomppa** [comment]
Yup. Firefox:

Field | Wanted | Got
---- | ------ | -----
freq | 44100 |48000
format | 32784 | 33056
channels	| 2 | 2
samples |1024|1024

So, yeah. Sorry to have been a nuissance. I'll just have to make my sdl2 code more robust =)

**Comment by jarikomppa** [comment]
So yeah, works:
http://dl.dropboxusercontent.com/u/75238938/soloud/monotone.html

**Comment by rhinoid** [comment]
Sorry to drop a msg here. But for future reference to someone else banging their head on the computer trying to figure this one out (Like I have):   If you don't use the deprecated SDL_OpenAudio but use SDL_OpenAudioDevice instead with the flag '0' which means don't allow format changes, then you WILL get a deviceID, but this deviceID does NOT work and it will never call the callback method to get the buffer filled.

So I still consider this a bug as this does work on desktop SDL builds. 

So work-around now is to allow for formatchanges (or just use the old method) and convert formats on the fly where needed yourself

**Comment by Daft-Freak** [comment]
That does sound like a bug, I can't reproduce it though. Also, it sounds like a different bug to this one ("bad" audio vs no audio)
