### ISSUE TITLE
OpenAL typedef redefinition with different types

### ISSUE THREAD

**Issue by ZengruiWang** [kripken/emscripten#3481]
Hi, 
I am working on building the openAL library, but I encountered a problem as follows:

..\Emscripten\emscripten\1.30.0\system\include\AL\al.h(88,21): error : typedef redefinition with different types ('signed char' vs 'char')
1>  typedef signed char ALbyte;
1>                      ^
1>  ..\vhcl\openal\include\al.h(48,14):  note: previous definition is here
1>  typedef char ALbyte;

It seems like the different definition makes the building failed. Is there any way that I could fix it?
Thank you!

**Comment by juj** [comment]
OpenAL does not need to be built from source in Emscripten. Instead it is provided internally by the Emscripten repository, including the headers. Or are you specifically trying to do a second port of the library and explicitly override the one that Emscripten is providing?

**Comment by ZengruiWang** [comment]
Hi,
It seems like my version of OpenAL has a different typedef of the one in Emscripten, I replaced my version with Emscripten's al.h alc.h and no errors.
Thank you!
