### ISSUE TITLE
cxxabi lib not in default include paths?

### ISSUE THREAD

**Issue by Phyks** [kripken/emscripten#3484]
Hi,

It seems the `cxxabi.h` header is not in default include paths. When compiling 
```c++
#include <cxxabi.h>
int main() {
   return 0;
}
```

I get
```zsh
test.cpp:7:10: fatal error: 'cxxabi.h' file not found
#include <cxxabi.h>
         ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
zsh: exit 1     em++ test.cpp -o test.html
```

Manually adding `-I/usr/lib/emscripten/system/lib/libcxxabi/include/` solves the problem, but I am not sure it is really safe. This header file is needed to build Google Testing Framework unittests for example.

Thanks

**Comment by kripken** [comment]
I am not sure it is safe to do so. Does it work when you call methods of `libcxxabi`? which methods does that project need?

**Comment by Phyks** [comment]
I am not sure to understand your first question. The concerned file is https://code.google.com/p/googletest/source/browse/trunk/include/gtest/internal/gtest-type-util.h from google testing framework, for the use of the `libcxxabi`.

**Comment by arielm** [comment]
Hi there,

GoogleTest is making use of `__cxa_demangle`, which is [implemented in emscripten-fastcomp](https://github.com/kripken/emscripten-fastcomp/blob/222fcc59cbd2445e496f67de33e9717220bfc142/tools/llvm-symbolizer/LLVMSymbolize.cpp#L503) (which itself [relies on GoogleTest](https://github.com/kripken/emscripten-fastcomp/tree/master/utils/unittest/googletest) :)

Now when buidling GoogleTest with Emscripten:

I can confirm that [GTEST_HAS_RTTI](https://github.com/arielm/googletest/blob/emscripten/include/gtest/internal/gtest-type-util.h#L65) is properly defined, and that tests based on [GetTypeName<T>](https://github.com/arielm/googletest/blob/emscripten/test/gtest-unittest-api_test.cc#L192) are producing similar results on Emscripten and OSX.

**Comment by kripken** [comment]
I see, thanks.

I think the best thing is to just make that project add an `"-I" + shared.path_from_root('system', 'include', 'libcxxabi', include')` (where `shared` is emscripten's `shared` python module). That feels better than emscripten enabling that by default, because `libcxxabi` has a lot more things than name mangling, probably most of which do not work. (Emscripten internally uses the name mangling and dynamic casting functionalities, which are known to work.)

**Comment by Phyks** [comment]
Hmm, not 100% sure about it but that would mean adding `-I/usr/lib/emscripten/system/lib/libcxxabi/include/` to the `emcc` command line is ok, right?

**Comment by kripken** [comment]
If emscripten is in `/usr/lib/emscripten` then yes.

**Comment by Phyks** [comment]
Ok. Thanks!
