### ISSUE TITLE
Error using std::tr1::shared_ptr

### ISSUE THREAD

**Issue by ZengruiWang** [kripken/emscripten#3486]
I am using `std::tr1::shared_ptr` in my project, but when building it with Emscription, it gave me the error message as follows:
->error : no member named 'tr1' in namespace 'std'
Should I use boost shared pointer instead?
Thanks!

**Comment by kripken** [comment]
If that isn't in our `libc++` headers, you might need to bundle those headers yourself, from boost or some other source, yes.
