### ISSUE TITLE
"getTypeName is not defined" when calling C function

### ISSUE THREAD

**Issue by dsvensson** [kripken/emscripten#3487]
I recently tried to update my emscripten build of game-music-emu to latest with the help of _embind_ and when calling the function like this:

```
var payload = new Uint8Array(this.response);
var ref = Module.allocate(1, "i32", Module.ALLOC_STACK);
var samplerate = 44100;
if (Module.gme_open_data(payload, payload.length, ref, samplerate) != 0)
    console.error("could not load data", payload);
```

I get the following error:

```
Uncaught ReferenceError: getTypeName is not defined
```

Which happens during construction of the error message passed to a _UnboundTypeError_. So even if the original problem would disappear, there would still be an exception thrown.

For reference, I used to call this function in my old (~2 years ago maybe) emscripten build via:

```
Module.ccall("gme_open_data", "number",
             ["array", "number", "number", "number"],
             [payload, payload.length, ref, samplerate]) 
```

The _embind_ C++ code looks like this:

```
#include <emscripten/bind.h>
#include "gme.h"

using namespace emscripten;

EMSCRIPTEN_BINDINGS(Gme) {
    function("gme_open_data", &gme_open_data, emscripten::allow_raw_pointers());
    ....
}
```

And the _gme_open_data_ prototype looks like this:

```
gme_err_t gme_open_data( void const* data, long size, Music_Emu** out, int sample_rate );
```

Where _Music_Emu_ is an opaque type (actually a C++ class, but the API is C), and _gme_err_t_ is a _const char *_.

I built this (https://bitbucket.org/mpyne/game-music-emu) with:

```
~/bin/emsdk_portable/emscripten/master/em++ -O0 --bind -std=c++11 -o out.js *.cpp
```

In the _gme_ sub-directory of the git-repo, where I added my _Emscripten.cpp_ file with the _EMSCRIPTEN_BINDINGS_ declaration.

emscripten version is:

```
emcc (Emscripten GCC-like replacement) 1.32.0
    (commit b3efd9328f940034e1cab45af23bf29541e0d8ff
        (HEAD -> master, tag: 1.32.0, origin/master, origin/HEAD))
```

**Comment by dsvensson** [comment]
Ok, so the problem that led me here can be avoided ccall/cwrap, together with EMSCRIPTEN_KEEPALIVE, but I guess it's still a bug that it produced invalid JavaScript code.

**Comment by GuillaumeLeclerc** [comment]
I get the same error.

**Comment by kripken** [comment]
Should now be fixed.
