### ISSUE TITLE
Compile .cxx and .cc files in Visual Studio 2010

### ISSUE THREAD

**Issue by ZengruiWang** [kripken/emscripten#3490]
Hi, I would like to ask does Emscripten support compiling .cc and .cxx files? When building either files, I got the error message: 
GCCCOMPILE : error : invalid argument '-std=c++03' not allowed with 'C/ObjC'
GCCCOMPILE : error root: compiler frontend failed to generate LLVM bitcode, halting

Thank you!

**Comment by juj** [comment]
Emscripten does support compiling these extensions, see https://github.com/kripken/emscripten/blob/incoming/emcc#L58 . It is possible that this is a limitation of the vs-tool plugin. Can you try building from the command line?

**Comment by ZengruiWang** [comment]
Hmm...Currently, I am using google's protocol buffer to generate `.pb.h` and `.pb.cc` files, for example `helloworld.pb.h` and `helloworld.pb.cc`, then how do I build these files using emscripten? Using emcc?

Thank you!

**Comment by juj** [comment]
Yes, you can do `emcc helloworld.pb.cc ...` to compile the files from the command line. I think if you do that, you will get the same error message that you did when changing the extension to `.cpp`. The error is  like stated, protobuf source tree doesn't recognize Emscripten. This will require you to configure/set up/adapt protobuf for the Emscripten environment. Try backtracking the error message and see what assumptions it makes, and how to apply the correct ones to Emscripten. If necessary, the Emscripten compiler can be detected at compile time via a `#ifdef __EMSCRIPTEN__` preprocessor directive.

**Comment by ZengruiWang** [comment]
Indeed, the same error. I finally found that there is a c-version of protobuf call `protobuf-c` and I saw an online article which indicated a successful compilation. Apart from debug the error above, I will also try the C version. 

Thank you very much!

**Comment by ZengruiWang** [comment]
Good news! I found an repo on Github which has already configure the [protobuf for Emscripten](https://github.com/artillery/protobuf-emscripten). I those changes to my project, it works!
