### ISSUE TITLE
Implement support for PROXY_TO_WORKER and pthreads.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3496]
The flags `-s USE_PTHREADS=1` and `--proxy-to-worker` are now mutually exclusive, but enabling them together will allow more interesting proxying options.

This has the potential of allowin main thread to runny fully synchronously, while effectively postMessageing via SharedArrayBuffer instead of using browser events. This might be a separate build option "--double-proxy-to-worker" or similar.

**Comment by awtcode** [comment]
@juj can I check if this request is supported in Emscripten and most major browsers now? e.g. Chrome, Firefox

**Comment by juj** [comment]
This was implemented some time ago in #4372, which added the support for combining `-s USE_PTHREADS=1` with `--proxy-to-worker`.

@awtcode : this bug entry does not relate to browser support, just the feature to chain these two flags together when building code in Emscripten (to enable SharedArrayBuffer when proxying the main thread to a worker). SharedArrayBuffer is not yet shipped with stable browser versions, but Firefox Nightly has it, and Chrome Canary too, but there one has to enable it via command line flag iirc.
