### ISSUE TITLE
Option(s) to not include Javascript libraries

### ISSUE THREAD

**Issue by michalc** [kripken/emscripten#3512]
It appears that many Javascript libraries are always included unconditionally in [`module.js`](https://github.com/kripken/emscripten/blob/1.33.1/src/modules.js#L119):

    libraries = libraries.concat([
      'library_sdl.js',
      'library_gl.js',
      'library_glut.js',
      'library_xlib.js',
      'library_egl.js',
      'library_jansson.js',
      'library_openal.js',
      'library_glfw.js',
      'library_uuid.js',
      'library_glew.js',
      'library_html5.js',
      'library_signals.js',
      'library_idbstore.js',
      'library_async.js',
      'library_vr.js'
    ]).concat(additionalLibraries);

There are a few options already to control some of them, `NO_FILESYSTEM` and `NO_BROWSER`, but I would like to not include others that I'm not using. SDL, GL and HTML5 are examples that I think I'm not using, and I suspect I'm not using others as well.

Can there be an option for each to exclude them? Or, perhaps a way to only include libraries that are specifically needed?

**Comment by kripken** [comment]
Their contents are only included if actually used, as in, an undefined symbol is provided by them. Did you see them appear unnecessarily in your output?

**Comment by michalc** [comment]
Ah: I'm saw lots of code with "SDL", or "WebGl" references in the minified version, and I assumed. Looking further, It just seems to have a fair bit of code that tests for their existence. My bad.
