### ISSUE TITLE
Document creating an ArrayBuffer val

### ISSUE THREAD

**Issue by iboB** [kripken/emscripten#3515]
I have existing code that works with array buffers. There are ways to convert them to strings from JS to C++, but there doesn't seem to be a way to do the opposite (while it could be very easy to do).

A constructor to `val` like `static val array_buffer(char* buf_ptr, uint32_t size);` or something similar would be very nice.

Right now a way to work around this is by having the memory allocated in the js code, then passed to C++ by a function like `extern "C" void fill_buf(char* data)` to be filled.

**Comment by iboB** [comment]
Actually the undocumented typed_memory_view does just that. You should add it to the docs, because it does some awesome work.

**Comment by kripken** [comment]
Reopening for the docs aspect.

**Comment by cwoffenden** [comment]
I recall poking around to get this to work a while ago and finding `memory_view` in `wire.h`. A simple example converting a char buffer to an `ArrayBufferView` would be:
```
#include <val.h>
#include <wire.h>
using namespace emscripten;

char buf[] = {4, 3, 2, 1};
val myView = val(typed_memory_view(sizeof(buf), buf));
```
The first parameter to `typed_memory_view` expects the number of elements, not bytes, which needs taking into consideration when creating a typed array of floats, for example.
