### ISSUE TITLE
glfwOpenWindow causes js exception ReferenceError: GL is not defined

### ISSUE THREAD

**Issue by xcodedave** [kripken/emscripten#3530]
I'm trying to use GLFW to open a window, however I keep hitting the same issue.
It seems to be caused by calling glfwOpenWindow.

Here is some code which reproduces the issue:
```
#include<stdio.h>
#include<stdlib.h>
#include<emscripten/emscripten.h>
#define GLFW_INCLUDE_ES2 
#include<GL/glfw.h>

int main() {
  	printf("main function started\n");
    if (glfwInit() != GL_TRUE) {
        printf("glfwInit() failed\n");
        glfwTerminate();
    } else {
        printf("glfwInit() success\n");
		if (glfwOpenWindow(640, 480, 8, 8, 8, 8, 16, 0, GLFW_WINDOW) != GL_TRUE){
			printf("glfwOpenWindow() failed\n");
			glfwTerminate();
		} else {
		  printf("glfwOpenWindow() success\n");
		}
    }
	return EXIT_SUCCESS;
}

```
And here are the version details as reported by my emsdk installation:
```
./emcc -v
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.30.0
clang version 3.5.0 
Target: x86_64-apple-darwin14.4.0
Thread model: posix
```

**Comment by kripken** [comment]
Thanks, fixed on incoming. We were missing a dependency on GL (which we need to open the context). This only happens if GL is not pulled in for another reason - like having a `gl*` call somewhere - which is why this wasn't noticed before.

**Comment by xcodedave** [comment]
Awesome - thanks for checking this out! I only caught it as I was verifying my build step by step. On to adding some gl* calls next! :D
