### ISSUE TITLE
Pass --max-old-space-size to underlying node call in emcc

### ISSUE THREAD

**Issue by andrenatal** [kripken/emscripten#3540]
When optimizing with -O3, after more than 30 minutes building, nodejs get out-of-memory and compilation exits with:

CALL_AND_RETRY_2 Allocation failed - process out of memory

So, is there some way to to pass --max-old-space-size=4000 to node under emcc?

**Comment by kripken** [comment]
Which version of emscripten is this with? In newers ones, node is used a lot less, or not at all, in `-O3` with default settings.

You can add parameters to node by adjusting `NODE_JS` in `~/.emscripten`. Just use a vector, `NODE_JS = ['nodejs', '--arg']`.

**Comment by andrenatal** [comment]
His Alon, this worked for me, so will close it out, ok?
