### ISSUE TITLE
Installation fails on fresh 14.04 Ubuntu VM: Clang error

### ISSUE THREAD

**Issue by ashes999** [kripken/emscripten#3543]
Hi,

I'm trying to install emscripten on a brand-new (64-bit) 14.04 VM. I get an error about 64-bit integers being unavailable on my platform. Here's a partial stack trace:

```
emsdk_portable/clang/fastcomp/build_master_64/include/llvm/Support/DataTypes.h:77:3: error: #error "Don't have a definition for uint64_t on this platform"
 # error "Don't have a definition for uint64_t on this platform"
   ^
make[2]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o] Error 1
make[1]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/all] Error 2
make: *** [all] Error 2
```

I believe this is an upstream `clang` build error. Google leads me to believe this is some kind of source version mismatch.

Instead of trying `install latest`, is there a way I can specify known, working versions of `emscripten` and `clang`?

**Comment by kripken** [comment]
Emscripten's clang and LLVM repos are snapshots of known working versions. If this is an upstream bug, it is one that is in a version of LLVM and clang that is considered stable.

Moving to an older version of emscripten might help, but just by going back in LLVM and clang history to before the regression happened upstream, if this is a regression.

I believe the SDK has a way to do that, but I'm not sure how, maybe `--help` would say.

**Comment by ashes999** [comment]
`./emsdk list --old` lists the versions. I was able to install 1.30 by specifying the version.

There's also a package someone uploaded which I can get through `apt`.

Thanks for your help.
