### ISSUE TITLE
Change arguments between calls

### ISSUE THREAD

**Issue by andrenatal** [kripken/emscripten#3544]
I am not being able to change the arguments between multiple Module.callMain(). 

Is this the right way to change the argument set: Module.arguments = ['new_arg'] ? When I change this way, does not reflect on the module that keeps the same of fist run.

**Comment by kripken** [comment]
The best thing, as always, is to read the source :) It's just JavaScript. I didn't remember this code myself, so I had to read it too. Looks like in the code for callMain you can see that it receives the arguments as a parameter. In other words, simply call `Module.callMain(['new_arg'])`.
