### ISSUE TITLE
code miscompiled at -Os and -O3 on x86_64-unknown-linux-gnu 

### ISSUE THREAD

**Issue by zhendongsu** [kripken/emscripten#3549]
The following code (small.c) seems to be miscompiled by emscripten at -Os and -O3 (this might be related to https://github.com/kripken/emscripten/issues/3520, which has been fixed): 

```
struct S0
{
  long long f0;
  volatile short f1;
  unsigned f2;
  unsigned f3;
} a, b;

volatile struct S0 c;

int d;
unsigned e;
short f;

int
fn1 ()
{
  char g = 0;
  if (a.f3 ^ f)
    {
      if (a.f0)
	f && c.f2;
      else
	return g;
      b.f1;
    }
  return f;
}

int
main ()
{
  unsigned h = fn1 ();
  d = e = h;
  return 0;
}
```

$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 3d7aff0906f41c562d70c6e0483012de758f9bfa) (https://github.com/kripken/emscripten-fastcomp/ dccd6517fcc00126e4e74d77c5a8fa06efd3a2ad)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
$ 
$ emcc -O1 small.c
$ node a.out.js
 
$ emcc -O2 small.c
$ node a.out.js
 
$ 
$ emcc -Os small.c
$ node a.out.js
/data2/c-hunter/test/javascript-nor/RES/bug19/15/a.out.js:5
>16;if((d|0)!=(a|0)){d=8;if((c[d>>2]|0)==0&(c[d+4>>2]|0)==0)a=0;else}else a=d;
                                                                    ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
$ 
$ emcc -O3 small.c
$ node a.out.js
/data2/c-hunter/test/javascript-nor/RES/bug19/15/a.out.js:5
>16;if((d|0)!=(a|0)){d=8;if((c[d>>2]|0)==0&(c[d+4>>2]|0)==0)a=0;else}else a=d;
                                                                    ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
$

**Comment by kripken** [comment]
I can't reproduce that on 1.34.0. Might be like in that other issue, where I need you to send the emcc temp files, because LLVM differences on our machines somehow make the bug only show up on yours.

**Comment by zhendongsu** [comment]
Here it is Alon: https://dl.dropboxusercontent.com/u/10788753/pr3549-emscripten_temp.zip

**Comment by kripken** [comment]
Thanks! Ok, I pushed a commit to incoming which should fix that. Let's see if the bots are ok with it.

Note I didn't bump the version yet, you need to `emcc --clear-cache` to force a rebuild of the optimizer to see the change.

**Comment by kripken** [comment]
Looks good on bots.
