### ISSUE TITLE
Exposing OpenAL functions to JavaScript

### ISSUE THREAD

**Issue by mispy** [kripken/emscripten#3562]
This is a bit of an odd use case, but I've found that by using EXPORTED_FUNCTIONS in conjunction with USE_SDL I can cause emscripten to expose SDL functions for direct use by external javascript. However, this trick doesn't with with OpenAL. Is there an alternative?

**Comment by kripken** [comment]
Do you mean with `USE_SDL=2` Or 1?

If 2, then this would make sens, exported functions does not export js library functions (which is what OpenAL is). But, I see no reason not to support that, so if that is indeed the issue here, we can fix it.

**Comment by mispy** [comment]
USE_SDL=2, yep! Ideally for my use case I'd be able to call JS library functions using Module.ccall, though I'm not sure that makes a great deal of sense.

**Comment by kripken** [comment]
Looking into this a little more, you just need to add the function to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`. The `EXPORTED_FUNCTIONS` list just exports, it doesn't pull in code from js libraries, which is what the former does. Note there is no `_` prefix on the former (one isn't needed, as it is unambiguously a js library func).

**Comment by mispy** [comment]
that did the trick. thanks for your help!

I might suggest mentioning DEFAULT_LIBRARY_FUNCS_TO_INCLUDE alongside EXPORTED_FUNCTIONS on http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html in case anyone has a similar problem :)

**Comment by kripken** [comment]
Added to docs.
