### ISSUE TITLE
unresolved symbol: remquo (musl missing?)

### ISSUE THREAD

**Issue by dead** [kripken/emscripten#3563]
Shouldn't that be available?

And another unrelated question, when using a pre-js script, my embed files not work.
```
if (typeof(Module) === "undefined") Module = {};

Module.preRun = function() {
	FS.mkdir('/working');
	FS.mount(NODEFS, {root: '.'}, '/working');
};
```

**Comment by kripken** [comment]
Looks like we don't include that part of musl. It is present in the `musl-syscalls` branch, but it isn't clear if that will be merged or not. If not we can add that separately.

Can you please file a separate issue for the second topic, with a full standalone testcase?

**Comment by dead** [comment]
I think that since the [remainder](https://github.com/kripken/emscripten/blob/master/system/lib/libc/musl/src/math/remainder.c#L4) was included and it use remquo, the remquo should also be included.
And ok, sorry :+1:

**Comment by kripken** [comment]
`musl-syscalls` was merged, so this should be ok now on incoming.
