### ISSUE TITLE
Skipping drawing in WebGLWorker proxied frames can result in nothing rendered

### ISSUE THREAD

**Issue by hoongern** [kripken/emscripten#3567]
This commit attempts to skip `drawArrays`/`drawElements` in all but the last `commandBuffer`, however, this makes the assumption that each `commandBuffer` is a complete frame. 

The [`eglSwapBuffers`](https://github.com/kripken/emscripten/blob/2643bd9513638ea32f8023c153f50d2564745a5f/src/library_egl.js#L563-L583) method calls `Browser.doSwapBuffers` (which is set to [`postRAF`](https://github.com/kripken/emscripten/blob/2643bd9513638ea32f8023c153f50d2564745a5f/src/webGLWorker.js#L1018)), which posts the current `commandBuffer`. However, it then calls [`.isContextLost`](https://github.com/kripken/emscripten/blob/2643bd9513638ea32f8023c153f50d2564745a5f/src/library_egl.js#L572) which queues a single command in the command buffer. `WebGLWorker` then proceeds to call [`postRAF();`](https://github.com/kripken/emscripten/blob/2643bd9513638ea32f8023c153f50d2564745a5f/src/webGLWorker.js#L1028). The result is that `WebGLClient` can end up with a `commandBuffers` where the first element is the 'full' frame, and the 2nd element is the single `isContextLost` command. Since the 1st element is not 'drawn', nothing gets rendered.

I'm currently working around this issue by removing the [`postRAF`](https://github.com/kripken/emscripten/blob/2643bd9513638ea32f8023c153f50d2564745a5f/src/webGLWorker.js#L1028) call in `window.requestAnimationFrame`. My project uses the `USE_SDL=2` option for the emscripten SDL port.

**Comment by kripken** [comment]
Definitely sounds like a bug, but I don't think I fully understand the issue yet. Can you perhaps create a testcase showing the issue? Then when we fix it we can also add it to the test suite.

**Comment by hoongern** [comment]
Here's some simple test code:
```
#include <SDL.h>
#include <emscripten.h>

SDL_Window* window;
SDL_Renderer* renderer;

void frame()
{
	static int x = 0;
	static int y = 0;
	SDL_Rect rect;
	rect.x = x;
	rect.y = y;
	rect.w = 100;
	rect.h = 100;

	SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
	SDL_RenderClear(renderer);
	SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
	SDL_RenderFillRect(renderer, &rect);
	SDL_RenderPresent(renderer);

	x = (x + 2) % 540;
	y = (y + 1) % 380;
}

int main()
{
	SDL_Init(SDL_INIT_VIDEO);
	window = SDL_CreateWindow("test", 0, 0, 640, 480, SDL_WINDOW_OPENGL);
	renderer = SDL_CreateRenderer(window, 0, SDL_RENDERER_ACCELERATED);
	SDL_GL_SetSwapInterval(1);
	emscripten_set_main_loop(frame, -1, true);
}
```
When compiled with `emcc test.cpp -s USE_SDL=2 -o test.html` it works as expected. However, with `emcc test.cpp --proxy-to-worker -s USE_SDL=2 -o test.html` the rectangle flashes

**Comment by kripken** [comment]
Thanks for the testcase. I fixed this in that commit, which will merge to incoming shortly.

**Comment by kripken** [comment]
Merged to incoming.
