### ISSUE TITLE
WebGLWorker bindTexture fails with null texture

### ISSUE THREAD

**Issue by hoongern** [kripken/emscripten#3569]
bindTexture can be called with `texture = null` ([here](https://github.com/kripken/emscripten/blob/master/src/library_gl.js#L1080)), which then [fails](https://github.com/kripken/emscripten/blob/master/src/webGLWorker.js#L825). Should be easily fixed by checking `if (texture)` first.

**Comment by kripken** [comment]
Thanks fixed on incoming with a test.
