### ISSUE TITLE
Freetype break when compiled with O1 / O2

### ISSUE THREAD

**Issue by dead** [kripken/emscripten#3576]
Seems related to issue #0324

Using the current freetype from test FT_Stroker work when compiled with O0, but when compiled with O1/O2 it produce a wrong result.

A test case that address this problem:
http://puu.sh/iAMqG/b49fa696fe.zip

In newer version of freetype (2.6) FT_Stroker in O0 produces a very strange result, and with O1/O2 it produce similar results as the older library in these modes.

O0 / O2
![out](https://cloud.githubusercontent.com/assets/2395791/8326554/433a6700-1a38-11e5-8d1f-a1737059b08a.png)

**Comment by kripken** [comment]
In `tests/test_core.py` we have `test_freetype`, could you perhaps provide a diff that adds to that test something showing this issue? That way it is easiest for us to reproduce, and when we fix it, it already has a regression test.

**Comment by dead** [comment]
The diff: https://gist.github.com/dead/e8734193b74d0f84a008
main_4.cpp and ref.tga in http://puu.sh/iAMqG/b49fa696fe.zip

**Comment by kripken** [comment]
1. What is the part with `POST_RUN_ADDITIONS` that you added? Wouldn't that affect the other tests before it?
2. Why is there an `.a` / `.so` change?
2. It doesn't seem to work here. Both with `.a` or `.so`, it fails even in `-O0` (which you said should work). I get

````
$ ./tests/runner.py test_freetype
test_freetype (test_core.default) ... (checking sanity from test runner)
INFO     root: (Emscripten: Running sanity checks)
outlining: 0
<building and saving freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 into cache> 
warning: Output contains some very large functions (3650 lines in _printf_core), consider building source files with -Os or -Oz, and/or trying OUTLINING_LIMIT to break them up (see settings.js; note that the parameter there affects AST nodes, while we measure lines here, so the two may not match up)
outlining: 5000
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
[issue 324]
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
[issue 324 case 2]
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
[issue 324 case 3]
[issue 3576]
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
Failed to find proper image output in: 
ERROR

======================================================================
ERROR: test_freetype (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alon/Dev/emscripten/tests/test_core.py", line 5750, in test_freetype
    post_build=post, output_nicerizer=image_compare_freetype)
  File "/home/alon/Dev/emscripten/tests/runner.py", line 506, in do_run
    js_output = self.run_generated_code(engine, filename + '.o.js', args, output_nicerizer=output_nicerizer, assert_returncode=assert_returncode)
  File "/home/alon/Dev/emscripten/tests/runner.py", line 305, in run_generated_code
    ret = output_nicerizer(out, err)
  File "/home/alon/Dev/emscripten/tests/test_core.py", line 5733, in image_compare_freetype
    js_data = eval(m.group(0))
AttributeError: 'NoneType' object has no attribute 'group'

----------------------------------------------------------------------
Ran 1 test in 67.689s

FAILED (errors=1)
````

**Comment by dead** [comment]
1. No. Because `do_run` use `assertContained` and the `Module.print()` will be empty in the other tests.
2. When I use the .a I get: 
```
[issue 3576]
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
warning: unresolved symbol: FT_Get_Glyph
warning: unresolved symbol: FT_Stroker_Set
warning: unresolved symbol: FT_Stroker_Done
warning: unresolved symbol: FT_Done_Glyph
warning: unresolved symbol: FT_Stroker_New
warning: unresolved symbol: FT_Glyph_StrokeBorder
Failed to find proper image output in: -1
ERROR
```
\3. I was having this same issue but in reverse, all cases it was working... Fixed it executing `emmake make clean` in the `tests/freetype` folder. Don't know why it would make any difference but it does.

**Comment by kripken** [comment]
Ok, looks like we need to figure out 2 and 3 in order for me to reproduce this problem. Or perhaps find another way to add it to the test suite.

**Comment by dead** [comment]
Just realized that my modules.cfg differs from master.
So to exclude Any other difference I deleted the freetype folder then downloaded it from master.
Then I ran the test and got de same results as before...

```
test_freetype (test_core.default) ... (checking sanity from test runner)
INFO     root: (Emscripten: Running sanity checks)
outlining: 0
<building and saving freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 into cache> 
warning: Output contains some very large functions (3641 lines in _printf_core), consider building source files with -Os or -Oz, and/or trying OUTLINING_LIMIT to break them up (see settings.js; note that the parameter there affects AST nodes, while we measure lines here, so the two may not match up)
outlining: 5000
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
[issue 324]
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
[issue 324 case 2]
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
[issue 324 case 3]
[issue 3576]
<load freetype_g_8ec1e0ccaffc96a6eb6d5a530bbc2221 from cache> 
ok

----------------------------------------------------------------------
Ran 1 test in 60.054s

OK
```
```
test_freetype (test_core.asm2) ... (checking sanity from test runner)
INFO     root: (Emscripten: Running sanity checks)
outlining: 0
<building and saving freetype_O2_bd82d6778c6d15b8746c1a32290da1a0 into cache> 
outlining: 5000
<load freetype_O2_bd82d6778c6d15b8746c1a32290da1a0 from cache> 
[issue 324]
<load freetype_O2_bd82d6778c6d15b8746c1a32290da1a0 from cache> 
[issue 324 case 2]
<load freetype_O2_bd82d6778c6d15b8746c1a32290da1a0 from cache> 
[issue 324 case 3]
[issue 3576]
<load freetype_O2_bd82d6778c6d15b8746c1a32290da1a0 from cache> 
FAIL

======================================================================
FAIL: test_freetype (test_core.asm2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dead/Desktop/emsdk_portable/emscripten/master/tests/test_core.py", line 5724, in test_freetype
    post_build=post_out, output_nicerizer=image_compare_freetype)
  File "/home/dead/Desktop/emsdk_portable/emscripten/master/tests/runner.py", line 506, in do_run
    js_output = self.run_generated_code(engine, filename + '.o.js', args, output_nicerizer=output_nicerizer, assert_returncode=assert_returncode)
  File "/home/dead/Desktop/emsdk_portable/emscripten/master/tests/runner.py", line 305, in run_generated_code
    ret = output_nicerizer(out, err)
  File "/home/dead/Desktop/emsdk_portable/emscripten/master/tests/test_core.py", line 5714, in image_compare_freetype
    assert(len(js_data) == len(true_data))
AssertionError

----------------------------------------------------------------------
Ran 1 test in 59.524s

FAILED (failures=1)
```

I was trying to figure out why the .a library was not working, so I put the new test in front of the others and it worked. No clue why this happens, any ideia?

I really don't know why the test is not working there.
Try manual compiling the `freetype` and see the result from it
```
echo "if (typeof(Module) === 'undefined') Module = {}; Module.preRun = function() { FS.mkdir('/wd'); FS.mount(NODEFS, {root: '.'}, '/wd'); }; " > pre.js
emmake make clean
emconfigure ./configure
emmake make
em++ -Iinclude/ objs/.libs/libfreetype.so main_4.cpp -o main4O0.js --pre-js pre.js
nodejs main4O0.js wd/LiberationSansBold.ttf wd/O0.tga
emmake make clean
emconfigure ./configure CFLAGS="-O1"
emmake make
em++ -O1 -Iinclude/ objs/.libs/libfreetype.so main_4.cpp -o main4O1.js --pre-js pre.js
nodejs main4O1.js wd/LiberationSansBold.ttf wd/O1.tga
emmake make clean
rm pre.js
```

Executing this I get two different results, and O0 being right

**Comment by kripken** [comment]
No idea why the `.a` or the order would matter, very strange...

**Comment by juj** [comment]
As a random aside (perhaps related?), did you patch freetype to fix the function pointer signatures issues:  see e.g. https://github.com/juj/emscripten-freetype/commit/5af357ae531632a4ea4991863f4ba77c3366eda2 . Also, if the issue still persists, try building with `-s SAFE_HEAP=1` to check whether there might be some odd code in FreeType that dependend on alignment.

**Comment by dead** [comment]
1. did you patch freetype to fix the function pointer signatures
Yes, the freetype in `tests/freetype` from master is patched.

2. Also, if the issue still persists, try building with `-s SAFE_HEAP=1`
Didn't work.

I think I found out the problem with the `libfreetype.a`
http://stackoverflow.com/questions/26888332/static-freetype-has-dependencies-libfreetype-6-dylib

Since this problem can be avoided using the `libfreetype.so` I don't think this is related with the main problem.

**Comment by Kagami** [comment]
I'm using freetype 2.6 + asm.js patch, libass fonts branch, ffmpeg 2.7.2 + vf_subtitles, all compiled with -O3, and haven't encountered any issues with hardsubbing. Though I haven't tested it heavily yet.
