### ISSUE TITLE
emscripten broken on Windows 7?

### ISSUE THREAD

**Issue by qwertie** [kripken/emscripten#3579]
I installed emsdk-1.30.0-web-64bit.exe this morning and got the following error while trying to compile a hello-world program:

    D:\Dev>emcc hello.c
      File "C:\Program Files\Emscripten\emscripten\1.30.0\\emcc", line 150
        ''' % (open(shared.path_from_root('site', 'build', 'text', 'docs', 'tools_reference', 'emcc.txt')).read())
          ^
    SyntaxError: invalid syntax

**Comment by qwertie** [comment]
Never mind! This problem is fixed by running the same command under the "Emscripten Command Prompt" in the Start Menu. (Whoa - hello world produces over 10,000 lines of output!)

**Comment by kripken** [comment]
See the FAQ for ways to reduce that, but yes, hello world needs printf, stdio, malloc, etc., a full C runtime basically...
