### ISSUE TITLE
FS readdir does not work properly with UTF-8 filenames

### ISSUE THREAD

**Issue by fdelapena** [kripken/emscripten#3584]
It is stripping higher bytes with the `charCodeAt()` way.
The following monkey patch uses `stringToUTF8()`: EasyRPG/Player#508
It is needed to make [this demo](https://easy-rpg.org/play/?game=yume_nikki) work properly.

**Comment by kripken** [comment]
It would be good to test this against the `musl_syscall` branch, where I think this should work.

**Comment by kripken** [comment]
(see #2701)

**Comment by kripken** [comment]
That branch merged, so this should be ok now.

**Comment by fdelapena** [comment]
I didn't have time to rebuild the toolchain before, sorry.
Looks like it is failing [yet](https://easy-rpg.org/play/index-pr.html?game=yume_nikki).

**Comment by kripken** [comment]
Could you make a small standalone testcase showing the issue?

**Comment by fdelapena** [comment]
OK, we'll need to provide another one first, as it is currently failing on a previous assert with lstat() (which was working fine before), best probably on a separated issue.

**Comment by fdelapena** [comment]
Finally we worked around this issue by simplifying our file finder code
https://github.com/EasyRPG/Player/pull/806/commits/87cea3dbbbc67e6223addca4687fa5c917a36822
