### ISSUE TITLE
Async Results Callback for Ccall and Cwrap for Emterpreter-Async

### ISSUE THREAD

**Issue by zz85** [kripken/emscripten#3596]
Actually, this could be 2 suggestions

a) would it be possible to get async support for cwrap eg.

``` js
var int_sqrt = Module.cwrap('int_sqrt', 'number', ['number'], { async: true })

int_sqrt()
```

b) get return values from async ccalls and cwraps 

for example,

``` js
// ccall
var ccaller = Module.ccall('method', 'number', ['string'], [args], { async: function(number) {
  // done
} });

// cwrap
cwrapper = Module.cwrap('int_sqrt', 'number', ['number'], { async: onComplete })

// or

cwrapper = Module.cwrap('int_sqrt', 'number', ['number'], { async: true })

cwrapper(function(number) {
  // async results.
})
```

possibly related: #3307

**Comment by kripken** [comment]
Is this meant in the context of asyncify and/or emterpreter-async?

**Comment by zz85** [comment]
yes i came upon this use case trying emterpreter-async. it isn't really a show stopper for me (i could add additional callbacks from C and wrap these JS functions in more functions) but I guessing it would be convenient to extend ccall and cwrap to support async return values.

**Comment by kripken** [comment]
Got it. Yes, I agree, this would be nice to add, and probably not that hard, although I am not 100% sure.

**Comment by curiousdannii** [comment]
A pull request has just been made: #6586

**Comment by markmarucot** [comment]
Thanks @curiousdanni!

**Comment by krzkaczor** [comment]
Should this be closed then @curiousdannii @kripken? Thanks for this contribution btw. :)

**Comment by kripken** [comment]
Looks like this can be closed, yeah, thanks.
