### ISSUE TITLE
Doc: Missing instruction to install CMake prerequisite on OS X

### ISSUE THREAD

**Issue by davidfstr** [kripken/emscripten#3600]
Clear instructions to install the following prerequisites are missing from the main [OS X installation instructions](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#windows-osx-and-linux-installing-the-portable-sdk):

* Install Xcode, including the command line tools.
* Install CMake.

The requirement to install Xcode is fairly standard on OS X systems, but would be good to mention for clarity. CMake on the other hand is special and definitely should be mentioned.

I do notice however that these missing steps *are* detailed in the installation instructions for [building from source](http://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_mac_os_x.html).

**Comment by kripken** [comment]
Thanks, I added some stuff from that other section. I almost merged them, but I noticed that they have some internal differences.
