### ISSUE TITLE
Can not install SDK - Ubuntu 15.05

### ISSUE THREAD

**Issue by fidian** [kripken/emscripten#3601]
When I try to use `emsdk install latest` I receive errors about "Manifest error: No tool by name 'clang-tag-1.34.1-64bit'".  I have installed cmake, build-essential, node (from PPA but `nodejs` works from command line), java, python 2.7.

I can run the update

```
09:54 slate:~/Vault/emscripten$ ./emsdk update
Downloading: /home/fidian/Vault/emscripten/zips/emsdk_unix_update.tar.gz from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_unix_update.tar.gz
Unpacking '/home/fidian/Vault/emscripten/zips/emsdk_unix_update.tar.gz' to '/home/fidian/Vault/emscripten'
emsdk_portable/emscripten-tags.txt
emsdk_portable/emsdk
emsdk_portable/emsdk_env.sh
emsdk_portable/emsdk_manifest.json
emsdk_portable/README.md
Fetching all tags from Emscripten Github repository...
Done. 36 tagged releases available, latest is 1.34.1.
```

Running the install fails.

```
09:54 slate:~/Vault/emscripten$ ./emsdk install latest
Installing SDK 'sdk-tag-1.34.1-64bit'..
Manifest error: No tool by name 'clang-tag-1.34.1-64bit' found! This may indicate an internal SDK error!
Traceback (most recent call last):
  File "./emsdk", line 1734, in <module>
    sys.exit(main())
  File "./emsdk", line 1717, in main
    success = tool.install()
  File "./emsdk", line 1007, in install
    success = tool.install()
AttributeError: 'NoneType' object has no attribute 'install'
```

I tried installing clang and llvm to no avail, then later removed both packages.

**Comment by zjhlogo** [comment]
I have the same problem.
but, finally I found out there is a spelling bugs in file emsdk_manifest.json

replace the line 1093:
    "uses": ["clang-tag-%tag%-64bit", "emscripten-tag-%tag%-64bit"],
to
    "uses": ["clang-tag-e%tag%-64bit", "emscripten-tag-%tag%-64bit"],

**Comment by fidian** [comment]
That change worked for me.  I don't see emsdk_manifest.json in this repository otherwise I'd make a pull request.  From where does that file come?

**Comment by fidian** [comment]
I think I found the repository and I've submitted a pull request.  I do not want to close this issue myself without getting confirmation that emsdk's official source is the repository I updated.  If that was the official place for emsdk, then this issue may be closed.

**Comment by cincodenada** [comment]
I just now downloaded from https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html and ran `emsdk update` and `emsdk install latest`, and still ran into this issue.  I added the character in the patch to the downloaded `emsdk_manifest.json` and all was well.

I realize it's been merged, but is there something that needs to be deployed/pushed/whatever to fix the emsdk_manifest.json that's being downloaded by the updater?  This is a tiny issue, but it effectively breaks the install for Linux users.

**Comment by kripken** [comment]
Note that @juj is currently on vacation, might be 2 weeks til he can respond to these SDK issues.

**Comment by juj** [comment]
Thanks for catching this, and very sorry about the typo! Updated packages are now pushed and they should fix the Linux issue.

**Comment by cincodenada** [comment]
Awesome, thanks for the update!
