### ISSUE TITLE
rounf() function doesn't really rounds some numbers

### ISSUE THREAD

**Issue by alekzander2005** [kripken/emscripten#3608]
Code below can demonstrate this issue:
```C++
#include <cstdio>
#include <cmath>

int main()
{
 float a = 102;
 a /= 256;
 a *= 100;
 printf("%f\n", a);
 a = roundf(a);
 printf("%f\n", a);
 return 0;
}
```
If compiled with MinGW(gcc 4.8.1) it prints out:
39.843750
40.000000

Although if compiled with Emscripten (emcc 1.34.1) result differs:
39.843750
39.843750

**Comment by kripken** [comment]
JS numeric precision is double by default. Building with `-s PRECISE_F32=1` makes this work as expected. See http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-i-get-odd-rounding-errors-when-using-float-variables
