### ISSUE TITLE
Porting UDP network code

### ISSUE THREAD

**Issue by VinnyVicious** [kripken/emscripten#3610]
Is it possible to port UDP network code to emscripten? I wasn't able to find anything in the manual or the forums about this. Does it have an abstraction layer, or do we have to write emscripten-specific code on top of our network abstraction?

**Comment by kripken** [comment]
See `test_enet`, it tests ENet, a UDP-using library. It should work out of the box, using websockets, assuming the code using sockets asynchronously.
