### ISSUE TITLE
emsdk install latest fails with 'NoneType' object has no attribute 'install' on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by davidfstr** [kripken/emscripten#3612]
Received an internal error while attempting to install Emscripten on a representative Linux system, the latest long-term-support release of Ubuntu, while following the [standard installation instructions](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#all-os-installation-instructions-portable-sdk).

Repro steps:
* Provision a Ubuntu 14.04 LTS virtual machine.
* wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
* tar xzf emsdk-portable.tar.gz
* cd emsdk-portable
* sudo apt-get update
* sudo apt-get install build-essential cmake nodejs default-jre git-core
    * Python 2.7 is already installed by default, so it is not included in this install command.
    * Git is incorrectly indicated as an *optional* prerequisite by the build instructions, since the following `emsdk update` command requires it.
* ./emsdk update
* ./emsdk install latest

The final command fails with the following error:

```
parallels@ubuntu:~/pkgs/emsdk_portable$ ./emsdk install latest
Installing SDK 'sdk-tag-1.34.1-64bit'..
Manifest error: No tool by name 'clang-tag-1.34.1-64bit' found! This may indicate an internal SDK error!
Traceback (most recent call last):
  File "./emsdk", line 1734, in <module>
    sys.exit(main())
  File "./emsdk", line 1717, in main
    success = tool.install()
  File "./emsdk", line 1007, in install
    success = tool.install()
AttributeError: 'NoneType' object has no attribute 'install'
```

**Comment by davidfstr** [comment]
I also tried `sudo apt-get install clang` in case the `build-essential` package wasn't clang (which is likely). No effect on the error message from `emsdk install latest`.

**Comment by GGAlanSmithee** [comment]
I am also experiencing this issue.

Has been brought up in #3607 and in juj/emsdk#37

I just wanted to add that if I attempt to install an earlier version (like 1.30.0) the installation goes well, but when trying to verify <code>./emcc</code> by running <code>./emcc -v</code> i get output

<code>
Traceback (most recent call last):
  File "./emcc", line 52, in <module>
    from tools import shared, jsrun, system_libs
  File "/home/ubuntu/workspace/emsdk_portable/emscripten/1.30.0/tools/shared.py", line 533, in <module>
    USING_PNACL_TOOLCHAIN = os.path.exists(os.path.join(LLVM_ROOT, 'pnacl-clang'))
NameError: name 'LLVM_ROOT' is not defined
</code>

I have veryfied the compiler toolchain according to [here](http://kripken.github.io/emscripten-site/docs/building_from_source/toolchain_what_is_needed.html#compiler-toolchain) with output:

<code>
$ python --version
Python 2.7.6
</code>
<code>
$ nodejs --version
v0.10.25
</code>
<code>
$ git --version
git version 1.9.1
</code>
<code>
$ java -version
java version "1.7.0_75"
</code>
<code>
$ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
</code>
<code>
$ g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
</code>
<code>
$ cmake --version
cmake version 2.8.12.2
</code>

**Comment by davidfstr** [comment]
I will attempt to verify the fix this weekend (July 18-19) and close if verified.

**Comment by davidfstr** [comment]
I no longer receive this error when running the repro steps. Closing as Fixed.

I would recommend adding continuous integration to the project via a tool like Travis so that really basic setup errors like this one are detected quickly.

**Comment by kripken** [comment]
We have CI for emscripten but not for the SDK, I believe. I agree it would be good to add this.

Regarding Travis specifically, sadly it has a very short limit on execution time, 15 minutes I believe. It takes more time than that to fetch and build LLVM+clang, I'm afraid.

**Comment by davidfstr** [comment]
Yeah. Memory limits might also be an issue. I need to bump my Ubuntu VM to 3 GB to avoid crashing while building clang as part of emscripten. (1 GB and 2GB wouldn't cut it.)

**Comment by GGAlanSmithee** [comment]
> Yeah. Memory limits might also be an issue. I needed to bump my Ubuntu VM to 3 GB to avoid crashing while building clang as part of emscripten. (1 GB and 2GB wouldn't cut it.)

I experienced the same thing, 3GB is really the lower memory limit for building clang.
