### ISSUE TITLE
windows system not recognized (probably)

### ISSUE THREAD

**Issue by lamasuma** [kripken/emscripten#3615]
hi,,,

emcc/clang throwing error in the form1 window code-

public System::Windows::Forms::Form

how to rewrite this?

thanks

**Comment by kripken** [comment]
That sounds like non-portable code is being used. Emscripten can only compile portable codebases. Code that is tied to Windows APIs would need to be rewritten to use something portable.

**Comment by juj** [comment]
On web pages, one can use HTML to develop UIs, and GL games typically use OpenGL/WebGL for in-game UIs in the canvas element. Let me close this bug, as we can't do much anything to port platform-specific WinForms over to the web.
