### ISSUE TITLE
Module.doNotCaptureKeyboard and Module.keyboardListeningElement don't work with SDL2

### ISSUE THREAD

**Issue by iboB** [kripken/emscripten#3621]
Module.doNotCaptureKeyboard and Module.keyboardListeningElement seem to worki with SDL (1), but are ignored in SDL2. SDL2 doesn't seem to have a way of not capturing the entire keyboard input of the window.

I have a use case where I don't care about the keyboard input at all, and instead want to enter data in text inputs on the page. Is there some way to accomplish this with SDL2?

**Comment by Daft-Freak** [comment]
The SDL2 equivalent of `keyboardListeningElement` is the `SDL_EMSCRIPTEN_KEYBOARD_ELEMENT` hint which can be set using `SDL_SetHint` in C or `ENV.SDL_EMSCRIPTEN_KEYBOARD_ELEMENT` in JS. There is also a PR for disabling events that isn't merged yet: https://github.com/emscripten-ports/SDL2/pull/10 (I think all that was missing was tests)

**Comment by iboB** [comment]
`SDL_EMSCRIPTEN_KEYBOARD_ELEMENT` does what I need. Thanks. 

I didn't think that this would come from the SDL source itself. I only looked in the Emscripten sources :)

**Comment by juj** [comment]
I'll close this as resolved, feel free to reopen if an issue still persists.

**Comment by tarun550** [comment]
I am using SDL-2. I have a 2 canvases on my document along with a textbox. I donot require any of the canvases to capture keyboard events directly.
Even after setting ENV.SDL_EMSCRIPTEN_KEYBOARD_ELEMENT = undefined, my textbox is not able to get any keyboard inputs. 

Am I using this API correctly? I am using emscripten 1.36.0

**Comment by tarun550** [comment]
@Daft-Freak Thanks. This made it more clear.
Could you also provide, for the sake of clarity, how to use this with JS ie using ENV.SDL_EMSCRIPTEN_KEYBOARD_ELEMENT.?

**Comment by Daft-Freak** [comment]
You should set it in a preRun handler. Something like: 
```
Module.preRun.push(function()
{
    ENV.SDL_EMSCRIPTEN_KEYBOARD_ELEMENT = "...";
});
```
