### ISSUE TITLE
No tool by name 'clang-tag-1.34.1-64bit' found! This may indicate an internal SDK error!

### ISSUE THREAD

**Issue by looopTools** [kripken/emscripten#3622]
I get this error, the error below when trying to run `./emsdk install latest`:

```
[tools@steinwurf-124 emsdk_portable]$ ./emsdk install latest
Installing SDK 'sdk-tag-1.34.1-64bit'..
Manifest error: No tool by name 'clang-tag-1.34.1-64bit' found! This may indicate an internal SDK error!
Traceback (most recent call last):
  File "./emsdk", line 1734, in <module>
    sys.exit(main())
  File "./emsdk", line 1717, in main
    success = tool.install()
  File "./emsdk", line 1007, in install
    success = tool.install()
```
I am runing 64 bit fedora 22, and just pulled emsdk, if it helps. 
Can I solbe this my self some how?

**Comment by mbrodersen** [comment]
I have the same problem (Ubuntu 15.04):

$ ./emsdk install latest
Installing SDK 'sdk-tag-1.34.2-64bit'..
Manifest error: No tool by name 'clang-tag-1.34.2-64bit' found! This may indicate an internal SDK error!
Traceback (most recent call last):
  File "./emsdk", line 1734, in <module>
    sys.exit(main())
  File "./emsdk", line 1717, in main
    success = tool.install()
  File "./emsdk", line 1007, in install
    success = tool.install()
AttributeError: 'NoneType' object has no attribute 'install'

**Comment by mbrodersen** [comment]
A solution has been found here:

https://github.com/kripken/emscripten/issues/3601

**Comment by juj** [comment]
Thanks for catching this, and very sorry about the typo! Updated packages are now pushed and they should fix the Linux issue.

**Comment by mbrodersen** [comment]
You are welcome and thanks for fixing it :-)
