### ISSUE TITLE
Help, question about the filesystem of the emscripten

### ISSUE THREAD

**Issue by therains1018** [kripken/emscripten#3633]
Hi All~ 
  Does anybody know how and when will the file  which created by FS.create***, write back to the *.data file? Many thanks.

**Comment by kripken** [comment]
`.data` files are created by the file packager offline. `FS.create*` methods write to the in-memory filesystem, they never write to a `.data` file.

If you want persistent storage, see IDBFS and NODEFS, which can write to IndexedDB and node, respectively. One could also write a filesystem backend that does write to a `.data` file, using a POST perhaps?

**Comment by therains1018** [comment]
Hi,kripken, I get your meaning. Many thanks for helping.
