### ISSUE TITLE
NODEFS failures on Windows

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3634]
`test_fgetc_ungetc` and `test_fs_nodefs_rw` fail when using NODEFS. It looks like basic functionality is failing, for example in `test_fgetc_ungetc` the syscall trace is

````
syscall! 5,SYS_open
    (raw: "672")
    (str: "/tmp/file.txt")
    (raw: "32961")
    (raw: "438")
syscall return: 3
syscall! 4,SYS_write
    (raw: "3")
    (stream: "/tmp/file.txt")
    (raw: "686")
    (raw: "2")
syscall return: 2
syscall! 6,SYS_close
    (raw: "3")
    (stream: "/tmp/file.txt")
syscall return: 0
syscall! 5,SYS_open
    (raw: "672")
    (str: "/tmp/file.txt")
    (raw: "32768")
    (raw: "438")
error: syscall failed with 2 (No such file or directory)
syscall return: -2
````

It opens, writes, and closes a file, but when it tries to read it, it isn't there. Very strange.

I'm not sure when this started to fail. I noticed it after the `musl-syscalls` landing, which should hopefully not affect this. But the windows bot was broken due to `asm2m` for a while before. We should probably bisect for this.

**Comment by juj** [comment]
There was that fopen modes fix for node.js some time ago, I think that fixed this. Running `ALL.test_fs_nodefs_rw` and `ALL.test_fgetc_ungetc` today on Windows succeeds, though we do have the message

    test_fgetc_ungetc (test_core.asm2) ... WARNING:root:TODO: update this test once the musl ungetc-on-EOF-stream bug is fixed upstream and reaches us

Should we call this issue fixed regardless of that todo?

**Comment by kripken** [comment]
Sure.
