### ISSUE TITLE
LLVM optimization step fails

### ISSUE THREAD

**Issue by dgrechka** [kripken/emscripten#3645]
Hi,

I try to compile linked bitcode to JavaScript, however emcc call fails with "Failed to run llvm optimizations". I don't specify any optimization flags, I just run "emcc -o out.js ..... "

The output:
```
DEBUG    root: using response file for llvm-link
DEBUG    root: emcc step "link" took 17.00 seconds
DEBUG    root: saving intermediate processing steps to c:/users/dmitry/appdata/local/temp\emscripten_temp
DEBUG    root: emcc: LLVM opts: -strip-debug -internalize -internalize-public-api-list=main,malloc,free,__cxa_can_catch,__cxa_is_pointer_type,malloc,free -globa
ldce -pnacl-abi-simplify-preopt -pnacl-abi-simplify-postopt -enable-emscripten-cxx-exceptions -disable-loop-vectorization -disable-slp-vectorization -vectorize-
loops=false -vectorize-slp=false -vectorize-slp-aggressive=false
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.34.1\\emcc", line 1260, in <module>
    shared.Building.llvm_opt(final, link_opts)
  File "C:\Program Files\Emscripten\emscripten\1.34.1\tools\shared.py", line 1429, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:

Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.34.1\\emcc", line 1260, in <module>
    shared.Building.llvm_opt(final, link_opts)
  File "C:\Program Files\Emscripten\emscripten\1.34.1\tools\shared.py", line 1434, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
```

I can see that bitcode optimizer does not produce any output file for my input file. There are no error messages as well.

When I call the optimizer explicitly the result is the same. No output file, no stderr.
I also tried to remove any opt.exe prameters which are added by emcc. The same behavior.
Even when I call optimizer to perform analysis (eg opt.exe -analyze a.out.bc) it does not produce any messages.

Other utilites that come with emscripten (e.g. llvm-bcanalyzer) read the file successfuly.

The file I try to compile is at http://home.dgrechka.net/filestore/for_external/a.out.bc

What can cause such problem?

Platform: windows
python: Python 2.7.5
emsdk: emsdk-1.34.1-full-64bit.exe

```
c:\Program Files\Emscripten\clang\e1.34.1_64bit>opt.exe -version
LLVM (http://llvm.org/):
  LLVM version 3.7.0svn
  DEBUG build.
  Built Jul  3 2015 (18:07:05).
  Default target: x86_64-pc-windows-msvc
  Host CPU: sandybridge
```

Regards,
Dmitry.

**Comment by kripken** [comment]
Running `EMCC_LEAVE_INPUTS_RAW=1 EMCC_DEBUG=1 ~/Dev/emscripten/emcc -O2 a.out.bc` on my linux machine works, so I can't reproduce the problem. Perhaps it is windows-only?

Is there some way on windows to run it in a debugger, maybe that will show something?

**Comment by gouletr** [comment]
This doesn't repro anymore in `1.34.6`, but yes this did happen in `1.34.1`. I haven't found the cause.

**Comment by dgrechka** [comment]
Yes. The issue is solved in 1.34.6 .

**Comment by diegocr** [comment]
I'm facing this problem as well, trying to compile a program using cryptopp.

Win8.1 and emsdk 1.34.1 here -- when can we expect new precompiled SDK versions? thanks.

**Comment by juj** [comment]
New precompiled 1.35.0 went live today: https://groups.google.com/d/msg/emscripten-discuss/TW-AvHt-lc4/_59T4YBxBQAJ .
