### ISSUE TITLE
emscripten_log not producing correct output for %f with emscripten version 1.34.1

### ISSUE THREAD

**Issue by mbarthelemy** [kripken/emscripten#3647]
Code:
```
#ifdef EMSCRIPTEN

#include <emscripten/emscripten.h>

#define TestLog(args...)        emscripten_log(EM_LOG_CONSOLE, args)

#else /* !EMSCRIPTEN */

#define EMSCRIPTEN_KEEPALIVE

#include <stdio.h>

#define TestLog(args...)        fprintf(stderr, args)

#endif /* EMSCRIPTEN */

EMSCRIPTEN_KEEPALIVE void PrintFloatStuff(float first, float second)
{
    float divided = first / second;

    TestLog("%f %f %f\n", first, second, divided);
    TestLog("%d %d %d\n", (int)(first * 10000000), (int)(second * 10000000), (int)(divided * 10000000));
}

#ifndef EMSCRIPTEN

int main(int argc, char **argv)
{
    PrintFloatStuff(12.3456789, 9.12345678);

    return 0;
}

#endif
```
Compiled with: emcc Test.c -g -O3 --js-opts 1 --llvm-opts 3 --llvm-lto 3 -o Test.js

Used by:
```
<!DOCTYPE html>
<html>
<head>
</head>
	<body>
        <script type="text/javascript">
            var Module = {
                onRuntimeInitialized: function() {
                    Module.ccall('PrintFloatStuff', 'void', ['number', 'number'], [12.3456789, 9.12345678]);
                }
            };
        </script>
		<script type="text/javascript" src="Test.js"></script>
	</body>
</html>
```

Produces the following output:

Chrome Version 43.0.2357.132 (64-bit) on Mac OS X Version 10.10.4 (14E46)

pre-main prep time: 6 ms
Test.js:136 -3.395250601131434e+92 -0.000000 0.000000
Test.js:136 123456789 91234567 13531799

Safari Version 8.0.7 (10600.7.12) on Mac OS X Version 10.10.4 (14E46)

[Log] pre-main prep time: 4 ms (Test.js, line 139)
[Log] -3.395250601131434e+92 -0.000000 0.000000 (Test.js, line 136)
[Log] 123456789 91234567 13531799 (Test.js, line 136)

Result by compiling natively with: cc Test.c -g -O3 -o Test on Mac OS X Version 10.10.4 (14E46) with Xcode Version 6.4 (6E35b)

12.345679 9.123457 1.353180
123456792 91234568 13531799

**Comment by mbarthelemy** [comment]
The precision differences between the %d output aren't a concern for this issue.

**Comment by kripken** [comment]
Thanks for filing! We had a pretty bad varargs bug here, that actually could only manifest in `emscripten_log`, which was not heavily tested. Fixed on incoming and added testing.
