### ISSUE TITLE
Is it possible to return something from a synchronous call to an asynchronous function?

### ISSUE THREAD

**Issue by albertjan** [kripken/emscripten#3652]
I've compiled the project with emterpreter. And added a function to the library that awaits a promise like this:

```js
function _emjs_await(promise_h) {
  var promise = _emjs_deref(promise_h);
  EmterpreterAsync.handle(function(resume) {
    promise.then(function(val) {
      if (ABORT) return;
      resume(function () {
        return val;
      });
    }, function(err) {
      if (ABORT) return
      EMJS.last_error = err;
      resume(function () { return EMJS.ERROR; });
    });
  });
}
```

As you can see I hoped that returning a callback as a parameter to the `resume` function, but so far the result seems to be `undefined`.

**Comment by kripken** [comment]
We do that in `fsync` and it works, so perhaps compare to what's going on there to see what's different?

Otherwise, I don't see anything obviously wrong. If you can make a full standalone testcase of this I could take a look if you get stuck.

**Comment by albertjan** [comment]
@kripken thanks it worked as advertised :smile: i had to turn the return value into a emscripten handle first.
