### ISSUE TITLE
Fatal error string not found, Fatal error sstream not found

### ISSUE THREAD

**Issue by SlightlyCyborg** [kripken/emscripten#3656]
Hello. I am getting these errors. I am actually not even trying to compile with emcc right now. I followed the install instructions [here](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#sdk-download-and-install) and it changed my PATH I think so now clang++ does not call my system standard compiler.

 2 questions:
1) How do I resolve these errors. Must I include all the stdlib stuff in the main cpp?
2) How do I get my systems clang compiler back. Is there a way to have emcc not take over the clang PATH?

**Comment by SlightlyCyborg** [comment]
I solved 1).
For any beginners out there like myself, "source ./emsdk_env.sh" will change the path for that one bash instance only.

**Comment by SlightlyCyborg** [comment]
Solved 2) by changing the make file to use emcc. It wasn't too clear that I had to change the make file

**Comment by juj** [comment]
The `clang` and `clang++` that are provided with emsdk are intended to be usable for compiling native programs. However LLVM does not provide standard C++ libraries or have a mechanism to automatically choose which OS runtime/SDK to target, so the user has to specify that when building for native. https://github.com/kripken/emscripten/blob/master/tools/shared.py#L561 does that for internal Emscripten purposes e.g. for when Emscripten test harness wants to compile a native application. If you want to build native applications with Emscripten-provided `clang`, then following the directives there can help.

Of course you can just compile using your system `clang` compiler, by doing that outside the Emscripten shell environment like you mentioned. And like you noticed, emsdk never replaces your system `clang` compiler, but only points to it inside the Emscripten shell. Outside the Emscripten environment things are as usual.
