### ISSUE TITLE
Hitting dlmalloc worst case behaviour

### ISSUE THREAD

**Issue by CJoEmery** [kripken/emscripten#3661]
I'm developing 3d applications using emscripten that have quite high memory requirements (see http://makethingsnow.com/minecraft/ if you're interested ).

I've been hitting dlmalloc worst case behaviour (this isn't really an emscripten issue, but I worked out what is happening, the description is at the end and is somewhat interesting). Anyway this article(http://mozakai.blogspot.co.uk/2012/01/emscripten-standard-library-support-now.html) says "However, we should implement malloc and free in JavaScript eventually since we could optimize it quite a bit". Is that just referring to hand optimising the code to be really fast, or is there some way to use browser/javascript features to significantly improve malloc? If so then I'd be interested what would be involved in this.

Anyway here's what the problem turned out to be:
I've been having issues with my program hitting the memory limit "unexpectedly". I have ALLOW_MEMORY_GROWTH=0 and TOTAL_MEMORY=536870912 (512meg). I have things set up so that I can build for both normal Mac OS and JS. The Mac app wasn't using anywhere near 512 meg of memory.

It turned out that the problem was that at some point in my program I'm sitting inserting lots of vertices in to a vector. By a lot I mean, say 100 megabytes worth. During my insertion loop the vector implementation is reallocing every now and then as I get to its allocated limit. The problem is that dlmalloc's realloc doesn't grow the initial allocation (I'm not sure why?), so it does a malloc(and a copy) which causes an sbrk. So then as I insert in to my array, every realloc to up the size of the vector causes an sbrk for that size, and I hit the memory limit pretty quickly, even though I'm not using most of it. Sorry if that doesn't make full sense, I can go in to better detail if someone is interested. I'm going to fix the problem by just being careful to resize my vectors etc before starting insertion so I don't end up with a fragmenty memory.

(As an aside, is there any downside to just starting off with the entire memory available rather than having dlmalloc sbrk all the time? (Though I don't think that will fix my problem since I think it's a fragmentation issue))

**Comment by kripken** [comment]
I think that 2012 blogpost is out of date by now. But, in general, it does sound like you are hitting an unoptimal behavior in dlmalloc. Perhaps there is a better malloc (newer version of dlmalloc, perhaps) that could improve this. Some mallocs are just better at avoiding fragmentation.

If you can start off with the full size of memory, that is better, as growing memory takes overhead.

Note that you might want to avoid the fragmentation in your C++ source code. You can `reserve()` room in the vector, for example. Or use a custom allocator of your own.

**Comment by CJoEmery** [comment]
Yup I'm now reserve()ing aggressively and that's helping. I might try some other mallocs at some point. I'll let you know if any seem better.

(Also thanks in general for emscripten. I'm making pretty heavy use of it(using embind, OpenGL ES, web workers, and it's working great! Actually I have a --js-library that implements a less restricted web-worker api that I should make nice enough to be a pull request some time. The current web-worker request/response style wasn't powerful enough.)

**Comment by kripken** [comment]
@floooh might be interested in that worker API, he proposed the current one.

**Comment by kripken** [comment]
Btw, that project seems to have over 5,000 loops in a single function. This causes slow startup and high memory usage on browsers doing AOT compilation (firefox and edge, at least). I wonder if that function is the result of LTO? Or some other way for excessive inlining to occur?
