### ISSUE TITLE
FileSystem in web workers using FileReaderSync and FileWriterSync

### ISSUE THREAD

**Issue by sunnygoyal** [kripken/emscripten#3662]
WebWorkers now support synchronous file systems
  - http://www.html5rocks.com/en/tutorials/file/filesystem-sync/
  - http://html5index.org/File%20API%20-%20FileWriterSync.html

Is there a file system implementation based on this?
Or is there any doc on how to implement a custom file system?

**Comment by Deamon87** [comment]
You can check my comment https://github.com/kripken/emscripten/issues/3641#issuecomment-128006596
Though I didn't make use of FileWriterSync, but it's no hard to do with that code

**Comment by sunnygoyal** [comment]
Thanks. Exactly what I was looking for.
