### ISSUE TITLE
Fresh Windows install has exception traceback with emcc -v (LLVM_ROOT not defined)

### ISSUE THREAD

**Issue by jleaders** [kripken/emscripten#3664]
Brand new install on Windows 8.1 using NSIS  **emsdk-1.34.1-web-64bit.exe**

Opening the cmd prompt (which, btw, DID NOT get installed to the start menu :( this may be related)
Also the 1.34.1 SDK did not get installed, I had to `emsdk install` that -- botched install?

Here's the traceback:

C:\Program Files\Emscripten\emscripten\1.34.1>emsdk list

      The following precompiled tool packages are available for download:
                 clang-e1.30.0-64bit
           *     clang-e1.34.1-64bit          INSTALLED
                 node-0.12.2-32bit
                 node-0.12.2-64bit            INSTALLED
                 python-2.7.5.3-32bit
           *     python-2.7.5.3-64bit         INSTALLED
                 java-7.45-32bit
                 java-7.45-64bit
                 spidermonkey-37.0.1-64bit
                 spidermonkey-nightly-2015-04-12-64bit
                 git-1.9.4
                 emscripten-1.30.0
           *     emscripten-1.34.1            INSTALLED
                 vs-tool-0.9.4                Not available: Visual Studio 2010 was no
      t found!
                 crunch-1.03
                 mingw-4.6.2-32bit

      The following tools can be compiled from source:
                 clang-tag-e1.34.0-32bit
                 clang-tag-e1.34.1-32bit
                 clang-tag-e1.34.0-64bit
                 clang-tag-e1.34.1-64bit
                 clang-incoming-32bit
                 clang-incoming-64bit
                 clang-master-32bit
                 clang-master-64bit
                 emscripten-tag-1.34.0-32bit
                 emscripten-tag-1.34.1-32bit
                 emscripten-tag-1.34.0-64bit
                 emscripten-tag-1.34.1-64bit
                 emscripten-incoming-32bit
                 emscripten-master-32bit
                 emscripten-incoming-64bit
                 emscripten-master-64bit

      The following precompiled SDKs are available for download:
               sdk-1.30.0-64bit
               sdk-1.34.1-64bit               INSTALLED

      The following SDKs can be compiled from source:
               sdk-incoming-32bit
               sdk-incoming-64bit
               sdk-master-32bit
               sdk-master-64bit
               sdk-tag-1.34.0-32bit
               sdk-tag-1.34.1-32bit
               sdk-tag-1.34.0-64bit
               sdk-tag-1.34.1-64bit

      Items marked with * are activated for the current user.

      To access the historical archived versions, type 'emsdk list --old'

C:\Program Files\Emscripten\emscripten\1.34.1>emcc -v

      Traceback (most recent call last):
        File "C:\Program Files\Emscripten\emscripten\1.34.1\\emcc", line 52, in <modul
      e>
          from tools import shared, jsrun, system_libs
        File "C:\Program Files\Emscripten\emscripten\1.34.1\tools\shared.py", line 532
      , in <module>
          USING_PNACL_TOOLCHAIN = os.path.exists(os.path.join(LLVM_ROOT, 'pnacl-clang'
      ))
      NameError: name 'LLVM_ROOT' is not defined

**Comment by jleaders** [comment]
Uninstalling, and re-installing using the **Offline Installer** fixed it.

**Comment by juj** [comment]
I am quite confident that this was issue https://github.com/juj/emsdk/commit/89df87a4608d07bdde92bf2e2fa1356aa8ebfa89 . New Emscripten SDK 1.35.0 went live today, see https://groups.google.com/d/msg/emscripten-discuss/TW-AvHt-lc4/_59T4YBxBQAJ . Tested the web installer to work, so let me close this as assumed to be fixed. Feel free to reopen if an issue still occurs!
