### ISSUE TITLE
Accept File/Blob files without copying

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#3666]
Hi. Sorry if it was already asked, I haven't found similar issues.

Currently Emscripten provides 2 different file systems for browsers: MEMFS and IDBFS. MEMFS is fine for medium-size files but if we want to support 500M-1G files and larger it becomes a problem. We can try to workaround it by using IndexedDB - at first load & save file using buffered read & write, then mount that DB inside Emscripten. But probably there is some better way.

For example we have `File` object with 1G file provided by user via typical `<input type=file>`. User selected it and it showed up in interface but browser hasn't read it yet (as far as I can understand). What if we can pass it to e.g. `FS.createLazyFile` and it won't reat it right away, but instead will provide buffered read-only access to that file?

Is it possible at all? I'm very interested in such feature and I think it may be useful for a lot of JS projects which uses Emscripten (e.g. video editors, converters, players, etc).

**Comment by kripken** [comment]
A Blob could be very useful, I agree. Perhaps a BLOBFS. But a downside is that Blobs can only be read from asynchronously. However, they **can** be read from synchronously in web workers. I proposed that we write a WORKERFS that uses Blobs that way in #3641.

**Comment by Kagami** [comment]
Perfect, thanks, exactly that I've looked for.
