### ISSUE TITLE
Mac build instructions specify a CMake version older than the required minimum

### ISSUE THREAD

**Issue by cdc6d** [kripken/emscripten#3667]
The [platform notes](https://github.com/kripken/emscripten/blob/incoming/site/source/docs/building_from_source/building_emscripten_from_source_on_mac_os_x.rst) for installing the portable SDK on Mac recommend installing CMake version 2.8.10.2.  However, when building with `./emsdk install latest`, I get this error:

```
x www/robots.txt
Running CMake: ['cmake', '-G', 'Unix Makefiles', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_TESTS=OFF', '/private/tmp/emsdk_portable/clang/tag-e1.34.4/src']
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 2.8.12.2 or higher is required.  You are running version 2.8.10.2
```

It might make sense to just change 2.8.10 to 2.8.12 in the doc.  OTOH, I haven't tried newer CMake versions.  If they work, then removing the tip about using a specific CMake version might be best.

**Comment by juj** [comment]
Thanks! Fixed in https://github.com/kripken/emscripten/commit/ba088cae8752e24135f753fce03467b78167b841 . (Note that we definitely recommend using `emsdk`, since it supports all use cases that building manually from source does, and it automates these steps as well)
