### ISSUE TITLE
"perms is undefined" in realpath()

### ISSUE THREAD

**Issue by peter-b** [kripken/emscripten#3668]
I have a program that's using `--preload-file` to provide an initial filesystem image for my emscripten-compiled program.  This was working fine until this morning, when I updated my emsdk to the latest incoming version.

Now, on the first attempt to use the `realpath(3)` libc function, I'm getting an exception:

````
TypeError: perms is undefined
Stack trace:
FS.nodePermissions@http://localhost:8080/standalone-community.js:3270:1
FS.mayOpen@http://localhost:8080/standalone-community.js:3326:16
FS.open@http://localhost:8080/standalone-community.js:3891:21
___syscall5@http://localhost:8080/standalone-community.js:6910:20
_realpath@http://localhost:8080/standalone-community.js:578362:45

<application stack frames omitted>
````

Any idea why this has started happening? What's the best way to debug it?

**Edit:** It looks like the problem may be specific to `realpath()`.

**Comment by juj** [comment]
Can you remember which version was working properly? A simple way to do rough bisection is to build one of the tagged versions via `./emsdk install sdk-tag-1.xx.y-64bit` (call `./emsdk update` first to have emsdk pull in the latest list of tags) followed by `./emsdk activate sdk-tag-1.xx.y-64bit` and `source ./emsdk_env.sh`.

Alternatively if you have a small C snippet testcase to repro, I can try to bisect it for you.

**Comment by peter-b** [comment]
Pretty minimal testcase:

https://gist.github.com/peter-b/7871324591f5e6f70191

**Comment by peter-b** [comment]
Unfortunately I don't know exactly which version was working correctly -- but it was an `incoming` branch release built around the 7th July.

**Comment by peter-b** [comment]
Having taken the opportunity to do some more careful debugging, it looks like it's something specific to `realpath(3)`.  If I skip calling `realpath()`, then I can actually just `open()` and use the file just fine...

**Comment by kripken** [comment]
Thanks for filing, I'm surprised this FS bug wasn't noticed before. I suspect our previous libc avoided it by sheer luck, and our test suite didn't happen to cover it, so the musl migration uncovered it. Fixed on incoming.
