### ISSUE TITLE
Native optimizer dumps user-unfriendly error message on input.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3671]
Running `optimizer emcc-3-meminit.js asm eliminate simplifyExpressions registerize asmLastOpts last` on the file http://clb.demon.fi/emcc/dump/emcc-3-meminit.js spams the following error message:

	bad parseExpression state:
	==========
	global.SIMD === "undefined") {
	  // SIMD module.

        ....
        thousands of times the same error
        ....

	bad parseExpression state:
	==========
	global.SIMD === "undefined") {
	  // SIMD module.

	bad parseExpression state:
	==========
	global.SIMD === "undefined") {
	  // SIMD module.

	Segmentation fault: 11

It would be nice to get a compact error message, along with file:line:column info of where the error occurs. (this is not that critical, but just observing)

**Comment by kripken** [comment]
The native optimizer isn't meant to be run on a file like that - it should just be run on the individual asm.js functions. cashew cannot parse general JS.

`js_optimizer.py` should split out the asm.js functions and only pass those to the optimizer.

**Comment by juj** [comment]
Yeah, I realize it is not, but I think it would still be good to be able to handle malformed input. This was just something I noticed while debugging #3672.

**Comment by kripken** [comment]
Hmm, I believe the thousands of repetitions are because your build has assertions turned off, and we do `assert(0)` where we should put an `abort()`. I fixed that now.

**Comment by juj** [comment]
Ah right, that makes sense. Thanks for the fix!
