### ISSUE TITLE
Native optimizer performs string + integer pointer arithmetic somewhere.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3672]
STR:

1. Check out https://github.com/juj/emscripten-fastcomp/commit/a6f8a6c438962a9df44cf8fb8555990aefad581e
2. Compile `tests/core/test_simd.in` with `-O2 -g2`.

Observed: the generated output contains the following garbage JS code:

	HEAP32[i3 >> 2] = ~~+SIMD.Float32x4.pA‘«;
	HEAP32[i3 + 4 >> 2] = ~~+SIMD.Float32x4.;
	HEAP32[i3 + 8 >> 2] = ~~+SIMD.Float32x4.`A‘«;
	HEAP32[i3 + 12 >> 2] = ~~+SIMD.Float32x4.@A‘«;
	HEAP32[i3 + 16 >> 2] = ~~+SIMD.Float32x4.  A‘«;
	HEAP32[i3 + 20 >> 2] = ~~+SIMD.Float32x4.;
	HEAP32[i3 + 24 >> 2] = ~~+SIMD.Float32x4.à'A‘«;
	HEAP32[i3 + 28 >> 2] = ~~+SIMD.Float32x4.À+A‘«;

which seems to be a result of raw char * string plus integer arithmetic.

Expected: Native optimizer should have generated a parsing error(?), since the syntax of the asm.js code is not valid, I think. A fix that hides this issue was committed at https://github.com/juj/emscripten-fastcomp/commit/e20b968a7d890246e1e55465b6d180e4dca1fb6a , which fixes the syntax and avoids the optimizer from outputting garbage.

**Comment by juj** [comment]
Oh, most likely one must as step 1.5 check out https://github.com/juj/emscripten/tree/sse2_emmintrin_h

**Comment by kripken** [comment]
Is the issue dot notation? Yes, we don't support dot notation in the optimizer, because it isn't in asm.js - although I suppose if it is added to SIMD.js, we will need to support it?

Is the fix to use underscores the proper fix for SIMD? I'm not sure what is left to investigate here.

**Comment by juj** [comment]
Yes, using underscore instead of dot is the fix, but like mentioned, that fix hid the error in cashew. It should abort with a parsing error, instead of operating seemingly normally, and silently failing and generating a corrupted output as a result.

**Comment by kripken** [comment]
Yes, I fixed the continuing problem in the other issue. Is this one finished then?

**Comment by juj** [comment]
Yeah, thanks!
