### ISSUE TITLE
GenericWireType must be 8 bytes, c++11/c++14

### ISSUE THREAD

**Issue by howpenghui** [kripken/emscripten#3674]
I am trying to bind a c++11 program (this applies to c++14 as well) to javascript using embind - upon inclusion of <emscripten/bind.h>, the following error was shown:
<code>error: static_assert failed "GenericWireType must be 8 bytes"</code>
Any idea what is going on? This is on a 64-bit machine. Thanks!

**Comment by DutchKevv** [comment]
@howpenghui - Bit overtime, but did you figure it out?? Im running in to it right now and theres almost nothing to find about it on Google. Thanks!

**Comment by AlexPerrot** [comment]
Can you provide more details ?
What is the complete error message, more specifically the line of the error ?
On what system are you compiling ?
Can you craft a minimal code example ?

**Comment by DutchKevv** [comment]
OS - MacOS Sierra
Node - 8.1.2
emcc - 1.37.14
clang - 4.0.0
cmake - 3.8.2

```
    #include <string>
    #include <stdlib.h>
    #include <stdio.h>
    #include <GL/glut.h>
    #include <GL/glew.h>
    #include <emscripten.h>
    #include <emscripten/bind.h>

    int main(int argc, char** argv) {}
```    
    project(Chart)
    set(CMAKE_CXX_STANDARD 11)
    set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    #add_subdirectory(/usr/local/include/GLFW)
    add_executable(Chart main.cpp)
    find_package(OpenGL REQUIRED)
    find_package(GLUT REQUIRED)
    find_package(GLEW REQUIRED)
    find_package(GLFW3 REQUIRED)
    
    #target_include_directories(Chart ${OPENGL_INCLUDE_DIR})
    target_link_libraries(Chart ${OPENGL_gl_LIBRARY})
    include_directories(${OPENGL_INCLUDE_DIRS} ${EMSCRIPTEN_INCLUDE_DIRS} ${GLUT_INCLUDE_DIRS} ${GL_INCLUDE_DIRS} ${GLEW_INCLUDE_DIRS} ${GLFW3_INCLUDE_DIRS})
    include_directories(/usr/local/include/)
    include_directories(/emscripten/emscripten/incoming/system/include)
    include_directories(/emscripten/)
    link_directories(/usr/local/lib/)
    target_link_libraries(Chart glfw ${GLUT_LIBRARY} ${GLEW_LIBRARY} ${GLFW3_LIBRARY})
`


Error

Scanning dependencies of target Chart
[ 50%] Building CXX object CMakeFiles/Chart.dir/main.cpp.o
In file included from /Users/kewinbrandsma/Projects/TradeJS/client/chart/main.cpp:6:
In file included from /emscripten/emscripten/incoming/system/include/emscripten.h:1:
In file included from /emscripten/emscripten/incoming/system/include/emscripten/emscripten.h:26:
In file included from /emscripten/emscripten/incoming/system/include/SDL/SDL.h:75:
/emscripten/emscripten/incoming/system/include/SDL/SDL_atomic.h:214:15: warning: 'OSAtomicCompareAndSwap32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    } while (!SDL_AtomicCAS(a, value, v));
              ^
/emscripten/emscripten/incoming/system/include/SDL/SDL_atomic.h:163:42: note: expanded from macro 'SDL_AtomicCAS'
#define SDL_AtomicCAS(a, oldval, newval) OSAtomicCompareAndSwap32Barrier((oldval), (newval), &(a)->value)
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:518:9: note: 'OSAtomicCompareAndSwap32Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32Barrier( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from /Users/kewinbrandsma/Projects/TradeJS/client/chart/main.cpp:6:
In file included from /emscripten/emscripten/incoming/system/include/emscripten.h:1:
In file included from /emscripten/emscripten/incoming/system/include/emscripten/emscripten.h:26:
In file included from /emscripten/emscripten/incoming/system/include/SDL/SDL.h:75:
/emscripten/emscripten/incoming/system/include/SDL/SDL_atomic.h:244:15: warning: 'OSAtomicCompareAndSwap32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    } while (!SDL_AtomicCAS(a, value, (value + v)));
              ^
/emscripten/emscripten/incoming/system/include/SDL/SDL_atomic.h:163:42: note: expanded from macro 'SDL_AtomicCAS'
#define SDL_AtomicCAS(a, oldval, newval) OSAtomicCompareAndSwap32Barrier((oldval), (newval), &(a)->value)
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:518:9: note: 'OSAtomicCompareAndSwap32Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32Barrier( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from /Users/kewinbrandsma/Projects/TradeJS/client/chart/main.cpp:6:
In file included from /emscripten/emscripten/incoming/system/include/emscripten.h:1:
In file included from /emscripten/emscripten/incoming/system/include/emscripten/emscripten.h:26:
In file included from /emscripten/emscripten/incoming/system/include/SDL/SDL.h:75:
/emscripten/emscripten/incoming/system/include/SDL/SDL_atomic.h:289:15: warning: 'OSAtomicCompareAndSwap64Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    } while (!SDL_AtomicCASPtr(a, value, v));
              ^
/emscripten/emscripten/incoming/system/include/SDL/SDL_atomic.h:167:45: note: expanded from macro 'SDL_AtomicCASPtr'
#define SDL_AtomicCASPtr(a, oldval, newval) OSAtomicCompareAndSwap64Barrier((int64_t)(oldval), (int64_t)(newval), (int64_t*)(a))
                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libkern/OSAtomicDeprecated.h:645:9: note: 'OSAtomicCompareAndSwap64Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap64Barrier( int64_t __oldValue, int64_t __newValue,
        ^
In file included from /Users/kewinbrandsma/Projects/TradeJS/client/chart/main.cpp:7:
In file included from /emscripten/emscripten/incoming/system/include/emscripten/bind.h:14:
/emscripten/emscripten/incoming/system/include/emscripten/val.h:177:9: error: static_assert failed "GenericWireType must be 8 bytes"
        static_assert(sizeof(GenericWireType) == 8, "GenericWireType must be 8 bytes");
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/kewinbrandsma/Projects/TradeJS/client/chart/main.cpp:7:
/emscripten/emscripten/incoming/system/include/emscripten/bind.h:814:70: warning: static_assert with no message is a C++1z extension [-Wc++1z-extensions]
            static_assert(sizeof(FieldType) == sizeof(ElementType[N]));
                                                                     ^
                                                                     , ""
4 warnings and 1 error generated.
make[3]: *** [CMakeFiles/Chart.dir/main.cpp.o] Error 1
make[2]: *** [CMakeFiles/Chart.dir/all] Error 2
make[1]: *** [CMakeFiles/Chart.dir/rule] Error 2
make: *** [Chart] Error 2

**Comment by DutchKevv** [comment]
Hi Never mind, new to emscripten and c++ toolchain and just figured out that compiling through CMake while including emscripten.h does not mean a successful emscripten build (per se)... So the real problem for me was building with CMAKe (it works fine with emcc through terminal)..

**Comment by opiepj** [comment]
Did you get it working with CMake?

**Comment by DutchKevv** [comment]
Yess I did.. One of the problems was (not sure if it was this blocker), that I expected to much from emcc. 

https://stackoverflow.com/questions/45260216/emscripten-cmake-pass-emscripten-options-in-cmakelist-file/45277855?noredirect=1#comment80687180_45277855

**Comment by froydnj** [comment]
@kripken, it sounds like we can close this?

**Comment by howpenghui** [comment]
Sure.

**Comment by adaviding** [comment]
I am actually stuck on this now.

So for a 64-bit build, sizeof(void*) is 8, which means `GenericWireType` would be 16 bytes, right?

```
union GenericWireType {
    union {
        unsigned u;
        float f;
        const void* p;
    } w[2];
    double d;
};
static_assert(sizeof(GenericWireType) == 8, "GenericWireType must be 8 bytes");
```

Does embind work in any 64-bit build?

My error message is:
```
In file included from C:/dev/github/emscripten-core/emsdk/upstream/emscripten/system/include\emscripten/bind.h:21:
C:/dev/github/emscripten-core/emsdk/upstream/emscripten/system/include\emscripten/val.h:194:9: error: static_assert failed due to requirement 'sizeof(emscripten::internal::GenericWireType) == 8' "GenericWireType must be 8 bytes"
        static_assert(sizeof(GenericWireType) == 8, "GenericWireType must be 8 bytes");
```

**Comment by adaviding** [comment]
Apparently, emscripten always uses 32-bit pointers, even of compiling to a 64-bit architecture.  More information [here](https://github.com/emscripten-core/emscripten/issues/9294#issuecomment-525459749).  Sadness.

**Comment by sbc100** [comment]
WebAssembly itself is a 32-bit platform so it has 32-bit pointers.   There is no such thing (today) as a 64-bit WebAssembly platform.
