### ISSUE TITLE
strftime and %-m syntax

### ISSUE THREAD

**Issue by desapi** [kripken/emscripten#3677]
Using strftime with the dash syntax "%-m" to omit leading zeros doesn't work.

**Comment by kripken** [comment]
Do you have a standalone testcase showing the issue?

**Comment by desapi** [comment]
This should print out the current date in Year/Month/Day format but it just returns `"%-Y-%-m-%-d"`.

```C++
time_t timer = time(NULL);
tm *local = localtime(&timer);
mktime(local);
char buffer[80];
strftime(buffer, sizeof(buffer), "%-Y-%-m-%-d", local);	
printf("%s\n", buffer);
```

**Comment by kripken** [comment]
Can you please provide a full standalone testcase? (I'm not sure which headers that needs, for example.)

**Comment by desapi** [comment]
```C++
#include <iostream>
#include <time.h>

int main(int argc, char *argv[])
{
	time_t timer = time(NULL);
	tm *local = localtime(&timer);
	mktime(local);
	char buffer[80];
	strftime(buffer, sizeof(buffer), "%-Y-%-m-%-d\n", local);	
	printf("%s", buffer);
	return 0;
}
```

**Comment by kripken** [comment]
Ok, thanks I see the difference between glibc and emscripten now. However, reading [some docs](http://www.cplusplus.com/reference/ctime/strftime/), I don't see why `%-Y` is valid input. Shouldn't that be `%Y` (which works)?

**Comment by desapi** [comment]
Yes, in that case "%-Y" doesn't do anything but you can attach ```-``` to any format parameter.  It just means don't pad with zeros but it only seems to work when the result is an integer.  For instance doing "%-D" will still return a full date string with padding zeros.

**Comment by kripken** [comment]
Where is this documented, though? Or is it a glibc extension?

**Comment by desapi** [comment]
Yes, it appears to be an extension.
http://linux.die.net/man/3/strftime

`-
(dash) Do not pad a numeric result string.`

**Comment by kripken** [comment]
Thanks for the update. In that case, since we use the musl libc, it makes sense that we don't have this feature, closing.
