### ISSUE TITLE
Get FS object by its name

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#3690]
Is there a way to get FS object by its name (`"NODEFS"`, `"IDBFS"`, etc) in order to pass it to `FS.mount` using something better than the following if/switch?

```js
var fs;
if (type == "NODEFS") {
  fs = NODEFS;
} else if (type == "IDBFS") {
  fs = IDBFS;
}
```

`eval` doesn't work in case of Closure because it minifies the names. Can we put FS objects to some dict if the answer is no?

**Comment by kripken** [comment]
I don't think we have a way to do that currently. I'd be ok to have them register themselves in a dictionary. But I'm not sure where this would help?

**Comment by Kagami** [comment]
It really helps in Emscripten API wrappers, like [this one](https://github.com/Kagami/ffmpeg.js#files). If we want to support every FS that Emscripten supports, it's much more convenient to get it from dict by name.

**Comment by kripken** [comment]
I see. Sounds fine to add a dict with this.

**Comment by Kagami** [comment]
I can file a PR, but could you please give a hint, what's the best place to put that FS dict? Unfortunately it's not so obvious.

**Comment by kripken** [comment]
At or near the top of the `FS` object, I think. Maybe initialize it in the `staticInit` method. Or perhaps each FS could register itself, but I don't think they all have init methods, so that's probably a bad idea.
