### ISSUE TITLE
cannot compile even trivial OpenGL code (undeclared identifier 'glutInitContextVersion')

### ISSUE THREAD

**Issue by CubeGod** [kripken/emscripten#3691]
obligatory version check:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.4
clang version 3.7.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-unknown-linux-gnu/5.2.0
Selected GCC installation: /usr/lib64/gcc/x86_64-unknown-linux-gnu/5.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)

since that doesn't get the llvm version here's that:
llvm-config --version
3.6.2

I follow the assumption that all parts of llvm will have the same version number (installed from arch repositories)
I have traced this to freeglut_std.h not having the glutInitContextVersion. (not really that hard)
glut.h does not have such either (not surprising since it's just a wrapper that includes the former).

I then had the bright idea to just pull my local freeglut.h and freeglut_ext.h that are used for native compilation, this compiles fine.
With a slight caveat, it gives these warnings:
warning: unresolved symbol: glVertex2f
warning: unresolved symbol: glutInitContextVersion
warning: unresolved symbol: gluErrorString
warning: unresolved symbol: glEnd

If you then run it a marvelous thing happens (it crashes, if it wasn't obvious).
Needless to say this is quite frustrating as I'm compiling example OpenGL 2.1 code, this code should compile fine (and I don't see how any platform is supposed to work at all if not even basic examples compile, I don't even dare try something more sophisticated).

This is one of many annoyances (the other being that emcmake can't take the -s USE_PTHREADS=1 flag and thus can't compile some other code but I'll just use other libraries instead), and a critical one; I don't know exactly how I'm supposed to compile OpenGL applications when OpenGL does not compile with emscripten.

http://lazyfoo.net/tutorials/OpenGL/01_hello_opengl/01_hello_freeglut.zip

The code I'm attempting to compile, that's by far the simplest test case I know of and I always refer to it as an OpenGL sanity check.
It compiles fine with GCC, does not compile with emcc or em++ and the internet has not helped at all (now the reason I have to use glut is because I tried and failed to link to X11, even with a nodejs implementation available (installed through npm) I couldn't get it to work so that avenue is one I gave up on, not to mention I don't really want such a huge dependency anyway)

**Comment by CubeGod** [comment]
oh yes, this is the one liner I'm building with.
Nothing fancy at all,

em++ main.cpp LUtil.cpp -lglut -lGLU -lGL -o b.html

The documentation says -lglut -lGLU -lGL can be omitted but I include them by habit, the result doesn't change if I omit them

**Comment by CubeGod** [comment]
I'm almost entirely certain that my emscripten install could be insane (even though it passed its own sanity test), the documentation claims FULL OpenGL ES 2.0 compatbility but the mesa demos for OpenGL ES 2.0 do NOT compile.
"/usr/bin/ld: /tmp/ccSUrAPT.o: undefined reference to symbol 'XCreateColormap'
/usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[shiina@z-dev LUDUM_WARMUP]$ gcc pleb.cpp -lGL -lX11
/usr/bin/ld: /tmp/ccQxIgxd.o: undefined reference to symbol 'cos@@GLIBC_2.2.5'
/usr/lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status" 
For the es2tri.c demo

And
"main.cpp:4:9: warning: '_GNU_SOURCE' macro redefined [-Wmacro-redefined]
#define _GNU_SOURCE
        ^
<built-in>:295:9: note: previous definition is here
#define _GNU_SOURCE 1
        ^
main.cpp:15:10: fatal error: 'eglut.h' file not found
#include "eglut.h"
         ^
1 warning and 1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting"
For the es2gears.c demo

This would indicate that the GLES 2.0 support is incomplete or that my install is incomplete, I'm leaning towards the latter and will debug that in the morning.

**Comment by CubeGod** [comment]
Okay, so to verify my theory I've uninstalled emscripten and installing it using the SDK download.
Right of the bat it disagrees, it decides that looking in the environment path for python is a good idea. I would be inclined to disagree, most modern linux systems have python3 as their python path; what the script SHOULD do it look for python, check the version; if it's greater than 2.7 it should then check for python2, if that check fails it should print an error.

Python2 scripts absolutely will not run in python3, as much as I want hem to and I can't break the rest of my system for emscripten alone.

Currently I have to do:
nano emsdk, change python line.
emsdk update, 
repeat edit step.
continue install.

Once the SDK finishes installing I can determine if my build environment was insane or if emscripten 1.34 hates my system/is broken (one of them).
For now I'll leave it at this, I'm determined to find the answer to this (my original post applies regardless, I checked through the sources on github and the freeglut implementation lacks the feature mentioned in the title, I also could not find an eglut header so those should apply regardless, at least for 1.34. Fun fact is that I've seen others get the glxgears demo running fine using the mesa example code so I know emscripten SHOULD be able to compile it, it just doesn't for me.)

**Comment by juj** [comment]
Hmm, there's a few things here:

First one is that `I follow the assumption that all parts of llvm will have the same version number (installed from arch repositories)`. Emscripten comes with its own fork of LLVM, which implements a LLVM backend that targets JS. Upstream LLVM repositories cannot be used. The easiest way to set up the whole compiler toolchain is to install the sdk at http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html , which runs on linuxes an automated build script that builds the LLVM fork.

The second one that catches my eye is `I then had the bright idea to just pull my local freeglut.h and freeglut_ext.h that are used for native compilation, this compiles fine.`. Since Emscripten is a cross-compiler, using any headers from native system directories will not work. They might get through compile and link steps (with warnings) like you are seeing, but at runtime it will abort at missing symbols.

Then, `Needless to say this is quite frustrating as I'm compiling example OpenGL 2.1 code, this code should compile fine (and I don't see how any platform is supposed to work at all if not even basic examples compile, I don't even dare try something more sophisticated).`: This assumption is unfortunately not true for Emscripten. Emscripten does not support desktop OpenGL, except through a very incomplete layer of emulation. See http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html for tips about OpenGL compilation.

`the other being that emcmake can't take the -s USE_PTHREADS=1 flag and thus can't compile some other code but I'll just use other libraries instead`:

CMake does not take in Emscripten linker flags, but if you want to add that flag, you should pass `-DUSE_PTHREADS=1` to CMake, and have the CMake script translate that to `-s USE_PTHREADS=1` link flag. Alternatively, one can use the `LDFLAGS` environment variable (depending on how the target project CMakeLists.txt was set up)

`It compiles fine with GCC, does not compile with emcc or em++ and the internet has not helped at all (now the reason I have to use glut is because I tried and failed to link to X11`:

Emscripten does not implement the X windowing system - there does exist an extremely light stubbing of some functions and symbols in order to make some existing internal tests pass for conveniency, but X11 applications in general don't work. It might be possible to add support for X11, community contributions there are welcome. In general for cross platform GL context creation, one can use EGL (http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/EGL-Support-in-Emscripten.html), or SDL or GLUT, although there is no full GLUT support implemented, so some functions might be missing.

**Comment by juj** [comment]
To configure python, you can try editing the file `~/.emscripten` instead of having to edit `emsdk`. Does that work?

**Comment by CubeGod** [comment]
I will try that, I'm currently finalizing the install of the SDK as the system install might be less likely to work.

I'm not entirely sure how I'd edit the emscripten config to always use python2, given that a python script that searches the environment for python will invariably use the version it looks for
One thing I already noticed is that the env path from ./emsdk_env.sh does not let me use the sdk from different locations, even in new login shells. This is a tad annoying but I suppose I could symlink an emcc dir to my project folder and call ./emsc/em++ main.cpp [...] -o a.html

Either way, it's still kind of annoying that even with /full/ GLES 2.0 support (as the documentation states) and EGL 1.4 support (again, per the documentation) that a simple GLES2.0 project with EGL will keel over.

Anyway, regardless even a fresh SDK install will fail to compile OpenGL code, this time the example code provided with the EMSDK

[shiina@z-dev Projects]$ cd projects/LUDUM_WARMUP/emsdk_portable/emscripten/tag-1.34.4/tests/glbook/Chapter_2/Hello_Triangle/
[shiina@z-dev Hello_Triangle]$ ./../../../../emcc Hello_Triangle_orig.c
Hello_Triangle_orig.c:18:10: fatal error: 'esUtil.h' file not found
#include "esUtil.h"
         ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting

Again, missing headers as with my tests. Always missing headers.

**Comment by CubeGod** [comment]
Further testing the demos the cubegeom.c test does not work either.

./emcc tests/cubegeom.c -o d.html
tests/cubegeom.c:59:42: warning: passing 'GLuint *' (aka 'unsigned int *') to
      parameter of type 'GLint *' (aka 'int *') converts between pointers to
      integer types with different sign [-Wpointer-sign]
    glGetIntegerv(GL_TEXTURE_BINDING_2D, &boundTex);
                                         ^~~~~~~~~
/home/shiina/Projects/projects/LUDUM_WARMUP/emsdk_portable/emscripten/tag-1.34.4/system/include/GL/gl.h:848:59: note: 
      passing argument to parameter 'params' here
GLAPI void GLAPIENTRY glGetIntegerv( GLenum pname, GLint *params );
                                                          ^
tests/cubegeom.c:68:42: warning: passing 'GLuint *' (aka 'unsigned int *') to
      parameter of type 'GLint *' (aka 'int *') converts between pointers to
      integer types with different sign [-Wpointer-sign]
    glGetIntegerv(GL_TEXTURE_BINDING_2D, &boundTex);
                                         ^~~~~~~~~
/home/shiina/Projects/projects/LUDUM_WARMUP/emsdk_portable/emscripten/tag-1.34.4/system/include/GL/gl.h:848:59: note: 
      passing argument to parameter 'params' here
GLAPI void GLAPIENTRY glGetIntegerv( GLenum pname, GLint *params );
                                                          ^
2 warnings generated.
warning: unresolved symbol: glNormalPointer
warning: unresolved symbol: glRotatef
warning: unresolved symbol: glTexCoordPointer
warning: unresolved symbol: glLoadMatrixf
warning: unresolved symbol: glEnableClientState
warning: unresolved symbol: glGetPointerv
warning: unresolved symbol: glClientActiveTexture
warning: unresolved symbol: glFrustum
warning: unresolved symbol: glColorPointer

Which throws an exception, as expected given that the OpenGL code is completely dysfunctional thus far.

The aniso.c demo also fails.

./emcc tests/aniso.c -o e.html
tests/aniso.c:224:12: warning: incompatible pointer types initializing
      'void (*)(int, int)' with an expression of type 'void (GLfloat, GLfloat,
      GLfloat)' [-Wincompatible-pointer-types]
    void (*g)(int, int) = glVertex3f;
           ^              ~~~~~~~~~~
1 warning generated.
warning: unresolved symbol: glTexCoord2i
warning: unresolved symbol: glVertex2i
warning: unresolved symbol: glEnd
warning: unresolved symbol: glLoadMatrixf
warning: unresolved symbol: glVertex3f

SDL2 code also does not compile.
Now instead I am trying to downgrade to sdk-master-64bit from sdk-tag-1.34.4-64bit (which was installed by default) will report further on the status of it.

**Comment by juj** [comment]
The glbook `hello_triangle.c` demo cannot be built just by invoking `emcc` on it. It is not a standalone .c file that would build like that. There are more needed files at https://github.com/kripken/emscripten/tree/master/tests/glbook/Common , so include directives (and possibly other command line directives) are needed. If you want to test running that in a simple manner, invoke `python tests/runner.py browser.test_glbook` in the root Emscripten directory.

Also `cugegeom.c` does not work like that. Like mentioned in the GL support page documentation I linked to above (http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html#opengl-support-legacy-and-mobile), emulating desktop GL requires a linker flag `-s LEGACY_GL_EMULATION=1`. See here for the command line that the test harness runs when building `cubegeom.c`: https://github.com/kripken/emscripten/blob/master/tests/test_browser.py#L1425 .

**Comment by CubeGod** [comment]
Okay, while I never got any OpenGL code to compile standalone I can get it to work in conjunction with SDL, but not under tag-3.14.4, only under master.

Either way, I am probably at fault for most of these aside from the missing headers, the missing headers are indeed missing (at least under tag, didn't bother to re-run those tests under master as I have a time constraint)

**Comment by juj** [comment]
I'll close this as resolved, like you mention you got some code working. There were several different items that were discussed here, so if issues with those persist, let's open individual specific bug items to track them further, that will help focus the conversation better on individual bugs.
