### ISSUE TITLE
empty glbegin..glend block leads to exception

### ISSUE THREAD

**Issue by jarikomppa** [kripken/emscripten#3693]
This should be relatively easy to fix for someone who understands how the legacy gl support works.

I've been porting some old opengl code over to emscripten, and there's code blocks which may generate 0..N vertices inside glBegin()..glEnd(). If the block generates zero vertices, emscripten-generated code doesn't work, and produces error:

"exception thrown: TypeError: nextFreeBufferIndex is undefined,getTempVertexBuffer"

**Comment by juj** [comment]
Thanks! Fixed in above commit.
