### ISSUE TITLE
performance with GL's getError()

### ISSUE THREAD

**Issue by Dchandaman** [kripken/emscripten#3708]
getError() is called too often and is showing up in performance profiles.  In my particular case, taking up about 5% of the time.  A solution might be a flag we can pass in to skip calling getError in _glGetError().

**Comment by kripken** [comment]
Is this from calling `glGetError` in your code? Or is this happening from our glue code somewhere?

**Comment by Dchandaman** [comment]
I believe it is the glue code.  I will try and get a list of functions.


On August 21, 2015 at 10:25:52 AM, Alon Zakai (notifications@github.com) wrote:

Is this from calling glGetError in your code? Or is this happening from our glue code somewhere?

**Comment by Dchandaman** [comment]
I apologize.  Looks like it is our code. 


On August 21, 2015 at 10:28:50 AM, Daniel Miya (hachijugo@gmail.com) wrote:

I believe it is the glue code.  I will try and get a list of functions.


On August 21, 2015 at 10:25:52 AM, Alon Zakai (notifications@github.com) wrote:

Is this from calling glGetError in your code? Or is this happening from our glue code somewhere?

**Comment by kripken** [comment]
Ok, no problem. I guess we can close this then.
