### ISSUE TITLE
<random> linear_congruential_engine and subtract_with_carry_engine not consistent with other platforms

### ISSUE THREAD

**Issue by iboB** [kripken/emscripten#3712]
Simple repro case:

```
ranlux24 rl(1234);
for(int i=0; i<5; ++i)
    cout << rl() << endl;
minstd_rand mr(5678);
for(int i=0; i<5; ++i)
    cout << mr() << endl;
```

I get the same numbers on Windows with msvc12 and Linux with gcc 4.9.2 but different ones in the browser with Emscripten.

Only the Mersenne Twister engine seems to produce the same numbers on all platforms.

edit: In case it's not clear. I do get the same numbers on different runs in the browser. The seed works. What I don't get are the same numbers across all platforms.

**Comment by kripken** [comment]
Should they be the same across platforms? What is the relevant spec?

**Comment by iboB** [comment]
From http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3551.pdf  

> For knowledgable users, the library provides nine additional aliases for pre-configured
> engine types of known good quality.12 These types span a wide spectrum of trade-offs in
> performance and size. Among other characteristics, the C++11 standard requires that these
> engines produce bit-for-bit identical results across implementations

**Comment by iboB** [comment]
Also, I just tested this and I get the exact same values on Mac OS X with clang 3.6.0 (Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn))

**Comment by iboB** [comment]
Well, I cannot reproduce this 1.34.6. I could in 1.34.1. I have no Idea what might have caused this...

**Comment by kripken** [comment]
It's possible a libc update since 1.34.1 made a difference.
