### ISSUE TITLE
warning: unresolved symbol: mkport

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#3724]
We get this warning at link time:

`warning: unresolved symbol: mkport`

We don't use any function named as `mkport` in any source file, and neither in any external libraries. We are building against Emscripten `1.34.6` on Windows using CMake and the toolchain file provided. Could it be a bug in Emscripten?

**Comment by kripken** [comment]
Yes, sounds like a bug. Can you see where (in a non-minified build) that is called? Or provide a testcase to reproduce the issue.

**Comment by raptor** [comment]
I am hitting the same exact issue on the same version of emscripten.  I am getting the same on these symbols (I know this issue is only for the `mkport` one...  and possibly also `htonl`):
```
warning: unresolved symbol: htonl
warning: unresolved symbol: glPointSize
warning: unresolved symbol: mkport
warning: unresolved symbol: ltc_mp
```
I am compiling a large codebase; here is a link to the debug build JS (9MB; 71MB uncompressed):  http://bitfighter.org/~raptor/bitfighter.js.zip

**Comment by kripken** [comment]
* `htonl`: That shouldn't be a problem on incoming. If it still is, can you provide the bitcode to debug it?
 * `glPointSize` looks like something not in WebGL, so we don't support it. If you call that at runtime, it will fail.
 * `mkport` was a no longer needed dependency in the sockets code, fixed on incoming.
 * `ltc_mp`: not sure what that is?

**Comment by kripken** [comment]
@gouletr : does your problem go away with latest incoming?

**Comment by gouletr** [comment]
Yep, confirmed it works after pulling 108797d366f4e0ee8fab90908310736665c8b103.
