### ISSUE TITLE
Add information about Swift to Javascript conversion

### ISSUE THREAD

**Issue by DanielAsher** [kripken/emscripten#3726]
Swift compiles to LLVM. Can emscripten handle Swift to Javascript conversion? 

A clear answer would be useful in the Readme.md

**Comment by kripken** [comment]
Depends on swift. Does it need a runtime? If so is there a portable open source runtime?

**Comment by DanielAsher** [comment]
Hi kripken,

these are good questions. I don't have any definitive answers. Swift 2.0 and standard library will be open sourced in the next few months.

Until then I could only find information about intermediate `SIL -> LLVM IR` transformation here:

https://www.accelebrate.com/blog/thinking-swift-part-ii/

**Comment by juj** [comment]
There were some discussion threads about compiling swift in emscripten-discuss, try a search there for the past results? iirc the development blocked back then on not having an open source runtime available.

**Comment by DanielAsher** [comment]
@juj :+1: 
[this](https://groups.google.com/forum/#!searchin/emscripten-discuss/swift/emscripten-discuss/Q0kvsJhQvhE/zoheLfg8hp4J) raises the question. 

guess we'll wait for the open source to arrive :)

**Comment by ahti** [comment]
In the meantime, Swift open source has arrived. It does require a runtime, which was also released as open source and is written in C++.

Swift also has a set of core libraries, written in a mixture of Swift and C which would be cool, but not necessary to have.
