### ISSUE TITLE
How to make libwebp javascript library from header files?

### ISSUE THREAD

**Issue by acterhd** [kripken/emscripten#3727]
Hello, I have one question. Under linux I try to get libwebp with javascript, but from header files I gets only binary code. How I can get JS library file?

**Comment by juj** [comment]
Header files only contain declarations of code symbols, and not the code itself. If you want to build libwebp to javascript, you should obtain the full source code for example from https://chromium.googlesource.com/webm/libwebp and port that to Emscripten.

**Comment by juj** [comment]
Let me close this as resolved. Feel free to reopen if there's still something to address (though the mailing list emscripten-discuss may suit better to porting help q&a format)
