### ISSUE TITLE
Missing $n arguments for EM_ASM_INT(or DOUBLE) blocks that don't use all of their arguments

### ISSUE THREAD

**Issue by svetlin-mladenov** [kripken/emscripten#3730]
If an EM_ASM_INT block gets more then 1 argument and some of the arguments are not used then the compiler doesn't generate $1, $2 or so on arguments for the the ASM_CONST function.

Here is a test case that will hopefully clarify what I mean:

    def test_unused_em_asm_arguments(self):
      src = r'''
        #include <stdio.h>
        #include <emscripten.h>
  
        int main(int argc, char **argv) {
          int sum = EM_ASM_INT({
             return $0 + $2;
          }, 0, 1, 2);
          printf("0+2=%d\n", sum);
          return 0;
        }
      '''
      self.do_run(src, '''0+2=2''')

And here is the generated ASM_CONSTS:

    var ASM_CONSTS = [function($0) { { return $0 + $2; } }];

As you can see the $1 and $2 are missing. I am using the incoming branch commit 108797d366f4e0ee8fab.

if $1 is added to the body of the EM_ASM_INT block then everything works es expected. For example:

        int main(int argc, char **argv) {
          int sum = EM_ASM_INT({
             $1;
             return $0 + $2;
          }, 0, 1, 2);
          printf("0+2=%d\n", sum);
          return 0;
        }

generates:

   var ASM_CONSTS = [function($0, $1, $2) { { $1; return $0 + $2; } }];

**Comment by kripken** [comment]
Thanks for reporting, and especially for reporting with a testcase in the test suite format!

This was an embarrassing bug with the compiler assuming all arguments were used. Fixed on incoming (note: need to update both fastcomp and emscripten repos).
