### ISSUE TITLE
Overwrite of global variable 'buffer' when BUILD_AS_WORKER=1

### ISSUE THREAD

**Issue by svetlin-mladenov** [kripken/emscripten#3736]
The global variable buffer (defined in src/preamble.js) holds the ArrayBuffer that represents the memory.

When BUILD_AS_WORKER=1 src/postamble.js is appended to the end of the output javascritp file. src/postamble.js however defines its own global variable called buffer (towards the end of the file just before onmessage = function onmessage(msg) ...). This  variable overwrite the value of buffer with an integer value that has a completely different meaning.

This bug has been in the code base for a very long time. It stays hidden because the buffer variable is very rarely used. But if it's used like for example if ALLOW_MEMORY_GROWTH=1 and enlargeMemory() is called then buffer will be overwritten with the new ArrayBuffer and when the worker receives a message the code in onmessage will execute HEAPU8.set(data, buffer); but buffer will not be an address but rather the ArrayBuffer and this will corrupt the memory array causing undefined behavior and eventually the script to "explode".

Here is a test:

    def test_global_variable_buffer_is_not_shadowed_in_workers(self):
      src = r'''
        #include <stdio.h>
        #include <emscripten.h>
  
        int main(int argc, char **argv) {
        	EM_ASM_INT_V({
              // add a dummy 0 timeout because nodejs furst executes the main function and only then the worker releated code
              // in a browser environment there is not need for the timeout
              setTimeout(function() {
         		   var msg = (buffer === HEAPU8.buffer) ? 'variable buffer is global memory' : 'varible buffer is NOT global memory';
                 console.log(msg);
              }, 0);
        	});
          return 0;
        }
      '''
      # test that buffer is indeed the memory ArrayBuffer when code is not built as a worker
      self.do_run(src, '''variable buffer is global memory''')
  
      # test that buffer is still the moemroy ArrayBuffer even when built as a worker
      self.emcc_args += ['-s', 'BUILD_AS_WORKER=1']
      self.do_run(src, '''variable buffer is global memory''', )

**Comment by kripken** [comment]
Fixed on incoming, thanks!
