### ISSUE TITLE
incoming branch build error (windows build)

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#3738]
I don't know which commit broke the build, but the commit at the time of writing this (49ff68e7cdc3dbbd18fda448c5a9cca04f277d58) doesn't build :
```
...\clang\fastcomp\src\lib\Bitcode\NaCl\Reader\NaClBitcodeHeader.cpp(299): error C3486: a parameter for a lambda cannot have a default argument
```
```
...\clang\fastcomp\src\include\llvm/Bitcode/NaCl/NaClRandNumGen.h(33): error C2143: syntax error : missing ';' before '(' (emsdk-1.34.1-portable-64bit\clang\fastcomp\src\lib\Bitcode\NaCl\TestUtils\NaClRandNumGen.cpp)
```

**Comment by gouletr** [comment]
Um, looks like it is actually this commit (https://github.com/kripken/emscripten-fastcomp-clang/commit/7096322e0fd07adbeed2967fd71ee4f61c8b1518) on clang fastcomp

**Comment by juj** [comment]
The fix for this is already in, pending a review: https://github.com/kripken/emscripten-fastcomp/pull/115

**Comment by kripken** [comment]
Merged that pull.
