### ISSUE TITLE
Possible reordering of emscripten_call_worker calls before main is called

### ISSUE THREAD

**Issue by svetlin-mladenov** [kripken/emscripten#3741]
I am not certain about this one but while reviewing 89047d8e5c6ef9f539ccdf23ff5c8ebf7e2f9425  I noticed the following possible ordering of events:

1. the worker is loaded by the js engine. there is async work to be done so main() is not immediately called and runtimeInitialized==false
2. the worker receives a message from emscripten_call_worker. The code in src/postamble.js (towards the end of the file) will see that the runtime is not yet initialized and will put the message on a queue and wind a timer that checks if the environment is initialized every 100ms
3. the runtime gets initialized and runtimeInitialized is set to true
4. the worker receives another message from emscripten_call_worker. This time the runtime is initialized and the callback function will be called immediately
5. the timer winded on step 2 fires and the callback for the message sent on step 2 will be called. The two calls will effectively get reversed.

**Comment by kripken** [comment]
Thanks, yes, that definitely looks like a bug. How does fa97850c2b3402b15cb34a4f7482a820880a98da look to you?

**Comment by svetlin-mladenov** [comment]
Looks good.

**Comment by kripken** [comment]
Thanks, merged.
