### ISSUE TITLE
Uncaught exception: TODO

### ISSUE THREAD

**Issue by raptor** [kripken/emscripten#3752]
Hi,

I've got my code base compiling against the latest `incoming` branch.  When running it properly resizes the window but then throws an exception like so:
```
uncaught exception: TODO : jsStackTrace@file:///home/user/code/git/bitfighter/exe/bitfighter.js:1:42884
stackTrace@file:///home/user/code/git/bitfighter/exe/bitfighter.js:1:43067
FS.handleFSError@file:///home/user/code/git/bitfighter/exe/bitfighter.js:1:138097
_bind@file:///home/user/code/git/bitfighter/exe/bitfighter.js:1:349914
jTc@file:///home/user/code/git/bitfighter/exe/bitfighter.js:9:411578
KQc@file:///home/user/code/git/bitfighter/exe/bitfighter.js:9:350977
wga@file:///home/user/code/git/bitfighter/exe/bitfighter.js:11:447823
m_@file:///home/user/code/git/bitfighter/exe/bitfighter.js:11:223980
OUb@file:///home/user/code/git/bitfighter/exe/bitfighter.js:5:150975
rw@file:///home/user/code/git/bitfighter/exe/bitfighter.js:15:115385
ww@file:///home/user/code/git/bitfighter/exe/bitfighter.js:15:126779
callMain@file:///home/user/code/git/bitfighter/exe/bitfighter.js:24:45694
doRun@file:///home/user/code/git/bitfighter/exe/bitfighter.js:24:46521
run/<@file:///home/user/code/git/bitfighter/exe/bitfighter.js:24:46689
```
This error seems to be thrown when calling this function in the `bitfighter.js` file:
```
sock.sock_ops.bind(sock,addr,port);
```
I've been looking around at the emscripten code but can't seem to find where an unresolved TODO may be for this.  Am I doing something wrong?

My linking command was:
```
/home/user/apps/emsdk_portable/emscripten/incoming/emcc -s USE_SDL=2 -s LEGACY_GL_EMULATION=1 -s GL_UNSAFE_OPTS=0 -s ALLOW_MEMORY_GROWTH=1 -DNDEBUG -O2 --preload-file /home/user/code/git/bitfighter/resource@/ -O2 @CMakeFiles/bitfighter.dir/objects1.rsp -o ../../exe/bitfighter.html -pthread ../../lib/liblua.a ../tnl/libtnl.a ../tomcrypt/libtomcrypt.so ../clipper/libclipper.a ../poly2tri/libpoly2tri.a -lm ../../lib/libphysfs.a -pthread --emscripten-cxx  (in /home/user/code/git/bitfighter/build/zap)
```
Here is the compiled project:  http://bitfighter.org/~raptor/bitfighter.zip
And here is the `.bc` file:  http://bitfighter.org/~raptor/bitfighter.bc.zip

Thanks!

**Comment by kripken** [comment]
There is a `throw 'TODO'` in `mkport`, which makes sense if it happens in a call to bind. `mkport` was removed from incoming, perhaps trying with the latest code fixes this?

**Comment by raptor** [comment]
This is the latest code, the `1.34.7` tag on the `incoming` branch.  Or, actually, I see two new commits now.  Is it in one of those?

**Comment by kripken** [comment]
No, looks like it happened before the tag, at 108797d366f4e0ee8fab90908310736665c8b103

Something wrong with the checkout perhaps?

**Comment by raptor** [comment]
Nope, I did a brand new sdk checkout last night to compile with these results.

**Comment by kripken** [comment]
That commit is on incoming, so I'm not sure why it isn't on your local checkout. Might be a git issue somehow? You should see all these commits locally: https://github.com/kripken/emscripten/commits/incoming

**Comment by raptor** [comment]
Argh, I see now - I just ran `emcc -v` and got 1.34.0 on everything again.  Maybe this is still related to that other issue with mismatched versions.  I'm not sure why this happened - I thought doing a fresh checkout on `incoming` would solve everything.

Can I manually update both git branches locally?

**Comment by kripken** [comment]
There are three branches, also one for clang. Manually doing `git checkout incoming` and `git pull` in the repos should update them all, then you just need to build llvm+clang.

**Comment by raptor** [comment]
OK, I found and updated all three branches; however, I had to run commands like so:
```
git pull origin incoming
...
git pull
```
For some reason `git checkout incoming` always yielded this error:
```
error: pathspec 'incoming' did not match any file(s) known to git
```
A look at the output of `emsdk install sdk-incoming-64bit` shows that the same error occurred beforehand when building LLVM at version 1.34.0.

Perhaps this was because I checked it out with the `--shallow` flag the first time?

With the latest `1.34.7`, the game compiles again.  The missing symbol `htonl` somehow returned
and running it gives an `abort("unsupported socketcall syscall 6")`.  I'm not sure which socketcall that is.

Thank you for your help so far.  Is there a better place to get help on these issues as I try to get our codebase to work in the browser?  I don't want to create too much noise in your issues list.

**Comment by raptor** [comment]
Looks like the `--shallow` did indeed create some issues.  In the `.git/config` for each branch, it had this in it:
```
fetch = +refs/heads/master:refs/remotes/origin/master
```
A change to this fixes the `incoming` issue:
```
fetch = +refs/heads/*:refs/remotes/origin/*
```
Then I could do a `git fetch`, `git checkout incoming`.  This doesn't change my compiling issues as I was on the correct commit already (just missing the ref for `incoming`.)

**Comment by kripken** [comment]
@raptor: This is the right place for these questions, no problem.

Can you create a standalone testcase showing that htonl crash? We have tests for it that pass, so there must be something we do not have covered that is broken.

@juj: is there an issue for the shallow clone problem.

**Comment by kripken** [comment]
(@raptor: might be useful to modify an existing tests in tests/test_sockets.py`, but if a new one is easier that's fine too)

**Comment by raptor** [comment]
Are you saying that my error of `abort("unsupported socketcall syscall 6")` is indeed due to the `htonl` missing symbol?

**Comment by kripken** [comment]
It might be related, I'm not sure yet without a testcase.

**Comment by raptor** [comment]
OK, I'm putting together a test case (a little slow, sorry).  I'll close this one as a duplicate of the other that tracks the `--shallow` issue

Duplicate of issue #3751
