### ISSUE TITLE
asm.js call _malloc each time when doing memcpy

### ISSUE THREAD

**Issue by solaslin** [kripken/emscripten#3755]
I'm porting a matrix library to JS for some performance test.
My first try is to embind the "operator =" to a JS function "CopyFrom"

What I do is just a memcpy, but somehow, when i looping 1,000,000 times to call CopyFrom, 
I got the "Cannot enlarge memory arrays" error. 

Then I trace the asm.js code and found that: 
In my function, the last line "return *this" will invoke a _malloc (in asm.js) and then a copy constructor of this matrix class

I post some step-by-step tracing screenshot below. 
Please, hope someone can tell me if there is something wrong..

1. The operator =  calls memcpy and return its own alias (reference)
![memcpy](https://cloud.githubusercontent.com/assets/14176347/9730627/4f542cc6-564a-11e5-98d8-2a245c5bd5d7.png)

2. Binding CopyFrom to this operator
![bind](https://cloud.githubusercontent.com/assets/14176347/9730640/647d021c-564a-11e5-8c42-0dc876266840.png)

3. Matrix Class has a copy constructor
![ctor](https://cloud.githubusercontent.com/assets/14176347/9731118/990da79a-564d-11e5-8d1d-9c0c31729613.png)

4. in my JS:
var mat1 = new Module.Matrix4x4();
var mat2 = new Module.Matrix4x4();
for ( var i = 0; i < 1000000; ++i ) {
	mat2.CopyFrom( mat1 ); 
}

5. Then I got the "Cannot enlarge memory arrays" error, this is the call stack:
![stack](https://cloud.githubusercontent.com/assets/14176347/9730642/6a1d7ff8-564a-11e5-99a1-f64273879b3f.png)

6. I use source map to trace the asm.js and here, i believe the $9 is my "operator =" function
![additioncall](https://cloud.githubusercontent.com/assets/14176347/9730763/4d011f82-564b-11e5-9ca8-667cda58840a.png)

7. Step in this function...Doing a memcpy and then return. Looks normal.
![operator](https://cloud.githubusercontent.com/assets/14176347/9730656/74151444-564a-11e5-8d0b-a27df6d278d2.png)

8. Back to 6, I stepped in the next line and this is what I don't understand...
It calls a _malloc, and then the last breakpoint seems the copy constructor of a Matrix.
( line 23 is the memcpy in that ctor )
Looks like it creates a new matrix and return to $10 (fig. 6). 
So finally, this CopyFrom returns a new instance, I think that's why the memory will grow...
How should I refine my code to avoid this ??
![question](https://cloud.githubusercontent.com/assets/14176347/9730663/891238cc-564a-11e5-9465-912a780bbfac.png)

**Comment by waywardmonkeys** [comment]
I believe you're seeing the code from here:

https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/system/include/emscripten/wire.h#L323-L339

```c++
        template<typename T>
        struct GenericBindingType {
            typedef typename std::remove_reference<T>::type ActualT;
            typedef ActualT* WireType;

            static WireType toWireType(const T& v) {
                return new T(v);
            }

            static WireType toWireType(T&& v) {
                return new T(std::forward<T>(v));
            }

            static ActualT& fromWireType(WireType p) {
                return *p;
            }
        };
```

emscripten wants to hold on to a pointer to the object since otherwise the lifetime of the value won't be happy.

So, it creates a copy of your value ...

When you're done with it, you need to call ``delete`` or call ``deleteLater`` after it is created and you know the lifetime will be short.

You may find reading through the tests in ``https://github.com/kripken/emscripten/blob/master/tests/embind/embind.test.js`` useful ... especially looking at calls to ``delete`` and ``deleteLater``.

I suspect without thinking too hard about it, so I may well be wrong, that you're seeing the temporary returned from ``operator=`` get copied into the JS world, not just the value of ``mat2`` being updated.

embind requires pretty rigorous attention to details like the above.

**Comment by solaslin** [comment]
Yes, thank you, it helps indeed.=)  

I really found the issues you mentioned yesterday. ( Almost for **`operator +-*/`** ) But as for this "assign operator", I think this is maybe it has a different behavior...

This is what I'm thinking:
We usually declare **`operator =`** with **`Type& Type::operator = ( const Type& rhs )`** and use it by **`obj1 = obj2`**. Here obj2 is a argument but obj1 is both a caller and a receiver...

Compare with an ordinary function **`Type& Type::CopyFrom( const Type& rhs )`** It has a return value, an argument, and a caller object of course. So we must use it by **`retObj = obj1.CopyFrom( obj2 );`**  (Without considering the operator = overloading) This means we have 3 different roles in this function call.

Because a assign operator automatically takes the caller as the receiver, but an ordinary function doesn't, it really returns a value. So Actually It is not good to bind this kind of operators to functions ( same reason for +=, -=...etc )

**Comment by waywardmonkeys** [comment]
Is there a bug here that needs fixing or can this be closed?

**Comment by solaslin** [comment]
Yes, I think this can be closed =) It's not a bug
