### ISSUE TITLE
EM_ASM_DOUBLE return gets truncated to int on linux

### ISSUE THREAD

**Issue by emilydolson** [kripken/emscripten#3770]
I have the following test code:

    #include <emscripten.h>
    #include <iostream>

    int main(){
      std::cout << EM_ASM_DOUBLE({
          console.log($0); 
          return $0; },1.2) << std::endl;
    }

This prints 1.2 to the console and 1 to stdout. I have tried all sorts of variants, such as printf, EM_ASM_DOUBLE_V, different numbers, and so on, but the result is always the same: the double is truncated down to an int when it is returned to C++. I tried running the compiled code in Chrome, Firefox, and node.

I am running Linux Mint 17, and have replicated this bug on a computer running Ubuntu 14.04. Compiling the same program on a mac, however, produces the expected result of printing 1.2 to both the console and stdout. Running the output of the compilation on the mac on my computer also produces the expected result.

This originally happened in emscripten 1.10, but I re-installed in an attempt to fix it, so my current emscripten installation is version 1.34.8, clang version 3.7.0. I want to say that it was originally working fine and this started happening in the past week or so, because I could swear I ran tests earlier that should have caught this, but I can't say with certainty that I wasn't just really oblivious before.

I have no idea what could be causing this. I ran the core tests (using the parallel runner) and they all passed, but some tests in "sanity" and "other" have failed (I haven't tested "browser", "sockets", or "interactive" yet:

In sanity:
- test_emcc_caching (with OSError: [Errno 2] No such file or directory: '/tmp/emscripten_temp')
- test_embuilder (with AssertionError: not seeing that requested library optimizer.exe has been built)
- test_native_optimizer (with an AssertionError on "assert 'building native optimizer' in output")

In other:
- test_crunch (with OSError: [Errno 2] No such file or directory: 'test.data')
- test_scons (with OSError: [Errno 2] No such file or directory)
- test_llvm_lit (with AssertionError: LLVM tests must pass with exit code 0)
- test_outline (with an AssertionError on assert len(JS_ENGINES) > 1)

I am completely at a loss as to what could be going wrong here.

**Comment by kripken** [comment]
Thanks! We should have tested double return values, but didn't...

Fixed on incoming, added a test too.

(I think those test failures you see are that some of the tests have various requirements, like that the v8 and spidermonkey shells be installed, or crunch, etc., which in general are optional. Nothing to worry about.)
