### ISSUE TITLE
--separate-asm option fails when pthread support is enabled

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#3774]
I get this error when trying to use `--separate-asm` option and running in Firefox Nightly, with pthread enabled. Running without this option works fine.
```
pthread sent an error! TypeError: Module.asm is not a function
[post-exception status] Exception thrown, see JavaScript console
TypeError: Module.asm is not a function
```

**Comment by kripken** [comment]
Fixed, thanks. When asm is separated, pthreads need to importScripts.
