### ISSUE TITLE
test_outline fails when only one test engine available.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3776]
https://github.com/kripken/emscripten/commit/08939e21702670ca7bf711125808676359c0c5ea#commitcomment-13235046

http://clb.demon.fi:8112/builders/osx-incoming/builds/1048/steps/other%20suite/logs/stdio

I suppose the assert is not really necessary? (this will be removed once I re-add SpiderMonkey to the bots, however other people who do not have two engines to run with will still fail here)

**Comment by kripken** [comment]
I believe I saw issues with different JS engines here, and ending up requiring coverage for at least 2, but not v8. However, I'd be ok to remove the assert, as I run multiple engines locally.

**Comment by juj** [comment]
The assert was removed in above commit.
