### ISSUE TITLE
When linking, "-l c" and "-l m" do not work.

### ISSUE THREAD

**Issue by The-Humanoid** [kripken/emscripten#3777]
When linking, "-lm" works, but "-lc", "-l c", and "-l m" don't work.

"-l c" and "-l m" are supported by the unix spec for c99, so it would be helpful if they would work.

**Comment by The-Humanoid** [comment]
When using the versions with the space after the -l, I get these errors:

ERROR    root: c: No such file or directory ("c" was expected to be an input file, based on the commandline arguments provided)
ERROR    root: m: No such file or directory ("m" was expected to be an input file, based on the commandline arguments provided)

When using "-lc" with no space, I get this warning:

WARNING  root: emcc: cannot find library "c"

**Comment by juj** [comment]
Is there an URL to the relevant spec wording online somewhere?

**Comment by The-Humanoid** [comment]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/c99.html

Look in "EXTENDED DESCRIPTION" -> "Standard Libraries"

It works fine in gcc and clang.  Something must've broke when doing the emscripten port of clang.

**Comment by kripken** [comment]
We have a python script as our frontend, we just need to add support that. Should be quite easy.

**Comment by pimlu** [comment]
Hi, I'm hoping to make a PR fixing this.  I've already written a fix that passes tests, but I still need to write a test for #3777 itself, which will happen soon.

One thing I'm unsure about is fixing this for `-I`, which I observed in GCC/Clang also features this behavior.  Doing so causes most tests to spam with [absolute path warnings](https://github.com/kripken/emscripten/blob/60ec2242db0223b07dae0c41c973ad20bad33f2a/emcc#L639) (which technically should have been shown in the first place) because the tests use files in `/tmp`.

What should be done about this?  Also, I was told to cc @juj.

**Comment by pimlu** [comment]
So, 56e356a has a test for #3777 which fails without the patch due to the parsing issue.  I tested that it passes the whole core suite.  We still need to do something about the warnings, though.

**Comment by juj** [comment]
In the tests, you can pass `-Wno-warn-absolute-paths` to hide the warnings. Slightly related, we have this pending item https://github.com/kripken/emscripten/issues/2713 about switching the default behavior, although, I haven't seemed to be able to find a good timing to change the behavior yet.

**Comment by pimlu** [comment]
Can I change it to use  `Wwarn-absolute-paths` in the same branch as 56e356a, so they both make it into the PR?  It's a very small fix.

**Comment by juj** [comment]
Yeah, adding multiple commits to same pull request is ok. Just prefer not to have any merge commits in the pull request, since those are quite tedious to deal with.

**Comment by pimlu** [comment]
I was trying to edit the documentation to reflect #2713, however even building fresh off of incoming gives a result inconsistent with what's in the build directory.  You can see the difference [here](https://github.com/pimlu/emscripten/commit/8177e1cd2e9d75a098104e45494fc7fc49977f50) - do you know what might be wrong?

I'm using the latest Sphinx (1.3.1).

**Comment by kripken** [comment]
Not sure. But I wouldn't worry about those differences.
