### ISSUE TITLE
test_lua fails on Linux and OS X with "Input file has an unknown suffix, don't know what to do with it!"

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3779]
Looking at the bot runs of `test_lua` on Linux and OS X, they both fail with the error message

	======================================================================
	FAIL: test_lua (test_core.default)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/Users/clb/emslave/buildslave/osx-incoming/emsdk/emscripten/incoming/tests/test_core.py", line 5919, in test_lua
	    output_nicerizer=lambda string, err: (string + err).replace('\n\n', '\n').replace('\n\n', '\n'))
	  File "/Users/clb/emslave/buildslave/osx-incoming/emsdk/emscripten/incoming/tests/runner.py", line 488, in do_run
	    build_ll_hook=build_ll_hook, extra_emscripten_args=extra_emscripten_args, post_build=post_build)
	  File "/Users/clb/emslave/buildslave/osx-incoming/emsdk/emscripten/incoming/tests/runner.py", line 250, in build
	    assert os.path.exists(filename + '.o.js'), 'Source compilation error: ' + output
	AssertionError: Source compilation error: ERROR    root: /Users/clb/emslave/buildslave/osx-incoming/emsdk/.tmp/emscripten_test_default_WMndBt/building/lua/src/lua: Input file has an unknown suffix, don't know what to do with it!

Haven't looked at this further - any clues if something might have changed here @kripken ?

**Comment by juj** [comment]
http://clb.demon.fi:8112/builders/osx-incoming/builds/1053/steps/default%20suite/logs/stdio

and

http://clb.demon.fi:8112/builders/ubuntu-incoming/builds/1055/steps/default%20suite/logs/stdio

**Comment by kripken** [comment]
I can't think of anything. The test passes for me on multiple linux machines. Very strange.

**Comment by juj** [comment]
Apparently GNU Make treats a directory name ".tmp" as a file with the suffix .tmp or something similar. Fixed in the above commit by renaming the temp directory to "tmp" instead.
