### ISSUE TITLE
llvm-lit broken on bots

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3784]
other.test_llvm_lit seems to fail on the bots. For it to work, LLVM has to be built with tests enabled, and might require `make check` (with configure it seems to, not sure about cmake).

**Comment by juj** [comment]
I've been looking at this, added an option earlier to emsdk to build LLVM with tests, https://github.com/juj/emsdk/commit/aebcc04dc759f7864bc34214603b363112128995, however I think the failure is something different now.

**Comment by kripken** [comment]
Yes, looks like SIMD changes broke lit tests.

**Comment by kripken** [comment]
cc @sunfishcode

**Comment by sunfishcode** [comment]
It looks like 911b8b9af3b876649d412ed3c1029a93de3316ac removed the support for partial loads and stores (load1, load2, load3, store1, store2, store3). @juj is this something that could be added back in?

**Comment by juj** [comment]
Thanks. Added support for less than 128 bit types in pull request https://github.com/kripken/emscripten/issues/3784 and tested that it fixes llvm-lit test.

**Comment by juj** [comment]
The above PR was merged, this should be working after bots do their latest run, and can then be closed.

**Comment by kripken** [comment]
Still looks broken locally for me,

````
******************** TEST 'LLVM :: CodeGen/JS/expand-insertextract.ll' FAILED ********************
Script:
--
/home/alon/Dev/fastcomp/build/Release+Asserts/bin/llc < /home/alon/Dev/fastcomp/test/CodeGen/JS/expand-insertextract.ll | /home/alon/Dev/fastcomp/build/Release+Asserts/bin/FileCheck /home/alon/Dev/fastcomp/test/CodeGen/JS/expand-insertextract.ll
--
Exit Code: 1

Command Output (stderr):
--
/home/alon/Dev/fastcomp/test/CodeGen/JS/expand-insertextract.ll:9:10: error: expected string not found in input
; CHECK: SIMD_Float32x4_store(HEAPU8, $0, $p);
         ^
<stdin>:10:2: note: scanning from here
 temp_Float32x4 = $0;SIMD_Float32x4_store(HEAPU8, temp_Float32x4, $p);
 ^
<stdin>:10:22: note: possible intended match here
 temp_Float32x4 = $0;SIMD_Float32x4_store(HEAPU8, temp_Float32x4, $p);
                     ^

******************** TEST 'LLVM :: CodeGen/JS/simd-loadstore.ll' FAILED ********************
Script:
--
/home/alon/Dev/fastcomp/build/Release+Asserts/bin/llc < /home/alon/Dev/fastcomp/test/CodeGen/JS/simd-loadstore.ll | /home/alon/Dev/fastcomp/build/Release+Asserts/bin/FileCheck /home/alon/Dev/fastcomp/test/CodeGen/JS/simd-loadstore.ll
--
Exit Code: 1

Command Output (stderr):
--
/home/alon/Dev/fastcomp/test/CodeGen/JS/simd-loadstore.ll:8:10: error: expected string not found in input
; CHECK: var $q = 0, $s = SIMD_Float32x4(0,0,0,0), $t = SIMD_Float32x4(0,0,0,0)
         ^
<stdin>:5:2: note: scanning from here
 var $s = SIMD_Float32x4(0,0,0,0), $t = SIMD_Float32x4(0,0,0,0), label = 0, sp = 0, temp_Float32x4 = 0;
 ^

--

********************
Testing Time: 0.15s
********************
Failing Tests (2):
    LLVM :: CodeGen/JS/expand-insertextract.ll
    LLVM :: CodeGen/JS/simd-loadstore.ll

  Expected Passes    : 27
  Unexpected Failures: 2
FAIL

````

**Comment by juj** [comment]
Oh, these are new failures I haven't seen before. I tested locally and fixed other cases before. I'll look further on these new failures.

**Comment by juj** [comment]
I see you fixed the last few issues. The bots look happy as well, so this is fixed in current incoming.
