### ISSUE TITLE
Remove the default behavior of decoding all preloaded audio and images?

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3785]
It feels that the default behavior we have that the whole filesystem is scanned at startup and all image and audio files are decoded immediately is not a good one:
    - only small projects load all of their assets immediately at startup, most need to manage when to load things, since it can take very long time to load everything, and a lot of memory as well.
    - the feature is specific to SDL 1, and not used in other APIs.
    - it occurs silently without developers knowing, slowing down startup, and the `--preload-file` workflow does not make it apparent that all assets will be immediately loaded at startup.
    - I think most developers don't use this feature, but they use their own asset loading - actually I have not seen a single project or engine use this feature.

We do have the `noImageDecoding: true` and `noAudioDecoding: true` flags, but they are disabled by default.

Preloading was implemented to fix the async->sync problem that audio and image decoding are asynchronous I believe?

I think we should go towards a path where we remove this feature altogether. However I don't want to break anyone's existing projects immediately. Perhaps we could take a two step deprecation path:
   - first step: issue a warning to console when image or audio is automatically decoded, unless `Module.autoImage/AudioDecoding = true;` was set to explicitly opt-in.
   - later: remove the default behavior of decoding, and only decode when opted in.

What do you think @kripken ?

**Comment by kripken** [comment]
I agree, we should probably deprecate this. Most projects seem to not use it.

But we should ask on the mailing list too, to get a clearer picture - maybe a bunch of people are using it that we don't know about.

A related question is whether we should keep the option to use the browser's async codecs to decode images. It seems few projects use that, as well - they ship libpng etc. in their codebases. But, it is a nice feature to use the browser codecs, just annoying it's async. If we still want this feature, we should perhaps add it as an option to the file packager (preloaded assets are loaded async anyhow, so this fits in well there).

**Comment by juj** [comment]
I think I would like to keep the browser decoding feature, but I'd like to make it a specific HTML5 API, along with both paths for synchronous in-browser asset decoding (when --proxy-to-worker + SAB is present), and an asynchronous callback-based asset decoding. With SAB it would even be possible to create a "wait for completion" type of api. I think in general it would be preferable to get `library_browser.js` slimmer, and have the functionality live a library that is explicitly opt-in.

Posted https://groups.google.com/forum/#!topic/emscripten-discuss/i_46X1oQdG8 to raise awareness about the change.

**Comment by kripken** [comment]
Sounds like no objections, so I'll get started on the first part, of making this off by default, but available as a file packager option.

By "a specific HTML5 API" I assume you mean in the `html5.h` file? Sounds good as a followup. It will already be possible through JS though by calling the API directly (`createPreloadedFile` etc.)

**Comment by kripken** [comment]
Inplemented in that pull.
