### ISSUE TITLE
Passing SIMD output by reference fails asm.js validation.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3787]
STR: Build the following file `a.cpp`

    #include <xmmintrin.h>

    void __attribute__((noinline)) foo(__m128 vec, __m128 &outLength)
    {
        outLength = vec;
    }

    int main()
    {
        __m128 x;
        foo(_mm_set1_ps(1.f), x);
    }

with `em++ a.cpp -o a.html -O1 -g2`.

Observed: The generated output contains the following function

    function __Z3fooDv4_fRS_($vec,$outLength) {
     $vec = SIMD_Float32x4_check($vec);
     $outLength = $outLength|0;
     var $outLength = 0, label = 0, sp = 0;
     sp = STACKTOP;
     $outLength = $outLength;SIMD_Float32x4_store(HEAPU8, $outLength, $vec);
     return;
    }

and running the code gives the following error

    TypeError: asm.js type error: local variable names must not restate argument names

**Comment by kripken** [comment]
Potentially fixed in https://github.com/kripken/emscripten-fastcomp/pull/119

**Comment by juj** [comment]
Looks great, thanks for hopping on to this bug so quickly!

**Comment by kripken** [comment]
Fixed by that pull, however, we should add this test to the suite, so leaving open.

**Comment by kripken** [comment]
Actually that pull didn't fix it completely, but I resolved that in a followup. Added test too.
