### ISSUE TITLE
Are there nightly Windows builds of Emscripten 'incoming'?

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3791]
I was just wondering whether, apart from the official Emscripten SDK releases, there are nightly builds of the incoming branch of fastcomp (and fastcomp-clang) for people not able to build it themselves.

**Comment by juj** [comment]
Sorry, we are not currently hosting binary nightly builds. It is a nice idea and something that we could consider adding in the future, but right now we don't have such an infrastructure in place.

**Comment by httpdigest** [comment]
Okay, thanks for the info!
