### ISSUE TITLE
--separate-asm and -s PRECISE_F32=2 are not compatible.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3797]
It looks like when `--separate-asm` and `-s PRECISE_F32=2` are specified and running on a browser without `Math.fround()` support, the `Math.fround()` calls are not correctly optimized out, but the regex to replace `Math.fround()` is performed on the `.js` file, instead of the `.asm.js` file that contains the asm.js module.

**Comment by kripken** [comment]
Thanks for noticing this. I'm fixing this by requiring `--separate-asm` for client code mods like `PRECISE_F32`; supporting two code paths is too complex, and also with the asm separated out, code mods become a lot simpler. This is also more future proof as wasm will be separate, and in general we should move to separate asm by default eventually.

**Comment by kripken** [comment]
Fixed.
