### ISSUE TITLE
MEMFS exception originating from FS.createDefaultDirectories ?

### ISSUE THREAD

**Issue by aardappel** [kripken/emscripten#3799]
Trying to get an SDL2 based project to work, and it throws an exception from the MEMFS implementation:

```
lookup:function (parent, name) {
          throw FS.genericErrors[ERRNO_CODES.ENOENT];
        }
```
This comes from `FS.createDefaultDirectories` trying to create a tmp dir, called from `FS.staticInit`.

I have files preloaded through a .data file, which I am guessing may have to do with this, but I'm not sure how :)

This is on Windows, with 34.1 (tried to update to 34.9, but that fails finding the right toolchain in some VS compilation step, may investigate later). Also running -O1 since that's the only level at which emcc doesn't give up with `AssertionError: Failed to run llvm optimizations:`.
Running from `emrun` with both firefox and chrome gives the same results.
Flags: -s USE_SDL=2 -s DISABLE_EXCEPTION_CATCHING=0 -s DEMANGLE_SUPPORT=1

**Comment by kripken** [comment]
I'm not aware of any open bugs related to those issues, so not sure what could be going wrong there. Can you provide steps to reproduce the problem, either the entire project or a reduced testcase?

**Comment by aardappel** [comment]
Just added a commit to make testing easier, so you should be able to:
```
git clone https://github.com/aardappel/lobster.git
cd lobster/dev/emscripten
make
emrun lobster.html
```
to reproduce it.

**Comment by kripken** [comment]
On incoming (1.34.9), it doesn't hit a MEMFS issue. Instead it throws a C++ exception when `AddGraphics()::___gl_frame::s_gl_frame()` calls `SDLFrame(vec<int, 2>&)`.

`-O2` builds ok, I think that might have been a bug we fixed since `1.34.1`.

**Comment by aardappel** [comment]
The C++ exception is intentional, that's what it uses to suspend the VM at the end of a frame, to get around the main-loop limitation. Does it actually render anything after that exception? It should show an animated tree.

Ok, I will try again with a newer version. Is there a full binary package (for Windows)? I tried with emsdk, but it fails not finding the VS v14 toolchain (even though I have VS2015 installed).

**Comment by kripken** [comment]
No, an uncaught exception makes it terminate. Do you just want to stop execution from continuing, and to only have the main loop run? Then you can call `emscripten_set_main_loop` with 1 in the last parameter.

Or, to just unwind the call stack, but not terminate the application, you can do `emscripten_exit_with_live_runtime`.

**Comment by aardappel** [comment]
That exception was not meant to be uncaught (const char * not caught at std::string) :)
Anyway, managed to upgrade to 1.34.9, now running into a different issue, so I'll open a different issue for that...

**Comment by chenzx** [comment]
I have the same problem in recent 3.1.10, it's normal when running without chrome devtools's source debugger enabled, but it hits when enable "Pause when exception".

since it doesn't disturb normal running, i want a switch or something to get rid of this...

**Comment by sbc100** [comment]
@chenzx .. did you always see this behaviour or is this something new / a regression?

Can you provide the steps you used to reproduce?   Or a an example of the failure?

Is your exception also coming from `createDefaultDirectories`?  If not can you provide a full backtrace?

**Comment by chenzx** [comment]
@sbc100 yes, it always. seems it's the problem of emcc, i'll provide a exception stack trace here: (only occurs when in debugger, no problem in normal run)

```
                lookup: function(parent, name) {
 >                   throw FS.genericErrors[44]
                },
                
            lookup: (parent,name)=>{
>                return parent.node_ops.lookup(parent, name)
            }

            lookupNode: (parent,name)=>{
                var errCode = FS.mayLookup(parent);
                if (errCode) {
                    throw new FS.ErrnoError(errCode,parent)
                }
                var hash = FS.hashName(parent.id, name);
                for (var node = FS.nameTable[hash]; node; node = node.name_next) {
                    var nodeName = node.name;
                    if (node.parent.id === parent.id && nodeName === name) {
                        return node
                    }
                }
 >               return FS.lookup(parent, name)
            }

            mayCreate: (dir,name)=>{
                try {
>                    var node = FS.lookupNode(dir, name);
                    return 20
                } catch (e) {}
                return FS.nodePermissions(dir, "wx")
            }
            
            mknod: (path,mode,dev)=>{
                var lookup = FS.lookupPath(path, {
                    parent: true
                });
                var parent = lookup.node;
                var name = PATH.basename(path);
                if (!name || name === "." || name === "..") {
                    throw new FS.ErrnoError(28)
                }
>                var errCode = FS.mayCreate(parent, name);

            mkdir: (path,mode)=>{
                mode = mode !== undefined ? mode : 511;
                mode &= 511 | 512;
                mode |= 16384;
 >               return FS.mknod(path, mode, 0)
            }

            createDefaultDirectories: ()=>{
>                FS.mkdir("/tmp");
                FS.mkdir("/home");
                FS.mkdir("/home/web_user")
            }
            
            ...
```

**Comment by chenzx** [comment]
I'm using emcc `-lworkerfs.js --preload-file xxx` linker flags, but emscripten's documentation says memfs is defaultly enabled, so i guess workerfs.js has something conflicted with memfs.

But why this `throw FS.genericErrors` behavior doesn't affect normal page run...

**Comment by sbc100** [comment]
Does it happen without `-lworkerfs.js` too?  

Is the exception being handling within emscripten?  Or is it making out the outside world?

**Comment by sbc100** [comment]
If its just happening within emscripten code and being caught locally then maybe its just expected... I'm not familiar enough with the JS ecosystem to know if exceptions that are thrown and caught within a given library are considered by form?  I guess devtools has an option to break on such internal exceptions?

**Comment by chenzx** [comment]
@sbc100 yes, i guess so.

I think this may be the chrome devtools debugger's design fault: i want to catch the first `useful` exception, but it catches the first exception which is expected in js library and will be catched...

**Comment by sbc100** [comment]
Actually looking at `library_workerfs.js` I'm not sure it gets much usage so it could well have bugs.

Are you using it with `--proxy-to-worker` or just starting your app inside a worker?     What is your use case for the filesystem?

**Comment by chenzx** [comment]
@sbc100 mainly for build a UI design system (like Figma) with an internal legacy C++ 2d ui render engine.
source code does font rendering which depends on fontconfig/skia/freetype/harfbuzz、loading custom .ttf font file、& also loading local file path image files dynamically...

**Comment by sbc100** [comment]
But just so I understand you are somehow running your code in a worker rather than on the main thread, right?  (Otherwise I don't think `library_workerfs.js` works, right?).

**Comment by chenzx** [comment]
@sbc100 yes

i thought memfs's throw catch code should be removed, it's not convenient for debugger
