### ISSUE TITLE
Specify exported functions as simple text file

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3801]
Is there a possibility to specify the list of exported functions as a simple one-line-per-function text file when invoking emcc?
This would be extremely helpful, since most of the functions in my program are loaded indirectly/dynamically and have no static callsite in the code. Now what happens is that most of the code is erased from the final minified JavaScript/asm.js file.
To avoid that, I now have to specify 998 functions as exported functions via the command line, which I build by parsing all .java files for "native" method declarations and create a corresponding exported functions entry in the list.

So, is there a way to maybe build that list into a text file and use that with EXPORTED_FUNCTIONS?
Or would you probably propose a different solution?

**Comment by httpdigest** [comment]
I could maybe also post-process the JamVM code, which does the indirect/dynamic invocation based on the name (as a char*) and the method parameter descriptor, by associating these method signatures with integers and storing that association in a JavaScript array.
Then, I could insert a huge switch-case statement with all the dynamically invoked functions to make them static callsites.

**Comment by kripken** [comment]
You can use a response file, `-s EXPORTED_FUNCTIONS=@file.txt`, then that file should contain the usual contents, e.g. `["_main","_other_function"]`.

You can also just disable dead code elimination, `-s LINKABLE=1`.

**Comment by httpdigest** [comment]
Okay, thanks for mentioning those possibilities!
