### ISSUE TITLE
Passing a parameter pack to EM_ASM_INT

### ISSUE THREAD

**Issue by jjrv** [kripken/emscripten#3804]
If I call `EM_ASM_INT` like:

```c++
template <typename... Args>
int call(Args... args) {
    return(EM_ASM_INT(
        {
            return(foobar.apply(this, arguments));
        },
        args...
    ));
}
```

The generated asm.js code seems to correctly call `_emscripten_asm_const_1` or `_emscripten_asm_const_2` etc. However, some of those functions don't exist. Would it be possible to automatically generate every `_emscripten_asm_const_n` that gets called in the generated code?

Background: I need this for Embind-style handling of callbacks. `args...` will be replaced by something like `BindingType<Args>::toWireType(args)...` so that for example an std::string is readable by `foobar`. Then any JavaScript function can be passed to C++ and turned into a functor with a `call` method somewhat like the example above. C++ can then call an arbitrary number of JavaScript functions without any constant `RESERVED_FUNCTION_POINTERS` limit (foobar on JavaScript side will convert the arguments to JavaScript types and call the correct function). Every single C++ -> JavaScript call would pass through that same EM_ASM block.

**Comment by jjrv** [comment]
It seems the code that generates the calls used to also update a list of all existing arities [in master](https://github.com/kripken/emscripten-fastcomp/blob/dccd6517fcc00126e4e74d77c5a8fa06efd3a2ad/lib/Target/JSBackend/CallHandlers.h#L540-L541) but no longer [in incoming](https://github.com/kripken/emscripten-fastcomp/blob/27141a113bf220e352ba84e3e17f24e25190dd9b/lib/Target/JSBackend/CallHandlers.h#L554)

**Comment by jjrv** [comment]
It seems the code that generates the calls used to also update a list of all existing arities [in master](https://github.com/kripken/emscripten-fastcomp/blob/dccd6517fcc00126e4e74d77c5a8fa06efd3a2ad/lib/Target/JSBackend/CallHandlers.h#L540-L541) but no longer [in incoming](https://github.com/kripken/emscripten-fastcomp/blob/27141a113bf220e352ba84e3e17f24e25190dd9b/lib/Target/JSBackend/CallHandlers.h#L554). Instead, it [tracks a single arity per EM_ASM block](https://github.com/kripken/emscripten-fastcomp/blob/27141a113bf220e352ba84e3e17f24e25190dd9b/lib/Target/JSBackend/JSBackend.cpp#L443).

A quick fix might be to support several different arities for each EM_ASM block.

**Comment by jjrv** [comment]
PR sent implementing option B.
Test with: `./runner.py ALL.test_em_asm_parameter_pack`

**Comment by kripken** [comment]
I'm not sure what is going wrong here - is that code sample a testcase that shows the problem? What does

> However, some of those functions don't exist. 

refer to - are "those functions" functions needed, causing the testcase to fail? Or are they needed for the advanced embind use case?

**Comment by jjrv** [comment]
That code is a test case showing the problem. The PR has a test case added in [core_test.py](https://github.com/jjrv/emscripten/blob/024e4db9d4438faee83528664a39cfec6c02b57d/tests/test_core.py#L2158-L2180). Without the patch, it calls `_emscripten_asm_const_1`, `_emscripten_asm_const_2` and `_emscripten_asm_const_3` but only the first of the three actually gets generated.

**Comment by kripken** [comment]
I see, thanks!

Reviewing the pulls now.

**Comment by kripken** [comment]
Fixed by those pulls.
