### ISSUE TITLE
null function pointer in virtual method call called from emscripten_set_main_loop

### ISSUE THREAD

**Issue by aardappel** [kripken/emscripten#3808]
I call (in main()):
```
emscripten_set_main_loop(one_frame_callback, 0, false);
return 0;  // return from main()
```
At this point, a global variable `g_vm` which is a pointer to an object with a virtual table, is still alive. When I enter `one_frame_callback`, I can verify is indeed still a valid pointer also. However, then I call a virtual method (`virtual void OneMoreFrame()`) on it, at which point I get:
```
Invalid function pointer '0' called with signature 'vi'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
This pointer might make sense in another type signature: v: 0  vid: 0  vii: 0  vidi: 0  vidd: 0  viid: 0  viii: 0  viddd: 0  viiid: 0  viiii: 0  viiiii: 0  viddid: 0  vidddd: 0  viiiiii: 0  viiiiiii: 0  viiiiiiii: 0  viiiiiiiii: 0  viiiiiiiiii: 0  viiiiiiiiiii: 0  viiiiiiiiiiiiiii: 0  i: 0  vdi: 0  vd: 0  ii: 0  di: 0  iid: 0  iii: 0  dii: 0  vdd: 0  dd: 0  iiii: 0  diii: 0  ddd: 0  diddi: 0  vdddd: 0  iiiii: 0  iiiiii: 0  iiiiid: 0  iiiiiid: 0  iiiiiii: 0  vdddddd: 0  iiiiiiii: 0  iiiiidii: 0  iiiiiiiii: 0  iiiiiiiiii: 0  iiiiiiiiiiii: 0  iiiiiiiiiiiiii: 0
```
I am aware of the issues around function pointer casting, but I'm not doing that here. The signature `vi` appears correct for a void method with a this parameter? `g_vm` is not null, but apparently the function pointer retrieved from the virtual table is null?

To reproduce:
```
git clone https://github.com/aardappel/lobster.git
cd lobster/dev/emscripten
make
emrun lobster.html
```

**Comment by kripken** [comment]
It looks like the object is being destroyed, I see a call to `lobster::VMBase::~VMBase()`, in `lobster::VM::VM(char const*, unsigned char const*)`. Looks like right before a C++ exception is resumed.

Specifically I see
````
make VMBase 0x549890
create VM 0x549890
destroy VMBase 0x549890
````

That call to the destructor modifies the virtual table, causing the later error, so the question is why it happens. I'm not an expert on C++ exception semantics, so I'm not sure what's going wrong here. In particular I am a little puzzled why I see the VMBase destroyed but not the VM.

**Comment by kripken** [comment]
Oh, it looks like the VM constructor fails. Specifically during the call to `EvalProgram()` right at the end.

So basically the VM constructor fails, and it then calls the destructor on its base class, so that part makes sense. The question is then why that `EvalProgram()` is throwing.

**Comment by aardappel** [comment]
Doh.. silly me. Sorry for bothering you to debug that :(

**Comment by Division** [comment]
I trapped into the same

```
int main(int argc, char *argv[]){
  Game game;

  Engine *engine = getEngine();
  engine->loop(game);

  return 0;
}
```

As I understand game is being destroying when emscripten loop is used.

> Game *game = new Game();
Fixes the issue

**Comment by kripken** [comment]
To prevent `main()` from exiting, see the `simulate_infinite_loop` parameter to `emscripten_set_main_loop`.

**Comment by Division** [comment]
That's better, thank you!
