### ISSUE TITLE
test_pthread_malloc.cpp behaves strangely

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3812]
When I use the very latest Emscripten incoming branch (fa3f95e8), fastcomp (972d28a6) and fastcomp-clang (f0a70828) and the very latest Firefox Nightly Windows 7 x64 (44.0a1 (2015-09-23)), I get the following effect when running the `test_pthread_malloc.cpp` test from Emscripten's tests/pthread directory.

First, Firefox hangs indefinitely without showing anything from the site, until after about ten seconds it shows *"A web page is causing Nightly to run slowly. What would you like to do?"*

When I then choose "Debug Script", it suddenly shows the loaded page for the first time and in the console the following was instantly printed:

```
Successfully compiled asm.js code (loaded from cache in 231ms) test.js
Preallocating 1 workers for a pthread spawn pool. test.html:1233:13
: Successfully compiled asm.js code (loaded from cache in 71ms) test.js
: Successfully compiled asm.js code (loaded from cache in 65ms) test.js
: Successfully compiled asm.js code (loaded from cache in 61ms) test.js
Thread 5337144: Worker with task number 0 finished. test.html:1233:13
Thread 5337144: Memory corrupted! mem[i]: 0, i: 0, n: 0 test.html:1245:13

: Successfully compiled asm.js code (loaded from cache in 69ms) test.js
Thread 5585184: Worker with task number 18 finished. test.html:1233:13
Thread 5585184: Memory corrupted! mem[i]: 0, i: 0, n: 18 test.html:1245:13

Thread 5833224: Worker with task number 36 finished. test.html:1233:13
Thread 5833224: Memory corrupted! mem[i]: 0, i: 0, n: 36 test.html:1245:13

: Successfully compiled asm.js code (loaded from cache in 69ms) test.js
: Successfully compiled asm.js code (loaded from cache in 70ms) test.js
Thread 5502504: Worker with task number 12 finished. test.html:1233:13
: Successfully compiled asm.js code (loaded from cache in 75ms) test.js
Thread 5502504: Memory corrupted! mem[i]: 0, i: 0, n: 12 test.html:1245:13

Thread 5915904: Worker with task number 42 finished. test.html:1233:13
Thread 5915904: Memory corrupted! mem[i]: 0, i: 0, n: 42 test.html:1245:13

Thread 5419824: Worker with task number 6 finished. test.html:1233:13
: Successfully compiled asm.js code (loaded from cache in 74ms) test.js
Thread 5419824: Memory corrupted! mem[i]: 0, i: 0, n: 6 test.html:1245:13

Thread 5667864: Worker with task number 24 finished. test.html:1233:13
Thread 5667864: Memory corrupted! mem[i]: 0, i: 0, n: 24 test.html:1245:13

Thread 5750544: Worker with task number 30 finished. test.html:1233:13
Thread 5750544: Memory corrupted! mem[i]: 0, i: 0, n: 30 test.html:1245:13
```

I only used the `-s USE_PTHREADS=1` flag when building the example. Also, this occurs in any optimization levels from O1 through O3.
Should I preallocate the worker threads using a compiler argument? And which one was it, I forgot?
And what is this "Memory corrupted!", that does not sound good. :)

Thanks!
Kai

**Comment by kripken** [comment]
In the test suite, that file is run here:

https://github.com/kripken/emscripten/blob/incoming/tests/test_browser.py#L2650

Options look like `-O3 -s USE_PTHREADS=2 --separate-asm -s PTHREAD_POOL_SIZE=8`.

The test passes over here (`./tests/runner.py browser.test_aaa_pthread_malloc`), does it not work for you? Those corruption errors look very strange and worrying.

**Comment by httpdigest** [comment]
Ah, that `PTHREAD_POOL_SIZE` was it. I built with that option and now, Firefox Nightly shows the page and sysout's the following:

```
Preallocating 8 workers for a pthread spawn pool.
Test finished with result 0
```

The browser console is showing this:
```
Successfully compiled asm.js code (loaded from cache in 8ms) test.js
Preallocating 8 workers for a pthread spawn pool. test.html:1233:13
: Successfully compiled asm.js code (loaded from cache in 6ms) test.js
: Successfully compiled asm.js code (loaded from cache in 17ms) test.js
: Successfully compiled asm.js code (loaded from cache in 13ms) test.js
: Successfully compiled asm.js code (loaded from cache in 11ms) test.js
: Successfully compiled asm.js code (loaded from cache in 10ms) test.js
: Successfully compiled asm.js code (loaded from cache in 11ms) test.js
: Successfully compiled asm.js code (loaded from cache in 12ms) test.js
Test finished with result 0
```

I guess that PTHREAD_POOL_SIZE option did the trick.

**Comment by httpdigest** [comment]
Okay, thanks! I guess that flag solved it.

**Comment by kripken** [comment]
@juj, is it surprising to get those errors without that flag? seems puzzling to me.

**Comment by juj** [comment]
Yes, because the main thread synchronously spawns a thread with `pthread_create` and then immediately joins on it with `pthread_join` at https://github.com/kripken/emscripten/blob/incoming/tests/pthread/test_pthread_malloc.cpp#L52 without yielding to the browser (for a long period of time) in between, one needs to prime a preloaded pool of workers with `PTHREAD_POOL_SIZE`.

Note that I've been pondering about a way to heuristically detect this, with a certain timeout threshold: we can kind of assume that if `pthread_join` is waiting for a thread to join that has not even started yet, and join takes more than a fixed k seconds (10 seconds or more perhaps), we could make a call that most likely the thread is unable to start, and `abort()` with a more clear error. Eventually the `--proxy-to-worker` arch will resolve this however.
