### ISSUE TITLE
Parallel test runner ignores embuilder errors

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3820]
http://clb.demon.fi:8112/builders/osx-incoming/builds/1094/steps/default%20suite/logs/stdio

Looks like the os x bot is failing to build the native optimizer. Perhaps we should assert on embuilder success in the parallel test runner, however I guess we should only do it after we figure out what's going wrong on that bot.

**Comment by juj** [comment]
This occurs because the method that builds native optimizer does not build it when a prebuilt native optimizer is already present. Fixed in the above commit by making `embuilder.py build ALL` not attempt to build native-optimizer if user has specified a prebuilt one.
