### ISSUE TITLE
Possible Chrome browser performance regression on Urho3D physics stress test sample between 1.29.0 and current incoming (1.34.10)

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3825]
Debugging through Urho 3D physics stress test sample performance on Chrome:
   - 1.29.0 without memory growth: fast
   - 1.29.0 with memory growth: fast
   - incoming without memory growth: fast
   - incoming with memory growth: slow

Which makes is look like at some point we lost Chrome performance when memory growth is enabled. This may be related to #3684.

**Comment by kripken** [comment]
I would guess the issue is that we used to disable "use asm" in memory growth, because it was not part of the asm.js spec. But now it is in the spec, and at least two browsers support it.

In February, Chrome said mitigations for the issue are coming in ["weeks or months"](https://code.google.com/p/v8/issues/detail?id=3907#c13), but I don't see any updates since then.

Anyhow, assuming this is the issue, building with `-s ASM_JS=2` is a workaround. But it makes other browsers slower because of Chrome, which is sad.

**Comment by dahliaT** [comment]
Here are some builds which illustrate the issue.

http://di01.wwweb3d.net/emscripten_test.tgz

You can also try them at http://di01.wwweb3d.net/emscripten_test/  if you don't want to download the builds.

**Comment by kripken** [comment]
Looks like the builds confirm the theory from my last comment: Chrome always runs Turbofan on `"use asm"`, even when it can't properly optimize the code, which is the case with memory growth.

**Comment by evanw** [comment]
Thanks for figuring this out! We've been stuck on 1.29.0 for a really long time because of this issue and I could never get to the bottom of it. This fix means we can just have a server-side special case for Chrome to send it the code without "use asm" and get the best of both worlds.

**Comment by cosinusoidally** [comment]
> I would guess the issue is that we used to disable "use asm" in memory growth, because it was not part of the asm.js spec. But now it is in the spec, and at least two browsers support it.

I can't seem to find any reference to memory growth in http://asmjs.org/spec/latest/ . Is that still the official specification document?

**Comment by kripken** [comment]
It is, but the spec is out of date, and given the momentum on WebAssembly, the people involved in writing it are focused on that instead. But the details of memory growth in asm.js are [here](http://discourse.wicg.io/t/request-for-comments-switching-resizing-heaps-in-asm-js/641).

**Comment by warrenseine** [comment]
I can confirm that the workaround @evanw suggests works fine here too. Not ideal in my case, but I can live with it.

**Comment by juj** [comment]
Looks like this can be closed. Since then, memory growth got killed in asm.js so looking at WebAssembly as the next point to restore that support.
