### ISSUE TITLE
Error building optimizer on windows

### ISSUE THREAD

**Issue by louarr** [kripken/emscripten#3826]
Error message:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140
') cannot be found. To build using the v140 build tools, please install v140 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "U
pgrade Solution...". [C:\Program Files\Emscripten\emscripten\tag-1.34.11_64bit_
optimizer\ZERO_CHECK.vcxproj]

I have both v140 and v120 toolsets. I don't understand why it is using v120 toolset "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\" but looks for v140?

**Comment by juj** [comment]
I believe this is a bug on CMake attempting a VS2015 build, but then running a VS2013 msbuild.

**Comment by louarr** [comment]
Maybe you're right, I checked the generated project files and even though they were for vs2013 they specified the platform toolset as v140 in the configuration.

**Comment by louarr** [comment]
This problem did not occur on my other computer with  vs2010,vs2012, and  vs2013 installed. I guess vs2015 screws up cmake.
