### ISSUE TITLE
-s PRECISE_F32=2 workflow inconvenience.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3829]
I notice that it is no longer possible to specify `-s PRECISE_F32=2`, but that will error out with the message

    AssertionError: options that modify code on the client, like PRECISE_F32 == 2, require --separate-asm

This for example breaks Unity3D build system, which now needs to be changed to add the new `--separate-asm` flag. Was this a deliberate change to not allow plain `-s PRECISE_F32=2` anymore?

**Comment by kripken** [comment]
1. Yes, to allow easier refactoring of the client mods code, I made it depend on separate asm. With separate asm, its easier to write such code mods, since they can directly operate on just the asm, and not have to parse it out.
2. But in any case Unity should not be using this option - we measured and they confirmed that it is slower on Chrome.

**Comment by juj** [comment]
Hmm, right, but they are using `-s USE_PTHREADS=2` flag, which seems to have the same behavior. This is a bit inconvenient, since now neither of those flags are allowed to be passed alone. Is there any advantage of requiring two build flags? Couldn't we make `-s USE_PTHREADS=2` and `-s PRECISE_F32=2` imply `--separate-asm` to keep compatibility, since in the current form, neither of those flags have any function if passed alone, and they just result in breaking builds?

This is particularly annoying, since in Emscripten before this change, `-s USE_PTHREADS=2 --separate-asm` fails because `--separate-asm` option is not recognized, and in Emscripten after this change, `-s USE_PTHREADS=2` fails because `--separate-asm` is not present, so there is no set of flags that would have compatibility across versions, but all projects that depend on either `-s USE_PTHREADS=2` or `-s PRECISE_F32=2` must configure their build systems specifically to tune whether the compiler is newer or older than https://github.com/kripken/emscripten/commit/56db50d0bc0239ce7786dcc7326577e5e65e6f79 . This makes it difficult to share the project build configuration between developers who might have different Emscripten versions, or when bisecting a project.

**Comment by kripken** [comment]
I'm ok with those turning on `--separate-asm`. Perhaps it should warn when doing so, I'm ok either way. I suppose it isn't that confusing to have a separate asm file by surprise, people will just see that the project fails if it isn't copied along.

**Comment by juj** [comment]
This was resolved in above.
