### ISSUE TITLE
Gzip and Lazy Filesystem

### ISSUE THREAD

**Issue by fzimmermann89** [kripken/emscripten#3837]
Hi,

I'm not sure whether this issue as been discussed before, I didn't find it using the github search:

Problem: 
Lazy loaded files which are served by the webserver using gzip are truncated.

Reason: 
https://github.com/kripken/emscripten/blob/master/src/library_fs.js#L1577
content-length is the compressed length, not the data length

Suggested Fix:
-check if gzip is used in this line.
-if not, continue as right know
-if it is use, download the whole file and get the true length

Sideeffect:
Getting the length of a compressed file will cause the download. BUT: It is better to download the file than to report a WRONG lenght.

Are there any opinions on this issue?

Fixing this issue would make manuels.github.io/texlive.js/ (which is listed as an example of using emscripten) work again. Right know it fails because github is compressing .map files which causes the bug to truncate it and pdftex will complain about missing fonts..

-Felix

**Comment by kripken** [comment]
Perhaps instead of downloading the whole file, it could throw an error, saying that gzip compression is not compatible with lazy-loaded files? Might be better for people to just not use a lazy-loaded file if they serve it compressed. I don't feel strongly about this though.

**Comment by fzimmermann89** [comment]
My goal is to not have it fail - after reconsidering it might be the best
solution to have it in three stages:
If uncompressed continue as right know
If compressed, look for an additional header telling the uncompressed
length (if the user has the ability to add one), else diwnload the whole
file.

The description of lazyloading doesn't imply that it has to use chunks.
Throwing an exception would mean that certain files cannot be lazx loaded
from github pages, etc. Not using chunks seems to me the "smallest
surprise" for the developer. We might throw a warning - but lazy loading
has more benefits than just junks:
For texlive.js a whole texlive installation is lazy loaded - a lot of
rather small text files. Using gzip is actually better than chunking those
files (and gh pages doesn't allow you to turn gzip off)

-Felix
Am 08.10.2015 01:26 schrieb "Alon Zakai" <notifications@github.com>:

**Comment by kripken** [comment]
Sounds good. We should warn in the console if we are forced to download the whole file.

**Comment by fzimmermann89** [comment]
Warning in the console unfortunately really spams the console in my application, so I didn't add it. Once again, nowhere in the documentation it says lazy loading has to use chunks.

**Comment by fzimmermann89** [comment]
mhm.. Google's datacompression sometimes (I haven't figured out under which conditions yet) removes the length header without adding an x-original-content-length header.
The patch  #3883 doesn't fix this issue. I will continue investigation.
