### ISSUE TITLE
Optimizer breaks a required SIMD store op related to _mm_load_ss(&function_parameter).

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3839]
This is a bit of an odd situation. Compiled with `-O0`, all is well and the output prints `1.000000 0.000000 0.000000 0.000000` as expected, but when `-O1` or higher is applied, the page outputs `0.000000 0.000000 0.000000 0.000000` instead.

	#include <xmmintrin.h>
	#include <stdio.h>

	class vec
	{
	public:
		__m128 v;

		void mul(float s)
		{
			__m128 vs = _mm_load_ss(&s);
			// __m128 vs = _mm_set_ss(s); // _mm_set_ss(s) instead of _mm_load_ss(&s) avoids the problem somehow..?
			v = _mm_mul_ps(v, vs);
		}
	};

	int main()
	{
		vec v;
		v.v = _mm_set_ps(1,2,3,4);
		v.mul(0.25f);

		float f[4];
		_mm_storeu_ps(f, v.v);
		printf("%f %f %f %f\n", f[0], f[1], f[2], f[3]);
	}

Looking at the generated JS code in `-O1`, the function `mul` is miscompiled:

	function __ZN3vec3mulEf($this,$s) {
	 $this = $this|0;
	 $s = +$s;
	 var $0 = 0, $1 = SIMD_Float32x4(0,0,0,0), $2 = SIMD_Float32x4(0,0,0,0), $3 = SIMD_Float32x4(0,0,0,0), label = 0, sp = 0, temp_Float32x4_ptr = 0;
	 sp = STACKTOP;
	 STACKTOP = STACKTOP + 16|0;
	 $0 = sp;
	 $1 = SIMD_Float32x4_load1(HEAPU8, $0);  // (*)
	 $2 = SIMD_Float32x4_load(HEAPU8, $this);
	 $3 = SIMD_Float32x4_mul($1,$2);
	 temp_Float32x4_ptr = $this;SIMD_Float32x4_store(HEAPU8, temp_Float32x4_ptr, $3);
	 STACKTOP = sp;return;
	}

The code line (*) is attempting to load the input scalar `$s` to a SIMD register for multiplication, however the code line that would store `$s` to address `$0` is missing altogether. In `-O0`, the store is correctly present:

    function __ZN3vec3mulEf($this,$s) {
      ...
      HEAPF32[$1>>2] = $s;
      $3 = (SIMD_Float32x4_check(__ZL11_mm_load_ssPKf($1)));
      ...

What could cause `-O1` go and wipe the store out?

**Comment by juj** [comment]
Hmm, perhaps the problem is that our call handlers for partial loads at https://github.com/kripken/emscripten-fastcomp/blob/incoming/lib/Target/JSBackend/CallHandlers.h#L529 somehow don't tell LLVM that they are loads from memory? And as a result since LLVM doesn't know it's a load, it's looking at the preceding stores to that address as being redundant (since they are stores to local stack area and not to global memory)? @sunfishcode : Should we need to teach LLVM somehow that our load handlers are actually loading from memory? (And I guess the same for stores? We should tell LLVM that our stores are touching memory?)

**Comment by kripken** [comment]
The attribute `__const__` is just wrong on those loads. They dereference the pointer, which means they are not `__const__` (`readnone` in LLVM IR). I'll push a fix.

**Comment by kripken** [comment]
Btw, I can't find actual documentation for `__const__` in clang. Closest is for `__const__` in other compilers. But [langref](http://llvm.org/docs/LangRef.html#function-attributes) says that `readnone` which it is lowered to is identical to the other compilers.

**Comment by kripken** [comment]
@sunfishcode informs me that the gcc docs are authoritative here, so this is settled.

**Comment by kripken** [comment]
Pushed fix after talking to @sunfishcode

**Comment by juj** [comment]
Thanks! This was the last one, I can confirm we're now all green on SIMDized Bullet! :) Great job here!

**Comment by kripken** [comment]
Great!

How do we measure perf, though? It won't validate due to float64x2.

**Comment by juj** [comment]
I posted this pull request to Bullet to address the SIMD.js port: https://github.com/bulletphysics/bullet3/pull/485
