### ISSUE TITLE
default to NODEFS

### ISSUE THREAD

**Issue by nickdesaulniers** [kripken/emscripten#3843]
When compiling command line utilities that use fopen, I currently need to add:

```c
#ifdef __EMSCRIPTEN__
#include "emscripten.h"
EM_ASM(
 FS.mount(NODEFS, { root: '.' }, '/working');
)
#endif
```

Before calling fopen.  If I'm compiling to JS without specifying that the -o file should be html file suffixed, could emscripten assume I'll only being using Node, and by default insert the FS.mount for me? Or, is that not a safe assumption to make?

**Comment by kripken** [comment]
I think it's not a safe assumption to make:

1. The code might still be run in a web browser, a person could just include it in a script tag.
2. The code might be run in another JS shell.
3. Making it magically just use NODEFS in node would be surprising in some cases, as people expect emscripten's default is to use the emulated filesystem, across all target platforms. For example, they might assume that compiled emscripten code should only use the files that they preload or embed, which is true everywhere else.
