### ISSUE TITLE
WebSocket creation in worker environment

### ISSUE THREAD

**Issue by PKarics** [kripken/emscripten#3849]
We are trying to create websocket as worker, but we can't because the generated code contains this code part (library_sockfs.js:214  version: 1.30.0):

    var WebSocket = ENVIRONMENT_IS_NODE ? require('ws') : window['WebSocket'];

The windows is not accessible in worker environment. 

I solved the problem on this way:

    if(ENVIRONMENT_IS_WORKER)
    {
     ws = new WebSocket(url, opts);
     ws.binaryType = 'arraybuffer';
    }
    else
    {
     var WebSocket2 = ENVIRONMENT_IS_NODE ? require('ws') : window['WebSocket'];
     ws = new WebSocket2(url, opts);
     ws.binaryType = 'arraybuffer';
    }

**Comment by kripken** [comment]
Thanks! Do you perhaps want to open a pull request with that?

**Comment by kripken** [comment]
Fix pushed to incoming.
