### ISSUE TITLE
Error when trying to run optimizations greater than -O1

### ISSUE THREAD

**Issue by Filiecs** [kripken/emscripten#3853]
I am using Emscripten to compile a large project and it works on optimization level O1 and lower, but after that I get an error that I can't seem to figure out.
I compile using these options:
__em++ main.cpp project.cpp -o index.html -std=c++11 -s DEMANGLE_SUPPORT=1 --embed-file Player.z -O2__

>warning: unresolved symbol: _ZN4Zero26cFileSystemCaseInsensitiveE
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\emcc", line 1540, in <module>
    flush_js_optimizer_queue()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\emcc", line 1447, in flush_js_optimizer_queue
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\emcc", line 1420, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\tools\shared.py", line 1578, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\tools\js_optimizer.py", line 519, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\tools\tempfiles.py", line 39, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\tools\js_optimizer.py", line 519, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "C:\Program Files\Emscripten\emscripten\tag-1.34.1\tools\js_optimizer.py", line 434, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
WindowsError: [Error 2] The system cannot find the file specified

When I compile without optimizations I usually get two warnings:
>warning: unresolved symbol: _ZN4Zero9FileRange10frontEntryEv
warning: unresolved symbol: _ZN4Zero26cFileSystemCaseInsensitiveE

These seem to stem from a FileSystem that the project has (which I am not using), but I am unsure of what the warnings actually mean as they do not seem to affect anything at runtime. I have no idea if the two are connected or not.

**Comment by kripken** [comment]
Building with `EMCC_DEBUG=1` in the env should provide more info.

**Comment by juj** [comment]
This sounds like a broken emsdk installation. How did you install emsdk? I see that you are running off a tagged build compiled from source? What were the install commands you ran, and what was the log output?

**Comment by Filiecs** [comment]
I downloaded the SDK and ran "emsdk update" then "emsdk install latest". This created the .sln for LLVM/Clang but then spit out a fatal error. 

Here is the error:
>-- Build files have been written to: C:/Program Files/Emscripten/emscripten/tag-1.34.12_64bit_optimizer
Performing a parallel build with 7 cores.
Running build: ['C:\\Windows\\Microsoft.NET/Framework/v4.0.30319\\MSBuild.exe', '/t:Build', '/p:Configuration=RelWithDebInfo', '/p:Platform=Win32', '/nologo', '/verbosity:minimal', 'asmjs_optimizer.sln']
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140
') cannot be found. To build using the v140 build tools, please install v140 bu
ild tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "U
pgrade Solution...". [C:\Program Files\Emscripten\emscripten\tag-1.34.12_64bit_
optimizer\ZERO_CHECK.vcxproj]
Build failed due to exception!
Working directory: C:/Program Files/Emscripten/emscripten/tag-1.34.12_64bit_optimizer
Command '['C:\\Windows\\Microsoft.NET/Framework/v4.0.30319\\MSBuild.exe', '/t:Build', '/p:Configuration=RelWithDebInfo', '/p:Platform=Win32', '/nologo', '/verbosity:minimal', 'asmjs_optimizer.sln']' returned non-zero exit status 1
Installation failed!

To get aroung this I opened up the .sln in Visual Studio and compiled from there.
I then ran "emsdk activate latest" and set the variables in .emscripten to their appropriate paths.

Here is a .zip of my emscripten folder.
https://mega.nz/#!cpQEXSjQ!x59Wn3C4oscFCRsNCZgkP5t8H02sOHS99nacTd6VS0I

I was talking to a friend trying to do the same thing I am and he said he ran into the same issue.

**Comment by Filiecs** [comment]
I fixed the issue. In the emsdk file I changed
MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp to
MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp and now it works like a charm.

On Fri, Oct 16, 2015 at 7:39 AM, juj <notifications@github.com> wrote:

> This sounds like a broken emsdk installation. How did you install emsdk? I
> see that you are running off a tagged build compiled from source? What were
> the install commands you ran, and what was the log output?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kripken/emscripten/issues/3853#issuecomment-148734883>
> .
>



-- 
Joshua Biggs, Designer and student at Digipen Institute of Technology.
LinkedIn
<http://www.linkedin.com/profile/view?id=250917970&trk=nav_responsive_tab_profile_pic>

**Comment by juj** [comment]
Oh, thanks, that is this bug https://github.com/juj/emsdk/commit/340543a46a67280c80b88346c167996d763bbbac . The next emsdk version will contain the fix. Good to know that there is a workaround like you mentioned for the current release as well!
