### ISSUE TITLE
Rebase emscripten off of upstream LLVM

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#3856]
Emscripten has been based off of PNaCl since we moved to our fastcomp backend (fastcomp uses PNaCl legalization passes, so it was easiest to do that way). However, PNaCl has not updated for a while now, and I hear they do not have concrete plans to stay close to trunk. We do want to be close to trunk, so after talking with PNaCl people, it seems best for us to just rebase emscripten off of upstream LLVM.

This means we'll need to maintain copies of the PNaCl passes we use, so overall it means more rebasing work for us.

I opened `back-to-llvm` branches on the 3 repos for this. This updates us to the latest revision of the [`google/stable` branches](http://llvm.org/viewvc/llvm-project/llvm/branches/google/stable/) (`stable` and `google/stable` in llvm and clang repos), which is around 2 months ago.

This merge is still a wip but right now it looks almost stable, the main test suite passes. Still more tests and benchmarking to verify first. We'd probably also delay a merge of this for a good time on incoming.

The benefits of being close to upstream LLVM are that

1. We get new LLVM optimizations sooner. (One that I noticed now is that LLVM optimizes stack usage better, so that I had to work on our stack-overflow-detection test because LLVM optimized out the stack there...)
2. Easier to use in conjunction with other LLVM-using projects like rust and [D](https://github.com/kripken/emscripten-fastcomp/issues/114)
3. Access to the wip WebAssembly backend being developed in LLVM, which we'll have as an output option when it's ready.

**Comment by kripken** [comment]
Looks like this merge is done. Tests pass, and benchmarks look quite good: 0.5% code size reduction in several, all showing at least some improvement, and a small speedup in some. zlib actually shows a relatively noticeable speedup of 3%.

@juj, what do you think about timing for landing this on incoming? We just merged to master, so perhaps some time this week?

**Comment by kripken** [comment]
Another option is to merge more from LLVM before merging to incoming, we are still 2 months behind.

**Comment by juj** [comment]
I'm all ok with merging multiple times at a rapid pace earlier rather than later. Since there are "unknown" modifications coming in, it would be good to have an Emscripten tag before and after the merge, so that people bisecting across all three repositories can easily identify if a regression might be caused by the LLVM update.

**Comment by kripken** [comment]
Ok, sounds good. I'll merge this to incoming this week then. I'll add a tag before and after as you suggest, that sounds good.

**Comment by kripken** [comment]
Finished all the tests I can run locally, including fuzzing. All looks good, so merged to incoming.
