### ISSUE TITLE
Emscripten doesn't support passing data by transferring ownership to or from Web Workers 

### ISSUE THREAD

**Issue by KhaledSami** [kripken/emscripten#3857]
According to the link [here] (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects)) it is possible to pass certain types of objects (transferable objects) to or from a web worker with ownership transfer(no copy), this can be done using [post messages] (https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage) but since emscripten's implementation (library_browser.js) doesn’t seem to support this: [here] (https://github.com/kripken/emscripten/blob/master/src/library_browser.js#L1345) and [here] (https://github.com/kripken/emscripten/blob/master/src/library_browser.js#L1335), it is impossible with the current implementation.

I tried to modify the library for one of the functions to test if it would work at all
``` js
emscripten_worker_respond: function(data, size) {
    if (workerResponded) throw 'already responded with final response!';
    workerResponded = true;
    var respondMsg = new Uint8Array({{{ makeHEAPView('U8', 'data', 'data + size') }}}) ; // XXX copy to a new typed array as a workaround for chrome bug 169705
    var objectData = {
      'callbackId': workerCallbackId,
      'finalResponse': true,
      'data': data ? respondMsg : 0 
    };
    postMessage(objectData,[objectData.data.buffer]);
  }
```
I measured the memory consumption with / without the modification (because without transferring the ownership two copies are needed vs one copy needed in case of transfer the ownership)
and it seems to be working.

What is the reason that emscripten does not support this by default?

Thanks.

**Comment by kripken** [comment]
One issue is that you have to make a copy first, then transfer the copy. Otherwise, we could avoid the copy and just call postMessage, which would do the copy. So we don't seem to be able to avoid a copy here anyhow, and letting postMessage do it implicitly might be better optimized by the browser, although that needs to be measured.

However, right now I see our code does have a copy because of [this chrome issue](https://code.google.com/p/chromium/issues/detail?id=169705) which has since been closed. We should test if, as suggested in the comments there, that copy might no longer be necessary. If it still is necessary, then transfer might be better.

**Comment by KhaledSami** [comment]
I tried to remove the extra copy [here](https://github.com/kripken/emscripten/blob/master/src/library_browser.js#L1350) and increase the heap size to be 1 GB then test the performance and the results are
to copy 20 MB in chrome it takes 2400 ms VS  35 ms without removing the copy
to copy 20 MB in firefox it takes 900 ms VS  20 ms without removing the copy

then I tried to do the transfer with the way I explained above and the results are 
to transfer 20 MB in chrome / firefox it takes 15 ms max. 

As per the chromium issue this is the expected behaviour since every browser will copy the underlying buffer of a TypedArray instead of copying the portion associated with the view. This means the manual transfer is the preferred way.

**Comment by kripken** [comment]
Thanks, sounds like we should definitely do the transfer then. Do you want to open a pull request?

**Comment by KhaledSami** [comment]
@kripken sorry for being late, this is the pull request for this issue https://github.com/kripken/emscripten/pull/3910
Would you check it please?

**Comment by kripken** [comment]
Sure, thanks, I'll get to it soon.

**Comment by kripken** [comment]
That pull was merged, closing.
