### ISSUE TITLE
"unresolved symbol: putchar" when linking Google Test with different optimization settings

### ISSUE THREAD

**Issue by warrenseine** [kripken/emscripten#3859]
Here's a shell script to reproduce the issue:

```sh
#!/bin/bash

set -e
set -x

SAMPLE=sample2

mkdir -p /tmp/emscripten-google-test
cd /tmp/emscripten-google-test
test -d googletest || git clone https://github.com/google/googletest
cd googletest/googletest
rm -f *.o *.a *.bc *.html

em++ -o gtest-all.o -c src/gtest-all.cc -Iinclude -I. -I$EMSCRIPTEN/system/lib/libcxxabi/include 
emar rcs libgoogletest.a gtest-all.o
em++ -O3 --llvm-lto 1 -o main.o -c src/gtest_main.cc -Iinclude -I. -I$EMSCRIPTEN/system/lib/libcxxabi/include
em++ -O3 --llvm-lto 1 -o $SAMPLE.o -c samples/$SAMPLE.cc -Iinclude -I. -I$EMSCRIPTEN/system/lib/libcxxabi/include 
em++ -O3 --llvm-lto 1 -o $SAMPLE.bc $SAMPLE.o main.o libgoogletest.a
emcc -O3 --llvm-lto 1 $SAMPLE.bc -o $SAMPLE.html
```

When reducing my test case, I found out what's causing the problem. I'm using different optimization settings for the library and the application. Adding `-O3 --llvm-lto 1` to the compilation of `src/gtest-all.cc` solves the issue.

Still, the error looks completely unrelated, especially considering that `putchar` is nowhere to be seen in the source code of `google-test`.

**Comment by kripken** [comment]
Thanks. Ok, this looks like [an LLVM LTO issue](https://llvm.org/bugs/show_bug.cgi?id=23814). I don't see any response in that issue, so I'm not sure what we can do.

A workaround, if you need one, is to add putchar to `EXPORTED_FUNCTIONS`.

**Comment by kripken** [comment]
The underlying issue here turned out to be the same as #3616, so let's close this.
