### ISSUE TITLE
emscripten_async_wget2_data: POST requests output errors to console in Chrome

### ISSUE THREAD

**Issue by reven86** [kripken/emscripten#3860]
When using emscripten_async_wget2_data with POST requesttype, I see a lot of errors in the output console in Chrome:
```
Refused to set unsafe header "Content-length"
Refused to set unsafe header "Connection"
```
Request, however, is normally processed and response is received. It seems some browsers consider these headers as harmful. I did find some information and it seems that XMLHttpRequest isn't allowed to set these headers, they are being set automatically by the browser.

These headers are set in the library_browser.js, if it's OK to remove them, I can test it and open a pull request.

**Comment by kripken** [comment]
Interesting, where did you read that XHRs aren't allowed to set those?

We might have another place or two where those are used, that needs changing.

**Comment by reven86** [comment]
Here is some explanation of the similar issue that I have: http://stackoverflow.com/questions/2623963/webkit-refused-to-set-unsafe-header-content-length

And a reference to standard (step 5): http://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader%28%29-method

**Comment by kripken** [comment]
I see, thanks. Yes, looks like we are ok to remove those, PR would be great.

**Comment by kripken** [comment]
This was fixed by that pull/
