### ISSUE TITLE
Emscripten can now use Int32Array, not SharedInt32Array

### ISSUE THREAD

**Issue by lars-t-hansen** [kripken/emscripten#3869]
When https://bugzilla.mozilla.org/show_bug.cgi?id=1205390 lands this morning, Odin will start to accept the use of Int32Array etc to create views on shared memory.  It should therefore become possible for emscripten to generate code that does that; the benefit is that such code will also work on other browsers with support for Shared Memory + Atomics.

Existing compiled asm.js code will continue to run, for now, since SharedInt32Array etc continue to be accepted by Odin.

There's a trick that's described in https://bugzilla.mozilla.org/show_bug.cgi?id=1205390#c3 that should allow asm.js code to also run in Firefox with asm.js disabled - should that be desired.  This trick is needed because the rest of SpiderMonkey does not yet allow Int32Array etc to create views on shared memory; that is bug 1176214, which is not close to landing.

Newly compiled asm.js code that uses Int32Array etc to create views on shared memory will not work in older Firefox, however - such code requires the patch, or a hackaround that changes the view names in the source before compilation (ISTR Jukka had something like that working).

**Comment by juj** [comment]
Thanks! I'll start working on a PR that removes the Shared* variants from Emscripten codebase.

**Comment by juj** [comment]
Wrote some code now to patch these out, see #3932. However, at the moment, the following can be observed in FF Nightly web console:

    var b = new SharedArrayBuffer(16*1024*1024);

    var s = new SharedUint32Array(b);
    s.length
    > 4194304

    var h = new Uint32Array(b);
    h.length
    > 0

I believe this is resolved by bug https://bugzilla.mozilla.org/show_bug.cgi?id=1176214, after which the pull request #3932 should be good to land.

**Comment by lars-t-hansen** [comment]
The change that landed previously only changes the reality for true asm.js code, all other JS code must still use SharedInt32Array, etc.  The early landing of that patch was intended to make it possible to change the code generator for emscripten, but all non-asm.js support code (or non-asm.js generated code for that matter) must use the old behavior until 1176214 lands, which will probably be after Thanksgiving given the review backlog on it.

**Comment by kripken** [comment]
Ok, the Firefox patches landed and I landed Jukka's pull.
