### ISSUE TITLE
Build fail when SSE2 is enabled (LLVM ERROR: invalid vector instr)

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#3871]
I get this error when SSE2 is enabled in PhysX 3.3 emscripten port. We are using `-O3` for optimizations, if that matters.

```
  %324 = zext <4 x i1> %323 to <4 x i32>
LLVM ERROR: invalid vector instr
Traceback (most recent call last):
  File "D:\dev\stingray\lib\emscripten-1.34.12-r0\emscripten\tag-1.34.12\emcc", line 1344, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "D:\dev\stingray\lib\emscripten-1.34.12-r0\emscripten\tag-1.34.12\tools\shared.py", line 1526, in emscripten
    call_emscripten(cmdline)
  File "D:\dev\stingray\lib\emscripten-1.34.12-r0\emscripten\tag-1.34.12\emscripten.py", line 1304, in _main
    temp_files.run_and_clean(lambda: main(
  File "D:\dev\stingray\lib\emscripten-1.34.12-r0\emscripten\tag-1.34.12\tools\tempfiles.py", line 64, in run_and_clean
    return func()
  File "D:\dev\stingray\lib\emscripten-1.34.12-r0\emscripten\tag-1.34.12\emscripten.py", line 1310, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "D:\dev\stingray\lib\emscripten-1.34.12-r0\emscripten\tag-1.34.12\emscripten.py", line 1208, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "D:\dev\stingray\lib\emscripten-1.34.12-r0\emscripten\tag-1.34.12\emscripten.py", line 103, in emscript
    end_funcs = backend_output.rindex(end_funcs_marker)
ValueError: substring not found
```

**Comment by kripken** [comment]
Thanks for reporting. This should be fixed in https://github.com/kripken/emscripten-fastcomp/pull/127

**Comment by gouletr** [comment]
Thanks! Looking forward to be able to try this out.

**Comment by kripken** [comment]
Merged that pull to incoming.

**Comment by gouletr** [comment]
I confirm it now successfully completes the build, however Firefox now output the following warnings:
```
TypeError: asm.js type error: all function calls must either be calls to standard lib math functions, standard atomic functions, standard SIMD constructors or operations, ignored (via f(); or comma-expression), coerced to signed (via f()|0), coerced to float (via fround(f())) or coerced to double (via +f())
Warning: Patching up SIMD.Float64x2.equal to return a Bool64x2 instead of Int32x4!
Warning: Patching up SIMD.Float64x2.notEqual to return a Bool64x2 instead of Int32x4!
Warning: Patching up SIMD.Float64x2.greaterThan to return a Bool64x2 instead of Int32x4!
Warning: Patching up SIMD.Float64x2.greaterThanOrEqual to return a Bool64x2 instead of Int32x4!
Warning: Patching up SIMD.Float64x2.lessThan to return a Bool64x2 instead of Int32x4!
Warning: Patching up SIMD.Float64x2.lessThanOrEqual to return a Bool64x2 instead of Int32x4!
```
How bad is this?

**Comment by kripken** [comment]
Any asm.js validation error means all asm.js optimizations are lost. Those look like they are due to Firefox not yet implementing Float64x2 types. I'm not sure what the timeline is for adding those, @sunfishcode would know. Meanwhile, is there a way to avoid them in the source of your project?

**Comment by gouletr** [comment]
It's not in our code base; that's PhysX, so we don't want to change that. I guess we'll have to keep vector intrinsics disabled for now.

**Comment by sunfishcode** [comment]
The main thing here are the new boolean types such as Bool64x2, which were introduced in some spec changes that were made after Firefox's main Float64x2 implementation was written. Work towards implementing the new bool types is being worked on [here](https://bug1160971.bmoattachments.org/attachment.cgi?id=8670462).

**Comment by gouletr** [comment]
@sunfishcode Cool! Which version of Firefox is it targeting? Will it make it for 44?

**Comment by sunfishcode** [comment]
SIMD.js in Firefox is currently only available in nightly builds.

**Comment by juj** [comment]
@gouletr: can you do an unminified build and check what the code on the line in question is that causes the asm.js validation error?

**Comment by gouletr** [comment]
@juj what's a unminified build again?

**Comment by juj** [comment]
Doing a build with linker flags `-O1` and higher enable minification. With no opt linker flags `-O0` or overriding the minification setting with e.g. `-O1 -g2` (or `-Oanything -g2` in general) creates an unminified build. This will leave the line endings intact so that one can easily go and examine the line:column info of where the asm.js validation fails.

**Comment by gouletr** [comment]
Does `-O2 -g4` would work? Because if I set `-O0` it just doesn't load in Firefox due to the compiler issue I mentioned before (Firefox going out of memory, because too many variables).

**Comment by juj** [comment]
Yeah, though generally `-g4` might be overkill for this, since it includes source mapping, which is not very memory friendly at the moment. Try `-O2 -g2` for example, that's generally very readable format.

**Comment by nickshinpho** [comment]
@gouletr where may i find the "PhysX 3.3 emscripten port"  --  i have access to nVidia's PhysX-3.3 github repository -- but i do not seem to see any emscripten or webGL target/platforms in there... thanks in advanced!

**Comment by gouletr** [comment]
That's just a port we did internally to build our engine so the code was never merged with NVidia's repository.

**Comment by gouletr** [comment]
I wasn't able to get the line of code that produce this warning. It brings me to line 1526 which is Emscripten code
```
// Work around Firefox Nightly bug that Float64x2 comparison return a Int32x4 instead of a Bool64x2.
try {
  if (SIMD.Int32x4.check(SIMD.Float64x2.equal(SIMD.Float64x2.splat(5.0), SIMD.Float64x2.splat(5.0)))) {
    SIMD.Float64x2.prevEqual = SIMD.Float64x2.equal;
    SIMD.Float64x2.equal = function(a, b) {
      var int32x4 = SIMD.Float64x2.prevEqual(a, b);
      return SIMD.Bool64x2(SIMD.Int32x4.extractLane(int32x4, 1) != 0, SIMD.Int32x4.extractLane(int32x4, 3) != 0);
    }
    console.error('Warning: Patching up SIMD.Float64x2.equal to return a Bool64x2 instead of Int32x4!');
  }
} catch(e) {}
```

**Comment by gouletr** [comment]
Oh I forgot to mention I also get this error right after the warning:
```
TypeError: asm.js type error: all function calls must either be calls to standard lib math functions, standard atomic functions, standard SIMD constructors or operations, ignored (via f(); or comma-expression), coerced to signed (via f()|0), coerced to float (via fround(f())) or coerced to double (via +f())
```

**Comment by gouletr** [comment]
The code that produce the TypeError is this:
```
function dynCall_Fii(index, a1, a2) {
 index = index | 0;
 a1 = a1 | 0;
 a2 = a2 | 0;
 return FUNCTION_TABLE_Fii[index & 15](a1 | 0, a2 | 0);
}
```

**Comment by kripken** [comment]
Looks like that's a function table with a SIMD result. I'll fix it.

**Comment by gouletr** [comment]
I tried to add a stackTrace in the js code where we print the warning `Warning: Patching up SIMD.Float64x2.equal...` and that didnt work. So I really dont know what code produce this warning from the C++ side. Seems like it would always happen when we enable -msse2?

**Comment by kripken** [comment]
That last error should now be fixed on incoming, it was indeed a function table SIMD result bug.

I think the "patching up" issue is separate, though, and will remain until SpiderMonkey has full Float64x2 support. Perhaps @sunfishcode or @juj know what the status of that is?

**Comment by juj** [comment]
The simd.js spec does not have Float64x2 type at the moment, I think that was planned in a future version of the spec. That message is from here: https://github.com/kripken/emscripten/blob/master/src/ecmascript_simd.js#L1348 and it will occur at startup. The warning is printed because in Firefox, we have a partial Float64x2 implementation (from old SIMD.js spec wording), which does not match the current Float64x2 polyfill implementation, so at the moment we detect the discrepancy and patch the Firefox impl up to match the polyfill.

Wrote down https://bugzilla.mozilla.org/show_bug.cgi?id=1228612 to track this. Once this is fixed, the warning should disappear, since the monkeypatching is no longer required.

**Comment by juj** [comment]
Note that the warning message should not have any effect on performance of non-Float64x2 operations, so it's safe to ignore it. Float64x2 will not have good performance or asm.js validation at the moment, since it is still unofficial.

**Comment by gouletr** [comment]
Here's an ongoing discussion about it: https://github.com/tc39/ecmascript_simd/issues/304
