### ISSUE TITLE
roundf returns itself

### ISSUE THREAD

**Issue by louisstow** [kripken/emscripten#3876]
~~~c
#include <stdio.h>
#include <math.h>

void main (void) {
    printf("%f %f %f\n", roundf(16.8), roundf(16.5), roundf(16.3));
}
~~~

Emscripten prints `16.799999 16.500000 16.299999`
GCC prints `17.000000 17.000000 16.000000`

~~~
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
clang version 3.7.0
~~~

**Comment by kripken** [comment]
Looks like a float32 precision issue. If you build with `-s PRECISE_F32=1` it works.

Perhaps we could improve on musl's `fround()` method to not be so sensitive, but generally we've preferred not to modify musl internals.

**Comment by evanw** [comment]
We just hit this too. It seems important to fix since it's totally unexpected and can cause lots of subtle issues. Would it make sense to substitute _roundf with _round at link time if musl shouldn't be changed?

**Comment by kripken** [comment]
I looked into this some more. It seems that we could do a lot better, by just implementing round/roundf using the browser's internal support, avoiding musl code which does reads and writes to memory. Pushed that to incoming.
