### ISSUE TITLE
emcmake configure step failed

### ISSUE THREAD

**Issue by Queuecumber** [kripken/emscripten#3880]
I have tried `emcmake` on two projects and both fail with the following error message (with obvious path differences):

    ERROR:root:Configure step failed with non-zero return code 1! Command line: ['cmake', '-DCMAKE_CROSSCOMPILING_EMULATOR="node"', '..', '-DCMAKE_BUILD_TYPE=MinSizeRel', '-DCMAKE_TOOLCHAIN_FILE=/home/mehrlich/Desktop/emsdk_portable/emscripten/tag-1.35.2/cmake/Modules/Platform/Emscripten.cmake'] at /home/mehrlich/Code/SDL-emscripten/build

Paste of the full error log [here](http://pastebin.com/sZKE4m9r)

Am I doing something wrong is is this a bug on your end?

**Comment by kripken** [comment]
The error looks like

````
clang-3.8: error: unknown argument: '-mpreferred-stack-boundary=2'
````

where is that argument coming from?

**Comment by Queuecumber** [comment]
hmmm I have no idea. I am following [these instructions](https://github.com/gsathya/SDL-emscripten/wiki/Building-with-CMake) and it happens on two completely unrelated projects so it could be a machine configuration? Do you have any suggestions for where I should look?

**Comment by kripken** [comment]
I've never seen that argument myself so no specific guesses. I would just grep in the projects' `CMake*` files for it, and if it's not there, in the cmake install on your system perhaps. Also worth seeing if the emscripten cmake tests pass on your system (`tests/runner.py other.test_cmake`).

**Comment by Queuecumber** [comment]
Update

1. The tests all pass
2. The project with the paste output in the original post does indeed set `-mpreferred-stack-boundary=2` in it's top level CMakeLists.txt
3. The other project doesn't, set that option, so I had a look at the error log and it is a completely different problem.

**Comment by kripken** [comment]
Ok, I think we can close this then.

**Comment by Queuecumber** [comment]
Agreed thanks for the help and sorry to waste your time

**Comment by kripken** [comment]
No problem, glad to help.
