### ISSUE TITLE
EM_ASM_DOUBLE return wrong value

### ISSUE THREAD

**Issue by claudiodaffra** [kripken/emscripten#3887]
i put here this simple code; correct result (1.2) but printf show 1.0000; double fail
int main ( void ){
double a=1.1;
double b=2.2;
double x = EM_ASM_DOUBLE({
    Module.print('I received: ' + $0);
    Module.print('I received: ' + $1); 
	return $0+0.1 ;
}, a,b);
 printf ( "%9.9lf",x ) ;
 return 0 ;
}

**Comment by kripken** [comment]
which version of emscripten is this on? it seems to be fixed already on 1.35.4.

**Comment by claudiodaffra** [comment]
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.1

**Comment by kripken** [comment]
Looks like it was fixed in 1.34.8 in 9dd293802d00d3d4051e5924a97ee8f76b1805f4

**Comment by claudiodaffra** [comment]
version 1.34, now i have fixed, with latest update, as you indicate me, thank you my friend.

**Comment by kripken** [comment]
Great.
