### ISSUE TITLE
64 bit integer bit operation

### ISSUE THREAD

**Issue by jardakotesovec** [kripken/emscripten#3895]
I built freetype library with emscripten, but library misbehaved with some math. I tracked down that this particular operation goes wrong:

```
#include <stdio.h>
#include <stdlib.h>

int main() {
    long int a = 131072000;
    printf("a: %lu, a << 16: %lu", a, a << 16);
    return 0;
}
```
Output in chrome:
```
a: 131072000, a << 16: 0
```

Output from normally compiled c program:
```
a: 131072000, a << 16: 8589934592000
```
It was compiled on ubuntu 64-bit (inside docker), freshly built emscripten. Tested on OS X with latest stable chrome.

I solved this by forcing freetype to emulate via 32-bit. 

Let me know if there are some details I could provide.

**Comment by juj** [comment]
Try changing `long int` to `int64_t` or `long long int`? There does not exist a standard that would dictate that  `long int` should be 64 bits.

**Comment by jardakotesovec** [comment]
@juj  I see, that makes sense. Thanks. 

Changing to `long long int` fixed my simple example. I will try to find out tomorrow, why freetype thought that `long int` is way to go. 

Here is ftconfig.h. In case you have some insights. I don't know what all magic does the `emmake` does.
https://gist.github.com/jardakotesovec/67315cf0474a3168b0d6

**Comment by juj** [comment]
Oh, perhaps it's possible that the build system does some kind of detection in the configure step, and it misdetects  the difference between build host (long=64) and build target (long=32) and assumes they would be the same?

Did you use cmake to configure the free type build? I generally use that, and build checks for size of long should come out correct there.

**Comment by jardakotesovec** [comment]
@juj Not sure what tools are behind that exactly, just followed the `emconfigure ./configure` and `emmake make` steps. But basically after `./configure` step, there is `build/unix/ftconfig.h` file which defines which type will be used as 64 bit int.
So just changed default value
```
#define FT_LONG64
#define FT_INT64   long
#define FT_UINT64  unsigned long
```
to
```
#define FT_LONG64
#define FT_INT64   long long int
#define FT_UINT64  unsigned long long int
```

And that seems to solve the problem.

@juj Thanks again for pushing me to the right direction.
