### ISSUE TITLE
macro expansion EM_ASM_INT have issues with javascript array

### ISSUE THREAD

**Issue by claudiodaffra** [kripken/emscripten#3896]
macro expansion EM_ASM_INT have issues with javascript array
not for EM_ASM this macro works perfectly

emcsriten 1.34 on windows 8 TESTED
clang version 3.7.0  
Target: x86_64-pc-windows-msvc
Thread model: posix
emscripten 1.35 on Linux Mint 17.1 NOT TESTED

----------------------------- source code
#include <emscripten.h>
#include <stdio.h>

int main ( void ) 
{
	int ret = EM_ASM_INT  ( {
		var x = $0 ;
		var a = [1,2,3] ; // <---- issue with javascript array
		return 1 ;
	},10) ;	
	printf ("%d",ret );
	return 0 ;
}
------------------------------- Error

prova.cpp:9:17: error: expected ')'
                var a = [1,2,3] ;
                              ^
C:\Program Files\Emscripten\emscripten\1.34.1\system\include\emscripten\emscripten.h:54:63: note: expanded from macro 'EM_ASM_INT'
#define EM_ASM_INT(code, ...) emscripten_asm_const_int(#code, __VA_ARGS__)
                                                              ^
prova.cpp:7:12: note: to match this '('
        int ret = EM_ASM_INT  ( {
                  ^
C:\Program Files\Emscripten\emscripten\1.34.1\system\include\emscripten\emscripten.h:54:55: note: expanded from macro 'EM_ASM_INT'
#define EM_ASM_INT(code, ...) emscripten_asm_const_int(#code, __VA_ARGS__)
                                                      ^
prova.cpp:11:3: error: expected unqualified-id
        },10) ; 
         ^
C:\Program Files\Emscripten\emscripten\1.34.1\system\include\emscripten\emscripten.h:54:63: note: expanded from macro 'EM_ASM_INT'
#define EM_ASM_INT(code, ...) emscripten_asm_const_int(#code, __VA_ARGS__)
                                                              ^
prova.cpp:13:2: error: C++ requires a type specifier for all declarations
        printf ("%d",ret );
        ^
prova.cpp:13:15: error: use of undeclared identifier 'ret'
        printf ("%d",ret );
                     ^
prova.cpp:15:2: error: expected unqualified-id
        return 0 ;
        ^
prova.cpp:16:1: error: extraneous closing brace ('}')
}
^
6 errors generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting

instead, in this way works :

int main ( void ) 
{
	int ret = EM_ASM_INT ( {
		var a = new Array($0) ;
		a[0] = 10 ; //  
		a[1] = 11 ;
		return a[1] ; ;
	},10) ;	
 
	printf ("%d",ret );
	
	return 0 ;
}

regards
claudio

**Comment by kripken** [comment]
This looks like a C preprocessor issue. It gets confused by that input.

Not sure what we can do, as we can't change the preprocessor for this. A workaround is to write such code in a js-library instead, which is basically the same as EM_ASM but is in a separate file.

**Comment by claudiodaffra** [comment]
with this macro, code compiles :

	#include <emscripten.h>
	#include <stdio.h>

	#define xEM_ASM_INT(code...) emscripten_asm_const_int(#code)
	 
	int main ( void ) 
	{
		int ret =  xEM_ASM_INT(
			var x = $0 ;
			var a = [1,2,3];
			return 1 ;
		,10) ; 
		
		printf ("%d",ret );
		return 0 ;
	}

unfortunately problem recurs in javascript generated code :

	// === Body ===

	var ASM_CONSTS = [function($0) { ( var x = $0 ; var a = [1,2,3]; return 1 ; ),10 }];

	function _emscripten_asm_const_0(code) {
	 return ASM_CONSTS[code]() | 0;

**Comment by kripken** [comment]
A downside to that approach is that it turns the input into a string, which is less efficient and must be evalled. But perhaps we should add such a macro. Basically like `emscripten_run_script` which receives a string, but with the `#` trick so people don't need to write the `"`.

**Comment by claudiodaffra** [comment]
you may change compiler translation code directly, so in this way works

	//var ASM_CONSTS = [function($0) { var x = $0 ; var a = [1,2,3]; return 1 ; ,10 }];

	function _emscripten_asm_const_0() 
	{
	 var x = 10 ; var a = [1,2,3]; return 1;
	}

**Comment by kripken** [comment]
I don't understand? Is that trying to work around the preprocessor problem? Or the string problem I mentioned in the last comment?

**Comment by claudiodaffra** [comment]
i have resolved in this way,

	int main ( void ) 
	{
		EM_ASM_	({
			var x = $0 ;
		} , 3 ) ; 
		
		int ret = -1 ;
		
		EM_ASM (    
			var a = [1,2,3];
			value = (a[0]+a[1]+a[2]) * 3 ;
		) ;

		ret = EM_ASM_INT ({
			return value ;
		} , NULL ) ;	
		
		printf ("%d",ret );
		return 0 ;
	}
	
ciao Kripken

**Comment by claudiodaffra** [comment]
i've resolved my issue in this way

	int main ( void ) 
	{
		EM_ASM_	({
			Module['x'] = $0 ;
		} , 3 ) ; 
		
		int ret = -1 ;
		
		EM_ASM (    
			var a = [1,2,3];
			value = (a[0]+a[1]+a[2]) * Module.x ;
		) ;

		ret = EM_ASM_INT ({
			return value ;
		} , NULL ) ;	
		
		printf ("%d",ret );
		return 0 ;
	}

**Comment by evanw** [comment]
The C preprocessor assumes top-level commas mean additional macro arguments. The preprocessor is only aware of nesting due to parentheses, not curly braces or square brackets which are just treated like any other token. To get around this, just make sure the commas are surrounded by parentheses:

```
int main ( void ) 
{
  int ret = EM_ASM_INT ( {
    var x = $0 ;
    var a = ([1,2,3]); // <---- make sure commas appear inside parentheses
    return 1 ;
  },10) ; 
  printf ("%d",ret );
  return 0 ;
}
```

@kripken this is probably something that's useful to have in the documentation near EM_ASM_INT and friends.

**Comment by kripken** [comment]
Thanks, that clarifies things a lot. I'll add that now.

**Comment by kripken** [comment]
Added. I think that's all we can do here, closing.
