### ISSUE TITLE
vswscanf missing ! Uncaught abort(-1)

### ISSUE THREAD

**Issue by claudiodaffra** [kripken/emscripten#3906]
vswscanf missing ! Uncaught abort(-1)

As you can see, by this example below; compiler show me this
warning message : unresolved symbol: vswscanf ;

warning: a problem occurred in builtin C++ name demangling; 
build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling

	Uncaught abort(-1) at Error
		at jsStackTrace (file:///C:/em/main.js:1166:13)
		at stackTrace (file:///C:/em/main.js:1183:22)
		at abort (file:///C:/em/main.js:17571:44)
		at _vswscanf (file:///C:/em/main.js:5622:53)
		at __Z14GetWideMatchesPKwS0_z [GetWideMatches?S(wchar_t*)] (file:///C:/em/main.js:6556:3)
		at _main (file:///C:/em/main.js:6571:2)
		at Object.asm._main (file:///C:/em/main.js:15722:19)
		at Object.callMain (file:///C:/em/main.js:17436:30)
		at doRun (file:///C:/em/main.js:17494:60)
		at run (file:///C:/em/main.js:17508:5)

so i'm trying :

	em++ -std=c++11 bug.cpp -o main.js  -s DEMANGLE_SUPPORT=1

warning: emitted code will contain very large numbers of local variables, 
which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
warning: unresolved symbol: vswscanf

but error in runtime always occur ...

	/* vswscanf example */
	#include <stdarg.h>
	#include <wchar.h>

	void GetWideMatches ( const wchar_t * str, const wchar_t * format, ... )
	{
	  va_list args;
	  va_start (args, format);
	  vswscanf (str, format, args);
	  va_end (args);
	}

	int main ()
	{
	  int val;
	  wchar_t buf[100];

	  GetWideMatches ( L"99 bottles of beer on the wall", L" %d %ls ", &val, buf);

	  wprintf (L"Product: %ls\nQuantity: %d\n", buf, val);

	  return 0;
	}
emscripten 1.34  :windows10 , emscripten 1.35 linux mint 17.1
best regards
Claudio

**Comment by kripken** [comment]
That works for me on `1.35.7` (incoming branch). Perhaps your version is before we switched to musl for libc, which provides this method.

**Comment by claudiodaffra** [comment]
yes,  as you say.

**Comment by kripken** [comment]
Ok, closing.
