### ISSUE TITLE
Exclude zero-initialized values from .mem file

### ISSUE THREAD

**Issue by danvk** [kripken/emscripten#3907]
Consider this small C program:

```c
#include <stdio.h>

int buf[1048576];

int main() {
  printf("hello, world! %d\n", buf[123456]);
  return 0;
}
```

When I build this file with `emcc -O2`, it produces a large (4MB) `.mem` file:

```
$ emcc -O2 hello.c -o hello.js
$ ls -l hello*
      111 hello.c
   185535 hello.js
  4198443 hello.js.mem
```

This file is almost entirely zeros, as evidenced by how well it gzips:

```
$ gzip -c hello.js.mem | wc -c
    5302
```

When I build the same binary with `gcc`, I get a much smaller output:

```
$ gcc -O2 hello.c -o hello
$ ls -l hello
8464 hello
```

So evidently `gcc` is smarter about not writing zero-initialized values to disk.

I realize that, since this file compresses so well, it may not seem like an issue in practice. But not everyone's web server is configured to do this properly. It feels like an unnecessary risk to have such a large file lying around and it feels like a bug when you first use Emscripten. If it's not necessary, why include all those zeros?

See also #3815 and [this discussion][1] on emscripten-discuss.

[1]: https://groups.google.com/forum/#!topic/emscripten-discuss/nZz2tjepBPY

**Comment by kripken** [comment]
Pushed an optimization to incoming. If you get a chance to measure this on your app I'd be interested to hear the results.

**Comment by danvk** [comment]
Brilliant! Thanks for the quick fix.

Before (emcc 1.34.12):
```
    346353 out.js
   2076549 out.js.mem
```

After (emcc 1.35.9):
```
    347675 out.js
      6177 out.js.mem
```

**Comment by kripken** [comment]
Great, thanks for the confirmation.

**Comment by juj** [comment]
Do we have a real zero section in Emscripten? I.e. all global data that have their initializer value initialized to zero would lie in subsequent memory addresses, and the memory initializer could omit all of the zeroes? I suppose that is what the staticBump is about?

**Comment by kripken** [comment]
Yes. Typed arrays are zero-initialized anyhow, so all we need is to bump the top of static memory, to leave space for them. The optimization just sorts them all to the end, and does not emit them into the memory init file.
