### ISSUE TITLE
-O3 and --closure 1    issue.

### ISSUE THREAD

**Issue by Joffrey** [kripken/emscripten#3912]
**Emscripten 1.35.9**

```c++
#include <stdio.h>
#include <emscripten.h>

extern "C" {

int main() {
	printf("Hello World !\n");
	return 0;
}

}
```

This code doesn't run with __-O3__ and __--closure 1__ parameters and javascript throws an error :
> TypeError: global is undefined

But it works fine without **--closure 1**.

**Comment by kripken** [comment]
Seems ok in `1.35.9`.

In what are you running the code?

**Comment by Joffrey** [comment]
Sorry it's my html which uses the same variable name as the final js output.
Sorry for all.
