### ISSUE TITLE
documentation for building Emscripten sends user down recursive infinite loop

### ISSUE THREAD

**Issue by sterlingcrispin** [kripken/emscripten#3913]
I want to build emscripten from source ,...

https://kripken.github.io/emscripten-site/docs/building_from_source/index.html#installing-from-source

I'm using OSX so I follow this link

https://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_mac_os_x.html

I already have Xcode command line tools, git, cmake, nodejs, I setup python2 as required in step 5 and then 

Step 6 says "Build Fastcomp (LLVM + Clang) from source using these instructions."  which links you to this page

https://kripken.github.io/emscripten-site/docs/building_from_source/building_fastcomp_manually_from_source.html#building-fastcomp-from-source-building

Which says 

"What you’ll need

First follow the instructions for your platform showing how to manually build Emscripten from source."

linking me back to https://kripken.github.io/emscripten-site/docs/building_from_source/index.html#installing-from-source

**Comment by kripken** [comment]
Note that the the link before last points to the section *after* "What you'll need", it goes to the section called "Building Fastcomp". So there isn't a direct infinite loop here. But, perhaps we could improve the text here, open to suggestions.

**Comment by sterlingcrispin** [comment]
I think this page

https://kripken.github.io/emscripten-site/docs/building_from_source/building_fastcomp_manually_from_source.html

Should say 

"First verify you have the compiler toolchain for your platform, download and install them as necessary.

Then follow the instructions for your platform showing how to manually build Emscripten from source steps 1-6 and return to this page. When you're done here return to those instructions."

**Comment by kripken** [comment]
Sounds good. Would you like to open a pull request with that change? The site docs are under `site/source`.

**Comment by claudiodaffra** [comment]
I add this broken link :

Unofficial Google+ page :

https://plus.google.com/100622854474489221138

**Comment by kripken** [comment]
Thanks, I removed the broken link.

**Comment by literalpie** [comment]
This issue should be closed. The change has been made

**Comment by kripken** [comment]
Good, thanks for the reminder.
