### ISSUE TITLE
installing on OSX El Capitan

### ISSUE THREAD

**Issue by calvinmetcalf** [kripken/emscripten#3916]
El Capitan doesn't allow you to modify /usr/bin so installation is failing

**Comment by kripken** [comment]
See #3872 for recent progress on this.

**Comment by juj** [comment]
We should now be fully python2/python3 aware (in incoming branch). When you say installation is failing, what installation are you referring to? Emsdk nor Emscripten modifies /usr/bin during installation?

**Comment by calvinmetcalf** [comment]
so strictly speaking installation is a success its *running* it that fails, but I was referring to the the installation instructions that fail.  When build from the incoming branch it does work so can confirm that you can use it in El Capitan if you want to spend an hour or 2 building it.

**Comment by juj** [comment]
Sounds like it is then about the `python2` symlinking issue, which has been fixed, so closing.
