### ISSUE TITLE
The linker flag --std=c++11 is silently ignored.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3938]
STR: First:

    >em++ tests\hello_cxx03.cpp -o a.html

works. Then:

    >em++ tests\hello_cxx03.cpp -o a.html --std=c++11

also works.

	>em++ tests\hello_cxx11.cpp -o a.html
	tests\hello_cxx11.cpp:4:2: error: This file should be compiled with -std=c++11!
	#error This file should be compiled with -std=c++11!
	 ^
	1 error generated.
	ERROR:root:compiler frontend failed to generate LLVM bitcode, halting

fails, as it should be, since we default to c++03 std mode. However:

	>em++ tests\hello_cxx11.cpp -o a.html --std=c++11
	tests\hello_cxx11.cpp:4:2: error: This file should be compiled with -std=c++11!
	#error This file should be compiled with -std=c++11!
	 ^
	1 error generated.
	ERROR:root:compiler frontend failed to generate LLVM bitcode, halting

It looks like `--std=c++11` does not enable C++11, but also is silently ignored without diagnostics. We should probably make `--std=...` generate a compiler frontend error saying that it's a wrong flag, and the proper form is `-std=...` instead?

**Comment by kripken** [comment]
Looks like in clang it accepts both, so let's just make emcc do the same? Just need to update one line, `elif newargs[i].startswith('-std='):` in emcc.py.

**Comment by juj** [comment]
Oh, thanks for diagnosing so quickly! I can verify - pushed that directly in.

**Comment by kripken** [comment]
Please push a test as well. I think we already have one for the one dash version in `other` somewhere.

**Comment by jeffRTC** [comment]
@juj 

How do you know which flag is linker type and which flag is compiler type? 

I can't find any info on this.

**Comment by sbc100** [comment]
For settings there is some documentation in `src/settings.js`.   You will see some flags marks as `[link]` or `[compile+link]` for example.

Other than that a lot of out flags mirror that of clang so you can refer to the clang documentation too.
