### ISSUE TITLE
Minification triggering invalid cwrap generation

### ISSUE THREAD

**Issue by loganfsmyth** [kripken/emscripten#3945]
We're using Uglify and it minifies the `stringToC` function to the following

```
function (e){var t=0;return null!==e&&void 0!==e&&0!==e&&(t=Runtime.stackAlloc((e.length<<2)+1),writeStringToMemory(e,t)),t}
```

which gets parsed into

```
{
  "arguments": "e",
  "body": "var t=0",
  "returnValue": "null!==e&&void 0!==e&&0!==e&&(t=Runtime.stackAlloc((e.length<<2)+1),writeStringToMemory(e,t)),t"
}
```

which breaks, compared to the original code on this line:

```
funcstr += arg + "=" + convertCode.returnValue + ";"
```

because the generated code, along the lines of

```
$0 = null!==e&&void 0!==e&&0!==e&&(t=Runtime.stackAlloc((e.length<<2)+1),writeStringToMemory(e,t)),t;
```

is parses as

```
($0 = null!==e&&void 0!==e&&0!==e&&(t=Runtime.stackAlloc((e.length<<2)+1),writeStringToMemory(e,t))),t;
```

rather than the intended

```
$0 = (null!==e&&void 0!==e&&0!==e&&(t=Runtime.stackAlloc((e.length<<2)+1),writeStringToMemory(e,t)),t);
```

Note the location of the parens. In this case, it means that the first argument of the function is always `undefined`.

**Comment by kripken** [comment]
I admit to not being able to fully follow that (what is `convertCode`, and how does it relate to the lines before it?). But this sounds like a bug in uglify - which version are you using?

Emscripten's test suite contains a ccall test that runs under minification using both uglify (the version bundled in emscripten, `1.0.7`, unmodified), and closure compiler.

**Comment by loganfsmyth** [comment]
Sorry, filed this bug a little quickly as I left work earlier.

`convertCode` is in [the preamble.js here](https://github.com/kripken/emscripten/blob/42fb486c53d627b203b77af6e5d0c088c0ad03ad/src/preamble.js#L248)  as a result of [this regex parser](https://github.com/kripken/emscripten/blob/42fb486c53d627b203b77af6e5d0c088c0ad03ad/src/preamble.js#L211). This is an issue with Emscripten's `cwrap` specifically, not ccall, so perhaps that is why the tests don't catch it?

The core issue is that the minifier changes the function to use the comma operator, which has different precedence in an assignment context vs a `return` context. Here's a quick example of the difference, which would show up in your current code if you manually used a comma and ignored the minifier:

```
(function(){
  var one = 1;
  var two = 2;
  return one, two;
})();
// evaluated as: return (one, two);
// returning 2
```

vs the current transform that moves the expression from a `return` onto an assignment:

```
(function(){
  var one = 1;
  var two = 2;

  var res;
  res = one, two;
  return res;
})();
// evaluated as: (res = one), two;
// returning 1
```

so to properly maintain the meaning of the originally code, essentially [that line from the preamble](https://github.com/kripken/emscripten/blob/42fb486c53d627b203b77af6e5d0c088c0ad03ad/src/preamble.js#L248) instead of 

    funcstr += arg + "=" + convertCode.returnValue + ";"

should be

    funcstr += arg + "= (" + convertCode.returnValue + ");"

**Comment by loganfsmyth** [comment]
Specifically, given my examples above, the code for `stringToC` ends up with

```
return null !== e &&
    void 0 !== e &&
    0 !== e && (
        t = Runtime.stackAlloc((e.length<<2)+1),
        writeStringToMemory(e,t)
    ),
    t;
````
which will return the value `t` from `stackAlloc` but evaluating the comma operator, to

```
$0 = null !== e &&
    void 0 !== e &&
    0 !== e && (
        t = Runtime.stackAlloc((e.length<<2)+1),
        writeStringToMemory(e,t)
    ),
    t;
````

which will assign the return value of `writeStringToMemory` into `$0`, essentially making any string argument `undefined`, and then it will discard the value of `t`.

**Comment by kripken** [comment]
Thanks for the elaboration. Ok, I think I understand now.

We do test cwrap under those minifications [here](https://github.com/kripken/emscripten/blob/incoming/tests/test_core.py#L6472), but I guess your version of uglify just minifies differently, and happens to hit this issue, while our uglify and closure do not?

In any case, this is definitely something we should fix with adding parens as you suggested, I pushed that to incoming now. I wish I could add a test, but if it requires bundling another minifier, that seems like overkill ;)

**Comment by loganfsmyth** [comment]
Thanks!
