### ISSUE TITLE
Alpha false by default and hardcoded into Browser.createContext ?

### ISSUE THREAD

**Issue by SBRK** [kripken/emscripten#3966]
I have a problem where I read pixels from the backbuffer and the alpha is always 255, even if I set it to something else. 
After digging, I traced that to the initialisation of the WebGL context, where alpha is always false, because it is hard coded in Browser.createContext.
Couldn't this be set to something else via the SDL_GL_ALPHA_SIZE attribute, in the same fashion as the stencil, with SDL_GL_STENCIL_SIZE in LibrarySDL.makeSurface ?

**Comment by kripken** [comment]
I saw the pull you opened for this - is that enough, or do we need other changes to support this?

**Comment by SBRK** [comment]
It's working for me so I think it's enough

**Comment by kripken** [comment]
Ok, let's close this then, the pull is enough.
