### ISSUE TITLE
Optimization -O2 generates unworkable code

### ISSUE THREAD

**Issue by yurevich1** [kripken/emscripten#3977]
If I try to optimize code using 
```
 ../emscripten/emcc -O2 ./emsc/fs.c src/liblzma/.libs/liblzma.a -Isrc/liblzma/api -s TOTAL_MEMORY=536870912  -o emsc/html/fs.min.html
```

but without -O2 all works.
I can't find an error because on correct callstack is show.
It just says, "No such file or directory"

**Comment by kripken** [comment]
The full output with `EMCC_DEBUG=1` in the env would help.

**Comment by yurevich1** [comment]
`Uncaught Error: No such file or directory` again :)

**Comment by kripken** [comment]
That's the entire console output? Then perhaps emcc does not exist where you are trying to call it? If it does, perhaps insert some debug printouts inside it? Or try a fresh reinstall?

**Comment by yurevich1** [comment]
I'm using this script as a Web Worker in a broswer. I'm converting a c++ lib into pure js code.
In main UI the same behavoiur.

Uncaught Error: No such file or directory FS.open @
 wrapper.js:1FS.readFile @
 wrapper.js:1Module.return @ 
wrapper.js:1toXZ @
 wrapper.js:14xzmemui.onclick @
 (index):56

In my code FS.readFile and FS.open appears only in Module.return() statement.
That is in -O0 it call at the end of operations but if -O2 it is called at the begin.

Module['return'] = function() {
	///...
		return FS.readFile('/data/file.data.xz');
	///...
	};
I have some callback functions inside the code.
-O2
That's why

Module.return() is called then some callback functions. No result at the end.

if -O0 all works,
Why?:)

**Comment by kripken** [comment]
One possible difference is that in `-O2` we have a mem init file, which makes startup asynchronous. Try `--memory-init-file 0` in `-O2` to disable that

If that's not it, then I am having a hard time following this. Is the error during compile time, or runtime? If runtime, can you provide a small standalone testcase + full instructions to build, that I can try to reproduce and debug the problem?

**Comment by yurevich1** [comment]
https://blog.slava.online/testdir/xz_example/ - with -O0 optimization + grunt compression. this is a workable example.
https://blog.slava.online/testdir/xz_example_O2/ - with -O2 optimization. 

To check press 'xz me! main UI' - to check main UI JavaScript execution. In the first case all works. It the second case it gives the error.

Open Debug Console. to view results.

**Comment by yurevich1** [comment]
I've tested `--memory-init-file 0` . Now it really works! Thanks. `-Oz` creates code which is much faster than `-O0` (by 3 times).

**Comment by kripken** [comment]
Ok, good.
