### ISSUE TITLE
Memory releasing doesn't work.

### ISSUE THREAD

**Issue by yurevich1** [kripken/emscripten#3978]
How can I release all memory after code execution?
If I'm using Web Worker I can just terminate. But if I use usual code the memory is in use even after  `Module.return()`

**UPDATE**
I found it takes some time (several seconds) in order to release huge memory.
You may close this topic.

**Comment by kripken** [comment]
Yes, you need to wait for the browser to collect garbage.

The `MODULARIZE` option is helpful here, btw (to make sure nothing stays around).
