### ISSUE TITLE
Unsigned SIMD types

### ISSUE THREAD

**Issue by stoklund** [kripken/emscripten#3982]
The unsigned integer SIMD types will most likely land in Firefox mozilla-inbound today. The tracking bug is <https://bugzilla.mozilla.org/show_bug.cgi?id=1233111>. This implements SpiderMonkey interpreter support for `SIMD.Uint8x16`, `SIMD.Uint16x8`, and `SIMD.Uint32x4`.

Right shifts
---------------
The patch series implements three right shift operations on every integer SIMD type, signed or unsigned:
- `shiftRightArithmeticByScalar` which is not part of SIMD.js.
- `shiftRightLogicalByScalar` which is not part of SIMD.js.
- `shiftRightByScalar` which behaves differently depending on the signedness of the underlying type. This is the only right shift operation defined in the SIMD.js spec.

*Emscripten should switch to using the standard `shiftRightByScalar` only*. The others can be polyfilled easily. The plan is to remove the non-standard right shift operations form SpiderMonkey with <https://bugzilla.mozilla.org/show_bug.cgi?id=1201934>.

Negation
------------
The new unsigned SIMD types all have a `neg` operation. It looks like the Emscripten polyfill does not implement `neg` on the unsigned types. See also <https://github.com/tc39/ecmascript_simd/issues/310>.

**Comment by juj** [comment]
Thanks for mentioning these! The above pull request should now resolve all the points here.
