### ISSUE TITLE
webidl test generates warnings

### ISSUE THREAD

**Issue by andreasplesch** [kripken/emscripten#3994]
Running 
```python tests/runner.py test_webidl```
generates these warnings:
```WARNING:root:function requested to be exported, but not implemented: "_main"```
for all three modes but finishes with an 'ok'.
Harmless ?

**Comment by kripken** [comment]
Yes, these are libraries and so they lack a `main()`, but in the test we didn't bother to remove it from the list of exported functions, it looks like.

**Comment by kripken** [comment]
It would be nice to fix that, of course.

**Comment by andreasplesch** [comment]
Ok, #4005 adds -s EXPORTED_FUNCTIONS=['_malloc'] to the emcc args in both test_core.py and test_browser.py. I tested with node but could not run the browser test due to httpd at localhost:9999 not being accessible though running.

**Comment by kripken** [comment]
Fixed on incoming by that merge.
