### ISSUE TITLE
When a .mem file is generated, "Dowloading..." never ends in Chrome

### ISSUE THREAD

**Issue by behdad** [kripken/emscripten#4000]
When compiling GLyphy with -O2 or -O3, resulting html file works just fine in Firefox, but the "Downloading..." phase never ends in Chrome and actual app never starts.

**Comment by behdad** [comment]
Humm, it seems to be because XMLHttpRequest is not supported for file: scheme in Chrome.  Perhaps warn the user?  Here's from the console log:

```
glyphy-demo.html:1310 XMLHttpRequest cannot load file:///home/behdad/SSD/gl/glyphy/embuild/demo/glyphy-demo.html.mem. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

**Comment by kripken** [comment]
Yes, chrome has issues with file URLs, so it's best to use a local webserver.

You should already receive a warning from emscripten if the xhr for the mem init file fails. Do you not see anything in the console?

**Comment by behdad** [comment]
I only see the warning that I mentioned in the previous comment.

**Comment by kripken** [comment]
Ok, then I guess we listen to onload and onerror, and chrome must not fire either one, as the xhr is not actually valid. At least we have that chrome warning in the console, I think that's all we can hope for here, so closing.
