### ISSUE TITLE
other.test_llvm_lit looks broken after recent SIMD updates 

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4004]
Might need to update those tests a little.

@juj

**Comment by juj** [comment]
Fixed by https://github.com/kripken/emscripten-fastcomp/commit/e7a5c111135f4bca3c5a98068af5411de13fed22 and https://github.com/kripken/emscripten-fastcomp/commit/e44e614cc457b54a9a4429d7869ba45b1250cd1e
