### ISSUE TITLE
Bag SIMD with ' Linking globals named 'emscripten_float32x4_lessThan' '

### ISSUE THREAD

**Issue by dalter** [kripken/emscripten#4011]
Hi i trying compil Mupen n64 emulator  with  DYNAREC  msse msse2 flags
But have this error 

emscripten v1.35.2 and 1.35.14

ERROR: Linking globals named 'emscripten_float32x4_lessThan': symbol multiply defined!
Traceback (most recent call last):
  File "/home/dalter/webdev/tools352/emscripten/emcc", line 1201, in <module>
    shared.Building.link(linker_inputs, specified_target)
  File "/home/dalter/webdev/tools352/emscripten/tools/shared.py", line 1432, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error: 
Makefile:399: recipe for target 'mupen64plus_libretro_emscripten.bc' failed
make: *** [mupen64plus_libretro_emscripten.bc] Error 1

**Comment by kripken** [comment]
That's a surprising error. Do you have a small testcase showing the problem?

In particular, that method is defined inline in `vector.h`, so I'm not sure why it would be linked twice. Unless inlining was disabled somehow?

**Comment by juj** [comment]
There has been a big chunk of improvements in the SIMD.js support in Emscripten vector.h intrinsics as well as SSEx intrinsics, so I'll close this issue for now. If there are still problems, feel free to reopen.
