### ISSUE TITLE
Vanilla LLVM

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4013]
With the `WASM_BACKEND` option, emscripten uses the WebAssembly backend to generate wasm (well, it generates a .s, then we use binaryen's s2wasm to get wasm). When doing so, we are not using the asm.js backend at all, and in fact we don't really need fastcomp - plain vanilla upstream LLVM should work.

A few minor things might need to be done to make sure this works properly:
 * We have some linking optimization code in `opt`. We can just not use it if we are using vanilla LLVM.
 * We need to tell clang and llvm to use the wasm triple.

And we need a plan for some other issues:
 * We can check if we have a vanilla LLVM by checking if the asm.js backend exists.
 * When using vanilla LLVM, we might as well auto-enable `WASM_BACKEND`.
 * Should changing the backend force a cache rebuild? Seems like it must, since the asm.js and wasm triples are not identical - in particular, wasm has long doubles. But rebuilds might be annoying, we could just have one cache dir per triple I suppose.
 * Testing? Optimal would be to test this on actual vanilla LLVM, to be 100% sure, but then it means 2 builds of LLVM for full coverage. Maybe not worth it?

Benefits of supporting vanilla LLVM
 * In the future, hopefully it's all we need, so we are preparing for that.
 * Some potential users don't want a side LLVM (either because of internal corporate policy, or because they are a project that already has a side LLVM - like Rust or Swift - so another one is tricky), so this could help them, at least when the wasm backend is ready.

cc @jfb, @juj, @sunfishcode

**Comment by kripken** [comment]
whoops, wrong cc, sorry. I meant @jfbastien :)

**Comment by jfb** [comment]
No worries!






On Tue, Jan 5, 2016 at 5:02 PM -0800, "Alon Zakai" <notifications@github.com> wrote:












whoops, wrong cc, sorry. I meant @jfbastien :)

**Comment by jfbastien** [comment]
Thanks for writing this up.

We'd also discussed making the C / C++ / runtime library location pluggable, so we can try upstreaming part of the changes and optionally point the tooling at a different directory.

**Comment by kripken** [comment]
Ok, this is mostly done. There is a `vanilla` branch with this, and in binaryen there is [a pull](https://github.com/WebAssembly/binaryen/pull/112) that tests that it works, which passes.

The only thing left here is to merge `vanilla` into `incoming`. I had to make some changes to bootstrapping stuff, so I'll check it carefully first.

**Comment by kripken** [comment]
This landed and can be closed.
