### ISSUE TITLE
Compile error when applying an atomic operation to a bitcasted address.

### ISSUE THREAD

**Issue by Maher4Ever** [kripken/emscripten#4025]
Hello there,

First of all happy new year! For the past couple of days I was trying to figure out why Emscripten was crashing while compiling an LLVM IR file containing some functions. After reducing the code to the instructions causing the crash it seems like there is something going wrong when applying an atomic operation to a bitcasted address.

Here is the reduced function causing the crash:

```
; ModuleID = 'test.ll'

define i64 @test_func(i8* %arg1) {
entry:
  %.7.i = bitcast i8* %arg1 to i64*
  %.4.i.i = atomicrmw add i64* %.7.i, i64 1 monotonic

  ret i64 0
}
```

Compiling this module with the following command `emcc test.ll -o test.js -s EXPORTED_FUNCTIONS="['_test_func']" -s INVOKE_RUN=0 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s ASSERTIONS=1 -s SAFE_HEAP=1` results in the following output:

```
0x000000013FBE0C35 (0x0000000000E970C8 0x0000000000B0E8C0 0x0000000000C7EE48 0x0000000000C7EE48), rl_set_output_buffer() + 0xC81B5 bytes(s)
0x000000013FDC7D47 (0x0000000000B0EF18 0x0000000000BF3288 0x0000000000C0AF10 0x0000000000B0EF18), rl_set_output_buffer() + 0x2AF2C7 bytes(s)
0x000000013FDC4EA2 (0x00000001402EFF60 0x0000000000C025F0 0x0000000000BF32C0 0x0000000000C419D0), rl_set_output_buffer() + 0x2AC422 bytes(s)
0x000000013FCC0D89 (0x0000000000000002 0x0000000000000000 0x0000000000000001 0x0000000000BF32C0), rl_set_output_buffer() + 0x1A8309 bytes(s)
0x000000013FCC0501 (0x0000000000000000 0x0000000000B0F350 0x0000000000BF32C0 0x0000000000C01620), rl_set_output_buffer() + 0x1A7A81 bytes(s)
0x000000013F99E402 (0x0000000000BE7FD0 0x0000000000BE8A60 0x0000000000BE7FD0 0x0000000000000000)
0x000000013F9A00BD (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x000000014000A99F (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), rl_set_output_buffer() + 0x4F1F1F bytes(s)
0x0000000077815A4D (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0xD bytes(s)
0x0000000077A4B831 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
Traceback (most recent call last):
  File "C:\PF\Emscripten\emscripten\1.35.0\\emcc", line 1344, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "C:\PF\Emscripten\emscripten\1.35.0\tools\shared.py", line 1571, in emscripten
    call_emscripten(cmdline)
  File "C:\PF\Emscripten\emscripten\1.35.0\emscripten.py", line 1304, in _main
    temp_files.run_and_clean(lambda: main(
  File "C:\PF\Emscripten\emscripten\1.35.0\tools\tempfiles.py", line 64, in run_and_clean
    return func()
  File "C:\PF\Emscripten\emscripten\1.35.0\emscripten.py", line 1310, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "C:\PF\Emscripten\emscripten\1.35.0\emscripten.py", line 1208, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "C:\PF\Emscripten\emscripten\1.35.0\emscripten.py", line 102, in emscript
    start_funcs = backend_output.index(start_funcs_marker)
ValueError: substring not found
```

I tried compiling without any extra command line arguments given to `emcc` but to no avail. The same LLVM module compiles fine with `llc` from the LLVM tool-chain so I suspect that `fastcomp` might be the offender here. Any help would be appreciated.

**Comment by kripken** [comment]
I think this might be a limitation on 64-bit atomics - it happens even without the bitcast. @juj, can we even do 64-bit int atomics like this?

**Comment by juj** [comment]
We don't have proper support for 64-bit atomics, but those are (very slowly!) emulated via C functions in https://github.com/kripken/emscripten/blob/master/system/lib/pthread/library_pthread.c#L534 . Compiling 64-bit atomics in C/C++ side should work since they get routed to those C functions, but directly from LLVM IR, looks like it doesn't work by the test case above. If we can make the `atomicrmw add` route to calling `emscripten_atomic_add_u64` in LLVM side, I think this would be doable.

**Comment by kripken** [comment]
Ok, i'll look into it.

**Comment by kripken** [comment]
Ok, this should be fixed by those merged pulls.

**Comment by Maher4Ever** [comment]
Thank you for quickly addressing this problem. Building the latest incoming branch fails on my machine but I'll open a new issue for that.
