### ISSUE TITLE
Compile error when working with complex LLVM structs

### ISSUE THREAD

**Issue by Maher4Ever** [kripken/emscripten#4031]
Hello,

The following piece of LLVM code fails to compile (which I reduced to show the error):

```llvm
; ModuleID = 'generated.ll'
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

define i32 @comment_set({ i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] }* noalias nocapture %retptr, { i8*, i32 }** noalias nocapture readnone %excinfo, i8* noalias nocapture readnone %env, i8* %arg.new_value.0, i8* %arg.new_value.1, i64 %arg.new_value.2, i64 %arg.new_value.3, i8* %arg.new_value.4, i64 %arg.new_value.5.0, i64 %arg.new_value.6.0, i8* %arg._value.0, i8* nocapture readnone %arg._value.1, i64 %arg._value.2, i64 %arg._value.3, i8* nocapture readnone %arg._value.4, i64 %arg._value.5.0, i64 %arg._value.6.0) {
entry:
  %inserted.meminfo = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } undef, i8* %arg.new_value.0, 0
  %inserted.parent = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.meminfo, i8* %arg.new_value.1, 1
  %inserted.nitems = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.parent, i64 %arg.new_value.2, 2
  %inserted.itemsize = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.nitems, i64 %arg.new_value.3, 3
  %inserted.data = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.itemsize, i8* %arg.new_value.4, 4
  %.19 = insertvalue [1 x i64] undef, i64 %arg.new_value.5.0, 0
  %inserted.shape = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.data, [1 x i64] %.19, 5
  %.20 = insertvalue [1 x i64] undef, i64 %arg.new_value.6.0, 0
  %inserted.strides = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.shape, [1 x i64] %.20, 6

  store { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.strides, { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] }* %retptr, align 8
  ret i32 0
}
```

Compiling with `emcc generated.ll -o generated.js -s EXPORTED_FUNCTIONS="['_comment_set']" -s INVOKE_RUN=0 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s ASSERTIONS=1 -s SAFE_HEAP=1` results in the following output:

```
warning: Linking two modules of different data layouts: 'C:\Users\maher\.emscripten_cache\libc.bc' is 'e-p:32:32-i64:64-v128:32:128-n32-S128' whereas 'c:/users/maher/appdata/local/temp\tmpqr2j8f\gener
ated_0.o' is 'e-m:e-i64:64-f80:128-n8:16:32:64-S128'

warning: Linking two modules of different target triples: C:\Users\maher\.emscripten_cache\libc.bc' is 'asmjs-unknown-emscripten' whereas 'c:/users/maher/appdata/local/temp\tmpqr2j8f\generated_0.o' is
 'x86_64-pc-windows-msvc'

warning: Linking two modules of different data layouts: 'C:\Users\maher\.emscripten_cache\dlmalloc.bc' is 'e-p:32:32-i64:64-v128:32:128-n32-S128' whereas 'c:/users/maher/appdata/local/temp\tmpqr2j8f\g
enerated_0.o' is 'e-m:e-i64:64-f80:128-n8:16:32:64-S128'

warning: Linking two modules of different target triples: C:\Users\maher\.emscripten_cache\dlmalloc.bc' is 'asmjs-unknown-emscripten' whereas 'c:/users/maher/appdata/local/temp\tmpqr2j8f\generated_0.o
' is 'x86_64-pc-windows-msvc'

warning: incorrect target triple 'x86_64-pc-windows-msvc' (did you use emcc/em++ on all source files and not clang directly?)
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\incoming\\emcc", line 13, in <module>
    emcc.run()
  File "C:\Program Files\Emscripten\emscripten\incoming\emcc.py", line 1366, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "C:\Program Files\Emscripten\emscripten\incoming\tools\shared.py", line 1593, in emscripten
    call_emscripten(cmdline)
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 1625, in _main
    temp_files.run_and_clean(lambda: main(
  File "C:\Program Files\Emscripten\emscripten\incoming\tools\tempfiles.py", line 64, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 1631, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 1528, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 114, in emscript
    end_funcs = backend_output.rindex(end_funcs_marker)
ValueError: substring not found
```

The code compiles when I remove these 2 lines:

```llvm
  %.19 = insertvalue [1 x i64] undef, i64 %arg.new_value.5.0, 0
  %inserted.shape = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.data, [1 x i64] %.19, 5
  %.20 = insertvalue [1 x i64] undef, i64 %arg.new_value.6.0, 0
  %inserted.strides = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.shape, [1 x i64] %.20, 6
```

I'm not really sure why this happens. Is it because LLVM arrays inside structs are not supported? 

I'm working with the latest SDK from the incoming branch on a Win7 64-bit machine.

**Comment by kripken** [comment]
The triple is wrong. LLVM IR is not portable, so the IR has to be generated for the emscripten triple, and emcc will tell clang to do that when it invokes it. I guess this IR was generated in some other manner?

**Comment by Maher4Ever** [comment]
You are correct. This IR was generated by [Numba](https://github.com/numba/numba) from python code. However, would the IR be different if it was generated for the emscripten triple? All it does is creating a (complex) struct and storing it in an address. Also, only 2 instructions are used (`insertvalue` and `store`) which I believe are supported by emscripten.

**Comment by Maher4Ever** [comment]
I experimented more with the shipped version of clang with emscripten by comparing the resulting LLVM IR when toggling the --target=asmjs-unknown-emscripten option when compiling some C code. The only difference I noticed on my machine was that when enabling the emscripten triple, some types were defined as i32 instead of i64. So I manually changed the datalayout and triple of the LLVM IR above to mimic the ones generated by clang and tried emcc again. Unfortunately, the same error persists (without the warnings now ofc).

**Comment by kripken** [comment]
Ok, i thought this might be a 32/64 issue, but if you see the same problem when using 32-bit code with the emscripten triple, it might be something else. Can you provide a full 32-bit IR file (as small as possible) with a testcase?

**Comment by Maher4Ever** [comment]
Thank you for the quick response. Here is the same LLVM IR generated for the emscripten triple:

```llvm
; ModuleID = 'generated.ll'
target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

define i32 @comment_set({ i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] }* noalias nocapture %retptr, { i8*, i32 }** noalias nocapture readnone %excinfo, i8* noalias nocapture readnone %env, i8* %arg.new_value.0, i8* %arg.new_value.1, i64 %arg.new_value.2, i64 %arg.new_value.3, i8* %arg.new_value.4, i64 %arg.new_value.5.0, i64 %arg.new_value.6.0, i8* %arg._value.0, i8* nocapture readnone %arg._value.1, i64 %arg._value.2, i64 %arg._value.3, i8* nocapture readnone %arg._value.4, i64 %arg._value.5.0, i64 %arg._value.6.0) {
entry:
  %inserted.meminfo = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } undef, i8* %arg.new_value.0, 0
  %inserted.parent = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.meminfo, i8* %arg.new_value.1, 1
  %inserted.nitems = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.parent, i64 %arg.new_value.2, 2
  %inserted.itemsize = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.nitems, i64 %arg.new_value.3, 3
  %inserted.data = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.itemsize, i8* %arg.new_value.4, 4
  %.19 = insertvalue [1 x i64] undef, i64 %arg.new_value.5.0, 0
  %inserted.shape = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.data, [1 x i64] %.19, 5
  %.20 = insertvalue [1 x i64] undef, i64 %arg.new_value.6.0, 0
  %inserted.strides = insertvalue { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.shape, [1 x i64] %.20, 6

  store { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] } %inserted.strides, { i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64] }* %retptr, align 4
  ret i32 0
}
```

The error is still the same:

```
c:\Users\maher\Desktop>emcc generated.ll -o generated.js -s EXPORTED_FUNCTIONS="['_comment_set']" -s INVOKE_RUN=0 -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s ASSERTIONS=1 -s SAFE_HEAP=1
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\incoming\\emcc", line 13, in <module>
    emcc.run()
  File "C:\Program Files\Emscripten\emscripten\incoming\emcc.py", line 1366, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "C:\Program Files\Emscripten\emscripten\incoming\tools\shared.py", line 1593, in emscripten
    call_emscripten(cmdline)
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 1625, in _main
    temp_files.run_and_clean(lambda: main(
  File "C:\Program Files\Emscripten\emscripten\incoming\tools\tempfiles.py", line 64, in run_and_clean
    return func()
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 1631, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 1528, in main
    temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "C:\Program Files\Emscripten\emscripten\incoming\emscripten.py", line 114, in emscript
    end_funcs = backend_output.rindex(end_funcs_marker)
ValueError: substring not found
```

**Comment by kripken** [comment]
Ok, an assertions build errors on

````
While deleting: [1 x i64] %.19
Use still stuck around after Def is destroyed:  store [1 x i64] %.19, [1 x i64]* %retptr.index5, align 4
````

This looks like a limitation of the pnacl legalization passes, which we rely on here. In particular, the focus has been on 32-bit code from clang, and those `[1 x i64]` are not generated there.

Is there a way to make your compiler emit 32-bit code there? Or are 64-bit values actually needed?

**Comment by Maher4Ever** [comment]
I switched to a 32-bit version of Numba and it generated the following code:

```llvm
; ModuleID = '<string>'
target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

define i32 @comment_set({ i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] }* noalias nocapture %retptr, { i8*, i32 }** noalias nocapture readnone %excinfo, i8* noalias nocapture readnone %env, i8* %arg.new_value.0, i8* %arg.new_value.1, i32 %arg.new_value.2, i32 %arg.new_value.3, i8* %arg.new_value.4, i32 %arg.new_value.5.0, i32 %arg.new_value.6.0, i8* %arg._value.0, i8* nocapture readnone %arg._value.1, i32 %arg._value.2, i32 %arg._value.3, i8* nocapture readnone %arg._value.4, i32 %arg._value.5.0, i32 %arg._value.6.0) {
entry:
  %inserted.meminfo = insertvalue { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } undef, i8* %arg.new_value.0, 0
  %inserted.parent = insertvalue { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } %inserted.meminfo, i8* %arg.new_value.1, 1
  %inserted.nitems = insertvalue { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } %inserted.parent, i32 %arg.new_value.2, 2
  %inserted.itemsize = insertvalue { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } %inserted.nitems, i32 %arg.new_value.3, 3
  %inserted.data = insertvalue { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } %inserted.itemsize, i8* %arg.new_value.4, 4
  %.19 = insertvalue [1 x i32] undef, i32 %arg.new_value.5.0, 0
  %inserted.shape = insertvalue { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } %inserted.data, [1 x i32] %.19, 5
  %.20 = insertvalue [1 x i32] undef, i32 %arg.new_value.6.0, 0
  %inserted.strides = insertvalue { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } %inserted.shape, [1 x i32] %.20, 6

  store { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] } %inserted.strides, { i8*, i8*, i32, i32, i8*, [1 x i32], [1 x i32] }* %retptr, align 4
  ret i32 0
}
```

As you can see all the fields are 32-bit now, but unfortunately I still get the same error. I'm compiling this with a 64-bit version of the incoming branch. I'm gonna try building the 32-bit version of emscripten and trying again.

On a side note, I'm not really sure how emscripten works internally, but is it possible to "skip" the passes causing the error while compiling?

**Comment by kripken** [comment]
No, the passes can't be skipped - we rely on them to simplify the IR. Otherwise we can't handle it later.

Looks like the options here are

1. Improve that pnacl pass to handle this. If this is just the very specific case of embedded `[1 x i32]` (and not `i64`, and not another multiple than `1`), then it might not be much work. But I'm not familiar enough with the pass to tell.
2. Modify Numba to just emit `i32` instead of `[1 x i32]`.

**Comment by Maher4Ever** [comment]
Ok thank you for the help so far. I'll submit a request to Numba to see if the modification on their side is possible (although I must say I doubt it).

In the mean time, is there anyone within the emscripten team that might be able to help with the pnacl pass?

**Comment by kripken** [comment]
I don't think so. If I had free time I might look into it, but that's not likely. You could ask the pnacl team directly, but I don't think they are focused on such improvements either.

If this is important to you, it would probably be best to try to fix it yourself. I'm happy to help with guidance and answer questions while doing so.

**Comment by Maher4Ever** [comment]
@kripken thank you for offering to help with this. I'm still waiting for Numba's response. In the meantime, where should I start looking for the problem within the emscripten source code (ex. which file(s))? Also, how can I see the actual error emscripten encounters (the one you posted above) while compiling that LLVM IR instead of the wrapper error I get when using `emcc`?

**Comment by kripken** [comment]
Building with `EMCC_DEBUG=1` in the env should show you which tools are being run. This error happens during a call to `llc`, and you should see a stack trace showing where. In a debug build of LLVM, the stack trace should be very clear, otherwise it might be a little fuzzy, but should still say which file is relevant, which would be in `lib/Target/JSBackend/NaCl`.

**Comment by Maher4Ever** [comment]
I was able to fix the specific error I was getting by modifying the `static bool ExpandExtractValues(Function &Func)` method inside the `lib\Target\JSBackend\NaCl\ExpandStructRegs.cpp` file (lines 473-506). At the end of that method, as indicated by a comment, the inservalue instructions are deleted. It's not stated however why this is done. So I simply commented out the code removing the references and it worked! Here is the modified code (notice the commented out code): 

```c++
static bool ExpandExtractValues(Function &Func) {
  bool Changed = false;

  SmallVector<Instruction *, 10> ToErase;
  // Expand out all the extractvalue instructions.  Also collect up
  // the insertvalue instructions for later deletion so that we do not
  // need to make extra passes across the whole function.

  for (auto &BB : Func) {
    for (BasicBlock::iterator Iter = BB.begin(), E = BB.end(); Iter != E;) {
      Instruction *Inst = &*Iter++;
      if (ExtractValueInst *EV = dyn_cast<ExtractValueInst>(Inst)) {
        Changed |= ExpandExtractValue(EV, &ToErase);
      } else if (isa<InsertValueInst>(Inst)) {
        ToErase.push_back(Inst);
        Changed = true;
      }
    }
  }

  // Delete the insertvalue instructions.  These can reference each
  // other, so we must do dropAllReferences() before doing
  // eraseFromParent(), otherwise we will try to erase instructions
  // that are still referenced.
  //for (Instruction *I : ToErase) {
  //  I->dropAllReferences();
  //}

  //for (Instruction *I : ToErase) {
  //  I->eraseFromParent();
  //}

  return Changed;
}
```

The important thing to note here is that the problem is localized to this piece of code. I must say the developer must have had a good reason for deleting the instructions (there is even a comment about it so it's definitely intentional), but everything I tested worked. Still, I doubt this is the correct fix. Any ideas?

**Comment by Maher4Ever** [comment]
I was able to fix the specific error I was getting by modifying the `static bool ExpandExtractValues(Function &Func)` method inside the `lib\Target\JSBackend\NaCl\ExpandStructRegs.cpp` file (lines 473-506). At the end of that method, as indicated by a comment, the inservalue instructions are deleted. It's not stated however why this is done. So I simply commented out the code removing the references and it worked! Here is the modified code (notice the commented out code): 

```c++
static bool ExpandExtractValues(Function &Func) {
  bool Changed = false;

  SmallVector<Instruction *, 10> ToErase;
  // Expand out all the extractvalue instructions.  Also collect up
  // the insertvalue instructions for later deletion so that we do not
  // need to make extra passes across the whole function.

  for (auto &BB : Func) {
    for (BasicBlock::iterator Iter = BB.begin(), E = BB.end(); Iter != E;) {
      Instruction *Inst = &*Iter++;
      if (ExtractValueInst *EV = dyn_cast<ExtractValueInst>(Inst)) {
        Changed |= ExpandExtractValue(EV, &ToErase);
      } else if (isa<InsertValueInst>(Inst)) {
        ToErase.push_back(Inst);
        Changed = true;
      }
    }
  }

  // Delete the insertvalue instructions.  These can reference each
  // other, so we must do dropAllReferences() before doing
  // eraseFromParent(), otherwise we will try to erase instructions
  // that are still referenced.
  //for (Instruction *I : ToErase) {
  //  I->dropAllReferences();
  //}

  //for (Instruction *I : ToErase) {
  //  I->eraseFromParent();
  //}

  return Changed;
}
```

The important thing to note here is that the problem is localized to this piece of code. I must say the developer must have had a good reason for deleting the instructions (there is even a comment about it so it's definitely intentional), but everything I tested worked. Still, I doubt this is the correct fix. Any ideas?

**Comment by kripken** [comment]
`insertvalue` is not something that the backend can handle later - you should get a compiler error, I think. Unless some other pass happens to handle them, like they are dead code?

Worth seeing if things in the emscripten test suite pass after your change. Like `./tests/runner.py ALL.test_cases`.

**Comment by Maher4Ever** [comment]
Interesting. I don't think the code is dead in this case, however, maybe another pass handles them. I'm not sure how to verify this.

I just pulled a fresh copy of the latest incoming branch, built it with my changes, ran the tests as you described, and aside from a few warnings all of them passed. The tests I ran were inside `C:\Program Files\Emscripten\emscripten\incoming\tests`.

**Comment by kripken** [comment]
Worth making sure you have a build of LLVM with assertions enabled.

I would also check that this emits valid code, that is, make a testcase with this type of struct, that prints an output, and verify that it works ok. I suspect something must still be wrong, and this would catch that. If not, I can take a look at that file also.

**Comment by Maher4Ever** [comment]
I built LLVM with assertions enabled by opening the project in CMake and toggling the assertion checkbox, built a debug version then copied the results to `RelWithDebInfo` folder which my `emsdk` adds to the path. Here is `llc --version`'s output:

```
LLVM (http://llvm.org/):
  LLVM version 3.9.0svn
  DEBUG build with assertions.
  Built Jan 27 2016 (14:05:13).
  Default target: x86_64-pc-windows-msvc
  Host CPU: haswell

  Registered Targets:
    js     - JavaScript (asm.js, emscripten) backend
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

Then I ran the tests again from Emscripten's command line and they all still pass!

 I'm not that familiar with the LLVM IR to write a test case (all the LLVM IR I use is generated). However, I verified the validity of the generated JS code by Emscripten by calling the function defined in my first post here (`@comment_set`) using `Module.ccall` and I was able to extract the correct data I pass as an argument from the "struct" in JS. Here is what Emscripten emits for that LLVM IR:

```js
function _comment_set($retptr, $excinfo, $env, $arg$new_value$0, $arg$new_value$1, $arg$new_value$2, $arg$new_value$3, $arg$new_value$4, $arg$new_value$5$0, $arg$new_value$6$0, $arg$_value$0, $arg$_value$1, $arg$_value$2, $arg$_value$3, $arg$_value$4, $arg$_value$5$0, $arg$_value$6$0) {
 $retptr = $retptr | 0;
 $excinfo = $excinfo | 0;
 $env = $env | 0;
 $arg$new_value$0 = $arg$new_value$0 | 0;
 $arg$new_value$1 = $arg$new_value$1 | 0;
 $arg$new_value$2 = $arg$new_value$2 | 0;
 $arg$new_value$3 = $arg$new_value$3 | 0;
 $arg$new_value$4 = $arg$new_value$4 | 0;
 $arg$new_value$5$0 = $arg$new_value$5$0 | 0;
 $arg$new_value$6$0 = $arg$new_value$6$0 | 0;
 $arg$_value$0 = $arg$_value$0 | 0;
 $arg$_value$1 = $arg$_value$1 | 0;
 $arg$_value$2 = $arg$_value$2 | 0;
 $arg$_value$3 = $arg$_value$3 | 0;
 $arg$_value$4 = $arg$_value$4 | 0;
 $arg$_value$5$0 = $arg$_value$5$0 | 0;
 $arg$_value$6$0 = $arg$_value$6$0 | 0;
 var $$4$i = 0, $$4$i$i = 0, $retptr$index1 = 0, $retptr$index2 = 0, $retptr$index3 = 0, $retptr$index4 = 0, $retptr$index5 = 0, $retptr$index6 = 0, label = 0, sp = 0;
 sp = STACKTOP;
 $$4$i = ($arg$new_value$0 | 0) == (0 | 0);
 if (!$$4$i) {
  $$4$i$i = SAFE_HEAP_LOAD($arg$new_value$0 | 0, 4, 0) | 0 | 0;
  SAFE_HEAP_STORE($arg$new_value$0 | 0, $$4$i$i + 1 | 0 | 0, 4);
 }
 SAFE_HEAP_STORE($retptr | 0, $arg$new_value$0 | 0, 4);
 $retptr$index1 = $retptr + 4 | 0;
 SAFE_HEAP_STORE($retptr$index1 | 0, $arg$new_value$1 | 0, 4);
 $retptr$index2 = $retptr + 8 | 0;
 SAFE_HEAP_STORE($retptr$index2 | 0, $arg$new_value$2 | 0, 4);
 $retptr$index3 = $retptr + 12 | 0;
 SAFE_HEAP_STORE($retptr$index3 | 0, $arg$new_value$3 | 0, 4);
 $retptr$index4 = $retptr + 16 | 0;
 SAFE_HEAP_STORE($retptr$index4 | 0, $arg$new_value$4 | 0, 4);
 $retptr$index5 = $retptr + 20 | 0;
 SAFE_HEAP_STORE($retptr$index5 | 0, $arg$new_value$5$0 | 0, 4);
 $retptr$index6 = $retptr + 24 | 0;
 SAFE_HEAP_STORE($retptr$index6 | 0, $arg$new_value$6$0 | 0, 4);
 return 0;
}
```

What I noticed in the generated JS is that it seems the array of 1 element is being treated as if it's the element inside; strange...

**Comment by kripken** [comment]
Thanks for the info. I looked into this based on that, and I believe what you are doing is valid. The problem here is that there are "recursive" insertvalue instructions, like `%.19` (itself an insertvalue, and fed into an insertvalue). The PNaCl pass assumes it is safe to clean them all up, but it must be done recursively. And that is in fact done properly by the DCE pass later.

The one risk here is increasing compile time, as it leaves around some dead code through other passes. We'd need to measure this.

In any case, after DCE, all the code is fine - no insertvalues are left, and there are some `[1 x 32]` remaining but only in getelementptrs, which is fine, as we can handle those.

Do you want to open a PR with your change and we'll continue there?

**Comment by Maher4Ever** [comment]
Done.

**Comment by kripken** [comment]
Good, thanks. Let's close this and focus on that pull.
