### ISSUE TITLE
'cxxabi.h' file not found

### ISSUE THREAD

**Issue by chepilot** [kripken/emscripten#4038]
Hi, 
I am experimenting port openCascade:

first configure it with:
`emcmake cmake`

them make:
`emmake make -j8 -I/<PATH TO EMSDK>/emscripten/1.35.0/system/lib/libcxxabi/include/`

It gives me:

```
In file included from /Users/rz/Documents/oce/oce/test/gtest-1.7.0/src/gtest-all.cc:39:
In file included from /Users/rz/Documents/oce/oce/test/gtest-1.7.0/include/gtest/gtest.h:58:
In file included from /Users/rz/Documents/oce/oce/test/gtest-1.7.0/include/gtest/internal/gtest-internal.h:63:
/Users/rz/Documents/oce/oce/test/gtest-1.7.0/include/gtest/internal/gtest-type-util.h:52:12: fatal error: 
      'cxxabi.h' file not found
#  include <cxxabi.h>
           ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make[2]: *** [test/CMakeFiles/gtest.dir/gtest-1.7.0/src/gtest-all.cc.o] Error 1
make[1]: *** [test/CMakeFiles/gtest.dir/all] Error 2
```

Even I include the folder where cxxabi.h resides with 
`-I/<PATH TO EMSDK>/emscripten/1.35.0/system/lib/libcxxabi/include/`
Same fatal error still occurs. 
I am using the portable version of emscripten on both mac and windows.
It bugs me for a while, wondering if there a solution for this. Thanks.

**Comment by juj** [comment]
Hmm, I think you could try `-isystem/<PATH TO EMSDK>/emscripten/1.35.0/system/lib/libcxxabi/include/`, since the #include is via angle brackets, or try doing `#include "cxxabi.h"`.

We had a discussion some time ago whether we should have the libcxxabi in default isystem includes, but like you are seeing, it is currently not. I wonder if we have any reason not to have this path in defauly `-isystem` #include. @kripken, what do you think ?

**Comment by kripken** [comment]
A risk factor is that I'm not sure everything in the header works or not, so it might surprise people with failures. We'd need to do testing first.

**Comment by chepilot** [comment]
@juj Thanks for your comment. I first tried to use `#include "cxxabi.h"` instead of `#include <cxxabi.h>` it still shows header file not found.

Then I tried `emmake make -isystem/<PATH TO EMSDK>/emscripten/1.35.0/system/lib/libcxxabi/include/` but `-isystem` is not a valid option.
I am wondering if possible I am somehow not using clang?

I tried `emcmake cmake` and method described in `Emscripten.cmake` both resulted the same.

**Comment by juj** [comment]
`-isystem` is a parameter to `emcc` and `em++`, and not to `make` or `cmake`. You need to configure the build script to add that directive. Try adapting the build system to add that flag. In some build systems, it is possible to use an environment variable `CFLAGS` or `CXXFLAGS` to add custom directives to the compiler, see e.g. https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html.
