### ISSUE TITLE
change log no longer updated

### ISSUE THREAD

**Issue by soliton4** [kripken/emscripten#4048]
the change log seems to be stuck at v1.34.12: 10/13/2015

there have been a lot of updates since then and even a new version step 1.35

any chance to find out what those changes are about?

**Comment by juj** [comment]
The changelog is updated with the same cadence that we do releases of the master branch. There is a release due soon, so I'll ping here once that is updated.

**Comment by soliton4** [comment]
thanks for clearing that up
