### ISSUE TITLE
polyfill simd

### ISSUE THREAD

**Issue by soliton4** [kripken/emscripten#4051]
there is a simd polyfill available
https://github.com/tc39/ecmascript_simd

a pragmatic solution would be to always activate simd by default
and include the polyfill in the module code.

**Comment by juj** [comment]
I'm not sure what this bug report specifically focuses on? We are using the polyfill, with manual modifications to add support for `Float64x2` and `Bool64x2`, see here: https://github.com/kripken/emscripten/blob/incoming/src/ecmascript_simd.js. SIMD is not activated by default, since it can possibly increase code size, which developers might not like ("don't pay for what you don't use")

**Comment by soliton4** [comment]
oh it was not meant as a bugreport.
more like a feature request.

i activated simd once for experimental reasons and i got the js error that simd was not defined.
maybe thats a bug then

emscripten is building a lot of libraries into the module regardless if they are needed or not.
filesystem for example.
you have to manually disable it.
so i didnt think the "dont pay for what you dont use" policy was applied to emscripten builds

**Comment by juj** [comment]
Not sure then. Do you have steps to repro?

**Comment by juj** [comment]
Closing, looks like this should be covered. If you do have issues with SIMD in the latest version which has a number of additions for SSE3, SSSE3 and SSE4.1 support as well, feel free to open a new item.

**Comment by sourceskyboxer** [comment]
Hello I have biiiig problem with simd :( I have tried but no success...

How do I fix? I t throws always error like emscripten.py
```
emcc Export/emscripten/obj/Main.cpp -o Export/emscripten/obj/Main.o
emcc Main.o /home/sourceskyboxer/lime/ndll/Emscripten/liblime.a libApplicationMain.a -o ApplicationMain.o
emcc ApplicationMain.o -s ASM_JS=1 -s NO_EXIT_RUNTIME=1 -s USE_SDL=2 -lpthread -lopenal --preload-file assets -o ../bin/DisplayingABitmap.js
Traceback (most recent call last):
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/emcc.py", line 3062, in <module>
    sys.exit(run())
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/emcc.py", line 1778, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/tools/shared.py", line 2268, in emscripten
    emscripten._main(cmdline)
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/emscripten.py", line 2228, in _main
    return temp_files.run_and_clean(lambda: main(
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/emscripten.py", line 2233, in <lambda>
    DEBUG=DEBUG,
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/emscripten.py", line 2159, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/emscripten.py", line 86, in emscript
    glue, forwarded_data = compiler_glue(metadata, libraries, compiler_engine, temp_files, DEBUG)
  File "/home/sourceskyboxer/emsdk/emscripten/1.38.12/emscripten.py", line 215, in compiler_glue
    assert not (metadata['simd'] and shared.Settings.WASM), 'SIMD is used, but not supported in WASM mode yet'
AssertionError: SIMD is used, but not supported in WASM mode yet
```
I feel that it blocks again again again again again.. I have tried tried. I am broken at floor.
