### ISSUE TITLE
WebGL off the main thread

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4052]
There is progress towards WebGL off the main thread, see [this blogpost](https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/) by @nickdesaulniers.

I started to work on this a while back, before there was browser support to test against. I don't have time now to return to it, but maybe someone else wants to? My work is in a branch called `webgl-in-worker`, in [two commits](https://github.com/kripken/emscripten/commits/webgl-in-worker), which might be a good starting point.

**Comment by juj** [comment]
This was implemented in #4412, closing.
