### ISSUE TITLE
Boolean has value of 191?

### ISSUE THREAD

**Issue by zwarmapapa** [kripken/emscripten#4054]
I have a boolean like this:

    bool Done = false;

Then I got two functions, like this:

    void Success(const TArray<uint8> Bytes)
    {
    	UE_LOG(LogBlueprintUserMessages, Log, TEXT(" SUCCESS a %d "), Done);
    	if(!Done)
    	{
    		UE_LOG(LogBlueprintUserMessages, Log, TEXT(" SUCCESS b %d "), Done);
    		bSuccess = true;
    		ResponseBytes = Bytes;
    		Done = true;
    	}
    }
    
    void Failed()
    {
    	UE_LOG(LogBlueprintUserMessages, Log, TEXT(" FAILED a %d "), Done);
    	if(!Done)
    	{
    		UE_LOG(LogBlueprintUserMessages, Log, TEXT(" FAILED b %d "), Done);
    		bSuccess = false;
    		Done = true;
    	}
    }

When Success is called, the Done boolean is supposed to be false, but instead it is 191? 
After that, Failed is called, and then Done is indeed false (it has a value of 0 then). 
I have no idea what's going on. 
Halp pls.

**Comment by kripken** [comment]
Booleans are often implemented as integers. If it contains an invalid value like 191, perhaps you are reading uninitialized memory? Or something else corrupted memory?

It usually helps to reduce this to as small a standalone testcase as you can, then the problem often becomes easy to figure out. Also useful are the [debugging tips](http://kripken.github.io/emscripten-site/docs/porting/Debugging.html).

**Comment by zwarmapapa** [comment]
I think I know a bit more now. 

The Success function is called by a pointer to this object, whereas Failed is called from within this object. 

I now expect the pointer to be incorrect, which is weird, since I just store it in a TMap, and then later retrieve it and access it. 

What is even weirder is that on a Win64 build it just works as expected, boolean Done is false in Success, not 191 but 0. 

*After putting a bit more time into this*

Turns out, doing this (code underneath) works fine on Windows, but on HTML5 it immediately invalidates the pointer or something:

    TMap<int32, FLowEntrySocketConnectionFunctionCallAction*> FunctionCalls; // initialized earlier
    
    FLowEntrySocketConnectionFunctionCallAction** FunctionCallPointer = FunctionCalls.Find(ReceivingFunctionCallId);
    FunctionCalls.Remove(ReceivingFunctionCallId); // this line right here
    if(FunctionCallPointer != nullptr)
    {
    	FLowEntrySocketConnectionFunctionCallAction* FunctionCall = *FunctionCallPointer;
    	if(FunctionCall != nullptr)
    	{
    		FunctionCall->Success(ReceivingPacket);
    	}
    }

After changing it to this, it works as expected:

    TMap<int32, FLowEntrySocketConnectionFunctionCallAction*> FunctionCalls; // initialized earlier
    
    FLowEntrySocketConnectionFunctionCallAction** FunctionCallPointer = FunctionCalls.Find(ReceivingFunctionCallId);
    if(FunctionCallPointer != nullptr)
    {
    	FLowEntrySocketConnectionFunctionCallAction* FunctionCall = *FunctionCallPointer;
    	if(FunctionCall != nullptr)
    	{
    		FunctionCall->Success(ReceivingPacket);
    	}
      	FunctionCalls.Remove(ReceivingFunctionCallId);
    }

Well, that's one bug less. 

Thanks for the halp, wouldn't have made sense of it otherwise.
