### ISSUE TITLE
Unable to use port of SDL2 SDL_ttf (USE_SDL_TTF=2)

### ISSUE THREAD

**Issue by GGAlanSmithee** [kripken/emscripten#4063]
Running `emcc --show-ports` yields (amongst other) `SDL2_ttf (USE_SDL_TTF=2; zlib license)`, indicating that there is an available port of SDL_ttf for SDL2, which is great.

Trying to `#include <SDL2/SDL_ttf.h>` however, produces the error `fatal error: 'SDL2/SDL_ttf.h' file not found`. Using `#include <SDL/SDL_ttf.h>` works, but to me this is a bit strange since it's inconsistent with how SDL itself as well as SDL_image is included, which is done with `<SDL2/*.h>`.

Actually, `#include <SDL/SDL_ttf.h>` probably just includes the original (none SDL2) SDL_ttf since it works even when not building with `USE_SDL_TTF=2`.

Unless I've done something wrong (which is very possible) there is something wrong with the port of SDL2/SDL_ttf or the documentation of how to use it (`emcc --show-ports`)

**Comment by Daft-Freak** [comment]
I think the correct `#include` line is `#include <SDL_ttf.h>` which works for SDL 1 and 2.

**Comment by GGAlanSmithee** [comment]
@Daft-Freak I see! Thanks for the fast reply.

I interpret this as `#include <SDL2/SDL*.h>` is overqualification, and that `#include <SDL*.h> is enough, with the argument `-s USE_SDL_*=2` assuring the right lib is linked, is this correct?

**Comment by Daft-Freak** [comment]
Yes, `USE_SDL=2` sets up the include path too.

**Comment by GGAlanSmithee** [comment]
Thanks for the varification!
