### ISSUE TITLE
emscripten_trace_report_memory_layout should be exported automatically

### ISSUE THREAD

**Issue by palant** [kripken/emscripten#4064]
If I compile my code with `--tracing` and `-s ALLOW_MEMORY_GROWTH=1` parameters the function `enlargeMemory()` will call `_emscripten_trace_report_memory_layout()`. However, this function doesn't exist by default - my C++ code doesn't call it so the compiler optimizes it away. Adding `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE='["emscripten_trace_report_memory_layout"]'` parameter works but this shouldn't be necessary.

**Comment by kripken** [comment]
Thanks for filing, fixed on incoming.
