### ISSUE TITLE
test_sse2_full breakage

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4068]
On `default, asm2`, and others, I see `test_sse2_full` fail on incoming,

````
+missing function: emscripten_int16x8_shiftRightByScalar
+-1

+/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:1489
+      throw ex;
+            ^
+abort(-1) at Error
+    at jsStackTrace (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:2559:13)
+    at stackTrace (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:2576:22)
+    at abort (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:50354:44)
+    at _emscripten_int16x8_shiftRightByScalar (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:7110:82)
+    at __Z10test_shiftv [test_shift()] (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:23646:39)
+    at _main (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:42856:3)
+    at Object.asm._main (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:50098:19)
+    at Object.callMain (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:50219:30)
+    at doRun (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:50277:60)
+    at run (/tmp/emscripten_test_default_hIiDGx/src.cpp.o.js:50291:5)
+
````

**Comment by juj** [comment]
Hmm, can you double-check this? On the bots this test passes and also locally on my OS X and Windows systems the build ok. If LLVM was not built up to date with the pull request https://github.com/kripken/emscripten-fastcomp/pull/133, then the above error would make sense. Also, if running in SpiderMonkey, it must recent enough to have `SIMD.int16x8.shiftRightByScalar`, perhaps in older SpiderMonkey if that doesn't exist, it could generate the above error.

**Comment by kripken** [comment]
Double-checked on latest mozilla-inbound, latest emscripten, latest fastcomp (including merge of #133), cache cleared.

**Comment by kripken** [comment]
(And the problem still exists.)

**Comment by juj** [comment]
I was looking at this today, and authored #4075 and https://github.com/kripken/emscripten-fastcomp/pull/135, but I could not find the root cause for this. Let's see nevertheless what the situation looks like after those fixes?

**Comment by kripken** [comment]
Sure.

**Comment by juj** [comment]
I wonder if the issue might be related to the following I am seeing, which I'm not sure what causes this. STR:

    #include <emscripten/vector.h>
    #include <stdio.h>

    int main()
    {
        int32x4 vec = emscripten_int32x4_set(1, 0, 1, 4);
        printf("%d %d %d %d\n", emscripten_int32x4_extractLane(vec, 0), emscripten_int32x4_extractLane(vec, 1), emscripten_int32x4_extractLane(vec, 2), emscripten_int32x4_extractLane(vec, 3));
    }

build with `em++ a.cpp -o a.js -O2 -g2`. This generates the following code fragments in the output file:

    function _emscripten_int32x4_set() {
     Module["printErr"]("missing function: emscripten_int32x4_set");
     abort(-1);
    }

    Module.asmLibraryArg = {
    ....
         "_emscripten_int32x4_set": _emscripten_int32x4_set,
    ....
    };
    var _emscripten_int32x4_set=env._emscripten_int32x4_set;

but that kind of import should not exist at all, since `emscripten_int32x4_set()` is handled by a call handler at https://github.com/kripken/emscripten-fastcomp/blob/incoming/lib/Target/JSBackend/CallHandlers.h#L915. The main function of the generated code is nevertheless correct and reads

    function _main() {
     var i1 = 0, i2 = 0, I43 = SIMD_Int32x4(0, 0, 0, 0), i4 = 0, i5 = 0, i6 = 0, i7 = 0;
     i1 = STACKTOP;
     STACKTOP = STACKTOP + 16 | 0;
     i2 = i1;
     I43 = SIMD_Int32x4_check(SIMD_Int32x4(1, 0, 1, 4));
     i4 = SIMD_Int32x4_extractLane(I43, 0) | 0;
     i5 = SIMD_Int32x4_extractLane(I43, 1) | 0;
     i6 = SIMD_Int32x4_extractLane(I43, 2) | 0;
     i7 = SIMD_Int32x4_extractLane(I43, 3) | 0;
     HEAP32[i2 >> 2] = i4;
     HEAP32[i2 + 4 >> 2] = i5;
     HEAP32[i2 + 8 >> 2] = i6;
     HEAP32[i2 + 12 >> 2] = i7;
     _printf(128, i2) | 0;
     STACKTOP = i1;
     return 0;
    }

i.e. no `_emscripten_int32x4_set(...)` as expected (nor is there a `_emscripten_int32x4_extractLane(...)` either). The same kind of "missing function" pattern occurs for other SIMD intrinsic functions as well.

As another example with the `emscripten_int16x8_shiftRightByScalar`, compiling the following:

    #include <emscripten/vector.h>
    #include <stdio.h>

    int main()
    {
        int16x8 vec = emscripten_int16x8_shiftRightByScalar(emscripten_int16x8_set(1, 2, 3, 4, 5, 6, 7, 8), 1);
        printf("%d %d %d %d %d %d %d %d\n", emscripten_int16x8_extractLane(vec, 0), emscripten_int16x8_extractLane(vec, 1), emscripten_int16x8_extractLane(vec, 2), emscripten_int16x8_extractLane(vec, 3), emscripten_int16x8_extractLane(vec, 4), emscripten_int16x8_extractLane(vec, 5), emscripten_int16x8_extractLane(vec, 6), emscripten_int16x8_extractLane(vec, 7));
    }

with `em++ a.cpp -o a.js -O? -g2`, I get a redundant

      function _emscripten_int16x8_shiftRightByScalar() {
      Module['printErr']('missing function: emscripten_int16x8_shiftRightByScalar'); abort(-1);
      }

being generated in the code, but that function is not referenced anywhere in the compiled code. Are you able to get that function be called with some specific set of compiler flags? (`-O0`, `-O1` or `-O2` seem to all be ok).

**Comment by kripken** [comment]
I don't think that's related, we just report it incorrectly as undefined and end up emitting that extra stub. It just wastes space. But worth fixing, looking into this now.

**Comment by kripken** [comment]
Opened https://github.com/kripken/emscripten-fastcomp/pull/136 for that.

**Comment by kripken** [comment]
`test_sse2_full` now looks broken on the bots as well, `SIMD_Int16x8_fromUint16x8Bits is not defined` etc.

**Comment by juj** [comment]
Oh indeed. That breakage was introduced by https://github.com/kripken/emscripten-fastcomp/commit/8f24899aab01dccdbdbc1b8f301e6aa7b78c259c and fixed now by commit https://github.com/kripken/emscripten-fastcomp/commit/bb2d997b857829943c4132721c9e6b051f055aa7.

**Comment by kripken** [comment]
Looks good now.
