### ISSUE TITLE
Exception raised in browser.test_zzz_pthread_create unit test

### ISSUE THREAD

**Issue by pgarnero06** [kripken/emscripten#4073]
Hi.

When I run  the "browser.test_zzz_pthread_create unit test, with firefox nightly build (firefox-47.0a1.en-US.linux-x86_64), I get the folloiwng exception:
ReferenceError: SharedInt8Array is not defined (test.js:1289).

Basically, it seems that all pthread related tests are broken. 

Here is my installed version:
$ em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.35.0 (commit 42fb486c53d627b203b77af6e5d0c088c0ad03ad)

Am I missing something ?

Cheers,

Pierre

**Comment by kripken** [comment]
The array names were updated. You need a newer emscripten, best to use the incoming branch.

**Comment by pgarnero06** [comment]
Thanks a lot. Works very well with 1.35.22.

**Comment by kripken** [comment]
Great!

We'll hopefully merge to master in a week or two, but for now incoming should be fine to use.
