### ISSUE TITLE
Anything compiled with SIMD=1 fails in Microsoft Edge

### ISSUE THREAD

**Issue by GordoRank** [kripken/emscripten#4079]
I have compiled several projects and in all of them have found a significant speed boost by enabling auto-vectoring via ```SIMD=1```.  The resulting code works perfectly in Chrome/Firefox.

However, anything compiled with ```SIMD=1``` completely fails in the latest build of Microsoft Edge.  I am using Windows 10 Insider build 1427, so it is quite possible that MS introduced a bug very recently, but I am unable to test an older version.

The error I get when any SIMD Emscripten code is run is:

```Unable to get property 'hasOwnProperty' of undefined or null reference```

**Comment by asRIA** [comment]
Do you have some stack trace?

**Comment by GordoRank** [comment]
Here's some more information i got from looking through the polyfill javascript as it gets spat out by emscripten.

The error occurs here, in the first section ```// Install each prototype function on each SIMD prototype.``` on the ```if(!proto.hasOwnProperty(name))``` line: 
```
  allTypes.forEach(function(type) {
            // Install each prototype function on each SIMD prototype.
            var simdFn = type.fn;
            var proto = simdFn.prototype;
            for (var name in prototypeFns) {
                if (!proto.hasOwnProperty(name))
                    proto[name] = prototypeFns[name](type);
            }
            // Install regular functions.
            type.fns.forEach(function(name) {
                if (typeof simdFn[name] === "undefined")
                    simdFn[name] = simdFns[name](type);
            });
            // Install 'fromTIMD' functions.
            if (type.from) {
                type.from.forEach(function(fromType) {
                    var name = "from" + fromType.name;
                    var toType = type;  // pull type into closure.
                    if (typeof type.fn[name] === "undefined") {
                        type.fn[name] =
                            function(a) { return simdFrom(toType, fromType, a); }
                    }
                });
            }
            // Install 'fromTIMDBits' functions.
            if (type.fromBits) {
                type.fromBits.forEach(function(fromType) {
                    var name = "from" + fromType.name + "Bits";
                    var toType = type;  // pull type into closure.
                    if (typeof type.fn[name] === "undefined") {
                        type.fn[name] =
                            function(a) { return simdFromBits(toType, fromType, a); }
                    }
                });
            }
        });

```

To clarify the line ```var proto = simdFn.prototype;``` never appears to be defined.

**Comment by kripken** [comment]
Looks like an upstream problem in the SIMD.js polyfill which we bundle. Can you please file it at https://github.com/tc39/ecmascript_simd ?

**Comment by GordoRank** [comment]
Done...
