### ISSUE TITLE
Pth not supported

### ISSUE THREAD

**Issue by Maeiky** [kripken/emscripten#4086]
Include a precompiled header file not work in emscripten :

Generate Pch:
 -std=c++11 -m32 -fno-exceptions -O2 -x c++-header xxx.h -o xxx.pch 

Compile Obj:
-std=c++11 -m32 -fno-exceptions -O2  -c xxx.cpp -include-pch xxx.pch -o xxx.o 

 I have this error :
ERROR:root:xxx.pch: **Input file has an unknown suffix, don't know what to do with it!**

**Comment by kripken** [comment]
emcc supports precompiled headers with suffix `gch`, which I thought was the standard gcc suffix, but that might have been wrong?

**Comment by Maeiky** [comment]
Same error with gch,
gch is for gcc, but emscripten is based on Clang!?
[http://clang.llvm.org/docs/UsersManual.html](http://clang.llvm.org/docs/UsersManual.html)
`To generate a PCH file using Clang, one invokes Clang with the -x <language>-header option. This mirrors the interface in GCC for generating PCH files:

$ gcc -x c-header test.h -o test.h.gch
$ clang -x c-header test.h -o test.h.pch
`
[http://clang.llvm.org/docs/PCHInternals.html](http://clang.llvm.org/docs/PCHInternals.html)
[http://clang.llvm.org/docs/PTHInternals.html](http://clang.llvm.org/docs/PTHInternals.html

**Comment by kripken** [comment]
`gch` is still the default clang emits, if you run `clang -x c-header test.h -c` (i.e. if you don't tell it the output name).

Looking into this more carefully, the core issue is that we didn't recognize the `-include-pch` argument. Added support for that, and verified it works with both `gch` and `pch`.

**Comment by kripken** [comment]
The one thing I didn't do is anything with `pth` files - is that important as well?

**Comment by Maeiky** [comment]
Yes, for future versions of Clang> = 3.9. This will provide a more flexible precompilation of headers.
Thanks

**Comment by kripken** [comment]
Ok, reopening for pth.

**Comment by jenvannier** [comment]
When I run 
em++ -Xclang -print-stats -c -xc++-header file.h
I get: 
root:file.h.gch: Input file has an unknown suffix, don't know what to do with it!

Am I doing something wrong or is the error somewhere else?

**Comment by froydnj** [comment]
I don't know if PTH files are worth supporting.  The official clang user's manual doesn't mention PTH files at all, preferring to focus on PCH files instead.  (PTH files are mentioned in the in design documents, but nowhere else AFAICS.)  The clang driver doesn't recognize `-include-pth`; that's a cc1 option, so you need to pass it down with `-Xclang`...but that confuses `emcc`'s extraction of input files.  WDYT, @kripken, should we just close this?

**Comment by kripken** [comment]
Sounds reasonable to close, yeah.

**Comment by pouyarb** [comment]
hello
built with qmake and mingw 13:
emcc -c -Xclang -include-pch -Xclang wasm\z_token_wasm.js.pch\c.pch -std=c11 -O2 -Wall -Wextra -s ALLOW_MEMORY_GROWTH=1 -Dzf_using_z_token_v4 -Dzf_e_core -Dzf_use_pana_keya -Dzf_using_z_token_v4 -Dzf_using_cipher_lib_v6 -Dzf_custom_hash_exists -Dzf_using_z_token_v4 -DZ_32 -DZ_LIN -D__UNIX__ -Dzf_use_epass -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I..\z_tokensrc -I. -I..\..\include -IC:\boost\boost_1_80_0 -I/home/boost/boost_1_80_0/ -I. -I./../Source_other/lib/panakey -IC:\Qt\Qt5.15\5.15.2\wasm_32\include -IC:\Qt\Qt5.15\5.15.2\wasm_32\include\QtNetwork -IC:\Qt\Qt5.15\5.15.2\wasm_32\include\QtCore -I/.emscripten_ports/openssl/include -IC:\Qt\Qt5.15\5.15.2\wasm_32\mkspecs\wasm-emscripten -o wasm\global.obj ..\z_tokensrc\unimate\global.c

i have error:
shared:ERROR: wasm\z_token_wasm.js.pch\c.pch: Input file has an unknown suffix, don't know what to do with it!

**Comment by sbc100** [comment]
@pouyarb what version of emscripten are you using?   The error message you getting looks like it was removed in #10560 (2020).. but the way the error is presented (with `shared:ERROR` at the start) make it look like this version goes back to before 2017.   That error reporting for that message back in #5710 (2017).. so it looks like you are using 1.37.23 or older?

**Comment by pouyarb** [comment]
Im using version 1.39.7 due to qt requirements. I can not update emscripten

**Comment by sbc100** [comment]
In that case maybe you could petition the qt folks to update their emscripten requirements, since this issue has already been fixed on the emscripten side.

**Comment by pouyarb** [comment]
thank you for your help. could you tell me which commit have fixed this issue?

**Comment by sbc100** [comment]
#10560 looks like a likely candidate since it removes the error in question.    For that you would need version 1.40.1 or above.  But honestly I wouldn't recommend upgrading to anything other than the very latest release (3.1.42).
