### ISSUE TITLE
Missing SSE intrinsic: _mm_set_sd

### ISSUE THREAD

**Issue by bjacob** [kripken/emscripten#4089]
SSE2 supports not only float but also double ; not only SIMD but also scalar arithmetic.

_mm_set_sd loads a 'double' value into the first half of a SSE register. It's not currently supported by Emscripten.

Testcase:

#include <xmmintrin.h>

int main() {
  double x = 0;
  _mm_set_sd(x);
}

Result:

$ em++ ~/vrac/missing-set-sd.cc -Wextra -msse2
/usr/local/google/home/benoitjacob/vrac/missing-set-sd.cc:5:3: error: use of undeclared identifier '_mm_set_sd'; did you mean
      '_mm_set_ss'?
  _mm_set_sd(x);
  ^~~~~~~~~~
  _mm_set_ss
/usr/local/google/home/benoitjacob/Downloads/emsdk_portable/emscripten/master/system/include/emscripten/xmmintrin.h:35:1: note: 
      '_mm_set_ss' declared here
_mm_set_ss(float __w)
^
1 error generated.

**Comment by juj** [comment]
`_mm_set_sd` was added in https://github.com/kripken/emscripten/commit/30936c07f7fb1d8983596e90922adf2c3f9ee582 in June 2015. The formatting is off in your test case, but perhaps you are missing the SSE2 `#include <emmintrin.h>` since the error message refers to `xmmintrin.h`?

**Comment by bjacob** [comment]
D'oh! Thanks, I had indeed the wrong header !
