### ISSUE TITLE
SIMD polyfill is impossibly slow

### ISSUE THREAD

**Issue by bjacob** [kripken/emscripten#4090]
https://kripken.github.io/emscripten-site/docs/porting/simd.html explains that

"For backwards compatibility, all generated SIMD code will embed a polyfill for all SIMD.js instructions. This allows Emscripten compiled pages to be run even on browsers that don’t have SIMD support available. However, due to the nature of the interoperation with asm.js, the SIMD.js polyfill will likely be much slower than scalar execution, so it is best to primarily target browsers that do support SIMD.js in hardware."

I would argue that this polyfill is so slow that it is no different than crashing. Below is a testcase that is a benchmark of matrix multiplication.

Firefox: enabling -msse2 causes performance to go from 2.6 GFlop/s (scalar) to about 0.0015,  so a > 1000x slowdown. Obviously, this triggers the slow-script dialog.

Chrome: enabling -msse2 causes this benchmark to never display anything in the console; after 30 seconds or so, there is the slow-script dialog.

Testcase:

```
#include <iostream>

#include <unistd.h>
#include <sys/time.h>

#include <Eigen/Core>

using Eigen::MatrixXf;

double current_time_in_seconds() {
  timeval t;
  gettimeofday(&t, nullptr);
  return t.tv_sec + 1e-6 * t.tv_usec;
}

// Make this function non-inlinable to prevent the compiler from optimizing
// away repeated calls.
__attribute__((noinline))
void do_one_benchmark_iter(const MatrixXf& a, const MatrixXf& b, MatrixXf* c) {
  *c = a * b;
}

double benchmark_sgemm_gflops(int size) {
  // Minimum duration for this benchmark to run. If the workload finishes
  // sooner, we retry with double the number of iterations.
  static const double min_benchmark_time_in_seconds = 0.1;

  MatrixXf a = MatrixXf::Random(size, size);
  MatrixXf b = MatrixXf::Random(size, size);
  MatrixXf c = MatrixXf::Zero(size, size);

  uint64_t iters_at_a_time = 1;

  while (true) {
    double t_start = current_time_in_seconds();
    for (uint64_t i = 0; i < iters_at_a_time; i++) {
      do_one_benchmark_iter(a, b, &c);
    }
    double t_end = current_time_in_seconds();
    double elapsed = t_end - t_start;
    if (elapsed > min_benchmark_time_in_seconds) {
      // Standard GEMM algorithm on NxN matrices requires 2N^3 operations
      double gflop_per_iter = 2.0 * size * size * size * 1e-9;
      return gflop_per_iter * iters_at_a_time / elapsed;
    }
    iters_at_a_time *= 2;
  }
}

int main() {
  for (int size = 16; size <= 1024; size *= 2) {
    std::cout << "Muliplying " << size << "x" << size << " matrices at " <<
        benchmark_sgemm_gflops(size) << " GFlop/s" << std::endl;
  }
}
```

Compile against the Eigen library (headers only, at http://eigen.tuxfamily.org ) :

em++ ~/vrac/eigen-benchmark.cc -I $HOME/eigen -O3 --std=c++11 -Wextra -o e.html -s TOTAL_MEMORY=30000000 -msse2

**Comment by juj** [comment]
This is known and discussed in #3783, where the concensus is that it might be more feasible to polyfill without performance loss when wasm is available. The preference here is to add a build mode that removes the SIMD polyfill, since it is not useful. If someone wants to implement a C side scalar version of all SSE intrinsics, feel free to champion and submit a pull request.
