### ISSUE TITLE
Webrtc start point

### ISSUE THREAD

**Issue by derofim** [kripken/emscripten#4094]
Hello, im trying to create simple networking with emscripten.
- Can i use WebRTC now with emscripten (Most tests marked "WebRTC support is not up to date")? 
- Where to start with networking and what libraries i can use (I hope cross platform solution exists, not Unix-specific)?

**Comment by juj** [comment]
Emscripten implements the BSD sockets api (https://en.wikipedia.org/wiki/Berkeley_sockets) with a rather large number of restrictions. This support backs on WebSockets (and not WebRTC). There used to be an implementation of a WebRTC backend to BSD sockets api, but it got out of date and was removed.

Naturally you can also implement networking by handwriting JavaScript, and performing interop calls between JS and C/C++ code to bridge your WebRTC networking code into the C++ land.
