### ISSUE TITLE
Non-ASCII characters in file paths don't work with file_packager.py on Windows

### ISSUE THREAD

**Issue by TannerRogalsky** [kripken/emscripten#4100]
https://github.com/TannerRogalsky/love.js/issues/14

I've reproduced this as well. Calling `unicode` on a non-ASCII character (at least on Windows) causes an error.

**Comment by kripken** [comment]
Thanks, this does look like w windows-specific problem. I opened #4102 with a test for this, let's continue the discussion there.

**Comment by juj** [comment]
https://github.com/kripken/emscripten/pull/4102 was merged, which contained a fix, so closing as resolved.
