### ISSUE TITLE
Can't build incoming 64bits

### ISSUE THREAD

**Issue by wshager** [kripken/emscripten#4105]
The build fails at 69% at `Building CXX object tools/clang/lib/ASTMatchers/CMakeFiles/clangASTMatchers.dir/ASTMatchFinder.cpp.o`

`c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [tools/clang/lib/ASTMatchers/CMakeFiles/clangASTMatchers.dir/ASTMatchFinder.cpp.o] Error 4
make[1]: *** [tools/clang/lib/ASTMatchers/CMakeFiles/clangASTMatchers.dir/all] Error 2
make: *** [all] Error 2
Build failed due to exception!`

**Comment by wshager** [comment]
I run Ubuntu 14.04. gcc is 4.8.4.

**Comment by juj** [comment]
Hmm, this is similar to #3706.

If you nuke the whole `emsdk/clang/build_incoming*` directory to force a full clean, and redo `./emsdk install sdk-incoming-64bit -j1`, does that work?

If it still hits the same error, does it work if after the first internal error, you navigate to `emsdk/clang/build_incoming/` and reissue `make -j1` for an incremental build? (this was suggested in build #3706).

**Comment by wshager** [comment]
@juj I've tried suggestions from #3706 but to no avail.

**Comment by wshager** [comment]
@juj the problem is clear: `virtual memory exhausted: Cannot allocate memory`

I have 1GB free of 2GB, probably too little.

**Comment by wshager** [comment]
@juj could you please provide a "minimal requirements" section in "building from source"? The build succeeds with more resources (i.e. minimal 4GB of memory, 40GB free storage for sdk-incoming-64bit).

**Comment by kripken** [comment]
I added a note on memory requirements in 7b2f9fd7484edd8a58dd42cffac2531d17e2399f now.

**Comment by wshager** [comment]
@juj thank you.
