### ISSUE TITLE
Chrome Canary breaks regexes run on function toString()

### ISSUE THREAD

**Issue by AshleyScirra** [kripken/emscripten#4111]
In Chrome Canary 50.0.2654.0, function toString() now includes the function name. This breaks zlib-asm, and while investigating it (reported as crbug.com/587818) I found that asm.js code appears to run a regex on the result of function toString(), and since it doesn't expect the name to be there it fails to match and then throws when it tries to slice the result.

The workaround is to find this regex:

    /^function\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/

and (my hack, feel free to improve) add a [A-Za-z0-9]* to optionally match the function name if emitted:

    /^function\s*[A-Za-z0-9]*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/

Then this works in both current and Canary versions of Chrome. The Chrome bug will allow Google to determine the web compat impact, but this might need fixing in Emscripten anyway.

**Comment by rossberg-chromium** [comment]
Note that Chrome's new behaviour conforms to the current ES.next proposal for standardising toString:

http://tc39.github.io/Function-prototype-toString-revision/

It basically amounts to "return the original source code", modulo white space changes. This was agreed upon at the last TC39 meeting, and is currently at stage 2.

**Comment by kripken** [comment]
Thanks for the report and the info. Fixed on incoming.

The reason we need this is that for `ccall` we want to emit fast code, and we figure out what code to emit using a regex on a minified function (otherwise minification will mix us up). If you build with `NO_DYNAMIC_EXECUTION = 0` then we go through a slow path that avoids this, btw.

**Comment by AshleyScirra** [comment]
FWIW, this only happens in Canary with "experimental javascript" enabled, and it looks like a V8 patch is on the way to correct it as well. However I would guess the change ought to be made anyway for robustness.

**Comment by kripken** [comment]
Yes, agreed.

**Comment by rodneyrehm** [comment]
Unless I'm missing something, `[a-zA-Z]*\s*`is not going to match all possible function names.

```js
String(function _(a, b){ return a + b; })
String(function ಠ_ಠ(a, b){ return a + b; })
```

If I didn't miss anything, I'd suggest matching for `[^(]*` instead (anything but opening parens)

**Comment by kripken** [comment]
You're right, but this is only run a very specific set of methods, that we provide.

Although, come to think of it, you're right, the minified name might not fall in that subset. But I'm worried about matching anything but `(` as it might allow non-function things.

Reopening, we should improve this.

**Comment by kripken** [comment]
I pushed a commit that makes it support all the values we can have as minified outputs. There is a risk of another minifier being used, however - but AFAIK none use unicode tricks.

**Comment by rodneyrehm** [comment]
In such a case I would've added a comment to the source explaining why we're limiting function names to the given set, but LGTM. :)
