### ISSUE TITLE
How to run the tests under `tests/` (specifically, for `tests/embind/embind_test.cpp`)?

### ISSUE THREAD

**Issue by ziyuang** [kripken/emscripten#4117]
Not sure how the tests scripts are organized but I need an example on how to call the `emval_test_return_vector_of_vectors` in `tests/embind/embind_test.cpp` from JavaScript because I can only get an empty object in my script (ref: [my question on stackoverflow](http://stackoverflow.com/q/35494467/688080)). 

I tried replacing the string "benchmark" in `tests/embind/build_benmark` with "test", but the generated HTML file renders nothing meaningful. 

So can anyone point out the location of test scripts for `tests/embind/embind_test.cpp`, or simply provide one with the `em++` compilation command? Thank you.

**Comment by kripken** [comment]
Search for `embind_test.cpp` in `tests/*.py`, all tests are driven from python, that will find the testing code that calls it.

**Comment by ziyuang** [comment]
Yes I found it in the `test_embind` member function of the class `other` in `tests/test_other.py`. But it looks like a part of a larger test:

```
  def test_embind(self):
    environ = os.environ.copy()
    environ['EMCC_CLOSURE_ARGS'] = environ.get('EMCC_CLOSURE_ARGS', '') + " --externs " + pipes.quote(path_from_root('tests', 'embind', 'underscore-externs.js'))
    for args, fail in [
      ([], True), # without --bind, we fail
      (['--bind'], False),
      (['--bind', '-O1'], False),
      (['--bind', '-O2'], False),
      (['--bind', '-O2', '--closure', '1'], False),
      (['--bind', '-O2', '-s', 'ALLOW_MEMORY_GROWTH=1', path_from_root('tests', 'embind', 'isMemoryGrowthEnabled=true.cpp')], False),
    ]:
      print args, fail
      self.clear()
      try_delete(self.in_dir('a.out.js'))

      testFiles = [
        path_from_root('tests', 'embind', 'underscore-1.4.2.js'),
        path_from_root('tests', 'embind', 'imvu_test_adapter.js'),
        path_from_root('tests', 'embind', 'embind.test.js'),
      ]

      Popen(
        [ PYTHON,
          EMCC,
          path_from_root('tests', 'embind', 'embind_test.cpp'),
          '--pre-js', path_from_root('tests', 'embind', 'test.pre.js'),
          '--post-js', path_from_root('tests', 'embind', 'test.post.js'),
        ] + args,
        stderr=PIPE if fail else None,
        env=environ).communicate()

      assert os.path.exists(self.in_dir('a.out.js')) == (not fail)
      if not fail:
        with open(self.in_dir('a.out.js'), 'ab') as f:
          for tf in testFiles:
            f.write(open(tf, 'rb').read())

        output = run_js(self.in_dir('a.out.js'), stdout=PIPE, stderr=PIPE, full_output=True, assert_returncode=0)
        assert "FAIL" not in output, output

```

The only file containing `emval_test_return_vector_of_vectors` under `tests/embind` is `tests/embind/embind_test.cpp`. So I still cannot find the code that tests the function `emval_test_return_vector_of_vectors`.

**Comment by ziyuang** [comment]
I ran `EMCC_DEBUG=1 tests/runner.py other.test_embind` but still don't find the JavaScript calling `emval_test_return_vector_of_vectors` in `tests/embind/embind_test.cpp`.

**Comment by kripken** [comment]
In `tests/test_other.py` it looks like that file is used in `test_embind`. And there, it uses `tests/embind/test.pre.js` and `post.js`, those might contain what you want.

**Comment by froydnj** [comment]
@kripken, I don't think there's anything else to do here, can we close this?

**Comment by kripken** [comment]
Agreed, thanks.
