### ISSUE TITLE
Activating Emscripten globally replaces instances of %SystemRoot%

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#4121]
When activating Emscripten globally, the values in `PATH` matching `%SystemRoot%` are replaced with `C:\Windows`. Preferably it shouldn't mess like that with our paths.

**Comment by juj** [comment]
Oh wow, ouch! Can you post full the relevant path sections you had before the change?

**Comment by gouletr** [comment]
```
%SystemRoot%
%SystemRoot%\System32
%SystemRoot%\System32\Wbem
%SystemRoot%\System32\WindowsPowerShell\v1.0\
```
became
```
C:\Windows
C:\Windows\System32
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
```

**Comment by juj** [comment]
Thanks for catching this, fixed in https://github.com/juj/emsdk/commit/9e68e895bde973d86e989a652715fe781414164e and https://github.com/juj/emsdk/commit/53e217fca6cb06b99df066de136f008f3be608ad

**Comment by gouletr** [comment]
You know there might be other paths that uses `%SystemRoot%`, and there might also be other tokens like `%UserProfile%`, etc. Your fix will probably not work on all Windows systems.

**Comment by juj** [comment]
Yes, but is there a better alternative? I think it is reasonable to undo the changes for the fixed known cases that we can. Checked on my Windows laptop to find those as the ones that are known to exist.

**Comment by gouletr** [comment]
Does that mean we can't simply avoid touching them?

**Comment by juj** [comment]
Hmm, not sure what you mean?

The commit https://github.com/juj/emsdk/commit/9e68e895bde973d86e989a652715fe781414164e fixes that emsdk won't anymore expand the %var%s when adding items to PATH, and the commit https://github.com/juj/emsdk/commit/53e217fca6cb06b99df066de136f008f3be608ad just tries to fix up after the fact the problem for anyone who had used the `--global` option before the fix, and their system path had the %SystemRoot% var expanded, which looks like is the only fixed %var% we can reliably fix back.

**Comment by gouletr** [comment]
Aw sorry for the noise, I only saw https://github.com/juj/emsdk/commit/53e217fca6cb06b99df066de136f008f3be608ad
><
