### ISSUE TITLE
window.id conflict when compiling with --closure 1

### ISSUE THREAD

**Issue by SBRK** [kripken/emscripten#4122]
This is a tricky one. 
When handling focus/blur events on window with Emscripten (with `emscripten_set_focus_callback`), I'm getting an error `Uncaught TypeError: a.charCodeAt is not a function` in the emscripten code of the event handling, more precisely in `registerFocusEventCallback` in library_html5.js, when calling `writeStringToMemory(id, ...)`. 

When compiling with  `--closure 1`, all classes and functions in the global scope get renamed to window.a, window.b, window.c, ... window.aa, window.ab, window.ac, ... and there is also one that takes window.id...
As a result, when trying to write window.id in the memory, instead of writing a String like it would normally do, it tries to write a window.id which in this case will be an object, and fails on window.id.charCodeAt.

What options do I have if I don't want to give up `--closure 1` and can't listen to focus events anywhere else than on window ?

Some way to fix this in emscripten would be to replace this line 

`var id = e.target.id ? e.target.id : '';`

with this 

`var id = e.target.id && (typeof e.target.id) == 'string' ? e.target.id : '';`

**Comment by juj** [comment]
Does just using `e['target']['id']` work? If not, then I think your suggestion looks good, we could check the type of id.

**Comment by SBRK** [comment]
That would still return the object and not a string, right ? The typeof test would still be required

**Comment by kripken** [comment]
It's confusing having both this and the pull open - how about if I close this, and we'll focus on the pull #4123?
