### ISSUE TITLE
cmake and CXX_STANDARD property

### ISSUE THREAD

**Issue by Lectem** [kripken/emscripten#4129]
I configured my project using emcmake, and my target has the property [CXX_STANDARD](https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html) set to 11.
However the toolchain file of emscripten uses (soon to be deprecated?) [CMAKE_FORCE_CXX_COMPILER](CMakeForceCompiler).

Because of this, no checks on the compiler are done, hence cmake doesn't know the c++11 flag to use for this compiler.
I tried using the following instead of force (which does the same things minus disabling checks, and set the correct information about the compiler Id)

```
set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER_ID Clang)
set(CMAKE_C_COMPILER_VERSION "3.7.0")
set(CMAKE_C_STANDARD_COMPUTED_DEFAULT 11)
set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
set(CMAKE_CXX_COMPILER_ID Clang)
set(CMAKE_CXX_COMPILER_VERSION "3.7.0")
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT 98)
```

I do not know why cmake is unable to detect that emcc and em++ are just replacements for clang, but my guess is that the first line of 'emcc -v' gives information about emcc and not clang. Perhaps it could be possible to skip this line when running emcmake if it is the case ?

Please note that while the following solutions work, those are considered bad practice : 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`
`add_definitions(-std=c++11)`

EDIT: removing the first line in emcc -v didn't help for the detection

**Comment by juj** [comment]
Thanks for filing. Would you be able to do a small hello world test cmake file, or add a failing test to the existing cmake tests?

**Comment by Lectem** [comment]
I was unsure if you meant to open a pull request, but I went ahead and did it anyway. 
You can try adding ` set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")` to make sure it compiles fine with c++11

**Comment by Lectem** [comment]
Any news on this ?

**Comment by juj** [comment]
A somewhat recent pull request removed the usage of CMAKE_FORCE_COMPILER. See #4477. Does latest Emscripten incoming which has that PR have any effect on this?

**Comment by Lectem** [comment]
I just tried using tag 1.36.9, and the problem remains. It seems cmake just doesn't get that emscripten is in fact clang.

> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown

**Comment by juj** [comment]
Thanks, had a look at this now, and feels like your fix in first comment is ok, although looking through CMake system script files, I'll amp it up a little for robustness. Looks like we don't want to CMake to try to do compiler autodetection, because it indeed doesn't understand anything about Emscripten.

There is an issue I'm having where CMake configure times become something like 30x slower when I do the changes. Looking at those now before posting a fix for this.

**Comment by Lectem** [comment]
Hi, it seems there is a regression (I don't know since when, I didn't try to run emscripten for a while).

I tried to build with ninja, and configure with emcmake.
The same example as before does not add the required c++ flags:

```
E:\progs\WEB\cmakeemscriptencxx11\build>emcmake cmake -G "Ninja" ..
-- Configuring done
-- Generating done
-- Build files have been written to: E:/progs/WEB/cmakeemscriptencxx11/build

E:\progs\WEB\cmakeemscriptencxx11\build>ninja

[1/2] Building CXX object CMakeFiles/helloworld.dir/main.cpp.o
FAILED: CMakeFiles/helloworld.dir/main.cpp.o
C:\emsdk\fastcomp\emscripten\em++.bat     -MD -MT CMakeFiles/helloworld.dir/main.cpp.o -MF CMakeFiles\helloworld.dir\main.cpp.o.d -o CMakeFiles/helloworld.dir/main.cpp.o -c ../main.cpp
../main.cpp:8:12: error: expected ';' at end of declaration
```  

Building with nmake gave the same issue.
Could we re-open this issue, or should I open a new one ?

**Comment by kripken** [comment]
I think we added a test for this, so what you see is probably something related but different. Yeah, filing a new bug is probably best, with a testcase if possible.
