### ISSUE TITLE
Slow memory write compared to native c++

### ISSUE THREAD

**Issue by hcomere** [kripken/emscripten#4148]
Hello,

I am doing some image processing and i notice a huge speed difference between generated code and native c++.

For exemple, a loop like following code runs for an image of 640x480 :
* in 2 ms in native c++ 
* In 12 ms in generated code with Chrome
* In 7 ms in generated code with Firefox

```
	std::uint64_t *	data2 = new std::uint64_t[2 * (m_width + 1) * (m_height + 1)];
    std::uint8_t * img2 = a_image->getPixels ();

	// first line is zero
	std::memset (data2, 0, m_rowstride * sizeof (std::uint64_t));
    
	for (int y = 0; y < m_height; ++y) 
	{
        // left column is zero
		data2[(y + 1) * m_rowstride] = 0;
        data2[(y + 1) * m_rowstride + 1] = 0;
        
        std::uint64_t sumLine = 0;
        std::uint64_t sum2Line = 0;
    
		for (int x = 0; x < m_width; ++x)
		{
			sumLine += img2[y * m_width + x];
            sum2Line += img2[y * m_width + x] * img2[y * m_width + x];
            
            /// Those 2 memory writes produce huge slowdown 
            data2[(y + 1) * m_rowstride + x] = sumLine + data2[y * m_rowstride + x];
            data2[(y + 1) * m_rowstride + x + 1] = sum2Line + data2[y * m_rowstride + x];
        }
    }
```

I tried with pointer arithmetic but it does not help.
Any advice to get portable near native speed with this kind of image processing ?

Regards,
Harold

**Comment by JSStats** [comment]
The 64 bit values might be a problem.

**Comment by hcomere** [comment]
Right, using only 32 bit values solve the problem, thanks :)

Why does 64 bit values are problematic ?

**Comment by JSStats** [comment]
asm.js has no native 64 bit integer support. wait for wasm.
