### ISSUE TITLE
HEAPU32 access comes out as signed(?) in SPLIT_MEMORY mode.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4150]
Looking at the logs after #4142 landed, two SPLIT_MEMORY tests have started failing: http://clb.demon.fi:8112/builders/ubuntu-incoming/builds/1354/steps/default%20suite/logs/stdio.

It looks like the issue is in testing the stack cookie, which is just doing a signed vs unsigned comparison of the value `0x89BACDFE`. Changing the magic value to something that fits in signed int32, e.g. `0x79BACDFE` fixes these tests to pass, so could just push that. However, got really curious as to why  the expression `HEAPU32[(STACK_MAX >> 2)-2].toString(16)` generates a signed integer "0x-76453202" (==`-1984246274`==`2310721022`==`0x89BACDFE`)  just in `SPLIT_MEMORY` mode but works otherwise?

**Comment by kripken** [comment]
Turns it out was a silly bug in the return coercion in that method. Fixed.
