### ISSUE TITLE
Emscripten should not attempt to generate same system libraries multiple times in buildsystem that supports concurrent/parallel build processes

### ISSUE THREAD

**Issue by weitjong** [kripken/emscripten#4151]
Our project performs CI build which prepares the VM from scratch including installing/activating Emscripten compiler toolchain on the fly each time the CI job start. Thus, the ~/.emscripten_cache is fresh out when we build our project afterwards. Our buildsystem supports concurrent/parallel build processes and we have a number of target samples to be built as part of the whole CI job. When our buildsystem is about to link the samples, it does that in concurrent, say 3 samples at a time. The problem is, when Emscripten realizes that it needs to generate those system libraries (gl, dlmalloc, libc, etc), it does so without any locking mechanism. As such the "realization" may come in multiple times for each concurrent process. This can be clearly seen from the CI build log. It is not just a cosmetic issue though. The generated *.bc are in theory try to overwrite each other out. There is a real potential issue that the final resultant *.bc file might be corrupted due to this race condition.

**Comment by weitjong** [comment]
Another related question regarding to this issue. As a workaround for our project (while waiting for the above issue to fixed permanently), I am planning to add a custom command in our CMake build script to perform a dummy linking operation a head of time, i.e. ahead of the actual linking phase for our targets. The idea of this dummy linking operation is so that Emscripten can generate the system libraries only once in a controlled fashion. Something like:
```
COMMAND ${CMAKE_COMMAND} -E touch dummy.cpp && ${CMAKE_CXX_COMPILER} -o dummy.html dummy.cpp && ${CMAKE_COMMAND} -E remove dummy.*)
```
This only works partially because with an empty input source file, Emscripten only attempts to generate the libc.bc and dlmalloc.bc. It does not pre-generate gl.bc and libcxxabi.bc as I have hoped for. The latter two only get generated in the actual linking phases for our targets and therefore they still got generated multiple times after the above attempt. I have attempted to change the command to add a linker flag "-lGL", but it did not seem to work. So my question is, what compiler/linker flags or EMCC specific settings "-s" flags that I can use to achieve this?

**Comment by kripken** [comment]
This is a known issue, and I think we just have not found a good cross-platform way to do such locking. Open to ideas here.

Instead, we recommend that you use `embuilder.py` to build the libraries you will need, before running the rest of the build system.

**Comment by weitjong** [comment]
Thanks for the prompt response. Changing the custom command to invoke the embuilder.py, works like a charm!

**Comment by weitjong** [comment]
Sorry, forgot that you might want to leave this issue open.

**Comment by bitc** [comment]
@kripken 
I notice a `~/.emscripten_cache.lock` file. Does this mean that this issue has been fixed and can be closed?

**Comment by kripken** [comment]
Thanks @bitc, yes, this was implement a while ago by @juj.
