### ISSUE TITLE
Demangling Stack Traces with Optimizations on

### ISSUE THREAD

**Issue by swimorsink** [kripken/emscripten#4166]
Hi,

We currently see stack traces like the following:
Uncaught abort(35) at Error
    at jsStackTrace (<anonymous>:688:1054169)
    at stackTrace (<anonymous>:688:1054352)
    at abort (<anonymous>:723:47862)
    at Array.yQc (<anonymous>:716:228645)
    at Pua (<anonymous>:709:232788)
    at Array.K8a (<anonymous>:707:59129)
    at uib (<anonymous>:708:249690)
    at Array.Dkc (<anonymous>:699:163973)
    at y2 (<anonymous>:694:132017)
    at Array.Pg (<anonymous>:704:6051)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.-undefined

We compile with --closure 0, but we still seem to lose all our function names, I'm assuming because that's just what the optimizer does.

Is there anyway to make these stack traces more meaningful? We're trying to debug the production version of our app.

It looks like Closure runs at anything above -O2. Could we keep most of the optimizations just without renaming stuff?

**Comment by kripken** [comment]
Try [`--profiling-funcs`](http://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html) to keep function names. That tells the optimizer to not remove the names.

Also relevant are the `-g` modes. For example `-g2` will preserve both function names and whitespace, which is helpful when debugging.

**Comment by swimorsink** [comment]
Perfect. Exactly what I was looking for. Thanks. Blows up our binary by about 20%, which is what I would expect, but actual performance seems about the same.

**Comment by kripken** [comment]
Good, looks like we can close this then.
