### ISSUE TITLE
Building with BINARYEN=1 embeds absolute path to .wasm file in .html

### ISSUE THREAD

**Issue by floooh** [kripken/emscripten#4170]
When building with BINARYEN=1 the generated .html file has an absolute path for to the .wasm file which then causes the the XHR to load that file to fail:

```
var xhr = new XMLHttpRequest();
xhr.open('GET', '/Users/floh/projects/fips-deploy/oryol/wasm-make-release/Shapes.wasm', true);
xhr.responseType = 'arraybuffer';
```
The Shapes.html.mem and Shapes.js files don't have the filesystem path in front of them. Also when building normally for asm.js it looks like this:
```
var script = document.createElement('script');
script.src = "Shapes.js";
document.body.appendChild(script);
```
This may be a side effect of generating the emcc makefiles with cmake, because this calls emcc with absolute paths. However in other places the path seems to be stripped, so I guess this is just an oversight.

Also, since I'm going to use my own shell.html file for the final build, this isn't super-critical for me, it's just an inconvenience for testing :)

**Comment by kripken** [comment]
Strange. When I build I get stuff like `xhr.open('GET', 'test.wasm', true);`, that is, a proper relative path.

Looking in emcc.py, this probably isn't a binaryen specific issue, as the variable here, `wasm_binary_target`, is a small modification of the `asm_target`, itself derived from `target`. So I would expect all targets to be wrong, or none?

Also, even when I set `-o ..absolute path..` I don't see this issue.

Maybe are you on an older version of emscripten? I tested on latest incoming.

**Comment by floooh** [comment]
Hmm, I'm on a very recent emscripten (from yesterday evening). My linker line has an absolute path with -o and I was assuming that this is simply taken as-is... but since you don't see that problem with an absolute path. 
```
-o /Users/floh/projects/fips-deploy/oryol/wasm-make-release/Clear.html
```
Grepping across all build results (wasm and asm.js) I only see this absolute path in this one place.

The only unusual thing I can think of is that my .emscripten file and cache are not under ~, but somewhere else, but that's hardly an issue... 

I'll try to investigate more, and will report back, since you can't reproduce it, please don't waste time with it :)

**Comment by floooh** [comment]
Alright, I don't know why it worked for you with absolute path, but I think I found the problem :)

In places where the asm_target is integrated into the generated shell HTML it is surrounded with a os.path.basename(), e.g. here:

- https://github.com/kripken/emscripten/blob/incoming/emcc.py#L1947
- https://github.com/kripken/emscripten/blob/incoming/emcc.py#L1970

Just a few lines down where the wasm_binary_target is integrated, this is missing:

- https://github.com/kripken/emscripten/blob/incoming/emcc.py#L1986

Surrounding this with an os.path.basename() fixes the problem for me. Do you want to fix this or should I provide a PR?

**Comment by kripken** [comment]
Thanks! That's obviously wrong without `os.path.basename`. No need for a PR, I fixed it now.

I didn't look into it, but I suspect somewhere in the build system it reduces the path to a relative one if possible, or something like that - and that worked for me, but not for you, or vice versa, if one of our build systems moved the current dir, etc. Seems like that could explain why I couldn't reproduce it.

**Comment by floooh** [comment]
confirmed working, thanks!
