### ISSUE TITLE
#define stderr (stderr) : Causes a well broken code

### ISSUE THREAD

**Issue by IngwiePhoenix** [kripken/emscripten#4172]
Within my application, I use STLPlus, which has a sub-process class that lets me execute processes synchronously or async. However, this is causing my code to throw this:

```
src/os-exec.cpp:66:47: error: expected unqualified-id
        int outRead = this->read_stdout(this->stdout);
                                              ^
/usr/local/Cellar/emscripten/1.35.23/libexec/system/include/libc/stdio.h:60:16: note: expanded from macro 'stdout'
#define stdout (stdout)
               ^
```

Do I now have to rename all the instances of `stdout` and `stderr`?

**Comment by kripken** [comment]
Looks like you're hitting a conflict with the musl headers. We'd need to look in the standards docs carefully to figure out if what they do is by the spec or not. But as a workaround, you can rename those fields as you mentioned, or perhaps you can just `#undef` stdout` in your C++ files (after musl headers were already included, doing it there should not break anything of musl).

**Comment by IngwiePhoenix** [comment]
I think I can actually go with a tiny "emscripten-fixes.h" after all the other includes, and just #ifdef and then #undef all the things :)

Thanks for your reply!

**Comment by kripken** [comment]
Great!
