### ISSUE TITLE
Standard file operations seem to...not work?

### ISSUE THREAD

**Issue by IngwiePhoenix** [kripken/emscripten#4177]
I am working on making my app emscripten-compatible. So far, I can compile it perfectly fine but am running into tiny little issues that I am still working on.

But the bigger issue is that an important dependency is not working: https://github.com/graphitemaster/incbin

The tool uses standard `fopen()`, `fread()` and alike to read a file, scan it for `INCBIN(a, b)` statements and emit a C source. But it can not read the input file, nor open the output file for writing...

Relevant lines:
- Output file https://github.com/graphitemaster/incbin/blob/master/incbin.c#L188-L191
- Input file https://github.com/graphitemaster/incbin/blob/master/incbin.c#L205-L212
  * `open_file`: https://github.com/graphitemaster/incbin/blob/master/incbin.c#L54-L68

What is wrong, that causes the tool to not work when compiled via emscripten?

**Comment by kripken** [comment]
Did you preload or embed the files, or use NODEFS or other? If not, see [these 2 FAQ entries](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-my-compiled-program-access-files).

**Comment by IngwiePhoenix** [comment]
I am so embarressed x) I only _now_ found the API limitation guide. That esyxplained everything... I'll have to code a way around this, so that there are synchronous APIs. I am only intending to run on Node, which does have `*Sync()` variants of `fs`. (`fs.readFileSync` for instance).

I should've read this beforehand. Sorry!

**Comment by kripken** [comment]
No problem.

If you only need node, then look at NODEFS - it provides sync access. So things should just work there, although it's probably less tested than the web case.

**Comment by IngwiePhoenix** [comment]
- https://github.com/IngwiePhoenix/IceTea/blob/master/src/icetea-emscripten.js
- https://github.com/IngwiePhoenix/IceTea/blob/master/src/main.cpp#L22-L27

Solved :).
