### ISSUE TITLE
Checking, if a path exists.

### ISSUE THREAD

**Issue by IngwiePhoenix** [kripken/emscripten#4180]
When I mounted a path via `FS.mount`, I can't seem to actually verify it's existence. `FS.isDir` returns false, and I am confused to what method to use to check if a mountpoint exists, or not.

**Comment by vadimkantorov** [comment]
Also, wonder if it's possible to check if something was mounted at a given dir path (so that I could unmount it)

**Comment by vadimkantorov** [comment]
I'm using:
```js
if(FS.analyzePath(this.project_dir).object.mount.mountpoint == this.project_dir)
    FS.unmount(this.project_dir);
```

@kripken Is it robust (API-wise)?

**Comment by kripken** [comment]
@vadimkantorov I would guess that makes sense, but I'm not very familiar with that code, sorry.
