### ISSUE TITLE
Incorrect report of "-s DEMANGLE_SUPPORT=1 to link in libcxxabi demangling" since 1.36.0

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#4193]
After updating to Emscripten 1.36.0, I get the following warning in browsers:
```
warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
```
We do set this flag, so there must be an issue with how Emscripten check this.

**Comment by kripken** [comment]
Thanks, we missed a case. Should be fixed now.

However, the case we missed was where libcxxabi reports an internal error. So for some reason it's not going to demangle that symbol.

**Comment by gouletr** [comment]
thanks!
