### ISSUE TITLE
Simple C stdio file IO does not work with nodejs

### ISSUE THREAD

**Issue by choikwa** [kripken/emscripten#4195]
Tested using sdk-incoming-64bit branch

a.c:
```
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv)
{
  for(int i=0; i<argc; i++)
  {
    printf("%s\n", argv[i]);
    if (strcmp(argv[i], "bbb") == 0)
    {
      FILE *fin = fopen(argv[i], "r");
      char c;
      while ((c = fgetc(fin)) != EOF)
      {
        printf("%c", c);
      }
    }
  }
  return 0;
}
```

===========================

bbb:
asdfajsdklfa
sdf

===========================

$ emcc a.c -o a.js
$ node a.js bbb
/a.js
bbb
$ gcc -std=c99 a.c -o a
$ ./a bbb
./a
bbb
asdfajsdklfa
sdf

**Comment by kripken** [comment]
See [this FAQ entry](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-can-t-my-code-access-a-file-in-the-same-directory).

**Comment by choikwa** [comment]
TIL. Thanks for a reading.

$ emcc a.c -o a.js --preload-file bbb
./a.js bbb
/a.js:21
      throw 'using preloaded data can only be done on a web page or in a web worker';
      ^
$ emcc a.c -o a.js --embed-file bbb.txt
$ node a.js bbb.txt
/a.js
bbb.txt
asdfajsdklfa
sdf
$ gcc -std=c99 a.c -o a
$ ./a bbb.txt
./a
bbb.txt
asdfajsdklfa
sdf
