### ISSUE TITLE
[ 46%] Built target opencv_ts Makefile:137: recipe for target 'all' failed make: *** [all] Error 2

### ISSUE THREAD

**Issue by mastanimaru** [kripken/emscripten#4196]
help me sort this issue

**Comment by juj** [comment]
Can you include the full error?

**Comment by mastanimaru** [comment]
That is the error i m getting which i posted in last mail, when i use 4
cores system gets restarted so i used 3 cores when i did that i got up to
46% and get the error as in last mail.

**Comment by kripken** [comment]
Running with more logging might help, like `make VERBOSE=1`, or `EMCC_DEBUG=1` in the env if it's an emcc issue.

However, if this changes based on how many cores you use, it's probably just running out of memory. Try with just 1 core, and monitor memory usage to see what's going on.

**Comment by juj** [comment]
Let me close this as resolved. The above commit fixes opencv build problem for me, which was due to it using gtest framework and including cxxabi.h, and the failure would be something like mentioned in the title of this bug.

If that was not it, please paste full logs.
