### ISSUE TITLE
Setting FPS with emscripten_set_main_loop() can be very inaccurate

### ISSUE THREAD

**Issue by reubenscratton** [kripken/emscripten#4200]
Setting a rate of 50fps with emscripten_set_main_loop() gives me an actual rate of ~35fps. To get the desired 50fps I find I have to set the rate parameter to 80 or so.

I imagine this is due to emscripten's  timer function calling `setTimeout(func, 1000/fps);` last thing before returning, effectively assuming that the app's callback takes no time at all. It would be significantly more accurate if `setTimeout(func, 1000/fps);` was the *first* thing done in the timer function rather than the last.

But ideally the timer would implement some self-correcting behaviour so each tick was as near to the scheduled tick as possible. (It is of course reasonably easy to implement this oneself in javascript and let the emscripten_set_main_loop() be a no-op, which is what I have done).

**Comment by kripken** [comment]
The tricky thing is that if we do this at the start, then we might hit an exception later, so we'd need to check for that. Also, the user might alter the main loop scheduling during this frame, which is another case to handle.

Instead, how about if we noticed the last frame start time, and called with a delay timed relative to that (so a long frame would incur a smaller timeout)? That seems correct. I worry though that it's a change in behavior, and might affect existing code. We have always recommended people use the requestAnimationFrame path anyhow, though, so maybe not many use it. And I agree with @reubenscratton that we should fix this. @juj, what do you think?

**Comment by reubenscratton** [comment]
For context, mine may be a slightly niche requirement... my first Emscripten app emulates a British 1980s home computer called the BBC Micro which was designed with PAL TVs (50Hz refresh rate) in mind. The code is kept simple if I can drive the whole thing off a 50Hz timer that emulates precisely 20ms of execution every tick. :)

**Comment by reubenscratton** [comment]
FWIW your proposal sounds sensible to me.

**Comment by juj** [comment]
Fixed in above pull request.
