### ISSUE TITLE
qsort doesn't sort negative floats correctly

### ISSUE THREAD

**Issue by dahonig** [kripken/emscripten#4204]
I'm using qsort() to sort some floats so I can compute their median.
It appears that negative floats are not sorted correctly, but treated as positive floats.  They are correctly sorted in the native C code that calls a qsort() implementation (using "tcc" for this).

C output: 
median() copying sample #5 width=5 0.300000 from #3
median() copying sample #5 width=5 0.400000 from #4
median() copying sample #5 width=5 -0.500000 from #5
median() copying sample #5 width=5 0.600000 from #6
median() copying sample #5 width=5 0.700000 from #7
med SORTED: -0.500000 0.300000 0.400000 0.600000 0.700000 odd 	median()=0.400000	

Emscripten output: 

median() copying sample #5 width=5 0.300000 from #3
median() copying sample #5 width=5 0.400000 from #4
median() copying sample #5 width=5 -0.500000 from #5
median() copying sample #5 width=5 0.600000 from #6
median() copying sample #5 width=5 0.700000 from #7
med SORTED: 0.300000 0.400000 -0.500000 0.600000 0.700000 odd 	median()=-0.500000

float median(float *data, int sample, int width)
{
  float median=0.0;

  int odd= width & 1;
  int halfwidth= (width-odd)/2;
  
  float buff[5]; // max width of median filter=5
  memset(buff, 0, sizeof(buff)); 

  // printf("med raw (sample=%d width=%d): ", sample, width); 
  for (int i=0; i<width; i++) {
    buff[i]=data[sample-halfwidth+i];
    printf("median() copying sample #%d width=%d %f from #%d\n", sample, width, buff[i], sample-halfwidth+i); 
  }

  qsort(buff, (size_t) width, (size_t) sizeof(float) , fltcompare );

  printf("med SORTED: "); 
  for (int i=0; i<width; i++) {
    printf("%f ", buff[i]);
  }

  if (odd) {
     printf("odd "); 
    median=buff[halfwidth];
  } else {
     printf("even "); 
    median=(buff[halfwidth-1]+buff[halfwidth])/2.0;
  }

  // test
  //  median=data[sample]; // wrong

   printf("\tmedian()=%f\t\n", median); 

  return median; 
}

void test_median() {

  float tdat[10];
  for (int i=0; i<10; i++) {
    tdat[i]= (float) i * 0.1;
  }

  float med; 

  med=  median(tdat, 5, 5);
 if ( 0.5==med) {
   printf("OK\n");
 } else {
      printf("NOT OK\n");
 }

  for (int i=0; i<10; i++) {
    tdat[i]= (float) i * 0.1;
  }

  med=median(tdat, 5, 4); 
  if ( (float) 0.45 == med) {
   printf("OK\n");
 } else {
   printf("NOT OK %f\n", med);
 }

  // TEST NEGATIVE FLOATS

  for (int i=0; i<10; i++) {
    tdat[i]= (float) i * 0.1;
  }

  tdat[5] *= -1.0; 

  med=median(tdat, 5, 5); 
  if ( (float) 0.5 == med) {
   printf("OK\n");
 } else {
   printf("NOT OK %f\n", med);
 }

  exit(0); 

}

**Comment by kripken** [comment]
Please escape the code sample so it is readable (4 `'s before and after).

**Comment by Matheus28** [comment]
Also, where's your `fltcompare` function?

**Comment by dahonig** [comment]
(Thanks for looking at this) 

int fltcompare(const void *a,const void *b) {
  float fa, fb;
  fa =  * ((float *) a);
  fb =  * ((float *) b);
  return (fa>fb);
}

**Comment by Matheus28** [comment]
Can you try returning `fa - fb` instead? The comparison function must return <0, 0 or >0, but your bool will only return 0 or 1.

**Comment by dahonig** [comment]
Here is a simpler standalone test that will demonstrate the diffference.  The comparison returns fa - fb as requested; no difference.


'
/* QSORT TEST with negative float
for Emscripten team 
*/



#include <stdio.h>
#include <stdlib.h> // qsort
#include <string.h> // memset



int fltcompare(const void *a,const void *b) {
  float fa, fb;
  fa =  * ((float *) a);
  fb =  * ((float *) b);
  return (fa - fb);
}





int main()
{

  int i;
  float vals[10];
  for (i=0; i<10; i++)
    {
      vals[i]= 0.1 * i;
    }

  vals[5] = -vals[5];

  for (i=0; i<10; i++) 
    {
      printf("input: #%d = %f\n", i, vals[i]);
    }

  qsort(vals, 10, (size_t) sizeof(float), fltcompare);
  

  for (i=0; i<10; i++) 
    {
      printf("qsorted: #%d = %f\n", i, vals[i]);
    }

}

// eof


`

**Comment by Matheus28** [comment]
I edited my comment a bit after you saw it, please check it again.

**Comment by dahonig** [comment]
Matheus28, the values ARE sorted correctly if their differences exceed 1.0
Good find!   

I thought qsort works with regular float ">" operators...
 
So a trivial change to the comparison (to use > but excplicitly return -1, 0, 1) will fix it.


Thanks much!   Emscripten is so cool!   Fairly amusing that C let me get away with this misunderstanding... its usually not very forgiving :-) 

Consider this 'bug' closed.
