### ISSUE TITLE
ctor_evaller.py failures on Windows

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4205]
Debugging Windows failure of `asm2.test_eval_ctors`, I see that in tools/ctor_evaller.py, there is:

    num_ctors = ctors_text.count(',') + 1
    shared.logging.debug('ctor_evaller: %d ctors' % num_ctors)

and on Windows when executing the text, the value of `ctors_text` ends up being

    __ATINIT__.push({ func: function() { _atexit(96,22048) } });

and the value of `num_ctors` erroneously becomes 2.

Another trouble I am seeing is that in the function `eval_ctors(...)`, there is an assert `assert total_ctors > 0`, but with the above form of `ctors_text`, `total_ctors` ends up being 0 inside the function body, because the above form of `ctors_text` doesn't map through the following code:

    all_ctors = filter(lambda ctor: ctor.endswith('()') and not ctor == 'function()' and '.' not in ctor, ctors_text.split(' '))
    all_ctors = map(lambda ctor: ctor.replace('()', ''), all_ctors)
    total_ctors = len(all_ctors)

The eventual failure though is that for some reason, `ctor_evaller.py` ends up running `eval_ctors()` function in an infinite loop, always trying to remove more ctors, but never having any to remove, the `ctors_text` is of the above form in each call. @kripken: does this give any clues what might trigger the infinite loop?

**Comment by juj** [comment]
Fixed the infinite loop issue in https://github.com/kripken/emscripten/commit/05e152df85c693fd506a62f567394a9272a91995, though the above suspect discrepancies still remain, which probably occurs on Linux as well?

**Comment by kripken** [comment]
I improved the logic for counting ctors, but I don't think it will fix what you see, which is really odd - there can't be an atexit call there, the backend should only emit a call to an exported LLVM __GLOBAL__ type function, which takes no params. I have no idea what would emit an atexit in `__ATINIT__` like you pasted, and it doesn't on linux. Any chance you looked at the wrong file somehow? If not, can you send me the file and command that builds it (that test has a few parts, so I need to know which that was).

I also added some more logging which might help on the bots, of the ctors_text.

**Comment by kripken** [comment]
Ok, looking more into this, the thing that emits atexits like you are seeing is in the ctor evaller itself. We need to replay atexits, so we just add them to `__ATINIT__` like that. But that should be in the *output* of the ctor evaller, not the input. And we should never run it again on its own output.

**Comment by kripken** [comment]
(So I still have no idea why you are seeing that.)

**Comment by juj** [comment]
Oh, I realise that it must have been the import safety issue that incorrectly caused ctor_evaller to execute on wrong input data, when that infinite loop issue occurred. So looks like this is resolved.
