### ISSUE TITLE
ctor_evaller.py fails with a red herring error code(?)

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4206]
Running the `test_eval_ctors` test in `EMCC_DEBUG=1` mode gives the following error message:

    DEBUG:root:failed to use vanilla file, will re-check: too many values to unpack
    DEBUG:root:testing for asm.js target, because if not present (i.e. this is plain vanilla llvm, not emscripten fastcomp), we will use the wasm target instead (set EMCC_WASM_BACKEND to skip this check)
    DEBUG:root:check tells us to use asm.js backend
    DEBUG:root:ctor_evaller: 1 ctors
    DEBUG:root:ctor_evaller: trying to eval 1 global constructors
    DEBUG:root:trying to eval ctors: __GLOBAL__sub_I_src_cpp
    DEBUG:root:not all ctors could be evalled:
    ReferenceError: ___syscall54 is not defined
        at Array.___stdout_write (c:\users\jukka\appdata\local\temp\emscripten_temp\ctorEval.js:2653:141)
        at ___overflow (c:\users\jukka\appdata\local\temp\emscripten_temp\ctorEval.js:2453:54)
        at _puts (c:\users\jukka\appdata\local\temp\emscripten_temp\ctorEval.js:2536:10)
        at Object.__GLOBAL__sub_I_src_cpp (c:\users\jukka\appdata\local\temp\emscripten_temp\ctorEval.js:2768:2)
        at Object.<anonymous> (c:\users\jukka\appdata\local\temp\emscripten_temp\ctorEval.js:2828:21)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:475:10)

    DEBUG:root:ctor_evaller: not successful

this looks like normal operation of the evaller, since syscalls have been sandboxed out from execution(?). However the error `ReferenceError: ___syscall54 is not defined` feels like an awkward error message to post in this case, since it points to something being missing that might be an implementation error in our part. I wonder if we could replace the sandboxed functions with other functions that throw an exception that would give a more clear message "ctor x was not optimized away since it refers to unoptimizable function y"?

**Comment by kripken** [comment]
It's not easy to do so, we actually don't have a list of all the methods that are callable. We basically set up what we know is safe to call, and then run, and use the JS semantics guarantee that if something else is called, it will throw. What we could do is parse out the function names from the stack trace, perhaps, and print a nicer message? However, getting that to work on all JS engines might be annoying.

**Comment by juj** [comment]
Ah, I see. That does sound a bit inconvenient and perhaps brittle. Would it instead be possible to have a global level try catch that catches the ReferenceError and turns it into another error?

**Comment by kripken** [comment]
Hmm, looks like v8 keeps the ReferenceError text in the stack trace, while sm does not. So it's not trivial to get just the stack and print a different error.

However, we can add text before and after it, to clarify, I added that.

**Comment by juj** [comment]
Feel like this is resolved, so closing!
