### ISSUE TITLE
Binaryen port building in Windows

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4207]
Binaryen is now an emscripten port, and we get and build it automatically when `BINARYEN=1` is used. This avoids the user needing to get and build it and modify their settings file.

To build, this runs cmake and then make, as we need to build the native binaryen executables. That fails on windows due to lack of make. What should we be doing there for windows?

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
Oh, thanks, fixed in above commit. In order for the test to run correctly on Windows, we'll need the build fixes in https://github.com/WebAssembly/binaryen/pull/281 to be applied.

**Comment by kripken** [comment]
Nice, thanks! I didn't know cmake could do that.
