### ISSUE TITLE
Additional printf causes memory corruption, TOTAL_STACK doesn't matter

### ISSUE THREAD

**Issue by cforger** [kripken/emscripten#4230]
Hello,

 I started this in the discussion group, but it's obviously an issue now, so I am reporting it here.

https://groups.google.com/forum/#!topic/emscripten-discuss/uJx1EwLKXZI

 The issue is that one more char from a printf is enough to cause a JS crash in the browser, perhaps on the function call?

 The program is a rather large codebase that I'm inserting debugging printf's into - Before long, the presence of the debug printf causes a crash in a different spot.  

 Look at these four tests. In each test, the printf statement isn't representing all of the printfs in my code, but it's showing you all that I need to change to cause a crash in the program. I also include my emcc command line so you can see what I'm passing.

Test1:
printf("\n\n\n");

emcc -g4 -O0 --js-opts 0 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s TOTAL_STACK=15000000 -s FS_LOG=1 -s ASSERTIONS=2 --separate-asm --memory-init-file 1 

(JS Console Warn: increasing TOTAL_MEMORY to 33554432 to be compliant with the asm.js spec (and given that TOTAL_STACK=15000000)

RESULT: Program is completely fine, different (real) problem occurs further in code. 

Test 2: Add one "\n" to the printf
printf("\n\n\n\n");

emcc -g4 -O0 --js-opts 0 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s TOTAL_STACK=15000000 -s FS_LOG=1 -s ASSERTIONS=2 --separate-asm --memory-init-file 1 

(JS Console Warn: increasing TOTAL_MEMORY to 33554432 to be compliant with the asm.js spec (and given that TOTAL_STACK=15000000)

RESULT: CRASH: Name﾿� name '__naﾾ�is not defined

Test 3: TOTAL_STACK is much larger, same printf.
printf("\n\n\n\n");

emcc -g4 -O0 --js-opts 0 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s TOTAL_STACK=20000000 -s FS_LOG=1 -s ASSERTIONS=2 --separate-asm --memory-init-file 1

(JS Console Warn: increasing TOTAL_MEMORY to 50331648 to be compliant with the asm.js spec (and given that TOTAL_STACK=20000000)

RESULT: CRASH: Name﾿� name '__naﾾ�is not defined

Test 4: Leave TOTAL_STACK increased, remove one "\n" from printf
printf("\n\n\n");

emcc -g4 -O0 --js-opts 0 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s TOTAL_STACK=20000000 -s FS_LOG=1 -s ASSERTIONS=2 --separate-asm --memory-init-file 1

RESULT: Same as #1 - Fine again.

There must be a max printf string storage someplace, and it's overwriting the function call table? Perhaps the function pointer cast wrappers? I'm not sure where to start looking for this, so I appreciate any pointers.

**Comment by kripken** [comment]
Those operations all affect the layout of things in memory. Adding a char to a string will make the string bigger and it might cause other items after it to be placed at different locations. Changing stack size alters where heap allocations will occur.

Perhaps there is some kind of memory corruption in your code. Does valgrind find anything in a native build? Or perhaps it depends on something nonportable like some sort of assumption on memory alignment or an absolute location for something.

If not, I would start to reduce the testcase, until it's obvious what memory is being overwritten incorrectly. For example, if it prints out a corrupt string, then adding a method that verifies that string is ok, and running it every other instruction, would show where it gets corrupted. (Can use SAFE_HEAP to get a function call on each load and store, which helps add such checks. DETERMINISTIC is helpful if your app has timing issues.) Or, reduce until you end up with a testcase you can attach here for us to debug.

**Comment by cforger** [comment]
Those are good comments - As I'm looking into this, I believe my function pointers are causing some problems, and I'm currently hunting that all down. It may all be an issue of improper function calls.

However, I'd like to understand this a bit more - using EM_ASM(console.log('x')) will also break the code in the same way - from what I understand, that's pure javascript into the browser.  How could more code in JS also cause the same issue? It's outside of the HEAPx arrays. 

It's present in IE as well as Chrome, so I don't think it's a browser issue. I haven't tried FF in a bit.

**Comment by kripken** [comment]
An `EM_ASM` can actually alter memory usage, due to technical reasons. The `EM_ASM` becomes a constant LLVM string which is used as the argument to a special function call, which the backend then handles in a special way and turns it into code on the outside. But the LLVM string is still in memory. (We could optimize it out, but it's not trivial, the use can be through bitcasts and so forth.)

**Comment by cforger** [comment]
Thanks, that's helpful for understanding.

**Comment by cforger** [comment]
Well, interestingly enough, if my printf's are a multiple of 8, they work.

I started with printf("1\n");, then printf("12\n"); , etc. and worked my way up to 7. 1-6 cause memory corruption crashes, but 7 where the issue stopped. Wrapping around another 8 bytes is also okay. 

I understand the significance of this if I were coding straight ASM, but I'm a little unsure of how to proceed with emscripten.

The native application doesn't leak memory, so I assume it's just alignment limitations of emcc compared to native clang x64 builds. 

I'm moving into the FORCE_ALIGNED_MEMORY and WARN_ALIGNED flags to see if I can pinpoint this, and I assume this isn't too chatty for issues - Otherwise I can take it back to groups.

I see #4231, but I wish I had a way of dropping direct console.log's into my C code that just show up in the JS side of things for debugging scaffolding.

**Comment by kripken** [comment]
The JS backend tries to place items in the data segment in an optimal manner, aligned to the minimal amount and with as little empty space in between. Perhaps forcing it to align everything to say 16 (or above) would work around this, and show that the issue is either clang is emitting the wrong alignment for a global, or the code is reading from something that isn't aligned but assuming it is (like a packed struct, which would be undefined behavior). Then perhaps bisect on that.

You can drop console.logs into the compiler output, as it's just JS. That's helpful sometimes. See some notes [here](http://mozakai.blogspot.com/2012/06/debugging-javascript-is-awesome.html). Then you can investigate the crash directly, adding console.logs around the stack trace etc. without changing things.

**Comment by cforger** [comment]
Thanks for the quick response. 

Yes, I can drop them into the compiler output, but I can't drop them into my C source where they stay put, and are of the most use.. I assume the patch in #4231 may give an option here?

If I wanted emcc to force align everything to 16, is there a switch for this? From what I was reading, the FORCE_ALIGNED_MEMORY is slightly depreciated, and is just a bool - or are you suggesting I force my C code to align?

**Comment by kripken** [comment]
(The patch in #4231 isn't close to working.)

I think you can just hack up the JS backend to force alignment. See `allocateAddress` in JSBackend.cpp. You can just force `Alignment` to 32 there for testing.

**Comment by cforger** [comment]
Excellent, thanks.

In the meantime, here's my quick hack to allow console.out directly from C:

emsdk_portable/emscripten/master/src/library.js around 3895, add this:

```
  emscripten_int_triple_out: function(int1, int2, int3) {
    console.log("%d,%d,%d", int1, int2, int3);
  },
```

Add the necessary header to emsdk_portable/emscripten/master/system/include/emscripten/emscripten.h

`void  emscripten_int_triple_out(int, int, int);`

and now you can call from C and get console.log output:
`
emscripten_int_triple_out(88,10,15);`

No muss, no fuss, directly out as there's no strings. It outputs as "88,10,15" so you can search for your int triple and find it in your C source as you scaffold.

I guess I could make a simple string substitution for an int in the JS code as well (1 = 'in main(), 2='starting ints', etc) but this used to work for me in ASM kernel dev, so it should be decent here.

I used to have a small notepad window open where I'd write what my codes meant for reference.

**Comment by cforger** [comment]
I'm still picking away at this, and I'm curious about the order of execution.

I assume the 'stringify' of emcc happens at compile time - that is, my printf's strings are packed into the heap, and replaced with a _puts command that references the memory address of my string. _puts simply reads and puts to the screen until it hits a null.

My code is crashing on trying to look up variable names that are garbage, and the garbage variable name changes based on how many printf's I have - Aligning prinfts with simple padding on 8 chars seems to make the obvious garbage names go away (ie real variable names now appear, execution continues).

How would the pre-execution addition of strings to the heap affect the later storing of variables? The variables are still there, just slightly garbled like it was a UTF8 issue. How is stringifying during compile a 7 byte string causing the error, and when I stringify an 8 byte string the error is no longer present?

Are there UTF8 gotcha's I should be investigating? Initially I thought this was a UTF8 issue (my codebase uses UTF8 in all strings, but I'm only using standard ASCII chars at the code points I'm working on), until I started playing with printfs and stumbled on the 8 byte alignment.

**Comment by cforger** [comment]
.. I also find it interesting that in C:

prinft("12\n"); 

encodes to a _puts, but:

prinft("12");

encodes to a _printf that ultimately never reaches output as I presume the buffer isn't flushed? (even though later printf's come through). Perhaps I can help update the wiki if you can provide a good answer? I know it's obscure behaviour, but it sometimes matters.

**Comment by cforger** [comment]
Well, with the new emscripten_int_triple_out() scaffolding, I was able to track the problem to an issue with the original ./configure script not setting the sizeof's various types/structs properly.

I'll close soon, but I'm still curious to know more about UTF8 / and the non-\n printfs.

**Comment by kripken** [comment]
If you have an 8 byte string, then the global after it will be placed at compile time at address x+8. If 7 bytes, x+7, unless it aligns it. So if not, it might be at an unaligned address, and assuming that second global is aligned can fail.

print("12") indeed can't be turned to a puts since there is no newline. It will be buffered. If there are prints later with newlines and it still doesn't show up, that's very very strange. We have tests for that, so you might be hitting some weird corner case, or maybe it's related to the general issue here (memory corruption?).

**Comment by cforger** [comment]
Thank you, that's all very helpful.
