### ISSUE TITLE
Strings in LibraryManager.library incorrectly treated as dependencies

### ISSUE THREAD

**Issue by poiru** [kripken/emscripten#4244]
First, create the following files:

* `main.cpp`:
```cpp
extern "C" {
  extern void bar();
}

int main() {
  bar();
  return 0;
}
```

* `lib.js`:

```js
mergeInto(LibraryManager.library, {
  foo: 'hello',

  bar__deps: [ 'foo' ],
  bar: function() {}
});
```

When compiling with `emcc --js-library lib.js -s ERROR_ON_UNDEFINED_SYMBOLS=1 main.cpp`, you get the following error:
```
error: unresolved symbol: hello
Aborting compilation due to previous errors | undefined
```
This compiles without error prior to 8c7c1bb.

**Comment by kripken** [comment]
Do you have a testcase showing the issue?

**Comment by poiru** [comment]
@kripken It turns out my original bug report was not the actual issue. I managed to track this down and added a testcase to the PR description.

**Comment by kripken** [comment]
I think the issue is that in JS libs, `x: 'y'` means a redirection. For example, `sqrt: "Math.sqrt"` makes us emit Math.sqrt in place of _sqrt. So the error is valid here, I think? What are you trying to do with `hello`, maybe there is another way?

**Comment by poiru** [comment]
@kripken We already fixed this in our codebase, but I figured this might be a regression. I'm closing the issue since it seems like this is expected behaviour.
