### ISSUE TITLE
unresolved GLFW3 symbols

### ISSUE THREAD

**Issue by NickPowers43** [kripken/emscripten#4250]
When I use the header "GLFW/glfw3.h" found within the "system/include/" directory I get a bunch of unresolved symbol warnings. They are not warnings because I cannot run the application. In the JS file the body of these unresolved functions are substituted with an "abort(-1)" statement.

**Comment by NickPowers43** [comment]
I tried adding both "-lglfw" and "-lglfw3" but neither of these arguments resolve the issue.

**Comment by Blockfinity** [comment]
after changing "GLFW/glfw3.h" to "GL/glfw.h" the issue is resolved. I assume GLFW3 isn't supported in v1.35.0.

**Comment by NickPowers43** [comment]
after changing "GLFW/glfw3.h" to "GL/glfw.h" the issue is resolved. I assume GLFW3 isn't supported in v1.35.0.

**Comment by NickPowers43** [comment]
The issue is resolved. Instead of "-lglfw" I used "-s USE_GLFW=3" and it works now.
