### ISSUE TITLE
"glFenceSync" Incorrect, Should Take Parameters

### ISSUE THREAD

**Issue by retrop** [kripken/emscripten#4260]
In order to make things work, and match the WebGL spec, I needed to change, in library_gl.js :

```
glFenceSync__sig: 'iii',
glFenceSync: function() {
  var id = GL.getNewId(GL.syncs);
  var sync = GLctx.fenceSync();
  sync.name = id;
  GL.syncs[id] = sync;
  return id;
},
```
to
```
glFenceSync__sig: 'iii',
glFenceSync: function(condition, flags) {
  var id = GL.getNewId(GL.syncs);
  var sync = GLctx.fenceSync(condition, flags);
  sync.name = id;
  GL.syncs[id] = sync;
  return id;
},
```

Thanks!

**Comment by kripken** [comment]
Thanks for the issue, do you want to open a PR with this fix?

**Comment by retrop** [comment]
Sure, will make one now.

**Comment by retrop** [comment]
Pull request created:
https://github.com/kripken/emscripten/pull/4289

**Comment by retrop** [comment]
Okay, created a new pull, this time to the "incoming" branch and added to the AUTHORS list:
https://github.com/kripken/emscripten/pull/4339

Thanks!

**Comment by juj** [comment]
Great, thanks, this was merged already some time ago, closing as fixed.
