### ISSUE TITLE
Bug in embind's JS optimizer that affects enum registration

### ISSUE THREAD

**Issue by achoudhury85** [kripken/emscripten#4276]
NOTE: There's currently an active [google groups discussion](https://groups.google.com/forum/#!topic/emscripten-discuss/mCJ5XLsQR-0) on this, pasting below for poserity.

On 1.36.1, I've found a bug where Emscripten's JS optimizer seems to be removing a local function within the __embind_register_enum function in embind.js if built with -O3 optimization. This is the piece of code that's being removed:

 ```
 _embind_register_enum: function(
    rawType,
    name,
    size,
    isSigned
  ) {
   ...
    // The constructor function is removed
    function constructor() {
    }
    ...
  },
```

I haven't yet root caused why the constructor function is being removed. But as a result, we are no longer referring to a local function object when registering the enum type, but a global value named constructor. As a result, if you end up registering a second enum, the values for the first enum get overwritten (since we set constructor.values = {}) and this results in undefined behavior later on.

I've also put together a repro for Windows: https://github.com/achoudhury85/Embind-Enum-Registration-Issue

**Comment by kripken** [comment]
When i build and run here, it prints

````
Enum2: 2
Enum1: 3
````

Does that mean I'm not seeing the problem?

Are you on latest incoming? What OS, etc?

**Comment by achoudhury85** [comment]
Hey Alon, this is on Windows - we're running off the 1.36.1 branch.

**Comment by achoudhury85** [comment]
Yeah - you will see a callstack saying "value is not defined" if you run into the problem. Looks like its not reproing for you.

**Comment by kripken** [comment]
Ok, might be a windows-specific bug then. Hopefully someone can try to repro this there.

**Comment by achoudhury85** [comment]
Hey Alon, I think this may be arising from changes that we made locally to our fork of 1.36.1 (although the changes are quite minimal). I can't repro off vanilla 1.36.1. 

Sorry about the confusion, I'll close this one out.
