### ISSUE TITLE
Cannot access __m128 union members, error generated

### ISSUE THREAD

**Issue by rahulchaphalkar** [kripken/emscripten#4279]
the __m128 in xmmintrin.h is a union, however when you try to access its member, for example qs4.m128_f32[1] , where qs4 is __m128 variable, I get the error "member reference base type '__m128'
      (aka 'const float32x4') is not a structure or union"
Repro Case: (compile with -msse2 flag)

#include \<emmintrin.h\>
#include \<xmmintrin.h\>

 void SetAngle(const __m128 angle4, __m128 qs4)
    {	   	qs4.m128_f32[0] = sinf(angle4.m128_f32[0]);	
	}	
	int main()
	{
				return 0;
	}

**Comment by kripken** [comment]
@juj, you're the expert on this - any idea?

**Comment by juj** [comment]
The internal structure of `__m128` is implementation-specific and there's no guarantee that any fields would be present. Even on a single compiler, there might not exist guarantees that the fields would remain in compiler updates (unless a compiler documentation explicitly promised that). Also things like just accessing lanes of a `__m128` by array index notation, e.g. `__m128 a; float f = a[1];` is not portable.

The `float __m128::m128_f32[4]` fields are Microsoft Visual Studio specific union structures. In GCC and Clang (and hence in Emscripten), vector types can be access via the array index notation above. 

The portable way is to use the SSE intrinsic functions to extract and insert elements to specific lanes.

@rahulchaphalkar: Perhaps it might be interesting to look at something like this Stackoverflow post, which is about a manual workaround to attempt to create a portable alias: http://stackoverflow.com/questions/19902123/compiler-support-of-members-of-sse-vector-types-like-m128-f32x . Alternatively you could create getters and setters for invididual fields, see e.g. `setx_ps(), sety_ps(), setz_ps()` and `setw_ps()` in https://github.com/juj/MathGeoLib/blob/master/src/Math/simd.h#L379 and `s4f_x(), s4f_y(), s4f_z()` and `s4f_w()` in https://github.com/juj/MathGeoLib/blob/master/src/Math/simd.h#L297.
