### ISSUE TITLE
warning : unresolved symbol : _Z4freePv

### ISSUE THREAD

**Issue by ToniKroos** [kripken/emscripten#4290]
Hello!

I'm trying to compile c code to js

But this warning should occur .

warning: unresolved symbol: _Z4freePv
warning: unresolved symbol: _Z6getenvPKc
warning: unresolved symbol: _Z6mallocj

I was included.

#include <stdlib.h>

Why it would not include ?

somebody help me :)

**Comment by juj** [comment]
The functions `free`, `getenv` and `malloc` are C functions and should not receive C++ name mangling. Are you declaring those functions manually by any chance, and are missing an `extern "C" { ... }` directive from the declaration?

If that doesn't give a clue, can you post a full minimal test case?

**Comment by ToniKroos** [comment]
thank you juj

i code problem. It was resolved.

missing include header.

**Comment by juj** [comment]
Sweet, let me close as resolved.
