### ISSUE TITLE
Static Local Constructor Not Called

### ISSUE THREAD

**Issue by throwthisaway** [kripken/emscripten#4297]
Hi,
I am using emscripten 1.35.0 on Windows 10:
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp.git 4e83be90903250ec5142edc57971ed4c633c5e25)

clang -cc1 version 3.7.0 based upon LLVM 3.7.0svn default target x86_64-pc-windows-msvc

[main.zip](https://github.com/kripken/emscripten/files/252956/main.zip)

I compiled the attached main.cpp in the zip file with:
emcc main.cpp -v -o main.html

It seems, when std::cerr is linked/referenced, the static local variable d in class Particles is not initialized.

If I don't reference std::cerr, it seems ok.

I tested with Microsoft Edge and Chrome, the result is the same.

**Comment by kripken** [comment]
What are the specific steps to take to see the problem? I built it and ran it, and nothing seemed obviously wrong.

**Comment by throwthisaway** [comment]
Check the console log the constructor for variable d is not called.

**Comment by throwthisaway** [comment]
for me, the output is:

**Comment by kripken** [comment]
I can't reproduce the problem, I see in the console.

````
A ctor. 0 3f80a.js:5879:11
A ctor. 1 3fb0a.js:5879:11
A ctor. 2 3fd0a.js:5879:11
A ctor. 3 3ff0a.js:5879:11
A ctor. 4 4010a.js:5879:11
A ctor. 5 4030a.js:5879:11
A ctor. 6 3f98
````

That's on emscripten incoming. Perhaps it was fixed since your version.

**Comment by throwthisaway** [comment]
Thanks, I try with a later version.
