### ISSUE TITLE
Does embind support 1) pointer as return value 2) reference as function arguments?

### ISSUE THREAD

**Issue by cnyzgkn** [kripken/emscripten#4308]
I am trying to use embind to convert C++ code to Javascript.
It seems embind doesn't support 1) pointer as return value 2) reference as function arguments.

1). pointer as return value in a virtual function 
class myClass
{
    virtual const char*  conName(handle* h) =0;
}

struct Wrapper : public wrapper<myClass> {
        EMSCRIPTEN_WRAPPER(Wrapper);
            …
            const char*  conName(handle* h) override {       
            return call<const char*>("conName", h); 
            …
}  
 
EMSCRIPTEN_BINDINGS(myClass) {
            class_<myClass>("myClass”)
            …
            .function("conName", &myClass::conName, pure_virtual(), allow_raw_pointers())
            …
}

It has error as below:
emscripten/wire.h:86:13: error: static_assert failed “Implicitly binding raw pointers is illegal. Specify allow_raw_pointer<arg<?>>"
wrapper.cpp:3036:16: note: in instantiation of function template specialization 'emscripten::wrapper<myClass>::call<const char *,
      handle *&>' requested here
        return call<const char*>("conName", h);

2. reference as function arguments
virtual void func(Point3d& pt) = 0;
{ ...}

.function("func", &MyClass::func, allow_raw_pointers, pure_virtual())

It has error as below:
non-const lvalue reference to type 'Point3d' cannot bind to a temporary of type 'Point3d'

Can anyone helped me about it?

**Comment by kivancyuksel** [comment]
Hello,
I was wondering if you have any answer to your own question. I also would like to know the answer.

Thank you.
