### ISSUE TITLE
Consider renaming/deprecating `Module.requestFullScreen` -> `Module.requestFullscreen`

### ISSUE THREAD

**Issue by cvan** [kripken/emscripten#4310]
[See this line.](https://github.com/kripken/emscripten/blob/5f091840/src/library_browser.js#L6)

The unprefixed API (now available in Firefox Nightly) is called `requestFullscreen` (instead of Firefox's previously named `requestFullScreen` - not to be confused with every other vendor's `requestFullscreen`). See the [spec](https://fullscreen.spec.whatwg.org).

**Comment by kripken** [comment]
This could be a breaking change for users. How about supporting both on `Module`?

**Comment by cvan** [comment]
yeah, I would recommend supporting both. and possibly throw a deprecation warning when calling `requestFullScreen`. and then in a few years (or possibly never) remove it.

**Comment by juj** [comment]
If we do this, we should be consistent to do it everywhere the same, and super careful to know what we deprecate on the user facing API and how it will affect developers. Pull request #4318 tries to do this diligently to illustrate.

**Comment by juj** [comment]
Ok, this was implemented in the above pull request, closing as resolved.
