### ISSUE TITLE
Call unprefixed Fullscreen API first

### ISSUE THREAD

**Issue by cvan** [kripken/emscripten#4311]
[This line](https://github.com/kripken/emscripten/blob/5f091840/src/library_browser.js#L332) causes a deprecation warning in Firefox:

```
Prefixed Fullscreen API is deprecated
```

<img width="897" alt="screen shot 2016-05-11 at 2 52 16 pm" src="https://cloud.githubusercontent.com/assets/203725/15199050/49bc9250-1790-11e6-8e00-ab04f964e692.png">

**Comment by juj** [comment]
Thanks! This was also fixed in #4318.
