### ISSUE TITLE
emscripten_get_callstack returns different count of bytes across browsers

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#4319]
I don't know if this is a technical limitation or not, but `emscripten_get_callstack` returns different callstack size depending on which browser it is running on. For instance, it seems on Google Chrome it always returns 6 or 7 first lines of the callstack, while on Firefox it always return the full callstack.

**Comment by kripken** [comment]
Browsers report stack traces a little differently, this is probably because of that. Unless you see an invalid call stack, then we should investigate that.

**Comment by gouletr** [comment]
The callstack isn't invalid. It's just more difficult to use because it is missing a lot of context lines. At least Firefox gives us the full callstack. If it's really a browser issue, then we can close this.

**Comment by gouletr** [comment]
Actually I was wondering... any idea why all our callstack begin with:
```
...
at dynCall_vi
at Runtime.dynCall
at _emscripten_set_main_loop/browserIterationFunc
at Browser.mainLoop.runIter
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
at FrameRequestCallback*requestAnimationFrame
at Browser_mainLoop_scheduler_rAF
at Browser_mainLoop_runner
```
all these requestAnimatFrame, why is that?

**Comment by kripken** [comment]
I suspect the browser may be trying to un-async the stack trace? so it shows a stack trace over separate invocations? if that's not it, maybe the line numbers shown indicate we are recursing, but we really shouldn't be doing that AFAIK.

**Comment by gouletr** [comment]
I'm not sure how this graph works in Firefox, does it look right to you? i.e. is there any recursion?
![image](https://cloud.githubusercontent.com/assets/6430434/15292950/a21f26d0-1b53-11e6-9dcb-996dd55754fb.png)

**Comment by kripken** [comment]
That's the timeline, I think? It doesn't indicate recursion, it shows what happens after what. I think it shows separate calls to that method, without recursion, but I could be wrong.

**Comment by gouletr** [comment]
Right, I wasn't sure. I verified the line numbers in the callstack and they don't change. So it just pollute the callstack with unnecessary spam. But I don't know if that's avoidable. Feel free to close this bug if you think that's unrelevant. Thanks!

**Comment by gouletr** [comment]
Not an issue in Emscripten, closing.
