### ISSUE TITLE
pthreads support in chrome?

### ISSUE THREAD

**Issue by seibelj** [kripken/emscripten#4323]
This website: https://github.com/tc39/ecmascript_sharedmem

Says that you can enable SharedMemoryBuffer in Chrome 48+ using command line flags. Does emscripten support pthreads in chrome if this is enabled? Reading through various documents, it appears that this feature is the linchpin of pthread support.

**Comment by kripken** [comment]
Yes, it should work. There are some limitations (see [docs](https://kripken.github.io/emscripten-site/docs/porting/pthreads.html)) but overall it should be close to true pthreads.

**Comment by juj** [comment]
Let me close this as resolved, as per kripken's answer above. You'll need to use Chrome Canary to use the feature I think. If something doesn't work, please open as a new issue (or reopen here if it makes sense)
