### ISSUE TITLE
Any way to cache dynCall lookup?

### ISSUE THREAD

**Issue by jdwissler** [kripken/emscripten#4326]
I'm aware that I can dynamically run a function via a pointer using [dynCall](http://stackoverflow.com/questions/25576458/calling-a-function-pointer-with-emscripten). 

Is there any way to just ask for the function, but not to run it? I don't see the reason to keep looking up the function more than once. Is there something I'm missing?

**Comment by kripken** [comment]
dynCall calls into the asm.js module. The module does not export methods, it just provides a way to call into it and to call methods by an index in a table. This makes things easier for JS engines to optimize, however, it means that you can't get a direct reference to the method.
