### ISSUE TITLE
SIMD.Int8x16.fromInt32x4 generated although it is not in Simd js spec

### ISSUE THREAD

**Issue by rahulchaphalkar** [kripken/emscripten#4341]
Emscripten generates `SIMD.Int8x16.fromInt32x4`, which is not part of the simdjs spec.
Following simple test code:

    #include <emmintrin.h>
    int main()
    {
         __m128i a;
         __m128 c;
         a=_mm_add_epi8(a,_mm_castps_si128(c)); 
        return 0;
    }

**Comment by kripken** [comment]
Which version is this with? The SIMD stuff has been changing a lot.

**Comment by rahulchaphalkar** [comment]
1.36.3
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.3
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ ebce0a585917af1f69cc372c3730a709ea97dc8c) (https://github.com/kripken/emscripten-fastcomp/ 8f1637cd5980ed8172b3874b6fdbd2f7829f92ed) (emscripten 1.36.3 : 1.36.3)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin
INFO:root:(Emscripten: Running sanity checks)

**Comment by juj** [comment]
Thanks, I see that we generated asm.js imports for such patterns. SIMD has casts between all non-bool types, but conversion operators only for types that have same number of lanes. This was not correctly distinguished before. Fixed that in the above commit.
