### ISSUE TITLE
%1 is not a valid win32 application

### ISSUE THREAD

**Issue by cyberorg012** [kripken/emscripten#4354]
Hi Guys,

I was trying to compile ffmpeg using emscripten and i am getting %1 is not a valid win32 application on Windows 10 x64 bit machine.

Can you please help me out in this?

**Comment by juj** [comment]
This means that the build system is trying to call an executable that does not exist. What is the full log of commands you typed and the results you got? Does ffmpeg build system by chance require Unix-based shell? (`./configure` based build system won't work on Windows)

If the logs don't give any hints, try setting the environment flags

    set EM_BUILD_VERBOSE=3
    set EMCC_DEBUG=1

before building. Does that give any debug info about what it's trying to invoke?

**Comment by mosra** [comment]
Maybe this can help you: in my case it was because I was using `emcc` instead of `emcc.bat` (and similarly for the other executables).

**Comment by cyberorg012** [comment]
Hello Juj,

I am getting this message.

C:\Program Files\Emscripten\ffmpeg>emconfigure ./configure --cc=emcc --disable-gpl
configure: ['./configure', '--cc=emcc', '--disable-gpl']
ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure --cc=emcc --disable-gpl"!
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\\emconfigure", line 41, in <module>
    shared.Building.configure(sys.argv[1:])
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\shared.py", line 1140, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout
, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by dslater38** [comment]
I get the same error anytime I try to use emconfigure on a configure script. I am running emconfigure from inside the Emscripten Command Prompt. It looks like popen is trying to execute a script.

Here's my output:
D:\Dev\build-make>emconfigure.bat ..\make-4.2.1\configure
ERROR:root:Exception thrown when invoking Popen in configure with args: "..\make-4.2.1\configure"!
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\\emconfigure", line 41, in <module>
    shared.Building.configure(sys.argv[1:])
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\shared.py", line 1140, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else st
derr, env=env)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

D:\Dev\build-make>

**Comment by juj** [comment]
`./configure` is a bash script, which are not supported by Windows. One might be able to use Cygwin or MSYS to emulate bash on Windows, but that might have a hard time working, since that is an emulation environment that the ffmpeg build system might not expect. Projects that require `configure` scripts are recommended to be built on a Linux or a Mac OS X system. I'll close this as unsupported.
