### ISSUE TITLE
Simd Autovectorization not being used?

### ISSUE THREAD

**Issue by rahulchaphalkar** [kripken/emscripten#4361]
Emscripten doesn't seem to use simd autovectorization (-s SIMD=1). A simple example i tested on is:
/*start*/
#include<stdio.h>
int main() {
	unsigned int a[1000];
	unsigned int b[1000], c[1000], i = 0;
	unsigned int size = 1000;

	for (i = 0; i < size; i++) {
		a[i] = i+2;
		b[i] = i+1;
		c[i] = 0;
	}
	for (i = 0; i < size; i++) {
		c[i] = (a[i] + b[i]);
	}
	return 0;
}
/*End*/
Compiling with:
emcc -O3 -s SIMD=1 Source.cpp -o Source.js
(i've tried different opt levels too)

My emscripten version is:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.3
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ ebce0a585917af1f69cc372c3730a709ea97dc8c) (https://github.com/kripken/emscripten-fastcomp/ 8f1637cd5980ed8172b3874b6fdbd2f7829f92ed) (emscripten 1.36.3 : 1.36.3)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin
INFO:root:(Emscripten: Running sanity checks)

Am I missing something?

**Comment by kripken** [comment]
First thing I would check is if clang can autovectorize that code in a native build. Autovectorization is not very predictable, so it's possible clang just fails on this example.

See the `test_autovectorize_*` tests for examples of autovectorization working, where we verify that there is vectorized code in the output.

**Comment by rahulchaphalkar** [comment]
Thanks for that. Where are the test_autovectorize_* tests located? I looked in emscripten/tests and couldnt find it there.

**Comment by rahulchaphalkar** [comment]
Its autovectorizing now with Simd. Thanks for the help.
