### ISSUE TITLE
locale.cpp error conversion from 'long' to 'const mask *'

### ISSUE THREAD

**Issue by shooshx** [kripken/emscripten#4362]
After doing a `emcc --clear-cache` I can no longer compile even the simplest code
running `em++ hello.cpp -o hello.html`
results in:

```
WARNING:root:generating system library: libcxx.a...
C:\lib\Emscripten\emscripten\1.35.0\system\lib\libcxx\locale.cpp:88:18: error: no matching constructor for initialization of 'std::__1::ctype<char>'
    ::new (&buf) T(a0, a1, a2);
                 ^ ~~~~~~~~~~
C:\lib\Emscripten\emscripten\1.35.0\system\lib\libcxx\locale.cpp:178:14: note: in instantiation of function template specialization 'std::__1::(anonymous namespace)::make<std::__1::ctype<char>, long, bool, unsigned int>' requested here
    install(&make<_VSTD::ctype<char> >(nullptr, false, 1u));
             ^
C:\lib\Emscripten\emscripten\1.35.0\system\lib\libcxx\locale.cpp:899:14: note: candidate constructor not viable: no known conversion from 'long' to 'const mask *' (aka 'const unsigned short *') for 1st argument
ctype<char>::ctype(const mask* tab, bool del, size_t refs)
             ^
C:\lib\Emscripten\emscripten\1.35.0\system\include\libcxx\__locale:516:24: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
class _LIBCPP_TYPE_VIS ctype<char>
                       ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

for some reason `nullptr` is interpreted as a `long` but I can't figure out why.
Maybe its some partical cache stuck somewhere?
In what directory is the cache saved?

**Comment by kripken** [comment]
The cache will be in `~/.emscripten_cache`.

We did change some libc++ things recently, however, things look ok on the bots. Perhaps make sure you are on very latest incoming, there might be a slightly previous commit that is bad?

**Comment by shooshx** [comment]
I reinstall 1.35.0 and the problem went away...
BTW, how come 
```
emsdk update
emsdk install latest
emsdk activate latest
```
(from https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html)
doesn't bring me to the 1.36.5? I do it but it still remains in 1.35.0 and nothing is changed...

Also, how come the changelog
https://github.com/kripken/emscripten/blob/master/ChangeLog.markdown
was updated as far back as v1.34.12: 10/13/2015 ?
is there a more up to date changelog?

**Comment by kripken** [comment]
Not sure about both. ccing @juj

**Comment by shooshx** [comment]
Err.. nothing?

**Comment by juj** [comment]
Emsdk install of `latest` downloads the latest precompiled build. This is to accommodate for people who don't have compilers installed or don't want to build from source. If you want to build manually, you can do

- `emsdk install sdk-1.xx.y-64bit` (run `emsdk update` before that to populate the latest list of tags) to build from source one of the tagged versions
- `emsdk install sdk-master-64bit` to build from source the current master branch
- `emsdk install sdk-incoming-64bit` to build from source the current incoming branch

ChangeLogs are updated around the time of a release. To find the latest ChangeLog, have a peek at the version in the incoming branch as opposed to the master branch. That should be more up to date.

**Comment by shooshx** [comment]
Thanks!
