### ISSUE TITLE
.gch not recognized

### ISSUE THREAD

**Issue by jenvannier** [kripken/emscripten#4363]
After doing: 
`em++ -c -xc++-header file.h`
and
`em++ -include-pch file.h.gch -DEMSCRIPTEN otherfile.cc -o output.bc`
I get:
`ERROR:root:file.h.gch: Input file has an unknown suffix, don't know what to do with it!`
(With the newest version of the sdk installed.)

Ideas?

**Comment by kripken** [comment]
In `tests/test_other.py` it looks like we do test in `test_precompiled_headers` that `.gch` works. Does that test pass for you?

When you say newest version, is that newest master, or incoming? What is the version number?

**Comment by jenvannier** [comment]
Strangely, that test does pass, and emcc -v gives me:

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
INFO:root:(Emscripten: Running sanity checks)
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

**Comment by kripken** [comment]
Check if the test contains that suffix - maybe it was added after that version, in which case upgrading might fix things for you.

**Comment by jenvannier** [comment]
It does have that test/suffix... This is quite weird. I also double checked the test against the one in the master branch on your github, and it's the same.

**Comment by kripken** [comment]
Must be a subtle difference then. I would just run the commands the test does manually, then compare them to what fails. Somewhere along the line between the two is a difference that matters somehow.

**Comment by jenvannier** [comment]
Mystery seemingly solved? I had to go to incoming instead of latest (from the emsdk), but it recognizes .gch files now. However, it still isn't using them--even with the include flag....

**Comment by jenvannier** [comment]
I rescind that last bit! It is completely working. However, either something is off in emsdk install latest or there was something locally very wrong. 

Thanks for your help!

**Comment by kripken** [comment]
Good, glad it's working.

Side note @juj, there seem to have been more reports of things not working with the emsdk recently. Either we have a lot more people using it, or something might be wrong?
