### ISSUE TITLE
emcmake cmake on Windows

### ISSUE THREAD

**Issue by ramonberrutti** [kripken/emscripten#4364]
Hi, I'm getting this error:

`emcmake cmake ../../ -DCMAKE_BUILD_TYPE=Debug
ERROR:root:Exception thrown when invoking Popen in configure with args: "cmake -DCMAKE_CROSSCOMPILING_EMULATOR="D:/Programming/Libraries/Emscripten/node/4.1.1_64bit/bin/node" ../../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=D:\Programming\Libraries\Emscripten\emscripten\1.35.0\cmake\Modules\Platform\Emscripten.cmake -G MinGW Makefiles"!
Traceback (most recent call last):
  File "D:\Programming\Libraries\Emscripten\emscripten\1.35.0\emconfigure", line 41, in <module>
    shared.Building.configure(sys.argv[1:])
  File "D:\Programming\Libraries\Emscripten\emscripten\1.35.0\tools\shared.py", line 1140, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "D:\Programming\Libraries\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\Programming\Libraries\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified`

is there a chance to build with Windows? Or i need to change to linux?

**Comment by juj** [comment]
Does both `emcmake` and `cmake` exist in `PATH`? E.g. try running

    > where emcmake
    > where cmake

in command line. That should print out the location of emcmake and cmake on your system. If either of those commands doesn't print anything, then it means that the command was not found in PATH. If so, try adding CMake to path manually after installing?

**Comment by ramonberrutti** [comment]
Thanks, I don't know why cmake remove from path, now all work perfect. THANKS!!

**Comment by kripken** [comment]
Great, looks like we can close this.

**Comment by farazirfan47** [comment]
My paths are set correctly but still I am showing this error:

`ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure"!
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\\emconfigure", line 41, in <module>
    shared.Building.configure(sys.argv[1:])
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\shared.py", line 1140, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Program Files\Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified`

What should be the problem ?

**Comment by juj** [comment]
`./configure` scripts (https://en.wikipedia.org/wiki/Configure_script) are a completely separate architecture from CMake (https://cmake.org). CMake is supported on Windows with Emscripten, when one uses CMake's MinGW Makefiles or NMake Makefiles generators, but Windows does not support `./configure` scripts, since those are a Unix abstraction.

It is possible to emulate some amount of `./configure` support for Windows with third party projects such as MSYS or Cygwin, but with those tools, it is very much project-specific whether it will work or not. In general it would be recommended to use a Linux or OS X system to build projects that use `./configure` scripts.
