### ISSUE TITLE
EXTRA_EXPORTED_RUNTIME_METHODS not considered for functions exported from library_fs.js

### ISSUE THREAD

**Issue by AlexPerrot** [kripken/emscripten#4375]
Hi,

When trying to add FS exported functions (such as `FS_writeFile` which is not exported by default), adding them to `EXTRA_EXPORTED_RUNTIME_METHODS` has no effect since only `EXPORTED_RUNTIME_METHODS` is considered there.

See line 8 of library_fs.js :
https://github.com/kripken/emscripten/blob/incoming/src/library_fs.js#L8

Maybe it would be better to merge the two list at the beginning of the code so that everything is considered everywhere ?

**Comment by kripken** [comment]
Yes, I agree, that sounds like what we should be doing.

**Comment by froydnj** [comment]
@kripken, can you close this, please, since a fix has been merged?
