### ISSUE TITLE
Corrupt static memory with certain order for constant arrays in LLVM IR

### ISSUE THREAD

**Issue by Maher4Ever** [kripken/emscripten#4388]
Hello,

It seems like I keep going through uncharted territories when it comes to my use of Emscripten :sweat_smile:. Just to give you a bit of context for the code to come, I'm converting some scientific formulas from Python to JS using Emscripten. 

Here is an (artificial) piece of LLVM IR that causes Emscripten to generate corrupted static memory:

```llvm
; ModuleID = 'func'
target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

@.const.picklebuf.87005624 = internal constant { i8*, i32 } { i8* getelementptr inbounds ([68 x i8], [68 x i8]* @.const.pickledata.87005624, i32 0, i32 0), i32 68 }
@.const.pickledata.87005624 = internal constant [68 x i8] c"\80\04\959\00\00\00\00\00\00\00\8C\08builtins\94\8C\11ZeroDivisionError\94\93\94\8C\10division by zero\94\85\94\86\94."
@.const.array.data = internal unnamed_addr constant [16 x i8] c"\D7\A3p=\0A\D7\0F@)\5C\8F\C2\F5\B0X\C0"

define double @func({ i8*, i32 }** noalias nocapture %excinfo, i32 %arg.i) {
entry:
  %.75 = icmp eq i32 %arg.i, 0
  br i1 %.75, label %B0.if, label %B0.endif

B0.if:                                            ; preds = %entry
  store { i8*, i32 }* @.const.picklebuf.87005624, { i8*, i32 }** %excinfo, align 4
  ret double -1.0

B0.endif:                                         ; preds = %entry
  %.49 = icmp slt i32 %arg.i, 0
  %.50 = add i32 %arg.i, 2
  %.51 = select i1 %.49, i32 %.50, i32 %arg.i
  %.64 = getelementptr double, double* bitcast ([16 x i8]* @.const.array.data to double*), i32 %.51
  %.65 = load double, double* %.64, align 8
  %.74 = sitofp i32 %arg.i to double
  %.79 = fdiv double %.65, %.74
  ret double %.79
}
```

Which is generated for the following (again artificial) Python code:

```python
from numba import njit, int32, double
import numpy as np

m = np.array([
    3.98, -98.765
])

@njit(double(int32))
def func(i):
    return m[i]/i
```

The reason why I'm showing the Python code is primarily to show the array `m`. Take note of its contents (**very important**). In the LLVM IR the `m` doubles array is encoded in the constant `@.const.array.data` as a byte array. The other constants are for the error message when a division by zero exception (in Python) occurs.

Now compile this code to JS with `emcc` (I'm using a 32bit build of the `incoming` branch) with the safe heap option and inspect the non-zero values of `HEAPF64` (using something like `var a = []; Module.HEAPF64.forEach(function(d) { if (d) a.push(d); }); console.log(a);` in the browser console). This is what I get:

```
[1.26e-321, 1.442957137935e-312, 4.773006783e-315, 1.0229740447153298e+200, 3.8605904883640124e-224, 1.0721665630297753e+200, 6.991778850694503e+228, 4.799529050176886e+199, 4.731097339934439e+164, -8.795204061049155e-282, 9.458746129691594e-13, -4310086189562.88, 1.5943685845e-314, 1.1545414596185118e-298]
```

The two values of the `m` array should be in there but that's not the case. After a while I figured out how to get it working. All it takes is to put the byte array for `m` at the top of the constants definitions in the LLVM IR file:

```llvm
; ...

; The array data is now at the top
@.const.array.data = internal unnamed_addr constant [16 x i8] c"\D7\A3p=\0A\D7\0F@)\5C\8F\C2\F5\B0X\C0"
@.const.picklebuf.87005624 = internal constant { i8*, i32 } { i8* getelementptr inbounds ([68 x i8], [68 x i8]* @.const.pickledata.87005624, i32 0, i32 0), i32 68 }
@.const.pickledata.87005624 = internal constant [68 x i8] c"\80\04\959\00\00\00\00\00\00\00\8C\08builtins\94\8C\11ZeroDivisionError\94\93\94\8C\10division by zero\94\85\94\86\94."

; ...
```

Compile the code again to JS and check the heap again. Voila (3rd and 4th items below):

```
[1.26e-321, 1.442957138014e-312, 3.98, -98.765, 4.773006783e-315, 1.0229740447153298e+200, 3.8605904883640124e-224, 1.0721665630297753e+200, 6.991778850694503e+228, 4.799529050176886e+199, 4.731097339934439e+164, -8.795204061049155e-282, 3.86105245e-315, 1.1545414596185118e-298]
```

In the generated JS files you will also notice that the `allocate` function is called with a different array of numbers (not only the order, but also the values differ). This leads me to conclude that if the constants are defined in a certain order then Emscripten will generate JS code with corrupt static memory. If you need any more info I'll be happy to help.

**Comment by kripken** [comment]
My guess is this is an alignment issue. `unnamed_addr constant [16 x i8]` is just an array of bytes, with alignment 1. But the double loads declare alignment 8. That works on x86, but will fail on arm and asm.js, and is nonportable.

Try to make the alignment on the double loads 1, that could fix it. A better fix might be aligning the global constant.

**Comment by Maher4Ever** [comment]
Thank you for the response. i tried changing the alignment in the load instruction to 1 but the static memory remains corrupted. I agree with you that the generated LLVM IR should align the global constant, so I'll report this to the Numba team and see if they can fix that. 

I'll close this issue for now until I have their response.
