### ISSUE TITLE
compiler-rt fails with wasm backend

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4389]
When I clear the cache and build bananabread, it tries to build compiler-rt but hits

````
WARNING:root:generating system library: wasm_compiler_rt.a...
In file included from /media/alon/d69dd9b2-4791-4b8e-aeb3-f6353b45d710/home/alon/Dev/emscripten/system/lib/compiler-rt/lib/builtins/addtf3.c:16:
In file included from /media/alon/d69dd9b2-4791-4b8e-aeb3-f6353b45d710/home/alon/Dev/emscripten/system/lib/compiler-rt/lib/builtins/fp_lib.h:24:
In file included from /media/alon/d69dd9b2-4791-4b8e-aeb3-f6353b45d710/home/alon/Dev/llvm/build/bin/../lib/clang/3.9.0/include/stdint.h:63:
In file included from /usr/include/stdint.h:25:
/usr/include/features.h:374:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^
````

The bad thing seems to be that `fp_lib.h` looks in a clang header - not our portable headers - and that sends it to `/usr/include` which is of course totally wrong, and on my machine happens to hit an error.

**Comment by kripken** [comment]
cc @dschuff @sunfishcode

**Comment by kripken** [comment]
First problem here is that we called clang without telling it of our include dirs, so it was using system include dirs nonportably. Fixed that in 1d979a75722a513b586e6705d662ff4ee0ea832b

**Comment by kripken** [comment]
Looks like that's sufficient. Fix in binaryen appears green, https://github.com/WebAssembly/binaryen/pull/611

**Comment by cpitclaudel** [comment]
Unrelated, but this may be useful here since this post was the first one I found on Google for this `fatal error: 'sys/cdefs.h' file not found` issue.

This can be caused by cmake assuming `-l/usr/include/`, which confuses emscripten because that path contains system libraries.  This happens in particular when using boost; see http://vclf.blogspot.com/2014/08/emscripten-linking-to-boost-libraries.html

**Comment by kgritesh** [comment]
@cpitclaudel i am facing the same problem as you mentioned. I am a newbie and haven't done system programming. Can you help?

**Comment by pans0ul** [comment]
> Another cause of this can be that configure isn't picking up the right compiler when running emconfigure. This happened to me because my ./configure checks whether the compiler in `$CXX` points to an executable program, and otherwise falls back to `g++`. emscripten had `python …/emsdk-portable/emscripten/1.37.36/em++.py`, which wasn't recognized as executable.

Hi, I met same issue , how can I solve it ?

**Comment by sbc100** [comment]
Can you post the full command you are running and its output?   Perhaps open another issue since this one is very old now and a has likely changed.

**Comment by pans0ul** [comment]
> Can you post the full command you are running and its output? Perhaps open another issue since this one is very old now and a has likely changed.

thank you reply .

I open another issue : https://github.com/emscripten-core/emscripten/issues/10818

I'll describe my situation as much as possible 
thank you
