### ISSUE TITLE
Compiler bug: exceptions not caught correctly under some circumstances

### ISSUE THREAD

**Issue by haukeduden** [kripken/emscripten#4390]
Under some circumstances exception catching does not work correctly. This happened in a more complicated real-world project, but I was able to distill the problem down to a relatively simply sample file. I have attached the source file in the following ZIP:

[test.zip](https://github.com/kripken/emscripten/files/306486/test.zip)

In this example code, an exception is thrown from the constructor of the Thrower instance inside throwerFunc.

It would be expected that the exception is immediately caught inside throwerFunc. "ok" should be printed and the app should exit normally.
This does not happen. The catch block inside throwerFunc does not catch the exception. Instead the exception is propagated upwards to the main function, which DOES catch it. This is clearly a compiler bug.

As far as I can see all the components remaining in the file are mandatory to reproduce the bug. If one of the components is changed (if-statement removed, Dummy object in throwerFunc removed, function call in if condition replaced by constant, exception thrown from something other than a constructor, Dummy class not having destructor) then the bug does NOT happen anymore. So this seems to be pretty much the minimal code needed to reproduce the bug.

The file was compiled and linked with em++ 1.35.0 with the following commandline:

em++  -std=c++11 -stdlib=libc++ -s DISABLE_EXCEPTION_CATCHING=0 test.cpp -o test.bc 
em++ --emrun  test.bc -o test.html

It was then executed with this commandline:
emrun --browser safari test.html

**Comment by kripken** [comment]
Looks like this was fixed, it prints `ok` on `1.36.1`. Probably fixed by the libc++ update we did recently.

**Comment by haukeduden** [comment]
You are right - I just confirmed with the "incoming" release. I was unaware that I was using an outdated version - my apologies.
