### ISSUE TITLE
Move sbrk() and ownership of DYNAMICTOP inside asm.js?

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4391]
Currently one source of proxying we need to do is when `sbrk()` is called. While prototyping multithreaded filesystem, I realize this is very problematic. Would it be possible to move `sbrk()` to be implemented in C, and additionally, DYNAMICTOP to be implemented as a value in a memory location inside the asm.js heap as opposed to being a thread local variable?

**Comment by kripken** [comment]
If this is important enough we could do it. Various stuff looks at DYNAMICTOP from JS, e.g.

 * memory growth code
 * SAFE_HEAP code (to know what is an invalid address)
 * memory profiler
 * possibly dynamic linking code
 * etc.

All fixable, we'd just need to do the same thing we do with STACKTOP basically - have everyone outside of asm.js read it using a function. Probably a few days of work.

The only downside aside from the work is that existing user code might look at it, and this could break it. But it's an internal implementation detail we never recommended people use, so it's probably fine.

**Comment by juj** [comment]
That sounds good. I'll hack something temporary up in the emscripten_fetch branch and let's have a look at this next week.

**Comment by juj** [comment]
Spliced this off of the rest of the emscripten_fetch work, as it is useful to optimize the performance of current pthreads-enabled applications as well, since it removes one current source of proxying we have. (and as any source of proxying is a potential for deadlocking if the main thread is running a busy spinning loop without any cancellation points). See the PR #4496.

**Comment by juj** [comment]
Done in above PR now, closing.
