### ISSUE TITLE
Warning "ELAST for this platform not yet implemented" when building libcxx

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4393]
When building the system libraries, libcxx gives the following warning:

    ELAST for this platform not yet implemented

which comes from https://github.com/kripken/emscripten/blob/f8e0b7dc838dea8b713944b5c9469be837826999/system/lib/libcxx/include/config_elast.h#L33

See e.g. http://clb.demon.fi:8112/builders/win-incoming/builds/1264/steps/default%20suite/logs/stdio

	WARNING:root:generating system library: libcxx.a...
	In file included from C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx\ios.cpp:18:
	C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx/include/config_elast.h:33:2: warning: ELAST for this platform not yet implemented [-W#warnings]
	#warning ELAST for this platform not yet implemented
	 ^
	1 warning generated.
	In file included from C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx\system_error.cpp:15:
	C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx/include/config_elast.h:33:2: warning: ELAST for this platform not yet implemented [-W#warnings]
	#warning ELAST for this platform not yet implemented
	 ^
	1 warning generated.
	WARNING:root:                                      ok
	WARNING:root:generating system library: libcxxabi.bc...
	WARNING:root:                                          ok
	INFO:root:...success
	INFO:root:building and verifying libcxx_noexcept
	WARNING:root:generating system library: libcxx_noexcept.a...
	In file included from C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx\ios.cpp:18:
	C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx/include/config_elast.h:33:2: warning: ELAST for this platform not yet implemented [-W#warnings]
	#warning ELAST for this platform not yet implemented
	 ^
	1 warning generated.
	In file included from C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx\system_error.cpp:15:
	C:\slaves\emslave\buildslave\win-incoming\emsdk\emscripten\incoming\system\lib\libcxx/include/config_elast.h:33:2: warning: ELAST for this platform not yet implemented [-W#warnings]
	#warning ELAST for this platform not yet implemented
	 ^
	1 warning generated.

This corresponds to pull request #4288.

Looks like `ELAST` is supposed to represent the highest-numbered error integer(?), but not sure what the business is that libcxx itself doesn't provide it. Perhaps there is some platform-specific error code range or similar. I wonder if we had this defined before, or if this is something new. CC @cynecx.

**Comment by cynecx** [comment]
@juj If I remember correctly we had an emscripten specific value.

    ...
    #elif defined(__EMSCRIPTEN__)
    #define _LIBCPP_ELAST 256
    #else

https://github.com/kripken/emscripten/blob/master/system/include/libcxx/__config#L651

It seems that this is eventually needed here.

**Comment by juj** [comment]
Thanks, posted a PR to fix this, #4501.

**Comment by juj** [comment]
This was fixed in above PR.
