### ISSUE TITLE
Rename `Module.requestFullScreen` to `Module.requestFullscreen`

### ISSUE THREAD

**Issue by cvan** [kripken/emscripten#4396]
I know Firefox introduced it as such, but the casing of `requestFullScreen` is incorrect. It should be `requestFullscreen`.

All other instances should be corrected – [this check](https://github.com/kripken/emscripten/blob/07b87426/src/library_glut.js#L277) should be, for example.

Related: https://github.com/kripken/emscripten/blob/07b8742/system/include/SDL/SDL_joystick.h

**Comment by juj** [comment]
I think all these instances were fixed in pull request #4318, so closing as resolved. If that pull request missed a spot (the above URL looks good to me), please reopen!
