### ISSUE TITLE
CMake for emscripten project with a bit more advanced features

### ISSUE THREAD

**Issue by xwaffelx** [kripken/emscripten#4398]
Hello,

I'm trying to set up a CMake project to drive compilation via emscripten. I found CMake toolchain provided by emscripten and tried to use it, and it works until it comes to a bit more advanced features then compiling helloworld.cpp. In particular, I can't make following flags working:
* --preload-file
* --bind

Preloading file doesn't show any warning or error, but also no .data file is generated in the end.
Bind seem to not do its work as messages like `warning: unresolved symbol: _embind_register_class` appear during the "linking" process and "bound" functions are not accessible via JS then.

Manually running emcc as follows works:
```
add_custom_command(
    OUTPUT manual-client.js
    COMMAND ${CMAKE_CXX_COMPILER}
    -I${CMAKE_SOURCE_DIR}/lib/assimp/include
    -s DEMANGLE_SUPPORT=1
    --preload-file ${CMAKE_SOURCE_DIR}/assets
    --bind
    ${CORE_SRC}
    ${CMAKE_SOURCE_DIR}/lib/assimp/lib-js/libassimp.so
    -o ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/manual-client.js
)
```
Using manually defined custom target works so far, but I believe its not the way its meant to be.
I've created a minimalistic example which fails: https://github.com/xwaffelx/minimal-cmake-emscripten-project/blob/master/CMakeLists.txt
This example contains the working "manual" target as shown above and the "normal" target which fails.
Am I doing something wrong?

Thank you.

**Comment by anlambert** [comment]
Hi,

Instead of creating a custom CMake target to pass the advanced emscripten options, use the CMake property LINK_FLAGS.

For instance in your minimalistic projet, remove your custom target and add the following to your CMakeLists.txt:

INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/lib/assimp/include)
SET_TARGET_PROPERTIES(client PROPERTIES LINK_FLAGS "-s DEMANGLE_SUPPORT=1 --preload-file ${CMAKE_SOURCE_DIR}/assets --bind)
TARGET_LINK_LIBRARIES(client ${CMAKE_SOURCE_DIR}/lib/assimp/lib-js/libassimp.so)

Hope that it will help

**Comment by xwaffelx** [comment]
Awesome! Thank you very much!

**Comment by printfdebugging** [comment]
hi, isn't there any better way to do this than appending to the linker flags? like i was trying 
```cmake
    target_link_options(${APPLICATION} PRIVATE
        -sMAX_WEBGL_VERSION=2
        -sNO_DISABLE_EXCEPTION_CATCHING
        -sASSERTIONS=1
        -sWASM=1
        -sSAFE_HEAP=1
        "--preload-file ${CMAKE_CURRENT_LIST_DIR}/assets@${PROJECT_NAME}/${APPLICATION}/assets"
        # "--preload-file ${CMAKE_CURRENT_LIST_DIR}/assets/shaders/shader.vert@${PROJECT_NAME}/${APPLICATION}/assets/shaders/shader.vert"
        # "--preload-file ${CMAKE_CURRENT_LIST_DIR}/assets/shaders/shader.frag@${PROJECT_NAME}/${APPLICATION}/assets/shaders/shader.frag"
    )
```

built none of those preloads work, neither the one over the whole directory, nor the individual file preloads. 

```cmake
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} \
        -sMAX_WEBGL_VERSION=2 \
        -sNO_DISABLE_EXCEPTION_CATCHING \
        -sASSERTIONS=1 \
        -sWASM=1 \
        -sSAFE_HEAP=1 \
        --preload-file ${CMAKE_CURRENT_LIST_DIR}/assets@${PROJECT_NAME}/${APPLICATION}/assets \
    ")

```
this on the other hand works, both for individual files and for directories. can someone please explain why that's so?

**Comment by rael346** [comment]
@printfdebugging so I also ran into the same error and after some experimenting, here are my observation
- With `target_link_options(${APPLICATION} PRIVATE "--preload-file dir")`, CMake will create `emcc "--preload-file dir"` (with the quote marks). This doesn't work.
- With `target_link_options(${APPLICATION} PRIVATE "--preload-filedir")`, CMake will create `emcc --preload-filedir` (without the quote marks). This also doesn't work.
- With `target_link_options(${APPLICATION} PRIVATE --preload-file dir)` (without quote marks), CMake will create `emcc --preload-file dir` (without the quote marks, with space). This works.
- With `target_link_options(${APPLICATION} PRIVATE "SHELL:--preload-file dir")` (with quote marks and using SHELL prefix), CMake will create `emcc --preload-file dir` (without the quote marks, with space). This also works.

So I think if the option is quoted and has spaced within it, CMake just include the quote marks with it, which emscripten doesn't accept. So you can either not use quotes in `target_link_options` or use `SHELL:` prefix with the option

**Comment by sbc100** [comment]
Try `--preload-file=dir` 

(e.g. use an equals sign to make it into a single argument).
