### ISSUE TITLE
__GLOBAL__sub_xxxxx is not a function

### ISSUE THREAD

**Issue by asRIA** [kripken/emscripten#4410]
Hi,

Recently we started to observe an interesting bug that randomly pops up only on Chrome (51+). 

A simplified callstack looks like: 
```
func@game.js
callRuntimeCallbacks@game.js
ensureInitRuntime@game.js
doRun@game.js
```
What we know:
- this is  an implementation depended, it has started to occur after a fresh release. Unfortunately we haven't detected what is a possible cause of this yet. 
- majority of people with this browser go through without any problem 
- we do have hits from 64 and 32 bit browser
- it happens across 2 of 3 titles (only one correlation is an amount of calls in `__ATINIT__`, for game that has no problem it is ~120, for other it's few times more)

How we can approach this problem? Do you have something in mind that we should pay an extra attention? 

Best regards,
Piotr

**Comment by kripken** [comment]
I have heard other bug reports from Chrome 51, might be a serious regression there. I suggest making the best testcase you can in a public link, and filing a bug on the chromium bug tracker. We can ping people on their side to take a look at it, stressing to them that this is serious.

**Comment by asRIA** [comment]
OK, thank you!
I'm closing this one since there is nor correlation to SDK
