### ISSUE TITLE
Improve test runner to parallelize individual tests in a suite

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4417]
Not an urgent item, but marking down, as I was looking at the runtimes of the current tasks. I'm in the process of adding a significant amount of more workload on the bots, and was examining the existing utilization rate of the hardware.

Currently the parallel test runner parallizes across the different modes of the `default` suite, and doesn't parallelize `other` suite at all. Observing the bot run times, the `default` suite takes up
- 1 hrs, 21 mins, 20 secs on the new Windows bot (8 logical cores),
- 1 hrs, 47 mins, 49 secs on the Mac Pro bot (12 logical cores, shares 4 with Linux below),
- 1 hrs, 47 mins, 58 secs on the Linux bot (temporarily virtualized to run on the Mac Pro, 4 logical cores)

There seems to be quite a considerable tail of time where the execution is dual core or single core towards the end of the run, since the modes take different time to complete. Parallelizing across individual tests would cut the runtime down by about 20 minutes I think.

The `other` suite takes up
- 24 mins, 53 secs on Windows,
- 21 mins, 52 secs on Mac Pro,
- 21 mins, 54 sec on Linux VM

Parallelizing this would more than halve the runtime of this suite.

**Comment by kripken** [comment]
There is a python library whose name I can't remember that can parallelize the python test framework. So this could be easy. However, some of these tests use `EMCC_DEBUG` and read from the temp dir it writes to, so those can't be parallelized. It's just a minority of tests, though, we could split those out.

**Comment by juj** [comment]
This was implemented by @jgravelle-google in #5074.
