### ISSUE TITLE
SIMD issue

### ISSUE THREAD

**Issue by ov** [kripken/emscripten#4420]
Hi guys, I'm using version 1.35.0 and having an issue with optimizer that generates faulty code for a specific set of SIMD instructions.

In two words, it generates this:

```
$a = SIMD_Float32x4_lessThan($x1, $y1); // SIMD_Bool32x4
$b = SIMD_Float32x4_lessThan($x2, $y2); // SIMD_Bool32x4
$c = SIMD_Int32x4_or($a, $b); // exception on type check
```

Basically, `lessThan` calls return bool type, while `or` function expects `int`, so it crashes.

Please see the [test program](https://github.com/kripken/emscripten/files/338698/test.zip). It is based on embree library and is quite messy, but the test itself is more or less simple. Have a look at the `test()` method in `test.cpp`. It compares some SIMD floats and combine results with bit-wise AND operations. Try `make debug` and `make release` to see the difference. Release crashes for me in most of the browsers, while debug works well.

Any ideas on re-writing the source code to avoid the issue?

Thank you.

PS: Can't test on 1.36, as it needs to be build from scratch - that takes too long. Hope you guys can test this faster :)

**Comment by ov** [comment]
ok, so I minimized the example to this:

```c++
#include <emmintrin.h>
#include <stdio.h>
#include <stdlib.h>

#define	__forceinline	inline __attribute__((always_inline))

struct sseb
{
	union  { __m128 m128; int v[4]; };

	__forceinline sseb(const __m128  input) : m128(input) {}
	__forceinline operator const __m128& (void) const { return m128; }
	__forceinline int& operator [] (const size_t i) { return v[i]; }
};

 
struct ssef
{
	union { __m128 m128; float f[4]; int i[4]; };

	__forceinline ssef(const __m128 a ) : m128(a) {}
	__forceinline ssef(float a) : m128(_mm_set1_ps(a)) {}
};


__forceinline const sseb operator &	(const sseb& a, const sseb& b) 	{ return _mm_and_ps(a, b); }
__forceinline const ssef abs       	(const ssef& a) 				{ return _mm_and_ps(a.m128, _mm_castsi128_ps(_mm_set1_epi32(0x7fffffff))); }
__forceinline const ssef operator +	(const ssef& a, const ssef& b) 	{ return _mm_add_ps(a.m128, b.m128); }
__forceinline const sseb operator !=(const ssef& a, const ssef& b) 	{ return _mm_cmpneq_ps(a.m128, b.m128); }
__forceinline const sseb operator >=(const ssef& a, const ssef& b) 	{ return _mm_cmpnlt_ps(a.m128, b.m128); }
__forceinline const sseb operator >=(const ssef& a, const float& b) { return a >= ssef(b); }
__forceinline const sseb operator <=(const ssef& a, const ssef& b) 	{ return _mm_cmple_ps (a.m128, b.m128); }

int main(int argc, const char **argv)
{
	ssef U = static_cast<float>(rand()) / 1000.f;
	ssef V = static_cast<float>(rand()) / 1000.f;
	ssef den = static_cast<float>(rand()) / 1000.f;
	ssef absDen = abs(den);

	printf("before\n"); 
	sseb valid = den != ssef(0) & U >= 0.f & V >= 0.f & U + V <= absDen;
	printf("after: %d %d %d %d\n", valid[0], valid[1], valid[2], valid[3]);

	return 0;
}
``` 

and the `Makefile` is:

```makefile
CC = emcc
CXX = emcc
CXXFLAGS = -std=c++11 -Wstrict-aliasing=1 -fPIC -D __SSE2__ -msse2
LD = $(CXX)

debug:
	$(CXX) $(CXXFLAGS) -O0 -D _DEBUG -g4 test.cpp -o test.html

release:
	$(CXX) $(CXXFLAGS) -O2 -g4 test.cpp -o test.html
```

hope this helps to locate the issue faster.

thanks :)

**Comment by kripken** [comment]
On incoming (`1.36.5`) I don't see a crash on that testcase. I do see a native build return `0 0 0 0` and js return `-1 -1 -1 -1` which might be wrong, I'm not sure.

**Comment by kripken** [comment]
I also see asm.js validation succeed, so the types of arrays fit with each other.

**Comment by ov** [comment]
That's good, any chance you can confirm it doesn't work on 1.35.0 for you too, so I can make sure it is fixed in 1.36? Thank you.

**Comment by juj** [comment]
@ov: can you try building latest Emscripten incoming from source? Try

    git clone https://github.com/juj/emsdk.git
    cd emsdk
    ./emsdk install sdk-incoming-64bit
    ./emsdk activate sdk-incoming-64bit
    source ./emsdk_env.sh

Even if that takes several hours, it is probably faster than asking for others to install another version to try.

**Comment by kripken** [comment]
(I'd be happy to check if it was a quick thing, but I can't easily install another version of emscripten on my current machine, I'm afraid.)

**Comment by ov** [comment]
@juj will try that. so far `emsdk install` command fails on my mac as the script tries to clone https addressed with slashes `/` at the end. I get 'not enough rights' error or something like that for it. Removing slashes at the end and cloning manually works, so I am not building the sdk. Will keep you updated.

**Comment by ov** [comment]
OK, so I built the latest 1.36.5 and tested my sample with it - it works fine, while doesn't work in 1.35.0, so I guess the issues is already fixed and we can safely close this.

Thank you guys :)

**Comment by kripken** [comment]
Great!
