### ISSUE TITLE
How to decode UTF16 into UTF8 using embind

### ISSUE THREAD

**Issue by firasdib** [kripken/emscripten#4426]
Hello,

I am trying to write bindings for the RE2 library (https://github.com/google/re2/blob/master/re2/). My bindings work fine, and I can interact with it from Javascript. The problem comes when I use any non-ascii character. I assume this is because Javascript uses UTF16 and the RE2 engine assumes UTF8.

My question is how can I deal with this problem?

I have tried the following:

1. Using `std::wstring`: This doesn't seem to work since everything seems to want `std::string` and I don't know how to convert these (or whatever needs to be done).
2. On the JS side, convert the string to UTF8 using `stringToUTF8` and send the pointer to C++ instead. This doesn't seem to work either, because when I use `const* string` in the argument list emscripten throws an error about raw pointers. After trying the `allow_raw_pointer` thing I find out it doesn't support primitive types and this solution also falls flat.

```c++
#include <emscripten/bind.h>
#include <emscripten/val.h>
#include "re2/re2.h"

using std::vector;
using re2::RE2;
using re2::StringPiece;

using namespace emscripten;

class RegexMatch {
  public:
    RegexMatch ();
    RegexMatch (int,int);
    int start;
    int end;
    int getStart() { return start; };
    int getEnd() { return end; };
};

RegexMatch::RegexMatch () {}

RegexMatch::RegexMatch (int a, int b) {
  start = a;
  end = b;
}

std::vector<RegexMatch> RE2_Match(std::string regex, std::string text, int startpos, int endpos, int captureGroupCount) {
  const char* match_text = text.c_str();

  RE2 re(regex);

  std::vector<StringPiece> groups(captureGroupCount + 1);
  std::vector<RegexMatch> result(captureGroupCount + 1);

  bool did_match = re.Match(match_text, startpos, endpos, RE2::UNANCHORED, &groups[0], groups.size());

  if (did_match) {
    for (size_t i = 0, n = groups.size(); i < n; ++i) {
      const StringPiece& item = groups[i];

      int match_start = item.begin() - match_text;
      int match_end = match_start + item.size();

      RegexMatch rm(match_start, match_end);

      result[i] = rm;
    }

    return result;
  } else {
    return vector<RegexMatch>();
  }
}

EMSCRIPTEN_BINDINGS(my_module) {
  register_vector<RegexMatch>("VectorRegexMatch");

  // this may or may not work, let's try directly binding the static funcs
  function("RE2_Match", &RE2_Match);

  class_<RegexMatch>("RegexMatch")
    .constructor<int,int>()
    .function("getStart", &RegexMatch::getStart)
    .function("getEnd", &RegexMatch::getEnd);
}
```

I was told to cc @chadaustin as he knows about this sort of stuff.

**Comment by juj** [comment]
Not sure about embind, though you can use the built-in function `stringToUTF8` in https://github.com/kripken/emscripten/blob/master/src/preamble.js#L634 to take a JavaScript string and write that to the heap as UTF8. For cooperating this conversion with embind, you could try making embind pass a regular std::string or a raw pointer or a std::vector<char>, or just directly `malloc` the memory in JavaScript side and `free` the memory in C/C++ side when done. See https://github.com/kripken/emscripten/blob/master/tests/utf8.cpp for test snippets on how that is used.

**Comment by firasdib** [comment]
@juj As you can see from my code sample, I'm using `std::string`. I tried leaving it as that and sending in a pointer to the heap where I've stored the UTF8 string - but that doesn't work, I get an error about sending a non-string. And raw pointers aren't allowed to primitive types unfortunately.

**Comment by juj** [comment]
Err, in that case, I'd just do a quick-and-dirty thing and cast the pointer to a plain `int` to get around embind not liking to marshall raw pointers. Since in JavaScript side pointers are just Numbers, it doesn't change anything if the pointer is marshalled as an int.

**Comment by firasdib** [comment]
I got that to work, thank you very much. But the problem is now that it seems the utf8 data it receives is not valid.

The string `å` results in `re2/re2.cc:642: Match . [\303] used DFA - no match.`. But the escape, `\303`, is wrong. It should be `\303\303` and thus it does not match. Maybe my string is not proper utf8?

On the JS side I do the following:
```js
const maxTestStringSize = (subject.length * 2 + 1) * 2;
const testString = Module._malloc(maxTestStringSize);
Module.stringToUTF8(subject, testString, maxTestStringSize);
```
and then use the `testString` variable which is the pointer.

Any help is much appreciated!

**Comment by amarav** [comment]
@firasdib I'm facing  the same issue. May I know how u fixed it?
