### ISSUE TITLE
Modifying string memory causes corruption (after rebuild)

### ISSUE THREAD

**Issue by modwizcode** [kripken/emscripten#4432]
While working on an OpenGL ES game with emscripten I suddenly started having severe issues when rebuilding. The string that I read my shader into would contain a bit of the next file in my preloaded data. Even after deleting the preload javascript file and the preload data file. A full clean followed by a rebuild would solve it every time. 

[This suddenly stoppped working](https://gist.github.com/modwizcode/d36b9189413646ee028a4681a1e73ca7)

[This works every time](https://gist.github.com/modwizcode/d1555d53e6b8c891a971b05d619445e7)

[Build flags](https://gist.github.com/modwizcode/f2f13008783631989e11a0ce7bf80de0)

The errors only appear when modifying the data files going into the preloaded file system and doing a partial rebuild. If it's just me doing something horribly incorrect I'd like to know too.

**Comment by kripken** [comment]
Strange, the code and build flags all seem fine. Perhaps this is hitting some form of memory corruption? Building with `-s ASSERTIONS=1 -s SAFE_HEAP=1` will enable a bunch of runtime checks that might find an error.

**Comment by modwizcode** [comment]
The build flags contain both, neither changed anything about the behavior that I saw.

**Comment by kripken** [comment]
Ok, might be something trickier then. Any chance you can reduce this as much as possible to a standalone testcase, and provide that code here?

If it's private code, one approach could be to look in the generated code for that method, and compare the two outputs. Nothing else should change, except for that one method (builds are deterministic, and I am hoping that change doesn't affect global variables).

**Comment by modwizcode** [comment]
The code is available at http://hg.modwiz.com/voxgl. I run build.sh to
generate the output build/src/voxgl/app.html. Then run with emrun.

**Comment by kripken** [comment]
Ok, I got the code and built it with `build.sh`, then ran it. I get a segfault error with a stack trace. I rebuilt with `-profiling` so the function names are present in the stack trace, and I see in the browser web console

````
uncaught exception: abort("segmentation fault") at jsStackTrace@http://localhost:6931/app.js:1072:12
stackTrace@http://localhost:6931/app.js:1086:11
abort@http://localhost:6931/app.js:8734:43
segfault@http://localhost:6931/app.js:552:2
SAFE_HEAP_LOAD@http://localhost:6931/app.asm.js:33350:1
_memcpy@http://localhost:6931/app.asm.js:31855:1
_fread@http://localhost:6931/app.asm.js:27286:1
__ZN5voxgl6Bitmap8load_bmpEPKc@http://localhost:6931/app.asm.js:10502:1
_main@http://localhost:6931/app.asm.js:11450:1
asm._main@http://localhost:6931/app.js:8376:9
callMain@http://localhost:6931/app.js:8646:13
doRun@http://localhost:6931/app.js:8683:40
run/<@http://localhost:6931/app.js:8692:4
````

So main calls `voxgl::Bitmap::load_bmp(char const*)` which calls fread which calls memcpy, which loads from a bad address. Perhaps it is loading from a file that doesn't exist, or something like that?

This is on emscripten incoming, 1.36.5.

**Comment by modwizcode** [comment]
Someone that reply missed my inbox. I just realized that the string didn't solve this. That profiling option seems to solve the fact that demangling is ignored after optimizations. I'm building against master currently also.

 I have another stacktrace from the error different than yours by enabling ASSERTIONS=2 and building by manually calling em++ so I knew exactly what was being run.

Here's what I got, I believe this gets optimized away on O2 due to inlining and as far as I can tell this code doesn't do anything remotely unsafe.

```
uncaught exception: abort("segmentation fault") at jsStackTrace@http://localhost:6931/app.js:1327:13
stackTrace@http://localhost:6931/app.js:1344:22
abort@http://localhost:6931/app.js:333000:44
segfault@http://localhost:6931/app.js:619:3
SAFE_HEAP_STORE@http://localhost:6931/app.js:127451:23
__ZN6Camera10setHeadingEf [Camera::setHeading(float)]@http://localhost:6931/app.js:126409:2
__ZN6Camera10addHeadingEf [Camera::addHeading(float)]@http://localhost:6931/app.js:126839:2
__Z25voxgl_window_mousemove_cbiPK20EmscriptenMouseEventPv [voxgl_window_mousemove_cb(int, EmscriptenMouseEvent const*, void*)]@http://localhost:6931/app.js:114471:3
dynCall_iiii@http://localhost:6931/app.js:179857:9
Runtime.dynCall@http://localhost:6931/app.js:515:14
JSEvents.registerMouseEventCallback/handlerFunc@http://localhost:6931/app.js:2347:30
jsEventHandler@http://localhost:6931/app.js:2250:11
````

**Comment by modwizcode** [comment]
Ah actually that's just my code responding to the fact that the object never initialized properly due to failing to create the shader. I think you're right that it's just not loaded yet, is there any way to wait for it to be loaded?

**Comment by kripken** [comment]
How is the file loaded into the filesystem? If it's preloaded (`--preload-file` etc.) then `main()` should only run after it is ready. If you don't have a `main()`, see [this faq entry](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html?highlight=onruntimeinitialized#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions) for how to wait until the runtime is ready.

**Comment by modwizcode** [comment]
I have a `main()` and I am using preloaded files. So I don't see any
opening for an unloaded file to come up.

**Comment by kripken** [comment]
Perhaps the file wasn't preloaded successfully for some reason (like the file packager hit an error, although if it does, you should see that error, so no idea what's going on). The file packager output is JS code, so you can look for your file in there by name, and can add some logging code to debug things.

**Comment by modwizcode** [comment]
I think it's probably an error in my own code as I partially suspected, yet to confirm as I've seen the corruption behavior after the change, I realized I'm not making sure the string read is null terminated before sending it to `std::string`'s constructor and therefore it just keeps going till the first `'\0'`. Unfortunately that doesn't seem to be the whole story. Again, I really need to diff the generated output between resource only changes.

**Comment by modwizcode** [comment]
After doing the diffs I can confirm that the difference between the two files is just the signature or hash or whatever which I assume is used to alert the client to the need to update their cache. However the full `app.js` file that initializes the code actually wasn't updating for the new code from `app.preload.js` causing length errors. This was actually a build system issue with the way I have waf configured.

**Comment by kripken** [comment]
Interesting, glad this worked out.
