### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed

### ISSUE THREAD

**Issue by mavidser** [kripken/emscripten#4442]
This error shows up while using emscripten. Using the latest version.

[Using this for reference](https://github.com/syl22-00/pocketsphinx.js#2a-compilation-with-the-default-acoustic-model)

```
[100%] Built target pocketsphinx
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: throwInternalError
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: posix_spawn_file_actions_init
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Traceback (most recent call last):
  File "/home/sid/dev/emscripten/emcc", line 13, in <module>
    emcc.run()
  File "/home/sid/dev/emscripten/emcc.py", line 1668, in run
    JSOptimizer.flush()
  File "/home/sid/dev/emscripten/emcc.py", line 1570, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/home/sid/dev/emscripten/emcc.py", line 1543, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/home/sid/dev/emscripten/tools/shared.py", line 1651, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/home/sid/dev/emscripten/tools/js_optimizer.py", line 538, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/sid/dev/emscripten/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/home/sid/dev/emscripten/tools/js_optimizer.py", line 538, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/sid/dev/emscripten/tools/js_optimizer.py", line 483, in run_on_js
    assert proc.returncode == 0
AssertionError
CMakeFiles/pocketsphinx.js.dir/build.make:57: recipe for target 'CMakeFiles/pocketsphinx.js' failed
make[2]: *** [CMakeFiles/pocketsphinx.js] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pocketsphinx.js.dir/all' failed
make[1]: *** [CMakeFiles/pocketsphinx.js.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kripken** [comment]
Looks like it runs out of memory in the js_optimizer phase. We spawn several processes, perhaps too many for your system? Try with `EMCC_CORES=1` in the env, which will limit it to 1. `EMCC_DEBUG=1` in the env may also help understand what's going on.

**Comment by mavidser** [comment]
Got this log with both the flags set. Do I have to build llvm again for this?

```
.
.
.
Packaging file "en-us-ptm/README.md5" to VFS in path "/en-us-ptm/README.md5".
Packaging file "en-us-ptm/mixture_weights" to VFS in path "/en-us-ptm/mixture_weights".
DEBUG:root:applying pre/postjses
DEBUG:root:optimizing memory initialization
DEBUG:root:emcc step "source transforms" took 2.59 seconds
DEBUG:root:running js post-opts
DEBUG:root:applying js optimization passes: asm eliminate simplifyExpressions simplifyIfs registerizeHarder minifyNames asmLastOpts last minifyWhitespace cleanup
chunkification: num funcs: 1746 actual num chunks: 4 chunk size range: 1276954 - 58612
DEBUG:root:js optimizer using native
splitting up js optimization into 4 chunks
.
.
.
.
running cleanup on shell code
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by kripken** [comment]
No, building llvm is not going to affect that.

Hmm, crashing in the "cleanup on shell code" stage is surprising. Do you include a lot of JS code in a `--pre-js` or such, or in preloaded files, or something else?

You can look in `/tmp/emscripten_temp`, it should save some temp files there, where you can see the JS.

What version of node are you using, btw? And is it 64-bit? We run node in that phase.

**Comment by mavidser** [comment]
I am running a 64 bit version of node. I don't think there's a lot of JS code in --pre-js (Not really sure. The emscripten code is being run by another makefile in pocketsphinx, but my grep didn't give any result for `--pre-js`).

Also, I have two .js files in `/tmp/emscripten_temp`

```
-rw-rw-r-- 1 sid sid 1.5M Jul 22 13:05 emcc-0-linktime.bc
-rw-rw-r-- 1 sid sid 4.3M Jul 22 13:05 emcc-1-original.js
-rw-rw-r-- 1 sid sid  80M Jul 22 13:05 emcc-2-pre-post.js
```

That is an 80M JS file. Is that the expected output from emscripten, or was it going to make it much smaller during the cleanup?

**Comment by kripken** [comment]
Yes, that looks like the issue. `original` is the compiled code (+support runtime). `pre-post` is after adding in `-pre-js`, `-post-js` and other extra code like file preloading. 76MB of that is a huge amount! I would just `diff` those two files to see what is added in the second.

(Yes, emscripten reduces the size very significantly in later passes, in that `cleanup` pass that is failing does a lot of it. You could btw just try to disable that pass, but 80MB of JS is definitely something that needs to be figured out where it came from.)

**Comment by mavidser** [comment]
Thanks. Never mind the huge JS. I was encapsulating a lot of raw data in JSON format, so I could see it being quite huge. Thanks for the help. :)
