### ISSUE TITLE
ctor_evaller.py leaks ctorEval.js files in the temp directory.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4446]
STR:

a) Run `em++ tests\hello_libcxx.cpp -o a.html -Oz` and see the temp directory, which now has 4 files of form `tmpehbajx.ctorEval.js`, or

b) run `EM_TESTRUNNER_DETECT_TEMPFILE_LEAKS=1 python tests/runner.py other.test_warn_toomany_vars`:

	C:\code\emsdk\emscripten\incoming>python tests/runner.py other.test_warn_toomany_vars
	WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
	Test suites:
	['test_other']
	Running test_other: (1 tests)
	test_warn_toomany_vars (test_other.other) ... C:\code\emsdk\emscripten\incoming\tests\hello_libcxx.cpp z
	ERROR: After running test, there are 4 new temporary files/directories left behind:
	leaked file: C:\code\emsdk\emsdk_tmp\tmpkc0yi3.ctorEval.js
	leaked file: C:\code\emsdk\emsdk_tmp\tmpxmiklj.ctorEval.js
	leaked file: C:\code\emsdk\emsdk_tmp\tmpswe3yx.ctorEval.js
	leaked file: C:\code\emsdk\emsdk_tmp\tmpagvovm.ctorEval.js
	ERROR

Not sure if this is Windows-specific or if it occurs on other OSes as well.

(running the default and other suites with `EM_TESTRUNNER_DETECT_TEMPFILE_LEAKS=1` seems to find other leaks as well, although note that this option is not compatible with the `parallel_test_core.py` script)

**Comment by juj** [comment]
Enabled the bots to run the `other` suite with `EM_TESTRUNNER_DETECT_TEMPFILE_LEAKS=1` active, https://github.com/juj/emslave/commit/21c68e7b4d785519ecdd9a66ae8c26e4b5b56d78, so the next run will give info about these on all OSes.

**Comment by kripken** [comment]
I can't reproduce this on linux. The command (b) passes without issue. And I added logging to print each note and clean operation in `tools/tempfiles.py`, and it correctly notes the `*.ctor.js` file and cleans it up (when not in `EMCC_DEBUG=1` mode - in that mode, the temp file is just `ctor.js` (nothing before) and it is intentionally left behind).

**Comment by juj** [comment]
Hmm, I wonder if it needs some other flags or environment to combine for it to occur. On the bots, each OS is now logging these kind of reports:
   - [OS X](http://clb.demon.fi:8112/builders/osx-incoming/builds/1525/steps/other%20suite/logs/stdio)
   - [Ubuntu](http://clb.demon.fi:8112/builders/ubuntu-incoming/builds/1534/steps/other%20suite/logs/stdio)
   - [Windows](http://clb.demon.fi:8112/builders/win-incoming/builds/1303/steps/other%20suite/logs/stdio)

I can take a closer look next week.

**Comment by juj** [comment]
@kripken : oh, now I recall what's going on here. Since we are relying on the process atexit time to clean up the generated temp files, so at the test time the temp files might still reside there.

In addition to this bug, there is a long time issue where I see that files keep accumulating up in the temp directory over time. This is due to python issues that atexit handlers don't always run, especially when paired up with multiprocessing pool (on Windows). See http://bugs.python.org/issue23489 on that (oh boy, was I in a rant mode when reading that in retrospect..)

How do you feel if we'd take the approach/convention that wherever any piece of code creates a temp file, it would always eagerly and explicitly remove it manually when it is no longer known to be needed (EM_SAVE_DIR and EMCC_DEBUG -like behavior excluded), and we'd eventually avoid relying on atexit to clean up the temp files that were created? (This might have the potential benefit of reducing required disk space as well, since multiple copies/passes of big temp files could all pile up if they co-live on the disk, until they're all only eventually deleted at process exit) Using RAII-style try: finally: blocks would make it more explicit when statically reading where different files are generated and how long they are expected to live.

**Comment by kripken** [comment]
Sounds reasonable, yeah, I'm ok with try-finally blocks for this stuff.

**Comment by juj** [comment]
Great, taking..

**Comment by juj** [comment]
This is now fixed in incoming.
