### ISSUE TITLE
Unable to build box2d test Helloworld

### ISSUE THREAD

**Issue by rahulchaphalkar** [kripken/emscripten#4457]
Hi, I'm trying to compile Helloworld.cpp in tests\box2d\Helloworld\ with the following command:
`\tests\box2d>emcc -I . HelloWorld\HelloWorld.cpp -o HelloWorld\hello.out.js`
However, i get several `warning: unresolved symbol`.
I'm using the -I option to resolve the include paths because in its absence I get the `HelloWorld\HelloWorld.cpp:19:10: fatal error: 'Box2D/Box2D.h' file not found` error.
I've set the EMCC_DEBUG in environment, and following is the complete output:

`\tests\box2d>emcc -I . HelloWorld\HelloWorld.cpp -o HelloWorld\hello.out.js
DEBUG:root:failed to use vanilla file, will re-check: too many values to unpack
DEBUG:root:testing for asm.js target, because if not present (i.e. this is plain vanilla llvm, not emscripten fastcomp), we will use the wasm target instead (set EMCC_WASM_BACKEND to skip this check)
DEBUG:root:check tells us to use asm.js backend
WARNING:root:invocation: C:\Program Files\Emscripten\emscripten\incoming\\emcc -I . HelloWorld\HelloWorld.cpp -o HelloWorld\hello.out.js  (in C:\Program Files\Emscripten\emscripten\incoming\tests\box2d)
INFO:root:(Emscripten: Running sanity checks)
DEBUG:root:compiling to bitcode
DEBUG:root:emcc step "parse arguments and setup" took 0.00 seconds
DEBUG:root:compiling source file: HelloWorld\HelloWorld.cpp
DEBUG:root:running: C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin\clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=36 -D__EMSCRIPTEN_tiny__=3 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\local\include -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\include\compat -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\include -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\include\emscripten -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\include\libc -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\lib\libc\musl\arch\emscripten -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\include\libcxx -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\lib\libcxxabi\include -I. -std=c++03 HelloWorld\HelloWorld.cpp -Xclang -isystemC:\Program Files\Emscripten\emscripten\incoming\system\include\SDL -emit-llvm -c -o c:/users/rschapha/appdata/local/temp\tmpoviwq8\HelloWorld_0.o
DEBUG:root:emcc step "bitcodeize inputs" took 0.29 seconds
DEBUG:root:emcc step "process inputs" took 0.00 seconds
DEBUG:root:will generate JavaScript
DEBUG:root:including libcxxabi.bc
DEBUG:root:including libc.bc
DEBUG:root:including dlmalloc.bc
DEBUG:root:emcc step "calculate system libraries" took 0.02 seconds
DEBUG:root:linking: ['c:/users/rschapha/appdata/local/temp\\tmpoviwq8\\HelloWorld_0.o', 'C:\\Users\\rschapha\\.emscripten_cache\\asmjs\\libc.bc', 'C:\\Users\\rschapha\\.emscripten_cache\\asmjs\\dlmalloc.bc', 'C:\\Users\\rschapha\\.emscripten_cache\\asmjs\\libcxxabi.bc']
DEBUG:root:emcc step "link" took 0.01 seconds
DEBUG:root:saving intermediate processing steps to c:/users/rschapha/appdata/local/temp\emscripten_temp
DEBUG:root:(not saving intermediate c:/users/rschapha/appdata/local/temp\emscripten_temp\emcc-0-basebc.bc because deferring linking)
DEBUG:root:emcc: LLVM opts: -strip-debug -internalize -internalize-public-api-list=main,malloc,free,__errno_location,fflush,__cxa_can_catch,__cxa_is_pointer_type -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 4]
DEBUG:root:emcc step "post-link" took 0.25 seconds
DEBUG:root:LLVM => JS
DEBUG:root:emscript: llvm backend: C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2015_64/RelWithDebInfo/bin\llc c:\users\rschapha\appdata\local\temp\tmpoviwq8\hello.out.bc -march=js -filetype=asm -o c:\users\rschapha\appdata\local\temp\emscripten_temp\tmplvgszv.4.js -emscripten-assertions=1 -emscripten-no-aliasing-function-pointers -emscripten-global-base=8 -O0 -enable-emscripten-cxx-exceptions
DEBUG:root:  emscript: llvm backend took 0.0479998588562 seconds
DEBUG:root:emscript: js compiler glue
DEBUG:root:very limited syscalls (6, 146, 140, 54) so disabling full filesystem support
warning: unresolved symbol: _ZN6b2Body13CreateFixtureEPK7b2Shapef
warning: unresolved symbol: _ZN7b2World4StepEfii
warning: unresolved symbol: _ZN6b2Body13CreateFixtureEPK12b2FixtureDef
warning: unresolved symbol: _ZN7b2WorldD1Ev
warning: unresolved symbol: _ZN7b2World10CreateBodyEPK9b2BodyDef
warning: unresolved symbol: _ZN14b2PolygonShape8SetAsBoxEff
warning: unresolved symbol: _ZN7b2WorldC1ERK6b2Vec2
warning: unresolved symbol: _ZTV14b2PolygonShape
DEBUG:root:  emscript: glue took 0.275000095367 seconds
DEBUG:root:emscript: python processing: function tables and exports
DEBUG:root:asm text sizes[[241186, 14106], 9464, 216, 3375, 0, 2078, 6058, 1068, 268, 2530, 7703]
DEBUG:root:  emscript: python processing: function tables and exports took 0.00400018692017 seconds
DEBUG:root:emscript: python processing: finalize
DEBUG:root:  emscript: python processing: finalize took 0.0019998550415 seconds
DEBUG:root:emcc step "emscript (llvm => executable code)" took 0.38 seconds
DEBUG:root:emcc step "source transforms" took 0.00 seconds
DEBUG:root:emcc step "js opts" took 0.00 seconds
DEBUG:root:emcc step "final emitting" took 0.00 seconds
DEBUG:root:total time: 0.96 seconds`

What am I missing here? (It does build natively om windows). Using emscripten 1.36.3

**Comment by kripken** [comment]
The HelloWorld.cpp file just contains the hello world demo code, you need to link to the compiled box2d library itself. `-I` gives you the includes, but not the library. You should build box2d and then add the library bitcode as an input to emcc.

You can look in `tests/benchmark.py` which does that for box2d.

**Comment by rahulchaphalkar** [comment]
Thanks! That cleared things up.
