### ISSUE TITLE
LLVM 3.9 merge

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4460]
The `next-merge` branches now contain a merge of LLVM and clang from in the LLVM 3.9 release branch. This issue is to track merging those to incoming.

`other` tests passed ok so far, a good start.

See previous discussion on blocking issues in #4435

**Comment by kripken** [comment]
The only bot failure I can reproduce locally is

 * `browser.test_html5_webgl_create_context`, assert on `!!stencil`. Not sure what's up, but almost certainly not going to be changed by an LLVM update.

**Comment by kripken** [comment]
@juj, what do you think about merging `next-merge` to incoming?

(I still have some local tests to finish, but looking good so far.)

**Comment by dschuff** [comment]
Is `next-merge` just a branch in fastcomp or are there changes in the emscripten repo too? I can run it through the wasm waterfall tests (it has asm2wasm tests that exercise the JS backend).

**Comment by kripken** [comment]
It's a set of 3 branches, in the fastcomp, fastcomp-clang and emscripten repos.

**Comment by dschuff** [comment]
Looks like the following tests from the gcc torture tests (https://chromium.googlesource.com/chromiumos/third_party/gcc/+/master/gcc/testsuite/gcc.c-torture/execute/) fail when built with next-merge:

```
Unexpected failures:
	931004-10.c.js
	931004-12.c.js
	931004-4.c.js
	931004-8.c.js
	pr44683.c.js
	strct-stdarg-1.c.js
	va-arg-22.c.js
```

**Comment by kripken** [comment]
What's the full set of commands they run on those files, so I can replicate it locally?

**Comment by dschuff** [comment]
Waterfall uses something like `emcc foo.c -o foo.c.js --std=gnu89 -DSTACK_SIZE=1044480 -w -Wno-implicit-function-declaration -s BINARYEN=1 -s BINARYEN_METHOD="native-wasm"`

**Comment by dschuff** [comment]
Oh, and then `d8 --expose-wasm foo.c.js` But I'd imagine it should work the same with the binaryen interpreter or SM.

**Comment by kripken** [comment]
Thanks. I verified they all work before the `next-merge` branch, next I'll try them there.

I did notice one used copysign, which is interesting as one major change in this merge is LLVM added a copysign intrinsic...

**Comment by kripken** [comment]
Meanwhile I finished running more of the test suite,

 * `sockets` pass
 * `core` pass
 * `sanity` pass

Of the gcc torture test failures, one was indeed a copysign bug (with negative zero), fixed. All the other tests use va_arg in odd ways, so they might have a single underlying cause. My guess is that what changed is we stopped using our va_arg code and defined the triple to do the same as the wasm triple does, so something might be wrong in the shared code. I'm not familiar with that code so no guesses. It would be good to investigate this, but I'm not sure it should block the merge.

**Comment by kripken** [comment]
@sunfishcode says that the new approach lowers `va_arg` but leaves `va_start`, `va_end` and `va_copy`, and indeed that's what I see. So there might be a mismatch in terms of what clang thinks the underlying `va_*` data structure is, and what the pnacl `ExpandVarArgsPass` lowering pass thinks. The tests pass a list of structures of size <4 bytes, so I am guessing one thinks I'm not sure where the clang info would even be stored so not sure how to proceed here.

**Comment by kripken** [comment]
* `browser` tests passed
 * `benchmark` results are ok

Overall, the only known issue is the weird varargs thing that just shows up on those torture tests. The emscripten test suite passes.

**Comment by kripken** [comment]
The PnaCl pass emits reasonable-looking stuff:

````
  %vararg_ptr5 = getelementptr inbounds { %struct.tiny, %struct.tiny, %struct.tiny }, { %struct.tiny, %struct.tiny, %struct.tiny }* %vararg_buffer2, i32 0, i32 1, !dbg !84
````

That creates a packed structure for the structs. Tiny here is a i16, so it's i16,i16,i16 with no padding in the middle, so each jump is 2. But the clang frontend generated code that jumps by 4.

It seems like we should tell clang to do things differently. Anyone know where that is defined?

**Comment by kripken** [comment]
Looks like `TargetInfo.cpp` is the place. I modified the code to do what the pnacl target does instead of the wasm target. Now things look ok on all those torture tests, and all our varargs tests.

So I think we are ready to land this on incoming, unless there are any concerns.

**Comment by kripken** [comment]
I still see a few bot errors, but they look either random or like the new tempfile leak asserts, so not enough to block the merge. Merged to incoming.
