### ISSUE TITLE
recipe for target 'src/CMakeFiles/ssh_shared.dir/all' failed

### ISSUE THREAD

**Issue by ShilpamSinha** [kripken/emscripten#4463]
I'm trying to install NetoPeer server on my centOS machine.
One of the dependencies is "libssh", for which i'm following the following step :
wget https://git.libssh.org/projects/libssh.git/snapshot/libssh-0.6.4.tar.gz 
    tar xvfz libssh-0.6.4.tar.gz
    cd libssh-0.6.4/build 
    cmake  .. 
    make 

After the "make" step I'm getting the following error : 

Linking C shared library libssh.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libnacl.a(crypto_scalarmult_curve25519_donna_c64-base.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libnacl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/ssh_shared.dir/build.make:1143: recipe for target 'src/libssh.so.4.5.0' failed
make[2]: *** [src/libssh.so.4.5.0] Error 1
CMakeFiles/Makefile2:185: recipe for target 'src/CMakeFiles/ssh_shared.dir/all' failed
make[1]: *** [src/CMakeFiles/ssh_shared.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

The "make" process is interrupted at 54%

The cmake log :

-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Performing Test WITH_FPIC
-- Performing Test WITH_FPIC - Success
-- Performing Test WITH_STACK_PROTECTOR
-- Performing Test WITH_STACK_PROTECTOR - Success
-- Found ZLIB: /usr/include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- checking for module 'openssl'
--   found openssl, version 1.0.1f
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found GSSAPI: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so;/usr/lib/x86_64-linux-gnu/libkrb5.so;/usr/lib/x86_64-linux-gnu/libk5crypto.so;/usr/lib/x86_64-linux-gnu/libcom_err.so
-- Found NaCl: /usr/lib/libnacl.a
-- Performing Test WITH_VISIBILITY_HIDDEN
-- Performing Test WITH_VISIBILITY_HIDDEN - Success
-- Looking for argp.h
-- Looking for argp.h - found
-- Looking for pty.h
-- Looking for pty.h - found
-- Looking for termios.h
-- Looking for termios.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for util.h
-- Looking for util.h - not found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for openssl/aes.h
-- Looking for openssl/aes.h - found
-- Looking for openssl/blowfish.h
-- Looking for openssl/blowfish.h - found
-- Looking for openssl/des.h
-- Looking for openssl/des.h - found
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
-- Looking for openssl/ec.h
-- Looking for openssl/ec.h - found
-- Looking for openssl/ecdsa.h
-- Looking for openssl/ecdsa.h - found
-- Looking for isblank
-- Looking for isblank - found
-- Looking for strncpy
-- Looking for strncpy - found
-- Looking for vsnprintf
-- Looking for vsnprintf - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for poll
-- Looking for poll - found
-- Looking for select
-- Looking for select - found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for ntohll
-- Looking for ntohll - not found
-- Looking for htonll
-- Looking for htonll - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for forkpty in util
-- Looking for forkpty in util - found
-- Looking for cfmakeraw
-- Looking for cfmakeraw - found
-- Looking for strtoull
-- Looking for strtoull - found
-- Looking for __strtoull
-- Looking for __strtoull - not found
-- Performing Test HAVE_GCC_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_GCC_THREAD_LOCAL_STORAGE - Success
-- Performing Test HAVE_MSC_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_MSC_THREAD_LOCAL_STORAGE - Failed
-- Performing Test HAVE_GCC_VOLATILE_MEMORY_PROTECTION
-- Performing Test HAVE_GCC_VOLATILE_MEMORY_PROTECTION - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1")
-- Found DOXYFILE_IN: /usr/local/libssh-0.6.4/doc/Doxyfile.in
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- ********************************************
-- ********** libssh build options : **********
-- zlib support: ON
-- libgcrypt support: OFF
-- libnacl support: ON
-- SSH-1 support: OFF
-- SFTP support: ON
-- Server support : ON
-- GSSAPI support : ON
-- Pcap debugging support : ON
-- With static library: OFF
-- Unit testing: OFF
-- Client code Unit testing: OFF
-- Public API documentation generation
-- Benchmarks: OFF
-- ********************************************
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/libssh-0.6.4/build

**Comment by juj** [comment]
Hi, I am going to close this, since this looks like the wrong bug tracker, this is not Emscripten-related. Try reaching out to the libssh or centOS support trackers.
