### ISSUE TITLE
Is SAFE_HEAP option usable in WebAssembly?

### ISSUE THREAD

**Issue by aheejin** [kripken/emscripten#4474]
It looks like SAFE_HEAP option is not working with wasm. In src/runtime.js, where Runtime.dynamicAlloc function is generated, if SAFE_HEAP is on it generates calls to Runtime.setDynamicTop.
```
    if (SAFE_HEAP) ret += '; if (asm) { Runtime.setDynamicTop(DYNAMICTOP); }';   
    ret += '; if (DYNAMICTOP >= TOTAL_MEMORY) { var success = enlargeMemory(); if (!success) { DYNAMICTOP = ret; ';
    if (SAFE_HEAP) ret += 'if (asm) { Runtime.setDynamicTop(DYNAMICTOP); }';     
    ret += ' return 0; } }' 
```

That Runtime.setDynamicTop function is generated within finalize_output function in emscripten.py, along with many other functions, and the finalize_output function is only called when compiling into asm.js.

I can add Runtime.setDynamicTop generation part to emscripten_wasm_backend function (in emscripten.py), which is responsible for generation of wasm code, but I am not sure if this is a right approach. Because finalize_output generates many functions along with this setDynamicTop, I am wondering how many of them are also necessary for wasm, and I am not sure if adding a single function(Runtime.setDynamicTop) to wasm backend is either sufficient or advisable.

I came across this issue while testing the asm.js-style exception handling scheme for wasm. test_exceptions_2 in test_core.py fails because it sets SAFE_HEAP option.

@dschuff @jpporto (I am mentioning my intern hosts)

**Comment by kripken** [comment]
Right, yes. This option depends on special stuff in emscripten.py that we add for asm.js, and so it works in asmjs and wasm with asm2wasm, but not wasm with the LLVM wasm backend.

Overall, the question is whether we want it to work in that mode. Perhaps there is a better way to do things, or we don't need them. For SAFE_HEAP, it mainly checks alignment errors and reading beyond the size of memory. The former is not an error in wasm anyhow, and the latter will throw an error in wasm (at least when reading beyond the wasm memory, but not beyond the sbrk'd memory but below it).

**Comment by aheejin** [comment]
Thank you for the answer. The code snippet in test_exceptions_2 is like this:
```
    for safe in [0,1]:                                                                                                          
      Settings.SAFE_HEAP = safe                                                  
      test_path = path_from_root('tests', 'core', 'test_exceptions_2')           
      src, output = (test_path + s for s in ('.in', '.out'))                     
      self.do_run_from_file(src, output)
```

So, would this be OK?
```
    for safe in [0,1]:
      if Settings.BINARYEN and safe == 1:
        continue
      Settings.SAFE_HEAP = safe                                                  
      test_path = path_from_root('tests', 'core', 'test_exceptions_2')           
      src, output = (test_path + s for s in ('.in', '.out'))                     
      self.do_run_from_file(src, output)         
```

**Comment by kripken** [comment]
Hmm, we do actually still want to test it in asm2wasm mode. So how about `if self.is_wasm_backend() and safe == 1`?

**Comment by aheejin** [comment]
I see, thanks. I'll send a new pull request.
