### ISSUE TITLE
Option to avoid process.exit on exit on Node environment

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#4479]
My use-case: [I'm wrapping](https://github.com/Kagami/ffmpeg.js/blob/v3.1.9000/build/pre.js#L3) the entire compiled program inside a function, export it via CommonJS API and then use it just like any other Node module. Maybe it's not perfect solution, but it works good enough for me.

The problem is: on exit on Node environment [Emscripten code runs](https://github.com/kripken/emscripten/blob/master/src/postamble.js#L262) `process.exit` that kills the entire Node process and makes it impossible to run program several times.

There was `NODE_STDOUT_FLUSH_WORKAROUND` option before which allowed to disable that behavior but [now it's gone](https://github.com/kripken/emscripten/commit/6ea7b3c549e1d8ad8eb21efd0e29d683211e8102). Currently [I'm redefining](https://github.com/Kagami/ffmpeg.js/blob/v3.1.9000/build/pre.js#L32) `Module.exit` function with similar function which doesn't call `process.exit` but I don't find it elegant and future-proof.

Could you suggest some better way to achieve this or maybe it's worth to add corresponding emcc option which would disable `process.exit`?

**Comment by kripken** [comment]
I think redefining `Module.exit` as you do is a reasonable solution here. It should be future-proof unless we change our exit approach significantly, which I can't think of a reason why we would.

**Comment by Kagami** [comment]
Ok, thanks. Just wasn't sure how stable the current code in `Module.exit`.
