### ISSUE TITLE
UnicodeDecodeError SDL example

### ISSUE THREAD

**Issue by squareless** [kripken/emscripten#4482]
When I try to compile hello_world_sdl.cpp and in almost every test file I get these errors:

Traceback (most recent call last):
  File "Emscripten\emscripten\1.35.0\\emcc", line 1309, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "Emscripten\emscripten\1.35.0\\emcc", line 1470, in llvm_opt
    output = Popen([LLVM_OPT] + inputs + opts + ['-o', target], stdout=PIPE).communicate()[0]
  File "Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 907, in _execute_child
    args = list2cmdline(args)
  File "Emscripten\python\2.7.5.3_64bit\lib\subprocess.py", line 646, in list2cmdline
    return ''.join(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 0: ordinal not in 
range(128)

Tried to add encoding at those lines, but there was a problem with js vm.

> CRITICAL root: The JavaScript shell used for compiling (['Emscripten/node/0.12.2_64bit/node.exe']) does not seem to work, check the paths in ~/.emscripten

hello_world.cpp is compiling, some of other tests that are working in console too.
I tried to compile [minimal example](https://wiki.libsdl.org/SDL_CreateWindow) for creating window in SDL, and it compiles as long as I don't put 
SDL_Init(SDL_INIT_VIDEO) line, but without it I can't create window.

-------EDIT:
When I tried to compile your example but without SDL_Init, it compiled and I see gradient. It worked!
What might be the issue? And my bad, trying to create window, when I should use surface....

**Comment by kripken** [comment]
That error about `The JavaScript shell used for compiling` should be fixed before anything else. Perhaps in your `~/.emscripten` file there is a relative path instead of an absolute path, and therefore emscripten cannot find node properly?

**Comment by squareless** [comment]
No it's absolute path. Not sure what's causing this problem, but without SDL_Init, I can easily draw like in desktop app I mean 0 warrning, 0 errors. Everything works as should...
What I meant by "Tried to add encoding at those lines, but there was a problem with js vm." is that I edited these python files and at every error line added .encode(...), I tried ascii, utf-8, unicode but it was only causing problem with VM. After that I deleted my changes in these python files, and was stroving to find a way to get rid of errors, so I deleted some lines of code from my c++ test file and it compiled.
What I noticed is that the SDL_Init was causing these errors, but I don't know why. Without calling it out, I can draw, I can add emscripten loop. So far I haven't had any problems.

**Comment by juj** [comment]
I recall that the documentation pages of SDL have some of the characters on the page that are non-ASCII UTF-8, either the `(`, `)`, `-` or `_` characters, but don't quite remember which. So if copy-pasting code there, one should make sure to change the characters to their ASCII counterparts. I've been bitten by that in the past, when copy-pasting some example code and then have the result mysteriously-looking fail to compile.

Btw, what do C++ compiler/spec standards say about `.c` or `.cpp` input files with UTF-8 encodings (with or without BOM?) Anyone have the definitive source? At present, it would be good to keep to plain ASCII for input files.

In either case, I'll close this issue as it is no longer troubling here.
