### ISSUE TITLE
Regression between 1.34.1 and 1.34.2

### ISSUE THREAD

**Issue by rtissera** [kripken/emscripten#4490]
Hello,

While playing this weekend with [libretro/Genesis-Plus-GX](http://github.com/libretro/Genesis-Plus-GX) repository, I stumbled upon some emscripten issue.

Emscripten 1.34.1 is compiling the code fine (I can play in my browser), while 1.35.0 binary sdk compilation results in garbled screen emulation. I compiled sdk-master-64bit from source (on OS X) and I have the same result.

I have not been able to isolate so far the problem, it probably lies into memory alignment or a strange wraparound into the Genesis-Plus-GX VDP emulation code, but I can look into it or narrow it down if you are interested in.

Of course I made all these tests with various optimization levels ranging from -O0 to -O3, no luck.

**Comment by kripken** [comment]
Is this still a problem on incoming (now at `1.36.7`)? Perhaps it's a bug that was fixed since.

If not it would be good to bisect between the two versions you mention, if there isn't a better approach.

**Comment by rtissera** [comment]
Let's build incoming and see how it goes.

**Comment by rtissera** [comment]
Cannot build incoming on my OS X laptop, I will give a shot tomorrow on a Linux box.

**Comment by rtissera** [comment]
Hello,
I have built both sdk-tag-1.34.1-32bit and sdk-incoming-64bit on Debian testing (stretch) amd64.
I can confirm incoming is producing incorrect build (garbled screen) at -O1, -O2, -O3 levels. -O0 seems OK.
I have rebuilt the code using 1.34.1 on Linux box and the build is fine even using -O3.
Should we narrow down which build introduces the regression ?

**Comment by kripken** [comment]
Yes, if you can bisect to a specific commit in one of the repos that would be optimal. Perhaps the changelog can help focus, too, it seems short for that version:

````
v1.34.1: 6/18/2015
------------------
 - Fixed an issue with resize canvas not working with GLFW.
 - Fixed handling of empty else blocks.
````

**Comment by rtissera** [comment]
Good news, I have been able to reduce so far the scope between 1.34.1 and 1.34.2.

I can guess I should bisect on [emscripten-fastcomp](https://github.com/kripken/emscripten-fastcomp) rather than  [emscripten](https://github.com/kripken/emscripten) right ?

I had a quick look at the changes and due to the nature of the issue, I can see so far two good candidates :

[heapalign](https://github.com/kripken/emscripten-fastcomp/commit/62f532d4586614d2c1a0fcad44b1109e70088613)

[ExpandBigSwitches commit](https://github.com/kripken/emscripten-fastcomp/commit/57b5a21bad36bbe5f4ee60c260f5b44817bd27eb)

**Comment by rtissera** [comment]
OK, got it.

Here is the result of the git bisect on emscripten-fastcomp :

452702ecfa2e6664a8db8e79aa39e788ef614e05 is the first bad commit
commit 452702ecfa2e6664a8db8e79aa39e788ef614e05
Author: Alon Zakai <alonzakai@gmail.com>
Date:   Fri Jun 19 15:28:55 2015 -0700

    align global data properly

:040000 040000 5e7a9fa64b3919ed456ea677ae9270d702f95c21 3b6d1b7673f5b10a64afe79c2061be76c1a76753 M     	lib

**Comment by kripken** [comment]
Good, glad you found the underlying issue.
