### ISSUE TITLE
Internet Explorer 11 MouseWheel delta returns NaN

### ISSUE THREAD

**Issue by mabrownptc** [kripken/emscripten#4499]
Registering for mouse wheel events using this function **emscripten_set_wheel_callback** causes NaN to be returned when using the scrollwheel on Internet Explorer 11 for the XY delta.

This function in library_html5
mouseWheelHandlerFunc is expecting the event to have the properties wheelDeltaX and wheelDeltaY but in Internet Explorer 11 it only has the property wheelDelta.

I think the Y delta code should updated with the following change, tried it and seems to work well
        {{{ makeSetValue('JSEvents.wheelEvent', C_STRUCTS.EmscriptenWheelEvent.deltaY, '-e["wheelDeltaY"] || -e["wheelDelta"]/* Invert to unify direction with the DOM Level 3 wheel event. */', 'double') }}};

The following code change doesn't fix the X delta by trying to set it to 0 I still get a NaN for that value, not sure how to get the delta to 0 when the property is not present.
{{{ makeSetValue('JSEvents.wheelEvent', C_STRUCTS.EmscriptenWheelEvent.deltaX, 'e["wheelDeltaX"]' || 0, 'double') }}};

Could this change be reviewed and submitted.
I have attached the change that contains the above changes.
[library_html5.zip](https://github.com/kripken/emscripten/files/426884/library_html5.zip)

Regards,

Mark

**Comment by kripken** [comment]
Thanks, this does look like something we should work around.

Would you like to create a pull request with this change? (if you haven't done that before, the process is basically: fork this repo's incoming branch; create a commit with your fix; push it to your fork; open a pull request to ours)

**Comment by mabrownptc** [comment]
Having created an incoming branch I've now noticed Harald Reingruber made two submissions to fix this on May the 12,13 2016

Add support for the wheelDelta in IE 11
 https://github.com/kripken/emscripten/commit/e7ae82583954c111118c3801bd3198e01332478f#diff-291d81f9d42b322a89881b6d91f7a122
 
 Small fix to the above change
 https://github.com/kripken/emscripten/commit/759beea47e8d1dd84c39be0f30ea2ff1b5e43c94#diff-291d81f9d42b322a89881b6d91f7a122

I'm not too sure how I create a pull requests containing these two changes to get them onto master. I don't see any pull request made by Harald.

**Comment by kripken** [comment]
You can do that by creating a fork of this repo if you don't already have one. Then cherry-pick those two commits to your incoming branch in your fork. Then open a [pull request](https://help.github.com/articles/using-pull-requests/) on this repo.

**Comment by juj** [comment]
Looks like this has already been fixed in the current code for y coordinate: https://github.com/kripken/emscripten/blob/incoming/src/library_html5.js#L310. Pushed the above commit to output 0 instead of NaN for the x coordinate. Thanks for highlighting this!
