### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by derofim** [kripken/emscripten#4500]
Hello.

**Issue**: Strange warnings (cache cleared).
**Example**: libc.h:72:18: note: expanded from macro 'LFS64'

**Full log**: https://gist.github.com/derofim/f9ae3775a6abb7df8abe14b623d984c6

Program runs fine.

**Comment by juj** [comment]
You can ignore these for now, they are benign. Most of those should have been cleaned up, I think #4393 is the last of them we still have. We should get those out by the next release.

**Comment by juj** [comment]
Above PR should clean up all the remaining warnings.
