### ISSUE TITLE
Help compiling openvpn

### ISSUE THREAD

**Issue by amilajack** [kripken/emscripten#4507]
I need help compiling openvpn to asm.js or wasm. I'm not a C++ dev so I really have no idea how to do this.

Here's the steps I followed:

```
git clone https://github.com/OpenVPN/openvpn.git
cd openvpn
autoreconf -i
./configure
emmake make
```

The last command fails with the output of:

```
make: *** No targets specified and no makefile found. Stop.
```

Although it reports that, `Makefile.am` and `Makefile.in` exist in the folder. Why is this?

**Comment by kripken** [comment]
[These docs](http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html?highlight=emconfigure) might help, in particular, you probably need `emconfigure` before `./configure`.

Then hopefully that will work and emit a `Makefile` file (the `.in` and `.am` files are what it is created from). If not, it should show an error you can investigate.

**Comment by amilajack** [comment]
@kripken Thanks! What do you think about the possibility of this tho? Doesnt openvpn forward traffic. How would that work in a browser?

**Comment by kripken** [comment]
Hmm I'm not sure what openvpn is. Networking I guess? If it can use WebSockets then it might work, emscripten can translate simple UNIX TCP sockets operations into WebSockets for you. But if it needs anything the web doesn't allow, that can't work of course. And even if it uses simple UNIX TCP sockets, you're probably looking at some debugging, as they don't work quite the same as natively.

**Comment by amilajack** [comment]
I see. Thanks for the explanation!
