### ISSUE TITLE
Manually set memory initializer path?

### ISSUE THREAD

**Issue by SaschaNaz** [kripken/emscripten#4513]
I want to put my emscripten-converted script for web browser in any arbitrary directory but the script always tries finding .js.mem file on the top directory where my .html file is exist.

```
/index.html
/built/output.js
/built/output.js.mem
```

I know getting current script path on JS is not that straightforward but then there should be a way to manually set path. Can I set it?

**Comment by kripken** [comment]
You can [define `locateFile` on `Module`](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.locateFile), and it will be called with file names, and what you return is the full path to them. (See examples in the test suite for usage.)

**Comment by SaschaNaz** [comment]
Works as I want. Thanks :D
