### ISSUE TITLE
WebGL 2 GL errors

### ISSUE THREAD

**Issue by pixelnerve** [kripken/emscripten#4514]
Hello everyone - I'm getting a few errors on some GL calls. This happens with WebGL 2 enabled and emscripten-incoming

These are the funcs and errors returned by it

```
GL_INVALID_ENUM

 glGetProgramiv( handle, GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH, &maxNameLen );
 glGetIntegerv( GL_VERTEX_ARRAY_BINDING, &vao );
 glGetIntegerv( GL_SAMPLER_BINDING, &sampler );
 glSamplerParameteri( samplerId, GL_TEXTURE_MAX_ANISOTROPY_EXT, anisoValue );


GL_INVALID_VALUE

 glGetActiveUniformBlockiv( handle, uniformBlockIndex, GL_UNIFORM_BLOCK_BINDING, &cbBlockBindingPoint );

``` 
Thanks in advance

**Comment by pixelnerve** [comment]
Here is a test program that shows some of the issues above 
(i've not recreated the issues with shader program or UBO as it needs some more work. Could do if really needed)

https://gist.github.com/anonymous/67f42faa92741cd7ca5b5ba0966b4ab9

**Comment by juj** [comment]
Thanks for the test case! Taking..

**Comment by juj** [comment]
This is now fixed in the above commit for the cases highlighted in the test case, except for the anisotropy bit, which looks like is an issue that interacts with the spec. Reported https://github.com/KhronosGroup/WebGL/issues/2006 about that. The uniform blocks will need separate handling.

**Comment by juj** [comment]
Thanks for reporting. This should now be fixed in the above commits. If you still have issues when running in the wild, let's explore it further through the new test cases.
