### ISSUE TITLE
sanity.test_struct_info regression from 80bd37a8a2fbd3bf73bf8825dba820358a206351

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4517]
80bd37a8a2fbd3bf73bf8825dba820358a206351 appears to have broken `sanity.test_struct_info`. cc @juj

**Comment by juj** [comment]
Oh right, indeed. Sorry for not noticing this earlier. There was a stray reference to proxied sbrk still. Fixed in above commit.
