### ISSUE TITLE
browser.test_glut_touchevents regression

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4518]
Looks like 1dffb515d633bcc718d136b0c2d711966b598109 broke `browser.test_glut_touchevents`.

cc @caiiiycuk

**Comment by caiiiycuk** [comment]
Sorry, i can`t reproduce it. On latest incoming on FF47 test is successful:
```
 python tests/runner.py browser.test_glut_touchevents
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_browser']
Running test_browser: (1 tests)
[Browser harness server on process 8685]

Running the browser tests. Make sure the browser allows popups from localhost.

test_glut_touchevents (test_browser.browser) ... [browser launch: test.html ]
[server response: /report_result?1 ]
[server response: /report_result?1 ]
ok
[Browser harness server terminated]

----------------------------------------------------------------------
Ran 1 test in 2.262s

OK
```

**Comment by kripken** [comment]
Strange, yes, on another machine it does pass for me. But on my one laptop, but firefox stable and nightly fail. Anyhow, must be a browser issue somehow, but it was triggered by that commit.

**Comment by massimilianonnx** [comment]
Excuse me for OFF TOpic but

from http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html 



Tip

If you are contributing to Emscripten you should build Emscripten from source.


Is not possible sort issues by priority ?

**Comment by juj** [comment]
This was seen in the buildbots, and fixed in https://github.com/kripken/emscripten/commit/5d480758f79465c37f5f7e6f4a38f531dfb7cdea
