### ISSUE TITLE
Option to Expose FS on Module

### ISSUE THREAD

**Issue by jvilk** [kripken/emscripten#4525]
Is there any way to expose the `FS` object on the `Module` object?

I'm running Emscripten in a scenario where I encapsulate Emscripten-generated code inside of a Function so I can invoke it at will. Thus, `FS` is not promoted to a global variable.

I tried changing `EXPORTED_RUNTIME_METHODS` to include `FS` and `EXTRA_EXPORTED_RUNTIME_METHODS` to include `FS`, but both of those seem limited to methods so `FS` is never added to `Module`.

I tried adding `Module['FS'] = FS;` to my `post.js` that gets appended to compiler output, but, naturally, that runs *after* `preInit` is called and Emscripten begins the program. I need to set up the file system before the program runs.

It looks like I might have to do something complicated for this use case, like defer main from running so I can access `FS` before invoking `main`?

**Comment by kripken** [comment]
You probably need to upgrade, this is possible on `incoming`. See more details in [this recent discussion](https://github.com/kripken/emscripten/issues/4515#issuecomment-242890364).

**Comment by jvilk** [comment]
Gotcha. I found a workaround that works for now (use `post.js` + `preRun` with the assumption that Emscripten has to do at least one asynchronous task), so I can stick with stable. Good to know this is a fixed limitation!
