### ISSUE TITLE
[csmith fuzzing] invalid code generated with BINARYEN=1 -O2 causing validation assertion failures

### ISSUE THREAD

**Issue by bnjbvr** [kripken/emscripten#4531]
The full report is there: https://benj.me/pub/emscripten-fuzz.zip

I've included:
- the C test case generated by csmith: `test.c`
- the emcc version used to compile: `emcc-version.txt`
- the command line used to compile: `compile.sh`
- the console error output: `error.log`
- the generated files by emscripten (output files as `a.out.*` and logs obtained from `EMCC_DEBUG=1`)

Please let me know if you need more information.

Are you generally interested in getting csmith fuzzing emscripten? I am planning to do some fuzzing of wasm implementations these days, and one way to do it is csmith + emscripten, we get emscripten fuzzing for free.

**Comment by sunfishcode** [comment]
The error is:

```
[wasm-validator error in function $xa] 1 != 0: function body type must match, if function returns, on 
(loop $while-out$0 $while-in$1
  (i32.store
    (i32.const 1528)
    (i32.const 1072)
  )
  (i32.store
    (i32.const 1268)
    (i32.const 29)
  )
  (br $while-in$1)
)
```

@kripken The code is an infinite loop, so there's no loop exit value, and while there are ongoing discussions about the specific rules, the current semantics roughly say that it's ok if it doesn't match the function return type. At first glance, it looks like binaryen is incorrectly raising a validation error here.

**Comment by kripken** [comment]
Yeah, we definitely do want to fuzz. Sorry for the confusion though, but because of the massive wasm changes in 0xc, most big work is on the `stack` branch. This testcase passes there, and in fact looks like a fuzz thing I fixed there already.

**Comment by bnjbvr** [comment]
OK, thanks for the answers. I'll defer fuzzing to when the binary format has stabilized (which I've been told would happen in 0xc, 0xd being only a defragmentation of the opcode space). Cheers!
