### ISSUE TITLE
The result of -O2 --closure 1 -s MODULARIZE=1 is broken

### ISSUE THREAD

**Issue by tomykaira** [kripken/emscripten#4538]
Because `MODULARIZE` assumes that the following code uses name `Module`, when `closure` and `O2` are specified, it is no the case.

```
emcc -O2 --closure 1 -s MODULARIZE=1 main.c
```

main.c

```
#include <emscripten.h>

int main(int argc, char *argv[]) {
  printf("hello\n");
  return 0;
}
```

output js:

```
var Module = function(Module) {
  Module = Module || {};

var b;b||(b=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));var g={},l;for(l in b)b.hasOwnProperty(l)&&(g[l]=b[l]);var n=!1,p=!1,r=!1,t=!1;
...
...

  return Module;
};
```

Because `Module` and `b` differ, the function returns empty object. This behavior is inconsistent the output without `-O2` or `-closure 1`. The problem may be more clear with `-s EXPORT_NAME'"exportName"'`.

**Comment by kripken** [comment]
Isn't this why we have that `eval`? It will find `Module` and return it, and then `b` is set to it.

**Comment by SaschaNaz** [comment]
I can repro this.

```cpp
#include <emscripten/bind.h>
using namespace emscripten;

int foo() {
  return 7;
}

EMSCRIPTEN_BINDINGS(foo) {
	function("foo", &foo);
}
```

**Comment by SaschaNaz** [comment]
with `-s EXPORT_NAME` thing it goes:

```js
var test = function(Module) {
  Module = Module || {};

var d;d||(d=eval("(function() { try { return test || {} } catch(e) { return {} } })()"));
/* ... */

  return Module;
};

... which won't work as `test` is undefined during the function call.
```

**Comment by SaschaNaz** [comment]
Opened a PR #4549 to fix this.

**Comment by SaschaNaz** [comment]
A fix is now merged and you can try it on incoming branch :D

**Comment by kripken** [comment]
Closing as this should be fixed by @SaschaNaz's PR. Please reopen if not.
