### ISSUE TITLE
On compatibility with strict mode: “Octal literals are not allowed in strict mode”

### ISSUE THREAD

**Issue by JianxinMa** [kripken/emscripten#4552]
Emscripten sometimes generates these code:
```javascript
flags &= ~0100000 /*O_LARGEFILE*/; // Ignore this flag from musl, otherwise node.js fails to open the file.
flags &= ~02000000 /*O_CLOEXEC*/; // Some applications may pass it; it makes no sense for a single process.
```
But “octal literals are not allowed in strict mode”.

Please consider using `~parseInt('0100000', 8)` instead of `~0100000`.

**Comment by juj** [comment]
Hmm.. I'd prefer using hex literals then. Those should be supported in strict mode?

**Comment by JianxinMa** [comment]
Yep. Hex literals are supported.

**Comment by kripken** [comment]
Hex literals sound good. All the relevant places to change should be in `src/library*.js`.

**Comment by juj** [comment]
Did a regex based search in sublime with `[^0-9/a-fx:\(\['\"\|\._#]0[0-9]` to find such occurrences of octals, found a few and changed in above commit. If there's more, let us know.
