### ISSUE TITLE
emscripten_webgl_create_context fails if canvas has no id attribute

### ISSUE THREAD

**Issue by beakbeak** [kripken/emscripten#4556]
Using 1.36.9, `emscripten_webgl_create_context` fails with the error `Could not create canvas: ?,TypeError: canvas.getContext is not a function` if `Module['canvas']` has no `id` attribute. The change that appears to have caused this is here: https://github.com/kripken/emscripten/commit/1b278917cd325c2aac877e4d09d1a8af07686c9f#diff-291d81f9d42b322a89881b6d91f7a122L1789

**Comment by juj** [comment]
Thanks, looking at this now.

**Comment by juj** [comment]
Fixed in https://git.io/vi25K now. Thanks for reporting, the new form is a bit cleaner as well.
