### ISSUE TITLE
Undefined symbol on curaEngine

### ISSUE THREAD

**Issue by minusplusminus** [kripken/emscripten#4576]
Hi, 

I'm using Emscripten to compile CuraEngine-15.04.3 to use in an browser. An older version I succeded allready, but I want to upgrade to an newer version:

I've executed it like this:
`emcc main.cpp src/modelFile/modelFile.cpp src/clipper/clipper.cpp -I. -o Cura_SteamEngine.js`

[](https://github.com/Ultimaker/CuraEngine/releases/tag/15.04.3) 

The build succeeds when building it in xCode, but Emscripten has some difficulties.

```
emcc main.cpp src/modelFile/modelFile.cpp src/clipper/clipper.cpp -I. -o Cura_SteamEngine.js
In file included from main.cpp:35:
./src/fffProcessor.h:631:34: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
            for(Polygons outline : part->skinOutline.splitIntoParts())
                                 ^
1 warning generated.
warning: unresolved symbol: _ZN4cura13generateSkinsEiRNS_18SliceVolumeStorageEiiii
warning: unresolved symbol: _ZN14ConfigSettings12readSettingsEv
warning: unresolved symbol: _ZN4cura11GCodeExport15writeFanCommandEi
warning: unresolved symbol: _ZN4cura11GCodeExport21setRetractionSettingsEiiiiii
warning: unresolved symbol: _ZN4cura14generateSparseEiRNS_18SliceVolumeStorageEiii
```
UPDATE

Solved it by adding  all the headers and cpp manually. Why didn't I have to do that before?
Thanks!

**Comment by juj** [comment]
You'll have to match the build system that Xcode runs for a native build. The Xcode project contains several .cpp files, so you will have to compile all of them for Emscripten as well, which requires pushing each of them through `emcc`.

Sounds like you got it working, so closing as resolved.
