### ISSUE TITLE
Documentation for byte length of UTF16 encoded string

### ISSUE THREAD

**Issue by zb3** [kripken/emscripten#4577]
Currently the docs say that `stringToUTF16` function requires `at most (str.length*2+1)*2 bytes of space in the HEAP.`. However, doesn't this assume that str.length is the unicode length of the string? In JS, it's not, it's the UTF16 length of the string..

The `lengthBytesUTF16` correctly returns `str.length*2`, because each code unit of the string occupies 2 bytes in memory. This function doesn't take null byte into account, so `stringToUTF16` would require at most `2*str.length+2` bytes. 

Am I missing something? Anyway, either the docs are correct or the `lengthBytesUTF16` function...

**Comment by juj** [comment]
Thanks, you are right. The implementation is correct, and the documentation is wrong. Fixed in https://github.com/kripken/emscripten/commit/60d03d782ed352516c2a404906d5fcee8d8f8e54.

(Note that the online documentation pages are built manually, so the update will not be live automatically)
