### ISSUE TITLE
cwchar functions were implemented ????

### ISSUE THREAD

**Issue by harykary** [kripken/emscripten#458]
Hi kripken,
My project use some function of cwchar (wchar.h in windows), but when i run it rises an error like that: 

Uncaught TypeError: Property '_wprintf' of object [object Window] is not a function 

So could you tell me why please ? I think Because all cwchar functions were not implemented, weren't it  ???

This is my test code:

    #include <stdio.h>
    #include <cwchar>
    int main(int argc, char** argv)
    {
	    wchar_t* strName = L"Test cwchar";
	    wprintf(L"%s\n", strName);
	    return 0;
    }

**Comment by juj** [comment]
This has been since implemented. Tested the above snippet and it works, although to note that one needs to use `%ls` (long string) instead of `%s` to print the wide string, so

    #include <stdio.h>
    #include <cwchar>
    int main(int argc, char** argv)
    {
        wchar_t* strName = L"Test cwchar";
        wprintf(L"l%s\n", strName);
        return 0;
    }

which builds and runs correctly.
