### ISSUE TITLE
WebAudio removed doppler functionality

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4587]
Looks like Web Audio API has remove support for computing doppler effects on spatial 3D audio sources. These correspond to calling `.setVelocity()` on the audio panner nodes.

This means we can't support OpenAL doppler effects anymore, so will need to replace those with no-ops or similar.

References:
- https://github.com/WebAudio/web-audio-api/issues/455
- https://github.com/WebAudio/web-audio-api/issues/372
- https://www.chromestatus.com/feature/5238926818148352

**Comment by sriharshachilakapati** [comment]
I did this a few months ago, in GWT-AL project, which provides OpenAL on top of WebAudio API for Java projects. I didn't primarily test it, but the algorithm is from the OpenAL Specification, and some of the code is taken from the OpenAL Soft library.

https://github.com/sriharshachilakapati/GWT-AL/blob/master/gwt-al/src/main/java/com/shc/gwtal/client/openal/ALSource.java#L106-L153

Maybe that is what you're looking after. I haven't tested it in depth, but for my ears, it plays similar to the implementation of OpenAL Soft on C programs.
