### ISSUE TITLE
Documentation: ccall and cwrap do not specify safe times to call

### ISSUE THREAD

**Issue by mcclure** [kripken/emscripten#4592]
Looking at http://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html#cwrap

I find documentation for `ccall` and `cwrap`. I do not, however, find documentation about when these functions are safe to call. Asking on #emscripten IRC, "azakai" said their belief was that `ccall` must wait for the runtime to be loaded, and `cwrap` can be called early (before the emscripten runtime loads) but that the callback returned by `cwrap` could not be called until the runtime loads. This is of interest to me because I wanted to call `cwrap` before launching my Emscripten program, perhaps in `preRun` or even before, to create several callbacks before they are needed.

Expected "behavior": The docs should include information about when ccall/cwrap become safe to run. "azakai" further suggests that there should be an automated test to verify this behavior does not change.

**Comment by kripken** [comment]
Proposed doc fix and test are in #4598.

**Comment by kripken** [comment]
This should now be fixed by that PR.

Thanks for the bug report!
