### ISSUE TITLE
--pre-js is not in front of everything

### ISSUE THREAD

**Issue by yglukhov** [kripken/emscripten#4599]
Code emitted with `--pre-js` is placed after `loadPackage` related stuff. This makes it impossible to control `loadPackage` behavior by adjusting `filePackagePrefixURL` from inside the resulting js file, which is a PITA.
emscripten version: 1.36.11

**Comment by kripken** [comment]
Another option is to use the file packager in a more manual manner: run it by itself, get the JS, and then add that JS in a `--pre-js`. Then you can specify the order of the pre-jses as you want, explicitly.

**Comment by yglukhov** [comment]
That looks like an option indeed. Thanks.
