### ISSUE TITLE
NetCDF-4 failing for z library

### ISSUE THREAD

**Issue by maasencioh** [kripken/emscripten#4620]
Hello, I'm trying to parse [netcdf-c-4.4.1](https://github.com/Unidata/netcdf-c) as described in [their tutorial](http://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#build_default), but when I try to do `CPPFLAGS=-I${H5DIR}/include LDFLAGS=-L${H5DIR}/lib emconfigure ./configure` I get the following error:

`configure: error: Can't find or link to the z library.`

This error doesn't happen when I remove the `emconfigure` label, so the z library and HDF5 dependencies should be configured and installed.

PS: If I remove the dependency with the tag `--disable-netcdf-4` it works, but I need those functions

**Comment by kripken** [comment]
It would depend on how that particular configure script works, but if the necessary library is `zlib`, then to use it in emscripten just add `-s USE_ZLIB=1` to `CFLAGS` or in some way that the configure and makefile will pass that in each invocation of emcc that needs zlib.

**Comment by maasencioh** [comment]
hello @kripken, thanks for the answer, appaerntly that solves the problem, but still I have an error of `error: Can't find or link against libdf`, but this libraries are in `${H5DIR}/lib`, so it should be added in the LDFLAGS variable, isn't it? there's not a general way to point this directory as a dependency resolver? thank you for the help

**Comment by kripken** [comment]
You might need to add `-L` plus that path, to the emcc arguments, so it finds the libraries in there.

**Comment by maasencioh** [comment]
the problem is that I'm not using emcc, I'm using emconfigure, I got this [congig.log](https://gist.github.com/maasencioh/3a3d70b01291a885eca7187d062e836d) file, I'm trying to fix it but I'm still unaviable to do it, it seems to don't be capable to find the libraries in `/usr/lib64/lib/`

**Comment by kripken** [comment]
`/usr/lib64/` is a local system directory? emscripten can only link with platform-independent code, not a local system binary.

**Comment by maasencioh** [comment]
That was the directory where I build the other libraries, but if I try that somewhere else it's still failling the build, I would try with other ideas and the porblem it's not related anymore with zlib, so I'll close this issue, thanks!
