### ISSUE TITLE
incrementing variables such as 'classy->post[i++].x' in array subscripts does not work.

### ISSUE THREAD

**Issue by TheJohnTalent** [kripken/emscripten#4621]

**Comment by kripken** [comment]
Do you have a small testcase showing the problem?

**Comment by TheJohnTalent** [comment]
yes, but this is just from memory.////////////////
int x1;
unsigned int i;
class Point{public:
  int x;  int y;
}
class thisstruct{public:
   Point point[128];
}

thisstruct->point[i++].x=x1;
/////////////
the problem is the i++ inside the array subscript.
something like the above. no compile errors.
//changing to:i=i+1;
thisstruct->point[i].x=x1;fixes the problem.

**Comment by EyeGem** [comment]
**2JohnTheTalent:**
Post-increment (i++) increments i after assignment.
Why do you expect any other behaviour?
How does this apply to Emscripten?
Consider your C/C++ manual.

**Comment by kripken** [comment]
Yes, this looks like correct C/C++ behavior.

@TheJohnTalent: it's useful to compare results on a native compiler to emcc, if they both give you something surprising, then in my experience it's often a bug in the code.

**Comment by juj** [comment]
If the author is seeing something that behaves different to native execution, I bet that it could be something related to unaligned data. If so, doing a debug build with the linker flag `-s SAFE_HEAP=1` is a good first try, that will add extra checks for proper expected alignment to each memory operation.

**Comment by TheJohnTalent** [comment]
it doesn't matter if it's i++ or ++i it still causes an error in the browser at runtime.
fixing only it to i=i+1 before the array access fixes it solely and completely.

try consulting your emscripten code for this 'feature'.

you must understand that this is a fault in emscripten.

**Comment by TheJohnTalent** [comment]
try before you deny.

**Comment by TheJohnTalent** [comment]
consider this case closed by the submitter.

**Comment by kripken** [comment]
Glad you found the problem.

**Comment by TheJohnTalent** [comment]
There was am .x increment and a .y increment in each subscript and the second onecreated only even numbered accessed which doubled the actual range limited read accessfor which there were no allocation from midway in it and on.
the post[++i].x actually works but the following line post[++i].y skips the end of the pair.
