### ISSUE TITLE
problem installing libpng

### ISSUE THREAD

**Issue by bobWinner** [kripken/emscripten#4626]
i'm using portable emscripten on linux (debian) and i'm trying to install libpng

i've downloaded the archive here : https://github.com/emscripten-ports/libpng

when i run ./autogen.sh before ./configure, to create "configure" and "Makefile.in" which are
not included in the GIT repository, the console answers me : 

	./autogen.sh: 169: ./autogen.sh: autoreconf: not found
	autoreconf failed: your version of autotools is incompatible
	with this libpng version.  Please use a distributed archive
	(which includes the autotools generated files) and run configure
	instead.

i've never did such installations before and i really don't know how to handle this.

- how to download a "distributed archive" ?

- is installation the good way to deal these kind of libs ? (assuming in the famous "http://www.learnopengles.com/loading-a-png-into-memory-and-displaying-it-as-a-texture-with-opengl-es-2-adding-support-for-emscripten/" example, they do not install the lib but include it in the project files)

**Comment by kripken** [comment]
The simplest thing is to let the ports system do it for you - build with `-s USE_LIBPNG=1` in your emcc flags, and it should just work.

**Comment by bobWinner** [comment]
this was so simple, 
and the compiler also automatically installed zlib at first use.
wonderful, thank you.
