### ISSUE TITLE
1.36.12: error in mkdirTree, invalid argument

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#4646]
Trying to upgrade to 1.36.12 I get error `Invalid argument` in `mkdirTree`:

``` js
    // Creates a whole directory tree chain if it doesn't yet exist
    mkdirTree: function(path, mode) {
      var dirs = path.split('/');
      var d = '';
      for (var i = 0; i < dirs.length; ++i) {
        d += '/' + dirs[i];
        try {
          FS.mkdir(d, mode);
        } catch(e) {
          if (e.errno != ERRNO_CODES.EEXIST) throw e; // <- Invalid argument
        }
      }
    },
```

Investigating it seems it doesn't like `throw e`. Replacing `throw e` with `{}` fixes the error and the page works. I would make a pull request but I don't know why this error happens.

**Comment by juj** [comment]
It looks like `FS.mkdir(d, mode);` is failing with the "Invalid argument" error. Are you able to reproducibly raise the error? Can you try printing out `d` and `mode` params that go to `FS.mkdir`:

    ...
    console.log('d: ' + d + ', mode: ' + mode);
    FS.mkdir(d, mode);
    ...

perhaps one of these two is the bad argument.

**Comment by gouletr** [comment]
Got this output:
```
d: /data, mode: undefined
```

**Comment by gouletr** [comment]
yeah...
```
      function() { // preFinish
        // if the destination directory does not yet exist, create it
        FS.mkdirTree(destinationDirectory);
      }
```

**Comment by gouletr** [comment]
Perhaps do like `mkdir` and do the following in case `mode` is undefined?
```
      mode = mode !== undefined ? mode : 511 /* 0777 */;
      mode &= {{{ cDefine('S_IRWXUGO') }}} | {{{ cDefine('S_ISVTX') }}};
      mode |= {{{ cDefine('S_IFDIR') }}};
```

**Comment by gouletr** [comment]
nope that didn't work :(

**Comment by gouletr** [comment]
Ok I think I understand the issue better now, it fails in `mknod` here:
```js
      if (!name || name === '.' || name === '..') {
        throw new FS.ErrnoError(ERRNO_CODES.EINVAL);
      }
```
printing the directory inside the `mkdirTree` function, we find that the very first directory it tries to create is `/.` which is not valid.

We are not trying to create any folders with such a path, and the only place it ends up calling `mkdirTree` would be from `emscripten_async_wget`. Somehow that function is passing dots to `mkdirTree`. I'll keep digging.

**Comment by gouletr** [comment]
Found it:
```
var destinationDirectory = PATH.dirname(_file);

**Comment by gouletr** [comment]
Previously we were able to pass file names without having to put a `/` in front, should that still work with the mkdirTree change?

**Comment by juj** [comment]
Thanks for debugging this. Looks like `emscripten_async_wget()` needs to be able to take in destination path names that are relative to cwd? Added PR #4649 which adds testing for this and implements support for relative path names for the destination directory. Does that look like what you'd expect?

**Comment by gouletr** [comment]
Fix merged, we can close this.
