### ISSUE TITLE
[bug?] TypeError: Module.requestFullscreen is not a function[Learn More]

### ISSUE THREAD

**Issue by jadekler** [kripken/emscripten#4684]
I'm trying the [web assembly demo](http://webassembly.org/demo/), and when I hit the emscripten 'Fullscreen' button I'm getting console error `Module.requestFullscreen is not a function`. Might be related to https://github.com/kripken/emscripten/issues/3283.

<img width="654" alt="screen shot 2016-11-01 at 7 50 46 am" src="https://cloud.githubusercontent.com/assets/3584893/19891925/ebcac83c-a007-11e6-8bc9-6a8e8420c576.png">

edit: I'm running firefox nightly, although I saw this in Chrome 54.0.2840.71 too.

**Comment by kripken** [comment]
Hmm, I don't see a fullscreen button? Weird.

In any case, this is probably a bug on the wasm website, can you open a bug on https://github.com/WebAssembly/website ?

**Comment by jadekler** [comment]
@kripken Will do!

**Comment by kripken** [comment]
Thanks. Let's close this meanwhile. If we need to we can reopen later.
