### ISSUE TITLE
Premature end when reading file with tools/file2json.py on Windows

### ISSUE THREAD

**Issue by russaa** [kripken/emscripten#4688]
I had a problem with [tools/file2json.py](https://github.com/kripken/emscripten/blob/master/tools/file2json.py) (Windows 10, MinGW):

when trying to read files, the script did prematurely stop, i.e. did not read the file completely

The solution for me was, to explicitly set the reading mode to binary upon opening the file, i.e. change `tools/file2json.py` from _(lines 15 and 34 w.r.t. current master branch, [45bf4d9](https://github.com/kripken/emscripten/commit/45bf4d99ac9d55b182c0aabbf9f2ae73f2c5a3f4))_
```python
...
line 15 | data = open(sys.argv[1], 'r').read()
...
line 34 | data = open(sys.argv[1], 'r').read()
...
```
to
```python
...
line 15 | data = open(sys.argv[1], 'rb').read()
...
line 34 | data = open(sys.argv[1], 'rb').read()
...
```

since the documentation for this script explicitly states, that files are read as binary files, this modification could probably safely applied to the repository, too

**Comment by kripken** [comment]
Thanks, that makes sense. Would you like to open a pull request with that?

**Comment by juj** [comment]
This was fixed in the above PR.

Do we have a test to verify this?
