### ISSUE TITLE
"Unclear preprocessor command: #W∩┐╜L∩┐╜0∩┐╜∩┐╜0n0" | undefined

### ISSUE THREAD

**Issue by YairMobile19** [kripken/emscripten#4697]
Hello,

I'm getting the error "Unclear preprocessor command..." when linking emscripten compiled files.

I'm linking module "A.js" with "B.bc".

Has anyone encountered something like that?

Thanks.

the log shows:

Internal compiler error in src/compiler.js! Please raise a bug report at https://github.com/kripken/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "Unclear preprocessor command: #W∩┐╜L∩┐╜0∩┐╜∩┐╜0n0" | undefined
1>  Traceback (most recent call last):
1>    File "C:\Emscripten\emscripten\1.35.0\\emcc", line 1344, in <module>
1>      final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
1>    File "C:\Emscripten\emscripten\1.35.0\tools\shared.py", line 1571, in emscripten
1>      call_emscripten(cmdline)
1>    File "C:\Emscripten\emscripten\1.35.0\emscripten.py", line 1304, in _main
1>      temp_files.run_and_clean(lambda: main(
1>    File "C:\Emscripten\emscripten\1.35.0\tools\tempfiles.py", line 64, in run_and_clean
1>      return func()
1>    File "C:\Emscripten\emscripten\1.35.0\emscripten.py", line 1310, in <lambda>
1>      DEBUG_CACHE=DEBUG_CACHE,
1>    File "C:\Emscripten\emscripten\1.35.0\emscripten.py", line 1208, in main
1>      temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
1>    File "C:\Emscripten\emscripten\1.35.0\emscripten.py", line 201, in emscript
1>      cwd=path_from_root('src'), error_limit=300)
1>    File "C:\Emscripten\emscripten\1.35.0\tools\jsrun.py", line 75, in run_js
1>      raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
1>  Exception: Expected the command ['C:/Emscripten/node/4.1.1_64bit/bin/node', 'C:\\Emscripten\\emscripten\\1.35.0\\src\\compiler.js', 'c:\\users\\tc61692\\appdata\\local\\temp\\tmpjvbvvk.txt', 'C:\\Prj\\MapCore7\\Dev\\MapCore\\Bin\\Emscripten\\SceneManager.bc', 'C:\\Emscripten\\emscripten\\1.35.0\\src\\embind\\emval.js', 'C:\\Emscripten\\emscripten\\1.35.0\\src\\embind\\embind.js', 'C:\\Emscripten\\emscripten\\1.35.0\\src\\library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
1>  // and export values on it, and do the work to get that through
1>  // closure compiler if necessary. There are various ways Module can be used:
1>  // 1. Not defined. We create it here
1>  // 2. A function parameter, function(Module) { ..gener

**Comment by kripken** [comment]
You can only link object files (with suffix `o, bc, a`, all containing bitcode). There are some options for linking JS files, but that is a separate thing, https://github.com/kripken/emscripten/wiki/Linking

**Comment by YairMobile19** [comment]
Right, thanks.
