### ISSUE TITLE
Minify JS in WASM mode

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4702]
We currently disable the JS optimizer in WASM/BINARYEN mode, as we don't need it - we generate wasm and optimize it using the binaryen optimizer. However, that has the effect that we don't minify the JS shell code (the non-compiled code).

For large projects it's negligible, but for smaller ones the JS shell code can be a significant chunk of total size, so we should fix this. Basically, we need to run the 'cleanup' js optimizer pass on the JS (after we split out the asm.js). The one tricky thing is that right now the JS optimizer assumes we are optimizing the compiled code too, so it looks for the asm.js markers, which are not there in this case, so some refactoring might be needed.

It might also make sense to look into enabling the minifier in this case.

**Comment by brion** [comment]
Is this still an issue? As of 1.37.28, my JS shell code in the wasm output mode appears to be minified (but I might be missing some optimizations I'm not knowing to look for).

**Comment by kripken** [comment]
Correct, thanks, this was fixed a while back. In fact we now have a bunch of interesting JS optimizations for the JS/wasm combination (meta-dce, blogpost coming next week).
