### ISSUE TITLE
emcc does not understand BINARYEN flag

### ISSUE THREAD

**Issue by bodokaiser** [kripken/emscripten#4710]
Still will compile without that flag.

```
emcc main.c -o build.js -s BINARYEN=1
llc: Unknown command line argument '-emscripten-only-wasm'.  Try: '/usr/local/opt/emscripten/libexec/llvm/bin/llc -help'
llc: Did you mean '-emscripten-wasm'?
Traceback (most recent call last):
  File "/usr/local/bin/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/emcc.py", line 1561, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/tools/shared.py", line 1740, in emscripten
    call_emscripten(cmdline)
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/emscripten.py", line 1767, in _main
    temp_files.run_and_clean(lambda: main(
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/emscripten.py", line 1772, in <lambda>
    DEBUG=DEBUG,
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/emscripten.py", line 1673, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/emscripten.py", line 91, in emscript
    funcs, metadata, mem_init = get_and_parse_backend(infile, settings, temp_files, DEBUG)
  File "/usr/local/Cellar/emscripten/1.36.13/libexec/emscripten.py", line 164, in get_and_parse_backend
    start_funcs = backend_output.index(start_funcs_marker)
ValueError: substring not found
```

`main.c`
```c
#include <stdio.h>
#include <emscripten.h>

int main(int argc, char **argv) {
	printf("Hello World!\n");
}
```

```
 emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.13
clang version 3.9.0  (emscripten 1.36.5 : 1.36.5)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
ERROR:root:Emscripten, llvm and clang build versions do not match, this is dangerous (1.36.13, 1.36.5, 1.36.5)
ERROR:root:Make sure to rebuild llvm and clang after updating repos
INFO:root:(Emscripten: Running sanity checks)
```

Installed via `brew install llvm --with-clang && brew install emscripten` on latest macOS.

**Comment by kripken** [comment]
Those `ERROR`s indicate a problem. Perhaps brew did not package up things properly? Basically, their emscripten repo is new, but the llvm and clang repos it uses are old.

**Comment by bodokaiser** [comment]
What are the llvm and clang versions emscripten requires? Maybe I can send a PR to homebrew.

**Comment by kripken** [comment]
They need to be the same emscripten version (`emscripten-version.txt` files note that, in each repo). For example, just get the latest in the master branch in all 3 repos, or the latest in the incoming branch in all three repos, or use the same tag (`1.*`) in all 3 repos.

**Comment by bodokaiser** [comment]
I made a PR to homebrew which fixes the versions.

However I noticed that the homebrew formula does miss [binaryen](https://github.com/WebAssembly/binaryen) to fully support webassembly.

Should I create a new formula for binaryen or does it make more sense to put it into the emscripten formula?

**Comment by kripken** [comment]
Binaryen should just work, emscripten will download and build it on demand. (Unless that doesn't work due to some homebrew limitation, I don't know much about homebrew?)

**Comment by bodokaiser** [comment]
```
emcc main.c -s WASM=1 -o build.js
Traceback (most recent call last):
  File "/usr/local/bin/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.36.14/libexec/emcc.py", line 1609, in run
    wasm_js_glue = open(os.path.join(shared.Settings.BINARYEN_ROOT, 'src', 'js', 'wasm.js-post.js')).read()
IOError: [Errno 2] No such file or directory: u'/usr/bin/src/js/wasm.js-post.js'
```

I don't think it does download and built on demand (`emsdk` is not available if you mean this).

**Comment by kripken** [comment]
Is `BINARYEN_ROOT` set in your env? That will override it and prevent it from downloading it itself (it thinks you want a local version).

Build with `EMCC_DEBUG=1` in the env to see more output about what it is doing, might help here.

**Comment by kripken** [comment]
I meant, is `BINARYEN_ROOT` set in the env or in the emscripten settings file.

**Comment by bodokaiser** [comment]
Yep, this fixed it. Compilation with `WASM=1` or `BINARYEN=1` works now!

I will add a note to the homebrew formula regarding this.

**Comment by kripken** [comment]
Great!

**Comment by juj** [comment]
The download and build on demand feature works independent of whether emsdk is being used. In emsdk the Binaryen install step is done via `emsdk install`, so to use latest Binaryen with Emscripten incoming, one can run

	git clone https://github.com/juj/emsdk.git
	cd emsdk
	./emsdk install sdk-incoming-64bit binaryen-master-64bit
	./emsdk activate sdk-incoming-64bit binaryen-master-64bit
	source ./emsdk_env.sh
