### ISSUE TITLE
Out of memory in Chrome when debugging

### ISSUE THREAD

**Issue by YairMobile19** [kripken/emscripten#4731]
Hello,
I am having great difficulties debugging the code generated by Emscripten.
I've compiled my code-base with the -g4 flag, and produced source maps. 
I think that the resulted code is too complex for the browser, and I encounter various unstable behaviors (browser crashing, mainly).
Is there any solution for this problem?
Is it possible to compile only one module with the -g4 flag? And not all of the models?

Thank you.

**Comment by juj** [comment]
If you have test cases that crash the browser, then it's good to zip those up and post a bug report to the browser in question.

Does debugging in Firefox work any better for the project?

**Comment by YairMobile19** [comment]
Unfortunately firefox doesn't handle it any better. It doesn't crash but it freezes and won't stop at any of the breakpoints.

**Comment by kripken** [comment]
If you open browser bugs on those, please link them here, it's interesting to follow those.
