### ISSUE TITLE
emcc:  Argument list too long

### ISSUE THREAD

**Issue by JerryYangJin** [kripken/emscripten#4735]
Hello, I'm working on a large project, I need to use `-s EXPORTED_FUNCTION = "[$funcs]"` option.

I provided the list, it's 10000+, and I'm getting `Argument list too long` error message.

I saw this ticket #3689 closed, it's a fix to this issue, not sure if it's implemented.

I don't see in `emcc --help` or official document how to use a file to store the list.

please help, how should I export long lists of functions?

Thanks a lot!

**Comment by kripken** [comment]
You can use a response file, something like `EXPORTED_FUNCTIONS=@filename`, see `test_exported_response` in `tests/test_core.py` for an example.

**Comment by JerryYangJin** [comment]
@kripken , thanks for the update, I found what I actually need is WEBIDT, 'cause the project is C++, exported functions have long mangled name, it's very difficult to use
