### ISSUE TITLE
Linking error of project with googletests.

### ISSUE THREAD

**Issue by redcat1** [kripken/emscripten#4739]
Hello,

When I tried to compile my project with googletests I've got an error:

**error: Linking globals named '_ZN7testing8internal11g_help_flagE': symbol multiply defined!
Traceback (most recent call last):
  File "/opt/emsdk/emscripten/master/em++", line 13, in <module>
    emcc.run()
  File "/opt/emsdk/emscripten/master/emcc.py", line 1364, in run
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/opt/emsdk/emscripten/master/tools/shared.py", line 1491, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
UnitTests/CMakeFiles/unit_tests.dir/build.make:2501: recipe for target 'Bin/unit_tests.js' failed
make[2]: *** [Bin/unit_tests.js] Error 1
CMakeFiles/Makefile2:140: recipe for target 'UnitTests/CMakeFiles/unit_tests.dir/all' failed
make[1]: *** [UnitTests/CMakeFiles/unit_tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
**

I haven't variable with the same name in my project. It's using in googletests only.

**Comment by kripken** [comment]
It would be good to reduce this to a small standalone testcase showing the issue. Perhaps llvm-link is misbehaving, or we are using it wrong.

**Comment by redcat1** [comment]
It was my fault. I linked my core library to googletests as a shared library. When I started to link it as a static library everything started to go right.
