### ISSUE TITLE
"unresolved symbol" warning when including library

### ISSUE THREAD

**Issue by justinmc** [kripken/emscripten#4744]
I'm trying to get a very simple program to compile with the library [openbabel](http://openbabel.org).  I've installed openbabel, run pkg-config to get the correct -L and -I flags, and when I compile with g++, everything works fine.  But when I compile with em++, I get a bunch of "unresolved symbol" errors:

    $ em++ myprogram.cpp -I/usr/local/include/openbabel-2.0 -L/usr/local/lib -lopenbabel -o myprogram.html
    warning: unresolved symbol: _ZN9OpenBabel12OBConversionD1EV
    warning: unresolved symbol: _ZN9OpenBabel12OBConversionC1EPNSt3__213basic_istreamIcNS1_11char_traitsIcEEEEEPNS1_13basic_ostreamIcS4_EE    

Running the output in the browser doesn't work and gives similar outputs in the javascript console:

    missing function: _ZN9OpenBabel12OBConversionC1EPNSt3__213basic_istreamIcNS1_11char_traitsIcEEEEPNS1_13basic_ostreamIcS4_EE

    Uncaught abort(-1) at Error

I've simplified my code down as far as possible, to this:

    #include <iostream>
    #include <openbabel/obconversion.h>
    using namespace std;

    int main(int argc,char **argv)
    {
      cout << "program started\n";
      OpenBabel::OBConversion converter = OpenBabel::OBConversion();
      cout << "declared openbabel object\n";
      return 0;
    }

When I run it in the browser, I see the first "program started" output in the emscripten console, then a -1 and the second cout never gets hit.

If I comment out the line where I use OpenBabel (keeping the include), it compiles fine and runs to completion in the browser.

I'm running emscripten 1.36.14.

**Comment by kripken** [comment]
You can use `llvm-nm` to show the symbols in that library, make sure those missing ones are in there. `EMCC_DEBUG=1` in the env when you build will show which libraries it links with, which can help too. `-s VERBOSE=1` as an argument will print even more linking stuff.

**Comment by justinmc** [comment]
My problem was that I was trying to compile my code with a regular installation of openbabel, and I didn't realize I needed to compile it to llvm bitcode (as [the docs admittedly do say](http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries)).

Thanks for the quick response, you got me looking in the right direction.
