### ISSUE TITLE
FAIL: Running the generated program failed!

### ISSUE THREAD

**Issue by Ni55aN** [kripken/emscripten#4753]
I have built this compiler successfully without errors  on Ubuntu 16.04 x64

But when I tried to compile a simple example, I get an error
> /usr/lib/emscripten/clang/fastcomp/build_master_64/bin/lli: error creating EE: No available targets are compatible with this triple, see -version for the available targets.
> FAIL: Running the generated program failed!

Installation was performed according to the instructions
https://kripken.github.io/emscripten-site/docs/tools_reference/emsdk.html#compiler-configuration-file

**Comment by kripken** [comment]
What does `emcc --version` say?

**Comment by Ni55aN** [comment]
@kripken, emcc (Emscripten GCC-like replacement) 1.22.1 ()

**Comment by Ni55aN** [comment]
`./emsdk list` say

```

The following precompiled tool packages are available for download:
           node-4.1.1-32bit         
     *     node-4.1.1-64bit         	INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
     *     emscripten-1.35.0        	INSTALLED

The following tools can be compiled from source:
           clang-tag-e1.36.13-32bit 
           clang-tag-e1.36.14-32bit 
           clang-tag-e1.36.13-64bit 
           clang-tag-e1.36.14-64bit 
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
     *     clang-master-64bit       	INSTALLED
           emscripten-tag-1.36.13-32bit
           emscripten-tag-1.36.14-32bit
           emscripten-tag-1.36.13-64bit
           emscripten-tag-1.36.14-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
           emscripten-master-64bit  	INSTALLED

The following precompiled SDKs are available for download:

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
         sdk-master-64bit         	INSTALLED
         sdk-tag-1.36.13-32bit    
         sdk-tag-1.36.14-32bit    
```

**Comment by kripken** [comment]
That's a quite old version, I'd make sure to update to at least 1.36.0, which is on current master.

**Comment by Ni55aN** [comment]
Thank you, I reinstalled the SDK and found that it was previously installed for root, but not for user

**Comment by kripken** [comment]
Ok good, closing this then.

**Comment by shameerariff** [comment]
I am getting the same error even after installed version was upto date.
Done installing tool 'emscripten-1.38.10'.
Done installing SDK 'sdk-1.38.10-64bit'.
and the installed packages are listed below
clang-e1.38.10-64bit
node-8.9.1-64bit
emscripten-1.38.10
clang-incoming-64bit
emscripten-incoming-64bit
binaryen-master-64bit
sdk-1.38.10-64bit
sdk-incoming-64bit
when I am compiling the sample hello I am getting the following 
**emcc hello.c -s WASM=1 -o hello.html**

WARNING  root: Assigning a non-existent settings attribute "WASM"
WARNING  root:  - did you mean one of ASM_JS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
/home/shameerariff/Source/emsdk/clang/fastcomp/build_incoming_64/bin/lli: error creating EE: No available targets are compatible with this triple.
FAIL: Running the generated program failed!

Can you please help me on this.

**Comment by kripken** [comment]
@shameerariff what does `emcc -v` say? (maybe there's an older version of emcc in your path)

**Comment by shameerariff** [comment]
Yes you are correct, I corrected this issue.
