### ISSUE TITLE
Harfbuzz

### ISSUE THREAD

**Issue by mahmoudghonim** [kripken/emscripten#4754]
I'm trying to compile "Harfbuzz" which is a text shaping library.

According to this link 
http://blog-archive.copyninja.info/2012/07/compiling_harfbuzz_on_debian.html
Harfbuzz requires following library and binary compilation:
    1. libglib2.0-dev: Glib Development files
    2. libcairo2-dev : Cairo 2D graphics library development files
    3. libicu-dev: Development components for International components for Unicode
    4. libgraphite2-dev: Development files for libgraphite2
    5. libfreetype6-dev: Freetype 2 library development files

So that I have to compile the previous fifth libraries to bit code first 
libglib2.0-de.bc 
libcairo2-dev.bc 
libicu-dev.bc 
libgraphite2-dev.bc 
libfreetype6-dev.bc 
and link them with harfbuzz.bc

Is That Right??

**Comment by kripken** [comment]
If it doesn't have an option to not use those, then yes. E.g. perhaps it has a way to render without cairo?

Note that freetype is in emscripten ports, so that is done already.

**Comment by mahmoudghonim** [comment]
I'm trying to compile harfbuzz using Emscripten to get harfbuzz as a bit code "harfbuzz.bc" or "harfbuzz.js"

According to : https://github.com/TheCherno/Sparky/edit/3D/Dependencies/FreeType-Emscripten/em_build_freetype.bat

I'm trying to simulate sparky Emscripten Experience with "Harfbuzz".
http://pastebin.com/z5G3apC0
I successfully compiled freetype source code ==> freetype.bc

but I failed to compile "Harfbuzz" I faced Exception "helper-cairo-ansi.cc:28:"
In file included from /home/mahmoud/Desktop/hello_world/harfbuzz-master/util/helper-cairo-ansi.cc:28:
/home/mahmoud/Desktop/hello_world/harfbuzz-master/util/options.hh:261:5: error: use of undeclared identifier
'hb_ot_shape_glyphs_closure'
hb_ot_shape_glyphs_closure (font, buffer, features, num_features, glyphs);
^
1 error generated.
ERROR root: compiler frontend failed to generate LLVM bitcode, halting

Any help plz.

**Comment by kripken** [comment]
Check if it compiles natively with the clang emscripten uses. Sometimes that clang, which is fairly new, has extra errors that old codebases trigger. Then you may need to fix the project to avoid those warnings/errors. In that specific error, perhaps that function needs to be properly declared (which old C versions don't require).

**Comment by juj** [comment]
I've worked on a closed codebase that does use HarfBuzz, and it does build through with Emscripten. I did not develop the original build system/conversion to it, so I'm not sure if their port had something stripped out of it, but looking at the build of the project, I see FreeType2 to be the only dependency that HarfBuzz has in there, so perhaps the other dependencies are all optional and can be excluded if not needed.

It is best to build HarfBuzz via CMake, since it does have a CMakeLists.txt file and CMake build scripts support cross-platform builds better than `./configure` does. (`emcmake cmake .` and `make` to build)

**Comment by lowdesertpunk** [comment]
We are using Harfbuzz in our engine and it compiles and runs fine with Emscripten too. None of those dependencies are needed, not even freetype2. Our build is using a custom CMakeLists.txt but originally I was using the supplied one, and they way @juj mentions should also work.

**Comment by ebraminio** [comment]
Hi, a harfbuzz maintainer here. HarfBuzz can be built without any of those dependency. We are building harfbuzz with emsdk on our [CI](https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L64-L70) but please let us know what is needed for your projects.

> Our build is using a custom CMakeLists.txt but originally I was using the supplied one, and they way @juj mentions should also work.

Was anything wrong with the originally provided CMakeLists.txt? Please let us know what was needed.

**Comment by lowdesertpunk** [comment]
Nothing wrong it's just because we build and package 3rd-parties in a custom and unified way to fit nicely into into our dependency management system.

**Comment by ebraminio** [comment]
> Nothing wrong it's just because we build and package 3rd-parties in a custom and unified way to fit nicely into into our dependency management system.

Oh, thanks. If you found anything useful to your use case and can be reused, please consider sharing it with us sometime. Thanks!

**Comment by ebraminio** [comment]
Hey all, feel free to have a look at harfbuzz/harfbuzz#743
