### ISSUE TITLE
nodejs not working for tests/hello_world_file.cpp

### ISSUE THREAD

**Issue by sampsh** [kripken/emscripten#4756]
Hi, I'm very new to emscripten and I'm working through the tutorials on the website. I came across the example for using files. I'm using a windows machine and emscripten 1.34.1 version.
I ran:
$ emcc tests/hello_world_file.cpp  (this complied fine)
$ node a.out.js
cannot open file

Why am i getting the "cannot open file?" How can I use node to display the results on the prompt? 

I also tried: 
$ emcc tests/hello_world_file.cpp -o hello.html --preload-file tests/hello_world_file.txt
$ node hello.js
throw 'using preloaded data can only be done on a web page or in a web worker';
      ^
using preloaded data can only be done on a web page or in a web worker

This didn't work also. 
Please let me know how I can do this. 
Thank you!!

**Comment by kripken** [comment]
As the error says, preloading uses some APIs that are on the web, but not in node.js Instead, you can use the `--embed-file` option, which embeds the file into the JS. That works in node, but increases the size of the file.

**Comment by sampsh** [comment]
I tried using the embed file option: 

$emcc tests/hello_world_file.cpp -o hello.html --preload-file tests/hello_world_file.txt
$node a.out.js
cannot open file

It ran in node now but cannot open the file?

**Comment by kripken** [comment]
How is it trying to open it? I don't remember offhand if the default is to store the file under `tests/` or not, try both ways.

**Comment by sampsh** [comment]
This is the code for hello_world_file.cpp. The textfile and this cpp file are located in the `tests/` directory.

#include <stdio.h>
int main() {
  FILE *file = fopen("tests/hello_world_file.txt", "rb");
  if (!file) {
    printf("cannot open file\n");
    return 1;
  }
  while (!feof(file)) {
    char c = fgetc(file);
    if (c != EOF) {
      putchar(c);
    }
  }
  fclose (file);
  return 0;
}

**Comment by kripken** [comment]
When I run this command, it works: `./emcc tests/hello_world_file.cpp --embed-file tests/hello_world_file.txt`, then run `node a.out.js`. Note that 

1. I use embed, which your last quoted command didn't, I guess that was just a typo though?
2. You have `-o hello.html`, but you ran `a.out.js`, so you ran something old and not what the compiler generated from that command.

**Comment by sampsh** [comment]
Its working now. Oops I meant to type `--embed-file` and also I ran `hello.js` instead of `a.out.js` which is why I was getting that error. Thank you so much!!

**Comment by hkamolov** [comment]
No when 

> Hi, I'm very new to emscripten and I'm working through the tutorials on the website. I came across the example for using files. I'm using a windows machine and emscripten 1.34.1 version.
> I ran:
> $ emcc tests/hello_world_file.cpp (this complied fine)
> $ node a.out.js
> cannot open file
> 
> Why am i getting the "cannot open file?" How can I use node to display the results on the prompt?
> 
> I also tried:
> $ emcc tests/hello_world_file.cpp -o hello.html --preload-file tests/hello_world_file.txt
> $ node hello.js
> throw 'using preloaded data can only be done on a web page or in a web worker';
> ^
> using preloaded data can only be done on a web page or in a web worker
> 
> This didn't work also.
> Please let me know how I can do this.
> Thank you!!

In my case, when I run in both preload and embed ways, it is not creating hello.html as well as hello.js files. But hello.data is there and hello.wasm is there created. How to fix this?

**Comment by hkamolov** [comment]
> Hi, I'm very new to emscripten and I'm working through the tutorials on the website. I came across the example for using files. I'm using a windows machine and emscripten 1.34.1 version.
> I ran:
> $ emcc tests/hello_world_file.cpp (this complied fine)
> $ node a.out.js
> cannot open file
> 
> Why am i getting the "cannot open file?" How can I use node to display the results on the prompt?
> 
> I also tried:
> $ emcc tests/hello_world_file.cpp -o hello.html --preload-file tests/hello_world_file.txt
> $ node hello.js
> throw 'using preloaded data can only be done on a web page or in a web worker';
> ^
> using preloaded data can only be done on a web page or in a web worker
> 
> This didn't work also.
> Please let me know how I can do this.
> Thank you!!

In my case, this is happening: not creating hello.html and hello.js. But hello.data and hello.wasm are both being created. And also, I am getting this answer: #4756 
The system cannot find the path specified.
emcc: error: 'C:\Emscripten\emsdk\upstream\emscripten\tools\file_packager.bat hello.data --from-emcc --export-name=Module --preload tests/hello_world_file.txt' failed (1)
