### ISSUE TITLE
Can't link to static library

### ISSUE THREAD

**Issue by dturevski** [kripken/emscripten#4763]
I must be missing something very basic here. Trying to build a big project with latest portable SDK on linux, tracked the problem down to this:

```
//a.h
#if !defined(A_H)
#define A_H
extern int foo[8];
#endif

//a.c
#include "a.h"
int foo[8];

//main.c
#include <stdio.h>
#include "a.h"

int main() {
    printf("%d\n", foo[0]);
    return 0;
}
```

```
emcc -o a.o a.c
emar rv library.a a.o
emcc -o main.o main.c
emcc -o a.js main.o library.a
warning: unresolved symbol: foo
```

However this works fine:
```
emcc -o a.o a.c
emcc -o main.o main.c
emcc -o a.js main.o a.o
```

And this works too:
```
gcc -c -o a.o a.c
ar rv library.a a.o
gcc -c -o main.o main.c
gcc -o a.out main.o library.a
```

**Comment by kripken** [comment]
Thanks, looks like this is indeed a bug. That object file defines `foo` as a "common", an uninitialized section, and we only looked at initialized sections for linking.

Possible fix is in #4764. Looks like it fixes this case, but i'm not sure it's the right solution yet.

**Comment by dturevski** [comment]
Yesterday, as a workaround, I commented out all such declarations in .c files and also removed `extern` keyword in .h files - luckily there was just a dozen of such places in the project. That allowed it to compile and run ok w/o optimization, but resulted in a very weird LLVM error when trying rebuild with optimize flags.
With your fixed tools/share.py it now happily compiles with -O2 (this development doesn't really make sense to me, but it's very nice to have)
Hope this information may help somehow and thank you!

**Comment by dturevski** [comment]
> it now happily compiles with -O2
It == the original code

**Comment by kripken** [comment]
Fixed by that PR.
