### ISSUE TITLE
WebIDL - interface Date conflict with Javascript Date class?

### ISSUE THREAD

**Issue by JerryYangJin** [kripken/emscripten#4784]
Hello, I'm using `WebIDL` to export a c++ project, which has it's own `Date` class.

when I try to export `Date` in `WebIDL` (I tried both with and without `[Prefix="Namespace::"]`), I got below error:

```sh
WebIDL.WebIDLError: error: invalid syntax, <unknown> line 8:10
interface Date {
```

Is it because `Date` is an existing JavaScript class? If yes, what are my options to export `Date` class from c++ project?

Thanks a lot!

**Comment by kripken** [comment]
Yeah, looks like the webidl parser has a list of reserved words and that's on the list.

Simplest thing is to just rename the class in C++. Or use a typedef to alias it.

**Comment by JerryYangJin** [comment]
@kripken , thank you!
