### ISSUE TITLE
WebIDL - DOMString to std::string

### ISSUE THREAD

**Issue by JerryYangJin** [kripken/emscripten#4792]
Hello, I'm using `WebIDL` to generate glue for my c++ project, the c++ code is using `std::string`, when I put `DOMString` in idl, the glue compiling will fail:

```
output.cpp:127:10: error: no viable conversion from returned value of type
      'const std::string' (aka 'const basic_string<char, char_traits<char>,
      allocator<char> >') to function return type 'const char *'
  return self->name();
```

output.idl

```
interface Output{
	void Output();
	[Const] DOMString name();
}
```

Is there any way that I can use `std::string` in WebIDL? Thanks!

**Comment by kripken** [comment]
Not directly. The IDL binder can handle C strings (`char*`). But you can assign such a string to an `std::string` in C++, of course.

**Comment by JerryYangJin** [comment]
@kripken , thanks for the reply, what I'm doing is replace char * in glue.cpp
