### ISSUE TITLE
function free in c does not work !?

### ISSUE THREAD

**Issue by ssx71** [kripken/emscripten#4798]
as you can see from this piece of code
the function 'c' free seems not to work

    #include <stdio.h>
    #include <stdlib.h>
    #include <emscripten.h>
    #include <string.h>

	int main ( void )
	{
		char *z = (char*)EM_ASM_INT(
		{
			var stringa = "STRING";

			return allocate(intArrayFromString(stringa), 'i8', ALLOC_NORMAL) ;

			
		},NULL );

		printf ("\nRETURNED %s %d" ,z,strlen(z) ) ; 

		free(z);
		 
		printf ("\nAFTER free RETURNED %s %d" ,z,strlen(z) ) ; 
		 
		return 0 ;
	}

console chrome  :

	pre-main prep time: 2 ms
	error.js:143 
	error.js:143 RETURNED STRING 6
	error.js:143 AFTER free RETURNED STRING 6
	
emscripten 1.35

**Comment by kripken** [comment]
`free` just frees the memory, which means malloc can reuse it for future allocations. But it doesn't zero out the memory contents or anything like that, so the old values are still there, as your example shows.

**Comment by ssx71** [comment]
It could be a problem if I have to know if the string is actually deallocated

	int freex ( char *s )
	{
		EM_ASM_INT(
		{
			Module._free( $0 ) ;
		
		},(unsigned int)s );

		s=0;
		
		return 0 ;	
	}
	
is this a right way to fix ? where is implemented _free ?

**Comment by gogoprog** [comment]
No, 's' would be changed only in your freex function scope.

Pointers are usually set back to null after being freed:

    free(myPointer)
    myPointer = NULL;

I don't see how emscripten is related to this issue...

**Comment by ssx71** [comment]
you are right it is not an issue. i'll do as you suggested to me.

2016-12-15 12:39 GMT+01:00 Gauthier Billot <notifications@github.com>:
