### ISSUE TITLE
Empty Assembly.Module when try to load .wasm file

### ISSUE THREAD

**Issue by ninja-hub** [kripken/emscripten#4805]
Hi. I am trying 'incoming' branch of emscripten to try WebAssembly.
I can get the .js file to work ok but I cannot get the .wasm file to work.
I compiled very simple cpp file and now trying to load it as webassembly at the moment.

add.cpp ----------
extern "C" {  
int myAdd(int a, int b) 
{
    return a + b;
}
}

emcc------------
emcc add.cpp -s BINARYEN=1 -s EXPORTED_FUNCTIONS=['_myAdd'] -o index.html

this produces index.html, index.js, index.wast and index.wasm

Then js code to load wasm, in the console -------

var xhr = new XMLHttpRequest();
xhr.responseType = 'arraybuffer';
xhr.onload = ready;
xhr.open('GET', 'index.wasm');
xhr.send(null);

function ready() {
    WebAssembly.compile(
       new Uint8Array(xhr.response)
    ).then( function(module) {
        myModule = module;
    }, function(err) {
        console.error("error " + err);
    });   
}

I opened generated index.html file from browsers and ran above javascript.
In chrome canary : myModule is an empty Object 
In Firefox nightly:  myModule is a WebAssembly.Module which does not contain anything.

I do not see any obvious errors in browser console.

Can anyone guide me what I am doing wrong please?

Best regards,

N

**Comment by kripken** [comment]
Does it work with the non-promise API? If so it might be a bug in promises in browsers. The non-promise API is what emscripten and binaryen [use to load wasm](https://github.com/WebAssembly/binaryen/blob/master/src/js/wasm.js-post.js#L186).

Note that in general the wasm file you get is not usable by itself. You need the imports stuff as in the link there, and in general, the wasm depends on runtime support on the outside. However, there is some experimental work towards allowing creation of standalone wasm modules, see [this wiki page](https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone). The `loadWebAssemblyModule` in `src/runtime.js` the emscripten branch mentioned there shows how to load such a standalone wasm.

**Comment by ninja-hub** [comment]
Thank you for clarification. I was new to emscripten and did not know much.
I checked "new WebAssembly.Instance(new WebAssembly.Module(getBinary()), info)" and it works in the doNativeWasm method. 
I thought I had to load 'wasm' file explicitly myself. I guess it did not work because i tried to load it without all the import and link stuff.


Cheers,

N
