### ISSUE TITLE
carriage return in generated code

### ISSUE THREAD

**Issue by stephassoria** [kripken/emscripten#4806]
I build two projects using emscripten (1.36.14-64bit) on Windows in Visual Studio Community 2015. I think I have the same build parameters for both of them (-O3 for build & link ...), but one js file is generated with carriage returns and spaces and starts like this : 

```
var Module;
if (typeof Module === "undefined") Module = {};
if (!Module.expectedDataFileDownloads) {
 Module.expectedDataFileDownloads = 0;
 Module.finishedDataFileDownloads = 0;
}
Module.expectedDataFileDownloads++;

```
the other is generated without carriage returns and spaces and is more compact . It starts like this :

`
var Module;if(typeof Module==="undefined")Module={};if(!Module.expectedDataFileDownloads){Module.expectedDataFileDownloads=0;Module.finishedDataFileDownloads=0}Module.expectedDataFileDownloads++;`

Of course, the file with carriage returns is bigger than the other (5.0Mb vs 3.5Mb) even if the source code is mainly the same and should generate an equivalent file size.

Any idea of what I am missing here ?

thanks.

Stéphane

**Comment by juj** [comment]
The first thing that comes to mind is the presence of `-g2` or similar that avoids minification.

Btw you can also try `--output-eol linux` on Windows to output even smaller code, since that'll do `\n` line endings instead of `\r\n`.

**Comment by stephassoria** [comment]
Thank you for your answer.

I looked directly in the vcxproj (As it's a quite old project it was probably upgraded from vs 2010), and found in the link section different options that was not visible in the Visual Studio ide project properties like this one :

`  <GenerateDebugInformation>true</GenerateDebugInformation>`

So I tweak the file by hand, and now the generated js is less than 3.2Mb, that's fine !

thank you,

     Stéphane Capo
