### ISSUE TITLE
How disable source maps from library

### ISSUE THREAD

**Issue by eduardodoria** [kripken/emscripten#4809]
I'm trying to disable source maps generation only for the library.
For example:

`./emcc file1.cpp -o project.bc`

When I generate project.bc, it has full path of my cpp source code inside bitcode. It's not good to redistribuite. If I try to use this library in a different system with source map generation debbug it will not find the code location:

`./emcc -g4 file2.cpp project.bc -o project.js`

I don't know if is possible to disable generation of source map for project.bc (**file1.cpp**), because not everybody has this source file in filesystem. I would like to enable only for **file2.cpp**.

**Comment by kripken** [comment]
I believe on current incoming this has been fixed - we no longer emit debug info in that case. But on master (1.36.0) we do still have this issue.

You can manually remove debug info using llvm's `opt` tool (in the same dir as clang etc.), with `opt input.bc -strip-debug -o output.bc`.

**Comment by eduardodoria** [comment]
Thanks! This is not the best solution but "opt" tool works for me.

**Comment by kripken** [comment]
Ok, good. And on master, we should merge incoming later this week, so using `opt` should not be needed any more.
