### ISSUE TITLE
webidl_binder.py crash

### ISSUE THREAD

**Issue by redcat1** [kripken/emscripten#4814]
Hello,

when I'am trying to bind my .h file which contains a simple code like that

`namespace A
{
int f1();
int f2();
}`

using WebIDL: **python /opt/emsdk/emscripten/master/tools/webidl_binder.py mytypes.idl glue** - I'am getting a script crash:

_Traceback (most recent call last):
  File "/opt/emsdk/emscripten/master/tools/webidl_binder.py", line 46, in <module>
    ''' + open(input_file).read())
  File "/opt/emsdk/emscripten/master/third_party/WebIDL.py", line 4961, in parse
    self._productions.extend(self.parser.parse(lexer=self.lexer,tracking=True))
  File "/opt/emsdk/emscripten/master/third_party/ply/ply/yacc.py", line 263, in parse
    return self.parseopt(input,lexer,debug,tracking,tokenfunc)
  File "/opt/emsdk/emscripten/master/third_party/ply/ply/yacc.py", line 792, in parseopt
    tok = self.errorfunc(errtoken)
  File "/opt/emsdk/emscripten/master/third_party/WebIDL.py", line 4911, in p_error
    raise WebIDLError("invalid syntax", [Location(self.lexer, p.lineno, p.lexpos, self._filename)])
WebIDL.WebIDLError: error: invalid syntax, <unknown> line 25:10
namespace A_

My .idl file code is
`namespace A
{
int f1();
int f2();
};`

**Comment by kripken** [comment]
It's possible A is a reserved word in the webidl parser we use, just a guess (maybe since `<a>` elements exist in HTML?), but easy to check if you alter A to something more unique.

**Comment by redcat1** [comment]
I've tryed different names. The error still the same.

**Comment by redcat1** [comment]
I checked **WebIDL.py** file and I didn't find keyword "namespace" in class **Tokenizer** in dictionary of keywords . Is this normal?

**Comment by kripken** [comment]
Oh, right, I didn't notice that was the file you sent to the idl binder. The idl binder's input should be an idl file, not a C or C++ .h file. So it doesn't have "namespace" for example. See `tests/webidl/*` for a complete working example (`test.idl` is what is passed to the webidl binder), and the code to run it is in `test_webidl` in `tests/test_core.py`.

**Comment by redcat1** [comment]
Oh, thanks for tip! But I still don't understand Is there any way to bind ordinary non class function using WebIDL?

**Comment by kripken** [comment]
Anything not tested in that test is likely not supported. I think global functions are in that category. Would be nice if someone added it. Meanwhile, you might turn such global functions into static methods in a shim class (see example of static methods in that test).
