### ISSUE TITLE
GL_DEPTH_STENCIL_ATTACHMENT not in GLES2/gl2.h

### ISSUE THREAD

**Issue by derofim** [kripken/emscripten#4832]
Im porting https://learnopengl.com/#!Advanced-OpenGL/Framebuffers tutorials to emscripten (sucessfully ported to "Framebuffers" for now).

Issue:
Add please 
`#define GL_DEPTH_STENCIL_ATTACHMENT       0x821A`
to GLES2/gl2.h (or something like this)

Reason:
Code like
`glFramebufferRenderbuffer(GL_FRAMEBUFFER, 0x821A, GL_RENDERBUFFER, rbo);`
works fine.

khronos webgl ( https://www.khronos.org/registry/webgl/specs/1.0/#6 ) says to use renderbufferStorage + DEPTH_STENCIL and framebufferRenderbuffer + DEPTH_STENCIL_ATTACHMENT. So correct DEPTH_STENCIL_ATTACHMENT for me was 0x821A.

UPD from http://stackoverflow.com/a/28997686 :
Packed depth/stencil surfaces are not a standard part of OpenGL ES 2.0, but are added via this extension:
https://www.khronos.org/registry/gles/extensions/OES/OES_packed_depth_stencil.txt

**Comment by juj** [comment]
Searching through the codebase after just merging #4831, the constant can be found in the following header files:

    /Users/clb/emsdk/emscripten/incoming/system/include/GL/glext.h:
      997: #define GL_DEPTH_STENCIL_ATTACHMENT       0x821A

    /Users/clb/emsdk/emscripten/incoming/system/include/GLES3/gl3.h:
      833: #define GL_DEPTH_STENCIL_ATTACHMENT       0x821A

    /Users/clb/emsdk/emscripten/incoming/system/include/GLES3/gl31.h:
      833: #define GL_DEPTH_STENCIL_ATTACHMENT       0x821A

    /Users/clb/emsdk/emscripten/incoming/system/include/GLES3/gl32.h:
      833: #define GL_DEPTH_STENCIL_ATTACHMENT       0x821A

    /Users/clb/emsdk/emscripten/incoming/system/include/SDL/SDL_opengl.h:
      701: /* reuse GL_DEPTH_STENCIL_ATTACHMENT */
      ...
     1644: #define GL_DEPTH_STENCIL_ATTACHMENT       0x821A

However for GLES2 core that define does not exist, so it's not present in any of the GLES2 headers. Adding that for a WebGL1 core header would be part of the work in #4502. For now, recommend adding the following snippet to your code (which you probably already did)

    #ifndef GL_DEPTH_STENCIL_ATTACHMENT
    #define GL_DEPTH_STENCIL_ATTACHMENT       0x821A
    #endif

**Comment by juj** [comment]
I'll close this for now, let's see if we some point have a WebGL-specific header file (PR #4502 added a bit of that). Adding WebGL-specific stuff to core GL headers would be a no-no from Khronos's intended implementor's guide perspective for those headers.
