### ISSUE TITLE
Mmap'ed addresses are not consistent with getpagesize

### ISSUE THREAD

**Issue by atrosinenko** [kripken/emscripten#4835]
Currently, `mmap` from Emscripten relies on `malloc` for anonymous mappings. This leads to the fact that the returned address is not page-aligned according to the return value of `getpagesize()`. I am not absolutely sure that this alignment is specified by POSIX, but it seems quite natural and QEMU, for example, [relies](https://github.com/qemu/qemu/blob/v2.4.1/util/oslib-posix.c#L128) on it. This caused hard to debug heap corruption caused by overwriting header of subsequent memory block.

## How to reproduce

Compile the following code:

```c
#include <stdio.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stdlib.h>

int main()
{
  void *ptr_mmap = mmap(NULL, 16536, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
  void *ptr_aligned;
  posix_memalign(&ptr_aligned, 4096, 16536);
  printf("getpagesize(): 0x%x\n", getpagesize());
  printf("mmap(...): %p\n", ptr_mmap);
  printf("posix_memalign(...): %p\n", ptr_aligned);
  return 0;
}
```

On Linux on amd64 it shows something like 

    getpagesize(): 0x1000
    mmap(...): 0x7fb97e04b000
    posix_memalign(...): 0x1314000

When compiled with Emscripten the output is like this:

    getpagesize(): 0x1000
    mmap(...): 0x501210
    posix_memalign(...): 0x506000

Note that on Linux the return value of `mmap` is multiple of `getpagesize` and on Emscripten it is not.

`emcc -v` output:

    emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.1
    clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 7372fbdc769db28fd534454268f4b008e629464f) (https://github.com/kripken/emscripten-fastcomp/ 942a10fbb02f54866c3fc11d6fad119cc38f1e8f) (emscripten 1.37.1 : 1.37.1)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /home/trosinenko/soft/emsdk_portable/clang/fastcomp/build_incoming_64/bin
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
    Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
    Candidate multilib: .;@m64
    Candidate multilib: 32;@m32
    Candidate multilib: x32;@mx32
    Selected multilib: .;@m64
    INFO:root:(Emscripten: Running sanity checks)

## Possible fixes

* Use `posix_memalign` instead of `malloc` (possibility of `free`-ing that memory should be checked)
* Make `getpagesize` return 8 instead of 4096 (this is honest but may surprise some programs)
* Align pointer manually in `mmap` (does not require exporting new functions but wastes up to 2x memory while `posix_memalign` *may or may not* be handled specially by allocator)

**Comment by kripken** [comment]
Thanks, I agree that this is worth changing. Switching to `posix_memalign` and using the page size seems like the best course to me (it's handled by dlmalloc, so freeing will work properly etc.).

**Comment by atrosinenko** [comment]
Thank you, I will try to implement it that way slightly later. It should be quite trivial.

**Comment by atrosinenko** [comment]
Fixed
