### ISSUE TITLE
GLFW3 doesn't convert minus or equals on MacOS Chrome

### ISSUE THREAD

**Issue by bradgrantham** [kripken/emscripten#4843]
In library_glfw.js, the DOM key codes 0xAD and 0x61 are converted to GLFW MINUS and EQUALS keycodes respectively.  In Chrome on my Macbook Pro, the minus/hypen key emits 0xBD and equals emits 0xBB.

http://www.javascripter.net/faq/keycodes.htm asserts that 0xBD(189) and 0xBB(187) are emitted also in IE, Opera, and Safari but I haven't verified.

https://github.com/bradgrantham/emscripten/commit/3704472dc643955d89f23e0eec405b21c2bfae14 implements this change.  What's the best way to proceed?  Should I submit a pull request next?

Thank you!

**Comment by kripken** [comment]
Thanks, yes, a pull request is a good next step.

We will need to verify on other browsers before merging (once the PR is up it should be easy to do so).

**Comment by bradgrantham** [comment]
Thank you!  Will do.

**Comment by kripken** [comment]
Fixed by that PR.
