### ISSUE TITLE
emscripten_bind c++&javascript symbol doesn't match

### ISSUE THREAD

**Issue by JerryYangJin** [kripken/emscripten#4847]
Hello, I'm using emscripten for a large c++ project

`emcc -v`

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.0
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 271ce598c3d1fe74efadc254f5be1b57edea9f41) (https://github.com/kripken/emscripten-fastcomp/ 61acfb230665464544f2e8db292f8999fc3c628c) (emscripten 1.36.0 : 1.36.0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jerry/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.3
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.3
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

I found that when the project is very large, the emscripten_bind symbol doesn't match anymore between c++ and js.

When I only build part of the project, 

c++glue code
```cpp
void EMSCRIPTEN_KEEPALIVE emscripten_bind_className_functionName()
```
js glue code

```js
  className.prototype['functionName'] = className.prototype.functionName= function() {
    var self = this.ptr;
    _emscripten_bind_className_functionName(self);
  };
```

this works when project is small.

when I build the whole project, which is quite large, there's error while loading the js file:

```
Uncaught ReferenceError: _emscripten_bind_className_functionName is not defined
```

I checked the generated js source file, the symble `_emscripten_bind_className_functionName` changed to `__Z48emscripten_bind_className_functionName`

Is this because the project is too large? is there anyway to prevent emscripten adding `_Z48` stuff?

Update to this ticket:
I tried `-s DEMANGLE_SUPPORT=1` option, the result is the same, `_Z` stuff still there, js and c++ symbol still not matching

Thanks!

**Comment by kripken** [comment]
Is this using embind? Or the webidl binder? Or is the name `emscripten_bind` something you use yourself?

**Comment by JerryYangJin** [comment]
@kripken , for smaller project I used webidl, and I follow the same pattern in glue code generated for the big project, which is difficult using webidl

**Comment by kripken** [comment]
To be sure I understand: in the problem described above, you are *not* using webidl, but just using similar names and conventions? You're doing it all yourself manually?

**Comment by JerryYangJin** [comment]
@kripken , yes

**Comment by kripken** [comment]
Ok, now I understand the background.

No idea what could cause that. Perhaps it's a JS engine bug - did you try more than one? Otherwise, I'd try to reduce it til you find a small change that causes the breakage, maybe decreasing the size of the big project til it works, etc.

**Comment by JerryYangJin** [comment]
@kripken , i found the issue, all cpp glue must be inside extern "C"
