### ISSUE TITLE
ogre3d-emscripten demo

### ISSUE THREAD

**Issue by kkimdev** [kripken/emscripten#485]
ogre3d is the most popular open source 3d rendering library for games. http://www.ogre3d.org/ 

and there have been a number of web porting attempts:
https://chrome.google.com/webstore/detail/ocpoapiejnpokdojkgjhglijajghikla
http://www.ogre3d.org/forums/viewtopic.php?f=10&t=64598
http://www.ogre3d.org/addonforums/viewtopic.php?f=3&t=14068
http://www.ogre3d.org/forums/viewtopic.php?f=1&t=62535

I think ogre3d-emscripten demo will be not only practical, but also a perfect example to demonstrate the capacity of emscripten's power since it is a very demanding real-time application.

**Comment by juj** [comment]
Since Ogre3D 1.10 release, Ogre3D now officially supports Emscripten, see http://www.ogre3d.org/2015/01/04/review-of-2014-outlook-into-2015 . So closing this as done.
