### ISSUE TITLE
Using preamble.js functions when compiling to WebAssembly

### ISSUE THREAD

**Issue by giann** [kripken/emscripten#4869]
I'm trying to compile an existing emscripten compiled project to WebAssembly.
I managed to compile it and the .wasm is generated.
But I have module additions which uses emscripten's preamble.js functions like cwrap.

How can i make preamble.js available ?

**Comment by kripken** [comment]
There should be no difference between asm.js and wasm. the main js file will load one or the other, but there should be no observable difference. what specific problem are you hitting?

**Comment by giann** [comment]
There wasn't I found my mistake thank you :)
