### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'/usr/bin/src/js/wasm.js-post.js'

### ISSUE THREAD

**Issue by Franke123** [kripken/emscripten#4878]
Getting this error on Arch Linux when trying to compile a hello world C file.

```
[franklin@fhardingxps ~]$ uname -a
Linux fhardingxps 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

[franklin@fhardingxps ~]$ emcc hello.c -s WASM=1 -o hello.html
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 2309, in <module>
    run()
  File "/usr/lib/emscripten/emcc.py", line 1683, in run
    wasm_js_glue = open(os.path.join(shared.Settings.BINARYEN_ROOT, 'src', 'js', 'wasm.js-post.js')).read()
IOError: [Errno 2] No such file or directory: u'/usr/bin/src/js/wasm.js-post.js'
```

File:
```
#include <stdio.h>

int main(int argc, char** argv) {
	printf("Hello, World!");
}
```

**Comment by kripken** [comment]
Is `BINARYEN_ROOT` set in your `~/.emscripten` file? If it points to the wrong place that could cause this.

If not, what version of emscripten is this? If latest incoming, is there not a file `~/.emscripten_ports/binaryen/binaryen-version_24/src/js/wasm.js-post.js`? (in older versions the number there might differ)

**Comment by Franke123** [comment]
From my ~/.emscripten: `BINARYEN_ROOT = os.path.expanduser(os.getenv('BINARYEN') or '/usr/bin') # directory`
emcc (Emscripten gcc/clang-like replacement) 1.37.1 ()

I don't have a ~/.emscripten_ports folder... just emscripten, emscripten_cache/, emscripten_cache.lock and emscripten_sanity.

**Comment by kripken** [comment]
I see, thanks. Ok, this looks like a rather serious bug that I'm surprised didn't get fixed by now - it appears to be from 0c77c773. But only in non-SDK usage. PR to fix it is in #4879.

To fix things for yourself, just replace '/usr/bin` with the empty string in your `~/.emscripten` (so BINARYEN_ROOT is the empty string, then it will use the port).

**Comment by Franke123** [comment]
I still get ```Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 2309, in <module>
    run()
  File "/usr/lib/emscripten/emcc.py", line 1683, in run
    wasm_js_glue = open(os.path.join(shared.Settings.BINARYEN_ROOT, 'src', 'js', 'wasm.js-post.js')).read()
IOError: [Errno 2] No such file or directory: u'/usr/bin/src/js/wasm.js-post.js'```

after changing BINARYEN_ROOT = ''

**Comment by kripken** [comment]
What is the full line with `BINARYEN_ROOT` now in your `~/.emscripten`? It should be `BINARYEN_ROOT = os.path.expanduser(os.getenv('BINARYEN') or '')`

**Comment by Franke123** [comment]
Oh shoot I'm an idiot, I need to run as root or I get permission denied, and I haven't modifed the .emscripten for root, I don't have one in /root/ where would that be for root? Thanks for the help a lot.

**Comment by kripken** [comment]
In general I don't think you need to run emscripten as root. It's ok to install it as root systemwide, but running it as a regular user should be fine. But I don't know arch linux or the details or your install, so I could be wrong... I use ubuntu which handles root pretty differently than most distros I think.

If in root, the config file should be in `/home/root/.emscripten`, I would guess.

Or maybe it's worth reinstalling it, not as root?

**Comment by Franke123** [comment]
I reinstalled, even as root or just my normal user I get:
```
[root@fhardingxps ~]# sudo emcc hello.c -s WASM=1 -o hello.html
INFO:root:generating port: binaryen_tag_version_21.txt... (this will be cached in "/root/.emscripten_cache/asmjs/binaryen_tag_version_21.txt" for subsequent builds)
INFO:root:building port: binaryen
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 2309, in <module>
    run()
  File "/usr/lib/emscripten/emcc.py", line 1411, in run
    compile_source_file(i, input_file)
  File "/usr/lib/emscripten/emcc.py", line 1400, in compile_source_file
    args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
  File "/usr/lib/emscripten/emcc.py", line 1383, in get_bitcode_args
    args = system_libs.process_args(args, shared.Settings)
  File "/usr/lib/emscripten/tools/system_libs.py", line 637, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "/usr/lib/emscripten/tools/ports/binaryen.py", line 34, in process_args
    get(ports, settings, shared)
  File "/usr/lib/emscripten/tools/ports/binaryen.py", line 29, in get
    return [shared.Cache.get('binaryen_tag_' + TAG, create, what='port', extension='.txt')]
  File "/usr/lib/emscripten/tools/cache.py", line 95, in get
    temp = creator()
  File "/usr/lib/emscripten/tools/ports/binaryen.py", line 24, in create
    ports.build_native(os.path.join(ports.get_dir(), 'binaryen', 'binaryen-' + TAG))
  File "/usr/lib/emscripten/tools/system_libs.py", line 596, in build_native
    subprocess.check_call(['cmake', '-DCMAKE_BUILD_TYPE=' + cmake_build_type, '.'])
  File "/usr/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

And I did remember to modify the line again @kripken. I will try compiling from source and all that jazz when I get home instead of the official arch repos.

**Comment by kripken** [comment]
If a reinstall doesn't fix it, try to run with `EMCC_DEBUG=1` in the environment, it will print out more info that might help figure things out.

**Comment by juj** [comment]
Definitely recommend against running any Emscripten or Emsdk install or build steps as root, we don't really integrate that way to Linux system directories in any manner. Although not sure what the permission denied there is about. See the [WebAssembly getting started guide](http://webassembly.org/getting-started/developers-guide/) for a quick cmdline that should work for getting Wasm builds going.

**Comment by Franke123** [comment]
@juj I did follow that guide, I had to install as root I mean with pacman, but everything should have installed right. It seems to be working now on my PC anyways (not the laptop though which was having the problems before).

**Comment by MichaReiser** [comment]
I'm also facing this issue. I have build emscripten, binaryen and llvm (together with clang) manually. The paths are set up accordingly. But the file post-wasm.js does no longer exist as mentioned in WebAssembly/binaryen#907

But I have no clue where I can find this file in the emscripten repository (where it should be now?)

**Comment by kripken** [comment]
That linked issue looks irrelevant, perhaps a typo in the number?

The contents of that `wasm.js-post.js` file have moved from binaryen to emscripten. If it's still looking for it, it means your emscripten and binaryen are too old. Make sure you use latest emscripten incoming, and that BINARYEN_ROOT is not overridden in ~/.emscripten.

**Comment by MichaReiser** [comment]
This pull request is linked as the mentioned file has been removed in one of its commits. 

This means it is not supported to override binaryen root at all? I linked my emscripten to my local copy from the master branch of binaryen.

**Comment by kripken** [comment]
Sorry, I wasn't clear. It is supported to override BINARYEN_ROOT, I just meant it was safer not to (as emscripten will just use a correct tag from it). But if you use latest emscripten incoming, then it should work with latest  binaryen master (as you mention in the update, looks like this can be closed).
