### ISSUE TITLE
can't compile to different folder with -o

### ISSUE THREAD

**Issue by ad8e** [kripken/emscripten#4890]
a.cpp:
```
int main() {}
```
```
emcc a.cpp -o folder/index.html
```
Notice that I'm putting the output index.html in a different folder.
```
Traceback (most recent call last):
  File "/home/jon/Documents/emsdk_portable/emscripten/master/emcc", line 13, in <module>
    emcc.run()
  File "/home/jon/Documents/emsdk_portable/emscripten/master/emcc.py", line 2034, in run
    shutil.move(final, js_target)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'folder/index.js'
```

If I manually create a file at "folder/index.js" before compiling, then it works. The file contents don't make a difference.
Same behavior on 1.35 Windows and 1.37.0 Linux.

If splitting out a .mem file, then the .mem file has the same issue, it must exist before the compiler can write it.

**Comment by kripken** [comment]
If `folder/` exists, then `emcc tests/hello_world.c -o folder/index.html` works for me.

Given what you describe, I think it might be a permissions issue. Somehow the permissions are different if the file already exists. Check `ls -al` on the folder and on its contents, maybe that will show something.

**Comment by ad8e** [comment]
You're right, if `folder/` exists, then compilation proceeds without error. I guess I just expected the folder to be created as well.
