### ISSUE TITLE
Bug in page:Emscripten Toolchain Requirements 

### ISSUE THREAD

**Issue by ad8e** [kripken/emscripten#4891]
Page claims that 

> Visual Studio 2010 is required! Visual Studio 2012 and Visual Studio 2013 do not correctly compile Fastcomp. This issue will be fixed (eventually) when Fastcomp is migrated to use a LLVM 3.4 or later.

as well as other mentions of Visual Studio 2010. But looking at the projects, it seems like later versions of Visual Studio are required now.

URL: ../../docs/building_from_source/toolchain_what_is_needed
URL: ../../docs/building_from_source/building_emscripten_from_source_on_windows

**Comment by kripken** [comment]
I don't know what the right fix is here, cc @juj.

**Comment by dschuff** [comment]
LLVM currently refuses to build with any toolchain earlier than VS 2015 and will warn you if you use any compiler older than visual studio 2015 update 3 (due to miscompiles from earlier versions).

**Comment by ad8e** [comment]
There are more VS 2010 references elsewhere (grep for 2010). Since the docs aren't maintained, I think the right fix is to move all references to VS into a single document that's easier to maintain. Otherwise the docs will go stale after every release of Visual Studio. More bits:
URL: ../../docs/getting_started/downloads
../../docs/getting_started/getting_started_with_emscripten_and_vs2010.html
../../docs/building_from_source/manually_integrating_emscripten_with_vs2010.html

**Comment by ad8e** [comment]
Closed by 2f05798
