### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by Volkhyn** [kripken/emscripten#4903]
Hello,
I cannot build my project because of missing slashes in the path of the object files to link. I have the version 1.37.1 of emsdk installed, clang 3.9.0 and python 2.7.13 and I do not have this issue with emsdk 1.35.0.
Here is the log : 

`WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpd9ig8i\truncate.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpsfgslz\tcgetpgrp.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpcyv8fe\tcsetpgrp.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmp9jy2ji\ttyname.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpl_0cnu\ttyname_r.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmp3rtope\ualarm.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpwuzrix\unlink.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpkj4ain\unlinkat.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpjf5fzw\writev.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpvu1rjx\write.c_0.o
WARNING:root:target c:/users/cpignol/appdata/local/temp\tmpqvew_z\_exit.c_0.o
WARNING:root:using response file for llvm-link
WARNING:root:emcc: llvm-linking: 
['c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\strlwr.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\strtol_l.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\strupr.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\__synccall.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\cabs.c.o', 
...
'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\unlink.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\unlinkat.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\write.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\writev.c.o', 'c:\\users\\cpignol\\appdata\\local\\temp\\tmpbdtygz\\_exit.c.o'] to c:/users/cpignol/appdata/local/temp\tmpbdtygz\libc.bc

C:/ShiVa_Technologies/ShiVa_Editor/Tools/Windows/emsdk/clang/tag-e1.37.1/build_tag-e1.37.1_vs2013_64/RelWithDebInfo/bin\llvm-link: c:userscpignolappdatalocaltemptmpbdtygzstrlwr.c.o: error: Could not open input file: no such file or directory
C:/ShiVa_Technologies/ShiVa_Editor/Tools/Windows/emsdk/clang/tag-e1.37.1/build_tag-e1.37.1_vs2013_64/RelWithDebInfo/bin\llvm-link: error loading file 'c:userscpignolappdatalocaltemptmpbdtygzstrlwr.c.o'

Traceback (most recent call last):
  File "C:\ShiVa_Technologies\ShiVa_Editor\Tools\Windows\emsdk\emscripten\1.35.0\\emcc", line 1222, in <module>
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout, stderr, forced=forced_stdlibs)
  File "C:\ShiVa_Technologies\ShiVa_Editor\Tools\Windows\emsdk\emscripten\1.35.0\tools\system_libs.py", line 339, in calculate
    libfile = shared.Cache.get(
name, do_create, extension=suffix)
  File "C:\ShiVa_Technologies\ShiVa_Editor\Tools\Windows\emsdk\emscripten\1.35.0\tools\cache.py", line 41, in get
    temp = creator()
  File "C:\ShiVa_Technologies\ShiVa_Editor\Tools\Windows\emsdk\emscripten\1.35.0\tools\system_libs.py", line 337, in do_create
    ret = create(name)
  File "C:\ShiVa_Technologies\ShiVa_Editor\Tools\Windows\emsdk\emscripten\1.35.0\tools\system_libs.py", line 119, in create_libc
    return build_libc(libname, libc_files, args)
  File "C:\ShiVa_Technologies\ShiVa_Editor\Tools\Windows\emsdk\emscripten\1.35.0\tools\system_libs.py", line 66, in build_libc
    shared.Building.link(o_s, in_temp(lib_filename))
  File "C:\ShiVa_Technologies\ShiVa_Editor\Tools\Windows\emsdk\emscripten\1.35.0\tools\shared.py", line 1431, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error: 

Could not build application
Authoring failed.`

**Comment by kripken** [comment]
Strange, does not look like a known issue.

2 possible things to do here: create a testcase for us so we can reproduce the problem and debug it, or you can bisect it (since it works on an older version, if you find which version it stopped working, that may point to the problem).

**Comment by Volkhyn** [comment]
I found where the issue was coming from ; in fact the issue was already patched in the latest release by removing the escping \\ by / before passing the arguments to llvm-link in shared.py but I wasn't targeting the righ version
