### ISSUE TITLE
ABORTING_MALLOC=0 works with asm.js but not with wasm

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4919]
Running the following test code `howmuchmemory.cpp`:

	#include <stdlib.h>
	#include <stdio.h>

	#define ALLOC_SIZE (16*1024*1024)

	int main()
	{
		int allocatedMemory = 0;
		for(;;)
		{
			printf("%d MB allocated so far, allocating %d MB more.\n", allocatedMemory, ALLOC_SIZE);
			char *mem = (char*)malloc(ALLOC_SIZE);
			if (!mem)
			{
				printf("Could not allocate memory. Total available memory: %d MB.\n", allocatedMemory);
				break;
			}
			for(int i = 0; i < ALLOC_SIZE; i += 1024*1024) mem[i] = (char)i;

			// Touch memory so compiler doesn't optimize out.
			char checksum = 0;
			for(int i = 0; i < ALLOC_SIZE; i += 1024*1024) checksum += mem[i];
			if (checksum != 0) printf("Checksum: %d\n", checksum);

			allocatedMemory += ALLOC_SIZE / (1024*1024);
		}
	}

with asm.js: `em++ howmuchmemory.cpp -o a.html -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -g2 -s ABORTING_MALLOC=0 -s SAFE_HEAP=1` gives

> Failed to grow the heap from 1807745024 bytes to 1892679680 bytes, not enough memory!
> Could not allocate memory. Total available memory: 1712 MB.

Building the same code with wasm: `em++ howmuchmemory.cpp -o a.html -s BINARYEN=1 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -g2 -s ABORTING_MALLOC=0` gives

	1280 MB allocated so far, allocating 16777216 MB more.
	 Module.reallocBuffer: Attempted to grow from 1556086784 bytes to 1556086784 bytes, but got error: RangeError: failed to grow memory
	 Failed to grow the heap from 1358954496 bytes to 1556086784 bytes, not enough memory!
	 exception thrown: RuntimeError: index out of bounds,_malloc@file:///C:/code/emsdk/emscripten/incoming/a.js:33727:1
	_main@file:///C:/code/emsdk/emscripten/incoming/a.js:1495:1
	callMain@file:///C:/code/emsdk/emscripten/incoming/a.js:2429:15
	doRun@file:///C:/code/emsdk/emscripten/incoming/a.js:2489:42
	run/<@file:///C:/code/emsdk/emscripten/incoming/a.js:2500:7
	RuntimeError: index out of bounds

I'm not quite sure why that is happening. (This is btw after applying https://github.com/kripken/emscripten/pull/4918, but I think that should all be safe changes) I expect that both should reach the final `printf` of when memory allocation fails, or if our `malloc` has trouble being graceful, then it should also show up in `-s SAFE_HEAP=1` build in asm.js side. @kripken: how does this look to you?

**Comment by kripken** [comment]
I don't get `index out of bounds`, it appears to behave properly for me. The only difference between us is that I am using plain incoming. Perhaps #4918 makes this break?

**Comment by juj** [comment]
I think #5289 is what ultimately fixed this, though it is possible that my test case was somehow off, had so many things in flight at the time of filing that not sure if the test case was accurate based on your comment above. Retested this today, and it works well, so closing as fixed.
