### ISSUE TITLE
What can cause the size of the .js.mem file increase ?

### ISSUE THREAD

**Issue by xiyanggudao** [kripken/emscripten#4933]
I am working on a project transplant, from desktop (C++) to web(Javascript). I find the .js.mem file became larger and larger. I want to improve this, but I don't know the detail in .js.mem file. what can cause the size of the .js.mem file increase in c++ code, the number of class/function , the static/global variables , or too much templates ?

**Comment by kripken** [comment]
The main thing would be static/global variables.

The `.mem` file contains data, not code, so adding more functions or templates usually doesn't increase it, only instances of them would. (However, a small increase could occur due to more vtables for new classes/template classes for example.)

**Comment by juj** [comment]
Hey, do we have a tool in wasm to somehow dump symbols and the sizes they contribute to the memory init file?

The bug report #2527 is very similar. Alon, I wonder if there's a good tool for this now in wasm on code functions as well?

**Comment by kripken** [comment]
We lose that information before we generate the mem init file or the memory section in the wasm. We would need to add code to dump that in fastcomp.

For function code, there isn't a good tool I am aware of right now, but it could be added in binaryen perhaps.

**Comment by xiyanggudao** [comment]
I checked the revisions carefully , and I find that .mem file size became larger when I change the implementation of a large matrix from std::vector to static array. Now I know the reason of large .mem file, thank you @kripken
