### ISSUE TITLE
Reusing Python multiprocessing.Pool() gets into trouble

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4941]
Seeing the issue that @kripken commented to earlier, with running

    python tests/runner.py binaryen0.test_multiply_defined_symbols binaryen0.test_freetype

failing with

    ======================================================================
    ERROR: test_multiply_defined_symbols (test_core.binaryen0)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/clb/emsdk/emscripten/incoming/tests/test_core.py", line 576, in test_multiply_defined_symbols
        Building.link([main_name + '.o', liba_name, libb_name], all_name)
      File "/home/clb/emsdk/emscripten/incoming/tools/shared.py", line 1651, in link
        Building.read_link_inputs(filter(lambda x: not x.startswith('-'), files))
      File "/home/clb/emsdk/emscripten/incoming/tools/shared.py", line 1576, in read_link_inputs
        object_names_in_archives = pool.map(extract_archive_contents, archive_names)
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
        return self.map_async(func, iterable, chunksize).get()
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
        raise self._value
    OSError: [Errno 2] No such file or directory

    ----------------------------------------------------------------------

It looks like python is not even passing the multiprocessing task to the workers in the pool on that invocation. That is, the function `extract_archive_contents` is not getting called by any of the children of the pool, and `archive_names` at the time of the call is `[/tmp/emscripten_test_binaryen0_2jId2N/liba.a, /tmp/emscripten_test_binaryen0_2jId2N/libb.a]`, and both of those files do exist on the filesystem and they look ok (though the code does not get that far to even attempt to open them).

Changing this line https://github.com/kripken/emscripten/blob/incoming/tools/shared.py#L1563 `pool = Building.get_multiprocessing_pool()` to use a fresh new multiprocessing pool instead of reusing the old one, i.e. `pool = multiprocessing.Pool(processes=multiprocessing.cpu_count())`, the issue is avoided. It seems that somehow the pool has gone to a bad state after it has been used in that test. The issue occurs when tested on Python 2.7.12 on Linux and on Python 2.7.10 on OS X, but the issue does not occur on Windows.

Not sure why exactly reusing the pool is not good here.

**Comment by kripken** [comment]
Here is where this was reported: https://github.com/kripken/emscripten/commit/8737d35b3c356a87741844f1d41e53450df22052#commitcomment-20771436

So this somehow is only a problem in the test suite, it seems. Perhaps we could disable the shared pool just there?

**Comment by kripken** [comment]
Note, a smaller testcase is `./tests/runner.py test_multiply_defined_symbols asm1.test_multiply_defined_symbols` (shows this has nothing to do with binaryen, and also avoids the slower freetype test). What is special in that test seems to be its use of `Building.emar` which uses the new pool in the test runner itself, as opposed to just inside emcc subprocesses.

**Comment by dschuff** [comment]
This seems to happen when `Building.link()` (which means reusing the pool in `read_link_inputs`) more than once in the same process, which happens in the test suite, but presumably not in emcc more generally. Presumably that's why doing a new pool there is a successful workaround. I wonder if this is specific to `read_link_inputs` or more general when there is a repeated use? What other repeated uses of the pool do we have?

**Comment by kripken** [comment]
This should be fixed now.
