### ISSUE TITLE
(Suggestion) Clarify how to use the preamble.js file

### ISSUE THREAD

**Issue by birgersp** [kripken/emscripten#4964]
I'm wondering how to actually use the preamble.js file. Maybe it is painfully obvious and I'm a complete moron for bringing it up, but it's not clear to me how to use it so I suggest it could be explained in on of the basic introductory tutorials on the emscripten website.

http://stackoverflow.com/questions/42376922/how-do-i-use-the-preamble-js-file-in-emscripten

**Comment by kripken** [comment]
It's actually automatically included for you. When we build the output JS, it contains the preamble, then the compiled code, then the postamble. I agree we should document this better, I'll add text to https://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html . Maybe there's other places too?

**Comment by birgersp** [comment]
In my personal opinion, having a sentence or two about it in the introductory text of the `preamble.js` API (your link) is probably enough.

**Comment by kripken** [comment]
Cool, thanks. Added a commit and updated the site. Looks good?

**Comment by birgersp** [comment]
It certainly does! Thanks a lot for your quick response, and all your effort on this great project!

**Comment by kripken** [comment]
No problem, and thanks for pointing this out, feels like it was a hole in our docs.
