### ISSUE TITLE
sysconf(_SC_PHYS_PAGES): totalMemory is not defined

### ISSUE THREAD

**Issue by artur-matuszewski** [kripken/emscripten#4973]
When using wasm, we get
```
Error: totalMemory is not defined
_sysconf@sample_wasm.js
```
Which is implemented in [library.js:292](https://github.com/kripken/emscripten/blob/db346f887642d6c06a93efe0e2ec6184ae44ad3d/src/library.js#L292) as follows, but `totalMemory`never defined
```
case {{{ cDefine('_SC_PHYS_PAGES') }}}: return totalMemory / PAGE_SIZE;
```

**Comment by juj** [comment]
Sorry about this, pushed a fix now to incoming, https://github.com/kripken/emscripten/commit/52ee9cddd636081482b1a88b7349c126919b088e

**Comment by artur-matuszewski** [comment]
Thanks for the quick fix!
