### ISSUE TITLE
Use of SDL_SetWindowSize() scales down image on high DPI displays

### ISSUE THREAD

**Issue by dreamlayers** [kripken/emscripten#4991]
Using SDL 2, if I create an window with a specific size, everything is fine. However, if I then call SDL_SetWindowSize() and set that same window to that same size, the drawable area is scaled down on high DPI displays. I'm testing in Firefox 51.0.1 (64-bit) in Ubuntu 16.10 with layout.css.devPixelsPerPx set to 1.5, though the problem is present in other browsers.

This problem is affecting Em-DOSBox built with Emscripten 1.36.14 a5db951 but not Emscripten 1.29.0 fdf24b4. Commenting out [this one line](https://github.com/dreamlayers/em-dosbox/blob/em-dosbox-svn-sdl2/src/gui/sdlmain.cpp#L636) prevents the problem but I don't think that line is wrong. I can also reproduce this in a small test:

SDL docs at https://wiki.libsdl.org/SDL_SetWindowSize and https://wiki.libsdl.org/SDL_CreateWindow say that window dimensions may not be pixels if window is created with SDL_WINDOW_ALLOW_HIGHDPI flag, but I'm not using that flag.

```C
#include <SDL.h>
#include <emscripten.h>

static void sdlError(const char *str) 
{
    fprintf(stderr, "Error at %s: %s\n", str, SDL_GetError());
    emscripten_force_exit(1);
}

void draw(SDL_Window *window, SDL_Surface *surface) {
    int x, y;

    if (SDL_MUSTLOCK(surface)) {
        if (SDL_LockSurface(surface) != 0) sdlError("SDL_LockSurface");
    }

    for (y = 0; y < 256; y++) {
        Uint32 *p = (Uint32 *)(((Uint8 *)surface->pixels) +
                               surface->pitch * y);
        for (x = 0; x < 256; x++) {
            *(p++) = SDL_MapRGB(surface->format, x, x ^ y, y);
        }
    }

    if (SDL_MUSTLOCK(surface)) SDL_UnlockSurface(surface);
    if (SDL_UpdateWindowSurface(window) != 0)
        sdlError("SDL_UpdateWindowSurface");
}

int main(void) {
    SDL_Window *window;
    SDL_Surface *surface;

    if (SDL_Init(SDL_INIT_VIDEO) != 0) sdlError("SDL_Init");

    window = SDL_CreateWindow(NULL,
                              0, 0,
                              256, 256,
                              SDL_WINDOW_SHOWN);
    /* This SDL_SetWindowSize() call should not cause any harm.
       However, in Firefox 51.0.1 (64-bit) with layout.css.devPixelsPerPx
       set to 1.5, it causes the drawing to be scaled down in the top left.
       Commenting out the call avoids the problem. */
    SDL_SetWindowSize(window, 256, 256);
    if (window == NULL) sdlError("SDL_CreateWindow");
    surface = SDL_GetWindowSurface(window);
    if (surface == NULL) sdlError("SDL_GetWindowSurface");

    draw(window, surface);

    return 0;
}
```

**Comment by dreamlayers** [comment]
This is already fixed in SDL 2 master: https://github.com/emscripten-ports/SDL2/commit/f9e76e476d9e9ff97f6efa2b3518b23aff005a04

**Comment by kripken** [comment]
I'm fairly sure we updated our sdl2 port since that commit, but it's just on incoming, so `1.37.2` or `.3` or so.

**Comment by dreamlayers** [comment]
Yeah, I confirmed this works with latest incoming 1.37.3 04255b4 and the SDL it automatically uses with ` -s USE_SDL=2`. Thanks!
