### ISSUE TITLE
scrolling causes returning of wrong movementX/movementY values in emscripten_set_mousemove_callback

### ISSUE THREAD

**Issue by hpohl** [kripken/emscripten#4996]
"wheel" events contain wrong `screenX/screenY` coordinates when pointer lock is active. They still set `JSEvents.previousScreenX`, though: https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L256.

If a "mousemove" event is triggered after a "wheel" event and `movementX` or `movementY` is 0, it is set to `e.screenX-JSEvents.previousScreenX` or `e.screenY-JSEvents.previousScreenY` respectively which will contain garbage values: https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L237-L238.

**Comment by lomateron** [comment]
has this been fixed?
I have been waiting for this fix for a long time

**Comment by kripken** [comment]
The PR for this just landed.
