### ISSUE TITLE
Better docs for EMTERPRETIFY_FILE

### ISSUE THREAD

**Issue by curiousdannii** [kripken/emscripten#5000]
The docs don't mention that the user is responsible for loading the EMTERPRETIFY_FILE if it is set. (settings.js does mention this, but the main docs don't tell you to check settings.js. for more details, as the docs often do for other settings.) An explanation of how to do that would be great.

Without loading the file it is hanging (100% CPU). It should probably throw if it doesn't have the data. Although when I've tried manually loading the data it still hangs, so maybe that's a separate problem?

Ideally could it load it automatically like it does for the memory file?

**Comment by kripken** [comment]
Agreed, improving the docs here is a good idea. Sounds like we just need to point to settings.js? PR would be welcome.

The hang sounds unrelated - please try to reduce to a small testcase, it could be a bug.

**Comment by curiousdannii** [comment]
I think this was sufficiently handled by #5354.
