### ISSUE TITLE
emscripten ASSERTIONS=1 generates linker error Referencing global in another module!"

### ISSUE THREAD

**Issue by dsiroky** [kripken/emscripten#5008]
When I set "-s ASSERTIONS=1" then linker will fail with lots of "Referencing global in another module!" messages, e.g.:

> Referencing global in another module! [16 x i8]* @_ZZN8nlohmann10basic_jsonINSt3__23mapENS1_6vectorENS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbxydS7_NS_14adl_serializerEE13escape_stringERKS9_E6hexify ; ModuleID = 'src/ui_lib/logic/libcommands.bc' [16 x i8]* @_ZZN8nlohmann10basic_jsonINSt3__23mapENS1_6vectorENS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbxydS7_NS_14adl_serializerEE13escape_stringERKS9_E6hexify ; ModuleID = 'src/ui_lib/curves.bc' Referencing global in another module! %"struct.ui::EmscriptenBindingInitializer_uicurves"* @_ZN5boost6detail15optional_detail13none_instanceINS_6none_tEE8instanceE ; ModuleID = 'src/ui_lib/logic/libcommands.bc' %"struct.ui::EmscriptenBindingInitializer_uicurves"* @_ZN5boost6detail15optional_detail13none_instanceINS_6none_tEE8instanceE ; ModuleID = 'src/ui_lib/curves.bc'

It happens when I use instances of nlohmann::json (https://github.com/nlohmann/json) in multiple translation units.

Is that an emscripten bug or a feature?

**Comment by kripken** [comment]
Strange, odd that ASSERTIONS would affect linking. Can you provide a small testcase showing this?

**Comment by dsiroky** [comment]
Here it is:
[ref.zip](https://github.com/kripken/emscripten/files/833720/ref_in_global.zip)
It prints:

> Referencing global in another module!
> %"struct.nlohmann::detail::to_json_fn"* @_ZN8nlohmann6detail12static_constINS0_10to_json_fnEE5valueE
> ; ModuleID = '/tmp/b/logic/libcommands.bc'
> %"struct.nlohmann::detail::to_json_fn"* @_ZN8nlohmann6detail12static_constINS0_10to_json_fnEE5valueE
> ; ModuleID = '/tmp/b/main.bc'
> All DICompileUnits must be listed in llvm.dbg.cu
> /mujbin/b/emscripten/clang/fastcomp/build_master_64/bin/opt: /tmp/b/logic/libcommands.bc: error: input module is broken!

When I remove "-g" from compilation flags then it can be linked with ASSERTIONS=1.

**Comment by kripken** [comment]
I unzipped that file, then ran `./build.sh`, and it completed without any error? That's on current incoming.

**Comment by dsiroky** [comment]
On my second computer the package does not yield an error as well. Please try this one: 
[bug_assertions_link.zip](https://github.com/kripken/emscripten/files/835846/bug_assertions_link.zip)

**Comment by kripken** [comment]
Thanks, now I see it. Fix is in #5021. Turns out with ASSERTIONS we verify the module in llvm, and it has some weird things with debug info there, which it works around in llvm-link, and we adding linking to opt so we need to do that there too.

**Comment by dsiroky** [comment]
Well done, it works. Thank you! You can close the issue.

**Comment by kripken** [comment]
Fixed by that PR.
