### ISSUE TITLE
emsdk 1.37.3 ASSERTIONS=1/2 corrupted heap memory area

### ISSUE THREAD

**Issue by hcomere** [kripken/emscripten#5013]
Hello,

I was using emsdk 1.35.0 and all was fine.
Now i have compiled emsdk 1.37.3 and with "-s ASSERTIONS=1" or "-s ASSERTIONS=2" option my application crashes at start with : 

```
Uncaught Runtime error: The application has corrupted its heap memory area (address zero)!
```

Is there any difference between 1.35.0 and 1.37.3 that can make revealing and issue on my side or could it be a 1.37.3 bug ?

Compiling with "-g4" does not give more informations, i do not know how to debug this.

Regards, 
Harold

**Comment by juj** [comment]
I believe we added that error check between those two versions, so I think the root cause has always been there, but only the updated version started uncovering that. Try rerunning with the linker flag `-s SAFE_HEAP=1` set, perhaps that is able to catch it. Presumably the application code might have a write to memory area around a null pointer.

**Comment by kripken** [comment]
SAFE_HEAP should definitely be able to catch that - if it doesn't yet, we probably just need to add that same corruption check on each store.

**Comment by hcomere** [comment]
Ok, thanks for the hint, with SAFE_HEAP=1 i have a call stack : 

```
index.html:25 run() called, but dependencies remain, so not running
index.html:36 Downloading data... (636/636)
index.html:36 Running...
index.html:25 read file: /dev/stdin
index.html:25 pre-main prep time: 27 ms
index.html:20 segmentation fault
index.html:25 segmentation fault
VM36:29 Uncaught abort("segmentation fault") at Error
    at jsStackTrace (<anonymous>:5:27281)
    at stackTrace (<anonymous>:5:27452)
    at abort (<anonymous>:29:32718)
    at segfault (<anonymous>:5:15285)
    at xj (<anonymous>:13:304)
    at Array.zo (<anonymous>:21:2984)
    at Object.gT [as dynCall_vii] (<anonymous>:9:56798)
    at invoke_vii (<anonymous>:5:421833)
    at no (<anonymous>:22:62293)
    at Object.Client.asm._main (<anonymous>:29:338)
callMain @ VM36:29
doRun @ VM36:29
(anonymous) @ VM36:29
```
It reveals the segmentation fault but i still cant find from where it comes :-/
Why does it happen only with ASSERTIONS=1 or 2 and not with ASSERTIONS=0 ?

**Comment by juj** [comment]
Oh, try also pairing that with `-g4` or with `--profiling-funcs`.

**Comment by hcomere** [comment]
Thanks, --profiling-funcs gave me the hint i needed :)
Uninitialized std::unique_ptr on my side .... now i wonder how it was working with that ... 

Regards,
Harold
