### ISSUE TITLE
Emscripten minifies asm.js code before calling asm2wasm, crashing cashew in assert(isNode);

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#5014]
STR:

	> echo "int main(){}" > a.cpp
	> em++ a.cpp -Os -s OUTLINING_LIMIT=40000 -s BINARYEN=1 -s ALLOW_MEMORY_GROWTH=1 -o a.js
    asm2wasm: binaryen/master/src/emscripten-optimizer/parser.h:320: NodeRef cashew::Parser<NodeRef, Builder>::ExpressionElement::getNode() [with NodeRef = cashew::Ref; Builder = cashew::DotZeroValueBuilder]: Assertion `isNode' failed.
	Traceback (most recent call last):
	  File "em++", line 16, in <module>
	    emcc.run()
	  File emcc.py", line 2154, in run
	    subprocess.check_call(cmd)
	  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
	    raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command '[u'asm2wasm', 'a.asm.js', '--total-memory=16777216', '-Os', '--mem-init=a.js.mem', '--mem-base=1024', '-o', 'a.wasm']' returned non-zero exit status -6

**Comment by juj** [comment]
Building with `EMCC_DEBUG=1` gives

	DEBUG:root:PYTHON not defined in /home/clb/.emscripten, using "/usr/bin/python"
	DEBUG:root:JAVA not defined in /home/clb/.emscripten, using "java"
	DEBUG:root:Cache: PID 34094 acquiring multiprocess file lock to Emscripten cache
	DEBUG:root:Cache: done
	DEBUG:root:Cache: PID 34094 released multiprocess file lock to Emscripten cache
	DEBUG:root:check tells us to use asm.js backend
	WARNING:root:invocation: /home/clb/emsdk/emscripten/incoming/em++ a.cpp -Os -s OUTLINING_LIMIT=40000 -s BINARYEN=1 -s ALLOW_MEMORY_GROWTH=1 -o a.js --emscripten-cxx  (in /home/clb/emsdk/emscripten/incoming)
	DEBUG:root:Checking JS engine ['/home/clb/emsdk/node/4.1.1_64bit/bin/node']
	INFO:root:(Emscripten: Running sanity checks)
	DEBUG:root:compiling to bitcode
	DEBUG:root:emcc step "parse arguments and setup" took 0.01 seconds
	DEBUG:root:compiling source file: a.cpp
	DEBUG:root:binaryen root already set to /home/clb/emsdk/binaryen/master_64bit_binaryen
	DEBUG:root:running: /home/clb/emsdk/clang/fastcomp/build_incoming_64/bin/clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=37 -D__EMSCRIPTEN_tiny__=3 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/include/libcxx -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/lib/libcxxabi/include -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/include/compat -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/include -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/include/SSE -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/include/libc -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/local/include -Os -std=c++03 -mllvm -disable-llvm-optzns a.cpp -fno-inline-functions -Xclang -isystem/home/clb/emsdk/emscripten/incoming/system/include/SDL -emit-llvm -c -o /dev/shm/tmp/tmpdhSyY6/a_0.o
	DEBUG:root:emcc step "bitcodeize inputs" took 0.02 seconds
	DEBUG:root:optimizing a.cpp
	DEBUG:root:emcc: LLVM opts: -Os -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 1]
	DEBUG:root:emcc step "process inputs" took 0.01 seconds
	DEBUG:root:will generate JavaScript
	DEBUG:root:binaryen root already set to /home/clb/emsdk/binaryen/master_64bit_binaryen
	DEBUG:root:including libc.bc
	DEBUG:root:Cache: PID 34094 acquiring multiprocess file lock to Emscripten cache
	DEBUG:root:Cache: done
	DEBUG:root:Cache: PID 34094 released multiprocess file lock to Emscripten cache
	DEBUG:root:including dlmalloc.bc
	DEBUG:root:Cache: PID 34094 acquiring multiprocess file lock to Emscripten cache
	DEBUG:root:Cache: done
	DEBUG:root:Cache: PID 34094 released multiprocess file lock to Emscripten cache
	DEBUG:root:including wasm-libc.bc
	DEBUG:root:Cache: PID 34094 acquiring multiprocess file lock to Emscripten cache
	DEBUG:root:Cache: done
	DEBUG:root:Cache: PID 34094 released multiprocess file lock to Emscripten cache
	DEBUG:root:emcc step "calculate system libraries" took 0.11 seconds
	DEBUG:root:linking: ['/dev/shm/tmp/tmpdhSyY6/a_0_1.o', '/home/clb/.emscripten_cache/asmjs/libc.bc', '/home/clb/.emscripten_cache/asmjs/dlmalloc.bc', '/home/clb/.emscripten_cache/asmjs/wasm-libc.bc']
	DEBUG:root:emcc step "link" took 0.02 seconds
	DEBUG:root:saving intermediate processing steps to /dev/shm/tmp/emscripten_temp
	DEBUG:root:(not saving intermediate /dev/shm/tmp/emscripten_temp/emcc-0-basebc.bc because deferring linking)
	DEBUG:root:emcc: LLVM opts: -strip-debug -disable-verify -internalize -internalize-public-api-list=main,malloc,free,__errno_location,fflush -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 4]
	DEBUG:root:emcc step "post-link" took 0.13 seconds
	DEBUG:root:LLVM => JS
	DEBUG:root:emscript: llvm backend: /home/clb/emsdk/clang/fastcomp/build_incoming_64/bin/llc /dev/shm/tmp/tmpdhSyY6/a.bc -march=js -filetype=asm -o /dev/shm/tmp/emscripten_temp/tmp3dadjb.4.js -emscripten-precise-f32 -emscripten-global-base=1024 -emscripten-stack-size=5242880 -O2 -emscripten-wasm
	DEBUG:root:  emscript: llvm backend took 0.0355279445648 seconds
	DEBUG:root:emscript: js compiler glue
	DEBUG:root:very limited syscalls (140, 6, 54, 146) so disabling full filesystem support
	DEBUG:root:  emscript: glue took 0.338130950928 seconds
	DEBUG:root:emscript: python processing: function tables and exports
	DEBUG:root:asm text sizes[[102556, 5377], 651, 173, 1355, 0, 402, 381, 718, 294, 714, 2451]
	DEBUG:root:  emscript: python processing: function tables and exports took 0.00253009796143 seconds
	DEBUG:root:emscript: python processing: finalize
	DEBUG:root:  emscript: python processing: finalize took 0.00101900100708 seconds
	DEBUG:root:emcc step "emscript (llvm => executable code)" took 0.39 seconds
	DEBUG:root:emcc step "source transforms" took 0.00 seconds
	DEBUG:root:wrote memory initialization to a.js.mem
	DEBUG:root:emcc step "memory initializer" took 0.00 seconds
	DEBUG:root:running js post-opts
	DEBUG:root:applying js optimization passes: asmPreciseF32 asm eliminateMemSafe simplifyExpressions optimizeFrounds emitJSON
	chunkification: num funcs: 32 actual num chunks: 1 chunk size range: 109172 - 109172
	DEBUG:root:config forcing native optimizer at /home/clb/emsdk/emscripten/incoming_64bit_optimizer/optimizer
	DEBUG:root:js optimizer using native
	DEBUG:root:config forcing native optimizer at /home/clb/emsdk/emscripten/incoming_64bit_optimizer/optimizer
	.
	DEBUG:root:applying js optimization passes: asmPreciseF32 asm receiveJSON outline emitJSON
	chunkification: num funcs: 3 actual num chunks: 1 chunk size range: 236131 - 236131
	.
	DEBUG:root:applying js optimization passes: asmPreciseF32 asm receiveJSON registerizeHarder minifyNames asmLastOpts last minifyWhitespace cleanup
	chunkification: num funcs: 3 actual num chunks: 1 chunk size range: 207668 - 207668
	DEBUG:root:config forcing native optimizer at /home/clb/emsdk/emscripten/incoming_64bit_optimizer/optimizer
	DEBUG:root:js optimizer using native
	DEBUG:root:config forcing native optimizer at /home/clb/emsdk/emscripten/incoming_64bit_optimizer/optimizer
	.
	running cleanup on shell code
	DEBUG:root:emcc step "js opts" took 0.95 seconds
	DEBUG:root:separating asm
	DEBUG:root:PYTHON not defined in /home/clb/.emscripten, using "/usr/bin/python"
	DEBUG:root:JAVA not defined in /home/clb/.emscripten, using "java"
	DEBUG:root:Cache: PID 34299 acquiring multiprocess file lock to Emscripten cache
	DEBUG:root:Cache: done
	DEBUG:root:Cache: PID 34299 released multiprocess file lock to Emscripten cache
	DEBUG:root:check tells us to use asm.js backend
	DEBUG:root:using binaryen, with method: native-wasm
	DEBUG:root:asm2wasm (asm.js => WebAssembly): /home/clb/emsdk/binaryen/master_64bit_binaryen/bin/asm2wasm a.asm.js --total-memory=16777216 -Os --mem-init=a.js.mem --mem-base=1024 -o a.wasm
	asm2wasm: /home/clb/emsdk/binaryen/master/src/emscripten-optimizer/parser.h:320: NodeRef cashew::Parser<NodeRef, Builder>::ExpressionElement::getNode() [with NodeRef = cashew::Ref; Builder = cashew::DotZeroValueBuilder]: Assertion `isNode' failed.
	Traceback (most recent call last):
	  File "/home/clb/emsdk/emscripten/incoming/em++", line 16, in <module>
	    emcc.run()
	  File "/home/clb/emsdk/emscripten/incoming/emcc.py", line 2154, in run
	    subprocess.check_call(cmd)
	  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
	    raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command '[u'/home/clb/emsdk/binaryen/master_64bit_binaryen/bin/asm2wasm', 'a.asm.js', '--total-memory=16777216', '-Os', '--mem-init=a.js.mem', '--mem-base=1024', '-o', 'a.wasm']' returned non-zero exit status -6

**Comment by juj** [comment]
Building with optimization flags `-O2`, `-O3`, `-Os` or `-Oz` hits the issue. Building with `-O1` doesn't, and also it looks like the `OUTLINING_LIMIT` and `ALLOW_MEMORY_GROWTH` directives are needed for the issue to trigger.

**Comment by kripken** [comment]
Thanks, yeah, sounds like something in the special handling of those two flags mixes us up here, I'll investigate. Outlining makes sense due to how it's special-cased for JS, but weird that memory growth is involved.

**Comment by juj** [comment]
Btw, do we know if  `OUTLINING_LIMIT` makes any sense with WebAssembly? The root issue with asm.js was that compiling the page took superlinear time in the number of local vars used in a function for register allocation to those vars. Is that still the case for Wasm or does it have something fundamentally better?

**Comment by kripken** [comment]
Well, on the one hand wasm will parse super-fast, so it does avoid some of those issues. But on the other, things like register allocation, gvn, etc., will be the same, and we did see superlinear time in those. But they have also improved a lot in recent years too. Overall, we'll just need to measure. Hopefully we'll not need outlining for wasm, but too soon to tell.

**Comment by kripken** [comment]
Fix is in #5015.

**Comment by juj** [comment]
This was resolved in the above, re-verified today.
