### ISSUE TITLE
epoll support

### ISSUE THREAD

**Issue by dk14** [kripken/emscripten#5033]
I'm currently trying to port Weston (with gl-renderer) to emscripten. The Wayland server requires epoll_create, epoll_ctl, epoll_create1, epoll_wait from clang's Epoll api. The question is do I have to reimplement those with web-sockets friendly code (like socket accept API)? or is it possible to do syscall somehow in Emscripten 1.37.3 (which can translate to websockets automatically)?

Another unrelated question is Wayland's libinput...Do I have to reimplement udev/mtdev libraries or is it possible to use them directly?

Update: 

Looks like an answer to my first question is "no" because epoll is not supported at all: https://github.com/kripken/emscripten/blob/master/src/library_syscall.js
Maybe I could emulate it somehow...Got it: https://github.com/fd00/cygepoll/blob/master/epoll.c. Basically it compiles with emcc, so you could add this hack if it really works.

It seems like there is ioctl syscall support, so maybe udev/mtdev will work somehow...

**Comment by dk14** [comment]
Thanks for reply!
My point was that you don't support linux's epoll api:
 http://man7.org/linux/man-pages/man7/epoll.7.html
https://stuff.mit.edu/afs/sipb/project/merakidev/include/sys/epoll.h

However, sygepoll (Cygwin hack, that is build over regular sockets) did the job. 
Is it okay if I add that hack as a pull request?

-----------------
I'm aware about Websockets support, basically my idea is to have window compositor webpage available for both Emscripten and regular remote applications (as well as javascipt vms) through some websocket relay. 

The point is to add simple abstraction over input/framebuffer. Potentially but much much harder, we could compile some X-Server (like XWayland) in order to provide no-vnc alternative with faster graphics. Basically I chose Wayland coz it's much simpler than Xorg.

------------------

libinput is Wayland's library that is using udev, mtdev (multitouch), xkb libraries to communicate with input devices. 

https://github.com/wayland-project/libinput
http://manpages.ubuntu.com/manpages/trusty/man7/udev.7.html

Udev is seem to basically rely on ioctl. Does emscripten provide some low-level /dev/input/* emulation or it's just high-level SDL/Xlib/Qt/HTML5.h?

Another thought I had is to try QtWayland, it seems simpler than weston and relies on high-level input abstractions. What would you suggest?

**Comment by kripken** [comment]
About sygepoll, that might be good but I know little about it. If it's a standard API others might find useful too, and is just a js library addition, then why not.

About /dev/input, I'm not familiar with that either :) I guess it's lower-level than SDL etc.? Anyhow, in the end all the input comes from browser events, which we just wrap for SDL, glfw, etc. Probably possible to add support for another low-level looking API, but it does need to be async.

**Comment by dk14** [comment]
1) I never actually used epoll, I encountered it in Wayland's code. Yes it's standard API (Linux 2.5+), it's implemented in Python for instance:
https://docs.python.org/2/library/select.html

2) as I understand '/dev/input' is file-based + some ioctl (I need more research too :) ), so it should be async in the meaning that you can request-reply through let's say websocket or even cookies (any non-blocking shared state).

**Comment by kripken** [comment]
Ok, cool, both sound possible to implement then.
