### ISSUE TITLE
continuations idea for blocking c-code

### ISSUE THREAD

**Issue by dk14** [kripken/emscripten#5040]
It comes from Scala/Python/Haskell.
Basically Scala is using `Future` concept for async interactions. Also, asynchronous scala-code can be compiled into javascript through ScalaJs. The only thing that can't is `Await.result(future)` which blocks current thread waiting for `Future`s result.

But(!) scala has [scala-async](https://github.com/scala/async) macros that translates sequential blocking code into asynchronous one and it seems to compile with scala-js as well. 

It's even possible to emulate shared state(!) in that way - you can emulate it with Streams ([Monix](https://monix.io/)), which are js-compatible. Pseudo code for actor:

```
actor{
   var state = "";
   def receive(msg) = msg match { //this function is executed sequentially in separate thread
      case GetState => sender ! state; //sending state back to sender
      case SetState(newstate) => state = newstate 
   }
}

//client code

await(actor ? SetState("hello")) //`?` sends SetState message and returns future of response
val newstate: String = await(actor ? GetState)

//Which automatically translates into:

val newstate: Future[String] = (actor ? SetState("hello")) flatMap { _ => // `map`/`flatMap` just registering an asynchronous handler, it also allows to return result wrapped in `Future`
    (actor ? GetState) map { state =>
        state //return state
    }
}

//Which can be easily translated to javascript using scala-js
```

Actor can easily be emulated as a monix-stream of its states. If you interested I could put more light on this concept.

The question is, is it possible to more or less easily implement something like this for LLVM? Or maybe get some experimental generator of scala-js+scala-async code from LLVM (preserving all emscrippten APIs)?

**Comment by kripken** [comment]
We have some similar things, [the emterpreter has async mode](https://github.com/kripken/emscripten/wiki/Emterpreter#emterpreter-async-run-synchronous-code) where it can pause and resume the call stack. We could use that to implement C coroutines, but it hasn't been done yet (it has been in an earlier [async approach](http://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_coroutine), but not ported to emterpreter yet).

**Comment by dk14** [comment]
Oh! That's cool - I completely missed emterpreter, thanks. I think it's possible to implement await with polling on some shared state, but implementing shared state effectively (avoiding obvious hacks like cookies, files) seems to require complete callcc implementation.
