### ISSUE TITLE
Warning about new symbol after incoming update (musl changes)

### ISSUE THREAD

**Issue by aidanhs** [kripken/emscripten#5045]
Trying to build a library after updating to latest incoming and configure on this library (glib, fyi) is now failing.

Investigation shows that it's because I've removed `res_query.c` from https://github.com/kripken/emscripten/blob/a5db951/tools/system_libs.py#L101 (my usage of the library doesn't touch `res_query`, I just want it to configure+link successfully) and there's a new warning when compiling the program configure uses to test:
```
#include <resolv.h>
int main() { res_query("test", 0, 0, (void *)0, 0); return 0; }
```
gives
```
warning: unresolved symbol: pthread_setcancelstate
```

And because we deny warnings during configure (iirc) it fails.

**Comment by kripken** [comment]
Why not return that file to `system_libs.py`? :)

Anyhow, this should not be new in 4.0, but rather is likely from the also recent change to musl - I guess it uses more pthreads calls - and the fix is likely to add that method to `src/library_pthread_stub.js`.

**Comment by jgravelle-google** [comment]
Interestingly when I try to compile just that test program I get `warning: unresolved symbol: res_query`...
Ok looking at that more closely it's because it's currently *blacklisted* in `system_libs.py`. Removing the blacklist and rebuilding libc I see the warning.

Fixed in https://github.com/kripken/emscripten/pull/5048

**Comment by aidanhs** [comment]
@kripken I'd love to put it back in the blacklist, but compiling glib was a monstrous effort and I'm not keen to revisit it to add yet more hacks on the pile I already have (in order to make it not check for res_query)!

**Comment by aidanhs** [comment]
Fix merged
