### ISSUE TITLE
getenv returns temporary strings?

### ISSUE THREAD

**Issue by mittorn** [kripken/emscripten#5053]
in preInit:
```
        ENV.LIBRARY_PREFIX='libs/';
        ENV.LIBRARY_SUFFIX='.js';

```
```
snprintf( path, MAX_SYSPATH, "%s%s%s", getenv( "LIBRARY_PREFIX" ), "menu", getenv( "LIBRARY_SUFFIX" ) );
```
this results in ".jsmenu.js" instead of "libs/menu.js"

**Comment by juj** [comment]
Verified this to occur. however, reading through the spec of `getenv` at http://man7.org/linux/man-pages/man3/getenv.3.html, it says

    The implementation of getenv() is not required to be reentrant.  The
    string pointed to by the return value of getenv() may be statically
    allocated, and can be modified by a subsequent call to getenv(),
    putenv(3), setenv(3), or unsetenv(3).

which means that the above code snippet is not guaranteed to work, so I'll close this issue.

Added the multithreading label initially, but removed that and marked that aspect as a separate item at #5054.
