### ISSUE TITLE
Fetch API Not Working

### ISSUE THREAD

**Issue by pbferre** [kripken/emscripten#5063]
I have installed Emscripten on Windows 10, using the 64 bit web installer. I am trying to run the first demo program on the Fetch API page, [https://kripken.github.io/emscripten-site/docs/api_reference/fetch.html](url). Originally, I got an error complaining that the fetch.h file did not exist. I installed and activated sdk-master-64bit. This time the file compiled, but when I tried to run it, it threw an exception over the emscripten_fetch_attr_init function.
```
c:\Users\Patrick Ferre\Documents\Emscripten Tests>node filetest.js
missing function: emscripten_fetch_attr_init
-1
-1

c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:97
      throw ex;
      ^
abort(-1) at Error
    at jsStackTrace (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:1173:13)
    at stackTrace (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:1190:22)
    at abort (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:13448:44)
    at _emscripten_fetch_attr_init (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:1668:71)
    at _main (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:5935:2)
    at Object.asm._main (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:13201:19)
    at Object.callMain (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:13313:30)
    at doRun (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:13371:60)
    at run (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:13385:5)
    at Object.<anonymous> (c:\Users\Patrick Ferre\Documents\Emscripten Tests\filetest.js:13474:1)
```
I attempted but failed to install sdk-incoming-64bit. I got this error during the compilation process.
```
unning CMake: ['cmake', '-G', 'Visual Studio 12 Win64', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Emscripten\\python\\2.7.5.3_64bit\\python.exe', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_TESTS=OFF', 'C:/Program Files/Emscripten/clang/fastcomp\\src']
-- Warning: Did not find file Compiler/MSVC-ASM
CMake Error at cmake/modules/CheckCompilerVersion.cmake:45 (message):
  Host Visual Studio must be at least 2015
Call Stack (most recent call first):
  cmake/config-ix.cmake:14 (include)
  CMakeLists.txt:583 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2013_64/CMakeFiles/CMakeOutput.log".
CMake invocation failed due to exception!
Working directory: C:/Program Files/Emscripten/clang/fastcomp\build_incoming_vs2013_64
Command '['cmake', '-G', 'Visual Studio 12 Win64', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Emscripten\\python\\2.7.5.3_64bit\\python.exe', '-DLLVM_TARGETS_TO_BUILD=X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_TESTS=OFF', 'C:/Program Files/Emscripten/clang/fastcomp\\src']' returned non-zero exit status 1
Installation failed!
```
Incidentally, I have VS 2015 Community Edition installed.

Any idea what I can do to get the Fetch API to work? Also, will this API work on code that is run in a browser, or just node js?

Patrick Ferre

**Comment by juj** [comment]
Did you build with the -s FETCH=1 linker flag? That is required to link in
the Fetch API.

For VS2015 build, try passing explicit --vs2015 flag to emsdk install.

I am not sure if Fetch API works at all in node.js actually, the current
development target has been to only support browsers.

2017-03-21 2:49 GMT+02:00 pbferre <notifications@github.com>:

**Comment by pbferre** [comment]
I got it working on the 1.35.6 tag, using the FETCH=1 option, like you said. However, it is exhibiting odd behavior. I am testing it, by attempting to download a file from a simple file server on my local machine. When I step through the server code, it is finding the file, and writing its contents to the output stream. But the download failed callback is being called, rather than the download succeeded, with a 404 error. Does the response have to be formatted as http? I am only transmitting the file contents. Here is my code:
```
#include <stdio.h>
#include <string.h>
#include <emscripten/fetch.h>

void downloadSucceeded(emscripten_fetch_t *fetch) {
  printf("Finished downloading %llu bytes from URL %s.\n", fetch->numBytes, fetch->url);
  
  // The data is now available at fetch->data[0] through fetch->data[fetch->numBytes-1];
  emscripten_fetch_close(fetch); // Free data associated with the fetch.
}

void downloadFailed(emscripten_fetch_t *fetch) {
  printf("Downloading %s failed, HTTP failure status code: %d.\n", fetch->url, fetch->status);
  emscripten_fetch_close(fetch); // Also free data on failure.
}

int main() {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);
  strcpy(attr.requestMethod, "GET");
  attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
  attr.onsuccess = downloadSucceeded;
  attr.onerror = downloadFailed;
  emscripten_fetch(&attr, "http://localhost:9999/update.sh");
}
```

**Comment by juj** [comment]
Try using the browser's Network devtools tab to debug the network transfer process. That should show the HTTP request and response communication, i.e. see the [docs here](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor).

**Comment by pbferre** [comment]
The request sows a status of 200, but the response field is blank. If I click 'Edit and Resend', I can see the response. The first request, the one that fails, has a cause of xhr, and a type of xml. The second, which succeeded, has a cause of other and a type of plain.

**Comment by juj** [comment]
Hmm, not sure. Does it work if you request data from other web servers?

**Comment by pbferre** [comment]
Seems to be a problem with my file server. It is a pretty bare bones thing, written in C# for a different project. I substituted the URL for the fetch.h file itself, [](url)https://raw.githubusercontent.com/juj/emscripten/emscripten_fetch/system/include/emscripten/fetch.h

and it worked. Downloaded the file and displayed it contents on the screen. Thanks.

**Comment by pbferre** [comment]
I spoke too soon. Sometimes the download works, and sometimes it doesn't. Here are two different URLs from Google images, for png files of Scarlett Johansson

[http://www.pngall.com/wp-content/uploads/2016/03/Scarlett-Johansson-Face-PNG.png](url)
[https://pbs.twimg.com/media/CAoh21KWEAARhYx.png](url)

Running the exact same code, the first URL fails with a 404 error, while the second one succeeds. Here is the code
```
#include <iostream>
#include <string.h>
#include <emscripten/fetch.h>
#include <emscripten/emscripten.h>

void downloadSucceeded(emscripten_fetch_t *fetch) {
  //printf("Finished downloading %llu bytes from URL %s.\n", fetch->numBytes, fetch->url);
  std::cout << "Finished downloading " << fetch->numBytes << " bytes from URL " << fetch->url << std::endl;
  
  // The data is now available at fetch->data[0] through fetch->data[fetch->numBytes-1];
  emscripten_fetch_close(fetch); // Free data associated with the fetch.
}

void downloadFailed(emscripten_fetch_t *fetch) {
  printf("Downloading %s failed, HTTP failure status code: %d.\n", fetch->url, fetch->status);
  emscripten_fetch_close(fetch); // Also free data on failure.
}

int main() {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);
  strcpy(attr.requestMethod, "GET");
  attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
  attr.onsuccess = downloadSucceeded;
  attr.onerror = downloadFailed;
  //emscripten_fetch(&attr, "http://localhost:9999/update.sh");
  //emscripten_fetch(&attr, "https://raw.githubusercontent.com/juj/emscripten/emscripten_fetch/system/include/emscripten/fetch.h");
  emscripten_fetch(&attr, "https://pbs.twimg.com/media/CAoh21KWEAARhYx.png");
}
```  
 Any clues?

**Comment by pbferre** [comment]
Sorry, for some reason the links don't want to insert correctly. Copy and paste them into a browser, you will see they work

**Comment by dreamlayers** [comment]
@pbferre you cannot simply download any URL from a web page in a browser. That would be a security hole. Take a look at: https://en.wikipedia.org/wiki/Same-origin_policy

https\://pbs.twimg.com/media/CAoh21KWEAARhYx.png works because the server sends a header telling the browser that any web page is allowed to download it: `access-control-allow-origin: *`. http\://www.pngall.com/wp-content/uploads/2016/03/Scarlett-Johansson-Face-PNG.png does not send such a header so it is not allowed.

Probably your browser informed you of this in the console.  Chrome would say something like `XMLHttpRequest cannot load http://localhost:8003/Gwbasic.exe. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8003' is therefore not allowed access.` The server did actually respond with status code 200 but the browser reported 404 to JavaScript. When something goes wrong, checking the console is a good idea, as it may have helpful messages.

**Comment by ArnaudBienner** [comment]
Hi,

I ran into the same issue (missing -s FETCH=1).
This flag isn't mentioned into the documentation I looked at (https://kripken.github.io/emscripten-site/docs/api_reference/fetch.html)
I think it could be good to mention it there, or any other way to activate this API.
What do you think?

**Comment by kripken** [comment]
Yeah, we should fix the docs if that's missing. A PR would be very welcome!

**Comment by ArnaudBienner** [comment]
@kripken sure, I will submit one!

**Comment by ArnaudBienner** [comment]
@kripken I've submitted PR #6319 
One test failed, but I'm not sure why, since my change is just related to the documentation.

**Comment by kripken** [comment]
Thanks for the PR!

Yeah, sometimes a browser test fails randomly, it's very hard to prevent that entirely.

**Comment by kripken** [comment]
Can we close this issue, or is there more aside from updating the docs?

**Comment by ArnaudBienner** [comment]
On my side it's OK, but I'm not sure if @pbferre managed to fix his issue.

**Comment by ArnaudBienner** [comment]
@kripken Actually I think this can be closed: the doc has been updated, and the remaining issue @pbferre had seemed to be related to a cross origin request.

**Comment by kripken** [comment]
Sounds good, closing.
