### ISSUE TITLE
Problems installing and activating SDKs

### ISSUE THREAD

**Issue by pbferre** [kripken/emscripten#5067]
I have Emscripten installed on a Win10 machine, using the web installer. I have tried to install and activate an alternate SDK, because the 1.35 one does not contain support for the Fetch API. I have tried installing both sdk-incoming-64bit, and sdk-tag-1.37.8-64bit. If is use the emsdk install command, without any flags, it complains that I need at least Visual Studio 2015 or later. I have VS 2015 Community Edition installed. If is use the --vs2015 flag, it appears to work. It spends over an hour downloading and building the components, and displays a message at the end that it is installed. When I try to activate it, however, it tells me it is not installed.
```
C:\Program Files\Emscripten>emsdk activate sdk-incoming-64bit
Writing .emscripten configuration file to user home directory C:\Users\Patrick Ferre/
The SDK/tool 'clang-incoming-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'emscripten-incoming-64bit' cannot be activated since it is not installed! Skipping this tool...
The SDK/tool 'sdk-incoming-64bit' cannot be activated since it is not installed! Skipping this tool...
``` 

I figure I am missing a step here, but cannot figure out what it is.

**Comment by juj** [comment]
The issue there is likely that both `install` and `activate` commands need to have the `--vs2015` flag. However we are deprecating the web installer in the next release, which is due out this week (packaging this as I write). In that release, support for VS 2013 is dropped, so the `--vs2015` flag will be always implied by default. If you want to jump to the latest immediately, you can try sourcing from the git repository:

    git clone https://github.com/juj/emsdk.git
    cd emsdk
    emsdk install --build=Release sdk-incoming-64bit binaryen-master-64bit
    emsdk activate --build=Release sdk-incoming-64bit binaryen-master-64bit

**Comment by pbferre** [comment]
Using the flag in the activate command did the trick. Thanks for your prompt response, and all the assists you have given in the last few days while I am trying to get up to speed with this.
