### ISSUE TITLE
Can't install sdk-tag-1.37.9-64bit version of emscripten using ./emsdk script on 64bit Linux

### ISSUE THREAD

**Issue by ziowk** [kripken/emscripten#5078]
I don't know if this is correct place to ask this, because ./emsdk script and emsdk_manifest.json files are not a part of this repository.

Anyway I'm trying to install newer versions of emscripten (1.37.9) with ./emsdk script on 64bit Linux. Neither installing "latest" nor "sdk-tag-1.37.9-64bit" seems to do the job.
```
$ ./emsdk update
...
Done. 96 tagged releases available, latest is 1.37.9.

$ ./emsdk install latest
Installing SDK 'sdk-master-64bit'..
...
Done installing SDK 'sdk-master-64bit'.

$ ./emsdk activate lastest
...

$ source ./emsdk_env.sh
...

$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.37.0 (commit 6dc4ac5f9e4d8484e273e4dcc554f809738cedd6) // master
...

$ ./emsdk install sdk-tag-1.37.9-64bit
Error: No tool or SDK found by name 'sdk-tag-1.37.9-64bit'.
```

I think that this is caused by accidentally using "unix" for "os" key instead of "linux" in emsdk_manifest.json:845. This results in all emscripten versions from git tags to be ignored on 64bit linux, because compatible_with_this_os() in load_sdk_manifest() only checks for "win", "linux" and "osx" strings (see ./emsdk script).

Changing the code to check also for "unix" or modifying emsdk_manifest.json to use "linux" lets me install sdk-tag-1.37.9-64bit.

I would submit a patch, but it seems that both emsdk script and emsdk_manifest.json are not a part of this repository.

**Comment by juj** [comment]
Thanks for reporting. I can see that in the current github trunk version of emsdk this works. If you are using the git version, try `git pull`ing to latest. The prepackaged version is now being worked to get updated really soon as well.

**Comment by ziowk** [comment]
Thanks @juj 

I'm using prepackaged version, but I've just checked and this is indeed fixed in the git version.

Also I couldn't find it earlier but now I see that https://github.com/juj/emsdk is the correct repository for this kind of issues.

Closing this issue.
