### ISSUE TITLE
cannot combine EXPORT_NAME and --preload-file/--embed-file

### ISSUE THREAD

**Issue by dsiroky** [kripken/emscripten#5089]
If --preload-file/--embed-file is used then EXPORT_NAME does not work because there is some prepended code that uses only the default "Module".
[emscdata.zip](https://github.com/kripken/emscripten/files/874919/emscdata.zip)

**Comment by Ni55aN** [comment]
There is the same problem with 1.37.22

**Comment by kripken** [comment]
I think we need to pass EXPORT_NAME from emcc to the file_packager, for this to work.

**Comment by nazar-pc** [comment]
Can someone test if it works as expected with #5751?
