### ISSUE TITLE
Failed SSE2 instruction: "_mm_set_epi64x"

### ISSUE THREAD

**Issue by kathawala** [kripken/emscripten#5103]
I have a simple C file which compiles fully using both `gcc` and `emcc` but produces two different results after compilation with each. The file makes use of one SSE2 instruction, namely `_mm_set_epi64x`. Here it is

```c
#include <stdio.h>
#include <stdint.h>
#include <emmintrin.h>

void print128_num(__m128i var) 
{
    int64_t *v64val = (int64_t*) &var;
    printf("%.16lld %.16lld\n", v64val[1], v64val[0]);
}

int main() {
  __m128i var;
  var = _mm_set_epi64x(-1588454185101182573, 437384867522774919);
  print128_num(var);
}
```
If this file is called `128test.c` then we can compile it with both `gcc` and `emcc` and get the following very different outputs:

```bash
$ emcc 128test.c -msse2 -O0
$ gcc 128test.c -msse2 -O0
$ ./a.out
-1588454185101182573 437384867522774919
$ node a.out.js
0000000000000000 -6120469326574942329
```

As far as I understand, this is not what should be happening, no?

According to [the documentation on porting SIMD code](https://kripken.github.io/emscripten-site/docs/porting/simd.html) this SSE2 instruction should work fine when compiled by emscripten, so what's up?

**Comment by kathawala** [comment]
After reviewing this bug with some others online, it was pointed out that there seems to be some alignment issue here. When converting the ints to hexadecimal, we can see that the `node a.out.js` output is actually the lower 32 bits of each of the outputs for the `./a.out` output. Here is what I mean, if we convert the ints to hexadecimal, we will get

```bash
$ ./a.out
E9F4AD55AB0FB993 611E7383AD38787
$ node a.out.js
0 AB0FB9933AD38787
```

**Comment by juj** [comment]
Thanks for the report, working on a fix now.

**Comment by juj** [comment]
Pushed a fix to incoming with a test case. Had to change the test case a little (print as 32-bit parts instead of 64-bit parts), because of a related incompatibility (#5164).
