### ISSUE TITLE
unresolved symbol pthread_self

### ISSUE THREAD

**Issue by ricochet** [kripken/emscripten#5136]
When building a library that relies on mutexes for thread-safety but never actually creates threads, I'm getting `unresolved symbol: pthread_self` at the latest incoming (no warnings with 1.37.0). 

I think it's related to https://github.com/kripken/emscripten/pull/4813/commits/52d80265bd2da59c0fe0b7bc9f0f45c1381c76d4. If I add back pthread_self to library_pthread_stub.js, I can build and run without issue. 

Emscripten related args: `-Oz -s "WASM=1" -s "BINARYEN_METHOD='native-wasm'" --emit-symbol-map -s "FULL_ES2=1" -s "OUTLINING_LIMIT=10000" -s "ALLOW_MEMORY_GROWTH=1" -s "NO_EXIT_RUNTIME=1"`

**Comment by jgravelle-google** [comment]
Weird that that's the unresolved symbol - on latest incoming, `pthread_self` is used by a good number of libc functions. What happens if you add `-s USE_PTHREADS=1` to your Emscripten args? That should include the pthread library that I'd expect you'd need for mutex support anyway.

**Comment by ricochet** [comment]
It looks like that setting is not compatible with WASM: `assert not shared.Settings.USE_PTHREADS, 'WebAssembly does not support pthreads'`. Because I'm intentionally running single threaded, using the pthread stubs has worked thus far. BTW I'm compiling ICU4c. 

I'm not sure why the symbols defined in emscripten_pthread.c are not pulled into my build.

**Comment by kripken** [comment]
I think when pthreads are not enabled, we use the code in `src/library_pthread_stub.js`. Looks like that doesn't implement `pthread_self`, so makes sense we'd warn about it, but the bigger question is what is using that method, as I think when pthreads are not enabled, it shouldn't appear at all. @ricochet, perhaps you can see in your project what's calling it?

**Comment by jgravelle-google** [comment]
In the musl update, lots of code was made thread-agnostic by always referencing thread-local storage on `pthread_self`, for example `CURRENT_LOCALE` (https://github.com/kripken/emscripten/pull/4813/files#diff-908ed196fdf0572125940ffd358103a0R33). So it should pretty much always appear. That it isn't is interesting.
We define `pthread_self` in `emscripten_pthread.c`, which testing locally gets included in libc builds.

Try deleting `~/.emscripten_cache/asmjs/libc.bc` and `~/.emscripten_cache/wasm/libc.bc`, and building again?

**Comment by ricochet** [comment]
Blergh it looks like this was user error. I've been updating with ./emsdk install sdk-incoming-64bit, and then activate. Maybe I missed activate this time? Looking at emsdk, it should clear emscripten caches on activate.

**Comment by Lachrista** [comment]
WebAssembly does not support pthread ?Is there any way to support the WebAssembly?

**Comment by eclecticdave** [comment]
Hi, @Lachrista - see https://github.com/kripken/emscripten/wiki/Pthreads-with-WebAssembly for the latest.
