### ISSUE TITLE
compile error in boost/libs/test/src/execution_monitor.cpp

### ISSUE THREAD

**Issue by kelleyma49** [kripken/emscripten#5146]
I get these compile errors when compiling `boost/test/impl/execution_monitor.cpp` against the incoming branch:

```
In file included from /mnt/e/tree/geoviz-refactor/external/boost/libs/test/src/execution_monitor.cpp:16:
../external/boost/include/boost/test/impl/execution_monitor.ipp:771:31: error: use of undeclared identifier 'SIGSTKSZ'
            sigstk.ss_size  = BOOST_TEST_ALT_STACK_SIZE;
                              ^
../external/boost/include/boost/test/impl/execution_monitor.ipp:171:39: note: expanded from macro 'BOOST_TEST_ALT_STACK_SIZE'
#    define BOOST_TEST_ALT_STACK_SIZE SIGSTKSZ
                                      ^
../external/boost/include/boost/test/impl/execution_monitor.ipp:798:23: error: use of undeclared identifier 'MINSIGSTKSZ'
    sigstk.ss_size  = MINSIGSTKSZ;
                      ^
../external/boost/include/boost/test/impl/execution_monitor.ipp:858:37: error: use of undeclared identifier 'SIGSTKSZ'
        m_alt_stack.reset( new char[BOOST_TEST_ALT_STACK_SIZE] );
                                    ^
../external/boost/include/boost/test/impl/execution_monitor.ipp:171:39: note: expanded from macro 'BOOST_TEST_ALT_STACK_SIZE'
#    define BOOST_TEST_ALT_STACK_SIZE SIGSTKSZ
                                      ^
```
I believe I've traced the issue is due to the update to [version 1.1.15 of musl](https://github.com/kripken/emscripten/pull/4813/files). `MINSIGSTKSZ` and `SIGSTKSZ` were moved from `include/signal.h` to `arch/**/bits/signal.h` (see  http://git.musl-libc.org/cgit/musl/patch/include/signal.h?id=d5a5045382315e36588ca225889baa36ed0ed38f), but [incoming/system/lib/libc/musl/arch/emscripten/bits/signal.h](https://github.com/kripken/emscripten/blob/incoming/system/lib/libc/musl/arch/emscripten/bits/signal.h) was not modified accordingly.

**Comment by jgravelle-google** [comment]
That was exactly the problem. Thank you for the very specific bug report!

**Comment by kelleyma49** [comment]
I updated to your change and it successfully compiles now.  Thanks for the fix!
