### ISSUE TITLE
Gamepads not detected on page refresh in Chrome

### ISSUE THREAD

**Issue by echeese** [kripken/emscripten#5169]
This seems like a problem with Chrome (tested with Chrome 58), but it causes issues with Emscripten apps using the controller APIs. It seems like a page refresh doesn't cause the `gamepadconnected` to fire off on restart or button press, meaning Emscripten thinks there are no controllers connected and won't poll them.

Potential fix: In the JS library, check the gamepad array for the highest non-empty index and assign it to `numGamepadsConnected`

The same code works in Firefox properly.

**Comment by echeese** [comment]
Here's my test file:

<details>
<summary>testcase.c</summary>

```C
#include <emscripten.h>
#include <emscripten/html5.h>
#include <stdio.h>

void count_controllers() {
	printf("There are %d controllers connected\n", emscripten_get_num_gamepads());
}

EM_BOOL gamepadConnected(int eventType, const EmscriptenGamepadEvent *gamepadEvent, void *userData) {
	printf("Gamepad connected!\n");
	count_controllers();
	return 1;
}

EM_BOOL gamepadDisconnected(int eventType, const EmscriptenGamepadEvent *gamepadEvent, void *userData) {
	printf("Gamepad disconnected!\n");
	count_controllers();
	return 1;
}

void do_nothing() {}

int main() {
	count_controllers();
	emscripten_set_gamepadconnected_callback(NULL, 0, gamepadConnected);
	emscripten_set_gamepaddisconnected_callback(NULL, 0, gamepadDisconnected);
	emscripten_set_main_loop(do_nothing, 0, 1);
}

```

</details>
Note that this will work the first time in Chrome, but after refreshing it will say there are zero controllers, and nothing else, even after pressing a button on the controller. It seems you can trick it into firing the event by switching tabs back and forth.

**Comment by juj** [comment]
This sounds like a browser bug, Emscripten does not store any state across page revisits on the above test case. Try out some test case outside Emscripten, e.g.
    - http://html5gamepad.com/
    - http://h4ck3r.net/gamepad.js/example/
does the issue reproduce there? If not, try grabbing the internals of the Gamepad API implementation from https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L1706, perhaps the way Emscripten accesses Gamepad is somehow special compared to the other JS based examples.

**Comment by echeese** [comment]
That first link works, in Chrome, if you refresh, the controller is still there, with the same state/timestamp as before the refresh. Firefox seems to reset the controller/state on each page load, as well as fire the events.

It looks like the event can't be relied on, at least in Chrome.

**Comment by echeese** [comment]
I added a pull request #5170 that solves the problem
