### ISSUE TITLE
Pre-js/post-js applied before MODULARIZE

### ISSUE THREAD

**Issue by brian-armstrong** [kripken/emscripten#5174]
Hi,

First, I am so thankful for emscripten. Really opens new possibilities in JS :)

I am trying to take my emscripten output and turn it into a UMD module. My plan to do this was to use MODULARIZE to get a exportable var, and then use pre-js/post-js to wrap this var into a UMD Module. To my surprise, the pre-js/post-js pass is applied before MODULARIZE, meaning my wrapper is actually bundled into what MODULARIZE turns into a var, creating something rather broken.

Is what I'm doing supposed to be feasible? I'm thinking now that it might actually just be easier to call `cat` to put the wrapper parts into a file outside of emscripten itself. However, if there's a better way to achieve what I want using just emcc, I would definitely prefer it. It's entirely possible there's some other way to achieve UMD that I haven't thought of.

Thanks!

**Comment by kripken** [comment]
I'm not familiar with UMD, but how pre-post stuff works is so the JS provided with them is optimized together with the compiler output. That helps achieve the best minification. So we first combine all the code include pre-post, optimize it all together, then finally if MODULARIZE is specified, we put all that in a function scope.

Yes, just doing concatenation yourself manually may be what you want here, if you want code outside of the module.

**Comment by brian-armstrong** [comment]
I'm not really familar with UMD either, to be honest 😉 As I understand it, it's the flavor of the month for wrapping a JS lib so that it can be consumed either as a global var or as a "require" in node.

I suspect there must be others wrapping emscriptened libs in either UMD or AMD. I was hoping there was sort of a best practice thing, but happy to just concatenate together if no :)

**Comment by brian-armstrong** [comment]
Closing since it sounds like what I want is outside the scope of emscripten

**Comment by curiousdannii** [comment]
I've just been putting my UMD-like wrapping within the pre and post files. This is non-ideal because it means that those files can't be linted. If you're doing that then there's no need for MODULARISE - all that MODULARIZE does is wrap it in a function (although now it also adds a .then() function), so if you're providing your own UMD then you don't need the option.
