### ISSUE TITLE
Cannot launch android chrome from emrun

### ISSUE THREAD

**Issue by fchiba** [kripken/emscripten#5180]
```
% emrun --android --browser=chrome test.html
Starting: Intent { act=android.intent.action.VIEW dat=http://x.x.x.x:6931/... cmp=com.android.chrome/.Main }
Error type 3
Error: Activity class {com.android.chrome/com.android.chrome.Main} does not exist.
```

This is caused by activity name change. Current name is ```com.google.android.apps.chrome.Main```.

Also, emrun assmues only chrome stable and beta, but Google releases all 4 channels (stable, beta, dev and canary) on android now.
cf. https://www.chromium.org/getting-involved/dev-channel

**Comment by fchiba** [comment]
https://github.com/kripken/emscripten/pull/5181

**Comment by juj** [comment]
Fixed in the above PR.
