### ISSUE TITLE
Change memory growth pattern for WebAssembly

### ISSUE THREAD

**Issue by palant** [kripken/emscripten#5183]
Currently, `enlargeMemory()` will always double the size of allocated memory. So if you need 17 MB of memory it will actually reserve 32 MB - you get 15 MB of unused memory space sitting around. In my understanding, the reasoning here is that copying array buffers around is expensive. Yet, with WebAssembly no data is being copied around any more - that's how I understood the specification, and that's what I see in the [SpiderMonkey source code](https://dxr.mozilla.org/mozilla-central/rev/5278e2a35fc8f2be390243db1e62858bf0982055/js/src/vm/ArrayBufferObject.cpp#557). Is it still necessary to reduce the number of memory growth operations then? From the look of it, growing the memory by the actual amount requested from `sbrk()` won't be much less efficient while avoiding to reserve too much memory.

**Comment by kripken** [comment]
Overall I agree, but I think the engine might still copy under the hood. If there is a max amount of memory, it might avoid that by reserving it all up front, but if the max is very large or there isn't a max, it might allocate less and reallocate. But I'm not sure.

**Comment by palant** [comment]
At least in SpiderMonkey I followed the code from https://dxr.mozilla.org/mozilla-central/rev/57b37213d81150642f5139764e7044b07b9dccc3/js/src/wasm/WasmJS.cpp#1351 to https://dxr.mozilla.org/mozilla-central/rev/5278e2a35fc8f2be390243db1e62858bf0982055/js/src/vm/ArrayBufferObject.cpp#557 and didn't notice any provisions to realloc.

**Comment by kripken** [comment]
Yeah, it's possible that's just for now though. I believe the max memory option is meant to allow optimizing stuff like this, but maybe browsers don't do anything useful with it yet.

**Comment by palant** [comment]
Sorry, never mind. I found the [logic you expected](https://dxr.mozilla.org/mozilla-central/rev/57b37213d81150642f5139764e7044b07b9dccc3/js/src/wasm/WasmJS.cpp#1465) - memory is only grown in place if a maximum size is set or in x64 builds (which is where `WASM_HUGE_MEMORY` is defined). Otherwise [ArrayBufferObject::wasmMovingGrowToSize](https://dxr.mozilla.org/mozilla-central/rev/a748acbebbde373a88868dc02910fb2bc5e6a023/js/src/vm/ArrayBufferObject.cpp#972) will be called which actually involves copying. I wonder whether it is possible to distinguish these two scenarios reliably so that the logic can be adjusted accordingly. I guess not, the spec didn't expose this info so one would have to rely on implementation details. :disappointed:

**Comment by palant** [comment]
And the V8 implementation [appears to copy memory around unconditionally](https://cs.chromium.org/chromium/src/v8/src/wasm/wasm-objects.cc?l=343&rcl=f166741253a5aae6ac69fcdc07147b21e4844113). Ok, this isn't going anywhere then, too bad...

**Comment by palant** [comment]
For reference, I filed https://github.com/WebAssembly/design/issues/1052.
