### ISSUE TITLE
Is it possible to add -u option to emcc?

### ISSUE THREAD

**Issue by tsatsulin** [kripken/emscripten#5198]
`clang` and `gcc` support an option to force link a symbol.

From [gcc guide](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#Link-Options):

> `-u symbol`
> Pretend the symbol symbol is undefined, to force linking of library modules to define it. You can use -u multiple times with different symbols to force loading of additional library modules.

From [clang guide](https://clang.llvm.org/docs/ClangCommandLineReference.html)

> `-u<arg>, --force-link <arg>, --force-link=<arg>`

Is it possible to add similar option to `emcc`?

**Comment by kripken** [comment]
Heh, first I've heard of this option. So many of them ;)

Yes, it should be fairly easy to add to emcc. Need to receive it in emcc.py, then pass it into tools/system_libs.py where the logic is for linking. Maybe add an extra `extra_undefs` param to `calculate()`.

**Comment by tsatsulin** [comment]
Hi, @kripken, 

Yeah,  I also discovered it recently when worked on a side project with plugin architecture ;)

Thank you for quick and prompt reply. I will check it and write back. Please, do not close this issue, I'm sure I will need to ask some additional questions.
