### ISSUE TITLE
The exports returned from create_exports contains duplicate keys

### ISSUE THREAD

**Issue by echeese** [kripken/emscripten#5210]
I noticed that the object returned from the asm part contains duplicate keys. Here's an example from a simple hello world. The code that produces this object is in `create_exports` in `emscripten.py` but the actual bug may be further up the chain, passing in these exports twice.

<details>

```js
return {
	_malloc: _malloc,
	getTempRet0: getTempRet0,
	_free: _free,
	runPostSets: runPostSets,
	setTempRet0: setTempRet0,
	establishStackSpace: establishStackSpace,
	stackSave: stackSave,
	_memset: _memset,
	_sbrk: _sbrk,
	_emscripten_get_global_libc: _emscripten_get_global_libc,
	_memcpy: _memcpy,
	stackAlloc: stackAlloc,
	setThrew: setThrew,
	_fflush: _fflush,
	stackRestore: stackRestore,
	___errno_location: ___errno_location,
	stackAlloc: stackAlloc,
	stackSave: stackSave,
	stackRestore: stackRestore,
	establishStackSpace: establishStackSpace,
	setThrew: setThrew,
	setTempRet0: setTempRet0,
	getTempRet0: getTempRet0,
	dynCall_ii: dynCall_ii,
	dynCall_iiii: dynCall_iiii
}
```
</details>

`stackAlloc`, `stackSave`, `stackRestore`, `establishStackSpace`, `setThrew`, `setTempRet0` and `getTempRet0` are all contained twice in the object.

**Comment by wyown** [comment]
yes, i have met the same problem。

**Comment by nazar-pc** [comment]
Potentially causes problems for #5464, will try to investigate

**Comment by nazar-pc** [comment]
Linked PR is merged now, this can be closed.
