### ISSUE TITLE
emrun requires python2

### ISSUE THREAD

**Issue by m0rl** [kripken/emscripten#5211]
Running *emrun* with python3 is resulted in error. AFAIU it's not designed to be compatible  
with python3, so maybe it would be better to replace `#!/usr/bin/env python` with  
`#!/usr/bin/env python2`?

**Comment by juj** [comment]
We cannot do that change because of https://github.com/kripken/emscripten/issues/3872#issuecomment-151115726. Fixed in a different manner in https://github.com/kripken/emscripten/commit/57c18ddf39abcc9fd9794b6ace853f73dc5f7842.
