### ISSUE TITLE
Creating webassembly file for a standalone runtime

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [kripken/emscripten#5214]
I have been looking into running wasm on a runtime by itself. Initially the main emscripten branch was difficult to use(atleast a lot of effort!!) for this due to the number of imports and other reasons. I have been using this-https://mbebenita.github.io/WasmExplorer/ for creating wasm files till now. I revisited emscripten this week and found the incoming  branch interesting- https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone. It gives me more optimized wasm but I do have a couple of questions
1. Assuming I want to stick to just 1.0 MVP features, do you suggest any particular branch for a standalone vm?
2. Is there an exhaustive list of functions which needs to be supported by vm(env) somewhere? I mean library functions like 'malloc' which emscripten imports. I was wondering if it's any c/c++ library functions used or just a subset of those.
3. Is there a way to force emscripten to tag a particular function as 'start'

My apologies if these questions have already been answered.

**Comment by kripken** [comment]
1. All we support are 1.0 MVP features currently. Eventually more will happen. At that point using an older version might make sense for you.
2. Basically everything not implemented becomes an import. So if you include a malloc implementation in the compiled files, malloc will not be an import, and the same for the rest of libc. So it completely depends on the input files.
3. No current option for that, although that sounds reasonable to add to binaryen.

**Comment by dschuff** [comment]
`s2wasm` has a flag `--start` to specify which function is the start function.

**Comment by DeepakRajendrakumaran** [comment]
Thanks for the explanations. I have been playing around with different options for teh past couple of days but I still have some questions.

Note: My source c file has no 'main' function. Assuming the entry function of the hypothetical runtime is another function
1. I tried the 'normal' wasm compilation (http://webassembly.org/getting-started/developers-guide/)(method 1) and compiling as a side module(method 2). I declared a function as  extern in my source file in both cases. In method 2, the 'extern' method showed as an import. I expected to see the same in method 1 as well since that function is not defined in any c system libraries for emscripten to pull in. But surprisingly, I did not see the 'extern' function as an import in method 1
2. Using s2wasm- I tried this but it gives an error. I tried the following 3 methods.
a. Use emcc to dump a .s file and use s2wasm. s2wasm fails
b. Use clang to dump a .ll /.bc and convert it to .s using llc. llc fails saying 'error: invalid target 'wasm32'.'

**Comment by kripken** [comment]
An extern should show up as an import, unless it is never used and so optimized out. If it is used, please make a testcase showing the issue, it might be a bug.

I don't think anyone is working on tool to modify `start` in modules in binaryen, feel free to write a PR.

**Comment by DeepakRajendrakumaran** [comment]
I have attached a zip file with a c file having the source code and the corresponding wasm/wast/js/html files.

I created the wasm file from c using the following command-
$emcc hello.c -s WASM=1 -o hello.html
 The wast file was created using wasm2wast from wabt.

[posssible_Bug.zip](https://github.com/kripken/emscripten/files/1001857/posssible_Bug.zip)

**Comment by kripken** [comment]
The issue was that the compiler optimized it out, since it thought it wasn't used. The extern was used from `entryFunc`, but `entryFunc` wasn't used, so both were removed. You can make `entryFunc` be used by e.g. marking it with `EMSCRIPTEN_KEEPALIVE` (from `emscripten.h`).

Btw, emcc will emit a `.wast` for you (so you don't need an additional tool) if you build with `-g`.

**Comment by DeepakRajendrakumaran** [comment]
Yeah..that makes sense. I should have have figured that out myself.My bad.

Thanks for clearing it up.

**Comment by kripken** [comment]
No problem, this is kind of a confusing issue. Unlike most platforms, we work hard to remove dead code from final binaries, because code size on the web matters a lot, and to make it more confusing here, in a shared module (like a side module), we don't do that intentionally because we know it will be "linked" later.
