### ISSUE TITLE
Can't set `memoryInitializerPrefixURL` when requiring in Node.js

### ISSUE THREAD

**Issue by phraemer** [kripken/emscripten#5216]
If you want to set the mem file prefix you can't do this before you require in node.
E.g.

```bash
./nodeInitScript.js
./dir_with_mem_file/myapp.js.mem
./dir_with_js_file/myapp.js
```

In `nodeInitScript.js`

```js
global.Module = {
	'memoryInitializerPrefixURL': './dir_with_mem_file/'
};

require('./dir_with_js_file/myapp.js');
```

```bash
node nodeInitScript.js
```

But if you manually remove `var Module;` from `myapp.js` then you can.
Perhaps we need an option like `-s USE_GLOBAL_MODULE_IN_NODE=1` which then doesn't output `var Module;`?

**Comment by kripken** [comment]
I don't know much about this, but is the `MODULARIZE` option related here? You can provide the memoryInitializerPrefixURL as a parameter to the object passed into the constructor function, in that case.

**Comment by phraemer** [comment]
Ah yes thanks, `MODULARIZE` helps a lot.
All that would be missing for Node then would be a line right at the bottom which exports the `Module` constructor function.

As a workaround I can do this...
```sh
echo "module['exports'] = Module;" >> myapp.js
```
And then as you suggest pass in my own object to the constructor function.

Better would be to do the same environment detection as in `if (Module['ENVIRONMENT']) {...`  and export if `ENVIRONMENT_IS_NODE` is true. Without exporting it the function is not visible and therefor not callable in Node.

I could make a PR for this if you would like?

**Comment by kripken** [comment]
That sounds good, yeah.
