### ISSUE TITLE
What is _llvm_trap(); ?

### ISSUE THREAD

**Issue by BabyRaptor** [kripken/emscripten#522]
Hi Kripken.

I have an issue like this. I tried to convert a big project, and when I run, an error about "_llvm_trap()" is not a function appeared. When I view the generated code, it's like:

_llvm_trap();
throw "Reached an unreachable!"

in a class constructor.

i have no idea what is this, but a magic appear just by adding a printf at the top of that constructor. i swear I don't add anything else, just a simple printf:

printf("a \n");

and the program can run with no problem. And when I view the generated Javascript code, the llvm_trap disappear, and no "unreachable" stuff too...

Can you explain me why this happened? And how to fix? because adding a printf to solve this problem will not be a good solution in the long term, as it... make no sense at all?

Thank you.

**Comment by juj** [comment]
Closing as old/stale. We've had a number of updates to LLVM since, so the landscape looks quite different now.
