### ISSUE TITLE
Agressive variable elimination produces invalid js if the variable being eliminated is never assigned after its declaration.

### ISSUE THREAD

**Issue by ImplOfAnImpl** [kripken/emscripten#5226]
The easiest way to reproduce this is to update tests.
E.g. in tests/optimizer/test-js-optimizer-shiftsAggressive.js add: `whee4(1 + $1);`
The corresponding expected string would be `whee4(1 + 0);`, however the actual result is `whee4(1 + );`

Checked on revision 8fae9e574972f91ada64509c4d771b0df1da2d80

**Comment by kripken** [comment]
Fixed by your PR.
