### ISSUE TITLE
Function/Variable names in the export/import section

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [kripken/emscripten#5228]
Is there a fixed convention for the function names used in the export/import?

The wasm documentation states- _Each export has three fields: a **name**, whose meaning is defined by the host environment, a type, indicating whether the export is a function, global, memory or table, and an index into the type’s corresponding index space._ 

Is there a convention regarding what this 'name' needs to be in the created wasm file?

For example a function 'myFunc' in c gets converted to '_myFunc' when wasm module is created using emscripten as a side module

'(import "env" "_myFunc" (func $_myFunc (param i64) (result i32)))'

But when I used another tool-https://mbebenita.github.io/WasmExplorer/
(import "env" "_Z12myFuncy" (func $_Z12myFuncy (param i64) (result i32)))

If an option to compile as a dynamic library is provided, shouldn't there be a common naming convention to ensure that individual functions can be identified/called from outside the module ? Internal indices are not reliable for this if multiple modules are not compiled together.

Am I missing something here?

**Comment by kripken** [comment]
Yeah, conventions need to match for things to work together, but like with native development, there are multiple conventions here. For example `_Z12myFuncy` is `myFunc` with clang's c++ name mangling, so if you link that with something else, it needs to know that it's using clang's c++ name mangling (as opposed to if it were built with `extern "C"`). I think there are plans to write up more naming conventions on the [wasm tool conventions repo](https://github.com/WebAssembly/tool-conventions).

**Comment by DeepakRajendrakumaran** [comment]
So, is the emscipten/binaryen standard to add a '_' to the beginning of externs and exported functions for the default build? I guess my question is , is it reliable to assume that if I see an 'import _myFunc', it means that there was an 'extern myFunc' in my c source

**Comment by kripken** [comment]
Emscripten does have the convention of adding `_` to compiled methods. Although that is more important for internal things (to contrast with JS), and on the wasm module, perhaps we should get rid of that. That's what the wasm backend does anyhow, so this could be a good way to simplify things?

**Comment by DeepakRajendrakumaran** [comment]
From your explanation, it seems like more of a tooling convention issue. So, rather than just emscripten changing it, maybe raising it in the wasm tool conventions repo would probably make sense since uniformity across tools either with or without the '_' would be the most desired outcome
