### ISSUE TITLE
html5.h does not offer a way to call `document.documentElement.requestFullscreen()`

### ISSUE THREAD

**Issue by rmsmith** [kripken/emscripten#5232]
I have encountered a case where calling `emscripten_request_fullscreen` on my element does not work on Chrome (58) for Android.  Investigating, it turns out that the recommended approach[1] is to call `document.documentElement.requestFullscreen()`.  But, I could not find any way to make this call via the Emscripten API.  Passing `#document` as the `target` does not work, as that results in a call to `document.requestFullscreen` instead.  One possible fix would be to add another alias like `#documentElement`.

My workaround for now is to use an `EM_ASM` block to make the call in JavaScript.

thanks!

[1] : https://developers.google.com/web/fundamentals/native-hardware/fullscreen/

**Comment by rmsmith** [comment]
I'll go ahead and close this since its easy enough to make the call into JavaScript.

**Comment by juj** [comment]
What is `document.documentElement`? Can you add an `id` to that element, and then request fullscreen based on that id?
