### ISSUE TITLE
empty Module object when imported in ReactNative

### ISSUE THREAD

**Issue by w8choi** [kripken/emscripten#5241]
I'm compiling a c code to js with emscripten and then importing the Module from index file so I call call cwrap. But I keep getting an error shown below (picture) while getting {} for Module when I console log it. I'm thinking Module object isn't being exported when I try to import it from another js file? Any suggestions as to why this is happening?

![18697932_10158760596775551_116534358_o](https://cloud.githubusercontent.com/assets/20712883/26376070/39a4488c-3fd9-11e7-8a1c-ab86a1087b51.png)

**Comment by kripken** [comment]
Is this with modularize? then #5239 might be relevant.

**Comment by w8choi** [comment]
I don't really use modularize but I think it might be relevant regardless? I mean it worked before and then when I overwrote it with another compiled file it stopped working and I have no way of recovering the file I used when it worked... :(

**Comment by kripken** [comment]
Sounds like it's not modularize then. Must be something in how react native loads code then, I know little about it, but I'd start with adding some console.logs in relevant places etc.

**Comment by w8choi** [comment]
Okay. I'll try that and see what happens. could you tell me where the Module object is being exported on the generated script? It's detecting RN app environment as WEB environment and I couldn't find the place where it actually exports the Module. (I could have missed it but when I console log from compiled js, Module object isn't empty)

**Comment by kripken** [comment]
Look in `shell.js`, the export code and environment setup is there. From what you say, it sounds like it might be that we don't handle RN properly, i.e., we have export code for node.js but not for RN. That's similar to #5239 (where we discuss exporting not just for node.js but anything that has a `module` object) which is why I thought it might be related - maybe we need to add export code for the environment.

**Comment by w8choi** [comment]
not quite sure what I can do at the moment but is there like a quick fix I can try? maybe?

**Comment by kripken** [comment]
You can try code similar to what is in that pr, might fix it. But I wouldn't do so blindly - I would add some debug printouts, and find out what's going wrong. This should be a matter at the JS level, so nothing to do with emscripten compiled-code complexity.

**Comment by rawrmaan** [comment]
@w8choi Did you ever solve this? I'm having the same issue.

**Comment by w8choi** [comment]
@rawrmaan No I have not.
I tried just copy pasting the generated code inside the component that I need to use which is VERY bad idea since bundled js becomes stupid. 
So ended up just building Bridge from JavaScript to C++ code
