### ISSUE TITLE
Worrying 100% CPU on browser.test_asmfs_read_file_twice

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#5263]
That test leaves a tab open which takes 100% CPU on firefox (53). What is very odd is that it keeps taking 100% CPU even when it is a background tab, and it doesn't appear to be doing work in a worker - so that shouldn't happen. Seems to be a firefox bug.

Aside from looking like a firefox bug, this seems to be a serious problem - when I run enough of the test suite the browser grinds to a halt, I suspect because more tests hit the same issue, so more and more open tabs at 100% CPU keep adding up.

I'm having trouble investigating this, so filing this here instead of firefox. First, the testcase just throws an error in Chrome, so I don't have a proper comparison across browsers. Second, I'm not sure what the testcase does precisely, so I'm not sure what area of firefox to file the bug on.

@juj, you wrote the test, what do you think?

**Comment by juj** [comment]
Hmmhmm, that doesn't sound good.

Tried out on a 2016 MacBook Pro with Firefox Nightly 55.0a1 (2017-05-30) (64-bit), that does not at least exhibit issues. Does the issue occur on Firefox Nightly for you?

**Comment by kripken** [comment]
Hmm yes, I see no problem on nightly. I guess it was indeed a firefox bug and has been fixed.
