### ISSUE TITLE
Direct access to the OS filesystem

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5266]
The NODEFS is documented as a way to directly access filesystem, but it's limited because it should be used through `FS.mount()`. As a result the C code cannot easily access paths for other drives e.g. `D:/image.png` (on Windows) got from the user input. Is there another way to allow "direct access" to OS filesystem?

Currently I'm trying to port image encoder/decoder to Node.js wasm command-line tool by passing process.argv into `callMain()`. However, this limitation forces me to pre-parse the arguments and then convert the paths.

In addition, the root directory `/` is not really the root one in Windows (same as `C:/`), which means you need to manually enumerate all drives to mount them. This cannot be done on Node in a simple way and causes cross-platform compatibility issue.

**Comment by SaschaNaz** [comment]
Similar to the one discussed on https://github.com/kripken/emscripten/pull/3152

**Comment by SaschaNaz** [comment]
I had to use [some hack](https://github.com/SaschaNaz/flif-wasm/blob/02362d95a94c59ff14b094c4f5ab50c021dc1e80/sources/flif-wasm.ts) to solve this problem, but it has unexpected permission problem when accessing user directory e.g. `C:/Users/username/Documents/`. No idea why...

**Comment by juj** [comment]
> The NODEFS is documented as a way to directly access filesystem, but it's limited because it should be used through FS.mount()

Thanks, updated the documentation in the above commit.

> Is there another way to allow "direct access" to OS filesystem?
> 
> Currently I'm trying to port image encoder/decoder to Node.js wasm command-line tool by passing process.argv into callMain(). However, this limitation forces me to pre-parse the arguments and then convert the paths.

Unfortunately Emscripten's filesystem (`library_fs.js`) is hardcoded to only understand the Unix path names form, so it cannot reason about the form `"C:/path/to/file.txt"` at all. Mounting root directories under `/mnt/c`, `/mnt/d`, etc. like MSYS does is probably the best bet here.

If one wanted to remove the whole virtual filesystem and replace it with direct mappings to node, then that would probably mean removing the `FS` object altogether and writing a `RAWNODEFS` or similar to fully replace this. That would mean that Emscripten would not maintain a filesystem at all, but only pass all filesystem operations through to node - though I'm not sure how much of a 1:1 correspondence these would have?

**Comment by saschanaz** [comment]
>If one wanted to remove the whole virtual filesystem and replace it with direct mappings to node, then that would probably mean removing the FS object altogether and writing a RAWNODEFS or similar to fully replace this.

I think a potential `RAWNODEFS` still should coexist with current `FS` to keep supporting non-node environments.
