### ISSUE TITLE
How does sdl_thread work with the binaryen backend?

### ISSUE THREAD

**Issue by 0joshuaolson1** [kripken/emscripten#5267]
Not sure where to ask. I know little about WebAssembly, but binaryen's codebase doesn't seem to me to deal with SDL directly.

**Comment by kripken** [comment]
I believe we simply don't have support for sdl_thread.

There is support for pthreads, which works with the SharedArrayBuffer spec that is being standardized.

**Comment by 0joshuaolson1** [comment]
Should there be an issue specifically for sdl_thread? I can't be the only uninformed prospective Emscripten user surprised SDL isn't supported completely.
