### ISSUE TITLE
Unexpected Error: Permission denied on FS.readdir on Windows

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5268]
```cpp
// helloworld.cpp ---emcc--> helloworld.js
#include <cstdio>

int main() {
  printf("Hello World!\n");
}
```

```js
// app.js
const _helloworld = require("./helloworld.js");

let notifyReady;
const tillReady = new Promise(resolve => notifyReady = resolve);
const helloworld = _helloworld({ onRuntimeInitialized: notifyReady });

async function main() {
    await tillReady;

    // helloworld.callMain([]);

    helloworld.FS.mkdir("/mnt");
    helloworld.FS.mkdir("/mnt/c");
    helloworld.FS.mount(helloworld.FS.filesystems.NODEFS, { root: "/" }, "/mnt/c");
    console.log(helloworld.FS.readdir("/mnt/c/Users/")); // no problem here
    console.log(helloworld.FS.readdir("/mnt/c/Users/(your username)/")); // Throws permission error
}
main();
```

```
emcc -s MODULARIZE=1 -s INVOKE_RUN=0 -s EXTRA_EXPORTED_RUNTIME_METHODS=['FS'] -s WASM=1 -s FORCE_FILESYSTEM=1 -s NO_EXIT_RUNTIME=1 helloworld.cpp -o helloworld.js
```

With the latest sdk-incoming-64bit (emcc 1.37.13) and Node.js 8.0.0 this throws. Strangely, when I comment out `await tillReady` line it does not throw, but then I cannot call `callMain`. Why does this happen?

PS on Nov 25, 2017: It does not throw when FS.staticInit hasn't been called (so NODEFS does not know it's on Windows)

**Comment by juj** [comment]
Not sure since I don't see the whole example, but do you know if that waits for the filesystem to initialize before the `main()` function is called? Try debugging that `FS.staticInit();` and `FS.init();` have been called before `main`?

**Comment by SaschaNaz** [comment]
This *is* the whole example, no other user code is involved.

Calling `FS.init` after `await tillReady` says:

>Assertion failed: FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)

And calling `FS.staticInit` says `Error: Mount device busy`.

**Comment by TheJaredWilcurt** [comment]
Also waiting on a fix for this.

**Comment by juj** [comment]
> This is the whole example, no other user code is involved.

Ah thanks, I had misinterpreted the example.

Trying this out on macOS 10.12.6 and Node.js 8.9.0 does not give an error, so looks like Windows specific.

**Comment by TheJaredWilcurt** [comment]
can confirm. It does not happen on OSX or Ubuntu. Only on Windows when inside the `C:\users\<user>\` directory. If you test in `C:\test\` it works fine.

**Comment by saschanaz** [comment]
My investigation shows that `C:\Users` has permission 444 so `FS.nodePermissions(dir, 'x')` inside `FS.mayLookup` fails.

**Comment by saschanaz** [comment]
Why does mayLookup check `w` instead of `r`?

**Comment by saschanaz** [comment]
Why does mayLookup check `x` instead of `r`?

**Comment by juj** [comment]
> Why does mayLookup check x instead of r?

On POSIX `x` bit on directories means it's allowed to traverse (enter) the directory. You can remove an `x` flag from a directory but keep its `r` flag, which will then allow one to read files in that directory, but not enter the directory (and curiously, this doesn't allow `ls`ing the directory, but `find` will work to look inside the directory). I think the intent of `mayLookup`  here has been of the "enter the directory" sorts, since a directory with read but not execute is of limited use. (also https://unix.stackexchange.com/questions/21251/execute-vs-read-bit-how-do-directory-permissions-in-linux-work for the nuances)

**Comment by TheJaredWilcurt** [comment]
So this was closed. I assume some conditional statement was added for Windows to fix this?

**Comment by saschanaz** [comment]
This is fixed by getting `x` bit from `r` bit. See #5847 for more information.
