### ISSUE TITLE
portable sdk installation fails.

### ISSUE THREAD

**Issue by lukasschmit** [kripken/emscripten#5272]
I am trying to install the latest portable sdk on OSX. I ran `./emsdk update` successfully, but the next step, `./emsdk install latest`crashes with the following after a few seconds:

>HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/emscripten-llvm-e1.37.13.tar.gz': HTTP Error 403: Forbidden
Installation failed!

I tried using sudo and that made no difference. Seems like this llvm file was uploaded incorrectly or something.

**Comment by lukasschmit** [comment]
I should point out a few other files download seemingly successfully first. Here's the full output:

>./emsdk install latest
Fetching all tags from Emscripten Github repository...
Done. 100 tagged releases available, latest is 1.37.13.
Fetching all tags from Binaryen Github repository...
Done. 27 tagged Binaryen releases available, latest is 1.37.13.
Fetching all precompiled Nightly versions..
Downloading: /Users/lukasschmit/emsdk-portable/llvm-nightlies-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/linux_32bit/index.txt
Downloading: /Users/lukasschmit/emsdk-portable/llvm-nightlies-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/linux_64bit/index.txt
Downloading: /Users/lukasschmit/emsdk-portable/emscripten-nightlies.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten/nightly/linux/index.txt
Fetching all precompiled tagged releases..
Downloading: /Users/lukasschmit/emsdk-portable/llvm-tags-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_32bit/index.txt
Downloading: /Users/lukasschmit/emsdk-portable/llvm-tags-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_64bit/index.txt
Installing SDK 'sdk-1.37.13-64bit'..
Installing tool 'clang-e1.37.13-64bit'..
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/emscripten-llvm-e1.37.13.tar.gz': HTTP Error 403: Forbidden
Installation failed!

**Comment by AliKarami** [comment]
I have this problem too.
it seems they are playing with file permissions in past hours :))

**Comment by lukasschmit** [comment]
@AliKarami Oh thanks that worked!

**Comment by CoreyDotCom** [comment]
Having same issue (I suppose we all are) with latest.

**Comment by juj** [comment]
Sorry about this, I notice that this is caused by a regression from https://github.com/juj/emsdk/pull/76. The workaround @AliKarami suggests is a good one, as we don't yet have 1.37.13 installers available on OS X due to https://github.com/WebAssembly/binaryen/issues/1035, but Linux does have 1.37.13. The problem here was that OS X is misidentified as Linux for the purposes of detecting which SDK versions are available.

**Comment by juj** [comment]
This should now be resolved and both emsdk install latest and emsdk install sdk-1.37.13-64bit should work.

However while working on this, I noticed that it's possible that emsdk update returns without printing anything and does not actually update emsdk. If that is the case, try redownloading emsdk_portable from a zip file (https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.zip for Windows and https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz for OS X)

If the issue still appears with latest, feel free to reopen.

**Comment by muraray** [comment]
I got the same error while running the below scripts

`C:\EmscriptenSDK
λ emsdk update
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip': <urlopen error [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Fetching all tags from Emscripten Github repository...
Done. 121 tagged releases available, latest is 1.37.34.
Fetching all tags from Binaryen Github repository...
Done. 48 tagged Binaryen releases available, latest is 1.37.34.
Fetching all precompiled Nightly versions..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/win_32bit/index.txt': <urlopen error [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/win_64bit/index.txt': <urlopen error [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten/nightly/win/index.txt': <urlopen error [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Fetching all precompiled tagged releases..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_32bit/index.txt': <urlopen error [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/index.txt': <urlopen error [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>`

Any suggestions

**Comment by juj** [comment]
The printed error log looks different, it mentions a SSL error, rather than a 403 Forbidden. The 403 Forbidden was caused by a missing file on the S3 bucket. The SSL error seems to be something to do with unagreeable handshake with your system and the Amazon S3 services. Not sure how to resolve that though.

Does

```
wget https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip
```

work on your system? Or via curl?

```
curl -O https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip
```

Or attempting to download the URL directly in a web browser?

**Comment by satyanandarowlo** [comment]
Actual fix is to use the exact python version specified in the documentation. Git has some changes related to python, so if there is wrong paths fetched for python, these kind of error will occur. if you are on macos , type python , then you will see python version number. try to update to different versions by installing new one. if nothing works, you have to uninstall python versions which you manually installed recently. I tried all other alternatives and this worked for me perfectly.
