### ISSUE TITLE
getaddrinfo() should always set ai_canonname to avoid invalid pointer

### ISSUE THREAD

**Issue by lukester1975** [kripken/emscripten#5282]
Hi

I've been getting sporadic failures using getaddrinfo() via Boost.asio, which the following with the returned addrinfo:

```
    std::string actual_host_name = host_name;
    if (address_info->ai_canonname)
      actual_host_name = address_info->ai_canonname;
```

The emscripten implementation of getaddrinfo() does (library.js):

```
      if (canon) {
        {{{ makeSetValue('ai', C_STRUCTS.addrinfo.ai_canonname, 'canon', 'i32') }}};
      }
```
hence getting a spurious non-null value for ai_canonname sometimes (`canon` is always null). Manifests itself as a strlen memory bound error from the assignment in Boost.asio. I've just removed the `if (canon) {` to make Boost.asio happy.

I guess it could be argued that the Boost.asio code should check for ai_flags and AI_CANONNAME before accessing ai_canonname, but looking at the Linux man page for getaddrinfo(), it doesn't appear to say that the results ai_flags will actually contain the value of the hints ai_flags (though I imagine it probably does - not checked). That said, emscripten's getaddrinfo() doesn't set ai_flags for the results addrinfo as far as I can tell, so maybe it should do that also...

Regards

Luke.

**Comment by juj** [comment]
Thanks, agreed here, it is best to always initialize the field to 0, independent of the input. It's not good form to have random bytes in output structures. Pushed your recommended fix in in the above commit.
