### ISSUE TITLE
SAFE_HEAP=1 causes "RuntimeError: function signature mismatch"

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#5285]
I'm trying to debug a [WebAssembly-only OOB memory access bug](https://bugs.chromium.org/p/chromium/issues/detail?id=729768) with SAFE_HEAP but it's not working for me. With the SAFE_HEAP=1 flag enabled, we get "RuntimeError: function signature mismatch" in both Firefox and Chrome. Our app works fine without that flag enabled. The function at the top of the call stack is in our C++ code and looks pretty benign. It does call out from C++ to JavaScript through an extern C binding though.

I'm not sure why this is happening because I'm not yet familiar with debugging WebAssembly. Chrome's Developer Tools says the problematic instruction is `call_indirect 6` but I'm not sure how to map that back to our source code. What's the best way of debugging this?

**Comment by jgravelle-google** [comment]
Which LLVM are you using? Is this using asm2wasm or s2wasm?
I've been seeing a similar issue with the s2wasm path, due to the FixFunctionBitcasts pass. My gut says SAFE_HEAP shouldn't introduce function pointer bitcasts on the wasm side, but I'm not super confident there.

**Comment by kripken** [comment]
Yeah, steps differ if this is asm2wasm or s2wasm. Assuming it's asm2wasm (the default) I would try this:

 * SAFE_HEAP enables the js optimizer. To rule that out, I'd build without SAFE_HEAP but with `--js-opts 1`. The wasm should be different (larger, as enabling the js optimizer is less efficient), and if it still shows the bug, it's an unknown js optimizer integration issue with asm2wasm perhaps.
 * SAFE_HEAP mode does 3 things: instrument loads, instrument stores, and instrument function pointer calls. The last is what might be relevant here. We check if the asm.js mask causes an overflow, which it should not - if it does, that means that the mask *made things work*, which is very very odd. To check if that's relevant, you can just remove that part of SAFE_HEAP and see if things change, see the `else` on line 5792 of `tools/js-optimizer.js`, there are 4 lines there that do the instrumentation, one of which has `SAFE_FT_MASK` in it. Can just erase those 4 lines and rebuild.

**Comment by evanw** [comment]
I can confirm that adding `--js-opts 1` (without `-s SAFE_HEAP=1`) to our build causes "RuntimeError: function signature mismatch". I'll work on a reduced test case.

**Comment by evanw** [comment]
Ok, here's a reduced test case:

```c++
#include <stdio.h>
#include <functional>
#include <vector>

struct Node {
  std::vector<Node *> _children;

  struct ChildIterator {
    bool operator != (const ChildIterator &other) const { return _node != other._node || _index != other._index; }
    size_t operator - (const ChildIterator &other) const { return _index - other._index; }
    void operator ++ () { _index++; }
    Node *operator * () { return _node->_children[_index]; }

    const Node *_node;
    size_t _index;
  };

  struct Children {
    ChildIterator begin() const { return {_node, 0}; }
    ChildIterator end() const { return {_node, _node->_children.size()}; }

    const Node *_node;
  };

  Children children() const { return {this}; }
};

void crashes(Node *root) {
  std::function<void (Node *)> visit;

  visit = [&](Node *node) {
    for (auto child : node->children()) {
      visit(child);
    }
  };

  for (auto child : root->children()) {
    visit(child);
  }
}

int main() {
  Node tree;
  tree._children.push_back(new Node);
  tree._children.front()->_children.push_back(new Node);

  puts("before");
  crashes(&tree);
  puts("after");
  return 0;
}
```

Compile with `emcc bug.cpp -std=c++11 --js-opts 1 -s WASM=1 -O3 -fno-exceptions`. Running that using `<script src="a.out.js"></script>` gives this output:

```
asynchronously preparing wasm
binaryen method succeeded.
before
exception thrown: RuntimeError: function signature mismatch
    at <WASM UNNAMED> (<WASM>[21]+180)
    at <WASM UNNAMED> (<WASM>[22]+185)
    at Object.Module._main (http://localhost:8000/a.out.js:1:39055)
    at Object.callMain (http://localhost:8000/a.out.js:1:44025)
    at doRun (http://localhost:8000/a.out.js:1:44768)
    at run (http://localhost:8000/a.out.js:1:44936)
    at runCaller (http://localhost:8000/a.out.js:1:43527)
    at removeRunDependency (http://localhost:8000/a.out.js:1:25186)
    at receiveInstance (http://localhost:8000/a.out.js:1:28665)
    at http://localhost:8000/a.out.js:1:29094
```

**Comment by kripken** [comment]
Strange, I can't reproduce that problem, using emscripten incoming, firefox nightly and chrome dev, on linux. Which versions are you using?

Unrealted, is perhaps the trap mode relevant here? Does `-s 'BINARYEN_TRAP_MODE="js"'` change things for you?

**Comment by evanw** [comment]
We're using 1.37.9 (the latest version that worked at the time we enabled WebAssembly) and I'm on macOS using stable versions of Chrome 59.0.3071.86 (64-bit) and Firefox 53.0.3 (64-bit).

I tried compiling with `emcc bug.cpp -std=c++11 --js-opts 1 -s WASM=1 -O3 -fno-exceptions -s 'BINARYEN_TRAP_MODE="js"'` but it still has the same problem. Is that what you meant for me to try?

I tried using a newer version of emscripten (1.7.12) but it has the same problem. Here were my steps:

```sh
$ curl -O https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
$ tar xzf emsdk-portable.tar.gz 
$ cd emsdk-portable
$ ./emsdk list
$ ./emsdk install sdk-1.37.12-64bit
$ ./emsdk activate sdk-1.37.12-64bit
$ . emsdk_env.sh
$ cd ..
$ emcc bug.cpp -std=c++11 --js-opts 1 -s WASM=1 -O3 -fno-exceptions
```

Unrelated: I tried installing the latest version (1.7.13) but it looks like that's currently broken:

```sh
$ ./emsdk install sdk-1.37.13-64bit
Installing SDK 'sdk-1.37.13-64bit'..
Installing tool 'clang-e1.37.13-64bit'..
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/emscripten-llvm-e1.37.13.tar.gz': HTTP Error 403: Forbidden
Installation failed!
```

**Comment by kripken** [comment]
Hmm, not sure what's wrong with 1.37.13. But I suggest [trying incoming](https://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_using_the_sdk.html#building-emscripten-from-the-main-repositories).

And you saw the crash on both firefox and chrome? Or just chrome as in the original issue in the chrome bug you filed?

**Comment by evanw** [comment]
It appears to work in incoming. The "RuntimeError: function signature mismatch " crash with `--js-opts 1` was in both Firefox and Chrome. The original "memory access out of bounds" was only in Chrome.

**Comment by evanw** [comment]
I built our app with incoming and `-s SAFE_HEAP=1`. It looks like the SAFE_HEAP option was broken but was fixed recently, so I'll close this issue. I tested SAFE_HEAP with `*(char*)0x3FFFFFFF` and that correctly throws a `segmentation fault` now in both Firefox and Chrome when I build with incoming.

I'll comment over on #5161 with info relating to the original Chrome bug.
