### ISSUE TITLE
403 when running install latest

### ISSUE THREAD

**Issue by Math3v** [kripken/emscripten#5291]
Reproduce:

- download the latest Portable Emscripten SDK for Linux and OS X
 - extract
 - run emsdk update
 - emsdk install latest

Error:
```
Installing SDK 'sdk-1.37.13-64bit'..
Installing tool 'clang-e1.37.13-64bit'..
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/emscripten-llvm-e1.37.13.tar.gz': HTTP Error 403: Forbidden
Installation failed!
```

**Comment by Paca-Vaca** [comment]
https://github.com/kripken/emscripten/issues/5272 Possible solution

**Comment by juj** [comment]
This should now be resolved and both `emsdk install latest` and `emsdk install sdk-1.37.13-64bit` should work.

However while working on this, I noticed that it's possible that `emsdk update` returns without printing anything and does not actually update emsdk. If that is the case, try redownloading emsdk_portable from a zip file (https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.zip for Windows and https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz for OS X)

If the issue still appears with latest, feel free to reopen.

**Comment by Math3v** [comment]
Thanks for your response @juj and @Paca-Vaca.

Not it's working, but you are right that `emsdk update` returns without printing anything.

**Comment by juj** [comment]
Thanks for the confirmation. In that case, either updating via above zips, or deleting a single line `sys.exit(0)` in script `emsdk` on line 1495 or so in function `update_emsdk()` should get `emsdk update` to working again.
