### ISSUE TITLE
How to link Boost or other library in Emscripten

### ISSUE THREAD

**Issue by messset** [kripken/emscripten#5306]
Sorry if this question is clumsy or duplicated.

I want to compile my C++ project to wasm which used Boost lib .
But I have no idea to link it in Emscripten.

I use  Emscripten 1.37.9  , Win10
Thank you!

**Comment by juj** [comment]
The mechanism to link should be the same as with native, whichever build system you are using. Make sure to generate static libraries instead of dynamic libraries, since dynamic linking is a bit experimental.

**Comment by messset** [comment]
Thanks for your reply.

If I have some ".lib" file, what should I do to link them. 
like putting them on some path, 
or inputting something in cmd before compile(em++ .....)

**Comment by juj** [comment]
Did you build those .lib files with Emscripten? If these are libraries that are compiled for native operating system to execute, then they contain native code and not LLVM bitcode/WebAssembly. You'll need to make sure that Boost itself is built with Emscripten.

In general the linker command line looks something like this: https://stackoverflow.com/a/17222528, but `g++` is replaced with `em++`.

**Comment by udnaan** [comment]
If you are using header only portion of boost than almost no change is required. It should just work as it would with clang or gcc.
