### ISSUE TITLE
Deadlock on building wasm-backend libc

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#5310]
This is a regression from #5074. STR:

````
rm -Rf ~/.emscripten_cache.lock ; EMCC_WASM_BACKEND=1 ./emcc --clear-cache ; EMCC_WASM_BACKEND=1 ./emcc tests/hello_world.c
````

That erases the lock file (so there is no history that can explain the bug), then clears the cache (so we need to rebuild libc) and then tries to build libc using the wasm backend.

This deadlocks on my machine on the cache filesystem lock: it just stalls and waits on the lock, no cpu usage, and eventually prints out the deadlock warnings:
````
WARNING:root:Accessing the Emscripten cache at "/home/alon/.emscripten_cache/wasm" is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "/home/alon/.emscripten_cache.lock" and try again. If this occurs deterministically, consider filing a bug.
WARNING:root:Accessing the Emscripten cache at "/home/alon/.emscripten_cache/wasm" is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "/home/alon/.emscripten_cache.lock" and try again. If this occurs deterministically, consider filing a bug.
WARNING:root:Accessing the Emscripten cache at "/home/alon/.emscripten_cache/wasm" is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "/home/alon/.emscripten_cache.lock" and try again. If this occurs deterministically, consider filing a bug.
WARNING:root:Accessing the Emscripten cache at "/home/alon/.emscripten_cache/wasm" is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "/home/alon/.emscripten_cache.lock" and try again. If this occurs deterministically, consider filing a bug.
````
This is on a machine with 4 cores, so looks like all 4 are waiting on something... else.

cc @jgravelle-google

**Comment by kripken** [comment]
In fact `UnixFileLock._acquire` seems to be called in a loop, a print in that function keeps getting printed (far more than the number of cores). No releases are called.

**Comment by juj** [comment]
Tried out with

```bash
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install --build=Release --enable-wasm --build-tests sdk-incoming-64bit binaryen-master-64bit
./emsdk activate sdk-incoming-64bit --build=Release binaryen-master-64bit
source ./emsdk_env.sh
cd emscripten/incoming
EMCC_WASM_BACKEND=1 ./emcc --clear-cache ; EMCC_WASM_BACKEND=1 ./emcc tests/hello_world.c
```

on my 80-core Linux Mint box, which was unable to reproduce.

There are some extra `logging.debug()` prints in `tools/cache.py`. Does `EMCC_DEBUG=1` give any hints to which thread(s) are acquiring and not releasing them? Note that there's also a somewhat tricky `EM_EXCLUSIVE_CACHE_ACCESS` variable that is used, because if in a parent process child process chain the parent process acquires cache lock and then spawns a subprocess inside that lock, the subprocess will not be treated to having that lock.

In all our uses, when a parent process has a lock to cache and spawns a subprocess, the parent process will never proceed to access the cache while the child process is executing, but we practically always wait for the child process to finish first. That is why the EM_EXCLUSIVE_CACHE_ACCESS environment variable is used to let parent process to tell its child that it is allowed to behave as if it owns a lock to the cache as well.

**Comment by jgravelle-google** [comment]
Fun. @tlively ran into what I'm assuming is the same issue, and I wasn't able to reproduce it either. He was able to work around it by manually removing the lock file while it was deadlocked (which I do not, in general, recommend). It looked like at some point a thread creates it and never releases it.

Rereading the diff for #5074, it is certainly this line: https://github.com/kripken/emscripten/pull/5074/files#diff-f29b65c6972c99fc164bbb35f3d626bcR40
So at some point we're calling `acquire_cache_lock` twice on one thread, and only calling `release_cache_lock` once. That seems bad.

The question then is, why only sometimes? Or more precisely, why only certain machines?

**Comment by juj** [comment]
Yeah, this is quite curious. I'd recommend adding

```python
import traceback
print 'On thread ' + str(os.getpid()) + ':'
traceback.print_stack()
```

to the locations where the lock is acquired and released on the affected threads (e.g. https://github.com/kripken/emscripten/blob/master/tools/cache.py#L39). Perhaps that would give some clues.

**Comment by kripken** [comment]
Investigating this, it looks like if I have `BINARYEN_ROOT` in my `~/.emscripten` file, then the problem does not occur. But if I remove it, then the problem happens.

**Comment by sbc100** [comment]
I've noticed this too.  Some kind of attempt to recursively take the lock when building binaryen... which is why building binaryen yourself seems to make the problem go away.

**Comment by kripken** [comment]
Indeed, if I add a print in binaryen's port's get method, I see
````
INFO:root:generating system library: libc.bc... (this will be cached in "/home/alon/.emscripten_cache/wasm/libc.bc" for subsequent builds)
binaryen.get
binaryen.get
binaryen.get
binaryen.get
````
So we start to build libc. We presumably take a lock for the cache for that. Then as part of building libc, we call emcc and it wants to make sure the binaryen port is available - and all 4 cores trying to do that deadlock.

Possible fix in #5324.

**Comment by kripken** [comment]
Fixed by that PR. Although, I think I saw a similar symptom recently, but wasn't able to reproduce, hmm.

**Comment by jspanchu** [comment]
Started noticing this in our wasm64 build bots. It occurs almost everytime on the bots but I cannot reproduce locally.

```
cache:WARNING: Accessing the Emscripten cache at "/.../gitlab-kitware-sciviz-ci/.gitlab/emsdk/upstream/emscripten/cache" (for "sysroot/lib/wasm64-emscripten/libstubs.a") is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "/.../gitlab-kitware-sciviz-ci/.gitlab/emsdk/upstream/emscripten/cache/cache.lock" and try again. If this occurs deterministically, consider filing a bug.
```

More context is [here](https://open.cdash.org/viewBuildError.php?type=1&buildid=10029518)

**Comment by sbc100** [comment]
@jspanchu, it looks like the lock is eventually released and this is just a warning?  is that right?  i.e. the build eventually succeeds? 

Are you linking mulitple programs at the same time?  It seems likely it could just be normal lock contention between those link processes.

**Comment by sbc100** [comment]
Having said that I can't think it would have changed.  Perhaps that machine you are building on changed in its performance?  Or the level of parallelism in you build changed?  In any case, as long is that builds eventually succeed the warning can be ignored.

**Comment by jspanchu** [comment]
> @jspanchu, it looks like the lock is eventually released and this is just a warning? is that right? i.e. the build eventually succeeds?

Correct, build completes successfully.

> Are you linking mulitple programs at the same time? It seems likely it could just be normal lock contention between those link processes.

Yes, multiple targets are linked concurrently.

Okay, in that case, I think it's reasonable to ignore the warning. I'll check if we can avoid linking in parallel.

**Comment by sbc100** [comment]
> > @jspanchu, it looks like the lock is eventually released and this is just a warning? is that right? i.e. the build eventually succeeds?
> 
> Correct, build completes successfully.
> 
> > Are you linking mulitple programs at the same time? It seems likely it could just be normal lock contention between those link processes.
> 
> Yes, multiple targets are linked concurrently.
> 
> Okay, in that case, I think it's reasonable to ignore the warning. I'll check if we can avoid linking in parallel.

It should be harmless enough to link in parallel.  It just means that if one of the linker processes happens to be building a library it will pervent the other ones from making progress.

You can also use the `embuilder` tool to build the libraries ahead of time before doing any linking.

**Comment by jspanchu** [comment]
> You can also use the embuilder tool to build the libraries ahead of time before doing any linking.

This sounds neat.

Another reason I want to avoid linking in parallel is because sometimes the linker gets terminated due to OOM problems.
