### ISSUE TITLE
BINARYEN_ASYNC_COMPILATION with non-wasm-only builds

### ISSUE THREAD

**Issue by buu700** [kripken/emscripten#5333]
Is it possible for `BINARYEN_ASYNC_COMPILATION` to eventually be supported with e.g. `"BINARYEN_METHOD='native-wasm,asmjs'"`, or is there a hard limitation somewhere that minor refactoring alone won't be able to fix?

Related question: will it ever be possible to include an asm.js fallback without degrading everything to a compromise build? The performance of the "almost asm" doesn't matter much for my purposes as long as it behaves compatibly with the wasm and can be made to have as low a size impact as possible (`-Oz` optimisation level, etc.), but it'd be nice if it didn't reduce the wasm performance.

**Comment by kripken** [comment]
I think it could be done. I think the main and possibly only issue is that the main loop where we try methods until one succeeds (where we print "trying binaryen method"; i.e. the loop where we see if we need a fallback) is a synchronous one. It would need to be made async, so that we can wait for async wasm compilation to possibly fail, then try asm.js, etc.

**Comment by buu700** [comment]
Ah, cool, that sounds like it should be doable. I'll look for that string and see if I can get something working.

**Comment by dschuff** [comment]
@buu700 see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects for some reasons why you might not actually want to do this, and #5047 for some discussion. Would my proposal there be good for your use case? If not, do you mind telling us a little more about what you want to do?

**Comment by buu700** [comment]
Ah, thanks, that makes sense and will work for me. It'd be nice to avoid duplication of the JS glue and memory init data, but if an optimal combined build isn't nearly as simple as making a synchronous loop async then I'm okay with just letting gzip/brotli do what they can to address that until wasm support is more ubiquitous.

So basically the recommended pattern here would be something to this effect?

```
${preJS}

try {
    ${wasmBuild}
    await ${somePromiseThatWillResolveAfterWasmIsCompiled};
}
catch (_) {
    ${asmjsBuild}
}

${postJS}
```

There's still the concern of asm.js AOT compilation always blocking the main thread even when it isn't used, but I imagine that a `s/use asm//g` would neatly solve that while only adversely affecting the small subset of users running old versions of Firefox and a certain range of Edge versions.

**Comment by buu700** [comment]
Okay, well that pattern is working nicely for me — just updated the previously-asm.js-only [mceliece.js](https://github.com/cyph/mceliece.js), [ntru.js](https://github.com/cyph/ntru.js), [rlwe.js](https://github.com/cyph/rlwe.js), [sidh.js](https://github.com/cyph/sidh.js), [sphincs.js](https://github.com/cyph/sphincs.js), and [xkcd-passphrase](https://github.com/cyph/xkcd-passphrase) to use it with no issues — so I'll go ahead and close that new PR I'd started.

Only (minor) issue is that I didn't see anything that fit the place of `${somePromiseThatWillResolveAfterWasmIsCompiled}`, so as a temporary workaround I had to make a promise that checks the value of `Module.usingWasm` in a 50ms interval.

Anyway, thanks for the guidance here @dschuff!
