### ISSUE TITLE
'function signature mismatch ' error with Embind and Wasm

### ISSUE THREAD

**Issue by awtcode** [kripken/emscripten#5337]
I have the following code:

```
class Message
{
public:
                    std::string a;
                    std::string b;
                    std::string c;
                    std::string d;
};

EMSCRIPTEN_BINDINGS(message_class) {
    class_<:Message>("Message")
        .constructor()
        .property("address", &Message::a)
        .property("payload", &Message::b)
        .property("onSuccess", &Message::c)
        .property("onError", &Message::d);
}

void testFn(const Message& msg)
{
    val postTestMessage = val::global("postTestMessage");
    return;
}
```
However, when testFn exits, I get the following error stack:

```
 RuntimeError: function signature mismatch
    at dynCall_vi (<WASM>[69201]+15)
    at Object.Module.dynCall_vi
    at invoke_vi 
```

I am using incoming at 1.37.13 on Chrome 60 and Firefox 53 and I last updated around 2 days back. The features that I am using include Wasm, Embind and the Emterpreter. I would appreciate any pointers in debugging this. Thanks.

**Comment by kripken** [comment]
Does this work without wasm?

**Comment by awtcode** [comment]
Yes, this works with asm.js and was also working with incoming about 2 months back. This is a new issue that I've just seen a few days back.

What I see is that the wasm code does a 'call xxx' and after I step into it, I end up in invoke_vi and the 'function signature mismatch' error straight away. 

I also want to highlight that the val::global call completed successfully so I'm not sure if its because of some issue with destructors or a mismatch between the worker.js and wasm? I'm using proxy-to-worker by the way.

**Comment by kripken** [comment]
Interesting, if this worked on incoming 2 months back, it might be easiest to bisect this, to find which commit broke things.

**Comment by awtcode** [comment]
I reverted to https://github.com/kripken/emscripten/commit/68b42f58b1c37174ced17e0728ec3012553d084f as well as the tag 1.37.13, however, the 'function signature mismatched' error is still there. 

I also notice that this error occurs whenever I have an emscripten_log call in my code. Could this error be triggered by c++ interoperating with JS code?

**Comment by kripken** [comment]
Hmm, perhaps bisect further back? Finding the bad commit could help a lot here.

I don't think emscripten_log could be related, but it's possible it does somehow in a way that matters for embind, that I am not aware of.

Maybe `SAFE_HEAP` and `ASSERTIONS` find something?

**Comment by awtcode** [comment]
@kripken, I realized that the issue is not with embind but with using the whitelist for the emterpreter. We can create a crash using the below code and build parameters:

------------ helloworld.cpp-----------------------------------------
#include <iostream>
#include <string>
#include <emscripten.h>
using namespace std;
std::string test("ccc");
std::string test1("bbbb");
std::string test2(10, 'c');
 
void printhello()
{
    test = test1 + test2;
    std::string test3 = "asdfasdgs";
    //cout << "time_t:" << sizeof(time_t) << "int64_t:" << sizeof(int64_t) << "long:" << sizeof(long) << test3 << test << std::endl;
    cout << "HelloWorld" << std::endl;
}
int main()
{
    printhello();
    //emscripten_sleep_with_yield(1);
    return 0;
}

-------------------------Build Parameters-----------------------------------------------
emcc -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1  --proxy-to-worker -s DISABLE_EXCEPTION_CATCHING=0 -s INLINING_LIMIT=1 -s OUTLINING_LIMIT=20000 -s EMTERPRETIFY_WHITELIST=@U:/xxx/empterpreter_whitelist.json --bind -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=369098752 -s ASSERTIONS=2 -s WASM=1 -s DETERMINISTIC=1 -s BINARYEN_TRAP_MODE='js' -s SAFE_HEAP=1  -O2 -g -s ERROR_ON_UNDEFINED_SYMBOLS=1 -o AcFabricBackend.js helloworld.cpp

------------------------Output--------------------------------------------------------------
HelloWorld
AcFabricBackend.js:368 Invalid function pointer '28' called with signature 'iiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
AcFabricBackend.js:368 This pointer might make sense in another type signature: iiii: __ZNK10__cxxabiv123__fundamental_type_info9can_catchEPKNS_16__shim_type_infoERPv  iiiii: 0  iii: 0  ii: __ZNKSt3__220__time_get_c_storageIwE8__monthsEv  iiiiiid: undefined  iiiiiii: __ZNKSt3__28time_getIcNS_19istreambuf_iteratorIcNS_11char_traitsIcEEEEE11do_get_dateES4_S4_RNS_8ios_baseERjP2tm  iiiiiiii: undefined  i: undefined  iiiiiiiii: undefined  iiiiiiiiiii: undefined  iiiiiiiiiiii: undefined  iiiiiiiiiiiii: undefined  viiii: undefined  fiii: undefined  diii: undefined  viii: undefined  viiiii: undefined  iiiiid: undefined  vii: __ZNKSt3__210moneypunctIwLb1EE16do_negative_signEv  viiiiii: undefined  vi: __ZNSt3__211__stdoutbufIwED0Ev  viiiiiii: undefined  v: __ZNSt3__212_GLOBAL__N_14makeINS_9money_putIwNS_19ostreambuf_iteratorIwNS_11char_traitsIwEEEEEEjEERT_T0_  viiiiiiiiii: undefined  viiiiiiiiiiiiiii: undefined 
AcFabricBackend.js:365 28
AcFabricBackend.js:368 28
AcFabricBackend.js:368 warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
AcFabricBackend.js:368 exception thrown: abort(28) at Error
    at jsStackTrace (http://localhost:8080/AcFabricBackend.worker.js:1214:13)
    at stackTrace (http://localhost:8080/AcFabricBackend.worker.js:1231:12)
    at abort (http://localhost:8080/AcFabricBackend.worker.js:9912:44)
    at nullFunc_iiiiii (http://localhost:8080/AcFabricBackend.worker.js:7424:1497)
    at b220 (<WASM>[882]+17)
    at __ZNSt3__211__stdoutbufIwE4syncEv (<WASM>[287]+253)
    at dynCall_ii (<WASM>[1010]+19)
    at Object.Module.dynCall_ii (http://localhost:8080/AcFabricBackend.worker.js:7942:89)
    at invoke_ii (http://localhost:8080/AcFabricBackend.worker.js:7502:32)
    at __ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE5flushEv (<WASM>[220]+400)
AcFabricBackend.worker.js:237 Uncaught abort(28) at Error
    at jsStackTrace (http://localhost:8080/AcFabricBackend.worker.js:1214:13)
    at stackTrace (http://localhost:8080/AcFabricBackend.worker.js:1231:12)
    at abort (http://localhost:8080/AcFabricBackend.worker.js:9912:44)
    at nullFunc_iiiiii (http://localhost:8080/AcFabricBackend.worker.js:7424:1497)
    at b220 (<WASM>[882]+17)
    at __ZNSt3__211__stdoutbufIwE4syncEv (<WASM>[287]+253)
    at dynCall_ii (<WASM>[1010]+19)
    at Object.Module.dynCall_ii (http://localhost:8080/AcFabricBackend.worker.js:7942:89)
    at invoke_ii (http://localhost:8080/AcFabricBackend.worker.js:7502:32)
    at __ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE5flushEv (<WASM>[220]+400)
:8080/AcFabricBackend.worker.js:237 Uncaught abort(28) at Error
    at jsStackTrace (http://localhost:8080/AcFabricBackend.worker.js:1214:13)
    at stackTrace (http://localhost:8080/AcFabricBackend.worker.js:1231:12)
    at abort (http://localhost:8080/AcFabricBackend.worker.js:9912:44)
    at nullFunc_iiiiii (http://localhost:8080/AcFabricBackend.worker.js:7424:1497)
    at b220 (<WASM>[882]+17)
    at __ZNSt3__211__stdoutbufIwE4syncEv (<WASM>[287]+253)
    at dynCall_ii (<WASM>[1010]+19)
    at Object.Module.dynCall_ii (http://localhost:8080/AcFabricBackend.worker.js:7942:89)
    at invoke_ii (http://localhost:8080/AcFabricBackend.worker.js:7502:32)
    at __ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE5flushEv (<WASM>[220]+400)

**Comment by juj** [comment]
Does it work without `--proxy-to-worker`? Can you produce a self-contained test case and build command line to verify?

**Comment by awtcode** [comment]
@kripken and @juj , after more testing, I believe the issue is not with embind but rather the Emterpreter whitelist. I was able to come up with a simple 'hello world' test case that shows another exception at runtime. This is the same code that I shared with the both of you via email.

This is my code:
 
#include <iostream>
#include <string>
#include <emscripten.h>
using namespace std;
std::string test("ccc");
std::string test1("bbbb");
std::string test2(10, 'c');
 
void printhello()
{
    test = test1 + test2;
    std::string test3 = "asdfasdgs";
    //cout << "time_t:" << sizeof(time_t) << "int64_t:" << sizeof(int64_t) << "long:" << sizeof(long) << test3 << test << std::endl;
    cout << "HelloWorld" << std::endl;
}
int main()
{
    printhello();
    //emscripten_sleep_with_yield(1);
    return 0;
}

These are the build parameters:
emcc -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 -s EMTERPRETIFY_WHITELIST="['_main']" --proxy-to-worker -s DISABLE_EXCEPTION_CATCHING=0 -s INLINING_LIMIT=1 -s OUTLINING_LIMIT=20000 --bind -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=369098752 -s ASSERTIONS=2 -s WASM=1 -s DETERMINISTIC=1 -s BINARYEN_TRAP_MODE='js' -s SAFE_HEAP=1  -O2 -g -s ERROR_ON_UNDEFINED_SYMBOLS=1 -o helloworld.js helloworld.cpp

This will throw up the following error:
   at jsStackTrace 
    at stackTrace 
    at abort 
    at nullFunc_iiiiii 
    at b220 (<WASM>[882]+17)
    at __ZNSt3__211__stdoutbufIwE4syncEv (<WASM>[287]+253)
    at dynCall_ii (<WASM>[1010]+19)
    at Object.Module.dynCall_ii 
    at invoke_ii 
    at __ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE5flushEv (<WASM>[220]+400)

**Comment by kripken** [comment]
As discussed on email, this should be fixed by https://github.com/WebAssembly/binaryen/commit/7bc2ed70de137aa6615fcd5d0e1f3e88f008a738

**Comment by waywardmonkeys** [comment]
Can this be closed then?
