### ISSUE TITLE
Workaround for crossplatform loading of .wasm files

### ISSUE THREAD

**Issue by zandaqo** [kripken/emscripten#5342]
Hi guys,

I'm playing with compiling C++ libraries to WASM modules over [here](https://github.com/zandaqo/iswasmfast), it's been great so far, but [the issue](https://github.com/kripken/emscripten/issues/4542) with loading .wasm from a different directory kills any attempt of making an npm package that can seamlessly work in both node and browsers. So I have two questions here: 

1. Is there some accepted workaround to fix this?
2. How can I manually load the .wasm file and feed it to the module? Just setting `Module.wasmBinary` doesn't seem to work:

```javascript
const fs = require('fs');
const wasm = require('./wasm.js');
wasm.wasmBinary = fs.readFileSync('./wasm.wasm');
```

**Comment by zandaqo** [comment]
Also, inlining wasm would probably be the simplest solution, can emcc do it?

**Comment by kripken** [comment]
Yeah, this is an annoying problem. There is a PR open for embedding it, #5296, which is one workaround. More discussion in #5104.

**Comment by zandaqo** [comment]
@kripken I guess I better wait for embedding then. Thank you, I'll close this issue in favor of #5104 then.
