### ISSUE TITLE
emcc does not compile when including <threads.h>

### ISSUE THREAD

**Issue by etienne02** [kripken/emscripten#5343]
Just by adding "#include <threads.h>", I have theses errors
 
In file included from thread.c:1:
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:60:14: error: unknown type name 'mtx_t'
int mtx_init(mtx_t *, int);
             ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:61:18: error: unknown type name 'mtx_t'
void mtx_destroy(mtx_t *);
                 ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:63:14: error: unknown type name 'mtx_t'
int mtx_lock(mtx_t *);
             ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:64:19: error: unknown type name 'mtx_t'
int mtx_timedlock(mtx_t *__restrict, const struct timespec *__restrict);
                  ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:65:17: error: unknown type name 'mtx_t'
int mtx_trylock(mtx_t *);
                ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:66:16: error: unknown type name 'mtx_t'
int mtx_unlock(mtx_t *);
               ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:68:14: error: unknown type name 'cnd_t'
int cnd_init(cnd_t *);
             ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:69:18: error: unknown type name 'cnd_t'
void cnd_destroy(cnd_t *);
                 ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:71:19: error: unknown type name 'cnd_t'
int cnd_broadcast(cnd_t *);
                  ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:72:16: error: unknown type name 'cnd_t'
int cnd_signal(cnd_t *);
               ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:74:19: error: unknown type name 'cnd_t'
int cnd_timedwait(cnd_t *__restrict, mtx_t *__restrict, const struct timespec *__restrict);
                  ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:74:38: error: unknown type name 'mtx_t'
int cnd_timedwait(cnd_t *__restrict, mtx_t *__restrict, const struct timespec *__restrict);
                                     ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:75:14: error: unknown type name 'cnd_t'
int cnd_wait(cnd_t *, mtx_t *);
             ^
~/emsdk-portable/emscripten/tag-1.37.15/system/include/libc/threads.h:75:23: error: unknown type name 'mtx_t'
int cnd_wait(cnd_t *, mtx_t *);

It's because the file define 
#define __NEED_cnd_t
#define __NEED_mtx_t
instead of
#define __NEED_pthread_cond_t
#define __NEED_pthread_mutex_t
to include mutex and conditions.

**Comment by juj** [comment]
Thanks! Fixed in https://github.com/kripken/emscripten/commit/7ddb47936292625f525e1cbebf9774aed9c31173
