### ISSUE TITLE
When packaging assets with '@' in the directory name and using '@' for redirecting, escaping doesn't work

### ISSUE THREAD

**Issue by thothonegan** [kripken/emscripten#5377]
When packaging a preload-file with @ in its name, and also using @ to redirect, escaping doesn't work properly. In the sample test case below, I package `res@master/test.txt` by passing `res@@master/test.txt@test.txt` to map it to the root, but it errors. Looking at the packager, it does the string replacement for `@@` before it splits up the source and destination, so it picks up the post-escape path.

Simple test case can be found in the given git repo : just run `make`:
https://github.com/thothonegan/emscripten-bug-packaging-with-at

emcc -v
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.9
clang version 4.0.0  (emscripten 1.37.9 : 1.37.9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/thothonegan/.local/emsdk_portable/clang/e1.37.9_64bit
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/6
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by juj** [comment]
Any chance you could try adapting a new test case to https://github.com/kripken/emscripten/blob/master/tests/test_browser.py#L162 to showcase the problem?

Btw, latest Emscripten SDK is 1.37.16. If you're unable to locate it with `emsdk update`, it could be due to https://groups.google.com/forum/#!topic/emscripten-discuss/bKCQxN6Q76Y

**Comment by thothonegan** [comment]
Thanks, updated my emscripten. Was wondering why it stopped at 9.

Added `("directory@@other/file.txt@file.txt", "file.txt")` to the list of test cases and it caused the tests to fail the same way : if needed I can make a pull request or whatever with the changed file.

**Comment by thothonegan** [comment]
For completion, another useful one could be `("file@@a.txt@file@@b.txt", "file@b.txt")` which maps a filename with @s straight over, escapes on both source/destination. [also fails currently]

**Comment by thothonegan** [comment]
Closing due to merge.
