### ISSUE TITLE
Publish to emsdk again?

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#5398]
The latest build available on emsdk is [1.37.12](https://github.com/kripken/emscripten/releases/tag/1.37.12), which is from May 1. Could emsdk be updated with [1.37.16](https://github.com/kripken/emscripten/releases/tag/1.37.16), the latest release? I'm particularly interested in picking up the fix for #5161.

Edit: I didn't know you had to run `./emsdk update-tags` before running `./emsdk list`. I think that fixes it but I'm not sure if I did it correctly. We're using `master` from https://github.com/juj/emsdk directly but running `./emsdk update-tags` leaves the staging area dirty afterwards (binaryen-tags.txt and emscripten-tags.txt are modified). Is that expected? Or does that mean the SDK is still out of date?

**Comment by poiru** [comment]
@juj Maybe the tags in the emsdk repo could be updated whenever there is an Emscripten release? That would make it easier for projects that use the emsdk repo as a submodule.

**Comment by evanw** [comment]
Closing this because we were able to work around this (we used a hard-reset of the repo as a post process).

**Comment by juj** [comment]
The latest build that is available via emsdk should be 1.37.16. If you are not seeing that, you may need to run `emsdk update`, or just `emsdk update-tags` if you don't want to update emsdk script itself.
