### ISSUE TITLE
RuntimeError: integer overflow when convert double to int in wasm mode

### ISSUE THREAD

**Issue by ElijahGr** [kripken/emscripten#5404]
(int)double - may produce RuntimeError: integer overflow 
I reproduce it with this example : file 1.cpp

```c
#include <stdio.h>
void test(double val)
{
  int i = (int) val;
  printf("test %f %d\n", val, i);
}
int main()
{
  test(1); // works fine
  test(70203888290798.0); //produce RuntimeError: integer overflow 
}
```
I compiled it with : `emcc 1.cpp -o 1.html -s WASM=1`
In asm.js mode it works as expected

**Comment by juj** [comment]
This is by design. Try building with `-s BINARYEN_TRAP_MODE=clamp` or `-s BINARYEN_TRAP_MODE=js`. See https://github.com/kripken/emscripten/blob/incoming/src/settings.js#L705.

**Comment by ElijahGr** [comment]
-s BINARYEN_TRAP_MODE='clamp' solve the problem thank you. 
this option may performance penalty on integer operations.
what reason to mix integer division and floating point conversion in one option.

**Comment by kripken** [comment]
There was a discussion on that in #4625. We can add separate options for each if we see cases where it matters.
