### ISSUE TITLE
webassembly doc - src/js/wasm.js-post.js in Binaryen doesn't have integrateWasmJS

### ISSUE THREAD

**Issue by runn1ng** [kripken/emscripten#5405]
Webassembly docs say

> For more details, see src/js/wasm.js-post.js in the Binaryen repo. The function integrateWasmJS is where all the integration between JavaScript and WebAssembly happens.

That file doesn't have integrateWasmJS function, and neither does the whole binaryen repo.

**Comment by dschuff** [comment]
That's probably just outdated. Which doc says that?

**Comment by runn1ng** [comment]
Here

https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods

The first result on "webassembly emscripten" on google :)

**Comment by kripken** [comment]
Thanks, updated.
