### ISSUE TITLE
WASM memory section usage 

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [kripken/emscripten#5410]
I have a question regarding wasm memory section and how emscripten uses it. My understanding was that the memory section was used for 2 purposes-
1. Building the ‘stack’(something like the stack allocated in heap for javascript backend)
2. For dynamic memory allocation
 
From a wasm file I created which had a malloc() instruction in it, the main memory related imports which I see are ‘STACKTOP’ and ‘enlargeMemory’. I see that malloc() pulls in a dlmalloc implementation which uses sbrk(). The only way Loads/Store will work in this case is if malloc() returns back an offset in the wasm memory section. Assuming this is the case, my questions are
1.  Where does the stacktop begin? When I create a wasm file using llvm+s2wasm, it doesn’t have a stacktop and the stack seem to be growing ‘top-down’(say first value stored at addr(16) and next addr(8)). This seem to suggest that STACKTOP should be the maximum size of wasm memory section. Is that a correct assumption?
2.  What offset does malloc() return for the very first call? This question is to understand if emscripten uses parts of the wasm memory for any other purposes. Is there a fixed starting point where dynamic memory allocation in ‘heap’ begins?

**Comment by DeepakRajendrakumaran** [comment]
Sorry to bump this ..but can someone please point me to documentation explaining the above?

**Comment by kripken** [comment]
The basic model is a pointer is an offset in memory. So a pointer of 1024 means memory location 1024. Importantly, that means a pointer is just an integer.

All the other details are not well-documented, but also not intended to be depended upon. Emscripten may emit a stack that grows up (asm.js, asm2wasm) or down (wasm-backend), for example. In general memory is used for the stack, for malloc, and for "static" allocations - global constants that the compiler can place in a fixed location in memory, avoiding a runtime malloc call, for example. To see this more in detail, you can generate a small program (with -g so the JS is readable) and read the JS, look for STACKTOP (the stack), STATICTOP (static allocations), DYNAMICTOP (mallocs), etc. But again, this is not meant to be depended upon, it's internal details, and could change depending on compilation mode or what compiler backend is used etc.

**Comment by Krovatkin** [comment]
Hi @Kripken,

Thank you very much for your reply! 

@DeepakRajendrakumaran and I are actually implementing another WASM runtime (not JS-based) and we would like to be able run C code compiled (with Emscripten) to WebAssembly. It seems our runtime does need to be aware of the layout of `(import memory)` Emscripten is using, so our runtime can set `STACKTOP`, `DYNAMICTOP_PTR` and implement the following imports properly. 
**Could you please point us to the parts of the code that a) decide on the memory layout b) provide the JS implementation of the imports below?**

```lisp
  (import "env" "DYNAMICTOP_PTR" (global (;0;) i32))
  (import "env" "tempDoublePtr" (global (;1;) i32))
  (import "env" "ABORT" (global (;2;) i32))
  (import "env" "STACKTOP" (global (;3;) i32))
  (import "env" "STACK_MAX" (global (;4;) i32))
  ;;... more stuff
  (import "env" "enlargeMemory" (func (;0;) (type 2)))
  (import "env" "getTotalMemory" (func (;1;) (type 2)))
  (import "env" "abortOnCannotGrowMemory" (func (;2;) (type 2)))
  (import "env" "abortStackOverflow" (func (;3;) (type 3)))
  (import "env" "nullFunc_ii" (func (;4;) (type 3)))
  (import "env" "nullFunc_iiii" (func (;5;) (type 3)))
  (import "env" "___lock" (func (;6;) (type 3)))
  (import "env" "___syscall6" (func (;7;) (type 4)))
  (import "env" "___setErrNo" (func (;8;) (type 3)))
  (import "env" "___syscall140" (func (;9;) (type 4)))
  (import "env" "_emscripten_memcpy_big" (func (;10;) (type 0)))
  (import "env" "___syscall54" (func (;11;) (type 4)))
  (import "env" "___unlock" (func (;12;) (type 3)))
  (import "env" "___syscall146" (func (;13;) (type 4)))
  (import "env" "memory" (memory (;0;) 256 256))
  (import "env" "table" (table (;0;) 10 10 anyfunc))
  (import "env" "memoryBase" (global (;7;) i32))
  (import "env" "tableBase" (global (;8;) i32))
```

**Comment by kripken** [comment]
Yes, if you're implementing your own runtime, you'll need to implement those imports. As I mentioned, the best thing is probably to build a small file and read the JS (look for the variables I mentioned, to find the relevant code).

(Alternatively, you can read `src/preamble.js` and `src/jsifier.js`, most of the code comes from them, but I think that would be harder.)

If you have suggestions for how to improve those imports, we may be able to refactor them to make creating new runtimes easier. That hasn't been a focus so far because the use case hasn't come up, but now with wasm perhaps it is more relevant. There has been an idea to create a minimal modular runtime that emscripten and others would use, for example, but no work has been done on that yet.

**Comment by DeepakRajendrakumaran** [comment]
@kripken Thanks for the explanation and the pointers. It would be great considering the possible use cases to have an option to provide 'self-dependent' wasm module which can be run with minimal  or even no js code. But since that doesn't seem to be in the critical path at this moment, we are trying to see if we can make it work with the current model using the suggestions you gave.

I'm closing this issue as the original questions have been answered.
