### ISSUE TITLE
WASM optimizer bug

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#5429]
We recently hit a bug in emscripten's WebAssembly optimizer. Our code is mis-compiled to WebAssembly when the -O3 flag is present. A self-contained minimized reproduction is here: https://gist.github.com/evanw/57e2c3f40bc8789951b4926fcce8e1e8. Run "make" and compare the console output of asmjs.html and wasm.html. The asm.js code reports 1 (correct) while the WebAssembly code reports 0 (incorrect). I believe this is a bug in emscripten and not the browser because both Chrome and Firefox report 0. This reproduces with both the latest SDK version (1.37.16) and with incoming.

**Comment by kripken** [comment]
Thanks, nice testcase. Fix in https://github.com/WebAssembly/binaryen/pull/1116/commits/56e49752b4258b89660825f2970a7e55067d7122 , included in https://github.com/WebAssembly/binaryen/pull/1116

**Comment by evanw** [comment]
I just tried out the latest emscripten release (1.37.19) but it looks like this bug is still there.

**Comment by kripken** [comment]
Yes, you need to use binaryen master to get it - we haven't updated the binaryen tag in emscripten as there are a few important PRs that are close to land there. I'll push on those more to try to get this done asap.

**Comment by juj** [comment]
If you want to get to latest Binaryen from source (instead of latest tagged Binaryen) with emsdk, you can run

```bash
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install --build=Release sdk-incoming-64bit binaryen-master-64bit
./emsdk activate --build=Release sdk-incoming-64bit binaryen-master-64bit
source ./emsdk_env.sh --build=Release
```

**Comment by evanw** [comment]
Thanks! We unfortunately can't use master/incoming builds. We'd like to enable WebAssembly in production and our users rely on our product every day to get their work done. We need make sure we're using a stable version of the compiler to build our code so that we can guarantee stability for our users.

**Comment by kripken** [comment]
Yeah, that makes sense. The PRs I mentioned as going to land soon are in fact going to give us a much better level of stability (they fix a lot of fuzz bugs that were found). So if you want stability it's best to wait for that. Should be just a few days.

**Comment by kripken** [comment]
incoming branch has been updated with latest binaryen master.

**Comment by evanw** [comment]
The latest release (1.37.20) fixes this. Thank you so much!
