### ISSUE TITLE
My app is buggy when using optimization flags

### ISSUE THREAD

**Issue by eilgin** [kripken/emscripten#543]
I'm trying to port a little compiler i've made (for fun). However, this application deals with files and directories using boost in order to deal with the filesystem. Following the tutorial, i've tried to use emcc in minGW (win7) : it works until i found that python doesn't work in minGW when you launch emconfigure (os.path uses code that's not part of win32 app).
From there, i've rebuild all the stuff under linux (VirtualBox/ubuntu 11.10). Then, i've made a little Makefile (derived from my initial visual project 2010 solution) which compiles every object files one by one and compiles them to javascript with the folowing cmd :
<code>emcc object1.o object2.o ... libs/libboost_filesystem.a libs/libboost_system.a  -o vm_translator.js</code>

I need 2 static libs in order to use boost::filesystem. Anyway, it compiles "fine" except that i've got this warning :  
<pre>
.ll contains floating-point values with more than 64 bits.
Faking values for them. If they are used, this will almost certainly break horribly!
</pre>

When i launch the JS file (with node), i've got this error :
<pre>
vm_translator.js:9069
var $call=__ZN5boost6system19get_system_categoryEv();
                 ^
TypeError: undefined is not a function
</pre>

<del>
So, it seems that "__ZN5boost6system19get_system_categoryEv" function body (and many more) wasn't included during the compilation process.

My question is : how do we add support for third-party libs ? 
</del>

PS : i'm not using the mt (multi-threading) libs.
Thanks.

<strong>EDIT : </strong>
Well, i used static libs compiled with gcc ! I took the source from boost, compiles it with clang and creating the 2 static libs with llvm-ar. Now it works fine. The thing is : my JS file is huge : > 5 MB with the closure compiler OR small (~= 600 KB) but buggy when using optimisation flag (some functions throw exceptions in the code).

**Comment by juj** [comment]
Closing as old/resolved, this reads like there might have been an issue with closure+opt, but no STR. Feel free to reopen with a repro, or just open a new item if issues still persist!
