### ISSUE TITLE
LLVM compilation results in errors with c++ libraries - cmath etc

### ISSUE THREAD

**Issue by akshay-hazari** [kripken/emscripten#5435]
Trying to compile results in errors for c++ libraries like cmath etc with emscripten 

```
emscripten/1.37.16/system/include/libcxx/cmath:311:9: error: no member named 'isfinite' in the global
      namespace
/cmath:310:9: error: no member named 'fpclassify'  in the global
      namespace
no member named 'isinf'
no member named 'isnan'
no member named 'isnormal'
no member named 'isgreater' etc ...

```

I've been running the cmake command like this.
`cmake -DOpenCV_DIR="/usr/share/OpenCV" -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.16/cmake/Modules/Platform/Emscripten.cmake . && make`

Here's the equivalent command `./emcc -std=c++11 -O3 -I.. ~/DLIB/dlib-19.4/dlib/all/source.cpp  -I/home/akshay/DLIB/dlib-19.4 -I/usr/include/X11/ -lpthread -lX11 -lopencv_imgcodecs  -o webca.js  ~/DLIB/dlib-19.4/examples/webcam_face_pose_ex.cpp -ldlib \`\` pkg-config opencv --cflags --libs\`

` which creates a javascript only to find several functions missing when running with nodejs.

Have been trying to work with compiling dlib facial landmarks detection to be converted to javascript. 
It seems dlib uses c++ 4.8.

Here's my CMakeLists.txt file:

```
 cmake_minimum_required(VERSION 3.5.1)
project(DLIB)
SET(CMAKE_BUILD_TYPE_INIT "Release")
set(CMAKE_CXX_STANDARD 11)
if (${CMAKE_SYSTEM_NAME} MATCHES "Emscripten")
    set(CMAKE_C_COMPILER "emcc")
    endif ()

if(NOT DEFINED OpenCV_PREFIX)
  set(OpenCV_PREFIX ${CMAKE_INSTALL_PREFIX})
  endif()
    
set(CMAKE_VERBOSE_MAKEFILE on)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/build.emscripten)

set(DLIB_SRC "/home/akshay/DLIB/dlib-19.4/examples/webcam_face_pose_ex.cpp")
add_library(DLIB_static ${DLIB_SRC})
set(OpenCV_PREFIX /usr/share/OpenCV/OpenCVConfig.cmake)

include_directories(/usr/include/X11  /home/akshay/DLIB/dlib-19.4 /home/akshay/DLIB/dlib-19.4/dlib/all/source.cpp)

set_target_properties(DLIB_static PROPERTIES LINK_FLAGS "-s DEMANGLE_SUPPORT=1 --preload-file assets --bind")
find_package(PkgConfig REQUIRED)

find_package(OpenCV REQUIRED  
    PATHS ${OpenCV_PREFIX}/lib/cmake/
    ${OpenCV_PREFIX}/share/OpenCV/
      NO_DEFAULT_PATH)
find_library(OpenCV REQUIRED     PATHS ${OpenCV_PREFIX}/lib/cmake/
    ${OpenCV_PREFIX}/share/OpenCV/
      NO_DEFAULT_PATH)

set(CMAKE_REQUIRED_FLAGS "-std=c++11 -xc++ -O3 -lpthread -lX11 -lopencv_imgcodecs -ldlib \`pkg-config opencv --cflags --libs\`")

#file(GLOB_RECURSE CORE_HDR src/.h)
#file(GLOB_RECURSE CORE_SRC src/.cpp)

add_definitions("-s DEMANGLE_SUPPORT=1 --preload-file ${CMAKE_SOURCE_DIR}/assets --bind")
add_executable(DLIB /home/akshay/DLIB/dlib-19.4/examples/webcam_face_pose_ex.cpp)
```

Any hints on this will be helpful.

**Comment by kripken** [comment]
That might have been fixed by the recent libc++ upgrade in 1.37.18.

**Comment by akshay-hazari** [comment]
How can I upgrade to that specific version of emscripten 1.37.18? Would be great if you could help.

**Comment by akshay-hazari** [comment]
@kripken  Will verify this https://github.com/kripken/emscripten/releases/tag/1.37.18 . Thanks

**Comment by akshay-hazari** [comment]
I get the same errors with 1.37.18 as well. 

```
emscripten-1.37.18/system/include/libcxx/cmath:315:9: error: no member named 'isfinite' in the global namespace
using ::isfinite;
      ~~^
system/include/libcxx/cmath:316:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
emscripten-1.37.18/system/include/libcxx/cmath:317:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
emscripten-1.37.18/system/include/libcxx/cmath:318:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
.
.
.
15 warnings and 20 errors generated.
```

**Comment by juj** [comment]
The issue does not occur in a small test case at least:

```bash
clb@x10dax ~/emsdk/emscripten/incoming $ cat cmath.cpp
#include <cmath>
#include <iostream>

int main()
{
  std::cout << "1 is finite? " << std::isfinite(1.f) << std::endl;
}
clb@x10dax ~/emsdk/emscripten/incoming $ ./em++ cmath.cpp -o a.js
clb@x10dax ~/emsdk/emscripten/incoming $ node a.js
1 is finite? 1
```

This may be due to some combination of includes in your OpenCV project? Try reducing it down to a small test case that build ok natively, but fails with Emscripten.

**Comment by akshay-hazari** [comment]
@juj @kripken 

The simple examples above run ok. 

The earlier errors are gone with the new 1.37.18 SDK. There are some new ones though.

```
/usr/include/stdio.h:472:7: error: unknown type name '__gnuc_va_list'
                    _G_va_list __arg)
                    ^
/usr/include/_G_config.h:46:20: note: expanded from macro '_G_va_list'
#define _G_va_list __gnuc_va_list

```

These may not be related to the earlier errors. If any one finds some solution on something similar will be great.
I guess it may be specific to opencv and dlib though.

**Comment by juj** [comment]
The code should probably be using just `va_list` instead of `__gnuc_va_list` or `_G_va_list`, those two sound like some kind of GCC specific extensions that Clang might not have.

Also, the headers are being included from `/usr/include/` directory, which is wrong and will not work, since headers in that directory are for building native code and not for cross-compiling. You'll need to remove OpenCV build system from passing `-I /usr/include/` to the build.

**Comment by akshay-hazari** [comment]
@juj  Hey thanks for replying. How can I make it do that? I have -DOpenCV_DIR="/usr/share/OpenCV" , so how do I make it use emscripten/1.37.18/system/include/libcxx

```
cmake -DOpenCV_DIR="/usr/share/OpenCV" -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/cmake/Modules/Platform/Emscripten.cmake . && make
```

**Comment by juj** [comment]
To remove `-I /usr/include/`, if you don't add that anywhere yourself, you will likely need to look into OpenCV's CMake scripts and figure out where it is adding the bad include.

Emscripten adds `-isystem$EMSCRIPTEN/system/include` automatically at https://github.com/kripken/emscripten/blob/master/tools/shared.py#L959 when compiling C++, so there is no need to manually add those in.

**Comment by akshay-hazari** [comment]
Changing the CMakeLists file in my PC where OpenCV is located /usr/share/OpenCV results in, it referring to opencv2/core/core.hpp and opencv2/core/types_c.h which need the string.h and math.h and they result in a lot many errors when exposed to only the libcxx libraries.

Errors like 
```
In file included from /home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/opencv2/core/types_c.h:94:
/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/math.h:640:39: error: use of undeclared identifier 'fabsf'
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
                                      ^
/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/math.h:644:40: error: use of undeclared identifier 'fabs'; did you
      mean 'abs'?
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
                                       ^
/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/math.h:644:1: note: 'abs' declared here
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/math.h:648:45: error: use of undeclared identifier 'fabsl'
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}

```
and 
```
/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/string.h:74:64: error: use of undeclared identifier 'strchr'
char* __libcpp_strchr(const char* __s, int __c) {return (char*)strchr(__s, __c);}
                                                               ^
/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/string.h:81:75: error: use of undeclared identifier 'strpbrk'
char* __libcpp_strpbrk(const char* __s1, const char* __s2) {return (char*)strpbrk(__s1, __s2);}
                                                                          ^
/home/akshay/Downloads/emsdk-portable/emscripten/1.37.18/system/include/libcxx/string.h:88:65: error: use of undeclared identifier 'strrchr'; did
      you mean 'strchr'?
char* __libcpp_strrchr(const char* __s, int __c) {return (char*)strrchr(__s, __c);}
```

```

**Comment by akshay-hazari** [comment]
Is this the js version of OpenCV built using emscripten you were saying about. https://github.com/ucisysarch/opencvjs 

Here I wish to convert dlib examples which use OpenCV. If I build OpenCV to js. The dlib examples need to refer to the js version of OpenCV. 
I don't know much.
How do I go about it.

**Comment by juj** [comment]
It was this one: https://github.com/kakukogou/opencv/tree/opencvjs, though now I see that has not been updated in a while. Perhaps the one you linked is newer.

> Here I wish to convert dlib examples which use OpenCV. If I build OpenCV to js. The dlib examples need to refer to the js version of OpenCV.

Sorry, I am not familiar with dlib, perhaps someone else here knows more about that. The general approach is to build dlib with Emscripten as well, and link it to Emscripten compiled OpenCV, assuming dlib is using OpenCV as a library.

**Comment by akshay-hazari** [comment]
@juj It builds successfully while specifying the new build for OpenCV specifically meant for Emscripten where it doesn't link system libraries. But running it results in the following. And it creates a webcam_face_pose_ex.cpp.o  file which I am not able to use.

It gives some warnings like this.

```
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
warning: unresolved symbol: _ZNK4dlib6base646decodeERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EE
warning: unresolved symbol: _ZNK4dlib11base_window9is_closedEv
warning: unresolved symbol: _ZNK4dlib13image_display22get_image_display_rectEv
warning: unresolved symbol: _ZN4dlib6base64C1Ev
warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_210set_streamERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEE
warning: unresolved symbol: _ZN4dlib17popup_menu_region7disableEv
warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_26decodeEjj
warning: unresolved symbol: _ZN9_IplImageC1ERKN2cv3MatE
warning: unresolved symbol: _ZN2cv8fastFreeEPv
warning: unresolved symbol: _ZN4dlib12image_windowC1Ev
warning: unresolved symbol: _ZN4dlib21draw_sunken_rectangleERKNS_6canvasERKNS_9rectangleEh
warning: unresolved symbol: _ZN4dlib12image_window13clear_overlayEv
warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_2D1Ev
warning: unresolved symbol: _ZN4dlib17scrollable_region19set_total_rect_sizeEmm
warning: unresolved symbol: _ZN2cv3Mat8copySizeERKS0_
``` 

These are similar warnings I get when I try to run it like this.  
```
./em++ -std=c++11 -O3 -I.. ~/DLIB/dlib-19.4/dlib/all/source.cpp  -I/home/akshay/DLIB/dlib-19.4 -I/usr/include/X11/ -lpthread -lX11 -lopencv_imgcodecs  -o webca.js  ~/DLIB/dlib-19.4/examples/webcam_face_pose_ex.cpp -ldlib  `pkg-config opencv --cflags --libs`

```
followed by 
node webca.js
which doesn't run.

**Comment by juj** [comment]
Those look like issues in the OpenCV project specifically, and there is no Emscripten bug that I can find, so it looks like this issue can be closed. Perhaps asking at emscripten-discuss mailing list or one of OpenCV mailing list might hit a set of people who have used OpenCV with Emscripten before?

**Comment by akshay-hazari** [comment]
@juj  Hey, thanks for helping out. Will try and look it up somewhere in OpenCV project.

**Comment by akshay-hazari** [comment]
@juj  Hi. Is there something with this and does it give me some clue. When running ./webcam_face_pose_ex.cpp.o (compiled code) gives an error like
error: Unknown attribute kind (52) (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.8.0')

**Comment by juj** [comment]
This suggests a miscompilation - The file was compiled with different compiler, or version of the same compiler, that is being read with.

Try running `emcc -v` to see which version of LLVM Emscripten has. LLVM 3.8 reads like your system compiler, that should not be used here.

**Comment by akshay-hazari** [comment]
emcc -v reads as 
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.19
clang version 4.0.0 (https://github.com/kripken/emscripten-fastcomp-clang.git f156a4f42ff4b0b72ef4839dfda2519b12f17b1d) (https://github.com/kripken/emscripten-fastcomp.git 51ce48a2c0599ef81b2830b72ff5b86b3cec6db3) (emscripten 1.37.19 : 1.37.19)
```
Do I need to have LLVM 4.0 then . Is there a way I could resolve it.

**Comment by juj** [comment]
The message says that you already have `LLVM 4.0` as part of Emscripten toolchain.

The issue is hinted to at the `Reader: 'LLVM 3.8.0'` field. Likely the system Clang compiler is what is reporting 3.8.0.

The bug is not that these version numbers are different. You do not want to downgrade Emscripten's LLVM to 3.8.0 or upgrade native system compiler to LLVM 4.0.0.

The bug is that object code files first compiled by Emscripten are for some reason being fed to native system compiler. The native system compiler does not understand a thing about Emscripten compiled code files, and these should not mix. Code object files compiled with Emscripten (= Emscripten's build of LLVM) should only be read by Emscripten, and code object files compiled with native system Clang should only be read by native system Clang. Mixing is not allowed, since this is cross compilation to two completely different target platforms: Emscripten produces asm.js/wasm, native compiler produces x86/x64.

**Comment by juj** [comment]
To figure out the root cause, which is likely due a misconfiguration of the OpenCV build system that is mixing the use of these two compilers; Given that OpenCV is using CMake, you can try `make VERBOSE=1` during the build to have it output exact command lines that it is passing, and see where it is calling the native system compiler, and then work towards a fix. Search for something like `"cmake verbose output"` at google for how to further debug CMake operation.

**Comment by akshay-hazari** [comment]
Had built OpenCV using em++ and emcc . Removing SIMD support and a lot of other things required.
```
cmake -DEMSCRIPTEN=1 -D CMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/home/akshay/Downloads/emsdk-portable/emscripten/incoming/em++ -DCMAKE_TOOLCHAIN_FILE=/home/akshay/Downloads/emsdk-portable/emscripten/incoming/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_C_COMPILER=/home/akshay/Downloads/emsdk-portable/emscripten/incoming/emcc  -D CMAKE_INSTALL_PREFIX=/home/akshay/OPENCV1/INSTALL -DWITH_1394=OFF ..
```

Then used Verbose to check if it was using the native compiler.
`make -j7 VERBOSE=1 EMCC_DEBUG=1`

It doesn't use native c, c++ . 

But it gives the same error 
`error: Unknown attribute kind (52) (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.8.0')`

**Comment by akshay-hazari** [comment]
Had to include streambuf in iterator in libcxx
`#include "streambuf"`
similarly had to include in __string
`#include "iosfwd"`
`#include "cstring"`

It still gave error for `no member named 'cerr' and 'endl' in namespace 'std'`

**Comment by akshay-hazari** [comment]
With another update to 1.37.21 The errors are gone.

But this error: Unknown attribute kind (52) (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.8.0') still persists. Where Verbose doesn't show native libraries being used.

**Comment by Rtoax** [comment]
> @juj It builds successfully while specifying the new build for OpenCV specifically meant for Emscripten where it doesn't link system libraries. But running it results in the following. And it creates a webcam_face_pose_ex.cpp.o file which I am not able to use.
> 
> It gives some warnings like this.
> 
> ```
> warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
> warning: unresolved symbol: _ZNK4dlib6base646decodeERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EE
> warning: unresolved symbol: _ZNK4dlib11base_window9is_closedEv
> warning: unresolved symbol: _ZNK4dlib13image_display22get_image_display_rectEv
> warning: unresolved symbol: _ZN4dlib6base64C1Ev
> warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_210set_streamERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEE
> warning: unresolved symbol: _ZN4dlib17popup_menu_region7disableEv
> warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_26decodeEjj
> warning: unresolved symbol: _ZN9_IplImageC1ERKN2cv3MatE
> warning: unresolved symbol: _ZN2cv8fastFreeEPv
> warning: unresolved symbol: _ZN4dlib12image_windowC1Ev
> warning: unresolved symbol: _ZN4dlib21draw_sunken_rectangleERKNS_6canvasERKNS_9rectangleEh
> warning: unresolved symbol: _ZN4dlib12image_window13clear_overlayEv
> warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_2D1Ev
> warning: unresolved symbol: _ZN4dlib17scrollable_region19set_total_rect_sizeEmm
> warning: unresolved symbol: _ZN2cv3Mat8copySizeERKS0_
> ```
> 
> These are similar warnings I get when I try to run it like this.
> 
> ```
> ./em++ -std=c++11 -O3 -I.. ~/DLIB/dlib-19.4/dlib/all/source.cpp  -I/home/akshay/DLIB/dlib-19.4 -I/usr/include/X11/ -lpthread -lX11 -lopencv_imgcodecs  -o webca.js  ~/DLIB/dlib-19.4/examples/webcam_face_pose_ex.cpp -ldlib  `pkg-config opencv --cflags --libs`
> ```
> 
> followed by node webca.js which doesn't run.
> 
> Also running ./webcam_face_pose_ex.cpp.o after it got compiled gave an error like `error: Unknown attribute kind (52) (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.8.0')`

My problem: `error: Unknown attribute kind (61) (Producer: 'LLVM11.0.0' Reader: 'LLVM 7.0.1')`

when i `$ whereis opt`, get
```
$ whereis opt 
opt: /usr/bin/opt /etc/opt /usr/local/bin/opt /usr/share/man/man1/opt.1.gz
$ /usr/local/bin/opt --version
LLVM (http://llvm.org/):
  LLVM version 7.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake
$ /usr/bin/opt --version
LLVM (http://llvm.org/):
  LLVM version 11.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake
```

i delete opt in `local`(`$ rm -f /usr/local/bin/opt`), the same as `llc` command.

**Comment by Rtoax** [comment]
> > @juj It builds successfully while specifying the new build for OpenCV specifically meant for Emscripten where it doesn't link system libraries. But running it results in the following. And it creates a webcam_face_pose_ex.cpp.o file which I am not able to use.
> > It gives some warnings like this.
> > ```
> > warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
> > warning: unresolved symbol: _ZNK4dlib6base646decodeERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EE
> > warning: unresolved symbol: _ZNK4dlib11base_window9is_closedEv
> > warning: unresolved symbol: _ZNK4dlib13image_display22get_image_display_rectEv
> > warning: unresolved symbol: _ZN4dlib6base64C1Ev
> > warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_210set_streamERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEE
> > warning: unresolved symbol: _ZN4dlib17popup_menu_region7disableEv
> > warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_26decodeEjj
> > warning: unresolved symbol: _ZN9_IplImageC1ERKN2cv3MatE
> > warning: unresolved symbol: _ZN2cv8fastFreeEPv
> > warning: unresolved symbol: _ZN4dlib12image_windowC1Ev
> > warning: unresolved symbol: _ZN4dlib21draw_sunken_rectangleERKNS_6canvasERKNS_9rectangleEh
> > warning: unresolved symbol: _ZN4dlib12image_window13clear_overlayEv
> > warning: unresolved symbol: _ZN4dlib24entropy_decoder_kernel_2D1Ev
> > warning: unresolved symbol: _ZN4dlib17scrollable_region19set_total_rect_sizeEmm
> > warning: unresolved symbol: _ZN2cv3Mat8copySizeERKS0_
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These are similar warnings I get when I try to run it like this.
> > ```
> > ./em++ -std=c++11 -O3 -I.. ~/DLIB/dlib-19.4/dlib/all/source.cpp  -I/home/akshay/DLIB/dlib-19.4 -I/usr/include/X11/ -lpthread -lX11 -lopencv_imgcodecs  -o webca.js  ~/DLIB/dlib-19.4/examples/webcam_face_pose_ex.cpp -ldlib  `pkg-config opencv --cflags --libs`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > followed by node webca.js which doesn't run.
> > Also running ./webcam_face_pose_ex.cpp.o after it got compiled gave an error like `error: Unknown attribute kind (52) (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.8.0')`
> 
> My problem: `error: Unknown attribute kind (61) (Producer: 'LLVM11.0.0' Reader: 'LLVM 7.0.1')`
> 
> when i `$ whereis opt`, get
> 
> ```
> $ whereis opt 
> opt: /usr/bin/opt /etc/opt /usr/local/bin/opt /usr/share/man/man1/opt.1.gz
> $ /usr/local/bin/opt --version
> LLVM (http://llvm.org/):
>   LLVM version 7.0.1
>   Optimized build.
>   Default target: x86_64-unknown-linux-gnu
>   Host CPU: skylake
> $ /usr/bin/opt --version
> LLVM (http://llvm.org/):
>   LLVM version 11.0.0
>   Optimized build.
>   Default target: x86_64-unknown-linux-gnu
>   Host CPU: skylake
> ```
> 
> i delete opt in `local`(`$ rm -f /usr/local/bin/opt`), the same as `llc` command.

https://github.com/emscripten-core/emscripten/issues/5499

**Comment by sbc100** [comment]
You issue is likely related to `pkg-config opencv --cflags --libs`, that will result in attempting to link against the system version of openvc which will not work.
