### ISSUE TITLE
How to call a native webassembly operator in c/c++ source code?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#5441]
![image](https://user-images.githubusercontent.com/8282020/29062328-d35b4c1c-7c53-11e7-9f81-37a81a9df1c6.png)

How to call those methods directly in c/c++ source code? Is there any macros we can use to help this?

**Comment by juj** [comment]
There does not currently exist intrinsics macros for these. For arithmetic, the usual arithmetic operators can be used. For copysign, http://en.cppreference.com/w/c/numeric/math/copysign should map to it, and for ceil, floor and trunc, the corresponding C functions: http://en.cppreference.com/w/c/numeric/math/ceil, http://en.cppreference.com/w/c/numeric/math/floor and http://en.cppreference.com/w/c/numeric/math/trunc. You can use Binaryen's `wasm-dis` to confirm that, or the online Wasm Explorer tool:

https://goo.gl/AZxGpc

shows how `floorf` turns into a `f32.floor` instruction.

@lukewagner, @kripken: I wonder if there exists any Wasm instructions that are currently not reachable? Eyeballing through https://webassembly.github.io/spec/appendix/index-instructions.html, can we produce the following?
 - `i32/i64.clz`
 - `i32/i64.ctz`
 - `i32/i64.popcnt`,
 - `i32/i64.shr_s` (right-shifting signed numbers is implementation defined in C standard)
 - `i32/i64.rotl`
 - `i32/i64.rotr`

If not, I wonder if it would be useful to have `emscripten_clz_i32()` etc. macros for these?

**Comment by Becavalier** [comment]
Do you thinks it's better to have some macros like stuff to control those processes manually? I find that emscripten's compiler backend will do this translation (to wasm native operators) automatically when I use "sqrt" which comes from a c/c++ standard library(math.h) and the same with any other methods from the same place.

**Comment by juj** [comment]
I think we should have macros for those operations that don't have a direct equivalent. A `emscripten_f32_add()` probably makes little sense since one can just do `float a,b,c; c = a + b;` and that will do a `f32.add`, but for operations that are not accessible otherwise, it would be nice to have direct intrinsic macros.

**Comment by Becavalier** [comment]
Make sense, thanks!

**Comment by kripken** [comment]
I think at this point that we emit all those wasm instructions when LLVM tells us to, properly. Still, perhaps intrinsics are useful for a more low-level approach.

**Comment by jamen** [comment]
@Becavalier @kripken Is there code or documentation of how to achieve this, if its possible?  In particular, I want to use the memory instructions `memory.size` and `memory.grow`.

**Comment by kripken** [comment]
@jamen those are used automatically by emscripten output in cooperation with malloc and sbrk. So if you wanted to call those directly, you wouldn't be able to use the default malloc and sbrk.

But, if you want that, you could do something like this: write some wasm functions by hand that call those intrinsics, then link them using binaryen's `wasm-merge` (the compiled C code should see those as extern C functions).

**Comment by jamen** [comment]
@kripken Thanks, that's what I needed to know. I ask because I'm compiling standalone WebAssembly and wanted to learn more about memory management algos. `malloc`/`free` based around the 64KiB pages in WASM was something I was gonna explore.
