### ISSUE TITLE
Can't call exported function when C code was compiled without -O3 flag

### ISSUE THREAD

**Issue by JankesJanco** [kripken/emscripten#5454]
I have a simple C code:
```C
#include <stdio.h>
#include <emscripten/emscripten.h>

int main(int argc, char ** argv) {
    printf("Hello World\n");
}

#ifdef __cplusplus
extern "C" {
#endif

void EMSCRIPTEN_KEEPALIVE myFunction(int argc, char ** argv) {
  printf("MyFunction Called\n");
}

#ifdef __cplusplus
}
#endif
```

If I compile it with -O3 flag (`emcc -o hello.html hello.c -O3 -s WASM=1`) and run this example ([hello_with_O3_flag.zip](https://github.com/kripken/emscripten/files/1212118/hello_with_O3_flag.zip)), everything works fine, I can call exported function `myFunction`.

If I compile same C code without -O3 flag (`emcc -o hello.html hello.c -s WASM=1`) and then run the example ([hello.zip](https://github.com/kripken/emscripten/files/1212124/hello.zip)), I am getting this error message after trying to call exported function `myFunction`:
> Assertion failed: the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)

I've tried it in Firefox and Chromium browsers. Version of emscripten I am using:
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.18
clang version 4.0.0 (https://github.com/kripken/emscripten-fastcomp-clang.git c7c210fee24e0227f882337521b25b1ed9c36d5b) (https://github.com/kripken/emscripten-fastcomp.git 90b726ede4acf47c1bca089de6c79a0b8f2c5d9a) (emscripten 1.37.18 : 1.37.18)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

PS 1: In given examples (hello.zip, hello_with_O3_flag.zip) I slightly edited generated hello.html file - I add there html button and piece of javascript code to call exported function `myFunction` on button click.

PS 2: I ran into this example on mdn sites (https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm, section _Calling a custom function defined in C_)

**Comment by kripken** [comment]
Yes, as the error message says, the runtime was shut down. It's just that in optimized builds that assertion is not on, and it happens to work, but it's incorrect. In general, if you want to call code after `main()` exits, you need to keep the runtime alive, otherwise it is shut down (which is necessary for proper C emulation, e.g., `atexit`s are called). To keep it alive, use that flag `NO_EXIT_RUNTIME`.

**Comment by kripken** [comment]
(I'll try to find out how to get those MDN docs fixed.)

**Comment by JankesJanco** [comment]
Thanks. Now I understand, the error was in mentioned mdn tutorial. As I see it has been already corrected there. Many thanks :)

PS: This is my very first bug report and very first contribution to open community. I know this "bug" has little to no value but I am celebrating now :smiley:

**Comment by kripken** [comment]
This definitely has value, thanks for filing this :) Fixing the docs means a lot of other people will have an easier time.
