### ISSUE TITLE
Perhaps "ENV['LANG'] = 'C'" should be "ENV['LANG'] = 'C.UTF-8'" in src/library.js?

### ISSUE THREAD

**Issue by ImplOfAnImpl** [kripken/emscripten#5474]
I'm not sure if it's a bug at all, but I wonder why is ENV['LANG'] set to 'C'? This effectively sets the system charset to ASCII, so for any code that uses `setlocale(xxx, "")` or `std::locale("")` the standard conversions between char* and other strings would assume char* to be ASCII. E.g. `boost::filesystem::path` uses `std::locale("")` by default, so in the following code
```
const std::string str(u8"語");
const boost::filesystem::path path(str);
const auto wstr = path.wstring();
```
`wstr` will contain garbage.

So, I suggest to change 'C' to 'C.UTF-8' (this value is recognized by musl). The following code may be used as a test:
```
setlocale(LC_ALL, "");

const char* const chr = u8"語";
const auto chrLen = strlen(chr);
assert(chrLen > 1);

mbstate_t mbs{};
const auto nextCharBytesCount = mbrtowc(nullptr, chr, chrLen, &mbs);
assert(nextCharBytesCount == chrLen);
```

**Comment by juj** [comment]
If I build `locale.cpp`:

```c++11
#include <locale.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <wchar.h>

int main()
{
	char *default_locale = setlocale(LC_ALL, NULL);
	printf("default locale: %s\n", default_locale);
	printf("getenv(\"LANG\"): %s\n", getenv("LANG"));

	setlocale(LC_ALL, "");

	const char* const chr = u8"語";
	const auto chrLen = strlen(chr);
	assert(chrLen > 1);

	mbstate_t mbs{};
	const auto nextCharBytesCount = mbrtowc(nullptr, chr, chrLen, &mbs);
	assert(nextCharBytesCount == chrLen);
}
```

natively on Linux Mint 18 with `g++ locale.cpp -o locale -std=c++11`, it outputs

```
default locale: C
getenv("LANG"): en_US.UTF-8
```

I wonder how `env['LANG']` and locale should relate?

**Comment by ImplOfAnImpl** [comment]
I'm not a *nix expert, but from what the documentation for LANG says [here](http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html):
> This variable determines the locale category for native language, local customs and coded character set in the absence of the LC_ALL and other LC_* (LC_COLLATE, LC_CTYPE, LC_MESSAGES, LC_MONETARY, LC_NUMERIC, LC_TIME) environment variables. This can be used by applications to determine the language to use for error messages and instructions, collating sequences, date formats, and so forth. 

I'd assume that it contains a default value for all locale categories.

In your case `setlocale(LC_ALL, NULL)` returns `"C"` because according to the C standard an equivalent of `setlocale(LC_ALL, "C")` is always executed at program startup.

The more interesting test case would be as follows:
```
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <wchar.h>

int main()
{
    printf("LC_ALL before setlocale: %s\n", setlocale(LC_ALL, NULL));
    setlocale(LC_ALL, "");
    printf("LC_ALL after setlocale: %s\n", setlocale(LC_ALL, NULL));

    const char* const chr = u8"語";
    const auto chrLen = strlen(chr);
    assert(chrLen > 1);

    mbstate_t mbs{};
    const auto nextCharBytesCount = mbrtowc(nullptr, chr, chrLen, &mbs);
    assert(nextCharBytesCount == chrLen);
}
```
And the result of running it is:
```
~/tmp$ gcc locale.cpp -std=c++11 -o locale
~/tmp$ ./locale 
LC_ALL before setlocale: C
LC_ALL after setlocale: en_US.UTF-8
~/tmp$ LANG=C ./locale 
LC_ALL before setlocale: C
LC_ALL after setlocale: LC_CTYPE=C;LC_NUMERIC=en_US.UTF-8;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=C;LC_PAPER=en_US.UTF-8;LC_NAME=en_US.UTF-8;LC_ADDRESS=en_US.UTF-8;LC_TELEPHONE=en_US.UTF-8;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=en_US.UTF-8
locale: locale.cpp:20: int main(): Assertion `nextCharBytesCount == chrLen' failed.
Aborted
```

During the second run some of the categories were not affected by `LANG=C` because I have the corresponding env vars explicitly set:
```
~/tmp$ printenv | grep LC_
LC_PAPER=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_NAME=en_US.UTF-8
```

P.S. I'm on Linux Mint 17.3

**Comment by juj** [comment]
Posted PR #5500 to fix this.

I see that `setlocale(LC_ALL, "C.UTF-8");` even without this PR does give one a UTF-8 aware locale, so that is a workaround for older Emscripten. Given that the code in the above PR works natively, it is good to have the same default.
