### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable on Mac OS X Sierra version 10.12.5 

### ISSUE THREAD

**Issue by nirus** [kripken/emscripten#5475]
Tried installing on **Mac OS X 10.12.5 (16F73)**
Tried with both the **python versions 3.6.2 and 2.7.13**

[Followed these steps ](https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm#Compiling_Emscripten)

**ErrorLog on terminal window after running the below line**

`./emsdk install --build=Release sdk-incoming-64bit binaryen-master-64bit`

Error Log:

> Traceback (most recent call last):
  File "./emsdk", line 35, in <module>
    if os.name == 'nt' or 'WINDOWS' in os.getenv('SYSTEMROOT') or 'WINDOWS' in os.getenv('COMSPEC'):
TypeError: argument of type 'NoneType' is not iterable

**Comment by juj** [comment]
Thanks, this was a regression from a feature that I just added an hour or so ago (https://github.com/juj/emsdk/commit/3b6c6b86520af475583a200e9994aaa93fa07ad4). Fix in https://github.com/juj/emsdk/commit/4ed531f67929f06ca11fdd22016652363f95c151.
