### ISSUE TITLE
How to set initial memory size of webassembly module?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#5493]
I mean how to customize the initial memory size of a webassembly module? something like to import a customize WebAssembly.Memory object?

**Comment by juj** [comment]
You can set `Module['buffer']` and `Module['wasmMemory']`. See e.g. this PR https://github.com/kripken/emscripten/pull/4930/files (not sure what we'll do about it, but the code in `src/shell.html` in there shows how to preallocate the module size).

Also you can use `-s TOTAL_MEMORY=16MB` to preset a size at `emcc` link time.

**Comment by Becavalier** [comment]
Cool!!! Thanks!
