### ISSUE TITLE
Support SAFE_HEAP with LLVM upstream backend

### ISSUE THREAD

**Issue by dschuff** [kripken/emscripten#5507]
I haven't investigated yet, but I interpret @kripken's comment in #5497 to mean that the wasm backend doesn't support `SAFE_HEAP`. Emscripten has a lot of random features, but `SAFE_HEAP` is probably one of the more useful ones, so we should probably support it before switching over to upstream by default.

**Comment by kripken** [comment]
I agree, SAFE_HEAP is one of the critical things for debugging.

I suggest we write a binaryen pass to do that instrumentation, and then we can use that regardless of backend (right now we use an asm.js optimizer pass), should be very simple.

**Comment by dschuff** [comment]
Yeah, that makes sense.

**Comment by kripken** [comment]
Implemented in those PRs.
