### ISSUE TITLE
Possible bug in dylink tests

### ISSUE THREAD

**Issue by dschuff** [kripken/emscripten#5514]
Currently V8 is banned on the dylink tests because it fails on, among others, the `dylink_funcpointer` test,
so I've been trying to reproduce it in a form I can use in a V8 bug report. 
I have dylink_funcpointer_main.c:
```
#include <stdio.h>
typedef void (*voidfunc)();
voidfunc sidey(voidfunc f);
void a() { printf("hello from funcptr\n"); }
int main() {
  sidey(a)();
  return 0;
}
```
dylink_funcpointer_side.c
```
typedef void (*voidfunc)();
voidfunc sidey(voidfunc f) { return f; }
```
dylink_funcpointer_pre.js
```
var Module = {
  dynamicLibraries: ['liblib.so'],
};
```
... and compile thusly:
```
$ src/work/wasm-install/bin/emcc --em-config /s/wasm-waterfall/src/work/wasm-install/emscripten_config -s MAIN_MODULE=1 --memory-init-file 0 --pre-js dylink_funcpointer_pre.js -o dylink_funcpointer_main.js dylink_funcpointer_main.c -s WASM=1 -s DISABLE_EXCEPTION_CATCHING=1
$ src/work/wasm-install/bin/emcc --em-config /s/wasm-waterfall/src/work/wasm-install/emscripten_config -s SIDE_MODULE=1 --memory-init-file 0  -o dylink_funcpointer_side.wasm dylink_funcpointer_side.c -s WASM=1 -s DISABLE_EXCEPTION_CATCHING=1
$ mv dylink_funcpointer_side.wasm liblib.so
```
When I do this I get something that looks correct (e.g. the `sidey` function is exported from the side module wasm file, and imported in the main module wasm file.

Because of the way these tests are dynamically generated, it's really hard to tell exactly how the test runner does it, but I thought that should be close. However it seems that when I run it in the test runner (e.g. using the `EM_SAVE_DIR` option), there is a `sidey` function exported from the main module, which seems wrong (actually as written in the current test runner it's C++-mangled, but I used the `force_c` option). 

@azakai can you reproduce that, and maybe confirm that I'm not crazy or somehow holding it wrong?

**Comment by kripken** [comment]
I think you might be confused by the flipping. After testing normally it will print "flip" in the console as it runs the test in flipped mode, i.e. with the main and side modules flipped. To remove that, you can edit `need_reverse=True` to `False` in `dylink_test` (or add a return before it calls the reversed version etc.).

**Comment by dschuff** [comment]
OK yeah that was it, I forgot that it ran the test twice.

**Comment by dschuff** [comment]
We really should route all the test compiles through a logger so we can actually see what runs (although that still wouldn't help much where all the tests are dynamically generated).
