### ISSUE TITLE
Debug info for upstream wasm backend

### ISSUE THREAD

**Issue by dschuff** [kripken/emscripten#5516]
Before we make the wasm backend default, it should have the same debug info capabilities as asm2wasm. Today that means a Name section and source maps. Currently IIRC LLVM .s files have line-table-style .loc directives in the output which s2wasm can turn into both of those. We should also support the name section with LLVM wasm binary output, but that probably doesn't block switching if we use s2wasm.

**Comment by jgravelle-google** [comment]
Today s2wasm supports name sections and source maps, so closing this.

In the future we'll need to support this in the wasm object file format, but that's a separate issue?
