### ISSUE TITLE
Does "emcc" fully supporting c++11 features?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#5535]

**Comment by juj** [comment]
Emscripten/`emcc` itself does not interact directly with C++11 language or library features, but those are provided by Clang/LLVM and libc++.

Running `emcc -v` will give you information about which version of Clang/LLVM is used:

```
C:\code\emsdk\emscripten\incoming>emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.20
clang version 4.0.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 9abeb949e02b1eee0908726067ad676114674d9b) (https://github.com/kripken/emscripten-fastcomp/ 04f33e466c63c2f3e33ca377035684390b65eb53) (emscripten 1.37.20 : 1.37.20)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\Release\bin
INFO:root:(Emscripten: Running sanity checks)
```

which you can trace back to the LLVM language support page for a specific C++xyz version support: https://clang.llvm.org/cxx_status.html, which suggests Clang 4.0.0 should be up to `C++17` compatible.

As for the standard C++ libraries, you can run

```
C:\code\emsdk\emscripten\incoming>git log system\include\libcxx
commit 9e5a83b1825762b1c49a17695d1a346315c61913
Author: Dirk Vanden Boer <dirk.vdb@gmail.com>
Date:   Mon Jul 24 09:40:39 2017 +0200

    Libcxx version bump to 4.0.1

commit f8e0b7dc838dea8b713944b5c9469be837826999
Author: cynecx <cynecx@users.noreply.github.com>
Date:   Mon May 9 23:39:55 2016 +0200

    libc++ update (#4288)

    * Update libc++ to SVN revision 268153

    * Fixes for shared.py and system_libs.py to support latest libc++ build

    * Updated libcxx symbols file

    * Seperate include paths into two lists (C_INCLUDE_PATHS and CXX_INCLUDE_PATHS).

    * fix test: test_emulate_function_pointer_casts because of libcxx updates

    * Address documentation issues (High priority for iostream constructor + acos overload issues in test_core.py)

commit c249f6dde01763daffae99f6f6e460aab80d28dc
Author: Alon Zakai <alonzakai@gmail.com>
Date:   Wed Jan 7 13:48:26 2015 -0800

    apply patch from libcxx bug 20084, fixes embind compilation error on clang 3.5

...

```

to see the history of libc++ versions. Looking at the latest change is commit [9e5a83b1825762b1c49a17695d1a346315c61913](https://github.com/kripken/emscripten/commit/9e5a83b1825762b1c49a17695d1a346315c61913), which GitHub says was part of PR #5415, where it is commented that version of libc++ has compatibility up to upcoming `C++17` standard.

So the answer should be yes. If there are some C++11 features that don't work that is not a known limitation in the docs, feel free to open a bug report with a small test case.
