### ISSUE TITLE
glWaitSync returns INVALID_OPERATION.

### ISSUE THREAD

**Issue by ShoYamaG** [kripken/emscripten#5536]
When glWaitSync is called in C/C++ program, it is converted as follows, 
```javascript
_glWaitSync(($1|0),0,-1,-1);
```
and, the implementation of _glWaitSync is
```javascript
glWaitSync: function(sync, flags, timeoutLo, timeoutHi) {
    // See WebGL2 vs GLES3 difference on GL_TIMEOUT_IGNORED above (https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.15)
    timeoutLo == timeoutLo >>> 0;
    timeoutHi == timeoutHi >>> 0;
    var timeout = (timeoutLo == 0xFFFFFFFF && timeoutHi == 0xFFFFFFFF) ? -1 : Runtime.makeBigInt(timeoutLo, timeoutHi, true);
    GLctx.waitSync(GL.syncs[sync], flags, timeout);
}
```
in library_gl.js.

In this function, timeout variable may be a huge integer but not exactly 0xFFFFFFFFFFFFFFFF 
due to JavaScripte specification.
And I think the first and the second line of the function have no meaning.
To change the two lines to 
```javascript
    timeoutLo = timeoutLo >>> 0;
    timeoutHi = timeoutHi >>> 0;
```
seems to work well.

Similar code is written in glClientWaitSync function.
Is it a proper fix?

**Comment by juj** [comment]
Thanks for noticing, the original code with `==` was a typo. Pushed the above fix. Does the code work well now?

**Comment by ShoYamaG** [comment]
Thanks for prompt modification. Now it works fine.
