### ISSUE TITLE
Google-chrome cannot run code compiled with em++   -O2

### ISSUE THREAD

**Issue by htg20** [kripken/emscripten#5540]
Hello,
I have a small C++ example (see below). When I compile it with 
em++ -O2  test01.cpp -o t01.html

firefox can run but using Google-chrome, it stays in the "Downloading" part and does not continue. With -O1, everything is fine on both browsers. I use:

emcc 1.37.16
google-chrome, Linux: Version 60
firefox: version 55.0.2

Below is the code. Thank you.

Cheers
Hossein

#include <iostream>
using namespace std;

class CSquare
{
public:
    double Side;

    CSquare() : Side(0.00) {}
    CSquare(double side) : Side(side) { }
    ~CSquare() { }

    double getSide() const { return Side; }
    void setSide(const double s)
    {
	if( s <= 0 )
		Side = 0.00;
	else
		Side = s;
	}

    double Perimeter() { return Side * 4; }
    double Area() { return Side * Side; }
};

int main()
{
    CSquare *sqr[4];

    sqr[0] = new CSquare;
    sqr[0]->setSide(24.55);
    sqr[1] = new CSquare;
    sqr[1]->setSide(15.08);
    sqr[2] = new CSquare;
    sqr[2]->setSide(8.212);
    sqr[3] = new CSquare;
    sqr[3]->setSide(202.24);

    cout << "Squares Characteristics" << endl;
    cout << "Square 1" << endl;
    cout << "Side:      " << sqr[0]->getSide() << endl;
    cout << "Perimeter: " << sqr[0]->Perimeter() << endl;
    cout << "Area:      " << sqr[0]->Area() << endl;

    cout << "Square 2" << endl;
    cout << "Side:      " << sqr[1]->getSide() << endl;
    cout << "Perimeter: " << sqr[1]->Perimeter() << endl;
    cout << "Area:      " << sqr[1]->Area() << endl;

    cout << "Square 3" << endl;
    cout << "Side:      " << sqr[2]->getSide() << endl;
    cout << "Perimeter: " << sqr[2]->Perimeter() << endl;
    cout << "Area:      " << sqr[2]->Area() << endl;
	
    cout << "Square 4" << endl;
    cout << "Side:      " << sqr[3]->getSide() << endl;
    cout << "Perimeter: " << sqr[3]->Perimeter() << endl;
    cout << "Area:      " << sqr[3]->Area() << endl;

    return 0;
}

**Comment by kripken** [comment]
Are you using a webserver to run it? Chrome requires that (doesn't allow localhost file access).

If that's not it, look in the chrome dev console, it should show a network error or some other error.

**Comment by htg20** [comment]
Thank you. 

I found this other post on this issue, and they seem to be the same problem.
https://github.com/kripken/emscripten/issues/4000
So, if there is no other comment on this, I close.
