### ISSUE TITLE
Chrono returning incorrect date time with WASM

### ISSUE THREAD

**Issue by yairlev** [kripken/emscripten#5542]
I encountered some weird behavior when calling chrono methods that are compiled with the `WASM` flag (tested on emscripten v1.37.16).

Here's a very simple test app that I ran:

`
int main(int argc, char* argv[])
{
    
    using namespace std::chrono;
         
    auto now = system_clock::now();
        
    std::time_t now_c = system_clock::to_time_t(now);
    std::cout << "now_c: " << now_c << std::endl;
    std::cout << "time is: " <<  std::put_time(std::localtime(&now_c), "%F %T") << std::endl;
        
}
`

When I compile the app with asmjs, the `now_c` has a correct value and the time printed is correct, whereas when I compile the same app with WASM including following flags: 
`WASM=1,
 DETERMINISTIC=1,
 BINARYEN_TRAP_MODE='js',
 ALLOW_MEMORY_GROWTH=1,
 EVAL_CTORS=0
` 

The `now_c` always returns the same bogus value of 10 or 11 and prints a wrong datetime (e.g. 1970-01-01 02:00:10)

**Comment by kripken** [comment]
Does this happen without `DETERMINISTIC`? That flag should "break" all time measurements, as it forces everything to be deterministic. That is, that flag guarantees that if you run it twice, you'll get the same result, and to do that it has to "fake" any clock measurements, not just random number generation.

**Comment by yairlev** [comment]
Thanks @kripken for the prompt reply. You're right. Once I removed the `DETERMINISTIC` flag std::chrono started working as expected.
