### ISSUE TITLE
How to eliminate those "nullFunc_*" functions?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#5546]
I have tried eliminating those invalid functions according to this doc: http://kripken.github.io/emscripten-site/docs/porting/guidelines/function_pointer_issues.html#asm-pointer-casts, but it doesn't work anymore, and I find those functions would appear if I include "\<stack\>" in my source file and use 
the stack structure from this header file, any idea would be appreciated!!

![image](https://user-images.githubusercontent.com/8282020/29907598-efbc83dc-8e4e-11e7-8624-18eda4cc81df.png)

**Comment by kripken** [comment]
Looking in emscripten.py, those `nullFunc_` methods are generated when ASSERTIONS is on. They help give better error messages for function pointer errors. So not enabling that setting should remove them. (Note that assertions are on by default in -O0, but not when optimizing.)

**Comment by Becavalier** [comment]
Make sense, thanks!
