### ISSUE TITLE
Can't link to OpenSSL

### ISSUE THREAD

**Issue by Gemscripten** [kripken/emscripten#5547]
I'm trying to compile some C code that uses OpenSSL with emscripten, but I get unresolved symbol warnings like:

    warning: unresolved symbol: SHA256_Init
    warning: unresolved symbol: SHA256_Final
    warning: unresolved symbol: SHA256_Update

I compiled the code using this command:

    emcc SHA256.c -lssl -lcrypto -L /usr/local/openssl-1.0.2k/lib/ -I /usr/local/openssl-1.0.2k/include -s WASM=1 -o SHA256.html --emrun

With the following source code

    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>
   
    #include <openssl/sha.h>
    #include <openssl/hmac.h>
    #include <openssl/evp.h>
    
    void sha256(char *string, char outputBuffer[65])
    {
        unsigned char hash[SHA256_DIGEST_LENGTH];
        SHA256_CTX sha256;
        SHA256_Init(&sha256);
        SHA256_Update(&sha256, string, strlen(string));
        SHA256_Final(hash, &sha256);
        int i = 0;
        for(i = 0; i < SHA256_DIGEST_LENGTH; i++)
        {
            sprintf(outputBuffer + (i * 2), "%02x", hash[i]);
        }
        outputBuffer[64] = 0;
    }
    
    int main (void)
    {
        static unsigned char buffer[65];
        sha256("string", buffer);
        printf("%s\n", buffer);
        return 0;
    }

**Comment by kripken** [comment]
You can't link to a local binary: it contains x86 or ARM or something like that. Emscripten output is asm.js or wasm, and it uses LLVM IR as its object files for linking.

You need to port OpenSSL itself and link to the emscripten-ported version, https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries
