### ISSUE TITLE
Opera fails to load the data: Cross origin request.

### ISSUE THREAD

**Issue by stolk** [kripken/emscripten#5557]
So my emscripted app is running well on firefox (apart from a SDL2 audio format issue.)
But when I try on Opera, I get:

_XMLHttpRequest cannot load file:///home/bram/apps/Smatch/JS/bin/smatch.html.mem. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https._

Affected line in the html file:
`meminitXHR.send(null);`

This is on Opera version 	44.0.2510.857 which is running on Ubuntu.

The data file was created with the --preload-file argument to the linker.

If I read this correctly, it means I cannot load the generated html from my local machine, it has to go through a web server like apache first?

**Comment by curiousdannii** [comment]
Chrome, and I assume Opera now, has crippled file://. Once #5296 has merged it would probably be the best option if you need to support file://.

**Comment by kripken** [comment]
And yes, you can use a local web server to get around this. E.g. python's built-in one is easy to run for testing purposes, `python -m SimpleHTTPServer`

**Comment by juj** [comment]
Emscripten also ships `emrun`, which is a supercharged version of `SimpleHTTPServer`, and support serving `.gz` compressed files, doing automated runs, etc. Docs at http://kripken.github.io/emscripten-site/docs/compiling/Running-html-files-with-emrun.html
