### ISSUE TITLE
wrapping functions with primitive pointer arguments

### ISSUE THREAD

**Issue by drhouse82** [kripken/emscripten#5562]
Hi,
likely a very stupid question...
I try to wrap a C++ function (part of opencv/opencvjs) that accepts two float pointers to return results using embind.
C++ function signature is:
`void minMaxLoc(InputArray src, double* minVal, double* maxVal=0, Point* minLoc=0, Point* maxLoc=0, InputArray mask=noArray())`

I have added wrapper
```
namespace Wrappers {
    void minMaxLoc_wrapper(const cv::Mat& arg1, double* arg2, double* arg3, Point* arg4, Point* arg5,  const cv::Mat& arg6) {
        return cv::minMaxLoc(arg1, arg2[0], arg2[1], arg4, arg5, arg6);
    }
}
```

and I added a function binding including "allow_raw_pointers()" argument:
```
EMSCRIPTEN_BINDINGS(testBinding) {
    function("minMaxLoc", select_overload<void(const cv::Mat&, double*, double*, Point*, Point*, const cv::Mat&)>(&Wrappers::minMaxLoc_wrapper), allow_raw_pointers());
}
```

The thing compiles, but when calling minMaxLoc from JS, I get 
```
"UnboundTypeError: Cannot call minMaxLoc due to unbound types: Pd, PN2cv6Point_IiEE
    at UnboundTypeError.<anonymous> (http://localhost:8080/cv-wasm.js:21:43859)
    at new UnboundTypeError (eval at createNamedFunction (http://localhost:8080/cv-wasm.js:21:43565), <anonymous>:4:34)
    at throwUnboundTypeError (http://localhost:8080/cv-wasm.js:21:139653)
    at Object.minMaxLoc (http://localhost:8080/cv-wasm.js:21:169191)
    at <anonymous>:1:4"
```

Having searched the web and this issues section, I meanwhile understand that pointers to primitives are not supported by embind. Also I read that easiest way is likely to group the two floats to an array. 
Yet, I'm not sure if this is possible without touching the C++ source and I'm stuck in searching for more embind docu / examples... 

Can anyone give a hint how to access this function easily?

**Comment by juj** [comment]
My understanding is that `double*` should be supported with `allow_raw_pointers()` and due to https://github.com/kripken/emscripten/blob/master/system/lib/embind/bind.cpp#L113 being called, but perhaps there is something else needed. It may be needed to register the type `Point` for `Point*` to work.

**Comment by drhouse82** [comment]
I thought, analogously to this post https://stackoverflow.com/questions/20355880/emscripten-how-can-i-solve-unboundtypeerror , the "Pd" in my error means "Pointer to double". Hence, I assumed its not the Point argument, that's causing the trouble.

To distinguish between the double* and a potential Pointer* issue, I targetted a similar function that has int* arguments instead of Pointer* ones. 

signature:
`void minMaxIdx(InputArray src, double* minVal, double* maxVal, int* minIdx=0, int* maxIdx=0, InputArray mask=noArray())`

wrapper:
```
void minMaxIdx_wrapper(const cv::Mat& arg1, double* arg2, double* arg3, int* arg4, int* arg5,  const cv::Mat& arg6) {
        return cv::minMaxIdx(arg1, arg2, arg3, arg4, arg5, arg6);
    }
```
binding:
`function("minMaxIdx", select_overload<void(const cv::Mat&, double*, double*, int*, int*, const cv::Mat&)>(&Wrappers::minMaxIdx_wrapper), allow_raw_pointers());`

The error is now similar and complaining about both, double* and int* (Pd, Pi).
```
"UnboundTypeError: Cannot call minMaxIdx due to unbound types: Pd, Pi
    at UnboundTypeError.<anonymous> (http://localhost:8080/cv-wasm.js:21:43859)
    at new UnboundTypeError (eval at createNamedFunction (http://localhost:8080/cv-wasm.js:21:43565), <anonymous>:4:34)
    at throwUnboundTypeError (http://localhost:8080/cv-wasm.js:21:139653)
    at Object.minMaxIdx (http://localhost:8080/cv-wasm.js:21:169191)
    at <anonymous>:1:4"
```

**Comment by AlexPerrot** [comment]
You have two unbound types : `Point*` and `double*`.
For `Point*`, you only need to register `Point`.

For `double*`, currently the only way to use it with embind is to cast to a number.
But calling a function with a primitive type pointer from js is odd since you need to provide a pointer that can only be obtained through c++. Maybe a wrapper can take care of that and remove the pointers from the js facing signature.
How do you intend to use those pointers in js ?

**Comment by drhouse82** [comment]
Point type, yes unterstood.

The double pointers are just outputs of the function. So wrapping it such that the javascript function returns an array of these numbers would be perfectly fine. However, I couldnt find an example how to achieve this in embind without changing the C++ source. 
Can you link / provide an example? (sorry for my ignorance).

Of coarse I can in principle also change the C++source, but as I feel I'll face this kind of signiture often in the future, a wrapper solution would be better for me.

**Comment by AlexPerrot** [comment]
You have two options here : handling the pointers in c++ or js.

For c++:
You can write the wrapper function in the `EMSCRIPTEN_BINDINGS` or between `#ifdef EMSCRIPTEN` / `#endif` or use the `optional_override` to replace the function in the bindings by a captureless lambda (best doc I could find is [here](https://fr.slideshare.net/chadaustin/connecting-c-and-javascript-on-the-web-with-embind), slide 67 onwards, and my post [here](https://github.com/kripken/emscripten/issues/4475#issuecomment-284986566) uses it.)
This function can then build a js array or object to put the return values using `emscripten::val` (doc [here](http://kripken.github.io/emscripten-site/docs/api_reference/val.h.html))

For js, you will also need a custom function in c++ side to take the pointers as numbers and call the right function.

IMHO, the c++ solution is much cleaner and easier to maintain. Although it may seem longer and more complicated to implement, it is mostly boilerplate code, so nothing very difficult, whereas the js solution is trickier.

Don't hesitate to ask for clarifications :)

**Comment by drhouse82** [comment]
Thank you very much... It worked out fine.
I added the following:
```
struct minMaxIdxResult {
    double min;
    double max;
    int minIdx;
    int maxIdx;
};
```
and
```
EMSCRIPTEN_BINDINGS(testBinding) {
       value_object<minMaxIdxResult>("minMaxIdxResult")
        .field("min", &minMaxIdxResult::min)
        .field("max", &minMaxIdxResult::max)
        .field("minIdx", &minMaxIdxResult::minIdx)
        .field("maxIdx", &minMaxIdxResult::maxIdx)
        ;
        
    function("minMaxIdx", optional_override(
        [](const cv::Mat& image, const cv::Mat& mask){
            double min, max;
            int min_idx, max_idx;
            cv::minMaxIdx(image, &min, &max, &min_idx, &max_idx, mask);
            return minMaxIdxResult{min, max, min_idx, max_idx};
        }));
}
```

Works perfectly... Thanks once more.
