### ISSUE TITLE
failed to compile wasm module

### ISSUE THREAD

**Issue by GregSlazinski** [kripken/emscripten#5566]
I've compiled my app using Emscripten, with flags:
--memory-init-file 1 -s ALLOW_MEMORY_GROWTH=1 -s USE_WEBGL2=1 -s WASM=1

I've uploaded the files generated by Emscripten:
Application.html
Application.js
Application.wasm

But when I run it on Chrome Version 61.0.3163.79 (Official Build) (64-bit), I get the error:
trying binaryen method: native-wasm
failed to compile wasm module: RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
Uncaught no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods

Application.js is 0.5MB in size.
Application.wasm is 3.5MB in size.

Did I miss something?
How to make it work?
I'm using the auto generated HTML/JS files so I assumed it should work out of the box.

When I run it on FireFox 55.0.3 I get this:
trying binaryen method: native-wasm 
failed to compile wasm module: CompileError: at offset 8: binary version 0xd does not match expected version 0x1  
uncaught exception: no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods

On Microsoft Edge 40.15063.0.0, EdgeHTML 15.15063 I get this:
trying binaryen method: native-wasm
no native wasm support detected
However after I've enabled "experimental JavaScript features", Edge is the only browser that successfully ran the application.

**Comment by kappa-gooner** [comment]
I have the exact same trouble. 
I'm able to run it on Firefox and Edge;
but on Chrome, the WebAssembly doesn't seem to compile.

```
failed to compile wasm module: RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
```

**Comment by juj** [comment]
Try updating to latest Emscripten. I cannot find a `WebAssembly.Compile()` being used anywhere in Emscripten anymore (nor `WebAssembly.compile()`), but `WebAssembly.instantiate()` should be used.

**Comment by GregSlazinski** [comment]
I've performed the installation instructions as here:
http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html
# Fetch the latest registry of available tools.
./emsdk update

# Download and install the latest SDK tools.
./emsdk install latest

# Make the "latest" SDK "active" for the current user. (writes ~/.emscripten file)
./emsdk activate latest

# Activate PATH and other environment variables in the current terminal
source ./emsdk_env.sh

However no updated was found, and I'm on the same version as before:
1.37.1

**Comment by GregSlazinski** [comment]
Would you mind updating the emscripten sdk?
I read that 1.37.1 was originally released ~9 months ago.
I've tried to extract contents from https://github.com/kripken/emscripten/releases version 1.37.21, but then it started to complain about incompatible clang version, at which point I gave up.
Thank you

**Comment by juj** [comment]
If you do not see `emsdk update` updating to newer versions, you might be hitting this bug: https://groups.google.com/d/msg/emscripten-discuss/bKCQxN6Q76Y/IsIw8LeXBgAJ . In that case, try updating manually by redownloading the emsdk zip. Apologies for the trouble, the updater bug affected quite many people.

**Comment by GregSlazinski** [comment]
Hello, thank you for the reply.
I think this is a different problem, because that didn't help.
I've just downloaded latest 64-bit Emscripten SDK for Windows (emsdk-portable-64bit.zip)
as described here:
http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#windows
https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable-64bit.zip
Extracted all contents to D:\Progs\Emscripten
Then I've ran Windows PowerShell in D:\Progs\Emscripten
Executed:
./emsdk update
./emsdk install latest
And this is the output that I've got:
```
PS D:\Progs\Emscripten> ./emsdk update
Downloading: D:/Progs/Emscripten/zips/emsdk_windows_update.zip from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip, 38803 Bytes                                                                            Unpacking 'D:/Progs/Emscripten/zips/emsdk_windows_update.zip' to 'D:/Progs/Emscripten'
Update complete, however skipped fetching the Emscripten tags, since git was not found.
If you want to compile one of the tagged releases from source, please install git by typing 'emsdk install git-1.9.4', or alternatively by installing it manually from http://git-scm.com/downloads . If you install git manually, remember to add it to PATH.
If you are not looking to build Emscripten from source, you can safely ignore this message.
PS D:\Progs\Emscripten> ./emsdk install latest
Update complete, however skipped fetching the Emscripten tags, since git was not found.
If you want to compile one of the tagged releases from source, please install git by typing 'emsdk install git-1.9.4', or alternatively by installing it manually from http://git-scm.com/downloads . If you install git manually, remember to add it to PATH.
If you are not looking to build Emscripten from source, you can safely ignore this message.
Installing SDK 'sdk-1.37.1-64bit'..
Installing tool 'clang-e1.37.1-64bit'..
The contents of file 'llvm/tag/win_64bit/emscripten-llvm-e1.37.1.zip' already exist in destination 'D:/Progs/Emscripten/clang/e1.37.1_64bit', skipping.
Done installing tool 'clang-e1.37.1-64bit'.
Installing tool 'node-4.1.1-64bit'..
The contents of file 'node_4.1.1_64bit.zip' already exist in destination 'D:/Progs/Emscripten/node/4.1.1_64bit', skipping.
Done installing tool 'node-4.1.1-64bit'.
Installing tool 'python-2.7.5.3-64bit'..
The contents of file 'python_2.7.5.3_64bit.zip' already exist in destination 'D:/Progs/Emscripten/python/2.7.5.3_64bit', skipping.
Done installing tool 'python-2.7.5.3-64bit'.
Installing tool 'emscripten-1.37.1'..
The contents of file 'https://github.com/kripken/emscripten/archive/1.37.1.zip' already exist in destination 'D:/Progs/Emscripten/emscripten/1.37.1', skipping.
Done installing tool 'emscripten-1.37.1'.
Done installing SDK 'sdk-1.37.1-64bit'.
PS D:\Progs\Emscripten>
```
I'm using Windows 10, 64-bit, I'm located in New Zealand.
It's still stuck on 1.37.1 and not detecting any newer versions.

**Comment by erikdubbelboer** [comment]
I just installed a brand new version of emscripten using [getting started](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html) and I'm running into the exact same issue.

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.21
clang version 4.0.0  (emscripten 1.37.21 : 1.37.21)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Users/erik/emsdk-portable/clang/e1.37.21_64bit
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by juj** [comment]
> Then I've ran Windows PowerShell

Try using Windows Command Prompt instead, currently Windows PowerShell is not supported, though there are some fixes being contributed to it (https://github.com/juj/emsdk/issues/100 and https://github.com/juj/emsdk/pull/105)

It looks like the source problem is however this

```
Update complete, however skipped fetching the Emscripten tags, since git was not found.
If you want to compile one of the tagged releases from source, please install git by typing 'emsdk install git-1.9.4', or alternatively by installing it manually from http://git-scm.com/downloads . If you install git manually, remember to add it to PATH.
```

which is saying that it is unable to find the list of tagged versions. This is required in order to find the list of downloadable Emscripten versions from GitHub. Try setting up git in command prompt. If it should exist in PATH, then this might be due to Windows PowerShell at present, in which case give good old command prompt a spin.

**Comment by GregSlazinski** [comment]
Thank you for the reply.
Using command prompt instead of PowerShell didn't make a difference, however after I've set PATH to my GIT installation folder, the EMSDK finally updated to latest version (when using PowerShell).
However I would strongly recommend lifting the requirement of having GIT installed, as I believe that current installation process (requirement of having GIT installed) is too complicated for a typical user.

I'm recompiling my engine and will see if WebAssembly works OK now on Chrome..

**Comment by GregSlazinski** [comment]
Excellent! WASM now works on Chrome, Firefox and Edge.
