### ISSUE TITLE
EMULATE_FUNCTION_POINTER_CASTS with WebAssembly should not disable async compilation

### ISSUE THREAD

**Issue by talljosh** [kripken/emscripten#5567]
I was recently trying to asynchronously load my compiled WebAssembly. I used ``Module.instantiateWasm``, but kept running into issues such as "real__malloc is not callable".

After much hunting around in the emscripten source code I found that, for asynchronous loading of WebAssembly to work, you need to compile with "-s BINARYEN_ASYNC_COMPILATION=1" or "-s SWAPPABLE_ASM_MODULE=1".

I suggest updating the documentation for ``Module.instantiateWasm`` to mention these compilation flags, to avoid others having to go through the same pain.

Documentation URL: https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.instantiateWasm

**Comment by kripken** [comment]
Those flags should be turned on automatically for you - what build options are you using?

**Comment by talljosh** [comment]
I compiled with:

`emcc -o output.js infile.bc -s TOTAL_MEMORY=268435456 -s EMULATE_FUNCTION_POINTER_CASTS=1 --memory-init-file 0 -s WASM=1 -s BINARYEN_METHOD=\"native-wasm\" --js-library src/lib.js --preload-file lib`

I am using emcc 1.37.18.

**Comment by kripken** [comment]
Ok, building on 1.37.21 shows
````
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
````
which is because of emulated function pointers, that mode has some limitations currently. (That warning might have been added recently, I'm not sure.)

Next question, why are you calling the instantiateWasm internal API, instead of letting the startup code call it for you?

**Comment by talljosh** [comment]
When I say I'm using `Module.instantiateWasm`, what I mean is that I'm defining `Module.instantiateWasm` before running the startup code. I'm not calling it directly.

At present I need the emulated function pointers for the program to work.

I do see a similar warning to the one you mentioned, when I mix `BINARYEN_ASYNC_COMPILATION` with `EMULATE_FUNCTION_POINTER_CASTS` (`WARNING:root:BINARYEN_ASYNC_COMPILATION requested, but disabled since not in wasm-only mode`).

But I fixed my problem by using `SWAPPABLE_ASM_MODULE` instead of `BINARYEN_ASYNC_COMPILATION`. Poking in the emscripten source code shows me that `is_wasm_only` returns False when `EMULATE_FUNCTION_POINTER_CASTS` is set, and this results in `BINARYEN_ASYNC_COMPILATION` being switched off. But that doesn't actually stop me from loading the WebAssembly asynchronously, if I've compiled with `SWAPPABLE_ASM_MODULE`.

So perhaps the actual bug here is that the test for whether to disable `BINARYEN_ASYNC_COMPILATION` shouldn't pay attention to `EMULATE_FUNCTION_POINTER_CASTS`?

**Comment by kripken** [comment]
Yes, that's something we need to look into. I believe I saw some test failures with it, but that wasn't very recently, so perhaps those were fixed. Concretely, we should stop paying attention to `EMULATE_FUNCTION_POINTER_CASTS` for wasm-only mode (I think that code is in tools/shared.py, `is_wasm_only` or something similar), and then run `python tests/runner.py binaryen*` and see if anything fails.

**Comment by talljosh** [comment]
After changing `is_wasm_only()` to ignore `EMULATE_FUNCTION_POINTER_CASTS` (patch below), the tests `browser.test_binaryen*` and `other.test_binaryen*` still all passed.

I struggled to get some other tests behaving even before I made the change, so perhaps someone more familiar with the test set-up should confirm this.

My patch:

    --- old/tools/shared.py	2017-09-20 18:32:43.750352055 +1000
    +++ new/tools/shared.py	2017-09-20 18:32:38.978198746 +1000
    @@ -2040,7 +2040,7 @@
         # fastcomp can emit wasm-only code.
         # also disable this mode if it depends on special optimizations that are not yet
         # compatible with it.
    -    return ('asmjs' not in Settings.BINARYEN_METHOD and 'interpret-asm2wasm' not in Settings.BINARYEN_METHOD and not Settings.RUNNING_JS_OPTS and not Settings.EMULATED_FUNCTION_POINTERS and not Settings.EMULATE_FUNCTION_POINTER_CASTS) or not Settings.LEGALIZE_JS_FFI
    +    return ('asmjs' not in Settings.BINARYEN_METHOD and 'interpret-asm2wasm' not in Settings.BINARYEN_METHOD and not Settings.RUNNING_JS_OPTS and not Settings.EMULATE_FUNCTION_POINTER_CASTS) or not Settings.LEGALIZE_JS_FFI
     
       @staticmethod
       def get_safe_internalize():

**Comment by kripken** [comment]
Good start, nice. I'd look next at `python tests/runner.py binaryen*`.

**Comment by kripken** [comment]
This affects dynamic linking since wasm shared modules currently use emulated function pointers.

**Comment by waterlike86** [comment]
in my own project we need this too, and after making the same patch as tbfleming, i found that some of the binaryen tests were failing. Most of them fails because of the same reason, and its demonstated by test_legalize_js_ffi , with error -> AssertionError: i64 not converted to i32 in exports.
seems like its similar to this issue https://github.com/kripken/emscripten/issues/5370. any idea where it might be causing the problem?

**Comment by kripken** [comment]
Not sure offhand. Does the workaround in the last comment in that other issue help you?

Otherwise, it would be good if someone had time to look into the general issue here. I can try to do that, but it might not be soon.

**Comment by kripken** [comment]
I opened #7036 which enables async compilation with `EMULATE_FUNCTION_POINTER_CASTS`. Turns out that just required some test updates.

It would also be good to see if that flag can work in wasm-only mode, but that's no longer blocking async compilation, with that PR.
