### ISSUE TITLE
Missing GL entrypoint for emscripten_GetProcAddress

### ISSUE THREAD

**Issue by fabiansperber** [kripken/emscripten#5583]
At least one entry point (glIsVertexArray) is missing from emscripten_GetProcAddress() in 'system/lib/gl.c'.

The API entry for glIsVertexArray (emscripten_glIsVertexArray) is already existing, only the match in the lookup function is missing.

**Comment by kripken** [comment]
Thanks, fixed in 51bd99dae9c9e57559378c6cbdcfab839fbf86bc.
