### ISSUE TITLE
ALLOW_MEMORY_GROWTH not supported with -s MAIN_MODULE and -s WASM=1

### ISSUE THREAD

**Issue by Auron52** [kripken/emscripten#5585]
Currently the error "memory growth is not supported with shared modules yet" is thrown when building with the options
-s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -s MAIN_MODULE=2
From this discussion: https://groups.google.com/forum/#!topic/emscripten-discuss/zZsG7spmdug it appears this error is unnecessary when generating WASM.

**Comment by kripken** [comment]
I ran the test suite and don't see anything we are missing, definitely looks like it should be enabled. Fix in #5589.

**Comment by kripken** [comment]
Fixed on incoming.
