### ISSUE TITLE
WASM shared modules export unnecessary symbols even with -s MAIN_MODULE 2 

### ISSUE THREAD

**Issue by Auron52** [kripken/emscripten#5586]
See the discussion at https://groups.google.com/forum/#!topic/emscripten-discuss/zZsG7spmdug for background. 

The basic issue is that WASM builds with -s MAIN_MODULE 2 can be unnecessarily large due to extra symbols being exported.

The sample at https://drive.google.com/open?id=0B462aSLeSsPMUFhnNW1iYzhjeHM can be used to reproduce the problem. The zip also includes the output
Build with default MAIN_MODULE=0: 66 KB .js file and 38 KB .wasm file
Build with -s MAIN_MODULE 2: 173 KB .js file and 48 KB .wasm file

Alon Zakai's Comment: "Looking at this, the main module 2 is 23% larger. Looks like much of that is due to us exporting all the functions in the table (which limits dce). I think we don't need that for wasm shared modules, this is just something that wasn't optimized yet."

**Comment by Shchvova** [comment]
This is exactly issue I'm having when trying to use dynamic linking. Just adding -s MAIN_MODULE 2 increases output size dramatically. Are there any updates on this issue?

**Comment by tasakm** [comment]
We too are facing same issue trying to use dynamic linking, WASM binary's size is increasing 3 fold. Is there any workaround to this issue? or any updates the way we can use dynamic linking?

**Comment by kripken** [comment]
There have been a bunch of improvements in this area. Try MAIN_MODULE mode 2 on latest incoming, it may be better. However, there are still a bunch of other things that could be done here to improve things, still a work in progress. In particular, see

https://github.com/kripken/emscripten/issues/7189#issuecomment-430047843

Would be good if someone had time to investigate that option.
