### ISSUE TITLE
very slow launch on Firefox

### ISSUE THREAD

**Issue by mchiasson** [kripken/emscripten#5591]
I was testing my emscripten-compiled app on various browsers, and noticed that it was extremely slow to launch my app on Firefox, where is launches near instantly on Chrome. 
Even after all of my assets are cached in the web browser from my first launch, it takes 4 minutes and 44 seconds to launch the app after a refresh. It gets stuck at `Downloading...`, but from the Network tab of the developer tool, it looks like it is not downloading anything. I also noticed that firefox takes 100% of one CPU core during the entire period.

This behaviour was observed on Firefox 55.0.2 (64-bit) for Ubuntu. I've also seen the same exact behaviour on my colleague's Mac in Firefox, but I do not know which version of Firefox he is using.

Any idea? It could be a bug in Firefox too, I don't know.

I have the app hosted on a private server. I can send it to you via a private message if you want to see for yourself.

Thanks!

**Comment by kripken** [comment]
Definitely strange...

What webserver is that with? What does the profiler show during that 100% CPU time?

Yeah, if those don't help isolate the problem, please send me a private message with the steps to reproduce.

**Comment by mchiasson** [comment]
Here is the performance profile report from firefox's built-in dev tool.
[profile.json.zip](https://github.com/kripken/emscripten/files/1322481/profile.json.zip)

**Comment by mchiasson** [comment]
the profiler shows that it spent 240s on Gecko. I am not sure how to interpret this.

**Comment by mchiasson** [comment]
@kripken any idea?

**Comment by mchiasson** [comment]
We are sort of seeing a delay on Safari 11 as well, but it's not as bad as firefox. It takes maybe a minute to launch after the download (while being stuck at the last byte of 'Downloading...')

**Comment by kripken** [comment]
Yeah, the profile says the time is spent in Gecko without more details, weird. This might be hitting a profiler bug. Was that on Firefox nightly? (might be better there) Another option is to use your system profiler on Firefox nightly (it has debug info symbols, so it should work).

Could you make a build we can debug directly?

**Comment by mchiasson** [comment]
I've temporarily hosted the app here:

http://138.197.196.76/Emscripten/ClothUIWASM/

**Comment by mchiasson** [comment]
no, that was not on Firefox nightly. We're using Firefox v55.0.3 (latest official release)

**Comment by kripken** [comment]
Thanks for the build! Ok, profiling on linux using perf, I see that it indeed looks like a serious issue, something with JS string processing speed. I filed [this issue for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1402958).

Meanwhile, please keep that link available so that they can investigate.

Btw, based on the profiling info I saw, the issue is due to text rendering speed. So a workaround might be to change how the page shows text - maybe it updates the status text on each byte received from the downloading files, or something like that?

**Comment by mchiasson** [comment]
> Meanwhile, please keep that link available so that they can investigate.
will do.

text rendering? Interesting. I'll try commenting out the `Module.setStatus` javascript function entirely and see if that helps.

**Comment by mchiasson** [comment]
after locally commenting out the content of `Module.setStatus` and even removing the spinner and the status elements from the web page, nothing really changed. Firefox is still bogged down. Thank you so much @kripken for profling this, and filing this issue at mozilla. Much appreciated!

**Comment by kripken** [comment]
Btw, more profiling shows it probably isn't rendering - which makes sense with what you said about it not improving when you removed that part. I think it's a compiler bug, see more details in that link.

**Comment by juj** [comment]
I can reproduce on Windows 10 Home with Intel Core i7-5960X and Firefox Nightly 58.0a1 (2017-10-01) (64-bit). However with the new wasm baseline tiering feature (https://bugzilla.mozilla.org/show_bug.cgi?id=1391196), the page does load up instantaneously, it is just the full compilation that hangs for a long time.

**Comment by mchiasson** [comment]
>  I assume the demo was not changed? 
You assumed correctly. I did not change the demo.

**Comment by kripken** [comment]
The firefox issue has been fixed, I verified that the problem is gone on current nightly. Thanks again for reporting this!

**Comment by igagis** [comment]
I'm seeing the same problem now in Firefox 128.12.0esr (64-bit) on Debian Bookworm.
Here is the app: https://gagistech.com/apps/bedsidemon-opengles-sdl.html

On Firefox it starts in about 10 seconds.
On Chromium it starts in about 1 second.
