### ISSUE TITLE
bind : Implicitly binding raw pointers is illegal

### ISSUE THREAD

**Issue by ssx71** [kripken/emscripten#5599]
I need to pass a simple c string to a function, as indicate in the source below,
but compiler fails to generate code. yet i cannot use pointer in function
void f1( int * value ) , emscriptern generates same error.

source code :

	#include <emscripten.h>
	#include <emscripten/bind.h>
	 
	void f1( const char *  value ) 
	{
	 printf( "#f1 <<%s>>\n",value );
	}
	EMSCRIPTEN_BINDINGS(emjq1) 
	{
		emscripten::function("f1", &f1);
	}

	int main( void )
	{
		emscripten_run_script ( " Module.f1 ( 'Hello world' )  ;" ) ;

		return 0 ;
	}

emscripten error 

	C:\xampp\htdocs\emjq>emcc -std=c++11 errore.cpp --bind -o main.js

	In file included from errore.cpp:3:
	In file included from C:\emscripten\emscripten\1.37.1\system\include\emscripten/bind.h:14:
	In file included from C:\emscripten\emscripten\1.37.1\system\include\emscripten/val.h:8:
	C:\emscripten\emscripten\1.37.1\system\include\emscripten/wire.h:90:13: error: static_assert failed "Implicitly binding raw pointers is illegal.  Specify allow_raw_pointer<arg<?>>"
				static_assert(!std::is_pointer<T*>::value, "Implicitly binding raw pointers is illegal.  Specify allow_raw_pointer<arg<?>>");
				^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
	C:\emscripten\emscripten\1.37.1\system\include\emscripten/wire.h:186:53: note: in instantiation of template class 'emscripten::internal::TypeID<const char *>' requested here
					static constexpr TYPEID types[] = { TypeID<Args>::get()... };
														^
	C:\emscripten\emscripten\1.37.1\system\include\emscripten/wire.h:209:24: note: in instantiation of member function 'emscripten::internal::ArgArrayGetter<emscripten::internal::TypeList<void,
		  const char *> >::get' requested here
						>::get();
						   ^
	C:\emscripten\emscripten\1.37.1\system\include\emscripten/bind.h:423:18: note: in instantiation of member function 'emscripten::internal::WithPolicies<>::ArgTypeList<void, const char
		  *>::getTypes' requested here
				args.getTypes(),
					 ^
	errore.cpp:12:17: note: in instantiation of function template specialization 'emscripten::function<void, const char *>' requested here
		emscripten::function("f1", &f1);
					^
	1 error generated.
	ERROR:root:compiler frontend failed to generate LLVM bitcode, halting

**Comment by AlexPerrot** [comment]
Hi,
First, have a look at the doc concerning raw pointers binding [here](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#raw-pointers).

Second, even using `allow_raw_pointers`, I think it won't work, since native types pointers are not bound.

Third, embind is oriented toward binding C++ constructs, but you're only using C. You can either use `cwrap` to access the C functions or switch to a C++ `string`.

**Comment by ssx71** [comment]
thanks to Alex for your clarification.
