### ISSUE TITLE
Bad double -> uint32 conversion when using clamp trap mode

### ISSUE THREAD

**Issue by kumpera** [kripken/emscripten#5603]
Test case:
```
#include <stdio.h>
#include <stdlib.h>

static double *bla;

int main (int argc, char *argv[]) {
	int i = 0;
	bla = malloc (8 * 16);
	for (i = 0; i < 16; ++i)
		bla[i] = 4294967295.0;
	unsigned int x = (unsigned int)bla[6];
	printf ("x is %f x is %x\n", bla[6], x);
	return 0;
}
```

How to compile it:
```
emcc -s "BINARYEN_TRAP_MODE='clamp'" -Os -g  -s WASM=1 repro.c -o repro.html
```

It prints `x is 4294967295.000000 x is 80000000`

The expected value for x is ffffffff and it works as expected if BINARYEN_TRAP_MODE is not passed.

**Comment by kripken** [comment]
Thanks, yeah, looks like in `clamp` mode we currently just clamp to `[-2147483648..-2147483648)]`, which is indeed odd for an unsigned conversion. We should clamp to unsigned values when the operation is an unsigned one.

@jgravelle-google, this would change the clamping code a little, so it could conflict with https://github.com/WebAssembly/binaryen/pull/1168/, should I wait for that to land first?

**Comment by jgravelle-google** [comment]
I did notice that while working through that. I can add it to that PR if you don't mind

**Comment by kripken** [comment]
Sounds good. Meanwhile I did a little experimenting and wrote [this patch](https://github.com/WebAssembly/binaryen/commit/573c2493362205481fc2cb9a4f6a9325e2633fd0), so that might help (or feel free to ignore and do it your way).
