### ISSUE TITLE
MSVCP140.dll not found

### ISSUE THREAD

**Issue by k2snowman69** [kripken/emscripten#5605]
I started setting up a new machine and have been following the steps from here for Windows:
https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

When I run emcc I now get an exception saying MSVCP140.dll is required along with another dll. I know these are installed with Visual Studio (how I've worked around it currently) but curious if Visual Studio is a known pre-requisite for emcc to work. 

If Visual Studio is a prerequisite for emcc it should be documented on the install instructions
If not then there is a bug that these dlls should be included in the portable sdk drop

**Comment by dschuff** [comment]
You should be able to just use the redistributable, e.g. https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by k2snowman69** [comment]
I'll give that a shot thanks! Still doesn't change the fact it needs to be documented in those instructions though... keeping this open to track that work.
