### ISSUE TITLE
Warning Chrome : Invalid asm.js: Unexpected token 

### ISSUE THREAD

**Issue by ssx71** [kripken/emscripten#5616]
I've compiled multiple sources without rewriting this warning, 
but in my file, Chrome returns a warning, everything works anyway
OK in Firefox and Edge.

	chrome 61 : Emscripten 1.37.21 : window 10 pro

		 while((ptr|0) <= (block_aligned_end|0)) {
			HEAP32[((ptr)>>2)]=value4;                <-- Warning
			HEAP32[(((ptr)+(4))>>2)]=value4;
			HEAP32[(((ptr)+(8))>>2)]=value4;
			HEAP32[(((ptr)+(12))>>2)]=value4;
			HEAP32[(((ptr)+(16))>>2)]=value4;
			HEAP32[(((ptr)+(20))>>2)]=value4;
			HEAP32[(((ptr)+(24))>>2)]=value4;
			HEAP32[(((ptr)+(28))>>2)]=value4;
			HEAP32[(((ptr)+(32))>>2)]=value4;
			HEAP32[(((ptr)+(36))>>2)]=value4;
			HEAP32[(((ptr)+(40))>>2)]=value4;
			HEAP32[(((ptr)+(44))>>2)]=value4;
			HEAP32[(((ptr)+(48))>>2)]=value4;
			HEAP32[(((ptr)+(52))>>2)]=value4;
			HEAP32[(((ptr)+(56))>>2)]=value4;
			HEAP32[(((ptr)+(60))>>2)]=value4;
			ptr = (ptr + 64)|0;
		  }
![immagine](https://user-images.githubusercontent.com/24575473/31047426-ce3c02c2-a60a-11e7-931e-a9b1ea33ae76.png)

**Comment by kripken** [comment]
Sounds like a bug in Chrome's new asm.js validation. Should probably file a bug on Chrome for this. cc @flagxor

**Comment by ssx71** [comment]
Done : [https://github.com/dherman/asm.js/issues/127](url)

**Comment by ssx71** [comment]
Done : [https://github.com/dherman/asm.js/issues/127]

**Comment by ssx71** [comment]
done :   [https://github.com/dherman/asm.js/issues/127](url)

**Comment by ssx71** [comment]
👍 https://github.com/dherman/asm.js/issues/127

**Comment by dschuff** [comment]
@ssx71 The place for V8 bugs is https://bugs.chromium.org/p/v8
When you post there it would probably be helpful to attach a wasm file as a reproducer, if you can.

**Comment by ssx71** [comment]
it will be so. I'm doing some other tests to reproduce warningbetter. you can close it.

**Comment by kripken** [comment]
Closing in favor of that v8 issue, thanks.
