### ISSUE TITLE
pre-js is not before all generated code when using modularize

### ISSUE THREAD

**Issue by k2snowman69** [kripken/emscripten#5622]
I'm attempting to create a universal module loader wrapper around an emscripten module and have a slightly frusterating bug in my way.

In the documentation, it says
```
"--pre-js <file>"
   Specify a file whose contents are added before the generated code.
   This is done *before* optimization, so it will be minified properly
   if the *Closure Compiler* is run.
```

Sadly when this flag is used in conjunction with `-s MODULARIZE=1` pre-js isn't actually put before all generated code.

```
// This looks like it's actually the modularize code
var Module = function(Module) {
  Module = Module || {};
  var Module = Module;

// Start of pre-js code
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports"], factory);
    }
    else {
        return factory(null, null);
    }
})(function (require, exports) {

// The Module object: Our interface to the outside world. We import
// and export values on it, and do the work to get that through
// closure compiler if necessary. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..generated code.. }
// 3. pre-run appended it, var Module = {}; ..generated code..
// 4. External script tag defines var Module.
// We need to do an eval in order to handle the closure compiler
// case, where this code here is minified but Module was defined
// elsewhere (e.g. case 4 above). We also need to check if Module
// already exists (e.g. case 3 above).
// Note that if you want to run closure, and also to use Module
// after the generated code, you will need to define   var Module = {};
// before the code. Then that object will be used in the code, and you
// can continue to use Module afterwards as well.
var Module;
if (!Module) Module = (typeof Module !== 'undefined' ? Module : null) || {};
```

This means that the Modularize code is coming before the pre-js code.

Is it possible to either move the pre-js and post-js so that they wrap the Modularized code? Or add new params to allow pre-modularize and post-modularize? 

If the latter is selected as a solution, the documentation for pre-js and post-js should be updated.

**Comment by kripken** [comment]
Yeah, some generated code is put before in the Modularize case. That is intentional, though - as mentioned in the help you quoted, the goal with --pre-js is to let the code be properly optimized with the generated code. For that, we have to put it inside the Modularize-generated function, and after the lines handling Module.

Your code looks like it should be outside the Modularize function itself, and doesn't need to be optimized together, so you can just manually prepend it after running emcc, that might be easiest.

**Comment by kripken** [comment]
And yeah, the docs could elaborate on this, I agree. A PR with the kind of text you would have benefited from would be very welcome.

**Comment by k2snowman69** [comment]
For reference, I'm trying to wrap this code into a universal module definition. My current work around has been to manually write the pre-js to contain both the umd and the modularized code. Here is the output I was trying to get (annotated with what goes where)
```
// UMD prefix code
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
      var v = factory(require, exports);
      if (v !== undefined) {
        module.exports = function (moduleParams) {
            return v(moduleParams);
        };
      }
    }
    else if (typeof define === "function" && define.amd) {
      define(["require", "exports"], function (require, exports) {
        var v = factory(require, exports);
        return function (moduleParams) {
          return v(moduleParams);
        };
      });
    }
    else {
      Module = factory(null, null);
    }
  })(function (require, exports) {


   // -s MODULARIZE=1
    var Module = function (Module) {
      Module = Module || {};
      var Module = Module;


   // The generated code
   ...
```

My work around seems to work but having to rewrite the modularize code (even though it is small) is a bit annoying (duplication of code and all).

I'm currently in and out of wifi but when I get back to the mainland I'll write up a PR for the comment update.
