### ISSUE TITLE
Reduce the JS file size when using WASM

### ISSUE THREAD

**Issue by GregSlazinski** [kripken/emscripten#5627]
I've just successfully compiled my application with WebAssembly, previous JS file size was 13 MB and the new WASM file size is 3.5 MB so that's a great reduction in size.

However I've noticed that the new JS size has 401,812 bytes, and it doesn't look like it's optimized.
Example contents from the new JS size:
```
var ENVIRONMENT_IS_WEB = false;
var ENVIRONMENT_IS_WORKER = false;
var ENVIRONMENT_IS_NODE = false;
var ENVIRONMENT_IS_SHELL = false;
if (Module["ENVIRONMENT"]) {
 if (Module["ENVIRONMENT"] === "WEB") {
  ENVIRONMENT_IS_WEB = true;
 } else if (Module["ENVIRONMENT"] === "WORKER") {
  ENVIRONMENT_IS_WORKER = true;
 } else if (Module["ENVIRONMENT"] === "NODE") {
  ENVIRONMENT_IS_NODE = true;
 } else if (Module["ENVIRONMENT"] === "SHELL") {
  ENVIRONMENT_IS_SHELL = true; 
```
Would it be possible if the JS file that's used together with WASM could be provided as already optimized version? using something like Closure Compiler or asm.js? (I'm a noob when it comes to optimizing JS files)

Thanks!
Greg

**Comment by kripken** [comment]
What options are you using? By default, optimized builds should minify the JS. For example `emcc tests/hello_world.c -O2 -s WASM=1` emits JS that starts with `var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(va [..]`.

You can additionally use closure compiler to further shrink the JS, with `--closure 1`.

**Comment by GregSlazinski** [comment]
Thank you, for some reason I had minification disabled (--minify).
After I've reset this to default settings, I'm getting same results as you.
The JS file is now 336,940 bytes in size.

I've tried to use also --closure 1, however when I use it (together with WASM).
Then upon loading my application using Google Chrome, I get the error:
```
Uncaught TypeError: c.Ya is not a function
    at _alcCreateContext (http://esenthel.com/Application/Application.js:242:229)
    at wasm-function[4285]:106
    at wasm-function[4123]:246
    at wasm-function[4121]:62
    at d._FileSystemReady (http://esenthel.com/Application/Application.js:339:283)
    at ra (http://esenthel.com/Application/Application.js:14:104)
    at http://esenthel.com/Application/Application.js:45:255
    at c (http://esenthel.com/Application/Application.js:130:57)
    at e (http://esenthel.com/Application/Application.js:130:130)
    at Object.Ic (http://esenthel.com/Application/Application.js:113:512)
```
if I disable closure compiler, it works fine.

I'm using
-o "D:\Projects\_Build_\Application\Emscripten\Release DX9\Application.html" -O2 "C:\Esenthel\Editor/Bin/EsenthelEngine.bc"
--memory-init-file 1 -s ALLOW_MEMORY_GROWTH=1 -s USE_WEBGL2=1 -s WASM=1

**Comment by kripken** [comment]
Closure compiler can be tricky to get working, if you add any additional JS or depend on the JS from the outside in ways that are [invalid for closure advanced mode](https://developers.google.com/closure/compiler/docs/api-tutorial3).

If you're not adding any JS, then you may be hitting an unknown bug - can you provide a full testcase that shows the issue?

**Comment by GregSlazinski** [comment]
Hello,
I'm submitting the test case:
https://www.dropbox.com/s/vkkypzfi1nwzumg/ClosureCompilerBug.7z?dl=0

1) Open ClosureCompilerBug\_Build_\Application\Project.sln in Visual Studio
2) Build Project
3) Upload files from "ClosureCompilerBug\_Build_\Application\Emscripten\Release DX9" folder:
Application.html
Application.js
Application.wasm
to a Web Server
4) Run "Application.html" from the web server.
Get crash:
Uncaught TypeError: c.Ya is not a function
    at _alcCreateContext (http://esenthel.com/Application2/Application.js:245:309)
    at wasm-function[4286]:106
    at wasm-function[4129]:246
    at wasm-function[4127]:62
    at d._FileSystemReady (http://esenthel.com/Application2/Application.js:342:283)
    at ra (http://esenthel.com/Application2/Application.js:14:104)
    at http://esenthel.com/Application2/Application.js:42:469
    at c (http://esenthel.com/Application2/Application.js:128:57)
    at e (http://esenthel.com/Application2/Application.js:128:128)
    at Object.Kc (http://esenthel.com/Application2/Application.js:112:32)

5) If you disable Closure compiler through "Visual Studio Project Settings \ Emcc Linker \  Force Closure... to - No (--closure 0)" and repeat the build/upload steps you will see that there's no crash.

In that case the app will try to load some data PAK's and just return an error that it's missing (because it's not included in the test case = it's okay).

The calls to 'alcCreateContext '
are done inside the static library "ClosureCompilerBug\EsenthelEngine.bc"

**Comment by kripken** [comment]
Is there a way to build it without visual studio? Maybe just provide the bitcode and skip the compiling to source part.

**Comment by GregSlazinski** [comment]
Hi,
Is this okay?
https://www.dropbox.com/s/ixxis61rcj71jzh/ClosureCompilerBug.7z?dl=0
Please look inside "bc only\*.bc"
or alternatively "bc+o\*" which has bc, o, html js and wasm too.

**Comment by kripken** [comment]
I unpacked that, then built with `emcc EsenthelEngine.bc -o a.html -Os --profiling -s WASM=1`, then ran the html in a webserver. I see errors in the server log,
````
127.0.0.1 - - [20/Nov/2017 12:30:47] code 404, message File not found
127.0.0.1 - - [20/Nov/2017 12:30:47] "GET /Engine.pak HTTP/1.1" 404 -
127.0.0.1 - - [20/Nov/2017 12:30:47] code 404, message File not found
127.0.0.1 - - [20/Nov/2017 12:30:47] "GET /Project.pak HTTP/1.1" 404 -
````
and I think the app won't load because of that, it hangs on 100% CPU with no rendering.

**Comment by GregSlazinski** [comment]
Hi,
those files are in the other folder, you can just copy them. However you don't really need them, because if the application reached the stage when it tries to load the Pak files, it means there's no error. The OpenAl initialized ok.
now if you use the closure optimization it won't run OK, it won't reach this stage.

**Comment by kripken** [comment]
I see, thanks.

Trying with closure, I see some errors. Most are fixed by the last merge to incoming, another by https://github.com/kripken/emscripten/pull/5824 - but there is an EM_ASM from your code which causes an error too, `ERROR - variable Ci is undeclared`.

**Comment by GregSlazinski** [comment]
Is that a problem with Closure Compiler or with my JS being badly formatted or something?
I can paste here all EM_ASM calls, if you want, I don't have many of them, only 5.

**Comment by kripken** [comment]
It's probably something that is valid JS but that closure compiler says is an error (we recently upgraded, so it has more errors it detects). Like using a variable without declaring it. Yeah, if you can't figure it out, paste a link to them.

**Comment by kripken** [comment]
It's that `Ci.nsIHttpChannel` - what is `Ci`?

**Comment by GregSlazinski** [comment]
Hi,
I copy pasted this from:
https://github.com/kripken/emscripten/blob/incoming/src/library_browser.js#L916

**Comment by togekk** [comment]
Hi, this error occurs when I'm using emscripten_async_wget2_data too. I'd like to know if this bug is fixed? Thanks!

**Comment by kripken** [comment]
Well, looks like noone knows what that `Ci` stuff is, so I opened #6349 to remove it.

**Comment by kripken** [comment]
That PR landed and the code was removed, so I think we can close this issue.
