### ISSUE TITLE
__int128 is not supported on this target

### ISSUE THREAD

**Issue by notgiven688** [kripken/emscripten#5630]
I have troubles compiling my source code which compiles fine using g++. I am trying to create a webassembly. I get an "__int128 is not supported on this target" compilation error and although the error description is quite clear in itself I do not understand the implications. Is my target wrong? I downloaded and build the SDK. The version is

`em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.37.21 (commit 5d18b58b00c45bced5f4cea4d233cf86eb1af2c3)
`
Thank you very much for some insights into this error.

**Comment by kripken** [comment]
wasm is a 32-bit target, and has 32 and 64 bit integers, but not 128, and the toolchain doesn't have emulation for 128-bit integers currently.

If all you need is simd operations on a 128-bit value, see the `vector.h` header.

**Comment by notgiven688** [comment]
Thank you very much!
