### ISSUE TITLE
Mount IDBFS to root "/" path

### ISSUE THREAD

**Issue by GregSlazinski** [kripken/emscripten#5632]
I'm trying to mount IDBFS to "/" to make entire filesystem persistent:
`FS.mount(IDBFS, {}, '/');`
However this generates an exception device busy.
Since MEMFS is mounted to "/" by default, I've tried to unmount it using:
`FS.unmount('/'); `
But then I get an exception thrown: Error: Invalid argument,Error

Is it not possible to mount IDBFS to "/" ?

**Comment by kripken** [comment]
Yes, there is a current limitation on not being able to mount the root dir, see https://github.com/kripken/emscripten/issues/2040
