### ISSUE TITLE
What's the simplest way to pre-generate all system libraries?

### ISSUE THREAD

**Issue by SaschaNaz** [kripken/emscripten#5633]
I want to build a Docker image for emscripten that has all supported prebuilt system libraries (e.g. libc.bc) so that each Travis test job doesn't have to generate them by themselves.

Is there a convenient way to do this?

**Comment by dschuff** [comment]
emscripten has a utility `embuilder.py` which can do that. So you can pick which libraries you want or do `embuilder.py build ALL` to build everything (IIRC).

**Comment by SaschaNaz** [comment]
That works, thanks!
