### ISSUE TITLE
Some system libraries are not included on embuilder

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5638]
The list includes dlmalloc_debug.bc, libcxx_noexcept.bc, al.bc, html5.bc, and compiler-rt.bc (which are required by test_dylink_syslibs)

**Comment by SaschaNaz** [comment]
Great, but test_dylink_syslibs requires libcxx_no_except as a bc file, not sure why.

**Comment by dschuff** [comment]
Looking at the code for dylink_syslibs, it's not at all obvious to me how that's supposed to work (those filenames are not even mentioned), and it does work for me. Maybe @kripken recalls more?

**Comment by kripken** [comment]
Hmm, `system_libs.py` creates `libcxx` as a `.a` file (also the `_noexcept` variant). But I do see that test creates it as a `.bc` file. It shouldn't do that, so I think we have a bug in `system_libs.py`, somehow there is a code path to the creation of libcxx that specifies a `.bc` suffix.

**Comment by SaschaNaz** [comment]
I found these lines force `.bc` suffix when forcing syslibs:

https://github.com/kripken/emscripten/blob/6f9e2302213cbe85cbc9429f547f66c7b2524caa/tools/system_libs.py#L469-L470

**Comment by kripken** [comment]
Oh right, thanks. Yeah, when we force system libs, we build them to bc files, so all their code is always included.

So embuilder should be made capable of building that variant.

**Comment by kripken** [comment]
Wrote #5675 to add .bc building for .a libraries.
