### ISSUE TITLE
Is hasInlineJS still used?

### ISSUE THREAD

**Issue by erikdubbelboer** [kripken/emscripten#5642]
`use asm` vs `almost asm` depends on `hasInlineJS` but I can't find any place where this could be set. See:
https://github.com/kripken/emscripten/blob/37b3124e757c1d5b2468d0137f01122fbef9d960/emscripten.py#L1500-L1502

**Comment by kripken** [comment]
Yeah, the metadata arrives from the backend, and looks like it was removed from there. I think in the far past we literally inlined JS from `asm` blocks, and so when there was inline JS we disabled "use asm". But we moved to a model where the `asm` blocks are on the outside of the asm.js module. So we could remove that check, PR welcome.

**Comment by kripken** [comment]
Fixed by that PR.
