### ISSUE TITLE
Call C++ function from javascript (emscripten) 

### ISSUE THREAD

**Issue by MichalPetryk** [kripken/emscripten#5651]
Hi,

I'm trying to call c++ function definied in my Application class (base class for Urho3D app) from javascript, but with no success.

My application class definition is:

<pre>
SharedPtr<Text> helloText;
public: SampleApplication(Context * context) : Application(context) {}
void CreateText()
	{
		helloText=new Text(context_);
		helloText->SetText("Hello!");
		helloText->SetFont(cache->GetResource<Font>("Fonts/Anonymous Pro.ttf"), 30);
		helloText->SetColor(Color(0.0f, 1.0f, 0.0f));
		helloText->SetHorizontalAlignment(HA_CENTER);
		helloText->SetVerticalAlignment(VA_CENTER);
		GetSubsystem<UI>()->GetRoot()->AddChild(helloText);
	}
public: void ChangeTextFromJs()
{
	helloText->SetText("Hello from JS!");
}
</pre>

I want to call public function ChangeTextFromJs in my javascript code (after click some html button).

<pre>
<script type='text/javascript'>
      var Module = {
        preRun: [],
        postRun: [],
        print: (function() {
.....
</pre>

**Comment by gogoprog** [comment]
What have you tried?
Have you read https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#embind ?

**Comment by MichalPetryk** [comment]
Hi @gogoprog! Thanks for quick reply! I have tried embind, but i can't make it works with Urho3D...

I added to my code:
<pre>
EMSCRIPTEN_BINDINGS(Module) {
    class_<SampleApplication>("SampleApplication").constructor<Context *>()
      .function("ChangeText", &SampleApplication::ChangeText);
   }
</pre>

But when i run command: mingw32-make.exe i got error:

<pre>
[ 50%] Linking CXX executable bin\File.js
error: unresolved symbol: _embind_register_class
error: unresolved symbol: _embind_register_class_function
error: unresolved symbol: _embind_register_class_constructor
Aborting compilation due to previous errors | undefined
Traceback (most recent call last):
  File "C:\emsdk-portable\emscripten\1.37.9\\em++", line 16, in <module>
    emcc.run()
  File "C:\emsdk-portable\emscripten\1.37.9\emcc.py", line 1673, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "C:\emsdk-portable\emscripten\1.37.9\tools\shared.py", line 1963, in emscripten
    call_emscripten(cmdline)
  File "C:\emsdk-portable\emscripten\1.37.9\emscripten.py", line 1852, in _main
    temp_files.run_and_clean(lambda: main(
  File "C:\emsdk-portable\emscripten\1.37.9\tools\tempfiles.py", line 78, in run_and_clean
    return func()
  File "C:\emsdk-portable\emscripten\1.37.9\emscripten.py", line 1857, in <lambda>
    DEBUG=DEBUG,
  File "C:\emsdk-portable\emscripten\1.37.9\emscripten.py", line 1758, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "C:\emsdk-portable\emscripten\1.37.9\emscripten.py", line 93, in emscript
    glue, forwarded_data = compiler_glue(metadata, settings, libraries, compiler_engine, temp_files, DEBUG)
  File "C:\emsdk-portable\emscripten\1.37.9\emscripten.py", line 296, in compiler_glue
    cwd=path_from_root('src'), error_limit=300)
  File "C:\emsdk-portable\emscripten\1.37.9\tools\jsrun.py", line 122, in run_js
</pre>

**Comment by gogoprog** [comment]
I guess you are missing the `--bind` flag on the `emcc` command line.
I don't know if Urho3D provides something to allow this...

**Comment by MichalPetryk** [comment]
@gogoprog you are right, i missed <code>--bind</code> in my build command. I use <code>mingw32-make</code> command to build my project and it doesn't provide to use<code>bind</code> flag. Finally i found solution. I have edited link.txt file in CMakeFiles directory by adding <code>--bind</code> on existing command.

Thank you for your help!
