### ISSUE TITLE
Browser test on Travis

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5660]
Not really familiar yet with the `browser` test set but probably Firefox headless mode can help here.

**Comment by juj** [comment]
Chatted with Alon yesterday about the browser tests on Travis, and the thinking here was that we should probably focus on using the test time that Travis gives on the default and other suites, and then keep the browser runs on the bots.

**Comment by SaschaNaz** [comment]
Travis time limit is for each job, not each build.

https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts

>There is no timeout for a build; a build will run as long as all the jobs do as long as each job does not timeout.

So I think it won't relaly matter.

**Comment by kripken** [comment]
I saw this helpful writeup on Twitter, of how to run full browser tests on Travis,

http://devosoft.org/javascript-testing-on-travis-ci-with-karma-and-mocha/

Maybe we could do what's described there?

**Comment by saschanaz** [comment]
The post mentions PhantomJS which is expected to die since the launch of Headless Chrome. https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

And we have #5668, which is Chrome side bug. Maybe we should skip some tests...

**Comment by kripken** [comment]
There may be a browser pref for firefox that allows popups. And maybe there's a way to set prefs from the firefox CLI?

**Comment by saschanaz** [comment]
I hope there is one but I can't find it here. https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options

**Comment by saschanaz** [comment]
We may do iframe way, which would be comfortable with popup blockers.

**Comment by kripken** [comment]
I like the iframe idea, that's worth trying. If it works it might be better anyhow for other reasons (no extra tabs left open, etc.). But it would take some work in the test runner.

If that doesn't work out, then looks like Firefox has
````
  --profile <path>   Start with profile at <path>.
````
And there are [options that control popups](https://superuser.com/questions/697018/how-to-disable-popups-in-firefox-without-add-ons). So we could create a firefox profile file once with the right options, and add that file in the repo (`tests/firefox.profile` perhaps), then on the bot, use that profile.

**Comment by saschanaz** [comment]
https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js

This code shows how we can create a custom profile, so we may try same thing to disable the blocker.

**Comment by saschanaz** [comment]
Maniging a Firefox profile is [more complicated In my understanding](http://kb.mozillazine.org/Profile_folder_-_Firefox), not sure what the package does yet.
