### ISSUE TITLE
browser.test_cubegeom_pre fails with headless chromium-browser

### ISSUE THREAD

**Issue by SaschaNaz** [kripken/emscripten#5668]
```
$ EMSCRIPTEN_BROWSER="chromium-browser --disable-gpu --headless --disable-popup-blocking --remote-debugging-port=9222" python2 emscripten/tests/runner.py browser.test_cubegeom_pre
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
Test suites:
['test_browser']
Running test_browser: (1 tests)
[Browser harness server on process 129]

Running the browser tests. Make sure the browser allows popups from localhost.

test_cubegeom_pre (test_browser.browser) ... [browser launch: test.html ]
[server response: /report_result?10 ]
ERROR
[Browser harness server terminated]

======================================================================
ERROR: test_cubegeom_pre (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saschanaz/emscripten/tests/test_browser.py", line 1752, in test_cubegeom_pre
    self.btest('cubegeom_pre.c', reference='cubegeom_pre.png', args=['-s', 'LEGACY_GL_EMULATION=1', '-lGL', '-lSDL'])
  File "/home/saschanaz/emscripten/tests/runner.py", line 968, in btest
    self.run_browser(outfile + url_suffix, message, ['/report_result?' + e for e in expected], timeout=timeout)
  File "/home/saschanaz/emscripten/tests/runner.py", line 810, in run_browser
    self.assertIdentical(expectedResult, output)
  File "/home/saschanaz/emscripten/tests/runner.py", line 485, in assertIdentical
    limit_size(''.join([a.rstrip()+'\n' for a in difflib.unified_diff(x.split('\n'), y.split('\n'), fromfile='expected', tofile='actual')]))
Exception: Expected to have '/report_result?0' == '/report_result?10', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+/report_result?10


----------------------------------------------------------------------
Ran 1 test in 7.354s

FAILED (errors=1)
```

Not sure why as test_cubegeom_color passes. Any clue why this happens?

(I won't open a PR for Travis `browser` test unless there is an explicit agreement on #5660)

**Comment by kripken** [comment]
Does it pass on firefox on the same machine? And what does the rendered image look like - anything similar to what it should (`tests/cubegeom_pre.png`)?

It's possible GL rendering is not 100% exact, but an error of 10 means quite a lot of difference, more than I'd expect. But it could still be that, we have `reference_slack` in some tests for that reason. So if the result looks correct, and so is a GL rendering imprecision, we can just add slack.

**Comment by SaschaNaz** [comment]
Removed `--headless` and I'm seeing this screen:

![image](https://user-images.githubusercontent.com/3396686/31800501-4c24f132-b57c-11e7-8faa-2c245c20339e.png)

**Comment by kripken** [comment]
Hmm yes, that looks wrong. The top 20% part with two colors separated by a slanted line should not appear at all. It's like some extra triangles block part of the properly-rendered tiles.

This is probably a GPU or browser bug. What GPU is that on?

**Comment by SaschaNaz** [comment]
Intel Atom X7-Z8700 integrated GPU, but this cannot be fixed by forcing software rendering by `--disable-gpu`.

**Comment by SaschaNaz** [comment]
I'm seeing the same diff value 10 on Travis CI so probably not a hardware issue...

**Comment by SaschaNaz** [comment]
I'm getting same diff errors on the cubegeom_pre tests also on Travis. Logs: https://travis-ci.org/SaschaNaz/emscripten/builds/290295450

**Comment by kripken** [comment]
All that's on chrome, correct? Perhaps it's all using chrome's software renderer (even on a machine with a seemingly normal GPU it might decide to not use it), and the bug is there?

Anyhow, it's fine to skip this test I guess. The only other thing I'd suggest doing is verifying whether this is in fact a chrome software renderer bug (e.g. seeing it works on firefox on the same machine, or making sure the chrome software renderer is or isn't on) and if so filing it.

**Comment by SaschaNaz** [comment]
Thanks for the tips, it seems Chrome software renderer is causing this error! Closing.
