### ISSUE TITLE
Travis CI: enable the auto cancellation feature

### ISSUE THREAD

**Issue by curiousdannii** [kripken/emscripten#5682]
![Screenshot of Travis CI's build log](https://user-images.githubusercontent.com/59074/31650485-dd68c048-b35a-11e7-8506-3014cb51fa42.png)

Travis CI has a feature [to automatically cancel builds](https://docs.travis-ci.com/user/customizing-the-build/#Building-only-the-latest-commit) when a newer commit is made to the same branch. As I write this I think there are 12 builds on the queue, and I think 4 of those could be skipped as their branches have newer commits. It's not ideal to skip running the tests on some commits, but when the tests take as long as they do it's probably a worthwhile trade-off.

(TBH I'm surprised it isn't on already - it seems to be the default option on my repos.)

**Comment by kripken** [comment]
Thanks, it wasn't the default. Seems like it should be! :) I changed it now.
