### ISSUE TITLE
AttributeError: 'str' object has no attribute 'sort'

### ISSUE THREAD

**Issue by ssx71** [kripken/emscripten#5693]
I have followed this tutorial about SDL2  and emscirpten, but something has gone wrong.
here are files to reproduce error.
https://lyceum-allotments.github.io/2016/06/emscripten-and-sdl2-tutorial-part-4-look-owl/

in reference to another similar problem ?! https://github.com/kripken/emscripten/issues/649

	emcc hello_owl.c -O2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' --preload-file assets -o hello_owl.html

Error :

	C:\xampp\htdocs\prova\hello_owl> emcc hello_owl.c -O2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' --preload-file assets -o hello_owl.html
	WARNING:root:retrieving port: zlib from https://github.com/emscripten-ports/zlib/archive/version_1.zip
	WARNING:root:unpacking port: zlib
	INFO:root:generating port: zlib.bc... (this will be cached in "C:\Users\claud\.emscripten_cache\asmjs\zlib.bc" for subsequent builds)
	INFO:root: - ok
	WARNING:root:retrieving port: libpng from https://github.com/emscripten-ports/libpng/archive/version_1.zip
	WARNING:root:unpacking port: libpng
	INFO:root:generating port: libpng.bc... (this will be cached in "C:\Users\claud\.emscripten_cache\asmjs\libpng.bc" for subsequent builds)
	INFO:root:building port: libpng
	INFO:root: - ok
	WARNING:root:retrieving port: sdl2-image from https://github.com/emscripten-ports/SDL2_image/archive/version_3.zip
	WARNING:root:unpacking port: sdl2-image
	Traceback (most recent call last):
	  File "C:\emscripten\emscripten\1.37.21\\emcc", line 13, in <module>
		emcc.run()
	  File "C:\emscripten\emscripten\1.37.21\emcc.py", line 1314, in run
		compile_source_file(i, input_file)
	  File "C:\emscripten\emscripten\1.37.21\emcc.py", line 1303, in compile_source_file
		args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
	  File "C:\emscripten\emscripten\1.37.21\emcc.py", line 1286, in get_bitcode_args
		args = system_libs.process_args(args, shared.Settings)
	  File "C:\emscripten\emscripten\1.37.21\tools\system_libs.py", line 718, in process_args
		args = port.process_args(Ports, args, settings, shared)
	  File "C:\emscripten\emscripten\1.37.21\tools\ports\sdl_image.py", line 53, in process_args
		get(ports, settings, shared)
	  File "C:\emscripten\emscripten\1.37.21\tools\ports\sdl_image.py", line 34, in get
		settings.SDL2_IMAGE_FORMATS.sort()
	AttributeError: 'str' object has no attribute 'sort

**Comment by SaschaNaz** [comment]
Sometimes the `-s SDL2_IMAGE_FORMATS='["png"]'` part should be `-s SDL2_IMAGE_FORMATS=["png"]` depending on different shell behaviors.

**Comment by ssx71** [comment]
issue does not changes

	C:\xampp\htdocs\prova\hello_owl>emcc hello_owl.c -O2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS=["png"] --preload-file assets -o hello_owl.html
	Traceback (most recent call last):
	  File "C:\emscripten\emscripten\1.37.21\\emcc", line 13, in <module>
		emcc.run()
	  File "C:\emscripten\emscripten\1.37.21\emcc.py", line 881, in run
		exec 'shared.Settings.' + key + ' = ' + value in globals(), locals()
	  File "<string>", line 1, in <module>
	NameError: name 'png' is not defined

**Comment by SaschaNaz** [comment]
Played a bit on Windows, got an answer: `-s SDL2_IMAGE_FORMATS="['png']"` (Note the quotes) :smile:

**Comment by ssx71** [comment]
yes, works in this way, if you want close this issue. can anyone apply a patch to emcc.py ?

**Comment by ssx71** [comment]
now work with this code, change in emcc.py, if you want feel free to insert in emcc.py

	import platform
	if ( platform.platform().find("Windows")!=-1 ):
		for i in range(0,len(sys.argv)):
			if ( sys.argv[i].find("SDL2_IMAGE_FORMATS")!=-1 ):
				sys.argv[i]=sys.argv[i].replace("'[","['");
				sys.argv[i]=sys.argv[i].replace("]'","']");

**Comment by ssx71** [comment]
now work with this code, change in emcc.py, if you want feel free to insert in emcc.py

	import platform
	if ( platform.platform().find("Windows")!=-1 ):
		for i in range(0,len(sys.argv)):
			if ( sys.argv[i].find("SDL2_IMAGE_FORMATS")!=-1 ):
				sys.argv[i]=sys.argv[i].replace("'[","['");
				sys.argv[i]=sys.argv[i].replace("]'","']");
