### ISSUE TITLE
emcc command not found

### ISSUE THREAD

**Issue by caperavensoftware** [kripken/emscripten#5696]
Having a hell of a time getting emcc working on mac.
Having followed and ensured that all the requirements are installed, i can't seem to get emcc to run outside of the installed folder getting a command not found.

Are these steps correct?
http://webassembly.org/getting-started/developers-guide/

**Comment by asRIA** [comment]
Hi, if you're inside emsdk folder please type: 
```
source ./emsdk_env.sh
emcc --version
```
What output do you see?

**Comment by caperavensoftware** [comment]
source:
```
Adding directories to PATH:
PATH += /Users/username/Documents/GitHub/webassembly/emsdk
PATH += /Users/username/Documents/GitHub/webassembly/emsdk/clang/e1.37.22_64bit
PATH += /Users/username/Documents/GitHub/webassembly/emsdk/node/4.1.1_64bit/bin
PATH += /Users/username/Documents/GitHub/webassembly/emsdk/emscripten/1.37.22

Setting environment variables:
EMSDK = /Users/username/Documents/GitHub/webassembly/emsdk
EM_CONFIG = /Users/username/.emscripten
BINARYEN_ROOT = /Users/username/Documents/GitHub/webassembly/emsdk/clang/e1.37.22_64bit/binaryen
EMSCRIPTEN = /Users/username/Documents/GitHub/webassembly/emsdk/emscripten/1.37.22
```

for the version I get this

```
emcc (Emscripten gcc/clang-like replacement) 1.37.22 (commit 024e3bb3b4d1860c46c2c887aad868db7053fe1a)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

when I do emcc -v outside that folder I get this
```
-bash: emcc: command not found
```

**Comment by gogoprog** [comment]
You always have to `source ./emsdk_env.sh` first in a new terminal session

**Comment by caperavensoftware** [comment]
ok, that makes sense now, ty

**Comment by hon** [comment]
@gogoprog why do we need to that all the time in a new terminal session? it is so boring.

**Comment by gogoprog** [comment]
@hon because there is nothing set magically: your default `PATH` doesn't contain the `emcc` path so it has to be set.

But of course you can set that up once for all by automatically calling the `source ./emsdl_env.sh` in your session startup script. Look for `.bashrc` if you're using `bash` (I guess that's the case on OsX)

**Comment by hon** [comment]
@gogoprog does't `source ./emsdk_env.sh` set env path? 
```shell
which emcc
/Users/hon/work/emsdk-portable/emscripten/incoming/emcc
```
and the '/Users/hon/work/emsdk-portable/emscripten/incoming/emcc' is already set into $PATH (in .zshrc file)

but it does't work...

**Comment by asRIA** [comment]
PATH contains directories instead of file paths.
After `source ./emsdk_env.sh` type `echo $PATH` to see how it's populated.

**Comment by gogoprog** [comment]
@hon yes `source ./emsdk_env.sh` will set the PATH.

How is it set in your `.zshrc` file?

**Comment by hon** [comment]
@gogoprog 
```shell
➜  emsdk-portable echo $PATH
./node_modules/.bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hon/work/go/bin:/usr/local/go/bin:/usr/local/nginx/sbin:/Users/hon/.cargo/bin:/Users/hon/Library/Android/sdk/build-tools/23.0.1:/Users/hon/rust/src:/Users/hon/Library/Android/sdk/tools:/Users/hon/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/include/libxml2/:/Users/hon/work/emsdk-portable:/Users/hon/work/emsdk-portable/clang/fastcomp/build_incoming_64/bin:/User/hon/work/emsdk-portable/emscripten/incoming:/Users/hon/work/emsdk-portable/emscripten/incoming/emcc
➜  emsdk-portable emcc
zsh: command not found: emcc
➜  emsdk-portable
```

**Comment by asRIA** [comment]
@hon You should add `/Users/hon/work/emsdk-portable/emscripten/incoming/` to the PATH as a folder what contains `emcc`, not a full path to `emcc`.

**Comment by gogoprog** [comment]
Also you better just do the following in your `.zshrc`:
```bash
pushd path/to/emsdk
source ./emsdk_env.sh
popd
``` 

So the `PATH` will be correctly set

**Comment by hon** [comment]
@asRIA folder /Users/hon/work/emsdk-portable/emscripten/incoming/ is alreay in $PATH
@gogoprog I add the commands, but I need to type the follow command in every new session:
```shell
. ~/.zshrc
```
what I wondering now is: the function of env path is make some binary file can be executed everywhere in the system, with out type the full path. since the path was in the $PATH, why 
can't it be executed?
Sorry for so many questions. I never met the situation before(I have to source .sh file every time
to make some command work).

**Comment by asRIA** [comment]
Maybe you don't use ZSH, but the regular bash? Can you type `ps -p $$` and check the output? 
If it's a bash, then it's needed to change `.bashrc` file

**Comment by hon** [comment]
@asRIA 
```shell
➜  emscripten ps -p $$
  PID TTY           TIME CMD
33664 ttys001    0:00.58 -zsh
```

**Comment by asRIA** [comment]
Hm.. Interesting, last call: in .zshrc please just leave: 
```
. /Users/hon/work/emsdk-portable/emsdk_env.sh
```

**Comment by hon** [comment]
Now it works, but every time in a new session, the console outputs:
```shell
Last login: Tue Oct 24 17:03:49 on ttys004
~/work/emsdk-portable ~
Adding directories to PATH:
PATH += /Users/hon/work/emsdk-portable/node/4.1.1_64bit/bin
PATH += /Users/hon/work/emsdk-portable/emscripten/incoming

Setting environment variables:
EMSDK = /Users/hon/work/emsdk-portable
EM_CONFIG = /Users/hon/.emscripten
EMSCRIPTEN = /Users/hon/work/emsdk-portable/emscripten/incoming

/Users/hon/.zshrc:popd:151: directory stack empty
➜  ~
```

**Comment by asRIA** [comment]
If you use the absolute path and `.` the `popd` and `pushd` commands aren't needed.

**Comment by hon** [comment]
ok, ty~

**Comment by sfjadi2010** [comment]
I have same issue, did everything but not able to fix it tonight.

**Comment by posthighline** [comment]
I have the same issue too. I followed this guide perfectly, it seems like it's incomplete: 
https://webassembly.org/getting-started/developers-guide/

**Comment by kripken** [comment]
Is the issue that `source ./emsdk_env.sh` needs to be run after install and activate? That does seem to be missing on the webassembly.org instructions (but is present on the [emscripten docs](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html)).

If that's it, I can open a PR to update their docs, but please let me know if that is indeed what's wrong.

**Comment by sfjadi2010** [comment]
@kripken I tried both way, but not able to fix.

**Comment by Samuelfaure** [comment]
For anyone having issues :
If you moved your emsdk folder after you ran `./emsdk activate --build=Release sdk-incoming-64bit binaryen-master-64bit` the sourcing wont work and you need to redo this command.

**Comment by kmturley** [comment]
I solved by adding the script to my .bash_profile file:
```
# Web Assembly paths
source "/Users/${USER}/Sites/emsdk/emsdk_env.sh"
```

**Comment by eyworldwide** [comment]
> Now it works, but every time in a new session, the console outputs:
> 
> ```shell
> Last login: Tue Oct 24 17:03:49 on ttys004
> ~/work/emsdk-portable ~
> Adding directories to PATH:
> PATH += /Users/hon/work/emsdk-portable/node/4.1.1_64bit/bin
> PATH += /Users/hon/work/emsdk-portable/emscripten/incoming
> 
> Setting environment variables:
> EMSDK = /Users/hon/work/emsdk-portable
> EM_CONFIG = /Users/hon/.emscripten
> EMSCRIPTEN = /Users/hon/work/emsdk-portable/emscripten/incoming
> 
> /Users/hon/.zshrc:popd:151: directory stack empty
> ➜  ~
> ```
-----------------------------------------------------
You need not to see these ugly logs every time when open a bash.   

The issue is because the command `source ./emsdk_env.sh` export path failed. I digged into the shell code but I could not fix it.  However,  I can add the path to the `.profile` file (which is in your user directory of the system) manually:

1. open the `emsdk_set_env.sh` with any text editor, copy the first line of the code, for me, it is:

    `export PATH="/Users......Frameworks/Mono.framework/Versions/Current/Commands"`

2. open '~/.profile', then paste the code:

     `export PATH="/Users......Frameworks/Mono.framework/Versions/Current/Commands:${PATH}`

Be careful, add `:${PATH}` in the end. Because we only want to add path other than cover the global paths.

**Comment by eliottparis** [comment]
Adding this to `.zshrc`/`.bash_profile` did the trick for me on macOS (set the emcc paths for new terminal sessions and hiding output logs):

```
source ~/path-to-emsdk/emsdk_env.sh &> /dev/null
```

**Comment by Ayan-web** [comment]
add 
`source ./emsdk_env.sh
 `
to .bashrc or zshrc file

**Comment by cool-delete** [comment]
Until now, I found the issue
`source ./emsdk_env.sh`
 ` echo ${EMSDK}`
get ""
![image](https://user-images.githubusercontent.com/13638610/128266203-5402aea5-6786-4c02-94ef-8fc580c624ed.png)

**Comment by joshxyzhimself** [comment]
what worked in my case, is just login as root

```
# login as root
sudo -s

# deps
apt install python3
apt install cmake

# prep emsdk
git clone git@github.com:emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
cd ../

# compile example-project
mkdir example-project
cd example-project
emcmake cmake ../some-wasm-wrapper-dir/
cmake --build ./
```

**Comment by tsavo-at-pieces** [comment]
Just a heads up for peeps. Installed via brew https://formulae.brew.sh/formula/emscripten#default and it all worked great out of the box. Worth a shot!

**Comment by KangChou** [comment]
> emcc --version

emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.21 (f9e81472f1ce541eddece1d27c3632e148e9031a)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by LakshmiMounika29** [comment]
source ./emsdk_env.sh
emcc --version

instead of using this try for windows
cd WHERE/YOU/INSTALLED/EMSCRIPTEN
emsdk update
emsdk install latest
emsdk activate latest
emsdk_env.bat
emcmdprompt.bat

**Comment by Zexoius** [comment]
> 

That works perfeck! thx bro~

**Comment by shubham0204** [comment]
In my case, I had not used the `activate` command, which resulted in a `bash: command not found` even after setting the environment variables in `.bashrc`,

```
# Make the "latest" SDK "active" for the current user. (writes .emscripten file)
./emsdk activate latest
```
