### ISSUE TITLE
Propose of new versioning and release circle

### ISSUE THREAD

**Issue by asRIA** [kripken/emscripten#5699]
Hi, 
Starting from problem what this proposal is trying to solve. 
ATM: In my understanding, the construction version of Emscripten is build as [1][Major][Minor]. Where:
- [**1**]: Looks pretty static
- [**Major**]: Is bumped seldom, after a set of changes is proven to be stable
- [**Minor**]: Bumped ~2weeks, after a set of functionalities is merged into `incoming`

This versioning and releases circle has some constrains: 
1. The Emscripten SDK and pre-compiled version is released (tagged) on every minor update. As it contains a set of functionalities, sometimes it's problematic to bisect exact what change potentially causes a problem, that is: It increases a probability that the release what contains FeatureA and FeatureB is unstable due a one broken feature implementation, and as a developer what would like to use the other feature I'm blocked for a while. 

1. Due a fact that the tool-chain is under a rapid development, as a developer I would like to test the newest features in a reliable and fast way (so that compiling locally isn't always a case). 

1. Current solution with nightly build is a half solution. Main problem is that the version tag doesn't say explicitly what changes it includes - due a possible case when multiple changes land to incoming branch. 

As an alternative I propose to switch to schema [Major][Minor][Feature], where:
- [**Major**]: is bumped as it is currently
- [**Minor**]: is bumped as it is currently
- [**Feature**]: is bumped on every merge to incoming action. 

This will: 
1. Allow developers to use an explicit version what contains a functionality. 
1. Compile more pre-build versions of the toolchain. 
1. One feature per release

Alternatively it could follow [SemVer](http://semver.org/), but in my opinion it doesn't apply to toolchains, because _"everything could be a breaking change"_

**Comment by kripken** [comment]
Some thoughts:
 * How would `[Feature]` be bumped on each merge to incoming, practically speaking?
 * Currently we use the full version number to decide when to invalidate the cache (and so rebuild libc etc.). We'd need to change that if we add `[Feature]`
 * Currently the `1.` part is indeed pretty static. But we've been thinking to bump it to `2` when we switch from asm.js to wasm output by default, to signify a major shift in focus.

**Comment by asRIA** [comment]
Hi @kripken,
I believe that you already have some mechanism similar to described below. 

1. Of course this will not happen magically. The common strategy is to leverage GitHub and hooks. Mainly it requires a few elements:
- A lightweight way to update version: 
  - A webhook to the push action on incoming branch (what in fact can be retried from data). TravisCI, CircleCI can be used for this. 
  - Shell script connected to a hook will update a feature part of version and commit it to the incoming. Perhaps it can create a tag. 

- Builder: Once the version is updated, it will create/use a pipeline of compilation.
  - Windows
  - macOS
  - Linux

Once it's done it can upload artifacts to the CDN.

Unfortunately the builder requires a dedicated server / premium TravisCI/CircleCI. It's due an execution limit, what I'm pretty sure it will exceed. 

2. OK, this indeed will invalidate cache faster - for people that are living on a bleeding edge. IHMO that's a fair price for this. BTW: Does it mean that if somebody uses sdk-incoming-64bit might hit a problem that pre-compiled libs aren't compatible anymore after update, and SDK will not clear a cache?

3. I see. Well, on the end of the day it isn't neither blocker not something super important, and it looks that the added value is rather small. 

Thx!
