### ISSUE TITLE
test_sockets_echo_client sends "[object SharedArrayBuffer]" instead of actual message

### ISSUE THREAD

**Issue by ismbabf** [kripken/emscripten#5706]
Hi, 
I'm new to emscripten and I'm trying to send a message from a client to a server, but instead of the actual message "pingtothepong", which is defined in the client, it sends "[object SharedArrayBuffer]".  

The problem seems to be that I'm passing the compiler flag -s USE_PTHREADS=1 when compiling the test_sockets_echo_client.c, but I don't understand why. Is it intended that the client is sending "[object SharedArrayBuffer]" instead of the actual message when pthread support is enabled?

**Comment by kripken** [comment]
cc @juj

**Comment by ismbabf** [comment]
Just to be completely clear, the Output changes only when the USE_PTHREADS flag is enabled.
Server output without pthreads: "pingtothepong"
Server output with pthreads: "[object SharedArrayBuffer]"

**Comment by juj** [comment]
Thanks for reporting - fix in above PR. If you run the server also using `-s USE_PTHREADS=1` compilation, you'll need a new enough Node.js that understands SharedArrayBuffer.
