### ISSUE TITLE
No Windows precompiled build for 1.37.22

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5713]
`./emsdk update-tags;./emsdk list` does not show precompiled 1.37.22 emscripten or clang. What happened to the build system?

**Comment by juj** [comment]
The Windows build bot is in the process of being migrated to Amazon (the original physical hardware suffered a breakdown recently), so some turbulence is expected to occur here.

**Comment by bsokol** [comment]
Any news for windows binaries? 1.37.22 was released 24 days ago,

**Comment by juj** [comment]
As of yesterday, we now have the Amazon migrated CI bot up and running, but it is not yet deploying builds. I am working on this as a I write, hopefully should not be too long.

**Comment by bsokol** [comment]
Sorry to bother you, but Is there any chance for these binaries in the near future?

**Comment by saschanaz** [comment]
@juj is on vacation so some delay is expected.

**Comment by bsokol** [comment]
Some news about windows binaries guys? :/ We are 3 versions behind main releases :/

**Comment by kripken** [comment]
Sorry again about this - @juj was on vacation and is currently traveling. I mentioned the urgency here to him, hopefully he can get to it soon.

Long-term, we just need a better solution, where it doesn't depend on just one person. But we need more help to get there.

Meanwhile, you can get and build incoming using the emsdk. That will take time to build LLVM+Clang, but otherwise should get you the very latest code.

**Comment by bsokol** [comment]
Hi Alon! :) First of all I would you thank you guys @kripken @juj for your hard work. Emscripten is a fantastic technology! I devoted last half year to a research of current HTML5 capabilities in gamedev, and thanks to Emscripten we are able to create high-quality and well-optimized games that may compete with native mobile apps.
You can test our small demo on every desktop and especially mobile browsers:
https://nanotitans.com/html5/nerdhero/
https://www.youtube.com/watch?v=lAlJ29CB30g
We are still surprised with the results and power of Emscripten! ;) It's only 800kb asm.js.

My main development platform is Windows so why I always waiting and begging for a new precompiled build. I prefer to work on stable/official releases. Building the whole emsdk on windows is also not trivial task :/

**Comment by kripken** [comment]
Nice game!

Yeah, I understand the problem with building the emsdk - clang and LLVM are large and take a while to compile. As I said above, we need to fix the process for creating the emsdk builds somehow, as @juj isn't always available.

One option I've suggested in the past is to create a portable emsdk containing wasm (or asm.js) builds. So clang compiled to wasm, etc. That would run a little slower than native builds, but it makes creating an emsdk for all platforms very easy (as easy as creating binaryen.js in the binaryen repo, which is super easy). Thoughts?

**Comment by saschanaz** [comment]
>One option I've suggested in the past is to create a portable emsdk containing wasm (or asm.js) builds.

That's what I recently though, just like your previous experiment: https://github.com/kripken/llvm.js

**Comment by saschanaz** [comment]
I think #5266 is a blocker when we want to build a CLI tool anyway...

**Comment by juj** [comment]
Sorry for the delay on this one - before getting to PTO I checked that the builds were running fine, and it turns out the bots were fine to do only one build, and they weren't able to successfully upload any newer ones - working on this now.

**Comment by bsokol** [comment]
Hi @juj , thanks for fixing build machine I've just downloaded 1.37.25 binaries and everything works like a charm. I had to only add -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap", "writeArrayToMemory", "stringToUTF8"]' option to my makefile according to last changes.

Btw. guys, bigs thanks for updating release notes history file. It is very helpful:
https://kripken.github.io/emscripten-site/docs/introducing_emscripten/release_notes.html

I keep fingers crossed for build machine bot and the brand new 1.37.26 release from few hours ago ;)

**Comment by juj** [comment]
Perfect! I'm seeing the bots have now run through and uploaded all the builds since 1.37.22, so this should be good now. I see also 1.37.26 tag build is now finished - run `emsdk update-tags` to get the latest set of tags.

**Comment by buu700** [comment]
It's working for me on Linux now too. (I'd been waiting for a pre-built release included my SINGLE_FILE PR.) Thanks!

**Comment by bsokol** [comment]
Hi Guys, it looks like the build bot stopped working again :/
The latest windows binary I can download via emsdk is 1.37.26.
but there are two releases more:
https://github.com/kripken/emscripten/releases

**Comment by juj** [comment]
Thanks for pinging @bsokol, I see that the EC2 bot has filled its limited disk space when doing a build, and it keeps retrying the build and running out of disk space. Updating it now.

**Comment by bsokol** [comment]
Just downloaded 1.37.28 binaries and compiled my game. Everything works like before! Thanks @juj ! :)

**Comment by juj** [comment]
Great, the infra gets more solid by the day, let's hope it's golden for a while this time around :)

**Comment by bsokol** [comment]
*beep* ;) @juj could you push the button for 1.37.29? Thanks! ;)

**Comment by juj** [comment]
Thanks for the ping, the builds up to 1.37.32 should be present now - the bots are being quite slow with the turnovers it looks like, 1.37.33 should come up hopefully within a day as well.

**Comment by bsokol** [comment]
1.37.35 and 1.37.36 builds are not present in emsdk for windows :/

**Comment by kripken** [comment]
I don't have a windows machine to check on, but I do see 1.37.35 and 36 in s3 for win64, so they should be available. Is this still not working for you? If so, what exactly does emsdk report?

**Comment by bsokol** [comment]
It looks like it doesn't see 36 and 36 updates:
```
w:\Emsdk>emsdk update
Downloading: w:/Emsdk/zips/emsdk_windows_update.zip from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip, 40919 Bytes
 Unpacking 'w:/Emsdk/zips/emsdk_windows_update.zip' to 'w:/Emsdk'
Fetching all tags from Emscripten Github repository...

w:\Emsdk>emsdk install latest
Installing SDK 'sdk-1.37.34-64bit'..
Installing tool 'clang-e1.37.34-64bit'..
The contents of file 'llvm/tag/win_64bit/emscripten-llvm-e1.37.34.zip' already exist in destination 'w:/Emsdk/clang/e1.37.34_64bit', skipping.
Done installing tool 'clang-e1.37.34-64bit'.
Installing tool 'node-8.9.1-64bit'..
The contents of file 'node-v8.9.1-win-x64.zip' already exist in destination 'w:/Emsdk/node/8.9.1_64bit', skipping.
Done installing tool 'node-8.9.1-64bit'.
Installing tool 'python-2.7.13.1-64bit'..
The contents of file 'WinPython-64bit-2.7.13.1Zero.zip' already exist in destination 'w:/Emsdk/python/2.7.13.1_64bit', skipping.
Done installing tool 'python-2.7.13.1-64bit'.
Installing tool 'java-8.152-64bit'..
The contents of file 'portable_jre_8_update_152_64bit.zip' already exist in destination 'w:/Emsdk/java/8.152_64bit', skipping.
Done installing tool 'java-8.152-64bit'.
Installing tool 'emscripten-1.37.34'..
The contents of file 'https://github.com/kripken/emscripten/archive/1.37.34.zip' already exist in destination 'w:/Emsdk/emscripten/1.37.34', skipping.
Done installing tool 'emscripten-1.37.34'.
Done installing SDK 'sdk-1.37.34-64bit'.
```

**Comment by kripken** [comment]
Does it work if you do `emsdk update-tags` before `install latest`?

**Comment by bsokol** [comment]
No, it didn't help :/

**Comment by kripken** [comment]
Well, this is getting beyond what I know of the emsdk codebase, so I guess we just need to debug it on your machine. First thing I'd try is to run with `EMSDK_VERBOSE=1` in the env, then maybe it will show something useful when it fetches the wrong version.

**Comment by juj** [comment]
Trying out today on a Windows system, I do see `emsdk update-tags` (`emsdk update` should work all the same as well) followed by `emsdk install latest` to download 1.37.36 64-bit. Also, `emsdk list` does show for me (before installing)

```
The following precompiled SDKs are available for download: (Run "git pull" followed by "./emsdk update-tags" to pull in the latest list)
         sdk-1.30.0-64bit
         sdk-1.34.1-64bit
         sdk-1.35.0-64bit
         sdk-1.37.1-64bit
         sdk-1.37.35-64bit
         sdk-1.37.36-64bit

The following SDKs can be compiled from source:
         sdk-incoming-32bit
    *    sdk-incoming-64bit             INSTALLED
         sdk-master-32bit
         sdk-master-64bit
         sdk-tag-1.37.35-32bit
         sdk-tag-1.37.36-32bit
         sdk-tag-1.37.35-64bit
         sdk-tag-1.37.36-64bit
```

and the file `emscripten-tags.txt` lists version 1.37.36.

In your case it reads as if the problem might be something else, since in your log print, the `Fetching all tags ...` operation seems to be cut off. It should read:

```
C:\code\emsdk>emsdk update-tags
Fetching all tags from Emscripten Github repository...
Done. 123 tagged releases available, latest is 1.37.36.
Fetching all tags from Binaryen Github repository...
Done. 50 tagged Binaryen releases available, latest is 1.37.36.
Fetching all precompiled tagged releases..
Downloading: C:/code/emsdk/llvm-tags-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_32bit/index.txt
Downloading: C:/code/emsdk/llvm-tags-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/index.txt, 1335 Bytes
      1335  [100.00%]
```

Can you try redownloading latest emsdk from the portable zip installer?

**Comment by nt-bsokolowski** [comment]
I've prepared fresh emsdk folder from portable zip installer and now I can download 1.37.36. It looks like something went wrong with previous emsdk installation. Thanks! :)

**Comment by bsokol** [comment]
I've prepared fresh emsdk folder from portable zip installer and now I can download 1.37.36. It looks like something went wrong with previous emsdk installation. Thanks! :)

**Comment by bsokol** [comment]
Guys, any chance for 1.38.1 windows binaries? The last version available is 1.37.40.

**Comment by kripken** [comment]
I restarted the windows machine now, something seems to have been wrong. Hopefully will have new builds in a few hours.

**Comment by bsokol** [comment]
Thanks @kripken , but after 20 hours there are no new builds :/

**Comment by kripken** [comment]
Ok, the bot says it finished successfully, and I think I see the output on S3 properly - @bsokol is it ok now?

**Comment by bsokol** [comment]
Emscripten 1.38.1 downloaded, installed and activated! Everything works with no issues! Thanks @kripken 🥇

**Comment by bsokol** [comment]
Hello again ;) Reporting no windows binaries for 1.38.31.
https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/index.txt

**Comment by kripken** [comment]
Looks like it might be @juj's commit here: https://github.com/juj/emslave/commit/2f4668796fbeabdcc8f645fde1de2ee3855d9004

**Comment by bsokol** [comment]
Thanks guys! Worked again!

**Comment by bsokol** [comment]
Hello again ;) Reporting no windows binaries above 1.38.32.
https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/index.txt

**Comment by kripken** [comment]
@bsokol Correct for 1.38.32, see [the changelog](https://github.com/emscripten-core/emscripten/blob/incoming/ChangeLog.md#v13832-skipped), we skipped 1.38.32 as part of the transition to the new builders.

For versions after that, the old mozilla builders are not being used, so all links to mozilla-games are obsolete. The emsdk will fetch from the new chromium builders (`./emsdk install latest` or `./emsdk install 1.38.33` for example). Please let us know if you see any issues there.

**Comment by bsokol** [comment]
Thanks for the info @kripken !

emsdk update

```
Downloading: c:/Work/Emsdk/zips/master.zip from https://github.com/emscripten-core/emsdk/archive/master.zip, 49816 Bytes
 [----------------------------------------------------------------------------Already up to date.
]
Unpacking 'c:/Work/Emsdk/zips/master.zip' to 'c:/Work/Emsdk'
**Unzipping file 'c:/Work/Emsdk/zips/master.zip' failed due to reason: [Error 183] Cannot create a file when that file already exists**
Fetching emscripten-releases repository...
Repository 'https://chromium.googlesource.com/emscripten-releases' already cloned to directory 'c:/Work/Emsdk/releases', skipping.
Fetching latest changes to the branch 'master' for 'c:/Work/Emsdk/releases'...
Successfully updated and checked out branch 'master' on repository 'c:/Work/Emsdk/releases'
Current repository version: "Sat, 15 Jun 2019 10:43:49 +0000 edb07a77f534273b7ff496b859ddb1dcaa0a6bb9"
Fetching all precompiled tagged releases..
Downloading: c:/Work/Emsdk/llvm-tags-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_32bit/index.txt
 []
Downloading: c:/Work/Emsdk/llvm-tags-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/win_64bit/index.txt, 2435 Bytes
 [----------------------------------------------------------------------------]
```
emsdk install latest
```

Installing SDK 'sdk-releases-fastcomp-98f49919f25e06fa557cbcb1321d4c10e60c87ca-64bit'..
Installing tool 'releases-fastcomp-98f49919f25e06fa557cbcb1321d4c10e60c87ca-64bit'..
**Error downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/98f49919f25e06fa557cbcb1321d4c10e60c87ca/wasm-binaries.zip': HTTP Error 404: Not Found**

```

**Comment by kripken** [comment]
Thanks @bsokol, looks like we missed something in the new builders. This fix should resolve that, and tag a new working version: https://github.com/emscripten-core/emsdk/pull/278 Please test! I don't have a windows machine here.

Separately, I am worried about the
```
**Unzipping file 'c:/Work/Emsdk/zips/master.zip' failed due to reason: [Error 183] Cannot create a file when that file already exists**
```
When I do `emsdk update` twice it doesn't happen for me. What happens if you delete zips/master.zip and then do `emsdk update` twice?

**Comment by bsokol** [comment]
> When I do emsdk update twice it doesn't happen for me. What happens if you delete zips/master.zip and then do emsdk update twice?

The same. It looks like that is the problem with overwrite some files from master.zp to EMSDK folder on Windows during unpacking.

```
Downloading: c:/Work/Emsdk/zips/master.zip from https://github.com/emscripten-core/emsdk/archive/master.zip
Unpacking 'c:/Work/Emsdk/zips/master.zip' to 'c:/Work/Emsdk'
Unzipping file 'c:/Work/Emsdk/zips/master.zip' failed due to reason: [Error 183] Cannot create a file when that file already exists
```

The same with existing python installation:

```
Downloading: c:/Work/Emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/WinPython-64bit-2.7.13.1Zero.zip, 41285159 Bytes
Unpacking 'c:/Work/Emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip' to 'c:/Work/Emsdk/python/2.7.13.1_64bit'
Unzipping file 'c:/Work/Emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip' failed due to reason: [Error 183] Cannot create a file when that file already exists
Installation failed!
```

Maybe you should enable/force overwrite mode to unzip script on Windows?

**Comment by bsokol** [comment]
Ok it looks like you should fix some lines with "unpack_even_if_exists" parameter in "emsdk" script.

**Comment by bsokol** [comment]
Ok, after fixing emsdk script and updating the whole SDK I have another problem with 3 messages:
"ERROR: The system was unable to find the specified registry key or value."
during "emsdk activate latest --global"

```
Registering active Emscripten environment globally for all users.

Writing .emscripten configuration file to user home directory C:\Users\Bartek/
The Emscripten configuration file C:\Users\Bartek\.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT = 'c:/Work/Emsdk/fastcomp/fastcomp/bin'
BINARYEN_ROOT = 'c:/Work/Emsdk/fastcomp'
NODE_JS = 'c:/Work/Emsdk/node/8.9.1_64bit/bin/node.exe'
PYTHON = 'c:/Work/Emsdk/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe'
JAVA = 'c:/Work/Emsdk/java/8.152_64bit/bin/java.exe'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/bartek/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Setting environment variables:
EMSDK = c:/Work/Emsdk

ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
Set the following tools as active:
   releases-fastcomp-d46be49c2aab975333423122239892bd46f52bba-64bit
   node-8.9.1-64bit
   python-2.7.13.1-64bit
   java-8.152-64bit


```

**Comment by bsokol** [comment]
There is also no package for mingw:

emsdk install mingw-7.1.0-64bit

```
Installing tool 'mingw-7.1.0-64bit'..
Error downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/mingw_7.1.0_64bit.zip': HTTP Error 404: Not Found
Traceback (most recent call last):
  File "c:\Work\Emsdk\\emsdk", line 2640, in <module>
    sys.exit(main())
  File "c:\Work\Emsdk\\emsdk", line 2622, in main
    success = tool.install()
  File "c:\Work\Emsdk\\emsdk", line 1542, in install
    success = download_and_unzip(url, self.installation_path(), download_even_if_exists=download_even_if_exists, filename_prefix=filename_prefix)
  File "c:\Work\Emsdk\\emsdk", line 1107, in download_and_unzip
    assert received_download_target == download_target
AssertionError
```

**Comment by bsokol** [comment]
After manual coping mingw from previous emsdk I've tried do build my project with the newest emskd. All codebase was compiled successfully but on the end of process I've got this error:

```
cache:INFO: generating system asset: optimizer.2.exe... (this will be cached in "C:\Users\Bartek\.emscripten_cache\asmjs\optimizer.2.exe" for subsequent builds)
Traceback (most recent call last):
  File "c:\Work\Emsdk\fastcomp\emscripten\emcc.py", line 3420, in <module>
    sys.exit(run(sys.argv))
  File "c:\Work\Emsdk\fastcomp\emscripten\emcc.py", line 2233, in run
    optimizer.flush()
  File "c:\Work\Emsdk\fastcomp\emscripten\emcc.py", line 311, in flush
    just_concat='emitJSON' in chunk)
  File "c:\Work\Emsdk\fastcomp\emscripten\emcc.py", line 341, in run_passes
    output_filename=self.in_temp(os.path.basename(final) + '.jsopted.js'))
  File "c:\Work\Emsdk\fastcomp\emscripten\tools\shared.py", line 2308, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "c:\Work\Emsdk\fastcomp\emscripten\tools\js_optimizer.py", line 572, in run
    return run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat)
  File "c:\Work\Emsdk\fastcomp\emscripten\tools\js_optimizer.py", line 455, in run_on_js
    commands = [[get_native_optimizer(), f] + passes for f in filenames]
  File "c:\Work\Emsdk\fastcomp\emscripten\tools\js_optimizer.py", line 187, in get_native_optimizer
    return get_optimizer('optimizer.2.exe', ['-DNDEBUG'])
  File "c:\Work\Emsdk\fastcomp\emscripten\tools\js_optimizer.py", line 180, in get_optimizer
    return shared.Cache.get(name, create_optimizer_cmake)
  File "c:\Work\Emsdk\fastcomp\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "c:\Work\Emsdk\fastcomp\emscripten\tools\js_optimizer.py", line 138, in create_optimizer_cmake
    proc = subprocess.Popen(['cmake', '-G', cmake_generator, '-DCMAKE_BUILD_TYPE=' + cmake_build_type, shared.path_from_root('tools', 'optimizer')], cwd=build_path, stdin=log_output, stdout=log_output, stderr=log_output)
  File "c:\Work\Emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\Work\Emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
w:/NanoTitans/HTML5/Game/makefile:21: recipe for target 'Build/libs/app.js' failed
mingw32-make.exe: *** [Build/libs/app.js] Error 1
```

I'm targeting asm.js with this parameters:
-s EXTRA_EXPORTED_RUNTIME_METHODS='["stringToUTF8", "cwrap"]' -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s MODULARIZE=1 -s 'EXPORT_NAME="NTTech"' --closure 1 -s SINGLE_FILE=1 -s MALLOC=emmalloc -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s ENVIRONMENT=web -s ABORTING_MALLOC=0 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=33554432 -s NO_FILESYSTEM=1 -fno-exceptions -Wno-invalid-offsetof -s WASM=0 -s LEGACY_VM_SUPPORT=1

**Comment by kripken** [comment]
Thanks @bsokol, I opened https://github.com/emscripten-core/emsdk/pull/279 for the `remove/move` fix.

I'll look into the mingw download tomorrow.

Not sure about those other windows issues, I don't know enough about windows. It might be best to open specific new issues for them to get more attention if no one responds here.

**Comment by kripken** [comment]
Mingw (4.6.2 and 7.1.0) have been uploaded, so the emsdk should be able to get them now.
