### ISSUE TITLE
asm2wasm crashing with -g4

### ISSUE THREAD

**Issue by lpugin** [kripken/emscripten#5718]
As reported here
https://groups.google.com/forum/#!topic/emscripten-discuss/sXz_iRuyCTI

/Users/laurent/tools/emsdk_portable/clang/e1.37.22_64bit/binaryen/bin/asm2wasm build/verovio.temp.asm.js --total-memory=268435456 --trap-mode=allow --mem-init=build/verovio.js.mem --mem-base=1024 -g --symbolmap=build/verovio.js.symbols -o build/verovio.wast -S

[attachment.zip](https://github.com/kripken/emscripten/files/1419760/attachment.zip)

**Comment by kripken** [comment]
Thanks, the issue is that the debug info comments here look like `//@line X` while we expect the form `//@line X "filename"`. I guess the debug info in LLVM for some reason did not have a filename.

Fix in https://github.com/WebAssembly/binaryen/pull/1249

**Comment by lpugin** [comment]
Great, thanks! I'll keep you posted if necessary.
