### ISSUE TITLE
Add --em-config support to cmake toolchain file

### ISSUE THREAD

**Issue by iBicha** [kripken/emscripten#5728]
If the SDK is **not** setup properly, and no env vars are setup correctly, cmake would fail at
`execute_process(COMMAND "${CMAKE_C_COMPILER}" -v`
Since there is no config available.

It would be better to be able to pass a -DEM_CONFIG, and if it's available, pass it to emcc.
Also, this would allow invoking emscripten with cmake without touching any env vars.

The use case for this is compiling with emscripten bundled with Unity (why install it again if it's there)

Will do a PR if this makes sense.

**Comment by kripken** [comment]
cc @juj

**Comment by iBicha** [comment]
Something like this https://github.com/iBicha/NativePluginBuilder/blob/master/Boilerplate~/NativeSource~/CMake/Emscripten.cmake#L106

**Comment by iBicha** [comment]
Will close this for now. Feel free to reopen.
