### ISSUE TITLE
Strange behavior when calling webworker multiple times

### ISSUE THREAD

**Issue by dmitrykuzmin** [kripken/emscripten#5731]
I encountered strange behavior when trying to call webworker multiple times, as demonstrated in a simple  [example](https://github.com/dmitrykuzmin/webassembly_webworker_test/tree/master).

In short, I try to do the following:

1. Serialize some string to bytes and send to the webworker via `emscripten_call_worker`;
2. Inside webworker, deserialize it, perform some actions on it, then serialize string again and send to worker callback via `emscripten_worker_respond()`;
3. In worker callback, deserialize the string and perform some actions on it again.

When I perform these operations for the first time, everything works fine, but if I perform them on the same worker again, I get corrupted data in the worker callback (on step 3).

Seems like memory gets corrupted or re-used.

**Comment by jritts** [comment]
I am encountering the same issue - have you found any way to work around it?

**Comment by dmitrykuzmin** [comment]
For me, the problem was the double-deletion of the `data` array passed to the worker.

I deleted it inside the worker function (if you lookup my example, its [test_worker.cpp](https://github.com/dmitrykuzmin/webassembly_webworker_test/blob/master/test_worker.cpp), line 16). 

And as far as I understand, the Emscripten does delete the `data` one more time, because their [doc](https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_call_worker) states that data exists only during the callback.

Removing the double deletion fixed the issue for me. I should probably close this issue now.

**Comment by jritts** [comment]
Yes, I just discovered and fixed that in your test project, and now it works, so I think this bug can be closed.  

I'm debugging a possibly similar problem of a worker returning corrupted data iff I do the dispatch while it already has another pending task in its queue.  Thank you for uploading the test project, it's saving me time. :)

**Comment by jritts** [comment]
FYI:
https://github.com/kripken/emscripten/issues/7466
