### ISSUE TITLE
emar -M does not work ("control it with a script supplied via standard input")

### ISSUE THREAD

**Issue by kainino0x** [kripken/emscripten#5733]
`emar` does not work correctly with `-M`:

> if you specify the single command-line option -M, you can control it with a script supplied via standard input

This seems to be because `emar` ignores stdin instead of forwarding it to the `llvm-ar` process.

This is used by some builds out there, such as the one for [google/shaderc](https://github.com/google/shaderc). It's needed here because there's no way to merge `.a` files without `-M`. (With `-M`, the `addlib` command does this.)

**Comment by kripken** [comment]
A PR with a test for this would be useful, with a concrete usage of this that fails. Or, writing a complete one out here would be useful too. (Saves the person working on the bug some time, can jump right into investigation instead of first crafting a testcase.)

**Comment by kainino0x** [comment]
I didn't see an obvious place to add a test like this, but here's a minimal example (it's very simple):

```sh
#!/bin/sh

AR_TOOL=emar

rm -f file1 file2 combine.ar file1.a file2.a combined.a

touch file1
touch file2

cat > combine.ar << EOF
create combined.a
addlib file1.a
addlib file2.a
save
end
EOF

# Create file1.a containing only file1
$AR_TOOL cr file1.a file1
# Create file2.a containing only file2
$AR_TOOL cr file2.a file2
# Create combined.a containing both file1 and file2
$AR_TOOL -M < combine.ar

# Check the contents of combined.a
$AR_TOOL t combined.a | grep -q '^file1$' || echo 'FAILED: file1 not found'
$AR_TOOL t combined.a | grep -q '^file2$' || echo 'FAILED: file2 not found'
```

**Comment by juj** [comment]
The above PR fixes `-M` to work. However `emar` has a feature that it appends a random hash to the files that are put into archives, in order to allow appending files with same filename to one archive. If this is an issue, then directly using `llvm-ar` avoids this and should work in place of `emar`.

**Comment by kainino0x** [comment]
I'm not sure if it will work, but I'll test it.

That workaround (`llvm-ar`) is what I've been using. Is there a way, in an emscripten CMake setup, to query the path of llvm-ar?
