### ISSUE TITLE
Provide async C/C++ API

### ISSUE THREAD

**Issue by ghost** [kripken/emscripten#574]
Currently when one has to compile with Emscripten, you have to find your own solution for dealing with pseudo async processing (especially since there is nearly no API present in C/C++ for this).
To provide people with best practises and ease development it would probably be best to provide an API with Emscripten.

**Comment by juj** [comment]
The general solution to doing async computation has been the `emscripten_async_run_script` ( http://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_async_run_script ) and `emscripten_async_load_script` functions. There's also async file i/o and IndexedDB i/o as described in http://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#emscripten-asynchronous-file-system-api and http://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#emscripten-asynchronous-indexeddb-api. These should cover most uses, so probably no worth keeping this open, but focus in individual missing use cases in separate bug items.
