### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [kripken/emscripten#5745]
Based on https://github.com/kripken/emscripten/releases and https://github.com/kripken/emscripten/latest I cannot tell if 1.37.5 or 1.37.22 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by kripken** [comment]
The first link shows 1.37.22 (the last tagged version), the second gives me a 404?

**Comment by ilovezfs** [comment]
sorry I meant  https://github.com/kripken/emscripten/releases/latest

**Comment by kripken** [comment]
Hmm, I don't know why it redirects `releases/latest` to 1.37.5. Both tags and releases show later ones. I guess I don't understand how github decides that.

**Comment by kripken** [comment]
The only "special" thing about 1.37.5 is that it has some release notes in it. I guess github treats those in a special way?

**Comment by ilovezfs** [comment]
>I guess github treats those in a special way?

@kripken yup. If you create any explicit release, then GitHub will always point releases/latest at the newest explicit release (excluding any of the explicit releases that have the pre-release checkbox checked). So you can resolve this either by making 1.37.22 an explicit release or by deleting https://github.com/kripken/emscripten/releases/tag/1.37.4 and https://github.com/kripken/emscripten/releases/tag/1.37.5

**Comment by kripken** [comment]
Hmm, but we do want those tags. I guess I could delete them and then create them "non explicitly", on the commandline, is that the difference?

**Comment by asRIA** [comment]
Is 1.37.23 somewhere on the horizon?

**Comment by kripken** [comment]
There is currently a bunch of broken stuff, https://github.com/kripken/emscripten/commit/c23ee7a59f2855f9ec1208d66e13897af139fc97 and https://github.com/kripken/emscripten/commit/93479ecbd390aec4f8a3765fe04bcb365d0b31b2 , but after that's resolved we can tag it.

**Comment by ilovezfs** [comment]
Deleting the release doesn't delete the tag.

**Comment by saschanaz** [comment]
It seems undescribed tags are not really a 'release' and adding release notes makes them real 'releases'. (Clicking "Add release note" opens publishing page.)

**Comment by ilovezfs** [comment]
@saschanaz that's correct. So either you have to always create an explicit release with the GitHub GUI (https://help.github.com/articles/creating-releases/) or the GitHub releases API (https://developer.github.com/v3/repos/releases/), or you have to never do it. Mixing them, sometimes doing it and sometimes not doing it, leads to the current ambiguous situation.

**Comment by kripken** [comment]
And is there a way to remove the description from a tag, so it becomes a non-explicit release? (Or should we delete it and create it again without a comment?)

**Comment by ilovezfs** [comment]
You should be able to go to https://github.com/kripken/emscripten/releases/tag/1.37.4 and in the upper right hand corner click the delete button. That shouldn't affect the underlying tag.

**Comment by ilovezfs** [comment]
Then do the same for https://github.com/kripken/emscripten/releases/tag/1.37.5 and it should all be fixed :)

**Comment by kripken** [comment]
Thanks! Done, and it looks fixed.

We need to remember to not create tags explicitly on github going forward. Odd github works that way though, seems confusing...

**Comment by ilovezfs** [comment]
Thanks! :heart:
