### ISSUE TITLE
Central Library Repo

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#575]
Right now linking with standard libraries means in many cases you need to build them first (see https://github.com/kripken/emscripten/wiki/Building-Projects ). This isn't too hard in most cases, you just build and link the bitcode, but in practice it means building a local native project is simpler (at least on linux where the libraries are likely already present).

We could have a central repo of bitcode files of common libraries, like zlib, freetype, glib, etc. Then if people needed those libraries, they could just tell emcc to use them, and it would -I the include dirs and link with the bitcode.

We would need to rebuild them all every time LLVM updates though.

**Comment by juj** [comment]
Closing, as we now have the https://github.com/emscripten-ports repository that implements this.
