### ISSUE TITLE
Does shared.BINARYEN_ROOT exist?

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5764]
I'm seeing some lines that try using shared.BINARYEN_ROOT and ignore any errors.

https://github.com/kripken/emscripten/blob/ea67ec150622ce2dd9902906b2b027bf73ef4d3d/emcc.py#L1142-L1146

https://github.com/kripken/emscripten/blob/ea67ec150622ce2dd9902906b2b027bf73ef4d3d/tools/ports/binaryen.py#L7-L13

Those lines raises `AttributeError: 'module' object has no attribute 'BINARYEN_ROOT'` on my Ubuntu and Windows environments. What do the lines actually do?

**Comment by kripken** [comment]
The idea is that the user might or might not specify `BINARYEN_ROOT` in the `.emscripten` file. (If not, then the port should be automatically downloaded.) And we also allow setting it on the commandline using `-s BINARYEN_ROOT`.

Are you saying those lines throw and the exception is caught (the intended behavior)? Or are you hitting a problem with it stopping here?

Btw, I think the ports code is not needed, we should do all this handling in emcc.py (which happens first anyhow).

**Comment by saschanaz** [comment]
Ah, thanks. I forgot .emscirpten is using `exec()`.

**Comment by saschanaz** [comment]
>Btw, I think the ports code is not needed, we should do all this handling in emcc.py (which happens first anyhow).

Should a new issue be opened?

**Comment by kripken** [comment]
Actually, I'll look into that issue in #5763, I may need to clean it up for that anyhow.

**Comment by saschanaz** [comment]
Okay, thanks 👍
