### ISSUE TITLE
How lower 1024 bytes of Linear Memory is used?

### ISSUE THREAD

**Issue by pepyakin** [kripken/emscripten#5775]
How lower 1024 bytes is used?

Emscripten generated code like this:
```WebAssembly
(set_local $0
  (call $_ext_memcpy
    (i32.const 1)
    (get_local $5)
    (get_local $2)
  )
)
```

I'm wondering is this could be correct?

**Comment by kripken** [comment]
What is `ext_memcpy`? Perhaps the first argument is not what it seems.

**Comment by pepyakin** [comment]
@kripken Oops. Sorry, it is my version of `memcpy`. I managed to reproduce this with an ordinal `$_memcpy`.

**Comment by kripken** [comment]
That does look wrong then, unless the source code has a literal pointer to location 1 in memory hardcoded? What test case did you see this with?

In general, it is wrong to emit something like this, the lower 1024 bytes are used for a few special things like a temp copy area for alignment issues etc., so no global data or stack or heap could be there.

**Comment by pepyakin** [comment]
I guess, it is not hardcoded. The line of code for which this code is generated looks like [this](https://github.com/paritytech/wasm-tests/blob/9a1fcbf0d4e73bea437577e807bc38c7ba243d80/src/suicidal.rs#L17).

**Comment by kripken** [comment]
Yeah, something's getting miscompiled then. I'd guess on the rust side just because the other parts are better tested, but can't be sure. Anyhow, if you can reduce this to a non-rust testcase I could help debug that.

**Comment by pepyakin** [comment]
> Anyhow, if you can reduce this to a non-rust testcase I could help debug that.

Ok, will try!

**Comment by pepyakin** [comment]
Turns out that this code could be perfectly valid! It seems that it is legal to execute `memcpy` with any  non-zero pointers and given that `len` is 0.
