### ISSUE TITLE
"warning: unresolved symbol" when compiling opencv

### ISSUE THREAD

**Issue by hundredeir** [kripken/emscripten#5785]
I am getting `unresolved symbol warnings` when trying to compile via emscripten

My code is really simple

```
#include "opencv2/core.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/opencv.hpp"
#include "emscripten.h"
#include <iostream>

using namespace cv;

int main(int argc,char **argv){
	cv::VideoCapture cap;
	Mat frame;
	int check;
	while(1){
		check=0;
		check=cap.read(frame);
		if ((check!=false)){
			imshow("picture",frame);
		}
		waitKey(2);
	}
	return 0;
}
```
```
emcc test123.cpp -o test123.html -I C:\opencv\opencv330\include

warning: unresolved symbol: _ZN2cv6imshowERKNS_6StringERKNS_11_InputArrayE
warning: unresolved symbol: _ZN2cv12VideoCaptureC1Ev
warning: unresolved symbol: _ZN2cv3Mat10deallocateEv
warning: unresolved symbol: _ZN2cv6String8allocateEj
warning: unresolved symbol: _ZN2cv12VideoCaptureD1Ev
warning: unresolved symbol: _ZN2cv8fastFreeEPv
warning: unresolved symbol: _ZN2cv12VideoCapture4readERKNS_12_OutputArrayE
warning: unresolved symbol: _ZN2cv7waitKeyEi
warning: unresolved symbol: _ZN2cv6String10deallocateEv
```
I even tried using exported functions,emscripten keepalive and ```-s LINKABLE =1 ``` also. But, none of them helped.

**Comment by gogoprog** [comment]
You are compiling an application using opencv, not opencv itself.
That's why you have unresolved symbols, opencv code is not included in your application.

You need to build opencv to llvm bitcode as a library and then link it to your application

**Comment by hundredeir** [comment]
I tried that also, but it failed.
I used emscripten to configure and build opencv. But, that also failed.

**Comment by nazar-pc** [comment]
Your source code only includes headers. You need to include actual source code of mentioned functions in one way or another. You can try to add `#include ...cpp` lines for the files that contain listed functions, then it should be fine.

**Comment by hundredeir** [comment]
@nazar-pc 

I thought using ```-I``` to include headers should be fine.

**Comment by nazar-pc** [comment]
By including headers you instruct compiler that there will be certain function of class with certain signature, so that it can check whether you're calling it properly. However, you need to include or link actual source code too, otherwise there is nothing to call.

I'm not C/C++ developer, so in one of my projects I've simply listed all of the C files that contain necessary functions: https://github.com/nazar-pc/ed25519-to-x25519.wasm/blob/master/src/ed25519-to-x25519.c

**Comment by hundredeir** [comment]
Okay, so I was able to build OpenCV using emscripten toolchain and then linked the files. 
But, still it gave me errors regarding highgui; Though other things seems fine

But, since above issue is solved. I'll close this issue

**Comment by happytoTom** [comment]
Could you tell me how to compile OpenCV through LLVM bitcode? @hundredeir
