### ISSUE TITLE
exception thrown: TypeError: undefined is not an object (evaluating 'AL.currentContext.ctx.listener._position[0]=v1'),_alListener3f

### ISSUE THREAD

**Issue by GregSlazinski** [kripken/emscripten#5797]
When I run my demo
http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.html
using Safari browser, I get this error:
```
[Log] exception thrown: TypeError: undefined is not an object (evaluating 'AL.currentContext.ctx.listener._position[0]=v1'),_alListener3f@http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:208366 (Esenthel Fantasy Demo.html, line 26)
wasm function@[wasm code]
wasm function: 4569@[wasm code]
wasm function: 4557@[wasm code]
wasm function: 2092@[wasm code]
wasm function: 4353@[wasm code]
wasm function: 4351@[wasm code]
wasm function: 6291@[wasm code]
wasm function@[wasm code]
dynCall_v@[native code]
http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:373816
browserIterationFunc@http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:174917
runIter@http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:177994
Browser_mainLoop_runner@http://esenthel.com/site/Esenthel%20Fantasy%20Demo/Esenthel%20Fantasy%20Demo.js:1:176459
```

Is this a bug in Safari?
Because Chrome, Firefox and Opera work fine.
Edge has another bug..

**Comment by dschuff** [comment]
Hard to say without know more about the code, but given where the exception is thrown, seems like it could be a bug in emscripten's OpenAL implementation, or a bug in Safari's Web Audio implementation. You might verify that by trying your demo without sound, or trying a small audio-only emscripten program.

**Comment by kripken** [comment]
In addition, building with `-s OPENAL_DEBUG=1` might give some useful logging.

**Comment by juj** [comment]
Try breaking that line up to multiple parts, i.e.

```javascript
var d = AL.currentContext;
var c = d.ctx;
var b = c.listener;
var a = b._position;
a[0]=v1;
```

or something similar to check what is the part that is undefined here? I presume this is at latest `incoming` after the large OpenAL refactor?

**Comment by GregSlazinski** [comment]
I'm using Emscripten 1.37.21

I've made a sound only app:
http://esenthel.com/site/SafariOpenALBug/Application.html

compiled it with `-s OPENAL_DEBUG=1` however no extra info showed up.

changed the code to:
```
var d = AL.currentContext;
var c = d.ctx;
var b = c.listener;
var a = b._position;
a[0]=v1;
```

Error that I get now:
```
[Log] exception thrown: TypeError: undefined is not an object (evaluating 'a[0]=v1'),_alListener3f@http://esenthel.com/site/Application/Application.js:1:209681 (Application.html, line 29)
wasm function@[wasm code]
wasm function: 4431@[wasm code]
wasm function: 4420@[wasm code]
wasm function: 1951@[wasm code]
wasm function: 4215@[wasm code]
wasm function: 4213@[wasm code]
wasm function: 5194@[wasm code]
wasm function@[wasm code]
dynCall_v@[native code]
http://esenthel.com/site/Application/Application.js:1:375796
browserIterationFunc@http://esenthel.com/site/Application/Application.js:1:174673
runIter@http://esenthel.com/site/Application/Application.js:1:177750
Browser_mainLoop_runner@http://esenthel.com/site/Application/Application.js:1:176215
```

**Comment by rspq** [comment]
Am seeing near identical issue in Mobile Safari, the same exception is thrown by AL's updateSourceSpace() where it tries to reference "src.context.audioCtx.listener._position[0]"; 

The 'listener' object is valid but it has no field named "_position".

**Comment by rspq** [comment]
My crappy workaround is to hack the emscripten source to add the custom listener fields if they're missing at the point they're wanted:

      emscripten/1.37.22/src/library_openal.js, insert the below at line 516:

      if (typeof listener._position === "undefined") {
          listener._position = [0.0, 0.0, 0.0];
          listener._velocity = [0.0, 0.0, 0.0];
          listener._direction = [0.0, 0.0, 0.0];
          listener._up = [0.0, 0.0, 0.0];
      }

**Comment by hgy29** [comment]
Stumbled upon this issue a few days ago, and been debugging it. it turns out (it seems) that webkit clears up any properties added to the AudioListener object, only keeping the one it recognizes (speedOfSound and dopplerFactor, as documented here: https://developer.apple.com/documentation/webkitjs/audiolistener). Sounds like a safari/apple bug.

A workaround woud probably be to avoid injecting custom properties into native objects. Any thought ?

**Comment by juj** [comment]
> A workaround woud probably be to avoid injecting custom properties into native objects.

I think this would be a viable general strategy for the OpenAL support library, this type of cross-browser behavioral inconsistency is somewhat common not only in Web Audio, so it's a good practice to avoid. If someone wants to write a PR to adjust OpenAL library to this, it would be very welcome.
