### ISSUE TITLE
naming conventions differs between backends

### ISSUE THREAD

**Issue by pepyakin** [kripken/emscripten#5802]
```c
extern void foo();
```

is emitted as `_foo` under `fastcomp`, however, with new LLVM backend it is emitted as `foo`.
Is there any way to make Emscripten to emit consistent names on both backends?

**Comment by kripken** [comment]
No, the new backend decided to do things differently than the old one, so you need to add or remove the prefix manually.

**Comment by pepyakin** [comment]
Could you elaborate on `(as emscripten does)`?

**Comment by kripken** [comment]
In the end, emscripten exposes the same thing on the export object, `Module`, for both backends, so you can swap them easily. So if you export the main function, you'll see `Module._main`, regardless of which backend emitted it. I believe that is done in emscripten.py where it generates the JS for that, probably it adds a `_` for the new backend.

I assume you're looking at the raw backend output, in which case the difference is still noticeable.

**Comment by pepyakin** [comment]
Thank you for elaboration!
