### ISSUE TITLE
(Potential) CI migration

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5806]
Continuing from the discussion on #5658.

[Tom Atkins from CircleCI says](https://discuss.circleci.com/t/free-plan-build-minutes-limit-on-circleci/17012):

>OSS projects built on Linux do not count towards your usage limit.

 So no worries at least for the time limit.

**Comment by nazar-pc** [comment]
Can we ask Travis CI to allow more parallel builds for this project? With multiple PRs submitted/updated it sometimes takes about 10 hours to complete them all. 5 parallel threads is clearly not enough. If Travis CI can provide more threads or more powerful machines it might be fine. But currently Travis CI is really slow.

Would be also nice to have some Docker container and a script to start multiple containers and run tests locally as they do on Travis CI. I have a powerful machine and it would be faster for me to test PRs locally first (I've added Travis CI to my fork to speed-up process a bit already).

**Comment by saschanaz** [comment]
Is there a reason to stay on Travis? If not we may try both CircleCI and Travis CI at the same time to see which is faster, then we can just switch when CircleCI is fast enough. My previous experience says [CircleCI was faster in significant way](https://circleci.com/gh/SaschaNaz/workflows/emscripten/tree/circleci), while was not always consistent.

**Comment by nazar-pc** [comment]
I'm just more familiar with Travis CI. If CircleCI is actually much faster - great!

**Comment by saschanaz** [comment]
CircleCI allows precompiling and sharing libraries including libc, which accelerates the whole build.

**Comment by kripken** [comment]
Sounds like it's worth trying CircleCI. Maybe we could run both for a while, and pick the best.
