### ISSUE TITLE
EmterpreterAsync: Moving ABORT into resume

### ISSUE THREAD

**Issue by curiousdannii** [kripken/emscripten#5816]
(Follow on from #5791)

EmterpreterAsync functions look like this:

```
	glem_select__deps: ['$EmterpreterAsync', 'window_to_id'],
	glem_select: function( data )
	{
		EmterpreterAsync.handle( function( resume )
		{
			var glk_event = new Glk.RefStruct()
			Glk.glk_select( glk_event )
			Module.glem_callback = function()
			{
				if ( ABORT )
				{
					return
				}
				Module.setValue( data, glk_event.get_field( 0 ), 'i32' )
				Module.setValue( data + 4, _window_to_id( glk_event.get_field( 1 ) ), 'i32' )
				Module.setValue( data + 8, glk_event.get_field( 2 ), 'i32' )
				Module.setValue( data + 12, glk_event.get_field( 3 ), 'i32' )
				resume()
			}
			Glk.update()
		})
	},
```

(From [my library.js file](https://github.com/curiousdannii/emglken/blob/master/emglken/library.js#L475))

I suggested that it might be possible to move the ABORT check inside resume so that people writing new functions don't need to remember to add it. But is it safe to do so? Actions between the ABORT check and calling resume might include calling functions like setValue. Could there be any problems with that?

**Comment by kripken** [comment]
If the runtime was aborted, then some operations will not be allowed, yes. But we should be ok: in `ASSERTIONS` mode, those operations should have runtime checks on them (like calling a function). And some things are ok, like `setValue` which just accesses memory.
