### ISSUE TITLE
Captured callbacks in emscripten_async_wget

### ISSUE THREAD

**Issue by Ni55aN** [kripken/emscripten#5818]
I'm trying to perform some actions on my data after downloading the file, but I can not do it since I need to capture my variables

```cpp
MyData md;
auto onload = [&](){
  md.doSmth();
};

emscripten_async_wget(url,filename, onload, onerror);
```

Getting an error
>  no viable conversion from '(lambda at /path/to/file.cpp:21:17)' to 'onload' (aka 'void (*)(const char *)')

I understand that emscripten_async_wget only accepts pointers to a function, not a lambda function, but is there a way to access my data in a callback?

**Comment by kripken** [comment]
The callback receives the filename, so you could store a map (in a global location) between filenames and other data for that filename.

**Comment by dschuff** [comment]
If you use `emscripten_async_wget_data` (https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_async_wget_data) you can pass an argument that will be handed back to your onload callback; so you could pass a pointer to your object and call a method on it. You do have to be careful about the lifetime though. Even in your example, if `md` is a local on the stack, it will go out of scope before your callback runs, and you'd have a garbage pointer in your closure.

**Comment by Ni55aN** [comment]
Thanks, with emscripten_async_wget_data it turned out, but it's very inconvenient for each time to transfer my variables to void *, and then back from the void*. Is there any way to capture objects I need, since it's done in lambda functions? That is, do not write a lot if boilerplate code
