### ISSUE TITLE
load-wasm-worker.js not found

### ISSUE THREAD

**Issue by sijakret** [kripken/emscripten#5822]
Hi,

When i enable wasm generation on a working asm build with `-s WASM=1` and then try to load the generated module.js file I run into the following problem:

Somehow the module.js script tries to side-load `load-wasm-worker.js` (probably to instantiate the wasm module or something similar) but this file does not exist.
I cannot find it anywhere - should it be generated or can it be grabbed from somewhere?

According to [the docs](https://github.com/kripken/emscripten/wiki/WebAssembly#compiler-output) i am still supposed to load the same file but it seems like some helper/glue code is not being generated or not found.

**Comment by kripken** [comment]
I don't think `load-wasm-worker.js` is something from emscripten - I can't find it in our repo. What emscripten command are you issuing, that appears to emit it or something that expects it?

**Comment by sijakret** [comment]
the problem was a very outdated sdk + me (#4032). 
after updating to `sdk-1.37.9-64bit` it worked right away.

thank you!
