### ISSUE TITLE
No std::cout output from c++ functions when main() is included in exported_functions

### ISSUE THREAD

**Issue by antmatyjajo** [kripken/emscripten#5823]
Hi,

When `main()` is included in the list of `-s EXPORTED_FUNCTIONS` passed to `emcc` command, `std::cout` no longer works in subsequently run functions. So in the case that main is exported, `std::cout` will print stuff fine when main is initially called but then will do nothing. 

For example,

```c++
#include <iostream>
#include <emscripten/emscripten.h>      

extern "C" {
  EMSCRIPTEN_KEEPALIVE                                                                    
  void print_tests() {                                                                  
    EM_ASM(                                                                             
      console.log('Hello from JS');                                                   
     ); 
    printf("printf from print_tests\n"); 
    std::cout << "cout from print_tests!" << std::endl; 
  } 

  int main(int argc, char* argv[]) {                                                      
    printf("printf from main\n");                                                         
    std::cout << "cout from main" << std::endl; 
    print_tests();
    return 0;                                                                             
  }                                                                                       
}
```

Compiling this with the following command:
```
emcc test_cout.cpp -std=c++11 -s WASM=1 -O3 -o index.js -s EXPORTED_FUNCTIONS="['_main', '_print_tests']"
```
will print everything as expected in the JS console, from ```main```. 
Subsequently trying to run ```Module._print_tests()``` produces no output on the console (in the case that this is a more complex function that returns something, I do actually get the return value, just no print output).

Compiling with a command that only exports ```print_tests```
```
emcc test_cout.cpp -std=c++11 -s WASM=1 -O3 -o index.js -s EXPORTED_FUNCTIONS="['_print_tests']"
```
results in the correct output when running ```Module._print_tests()``` in the JS console.

Can't see that I'm making an obvious mistake anywhere, so would appreciate any help; thanks!

**Comment by kripken** [comment]
I think this is because if main is exported then it is run by default when the module is loaded. Then it shuts down the runtime, flushing all file streams and closing them down, etc. You should see an error about that if you build with `-s ASSERTIONS=1`.

To avoid this, you can build with `-s NO_EXIT_RUNTIME=1`, which will keep the runtime alive, allowing code to be called after main exits.

**Comment by antmatyjajo** [comment]
Perfect, thanks! All works as expected.

Looks like I should spend some more time now digging into the compiler flags...
