### ISSUE TITLE
error in compiling C++ code contaning <windows.h> header.

### ISSUE THREAD

**Issue by gopal1022** [kripken/emscripten#5830]
I am trying to build my existing C++ libraries into web assembly with the help of emscripten toolchain in VIsualStudio 2015 community edition but getting an error of <windows.h> header .Is there any alternate for windows.h that can be used to build libraries.

**Comment by juj** [comment]
Unfortunately this is something that is not supported. Windows.h contains thousands of different functions, and the specific way to migrate away from using it depends on which of these functions are being called. Try removing that and seeing which symbols are complained about, and search for alternative APIs to replace them. If the code uses things like Win32 GDI windowing or events, then there's no other way than to rewrite it to use either HTML5 DOM with JavaScript or perhaps OpenGL ES 2/WebGL.
