### ISSUE TITLE
How to link C++ DLL to Emscripten Compiled Project.

### ISSUE THREAD

**Issue by gopal1022** [kripken/emscripten#5832]
I am porting my project to Web using Emscripten Tool chain.
It is written in c++ and have many DLL's.
Is there any to transpile the whole code including DLL's to web?
Currently I m using visual studio  2015 community edition update 3 and
emscripten version is 1.37.21.

**Comment by curiousdannii** [comment]
It depends on what exactly you're using. A lot of libraries are available already, anything that's open source could probably be ported if it hasn't been already, but anything closed source would have to be reimplemented from scratch, or avoided.

**Comment by gopal1022** [comment]
I have to port a project contaning lots of libraries/DLL's. some of them are closed source and some of them are open sourced and it is quite difficult to reimplement all of them.
So, i am finding the way to port the existing libraries with minimum changes.
please let me know whether it exist?

**Comment by dschuff** [comment]
If you have precompiled windows dlls, it's just not going to work. You need to at least be able to recompile the code, and might also need to make a few changes (e.g. the win32 API isn't available on the web)
