### ISSUE TITLE
--valid-abspath "C:\dev" crashes emcc in v1.37.22

### ISSUE THREAD

**Issue by missmah** [kripken/emscripten#5851]
After a few painful hours of hunting, I seem to have narrowed this bug down. I hope it exists only as an artifact of (somehow?) having a bad environment, but I haven't been able to determine that yet.

Essentially, if I invoke `emcc` like this:
`C:\dev\3rdparty\Emscripten\emscripten\1.37.22\emcc.bat -std=c++14 "C:\dev\SomePath\SomeFile.cpp"`

Then things work as expected, and I fail for not having specified the proper `#include` path.

If I invoke `emcc` like this (which worked in `Emscripten v1.35`):
`C:\dev\3rdparty\Emscripten\emscripten\1.37.22\emcc.bat -std=c++14 -Wwarn-absolute-paths "C:\dev\MicroGLRenderer\MicroGLRenderer\GFX\GfxTextureView.cpp" --valid-abspath "C:\dev" -I"C:\dev"`

Then I get the following error:
```
Traceback (most recent call last):
  File "C:\dev\3rdparty\Emscripten\emscripten\1.37.22\\emcc", line 13, in <module>
    emcc.run()
  File "C:\dev\3rdparty\Emscripten\emscripten\1.37.22\emcc.py", line 623, in run
    options, settings_changes, newargs = parse_args(newargs)
  File "C:\dev\3rdparty\Emscripten\emscripten\1.37.22\emcc.py", line 2042, in parse_args
    if os.path.isabs(options.path_name) and not is_valid_abspath(options, options.path_name):
  File "C:\dev\3rdparty\Emscripten\emscripten\1.37.22\emcc.py", line 2588, in is_valid_abspath
    if in_directory(valid_abspath, path_name):
NameError: global name 'in_directory' is not defined
```

If I instead invoke `emcc` like this:
`C:\dev\3rdparty\Emscripten\emscripten\1.37.22\emcc.bat -std=c++14 -Wno-absolute-paths "C:\dev\MicroGLRenderer\MicroGLRenderer\GFX\GfxTextureView.cpp" -I"C:\dev"`

Then things work as expected again, minus the protection from accidental absolute system path includes that we previously were able to opt into. This version is our current workaround for the issue, but ideally, we would very much like to go back to the `-Wwarn-absolute-paths` version.

Here's hoping that this has a simple fix, particularly that it's somehow just an artifact of my local install. But, I didn't do anything particularly interesting or deviate from the prescribed installation instructions...

**Comment by kripken** [comment]
Thanks for reporting, this is a regression on our side.

Sorry about that. This broke in a refactoring when we moved code around. Sadly the test for this was not good enough to prevent the breakage.

Fix in #5854. Includes a better test that would have prevented this regression.

**Comment by saschanaz** [comment]
This is now fixed, right?

**Comment by kripken** [comment]
I think so, yes.
