### ISSUE TITLE
Including an emscripten module in browserify build process

### ISSUE THREAD

**Issue by txusinho** [kripken/emscripten#5864]
#Hi all,

First of all, I would like to apologize if this is not the right place to ask for help to solve this issue. I'm a browserify user, and since I have problems just with a file create by emscripten, I assume the problem might live here.

Long story short, I'm importing an emscripten module in the frontend using browserify. At execution time, the module exists, but empty.

You can reproduce the issue as follows (requires emcc and browserify installed system wide):
 - Get the code from [this repo](https://github.com/txusinho/emscripten_browserify)
- Compile [this file](https://raw.githubusercontent.com/txusinho/emscripten_browserify/master/main.cpp) using emcc. I've used this command: `emcc main.cpp -o main.js -s EXPORTED_FUNCTIONS="['_int_sqrt']"`
- Create a bundle using browserify (which must be installed system wide): `browserify index.js > bundle.js`
- Open index.html in a browser, and you'll see an error in the developer console and one array showing the content of the Module object (this is, an empty array)

I've already tested that the generated code is correct: running in a node environment, works as expected (there is a demonstration using mocha [here](https://bitbucket.org/txusinho/emscripten_browserify_test/src/2c9cca133f59d9daabd261d3a266afae40e903ec/test/unit/index.spec.js?at=master&fileviewer=file-view-default)

PD: I have the same test case, but with a more elaborated toolchain in [this repo](https://bitbucket.org/txusinho/emscripten_browserify_test) with a readme to reproduce all the steps

**Comment by curiousdannii** [comment]
module.exports is set only when ENVIRONMENT_IS_NODE is true, and it won't be true if ENVIRONMENT_IS_WEB is true:

```
  ENVIRONMENT_IS_WEB = typeof window === 'object';
  ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';
  ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function' && !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_WORKER;
  ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;
```

I think it would be best to always set module.exports (if module exists etc), like it does for MODULARIZE.

Turning MODULARIZE on will probably help you @txusinho, but you will need to access the exported functions differently.

**Comment by txusinho** [comment]
@curiousdannii I appreciate your help, and the speed! The solution worked perfect on my side, and I'm able to use module as needed. The access to functions is not a problem if I have possibilities to access the Module element.

I made this question also [in stackoverflow](https://stackoverflow.com/questions/47511315/emscripten-module-in-browserify-pipeline), I'll update the answer there so anyone with the same problem can come to a solution.
