### ISSUE TITLE
emranlib is empty?

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5881]
emranlib hasn't contained any real code, why does it even exist?

**Comment by kripken** [comment]
I think it's because we can't run the system `ranlib` on our archives (which contain bitcode), so we just do nothing when `ranlib` would be called.

**Comment by curiousdannii** [comment]
It may be because llvm-ar adds an index automatically, so if you run emar and the emranlib, emranlib can be a noop?

(Aside, I have been calling ar and ranlib on my emcc produced object files and it seems to work without problems...)

**Comment by saschanaz** [comment]
Thanks for the explanations! 👍
