### ISSUE TITLE
emscripten_get_now() is painfully slow on Chrome

### ISSUE THREAD

**Issue by yairlev** [kripken/emscripten#5893]
`emscripten_get_now` uses `performance.now()` which is 3-4x slower than `Date.now()` on chrome. `performance.now()` is also 10x slower on Chrome than on Firefox.

Here's an example demonstrating it: https://jsfiddle.net/yairlev/avLx6z92/ 

There's an open bug on Chrome from Nov 2016 which was not resolved yet -
https://bugs.chromium.org/p/chromium/issues/detail?id=663120&q=performance.now&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Can `performance.now()` be replaced with `Date.now()`?

**Comment by kripken** [comment]
`performance.now` has higher precision, so it would be a breaking change for us to replace it with `Date.now`.

In general, though, these functions should not be on a hot path, as they require calling out of asm.js/wasm, which is slow anyhow. What is your codebase doing, that needs this to be fast?

**Comment by yairlev** [comment]
@kripken - We're using `std::chrono::steady_clock::now` to measure elapsed time, which seems to be calling `emscripten_get_now`

In the generated js code I see this:
```
if (ENVIRONMENT_IS_NODE) {
 _emscripten_get_now = function _emscripten_get_now_actual() {
  var t = process["hrtime"]();
  return t[0] * 1e3 + t[1] / 1e6;
 };
} else if (typeof dateNow !== "undefined") {
 _emscripten_get_now = dateNow;
} else if (typeof self === "object" && self["performance"] && typeof self["performance"]["now"] === "function") {
 _emscripten_get_now = (function() {
  return self["performance"]["now"]();
 });
} else if (typeof performance === "object" && typeof performance["now"] === "function") {
 _emscripten_get_now = (function() {
  return performance["now"]();
 });
} else {
 _emscripten_get_now = Date.now;
}
```

and in runtime I see that it resolves to this if statement:
```
_emscripten_get_now = (function() {
  return self["performance"]["now"]();
 });
```

Am I missing something?

**Comment by yairlev** [comment]
@kripken - I think I understand what's going on:

`steady_clock::now()` is calling `clock_gettime` and passing it `CLOCK_MONOTONIC` ([chrono.cpp:224](https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/system/lib/libcxx/chrono.cpp#L224)) which calls the js `performance.now()` ([library.js:2725](https://github.com/kripken/emscripten/blob/ea92fddbb6176b0d6161f167afdcc2343324ad8b/src/library.js#L2725)).
 I need `clock_gettime` to pass `CLOCK_REALTIME` which happens only if `_LIBCXX_USE_CLOCK_GETTIME` is defined ([chrono.cpp:34](https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/system/lib/libcxx/chrono.cpp#L34)), but since I'm compiling on Windows, it is not defined.

Is that correct?

**Comment by kripken** [comment]
Yes, but the bigger point here is that anything that measures the time will call out from asm.js/wasm into normal JS, and that will be slow. So it's important to avoid that in a hot loop. That's why I'm curious, what is your code doing, that needs to call this very frequently?

**Comment by yairlev** [comment]
Essentially we have a message loop on a worker thread that start a chain of events, which are handled by registered stateful methods. Some of these methods implement, internally, a throttling mechanism such that they do not invoke each cycle. The use steady_clock::now() to compare the last time they invoked with the current time.

The code base is huge and runs on multiple platforms and is highly involved such that it could not be changed. Moreover, other platforms (e.g. Windows) do not suffer from a performance hit when the call `steady_clock::now()`. The only platform that we see a substantial performance hit is on web.

I see that when I overwrite the performance.now() with `Date.now()`, the app is substantially more responsive. I understand that we cannot just replace `performance.now()` with `Date.now()` since it's a breaking change. I still don't understand why if I build on a Mac, eventually it will call `Date.now()` whereas if compiled on Windows it calls `performance.now()`

**Comment by kripken** [comment]
There should be no build difference, but it sounds like `_LIBCXX_USE_CLOCK_GETTIME` is defined in a different way on the two platforms? That's odd since emscripten doesn't use the native mac or windows target. Do you have a small testcase showing the issue? We should debug that.

Btw, `Date.now` might differ from `performance.now` in other ways, like `Date.now` can go backwards in time (daylight savings, timezone changes, etc.).

**Comment by yairlev** [comment]
You are right, `_LIBCXX_USE_CLOCK_GETTIME` is same for both platforms. When compiling on OSX it's still using `performance.now()`. I confirmed that.  

It's true that `Date.now()` can go backwards, but the odds of this happening while user is in the browser are low and even if it does happen, I don't see it affecting the user in our case. 
If I would still like to use `Date.now()` instead, should I just use `--post-js` and overwrite the`_clock_gettime` js method?

**Comment by kripken** [comment]
Yeah, that should work. Another option might be to do `performance.now = Date.now;`, but maybe that's overkill ;)

**Comment by yairlev** [comment]
Thanks for helping out.
