### ISSUE TITLE
test_failing_alloc is randomly failing on CircleCI

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#5910]
An example: https://circleci.com/gh/saschanaz/emscripten/833

I'm not seeing any helpful error message here, we should at least provide one.

**Comment by kripken** [comment]
We may need to just disable it on CI - it's a very intensive test. It allocates memory til the system malloc fails. On my local machine, it sometimes grinds everything to a halt as it swaps etc. So I guess it's not surprising it can fail on a bot.

Or maybe we can think of another way to test it. But nothing easy comes to mind.

**Comment by saschanaz** [comment]
Should it at least emit a valid error message? E.g. "Memory allocation failed".

**Comment by kripken** [comment]
Hard to detect that, it's probably just the process gets killed (by the linux OOM killer or something special on the bots).

**Comment by saschanaz** [comment]
Node emits this message when out of memory:

```
> a = new Uint8Array(2 ** 26)

<--- Last few GCs --->

[298:0x3df4e30]   216709 ms: Mark-sweep 1398.7 (1417.3) -> 1398.7 (1417.3) MB, 8752.7 / 0.1 ms  allocation failure GC in old space requested
[298:0x3df4e30]   227475 ms: Mark-sweep 1398.7 (1417.3) -> 1398.7 (1417.3) MB, 9553.0 / 0.1 ms  last resort GC in old space requested
[298:0x3df4e30]   236341 ms: Mark-sweep 1398.7 (1417.3) -> 1398.7 (1417.3) MB, 8799.0 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xaf1f6a25749 <JSObject>
    1: keys(this=0xaf1f6a046c1 <JSFunction Object (sfi = 0xacad6909d29)>,0x2ec53eeb62f9 <Uint8Array map = 0x17432ab82e09>)
    2: formatValue(aka formatValue) [util.js:458] [bytecode=0x3cd12f698771 offset=487](this=0xacad69022d1 <undefined>,ctx=0x2ec53eeb6701 <Object map = 0x17432abcb8f1>,value=0x2ec53eeb62f9 <Uint8Array map = 0x17432ab82e09>,recurseTimes=2,ln=0xacad69022d1 <undefined>)
    3: ar...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x11e177c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::PretenureFlag) [node]
 7: v8::internal::Factory::NumberToString(v8::internal::Handle<v8::internal::Object>, bool) [node]
 8: v8::internal::Factory::Uint32ToString(unsigned int) [node]
 9: 0xe01d37 [node]
10: v8::internal::FastKeyAccumulator::GetKeysFast(v8::internal::GetKeysConversion) [node]
11: v8::internal::KeyAccumulator::GetKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::KeyCollectionMode, v8::internal::PropertyFilter, v8::internal::GetKeysConversion, bool) [node]
12: v8::internal::Runtime_ObjectKeys(int, v8::internal::Object**, v8::internal::Isolate*) [node]
13: 0xea5ddc842fd
Aborted (core dumped)
```

Weird that it emits no similar message...

**Comment by saschanaz** [comment]
So now the CI says exit number -9 (which is the Python-specific way to represent SIGKILL). We may add `--max-old-space-size` to reduce maximum Node.js heap size, but I'm not sure why this happens as the default V8 heap size is 1400 MB while CircleCI provides 4096 MB memory.

**Comment by kripken** [comment]
Strange. Anyhow, I think we can just skip that test for now, if we don't have any other ideas (I don't).

**Comment by saschanaz** [comment]
I found that upgrading to Node.js v8+ fixes this problem. Memory consumption is similar (whopping nearly 4 GB), but anyway the test consistently passes on newer Node.js. Not sure why.

**Comment by senthil5053** [comment]
@saschanaz  Could you please tell me on which exact Node.js version has fixed this problem ?
