### ISSUE TITLE
unresolved symbol: memcpy

### ISSUE THREAD

**Issue by almstrand** [kripken/emscripten#5912]
Small example that shows the issue:

bug.c:
```
#include <string.h>

const char src[] = {"abc\0"};
char dst[4];

int fn() {
  int len = 4;
  memcpy(dst, &src, 4);   // <=== emcc compilation succeeds
  memcpy(dst, &src, len); // <=== emcc compilation fails
  return dst[0]; // 'a'
}
```
When passing in a constant as the third argument to `memcpy`, compilation succeeds:
```
$ emcc bug.c -s ONLY_MY_CODE=1 -s WASM=1 -s EXPORTED_FUNCTIONS="['_fn']" -o bug.js
$
```
However, when passing in a reference to a variable ("`len`") instead, compilation fails:
```
$ emcc bug.c -s ONLY_MY_CODE=1 -s WASM=1 -s EXPORTED_FUNCTIONS="['_fn']" -o bug.js
warning: unresolved symbol: memcpy
$
```
This is flagged as a warning, however in this error case, function `_fn` is no longer available in the compiled WASM module. I used the following HTML document to confirm this:

index.html:
```
<script>
const memory = new WebAssembly.Memory({ initial: 256, maximum: 256 });
const importObj = {
  env: {
    abortStackOverflow: () => { throw new Error('overflow'); },
    table: new WebAssembly.Table({ initial: 0, maximum: 0, element: 'anyfunc' }),
    tableBase: 0,
    memory: memory,
    memoryBase: 1024,
    STACKTOP: 0,
    STACK_MAX: memory.buffer.byteLength,
  }
};

fetch('bug.wasm').then((response) => response.arrayBuffer())
  .then((bytes) => WebAssembly.instantiate(bytes, importObj))
  .then((wa) => {
    console.log(`result: ${wa.instance.exports._fn()}`);
});
</script>
```
When opening this page in a browser, an error is logged:
```
Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #3 module="env" function="_memcpy" error: function import requires a callable
    at <anonymous>
```

**Comment by kripken** [comment]
This is a bug with `ONLY_MY_CODE`, I believe. It's an experimental mode that isn't much tested.

Is your goal to emit a tiny wasm file containing just the code you wrote - no system libs, no JS support code? If so then the [wasm standalone library](https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone) option might be close to what you want. Alternatively, I am working on dead code elimination optimizations now that should make us emit a tiny wasm file by default when possible, but that is not finished yet (I hope to remove `ONLY_MY_CODE` when it is).

**Comment by almstrand** [comment]
Thanks for the quick update on this issue. Exactly, I'm interested in compiling a minimal WASM module. It would be great if Emscripten's `emcc` acted just like e.g. `cc`, i.e. just generate a WASM file from my C/C++ code. I would like to load/compile/instantiate it using just a few lines of JavaScript code similar to your example in the referenced link, and not be dependent on the rather large, currently generated `.js` file. Generating a `.js` and `.html` file could be nice addition, but it seems that should not be the default behavior. Perhaps done via compiler flags?

**Comment by kripken** [comment]
The problem is that things like printing, I/O, C++ exceptions, etc., depend on JS to work. Generating just a wasm file is possible only on code that does simple pure computation.

In the near future, my goal is to get us emitting a minimal wasm file when that's possible (on simple pure computation), and to shrink the JS as much as possible otherwise (it can be much, much smaller).

In the far future, wasm may become capable of doing those things without JS. That's at least years away, though.
