### ISSUE TITLE
TypeError in _glBufferData() on Safari 11 with USE_PTHREADS=1

### ISSUE THREAD

**Issue by rspq** [kripken/emscripten#5913]
This looks like a Safari bug to me but I'm not totally sure. Also affects current Safari Technology Preview but does not affect Firefox, Chrome, etc.

When I build my project with USE_PTHREADS=1 (with a view to eventually moving some computation to a background thread) my rendering code breaks with a "TypeError TypeError" unhandled exception in _glBufferData(). Using the javascript debugger I see that the parameters going into the WebGLRenderingContext.bufferData() call in there are all valid and, more to the point, are exactly the same whether I compile with or without USE_PTHREADS=1.  However the TypeError only appears when USE_PTHREADS=1.

Does this ring any bells with anyone?

**Comment by kripken** [comment]
That does sound like a Safari bug. If those params are all the same, then the only difference is that the underlying ArrayBuffer is a SharedArrayBuffer in the pthreads case. You can probably verify that in a pthreads build by doing a manual copy in that function to a typed array on an ArrayBuffer, and that could be a good testcase to file for WebKit.

**Comment by rspq** [comment]
Thank you for the insight, I was able to write a simple jsfiddle at https://jsfiddle.net/6t1sd735/2/ that shows Safari's glBufferData() always throws a TypeError exception when given a SharedArrayBuffer. 

I'll close this and pursue it in Webkit's public issue tracker, assuming there is one.
