### ISSUE TITLE
Memory access out of bounds error

### ISSUE THREAD

**Issue by emilekberg** [kripken/emscripten#5929]
I was building my game, using OpenGL and C++17 (compiling with  adding shaders when i got this issue: 
`RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds`

I saw another thread suggesting to add this to help debugging: 
`added -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -s SAFE_HEAP=1 -s DETERMINISTIC=1`

which then lead me to get this error instead: 
`Uncaught abort("segmentation fault") at Error`

I'm not quite sure how to progress with error seaching and was looking if i could get some help.
I'm trying to run it on windows along side (using glew, glfw and freeglut) which yeilds some difference in syntax in some places, but very similar. It runs fine in windows but i get the error message in browser.

I guess my error is that i'm trying to access memory outside of my allocated one? So maybe i need more memory? or am i simply accessing a NULLPTR maybe?

this is my build command:
`em++ -O0 -s WASM=1 -std=c++1z -s FULL_ES3=1 -s USE_WEBGL2=1 -s USE_GLFW=3 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -s SAFE_HEAP=1 -s DETERMINISTIC=1 -o ./bin/onodrim.html ./Onodrim/Onodrim/Main.cpp ./Onodrim/Onodrim/src/components/Component.cpp ./Onodrim/Onodrim/src/components/RenderComponent.cpp ./Onodrim/Onodrim/src/components/Sprite.cpp ./Onodrim/Onodrim/src/components/Transform.cpp ./Onodrim/Onodrim/src/components/Transform2d.cpp ./Onodrim/Onodrim/src/Core.cpp ./Onodrim/Onodrim/src/Entity.cpp ./Onodrim/Onodrim/src/system/render/OpenGLSystem.cpp ./Onodrim/Onodrim/src/system/SystemManager.cpp`

**Comment by kripken** [comment]
The segfault should show a stack trace in the web console. You can also use the browser debugger to inspect things. Make sure to do this on a build with function names (`--profiling-funcs`, or even `-g` for full debug info).

Once you know in which function the problem happens, you can rebuild with some printfs to check for using a NULL pointer, etc.

**Comment by emilekberg** [comment]
Thank you! this really helped me find the issue :) The issue was really noobish from me. 
It seems i did comparison of pointer value with if(m_pParent && m_pParent ->method()) which seems to work with MSVC++ but not here, i did not use my HasParent method that does m_pParent != NULL;

Closing the issue and these commands are really great! Thank you again.
