### ISSUE TITLE
Emscripten / asm.js may ignore alignment on unaligned reads

### ISSUE THREAD

**Issue by aardappel** [kripken/emscripten#5939]
I had a function similar to this https://godbolt.org/g/e55e5d

```
#include <cstring>
int read_unaligned(int *p) {
    int r;
    memcpy(&r, p, sizeof(int));
    return r;
};
```

Which clang on x86 turn a single scalar load. Similarly, in emscripten (asm.js) this also appears to become a scalar load, but because it is unaligned, returns incorrect data.

The original code should be valid regardless of architecture though, so could it be that whatever alignment the load generated by LLVM (as a result of converting the memcpy) gets ignored by emscripten?

**Comment by kripken** [comment]
I believe that's undefined behavior - the compiler can assume that `int*` is aligned. You can do the copy on a `char*` if you want to support the unaligned case. (There may also be a clang attribute you can use on that pointer, I'm not sure.)

**Comment by aardappel** [comment]
Ahh.. I had assumed that because it was an argument to memcpy it would not be allowed to assume that. Makes sense, thanks.
