### ISSUE TITLE
Module.Pointer_stringify is not a function

### ISSUE THREAD

**Issue by aardappel** [kripken/emscripten#5940]
I get this error (with the emscripten binaries from https://wasm-stat.us/waterfall from 12-11-2017 I believe), regardless of -s WASM=1 or not:

```
exception thrown: TypeError: Module.Pointer_stringify is not a function,TypeError: Module.Pointer_stringify is not a function
    at Array.ASM_CONSTS (http://localhost:6931/lobster.js:1836:103)
    at _emscripten_asm_const_ii (http://localhost:6931/lobster.js:1862:26)
    at _Emscripten_ShowCursor (wasm-function[3344]:42)
    at _SDL_SetMouseFocus (wasm-function[3168]:149)
    at _Emscripten_CreateWindow (wasm-function[3278]:415)
    at _SDL_CreateWindow (wasm-function[3530]:1416)
    at __Z7SDLInitPKcRKN4geom3vecIiLi2EEEbii (wasm-function[2504]:595)
    at __ZZ11AddGraphicsvEN12___gl_window11s_gl_windowERN7lobster5ValueES2_S2_S2_S2_S2_ (wasm-function[1226]:532)
    at __ZN7lobster2VM11F_BCALLRET6Ev (wasm-function[2156]:408)
    at dynCall_vi (wasm-function[4448]:13)
```

When I manually add `Module["Pointer_stringify"] = Pointer_stringify;` in the generated .js file after that function definition, the problem goes away.

**Comment by kripken** [comment]
This is because of a recent change we made, to not export by default so many methods. In a -O0 build, or a build with `ASSERTIONS` enabled, you should see a warning pointing you to the fix for this. I guess that's an optimized build? (If not, then we need to figure out why that message didn't show up.)

If you want to export that method, you can add it to `EXTRA_EXPORTED_RUNTIME_METHODS`. However, if you use it in an `EM_ASM` (which I think is what's happening from that stack trace), then you can just use `Pointer_stringify` directly, without using it as `Module.*`. Perhaps we need to update something in the docs, was there a place where you read something out of date?

**Comment by aardappel** [comment]
Yes, this is a `-O2` build.
I did not use `EM_ASM` myself, though maybe the SDL code (2.0.7 I think) does?
I'll try with `EXTRA_EXPORTED_RUNTIME_METHODS` later..

**Comment by kripken** [comment]
Very odd. Yes, the SDL2 port uses EM_ASMs, but it should also auto-export that method for you, so things just work, https://github.com/kripken/emscripten/blob/incoming/tools/ports/sdl.py#L59

To verify this, I opened a branch with a test that uses one of those, and it works as expected, https://github.com/kripken/emscripten/commit/4ff80e4c0372ff411a237fd5864e05a96fa10b0c

Does that test not pass for you? Can you maybe provide your testcase that fails, and I'll check here?

Maybe the waterfall build is old? What version does `emcc --version` report?

**Comment by PetorSFZ** [comment]
I have the same problem, and think I have managed to pinpoint it further. Using SDL2 seem to work fine when building manually with `emcc`, but it fails when using CMake.

I get `'Pointer_stringify' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)` when compiling and running the following minimal example:

`example.cpp`:
~~~c++
#include <cstdio>

#include <SDL.h>

int main()
{
	// Init SDL2
	if (SDL_Init(SDL_INIT_EVENTS | SDL_INIT_VIDEO) < 0) {
		printf("SDL_Init() failed: %s\n", SDL_GetError());
		return EXIT_FAILURE;
	}

	// Create SDL Window
	SDL_Window* window = SDL_CreateWindow(
		"Test Title",
		SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
		512, 512,
		SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
	if (window == NULL) {
		printf("SDL_CreateWindow() failed: %s\n", SDL_GetError());
		return EXIT_FAILURE;
	}

	printf("I'd expect the program to reach this point, it does not.\n");

	// Cleanup
	SDL_DestroyWindow(window);
	SDL_Quit();

	return EXIT_SUCCESS;
}
~~~

`CMakeLists.txt`:
~~~cmake
cmake_minimum_required(VERSION 3.9 FATAL_ERROR)
project(Example CXX)

set(CMAKE_CXX_FLAGS "-s USE_SDL=2")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")

add_executable(example example.cpp)
~~~

Build commands (`$EMSCRIPTEN` is the path to the emscripten install location):
~~~
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE="$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake" -G "Unix Makefiles"
make
~~~

Some other information:
Operating System: macOS High Sierra
`emcc --version`: `emcc (Emscripten gcc/clang-like replacement) 1.37.25 ()` (latest version available using homebrew, built with closure-compiler support)

I have also tried using `emcc --clear-cache` before building, to no avail.

**Comment by aardappel** [comment]
Not sure if its CMake related since I am building with hand-written make (don't ask, yes I should fix that): https://github.com/aardappel/lobster/blob/master/dev/emscripten/Makefile

**Comment by kripken** [comment]
I see now, thanks @PetorSFZ and @aardappel - the underlying issue is a bug that happens when you compile to bitcode first, then to the executable, which is what cmake does by default, and also happens in that hand-written Makefile. We were only testing compiling SDL2 directly to an executable.

Fix + testing in #5945

**Comment by aardappel** [comment]
Verified working.

**Comment by RickHe-biubiubiu** [comment]
just try UTF8ToString(str) .  refer : https://forum.unity.com/threads/pointer_stringify-is-not-defined-pass-string-to-js.701501/
