### ISSUE TITLE
dladdr corrupts input pointer

### ISSUE THREAD

**Issue by morganbr** [kripken/emscripten#5944]
The stub implementation of dladdr in library.js writes to the input pointer rather than the output Dl_info pointer:
```
dladdr: function(addr, info) {
    {{{ makeSetValue('addr', 0, 'fname', 'i32') }}};
```
This should be setting info, not addr.

**Comment by kripken** [comment]
Yeah, that does look broken. It also says
```
    // report all function pointers as coming from this program itself XXX not really correct in any way
```
And there is no test for it.

We should figure out if we can support that method (I don't see why not), and fix it if so, or make it report an error.

**Comment by froydnj** [comment]
#6127 fixes the original issue.  I'll file followups for possibly more precise reporting of function pointer locations.  It'd also be good to not leak `fname` on every call to `dladdr`...
