### ISSUE TITLE
wasm backend: memory allocation problem

### ISSUE THREAD

**Issue by tbfleming** [kripken/emscripten#5974]
I've been experimenting with using emscripten with llvm's wasm backend, but hit memory issues. Here's an example where it allocates the same address twice.

Compile with this, open testmem.html, and look at the console.
```
em++ -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall']" -s EXPORTED_FUNCTIONS='["_main", "_test"]' -s MODULARIZE=1 testmem.cpp -o testmem.js
```

Example output:
```
pre-main prep time: 71 ms
In main
input:    0x501660 to 0x503d71
new mem:  0x501690
It overlaps
```

Tested with:
* sdk-incoming-64bit (fetched today)
* llvm 4b6a0ab74e1caeb2262384d60b0f7cf0551293fa
* clang f1094b8cc1ca05380b4fad618b7dcfdb113995e8

Also tested with:
* llvm and clang release_50

testmem.cpp:
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <emscripten.h>

int main() {
    printf("In main\n");
    EM_ASM(testJS());
}

extern "C" void test(const char* s) {
    const char* end = s + strlen(s) + 1;
    printf("input:    %p to %p\n", s, end);
    void* mem = malloc(1024);
    printf("new mem:  %p\n", mem);
    if (mem >= s && mem < end)
        printf("It overlaps\n");
}
```

testmem.html:
```html
<!doctype html>
<html lang="en-us">

<body>
    <script src="testmem.js"></script>
    <script type='text/javascript'>
        'use strict';

        let mod = Module();
        function testJS() {
            mod.ccall('test', 'void', ['string'], [' '.repeat(10000)]);
        }
    </script>
</body>

</html>
```

**Comment by tbfleming** [comment]
Tracing through:
* ```ccall``` uses ```stringToC``` which uses ```stackAlloc```
* ```stackAlloc``` returns the end of the newly-allocated block instead of the beginning.

```
 (func $stackAlloc (; 80 ;) (param $0 i32) (result i32)
  (local $1 i32)
  (set_local $1
   (i32.load offset=1024
    (i32.const 0)
   )
  )
  (i32.store offset=1024
   (i32.const 0)
   (i32.and
    (i32.sub
     (get_local $1)
     (get_local $0)
    )
    (i32.const -16)
   )
  )
  (get_local $1)
 )
```

Here's a potential fix: https://github.com/tbfleming/cib-binaryen/commit/a202b1304371b2e7769963bb9a173fbe54da9477

This patch produces:

```
 (func $stackAlloc (; 80 ;) (param $0 i32) (result i32)
  (local $1 i32)
  (i32.store offset=1024
   (i32.const 0)
   (tee_local $1
    (i32.and
     (i32.sub
      (i32.load offset=1024
       (i32.const 0)
      )
      (get_local $0)
     )
     (i32.const -16)
    )
   )
  )
  (get_local $1)
 )
```

**Comment by kripken** [comment]
Thanks, and that fix looks right to me. Maybe we're misunderstanding something about the wasm backend's stack support, though, cc @dschuff @jgravelle-google

**Comment by dschuff** [comment]
This looks right to me too, thanks.

**Comment by dschuff** [comment]
Actually, @tbfleming since you wrote this patch, can you join the WebAssembly Community Group at https://www.w3.org/community/webassembly/ so I can merge it into Binaryen?

**Comment by tbfleming** [comment]
Done. I had to fudge the signup a bit. There were two options:
* No significant relationship with an org (not true)
* Employee of an org (also not true).

I chose the first. I consult for Georgia Tech Research Institute, part of GT, but I'm not an employee, more of a freelancer. The contract I signed doesn't give them claim to what I've been doing here.

**Comment by dschuff** [comment]
Thanks! I merged the patch, so this issue should hopefully be fixed.
