### ISSUE TITLE
Linker should not enforce existence of --end-group

### ISSUE THREAD

**Issue by DopefishJustin** [kripken/emscripten#5982]
shared.py has the following assert:

```assert current_archive_group is None, '--start-group without matching --end-group'```

GNU ld does not enforce this, it just ends any open groups automatically when it reaches the end ([ref](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=ld/lexsup.c;h=cb9edaf7a6ac665e16004a145b657e3fbfcc3252;hb=HEAD#l1580))

Emscripten's behaviour makes it impractical to use --start-group with a build system such as GENie that allows you to specify linker options but doesn't have a concept of separate beginning and ending linker options. (The common case is just throwing everything into one group to avoid ordering issues.)

**Comment by kripken** [comment]
Thanks for the info. Makes sense, we should remove that assert, and add a test (in `tests/test_other.py`). It's possible removing the assert isn't enough and we need to manually add an end at the end, I'm not sure. Either way, it should be fairly simple.

**Comment by froydnj** [comment]
I will take this one; the hardest bit is writing the test.

**Comment by DopefishJustin** [comment]
That does the trick, thanks!
