### ISSUE TITLE
SDL2 IMG_Load failed after emscripten_run_preload_plugins_data

### ISSUE THREAD

**Issue by gliheng** [kripken/emscripten#5993]
I'm trying to pull data from web then put it on the canvas. After I pass the image data to `emscripten_run_preload_plugins_data`, I use `IMG_Load` to get a surface and I got a NULL pointer.
I read SDL1 test case and it works fine, but SDL2 does not have a test case for `emscripten_run_preload_plugins_data`.

```C++
#include <stdio.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <assert.h>
#include <emscripten.h>
#include <unistd.h>
#include <stdlib.h>
#include <string>

SDL_Window *window;
SDL_Renderer *renderer;

void ready(void *arg, const char *fileName) {
  printf("ready! %s (%d)\n", fileName, (int)arg);

  // SDL_Surface *image = IMG_Load(fileName);

  // SDL_Texture* tex = SDL_CreateTextureFromSurface(renderer, image);

  SDL_Texture *tex = IMG_LoadTexture(renderer, fileName);

  SDL_RenderCopy(renderer, tex, NULL, NULL);
  SDL_DestroyTexture (tex);

  SDL_RenderPresent(renderer);

  printf("you should see an image.\n");

  SDL_Quit();
}

int main() {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_CreateWindowAndRenderer(600, 450, 0, &window, &renderer);

#define SIZE 203164
  FILE *f = fopen("icon.png", "rb");
  char *buffer = (char *) malloc(SIZE);
  fread(buffer, SIZE, 1, f);
  fclose(f);

  emscripten_run_preload_plugins_data(buffer, SIZE, "png", (void*)25, ready, NULL);

  return 0;
}

```

**Comment by gliheng** [comment]
Hey, after some digging. I think it's a SDL2_image issue. IMG_Load in SDL2_image repo miss logic to read from preload data. I opened a pull request.[SDL2_image pull request](https://github.com/emscripten-ports/SDL2_image/pull/7)

**Comment by gliheng** [comment]
I have send a [pr](https://github.com/kripken/emscripten/pull/6030) for this issue and I'm closing this now.

**Comment by froydnj** [comment]
@gliheng Did you mean to reopen this issue?

**Comment by gliheng** [comment]
This issue is already closed as in [here](https://github.com/kripken/emscripten/pull/6030), sorry.  Closing it now.
