### ISSUE TITLE
Command line too long on Windows

### ISSUE THREAD

**Issue by dcodeIO** [kripken/emscripten#5997]
I recently ran into an issue on Windows where invoking `em++` with a long command line fails to execute because of some limit in `cmd.exe`. This happens, for example, when trying to compile binaryen.js manually with its longish `EXPORTED_FUNCTIONS` parameter where bash is not available.

Is there another way to specify exported functions? Like from a file? Or might wildcards be supported at some point, e.g, `EXPORTED_FUNCTIONS=["_Binaryen*", "_Relooper*"]`?

I know I could use powershell, but because the command is invoked from node via `child_process.spawn` with `{ shell: true }` in my scenario, that's not really an option, unfortunately.

**Comment by dcodeIO** [comment]
Solved it meanwhile by spawning python directly. Wildcards might be nice-to-have, though.

**Comment by curiousdannii** [comment]
I think you can put the functions in a JSON file and then reference the file like this, but I haven't specifically tested it for EXPORTED_FUNCTIONS:

`EXPORTED_FUNCTIONS="@exported.json"`

**Comment by froydnj** [comment]
We have tests for `EXPORTED_FUNCTIONS=@response-file`:

https://github.com/kripken/emscripten/blob/incoming/tests/test_core.py#L6360-L6381
https://github.com/kripken/emscripten/blob/incoming/tests/test_core.py#L6383-L6417

so yes, that should work.  I think that means we can close this issue?

**Comment by dcodeIO** [comment]
Yes, thanks!
