### ISSUE TITLE
binaryen.js compilation issues with 1.37.23+

### ISSUE THREAD

**Issue by dcodeIO** [kripken/emscripten#5998]
It seems binaryen.js no longer compiles with 1.37.23 or newer (using emsdk's windows binaries).

Haven't tested **1.37.27** because there are no prebuilt binaries yet.

**1.37.24, 1.37.25, 1.37.26**

When `--closure 1` is specified, compilation fails on invocation of closure compiler with exit code 1. Though `-v` doesn't provide more information, I assume that it happens for the same reason as below.

When `--closure 1` is not specified, it compiles but loading binaryen.js errors with `[TypeError: Cannot assign to read only property 'stack' of object 'Error: No such file or directory']` which originates somewhere [around here](https://github.com/kripken/emscripten/blob/incoming/src/library_fs.js#L1381). I've read somewhere that making the `stack` property `writable: true` where it's defined might solve this.

**1.37.23** errors with `Exception: closure compiler error: java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0`.

**1.37.22** appears to be the last working version.

**Comment by saschanaz** [comment]
>Haven't tested `1.37.27` because there are no prebuilt binaries yet.

So it seems the bot failed again. I think we need a new way to build them...

**Comment by dcodeIO** [comment]
Regarding 1.37.27, this is what emsdk tells me:

```
The following precompiled SDKs are available for download: (Run "./emsdk update" to pull in the latest list)
         sdk-nightly-1.37.9-2017_04_19_23_39-64bit
         sdk-nightly-1.37.9-2017_04_20_04_06-64bit
         sdk-1.30.0-64bit
         sdk-1.34.1-64bit
         sdk-1.35.0-64bit
         sdk-1.37.1-64bit
         sdk-1.37.25-64bit              INSTALLED
         sdk-1.37.26-64bit              INSTALLED
```

**Comment by saschanaz** [comment]
Yeah, it seems the bot failed to generate new precompiled SDK. And AFAIK the compilation failure should be fixed on 1.37.27. (#5923)

**Comment by kripken** [comment]
I think this might be a different problem, actually - if it's failing on closure, it's probably a new closure error from the new closure version. And we do test building binaryen.js on the bots now... but if Java isn't installed, closure is skipped.

But running this locally on binaryen master and emscripten incoming, I don't see a closure error. I do see a runtime error, which without closure looks like this:
````
TypeError: "stack" is read-only
Stack:
  ensureErrnoError/<@a.js:1:201156
  ensureErrnoError@a.js:1:201064
  staticInit@a.js:1:201241
  @a.js:1:230897
  @a.js:1:52
````
That looks like a recent emscripten change to setting the stack in `ensureErrnoError`, I think by you @saschanaz ? Could explain why this fails on some machines but not others, as I think it was a workaround for some node.js version? A bigger question though might be why is binaryen.js using ErronoError or filesystem support at all, that seems wrong.

**Comment by kripken** [comment]
Error happens on
```
FS.genericErrors[code].stack = "<generic error, no stack>"
```

**Comment by saschanaz** [comment]
Ah yes, opened #5999.

**Comment by dcodeIO** [comment]
With 1.37.28 I'm seeing the following Closure Compiler error again:

```
  File "...\shared.py", line 2279, in closure_compiler
    raise Exception('closure compiler error: ' + process.stdout + ' (rc: %d)' % process.returncode)
Exception: closure compiler error: java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Exception in thread "main"  (rc: 1)
```

**Comment by saschanaz** [comment]
That means your Java version is lower than 8: https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

You should use Java 8+ for Closure Compiler.

**Comment by saschanaz** [comment]
>Unsupported major.minor version 52.0

Does Closure Compiler now requires Java 9?

**Comment by dcodeIO** [comment]
Checking my emsdk directory, I see `java/7.45_64bit` there.

**Comment by saschanaz** [comment]
Emscripten recentely updated Closure Compiler and the update version now requires Java 8. The updated emsdk (which you can get from https://github.com/juj/emsdk) provides Java 8.

**Comment by dcodeIO** [comment]
Thanks, replacing the JRE with a newer solves the issue as well.

**Comment by saschanaz** [comment]
We probably should check Java version on sanity check to prevent this situation anyway...

**Comment by dcodeIO** [comment]
Just updated emsdk to master, still installs Java `7.45_64bit`.

**Comment by saschanaz** [comment]
That's strange, Java 8 is expected to be the default provided version now. Did you do `emsdk install latest` or something else?

**Comment by dcodeIO** [comment]
I always do

```
emsdk update
emsdk list
# pick the latest precompiled for windows
emsdk install sdk-1.37.28-64bit
emsdk activate sdk-1.37.28-64bit
```

Should I try latest?

**Comment by dcodeIO** [comment]
Heh, and suddenly it's `1.7.0_45-b18` again.

**Comment by saschanaz** [comment]
What Node.js version do you get, BTW? It should be 8.9.1 instead of old 4.1.1.

**Comment by juj** [comment]
> So it seems the bot failed again. I think we need a new way to build them...

This bug was resolved, and with `emsdk update-tags`, the 1.37.28 version should appear.

**Comment by juj** [comment]
Hmm, it sounds like some people are not getting the new Java update.. What happens if you run `emsdk update-tags` command explicitly instead of `emsdk update`? Does your `emsdk_manifest.json` file contain the following?

```json
  {
    "version": "%precompiled_tag64%",
    "bitness": 64,
    "uses": ["clang-e%precompiled_tag64%-64bit", "node-8.9.1-64bit", "python-2.7.5.3-64bit", "java-8.152-64bit", "emscripten-%precompiled_tag64%"],
    "os": "win",
    "version_filter": [
      ["%precompiled_tag64%", ">", "1.37.22"]
    ]
  },

```

**Comment by dcodeIO** [comment]
Fwiw, [this is my one](https://pastebin.com/4sZCJkBh) at this point in time after update-tags/update. No signs of Java 8 or node 8 (I manually replaced them).

**Comment by juj** [comment]
Thanks @dcodeIO : with that file I think I now see what is going on. Working on deploying a fix..

**Comment by juj** [comment]
As a workaround you can try directly bootstrapping via `git clone https://github.com/juj/emsdk.git`

**Comment by bsokol** [comment]
It is mine emsdk_manifest.json after emsdk update-tags :
https://pastebin.com/8RTy0REV

**Comment by juj** [comment]
Thanks - calling `emsdk update` should now update the manifest as well.

**Comment by bsokol** [comment]
Thanks! After normal update and activation, I have already proper setup on windows! :)

```
Set the following tools as active:
   git-1.9.4
   mingw-7.1.0-64bit
   clang-e1.37.33-64bit
   node-8.9.1-64bit
   python-2.7.5.3-64bit
   java-8.152-64bit
   emscripten-1.37.33
```

**Comment by froydnj** [comment]
@juj Does the above mean this issue can be closed?

**Comment by dcodeIO** [comment]
Confirming that after `emsdk update`, `emsdk install latest` now installs the correct packages (node 8.9.1, java 8.152). Thanks!
