### ISSUE TITLE
Is there a way to specify multiple constructors to a class?

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#600]
Note: This issue relates to a yet-not-merged embind pull request #592.

In MathGeoLib, I have a class float2, which has a default ctor float2(), and a parameter-taking ctor float2(float x, float y);

I tried exposing both of those with the form 

class_<float2>("float2")
    .constructor<>()
    .constructor<float,float>();

But it seems that effectively only the last exposed ctor works, and if I call 'var v = new float2();' in JS, I will get an error complaining that the ctor requires two arguments.

Being able to specify multiple ctors would be an important for conveniency in using MathGeoLib from JS.

**Comment by chadaustin** [comment]
@blockspacer Nice! Perhaps you should take your example and update the documentation at https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#overloaded-functions with the technique?

**Comment by chadaustin** [comment]
p.s. I think this issue is worth closing - the original feature has long been implemented. (cc @juj )
