### ISSUE TITLE
fgetc for virtual fs not working properly?

### ISSUE THREAD

**Issue by shooshx** [kripken/emscripten#6010]
I have the following html calling an emscripten compiled c file:

```
<html><head>
<script src="asm_js_main.js"></script>
<script>
function start() {
    run_nasm = Module.cwrap('run_nasm', null, ['string'])
    
    FS.writeFile('player1.asm', 'mov ax,bx\r\n', { encoding:'binary' })
    
    run_nasm('player1.asm')
}
</script></head>
<body onload="start()">
</body></html>
```

with a single .c file that contains this code:

```
int run_nasm(const char* filename)
{
    const char* filename = argv[1];
    FILE* f = fopen(filename, "rt");
    while (!feof(f)) {
        char c = fgetc(f);
        int ic = (int)c;
        printf("%d\n", ic);
    }
}
```

The expected result is that it would print out the ascii codes of the given file and then -1
instead what it does is output 11 times '0' and then -1.

This indicates a bug in `fgets` but I was not able to locate the bug or find a workaround yet.

**Comment by shooshx** [comment]
this is with:

> emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.37.1 ((unknown revision))

**Comment by shooshx** [comment]
Changing 'binary' to 'utf8' seem to produce the expected result. So the bug seem to be limited to 'binary' encoding.

**Comment by saschanaz** [comment]
I think the bug is in `writeFile` rather than in `fgetc`. Looking at the code, `encoding: 'binary'` only supports `ArrayBufferView` and `encoding: 'utf-8'` only supports `string`. The function should throw when it meets unsupported parameter pair but it doesn't. (Not sure why it even needs `opts` parameter then.)

**Comment by shooshx** [comment]
Interesting, I probably assumed the problem is in the output because I was getting 11 zeros so atleast the length does come from the input when it's a string. The documentation actually only says 'data' can be ArrayBufferView so, my bad for not noticing this and it should probably be updated to the to the actual behavior
