### ISSUE TITLE
Chrome produces this issue in the console:

### ISSUE THREAD

**Issue by JGames101** [kripken/emscripten#6012]
> on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)
abort("on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)") at Error
    at jsStackTrace (file:///C:/Users/John/Documents/Development/WebAssembly/hello/wasm2.js:1:13954)
    at stackTrace (file:///C:/Users/John/Documents/Development/WebAssembly/hello/wasm2.js:1:14125)
    at abort (file:///C:/Users/John/Documents/Development/WebAssembly/hello/wasm2.js:1:31908)
    at getBinary (file:///C:/Users/John/Documents/Development/WebAssembly/hello/wasm2.js:1:20520)
    at file:///C:/Users/John/Documents/Development/WebAssembly/hello/wasm2.js:1:20884
    at <anonymous>
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

On firefox, the code works properly. I am using the default template.

**Comment by eosrei** [comment]
*If someone else finds this issue...*

Chrome displays this message for local files `file:///home/user/WebAssembly-WebGL-2/build/index.html`, load the file via a web server using `http://` and it will be fine.

**Comment by jhasanjiv5** [comment]
Run the html file as "emrun filename.html" from the terminal, it will automatically launch the file in localhost. "emrun" is a command from Emscripten.

**Comment by palafranchise** [comment]
I've been using this bag file which has both "/camera/depth/image" and "/camera/rgb/image_color" topics with Image messages.

https://vision.in.tum.de/rgbd/dataset/freiburg1/rgbd_dataset_freiburg1_xyz.bag

Note: I had to decompress it.

Here's the `rosbag info` output:

```
rosbag info rgbTest.bag 
path:        rgbTest.bag
version:     2.0
duration:    30.4s
start:       May 10 2011 12:38:18.38 (1305031098.38)
end:         May 10 2011 12:38:48.81 (1305031128.81)
size:        1.6 GB
messages:    25626
compression: none [1598/1598 chunks]
types:       sensor_msgs/CameraInfo         [c9a58c1b0b154e0e6da7578cb991d214]
             sensor_msgs/Image              [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu                [6a62c6daae103f4ff57a132d6f95cec2]
             tf/tfMessage                   [94810edda583a504dfda3829e70d7eec]
             visualization_msgs/MarkerArray [f10fe193d6fac1bf68fad5d31da421a7]
topics:      /camera/depth/camera_info     798 msgs    : sensor_msgs/CameraInfo        
             /camera/depth/image           798 msgs    : sensor_msgs/Image             
             /camera/rgb/camera_info       798 msgs    : sensor_msgs/CameraInfo        
             /camera/rgb/image_color       798 msgs    : sensor_msgs/Image             
             /cortex_marker_array         3034 msgs    : visualization_msgs/MarkerArray
             /imu                        15158 msgs    : sensor_msgs/Imu               
             /tf                          4242 msgs    : tf/tfMessage
```
