### ISSUE TITLE
Worker processes broken on Windows?

### ISSUE THREAD

**Issue by stevenvergenz** [kripken/emscripten#6017]
The ammo.js build script calls `Building.link()` (from `tools/shared.py`) during its build script, which uses worker processes to load and unpack each assembly. However, for undetermined reasons, instead of the workers running the function passed to `multiprocessing.Pool#map`, they seem to be running the Ammo.js build script again in a loop.

Initially this produced illegible console spam when I tried to build ammo, but by forcing the emscripten pool size to 1 I could read the output, which was the ammo script running again and again. Emscripten seems to block at the first call to the worker pool ([tools/shared.py:1764](https://github.com/kripken/emscripten/blob/incoming/tools/shared.py#L1764)), and no emscripten code is run in the workers (no initializer function, no task function).

My only theory is this note in the [python documentation](https://docs.python.org/2/library/multiprocessing.html#using-a-pool-of-workers):

> **Note**: Functionality within this package requires that the \_\_main\_\_ module be importable by the children. This is covered in Programming guidelines however it is worth pointing out here. This means that some examples, such as the Pool examples will not work in the interactive interpreter.

Not sure if this is an error in Ammo.js's build script or in Emscripten. Feel free to close if not appropriate. Versions: Emscripten 1.37.26, Windows 10, Ammo.js 431ffae (latest master at time of writing)

**Comment by juj** [comment]
Is it this script that gets reimported again and again? https://github.com/kripken/ammo.js/blob/master/make.py

I think the referenced python doc page is the relevant one. The way Python subprocesses work on Windows, where `fork()` is not available is that they create new python process from scratch, and make that python process import the same series of python modules that the parent had. This means that importing cannot lead to creating new subprocesses or doing other multiprocessing/file-io/system sensitive ops in global scope, but wrapping to `__main__` is needed.

You can try to debug by globally setting `set EMCC_CORES=1` before running the build - does that avoid the issue altogether from occurring? If so, you can try wrapping the contents of the whole ammo.js `make.py` script inside a function, say, `def build():`, and then at the very end of `make.py`, have

```py
if __name__ == '__main__':
  build()
```

Check out this commit https://github.com/kripken/emscripten/commit/0a33856f60c02e552a311f5eb00c85095904e078 from a distant past which fixed the same issue in another script.

**Comment by stevenvergenz** [comment]
This is spot-on, thank you! I'll file a PR for ammo with your suggested changes.
