### ISSUE TITLE
Starting with emscripten

### ISSUE THREAD

**Issue by umeboshi2** [kripken/emscripten#6019]
I noticed emscripten a couple of years ago, but I never really bothered to play around with it.  I don't quite remember when I learned about WebAssembly, but it was early 2017, and it piqued my interest.  During that time, I just cloned repos and dabbled in the examples, but didn't get too involved.  I built stuff that was already ported (or partially ported) to see how things were.  I decided to really start to learn more during the holidays and read up a bit more.  I also thought it would be better to attempt to port a couple of simple projects to get my feet wet, since I was only experienced in code that was already "massaged" to work in the browser.  I chose two projects to start with, one a (hopefully) simple sdl emulator for genesis [dgen](https://github.com/umeboshi2/dgen) and a simple console program [bible-kjv](
https://github.com/umeboshi2/bible-kjv) (as I write this I just realize that the bible starts with genesis, lol).

My experience with porting dgen can be read in the readme.md on the "front page."  My main question for this port is that I presumed that ```ALLOW_MEMORY_GROWTH``` would allocate enough memory to run the program.  However I found that it wouldn't work unless I also set ```TOTAL_MEMORY``` higher.  I was under the impression that I could use ```ALLOW_MEMORY_GROWTH``` when developing and set ```TOTAL_MEMORY``` at a reasonable size for deployment.  This didn't work for me, and this is the primary issue to bring to y'all concerning this attempt to port dgen.  

At the moment, the dgen port is stuck on a ```copyOnLock``` failure that hasn't been resolved.  I read through both #754, as well as dreamlayer's article [here](http://dreamlayers.blogspot.com/2015/04/optimizing-emscripten-sdl-1-settings.html).  I played with the relevant(?) boolean options in ```SDL.defaults``` but didn't get anywhere but a dead page that had to be ```SIGTERM```'ed.  I am not expecting help with this problem, but if somebody happens to notice a quick or easy solution, it would be very welcome.  The debian package is in bad shape and is only available in i386, though upstream is 64bit ready, and there is a wishlist bug to that effect.  The last time I actually programmed using SDL was through PyGame, and that was ten years ago when I setup a slideshow/marquee program for a local watering hole.

Failing at dgen, I decided to take refuge in the [bible](https://github.com/umeboshi2/bible-kjv).  It's an old and more simple program that I felt could be more easily ported.  In fact, I was much more successful with this one.  It depends on readline, but I couldn't get that to work very well.  I gave up on readline and found [editline](https://github.com/troglobit/editline).  I was able to build the library without modifying any code, yet only setting config options, so I only had to adjust the bible code a bit to refer to editline.  I was almost successful, yet still impeded by obstacles.  Here is the output and stack trace:

```console
this.program: Debian/BRS Release 4.18, $Date: 2005/01/23 11:29:22 $
Hit '?' for help.

Genesis 1

  1 In the beginning God created the heaven and the earth.
bad ioctl syscall 21507
abort("bad ioctl syscall 21507") at Error
    at jsStackTrace (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:1259:13)
    at stackTrace (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:1276:12)
    at abort (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:30154:44)
    at ___syscall54 (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:5048:18)
    at _ioctl (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:26624:9)
    at _tcsetattr (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:26644:9)
    at _setattr (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:15323:10)
    at _rl_ttyset (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:15260:9)
    at _rl_prep_terminal (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:10887:2)
    at _el_prep (http://localhost:8080/EM-ports/foo/bible-kjv/bible-kjv.js:11750:2)
```

I made a gist that builds both editline and bible-kjv, so y'all can see how I did everything.  
The gist is here:  https://gist.github.com/umeboshi2/14c321c520e801e6493c8d75f4682dde

I looked up 21507 and got ```TCSETS```, which according to [this](https://github.com/kripken/emscripten/blob/4c5a6416f935a2a35626a397217633330d30286e/src/library_syscall.js#L331), seems to be a no-op, leading me to believe that it shouldn't crash.  I would like some help with this, since this seems to be a far more simple problem than the foregoing ```copyOnLock``` problem in dgen.

I have actually enjoyed working with emscripten.  I had forgotten what it was like to mess with c/c++ code and autotools.  I'll be honest, I've been in interpreters and away from compiling for so long, I'm not very familiar with cmake and clang, etc.  Most of the compiling and building I have done in the last 10-12 years has been primarily making debian packages, so I haven't really needed to get very deep into some of the problems such as the ones I've had in the last few days.  Yet, it seems a lot easier to find the info to solve the problem compared to back then when I had to resort to IRC or a mailing list.  Thanks!

**Comment by juj** [comment]
21507 is actually `TCSETSW`, which was missing in the list. The above PR adds the other variants to the no-op list.

**Comment by umeboshi2** [comment]
Thanks!  I guess I did some good by porting a console app.  I pulled the PR into ```$EMSDK/emscripten/incoming```.  I thought I might be able to test it with prebuilt clang, but it looks like I really have to use clang-incoming as well.  I am at 14% of clang build right now.  I'll give you a progress report when I'm able to test it.  I used --build=Release for the install.

**Comment by umeboshi2** [comment]
Thanks!  It's "working."  :+1:  The input seems to be an alert box and the content is printed in the javascript console.  It's working quite fine in node.  I would like to keep the issue open and determine what's happening with ```ALLOW_MEMORY_GROWTH```.  I left a description of what I did in the [readme](https://github.com/umeboshi2/dgen/blob/master/README.md).

**Comment by umeboshi2** [comment]
@juj , "I would like to keep the issue open and determine what's happening with ALLOW_MEMORY_GROWTH. "
Should I open another issue for this?
