### ISSUE TITLE
do_run receives extra_emscripten_args and ignores it

### ISSUE THREAD

**Issue by saschanaz** [kripken/emscripten#6023]
`do_run()` receives `extra_emscripten_args` and passes to `build()`, and finally to `ll_to_js()` but the `ll_to_js` does nothing with `extra_emscripten_args`

https://github.com/kripken/emscripten/blob/7dfffd8af19cacadad9782bccd6458cc724d388e/tests/runner.py#L295-L316

Several tests use `extra_emscripten_args`, I'm not sure what caused this situation.

**Comment by kripken** [comment]
We can remove it and all the stuff using it. I have a vague memory from the args passed using it like `libc/fcntl.h`, we used that arg a long time ago to work around some libc issue, but it's now irrelevant.

**Comment by kripken** [comment]
Fixed by that PR.
