### ISSUE TITLE
How can I export FS in js file?

### ISSUE THREAD

**Issue by lokpoi888** [kripken/emscripten#6061]
When I use FS in a .js file, the FS is undefine in Module, and I have already used '-s FORCE_FILESYSTEM=1'
the revision is emsdk-1.37.9
How can I use FS in js file?
the js code is shown below
`WebCore.FS.writeFile(filename, new Uint8Array(array), { encoding: "binary" });`
the tag I used when emcc is
-o web_core.js -s ASSERTIONS=1 -s MODULARIZE=1 -s TOTAL_MEMORY=1024*1024*128 -s FORCE_FILESYSTEM=1 -s TOTAL_STACK=1024*1024*96 -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_NAME=\"WebCore\" --bind --preload-file simkai.ttf --llvm-lto 1 --closure 1

**Comment by juj** [comment]
Try running without closure or without modularizing? Are you then able to access FS?

(Btw, the stack size `1024*1024*96` is remarkably high, in general it's best to have e.g. a few megabytes stack at most, since most of that memory is wasted from other use)

**Comment by lokpoi888** [comment]
I have tried a simple example use `emcc sample.cpp -o sample.js -s FORCE_FILESYSTEM=1`，but there has no `Module["FS"]` or `Module['FS']` in the sample.js.
The sample.cpp just have a simple function.
`int add (int x, int y) {
  return x + y;
}`
Is there something wrong in sdk-1.37.9?

**Comment by saschanaz** [comment]
It's not exposed by default as of now, you should add `-s "EXTRA_EXPORTED_RUNTIME_METHODS=['FS']"`.

**Comment by lokpoi888** [comment]
Thank you very much! It works after I used `-s "EXTRA_EXPORTED_RUNTIME_METHODS=['FS']"`
