### ISSUE TITLE
FUNCTION_POINTER_ALIGNMENT not working?

### ISSUE THREAD

**Issue by mhallin** [kripken/emscripten#6068]
Hello!

I'm trying to compile an older C++ codebase containing a bunch of assumptions regarding the values of pointers. The most problematic assumption is that function pointers are assumed to be aligned to something greater than one - the code basically does something like this (don't ask me why :) ):

```c++
size_t GLOBAL_TABLE[] = { reinterpret_cast<size_t>(&callback1), ... };

float compute(int param, float value) {
  size_t ptr = GLOBAL_TABLE[param];
  if ((ptr & 1) == 0) {
    float (*callback)(float) = reinterpret_cast<float(*)(float)>(ptr);
    return callback(value);
  }
  else {
    // Do something else...
  }
}
```

Since Emscripten packs all functions in the `FUNCTION_TABLE_*` arrays, the indices will sometimes be odd, and thus the comparison will fail.

To remedy this, I found the [`FUNCTION_POINTER_ALIGNMENT`](https://github.com/kripken/emscripten/blob/master/src/settings.js#L212-L217) setting, which _sounds_ like it would pad the tables with zeroes. However, this setting does not seem to have an effect, and [searching for uses](https://github.com/kripken/emscripten/search?utf8=✓&q=FUNCTION_POINTER_ALIGNMENT&type=) shows that it's only used for the reserved function pointer setting.

Am I misinterpreting the parameter's purpose, is this setting deprecated or scheduled for removal, or is this something that should work?

**Comment by kripken** [comment]
Yes, this does look like an old setting that is no longer functional - that it doesn't have any tests is the worst sign ;)

We should remove it, I think, as I don't think there is enough general benefit from it. But it should be easy for you to hack in what you want, the relevant code is here:

https://github.com/kripken/emscripten-fastcomp/blob/incoming/lib/Target/JSBackend/JSBackend.cpp#L481

You can probably just hardcode a value >1 for `Alignment` there.
