### ISSUE TITLE
Problem Finding 'corecrt.h' during Windows Compilation

### ISSUE THREAD

**Issue by blockulator** [kripken/emscripten#6077]
Looks like corecrt.h can't be found now it's been moved to the Win10 SDK, how can I get it to find this file?

`emsdk install --build=Release sdk-incoming-64bit binaryen-master-64bit`

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory [c:\emsdk\clang\fastcomp\build_incoming_vs2015_64\utils\PerfectShuffle\llvm-PerfectShuffle.vcxproj]`

**Comment by kripken** [comment]
Emscripten can't compile native windows apps. There would need to be a port of those APIs to the web first.

Currently emscripten can port code that uses portable APIs like libc, SDL, OpenGL, etc.

**Comment by kripken** [comment]
Does this problem happen when installing the emsdk? If so, is there more info on the commandline before that?

**Comment by ukpaul** [comment]
Yes, I'm using "emsdk install". This error repeats a lot, but actually the first error complains about PlatformToolset now I look closer. 
 
```
Successfully updated and checked out branch 'incoming' on repository 'c:/emsdk/c
lang/fastcomp\src\tools/clang'
Current repository version: "Mon, 8 Jan 2018 15:24:13 -0800 29de7f517cc4f0ed17a4
123e73844713da6c3430"
Running CMake: ['cmake', '-G', 'Visual Studio 14 Win64', '-DCMAKE_BUILD_TYPE=Rel
ease', '-DPYTHON_EXECUTABLE=C:\\Python27\\python.exe', '-DLLVM_TARGETS_TO_BUILD=
X86;JSBackend', '-DLLVM_INCLUDE_EXAMPLES=OFF', '-DCLANG_INCLUDE_EXAMPLES=OFF', '
-DLLVM_INCLUDE_TESTS=OFF', '-DCLANG_INCLUDE_TESTS=OFF', '-DLLVM_ENABLE_ASSERTION
S=OFF', 'c:/emsdk/clang/fastcomp\\src']
-- Warning: Did not find file Compiler/MSVC-ASM
CMake Warning at cmake/modules/CheckCompilerVersion.cmake:47 (message):
  Host Visual Studio should at least be 2015 Update 3 (MSVC 19.00.24213.1)
  due to miscompiles from earlier versions
Call Stack (most recent call first):
  cmake/config-ix.cmake:15 (include)
  CMakeLists.txt:583 (include)


-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Sphinx disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-pc-win32
-- LLVM default target triple: x86_64-pc-win32
-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
-- Using Release VC++ CRT: MD
-- Constructing LLVMBuild project information
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86
-- Targeting JSBackend
-- Clang version: 4.0.0
-- SampleAnalyzerPlugin ignored -- Loadable modules not supported on this platfo
rm.
-- PrintFunctionNames ignored -- Loadable modules not supported on this platform
.
-- AnnotateFunctions ignored -- Loadable modules not supported on this platform.

-- BugpointPasses ignored -- Loadable modules not supported on this platform.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/emsdk/clang/fastcomp/build_incoming_vs20
15_64
Performing a parallel build with 3 cores.
Running build: ['C:\\Program Files (x86)\\MSBuild/14.0/Bin/amd64\\MSBuild.exe',
'/t:Build', '/p:Configuration=Release', '/p:Platform=x64', '/nologo', '/verbosit
y:minimal', 'LLVM.sln']
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(365,5): warning MSB8003: Could not find VCInstallDir variable from the regis
try.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versio
n number. [c:\emsdk\clang\fastcomp\build_incoming_vs2015_64\ZERO_CHECK.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(365,5): warning MSB8003: Could not find VCInstallDir variable from the regis
try.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versio
n number. [c:\emsdk\clang\fastcomp\build_incoming_vs2015_64\lib\Demangle\LLVMDe
mangle.vcxproj]
  ItaniumDemangle.cpp
C:\emsdk\clang\fastcomp\src\include\llvm/Demangle/Demangle.h(10): fatal error C
1083: Cannot open include file: 'cstddef': No such file or directory [c:\emsdk\
clang\fastcomp\build_incoming_vs2015_64\lib\Demangle\LLVMDemangle.vcxproj]

```

**Comment by kripken** [comment]
It should install a binary build by default, which should not require a compile at all. Unless you are intentionally building from source?

In any case, this looks like a windows-specific compilation issue, maybe @juj can take a look.

**Comment by juj** [comment]
The include directories are something that CMake should be detecting. Try running the build from VS 2015 Command Prompt (either the unqualified, or if that doesn't do anything, then the X64 prompt), and see if that affects anything?

Alternatively, you can try emsdk installing with `--vs2017`, that's the current official VS version that LLVM is supporting. Not sure if these header lookups might behave different with versions.

**Comment by ukpaul** [comment]
My project uses threads so I wanted to try out experimental wasm pthread support which requires the latest incoming branch. But it might be that canary/FF nightly have disabled features I need to run the wasm because of Spectre/Meltdown, but I didn't get to looking in to it too far yet.

I'll get back to trying to build from source on Windows at the weekend anyway.

**Comment by juj** [comment]
You can manually re-enable SharedArrayBuffer in Firefox by setting `javascript.options.shared_memory;true` in `about:config`. I think Chrome Canary has a similar startup command line dev option or an experimental flag.

**Comment by blockulator** [comment]
This is my fault for not taking the time to read up correctly I think as I'm usually on Linux, but it seems the setup for windows is different and I can get everything I need with "emsdk install latest." I can build wasm but when I run it in FF nightly I get the error "wasm streaming compile failed: TypeError: Response has unsupported MIME type".

I'm not sure where the problem on that lies yet, but it's a different issue so I'll close this one.

**Comment by malamanteau** [comment]
I am having this same (or similar) issue. 

Windows 7 + VS2017
emsdk install sdk-master-64bit --build=Release --vs2017

```
c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.14.26428\include\cstddef(7): 
fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory 
[C:\emsdk\clang\fastcomp\build_master_vs2017_64\lib\Demangle\LLVMDemangle.vcxproj]
```
