### ISSUE TITLE
ONLY_MY_CODE results in empty file

### ISSUE THREAD

**Issue by taralx** [kripken/emscripten#6078]
Compiling with latest on macos:

emcc -Oz -s ONLY_MY_CODE=1 -s WASM=1 -o out.html x.c

Yields an 81 byte wasm file. No code is generated.

x.c is simply "int x() { return 4; }"

**Comment by taralx** [comment]
FWIW, I have yet to find a set of options that doesn't include a bunch of irrelevant stuff, like memoryBase or __post_instantiate in my wasm output.

**Comment by curiousdannii** [comment]
I assume you still need to set EXPORTED_FUNCTIONS.

**Comment by kripken** [comment]
As @curiousdannii said, you need to export things or it thinks they are removeable. You can also use `EMSCRIPTEN_KEEPALIVE` in the C code (from emscripten.h).

If you want minimal output, try just using very latest incoming with something like `-Os -s WASM=1` (optimize for size, and without `ONLY_MY_CODE`). That will turn something like
```
#include <emscripten.h>

EMSCRIPTEN_KEEPALIVE
int add(int x, int y) {
  return x + y;
}
```
into just 42 bytes of wasm, with just what you want in it. It disassembles to this:
```
(module
 (type $0 (func (param i32 i32) (result i32)))
 (export "_add" (func $0))
 (func $0 (; 0 ;) (type $0) (param $var$0 i32) (param $var$1 i32) (result i32)
  (i32.add
   (get_local $var$1)
   (get_local $var$0)
  )
 )
)
```

**Comment by taralx** [comment]
```> emcc -Oz -s ONLY_MY_CODE=1 -s WASM=1 -s EXPORTED_FUNCTIONS="['x']" -o out.html x.c
> type out.wast
(module
  (import "env" "memory" (memory $0 256 256))
  (import "env" "table" (table 0 0 anyfunc))
  (import "env" "memoryBase" (global $memoryBase i32))
  (import "env" "tableBase" (global $tableBase i32))
  (global $f0 (mut f32) (f32.const 0))
)```

**Comment by taralx** [comment]
Apparently I need _x instead of x. It works now!
