### ISSUE TITLE
long strings not printed by printf 

### ISSUE THREAD

**Issue by ledbit** [kripken/emscripten#6095]
I'm just starting with emscripten and running into an issue where a `printf` line seems  to be caped at 1024 characters (not including the null-termination character) 

```
#include <cstdio>

#define X 1026
int main(){
  char c[X];
  for(int i=0;i<X;i++)
    c[i] ='A';
  c[X-1] = '\0';
  printf("pre, X=%d\n", X);
  printf("%s\n", c);  /// if X > 1025 this line doesn't print 
  printf("=== after === \n");
}
```

here's how I'm compiling and running it
```
/mnt/ledion/workspace/asmjs$ emcc mem.cpp -s NO_EXIT_RUNTIME=0 -o mem.js && node mem.js
pre, X=1025
AAAAAAAAAAAAAAAA .....
=== after === 
```
line doesn't print when adding one more char
```
/mnt/ledion/workspace/asmjs$ emcc mem.cpp -s NO_EXIT_RUNTIME=0 -o mem.js && node mem.js
pre, X=1026

=== after === 
```

the compiled C++ version seems to work fine 
```
/mnt/ledion/workspace/asmjs$ ./a.out 
pre, X=1026
AAAAAAAAAAAAAAAAA .....
=== after === 
````

Am I missing some buffer setting somewhere?

**Comment by kripken** [comment]
Thanks! Yeah, this is a bug. A really silly one-letter typo in our JS syscall code, actually. Fix in #6096.
