### ISSUE TITLE
How to expose static class variables?

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#610]
Note: This issue relates to a yet-not-merged embind pull request #592.

In MathGeoLib, I have static class members like

static const float3 float3::zero = float3(0,0,0);
static const float3 float3::one = float3(1,1,1);
static const float3 float3::unitX = float3(1,0,0);
static const float3 float3::unitY = float3(0,1,0);
static const float3 float3::unitZ = float3(0,0,1);
static const float3 float3::nan = float3(nan,nan,nan);
static const float3 float3::inf = float3(inf,inf,inf);

I don't see embind_test.cpp showing an example of how static class variables are exposed, so I'm assuming this is still an unsupported feature? It would be nice to be able to say float3.unitX and float3.nan

How about the const btw?  Is it possible to make the members read-only? E.g. with this? https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by motiz88** [comment]
Sorry to revive an old issue, but is this still on the radar in some form? I'd like to add my vote to a `constant()` method on `class_`.

**Comment by chadaustin** [comment]
Fixed!  I added a `class_property` method to `class_` for binding static fields.  If someone wants to take a stab at adding `global()` for binding globals or general statics, feel free to copy the style of the code in patch 1f6b09d.

**Comment by ThorstenBux** [comment]
@chadaustin, just wondering was an option to expose a global C variable ever implemented?

**Comment by chadaustin** [comment]
@ThorstenBux I don't think it's been done yet, but I'd be happy to review a patch. It's probably fairly straightforward.

**Comment by ThorstenBux** [comment]
@chadaustin, thanks for your reply. Just that I'm not heading in the wrong direction. I'd like to get access to this https://github.com/artoolkitx/artoolkitx/blob/master/Source/ARX/ARX_c.cpp#L70 from JS. Is that what you would call a global? Might there be another way to bind it to JS? Highly appreciate your feedback.

**Comment by chadaustin** [comment]
@ThorstenBux Indeed, though that's a raw pointer so you might have better luck writing binding-specific wrapper functions that make it more natural to access from JavaScript, which wouldn't require updating embind itself.
