### ISSUE TITLE
Problem in addFunction support for Wasm backend

### ISSUE THREAD

**Issue by aheejin** [kripken/emscripten#6100]
# Goal
Add addFunction support to LLVM backend runtime (#5673)

# Fastcomp's Approach
When [`RESERVED_FUNCTION_POINTERS`](https://github.com/kripken/emscripten/blob/20486c99be91d91dad04e1c3011961f3a048706c/src/settings.js#L194) option is used, here is basically how [`addFunction`](https://github.com/kripken/emscripten/blob/20486c99be91d91dad04e1c3011961f3a048706c/src/support.js#L251-L281) works for fastcomp:

JavaScript creates [`functionPointers`](https://github.com/kripken/emscripten/blob/20486c99be91d91dad04e1c3011961f3a048706c/src/support.js#L249) array that has `RESERVED_FUNCTION_POINTERS` number of entries. When you add a JS function using `addFunction`, it inserts the function in the `functionPointers` array and returns its index + 1. This number (index + 1) is passed to a Wasm program and will be used as a function index to indirectly call the added JS function. A sample usage is in [`test_add_function`](https://github.com/kripken/emscripten/blob/20486c99be91d91dad04e1c3011961f3a048706c/tests/test_core.py#L6336-L6367) and these two files:
https://github.com/kripken/emscripten/blob/incoming/tests/interop/test_add_function_post.js
https://github.com/kripken/emscripten/blob/incoming/tests/interop/test_add_function.cpp

In asm.js side, a function table is generated for every function signature that is used for indirect function call sites. In each of these function tables, we reserve the `RESERVED_FUNCTION_POINTERS` number of entries for `jsCall` thunks. We need `RESERVED_FUNCTION_POINTERS` number of entries for each signature, because we wouldn't know the signature of functions that are going to be added using `addFunction`, and we should be able to support that many functions at the same time. So, for example, when `RESERVED_FUNCTION_POINTERS` is 3 and there are two signatures 'vi' and 'iii' used by indirect function calls, the function tables in asm.js side are gonna look like
```
var FUNCTION_TABLE_vi = [nullfunc, jsCall_vi_0, jsCall_vi_1, jsCall_vi_2, ... ]
var FUNCTION_TABLE_iii = [nullfunc, jsCall_iii_0, jsCall_iii_1, jsCall_iii_2, ... ]
(Index 0 of each table is reserved by a null function)
```

Also asm.js side has those `jsCall_sig_N` thunk functions:
```
function jsCall_vi_0(a1) {
  a1=a1|0;
  jsCall_vi(0,a1|0);
}

function jsCall_vi_1(a1) {
  a1=a1|0;
  jsCall_vi(1,a1|0);
}

function jsCall_iii_0(a1,a2) {
  a1=a1|0; a2=a2|0;
  return jsCall_iii(0,a1|0,a2|0)|0;
}

function jsCall_iii_1(a1,a2) {
  a1=a1|0; a2=a2|0;
  return jsCall_iii(1,a1|0,a2|0)|0;
}
```

And in the JS side, we have these `jsCall_sig` functions, which are to be imported from Wasm code (after the asm.js code above is converted to Wasm)

```
function jsCall_vi(index,a1) {
  functionPointers[index](a1);
}

function jsCall_iii(index,a1,a2) {
  return functionPointers[index](a1,a2);
}
```

The reason the approach above works is, each function signature has its separate function table, so whatever index returned by `addFunction` has its matching `jsCall_sig_N` thunk in the asm.js side at the same index in its function table. asm2wasm will eventually merge those multiple function tables into one, but all `call_indirect` instructions will be taken care of by adding appropriate base numbers to their function indices.

# Problem for Wasm Backend
But in Wasm, there is a single function table that contains functions with all signatures. This becomes problematic for addFunction support, because, when `addFunction` returns an index, we don't know which signature thunk function to put in the corresponding slot in the Wasm function table. For example, if `addFunction` returns 2. What kind of `jsCall_??` thunk function should we put in the 2nd slot in the Wasm table for that? We don't know the function signature that will be added by `addFunction`, and it's not even fixed, because functions can be added by `addFunction` and removed by `removeFunction` multiple times. Reserving (# of indirectly called function signatures * # of reserved function pointers) entries in Wasm side wouldn't work because `addFunction` can't figure out the added JS functions' signatures anyway.

# Possible Solutions (?)
Discussed with @jgravelle-google and came up with two possible solutions (?), and I admit, both of them are ugly and I really like neither. :( But other than that I'm currently not sure how we can support this. New suggestions are welcome too.

## 1. addFunction takes an additional Wasm signature string
So the usage is going to be like
```
var funcptr = addFunction(somefunction, 'vi');
```

Basically, binaryen will gather all the function signatures that are used in `call_indirect` instructions, and pass the list of signatures and the start index to emscripten using metadata. For example, we have # of reserved function pointer = 3 and binaryen passes the info below:
- jsCall thunk start index = 2
- Function signatures used in `call_indirect`s = ['vi', 'ii']

This way, emscripten then can return appropriate index based on the given added function's signature. If an added function has a signature 'vi', it returns index 2 or 3, based on the order. If it's 'ii', it will return 4 or 5. And in the Wasm side, the function table would look like
```
Table = [0, jsCall_vi_0, jsCall_vi_1, jsCall_ii_0, jsCall_ii_1, ...]
```
And it can work similarly to the fastcomp version. 

### Downside
It is an API change, previous code will break, and the user has to figure out what the function's signature is going to be when it is called in Wasm.

## 2. Convert every call_indirect into a call to a JS helper function
We reserve some unlikely range, let's say 1000000 ~ (1000000 + # of reserved function pointers), for `addFunction`'s use in the JS side. Now `addFunction` returns the actual index + 1000000. So the first return value of `addFunction` is 1000000, the second is 1000001, and so on. Here is an example case of 'vi'. We should do this for every signature used in `call_indirect` and convert every `call_indirect` instruction to a `call` instruction to an appropriate `jsCall_helper_sig` function. The JS helper functions will see the index, and if it belongs to the reserved range, it figures out that the call is to functions added by `addFunction` and calls an appropriate function. If the index does not fall into the reserved range, it's a normal indirect call, so we forward the call back to the Wasm side using `dynCall_sig`.

### Before
- Wasm side
```
...
 (call_indirect (type $FUNCSIG$vi)
  (arg)
  (index)
 )
...
```

### After
- Wasm side
```
(import "env" "jsCall_helper_vi" (func $jsCall_helper_vi (param i32 i32))
...
 (call $jsCall_helper_vi
  (arg)
  (index)
 )
...
```
- JS side
```
function jsCall_helper_vi(arg1, index) {
  if (index > 1000000)
    functionPointers[index - 1000000](arg1);
  else
    Module[`dynCall_vi`](index, arg);
}
```

### Downside
Every indirect function call will now become a inter Wasm-JS function call. This can be a huge performance issue.

**Comment by kripken** [comment]
Very good analysis.

I think the first option is better, the downsides are less bad there. We can document this well and have good error messages, hopefully there will be only minimal confusion for users.

**Comment by Lachrista** [comment]
@kripken @aheejin 
have question,
Why can't I use a callback function (addFunction) in a pthread?

Created a thread function (ThreadFunction)using pthread_create in the test.c .
At the same time，let the callback function point to addFunction.
Once the callback function is called in the ThreadFunction,will be error
,in pthread-main.js : functionPointers[index] is not a function
Is there a solution?
I look forward to hearing from you.
![error](https://user-images.githubusercontent.com/35955917/43885286-095eddda-9beb-11e8-95e1-89ace7bd5982.png)

**Comment by Lachrista** [comment]
well,
I tried to modify the pthread-main.js and can pass the data back to the upper layer via postMessage.
But it's too much trouble, which means that I need to manually change pthread-main.js every time I compile test.js
I believe that you have a better solution, I hope you can reply to me, thank you very much.
@kripken

**Comment by kripken** [comment]
@Lachrista yes, it looks like `functionPointers` is JS code that needs to be forwarded between the main thread and JS workers, so until we do that it won't work. Sounds like you have a partial solution for that already, by sending messages, would you like to open a PR with it?
