### ISSUE TITLE
No warning for notifying pre-main prep time?

### ISSUE THREAD

**Issue by kkimdev** [kripken/emscripten#6156]
We are working on an Emscripten application and recently started running continuous integration.  It came to our attention that tests are failing because it outputs the following console warning every time it loads.

```
'pre-main prep time: .....'
```

It's not too difficult for us to make an exception to that, but I feel like that shouldn't be printed out as warning at the first place, as there is noting going wrong really.  How about `Module.print` instead of `Module.printErr`

https://github.com/kripken/emscripten/blob/fcab695dc6dea96a1b0a8c26b4e6243a1d8deb2a/src/postamble.js#L285

**Comment by kkimdev** [comment]
@Deepayan-Ghosh

**Comment by kripken** [comment]
Thanks, yeah, we should do something about that. It should probably be behind another flag than `ASSERTIONS` at least, but maybe we should just remove it entirely? If no one objects to that, it's probably best.

**Comment by kkimdev** [comment]
I think it's OK to remove it.  It's not to difficult for users to measure themselves if they really want to see those values.
