### ISSUE TITLE
How can I load compiled files from a subfolder?

### ISSUE THREAD

**Issue by PawelekS** [kripken/emscripten#6164]
_How can I load compiled files from a subfolder?_

I want to create a project with such file architecture:
```
/webassembly/
    ├ index.html
    ├ css/
    ├ js/
    └ wasm/
        ├ example.cpp
        ├ example.js (generated by emscripten)
        └ example.wasm (generated by emscripten)
```

I'm using that emcc command syntax:
![image](https://user-images.githubusercontent.com/28712303/35638428-5ec4119c-06b7-11e8-9d8b-0e9d4a366091.png)

I'm loading example.js file by that markup:
![image](https://user-images.githubusercontent.com/28712303/35638451-6f49b71a-06b7-11e8-868c-c253a7c1397c.png)

Finally, the console is showing me that error:
![image](https://user-images.githubusercontent.com/28712303/35638472-800f041a-06b7-11e8-8f44-d986f5b96ac8.png)![image](https://user-images.githubusercontent.com/28712303/35638492-89ff8684-06b7-11e8-95d3-84c79ad973b1.png)

I did some research, but I didn't find any way to solve that problem.
Keeping all files in the root directory isn't good idea :/

**Comment by juj** [comment]
You can define a custom function in the `Module` object to specify how the compiled output downloads files relative to the main .js file. In your shell file:

```js
Module.locateFile = function(url) { return 'wasm/'+url; };
```

Currently the semantics are to treat relative URLs to be processed relative to the document's [baseURI](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) (the location of the `.html` file). There is a proposal to make relative URLs be treated relative to the `.js` file instead of being relative to the baseURI, but that's a semantically breaking change so has not yet proceeded; see #5484, #5368 (these relate to fixing another similar issue in node.js so the conversation ranges)

**Comment by PawelekS** [comment]
Great!

For future embarrassed people:
```html
<script> window.Module = { locateFile: url => `wasm/${url}`} </script>
<script src="./your/path/to/compiled.js"></script>
```
 ---

Well, i have included the script, but now console is showing me that warning:
![image](https://user-images.githubusercontent.com/28712303/35642744-6d1f0bea-06c4-11e8-89bf-e94883ddc6e2.png)

I read about it, but nobody find the solution. Do You know how can i fix that?

**Comment by juj** [comment]
Check out this recent emscripten-discuss thread: https://groups.google.com/d/msg/emscripten-discuss/C7-i1gqWay4/x2sSl2qmBQAJ

**Comment by froydnj** [comment]
@kripken or @juj, it looks like this issue has been addressed; can we close it?

**Comment by kripken** [comment]
Yeah, and I see we already have docs on the wiki.

**Comment by chase-moskal** [comment]
@Evolveye 

i attempted to use your solution, however, even though the emscripten module is picking up `locateFile`, i can see that `locateFile` is never actually being called or used

```js
	window.Module = {
		locateFile: url => {
			console.log("LOCATE", url)
			debugger
			return `./path/${url}`
		}
	}
```

the emscripten module is looking for `webp.wasm` and `webp.js.mem` at the *server root*, which is the wrong location, and i'm trying to influence the emscripten module to look at the location relative to the emscripten module -- but emscripten appears to be ignoring my `locateFile` definition

i can see in the debugger that emscripten is initially picking up my Module definition here, but i don't know why it's not being called
