### ISSUE TITLE
Cannot issue normal fetch if IndexedDB initialization failed

### ISSUE THREAD

**Issue by yume-chan** [kripken/emscripten#6169]
I'm dealing a mystery browser based on Chrome 39 where my `emscripten_fetch` calls silently fail.

After I enabled `-s FETCH_DEBUG=1`, I get 

> fetch: indexedDB.open(dbname="emscripten_filesystem", dbversion="1");
> fetch: IndexedDB upgrade needed. Clearing database.
> fetch: IndexedDB open failed.

(10 seconds later)

> still waiting on run dependencies:
> dependency: library_fetch_init
> (end of list)

That leads me to the fetch initialization method here:

https://github.com/kripken/emscripten/blob/c5a455873a5ee84ac07961e06a3a58204e5813b2/src/Fetch.js#L78-L105

Note that `onerror` handler doesn't call `removeRunDependency('library_fetch_init')`.

But by the following code:

https://github.com/kripken/emscripten/blob/c5a455873a5ee84ac07961e06a3a58204e5813b2/src/Fetch.js#L541-L570

I should still be able to issue normal requests using `EMSCRIPTEN_FETCH_REPLACE | EMSCRIPTEN_FETCH_LOAD_TO_MEMORY` flags, without IndexedDB support.

So is it intended to not callback `removeRunDependency('library_fetch_init')` to disable fetch function when IndexedDB initialization failed?

**Comment by juj** [comment]
> Note that onerror handler doesn't call removeRunDependency('library_fetch_init').

Hmm, there's a call to it here: https://github.com/kripken/emscripten/blob/incoming/src/Fetch.js#L102 . Does that not get called?

**Comment by juj** [comment]
Oh wait, now I see - does the fix in PR #6178 work for you?

**Comment by yume-chan** [comment]
Yes it fixes my problem.
