### ISSUE TITLE
Using Emscripten generated Wasm Module for Benchmark.js

### ISSUE THREAD

**Issue by gischi1704** [kripken/emscripten#6184]
Im trying to make some benchmark tests using the "benchmark.js" library, which is already working fine for me. I want to test the performance between C++ code compiled to wasm / asm.js and similar written functions in javascript.

 Anyways, i already used the Standalone Wasm Version to export converted wasm functions to add them into my benchmark.suite. This works very well:

loadWebAssembly('fibo.wasm')
.then(instance => {
    var fibo_wasm = instance.exports.__Z9fibonaccii;
    var fibo_wasm_rec = instance.exports.__Z12fibonacciReci;
    console.info(fibo_wasm(7));
    console.info(fibo_wasm_rec(7));
    const suite = new Benchmark.Suite; //Anlegen der Benchmark Suite und hinzufügen von Funktionen
    suite.add('js', () => fibo_js(numToFibo))
    suite.add('js_rec', () => fibo_js_rec(numToFibo))
    suite.add('asm', () => _fibo_asm(numToFibo))
    suite.add('asm_rec', () => _fibo_asm_rec(numToFibo))
    suite.add('wasm', () => fibo_wasm(numToFibo))
    suite.add('wasm_rec', () => fibo_wasm_rec(numToFibo))
.on('cycle', function(event) {
console.log(String(event.target));
})
.on('complete', function() {
console.log('Fastest is ' + this.filter('fastest').map('name'));
console.log('Slowest is ' + this.filter('slowest').map('name'));
})
.run({ 'async': true });
}
);

Im trying to add more functions, but this time I wanna use some code with linear algebra functions by using the "Eigen"-C++ library. But after trying to export some functions into Wasm-Standalone format, im running into many errors (importing issues). If i just compile it to Wasm with the Js-GlueCode and run the JS-File it works fine. My Question:
How can i bind the JS-GlueCode (with wasm) into my Benchmark Suite? Maybe there are other options, im pretty new in that (writing my thesis about Wasm). I would be very grateful if you can help me there.

Greetings, 
gischi

**Comment by kripken** [comment]
By standalone do you mean this? https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone

In general there isn't a way to make all programs standalone. They might need JS to do various things, or might currently depend on JS that could be eventually rewritten to wasm.

That shouldn't be a problem for benchmarking, though, just compile to js+wasm (default emscripten output when emitting wasm) and run the JS, which will load and run the wasm for you. The benchmark will still measure the speed of wasm (unless it spends most of its time in JS support code, but in computational benchmarks that shouldn't happen).

The one tricky thing you might see is that wasm startup is async, so the benchmark harness needs to wait for an event to tell it it finished (hopefully that's easy in benchmark.js, I'm not familiar with it). On the emscripten side, see https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions

**Comment by gischi1704** [comment]
Thank you very much, your Information helped me alot. It's working now and i can make the benchmarks for performance comparisons.
