### ISSUE TITLE
Missing .so file generation via emmake from 1.37.29

### ISSUE THREAD

**Issue by kwonoj** [kripken/emscripten#6185]
I am feeling I did something obvious mistake, but I couldn't pinpoint what it is - mind ask some help for this?

I've been building libprotobuf via emscripten (applying custom patch https://github.com/kwonoj/protobuf-wasm into protobuf source code) in docker image at https://github.com/kwonoj/docker-arch-emscripten. I have bumped up emscripten from `1.37.28` to `1.37.29`, and `emmake` result is different between two versions.

```
#run docker with 1.37.28
$docker build --tag test-1.37.28 --build-arg BUILD_TARGET=protobuf 
--build-arg PROTOBUF_VERSION=3.5.1.1 --build-arg EMSCRIPTEN_VERSION=1.37.28 .

...
drwxr-xr-x 2 builder builder     4096 Feb  4 00:41 .
drwxr-xr-x 1 builder builder     4096 Feb  4 00:41 ..
-rw-r--r-- 1 builder builder  1396644 Feb  4 00:41 libprotobuf-lite.a
lrwxrwxrwx 1 builder builder       22 Feb  4 00:41 libprotobuf-lite.la -> ../libprotobuf-lite.la
-rw-r--r-- 1 builder builder     1008 Feb  4 00:41 libprotobuf-lite.lai
lrwxrwxrwx 1 builder builder       26 Feb  4 00:41 libprotobuf-lite.so -> libprotobuf-lite.so.15.0.1
lrwxrwxrwx 1 builder builder       26 Feb  4 00:41 libprotobuf-lite.so.15 -> libprotobuf-lite.so.15.0.1
-rw-r--r-- 1 builder builder  1146056 Feb  4 00:41 libprotobuf-lite.so.15.0.1
-rw-r--r-- 1 builder builder 10168142 Feb  4 00:41 libprotobuf.a
lrwxrwxrwx 1 builder builder       17 Feb  4 00:41 libprotobuf.la -> ../libprotobuf.la
-rw-r--r-- 1 builder builder      973 Feb  4 00:41 libprotobuf.lai
lrwxrwxrwx 1 builder builder       21 Feb  4 00:41 libprotobuf.so -> libprotobuf.so.15.0.1
lrwxrwxrwx 1 builder builder       21 Feb  4 00:41 libprotobuf.so.15 -> libprotobuf.so.15.0.1
-rw-r--r-- 1 builder builder  8386364 Feb  4 00:41 libprotobuf.so.15.0.1
...
```
example job log: https://travis-ci.org/kwonoj/docker-arch-emscripten/jobs/337081030

```
#run docker with 1.37.29
$docker build --tag test-1.37.29 --build-arg BUILD_TARGET=protobuf 
--build-arg PROTOBUF_VERSION=3.5.1.1 --build-arg EMSCRIPTEN_VERSION=1.37.29 .

...
drwxr-xr-x 2 builder builder     4096 Feb  4 00:54 .
drwxr-xr-x 1 builder builder     4096 Feb  4 00:54 ..
-rw-r--r-- 1 builder builder  1396644 Feb  4 00:54 libprotobuf-lite.a
lrwxrwxrwx 1 builder builder       22 Feb  4 00:54 libprotobuf-lite.la -> ../libprotobuf-lite.la
-rw-r--r-- 1 builder builder      917 Feb  4 00:54 libprotobuf-lite.lai
-rw-r--r-- 1 builder builder 10168142 Feb  4 00:54 libprotobuf.a
lrwxrwxrwx 1 builder builder       17 Feb  4 00:54 libprotobuf.la -> ../libprotobuf.la
-rw-r--r-- 1 builder builder      902 Feb  4 00:54 libprotobuf.lai
...
```
example job log: https://travis-ci.org/kwonoj/docker-arch-emscripten/jobs/337085364

before 1.37.29, `emmake` emits `.so` files in build results but from 1.37.29 there aren't. Both images are using same protobuf version and patch code, also no configuration differences. Just fyi, I also tried latest release 1.37.33 and it works same as 1.37.29.

I'm bit confused by this result - is there any changes around emscripten requires additional configuration or is it just my simple mistakes around current configurations?

I run `emmake` for the build: 
`sh autogen.sh && emconfigure ./configure CXXFLAGS="-O2" && emmake make`
(https://github.com/kwonoj/docker-arch-emscripten/blob/3ad50b2ffdb5b982675e16aab4fd88bcfefba6d8/Dockerfile#L47)

**Comment by kwonoj** [comment]
diffing two logs, I could see differences like:

1.37.28
```
INFO:root:(Emscripten: Running sanity checks)
yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... /usr/lib/emscripten/em++ -E
checking for ld used by /usr/lib/emscripten/em++... /usr/lib/emscripten/emcc
checking if the linker (/usr/lib/emscripten/emcc) is GNU ld... yes
```

1.37.29
```
INFO:root:(Emscripten: Running sanity checks)
no
checking dynamic linker characteristics... ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... python /usr/lib/emscripten/em++.py -E
checking for ld used by python /usr/lib/emscripten/em++.py... python /usr/lib/emscripten/emcc.py
checking if the linker (python /usr/lib/emscripten/emcc.py) is GNU ld... yes
```

so shared lib building is indeed disabled in 1.37.29, but still not sure why / how to configure this correctly.

**Comment by kripken** [comment]
That's odd, I can't think of anything we did that should affect that. But configure scripts are often sensitive to minor things like even the output of `compiler --version`. Maybe if you look in the configure script, you can see what it is checking (what command it runs) in the configure check that changes?

**Comment by kwonoj** [comment]
@kripken I have very few knowledge around `configure` / other build configuration thing, reason I'm struggling with. This is protobuf's autoconfigure for 3.5.1.1 (https://github.com/google/protobuf/blob/3.5.1.1/configure.ac) , but bit hard to figure out what exactly it's checking by reading it myself.

**Comment by kripken** [comment]
Yeah, reading configure scripts is not always easy. It might be easier to bisect on emscripten commits, in between those two versions.

**Comment by kwonoj** [comment]
That's I've been tried last weekend so far (https://github.com/kripken/emscripten/compare/279e6a00b322f7fed56b3418f1e65645c7ae1985...16df331292e156d5578c053c26bc73943904d6d0) 

and so far no great luck, due to my lacks of internals on emscripten as well. This kind of flag change (https://github.com/kripken/emscripten/commit/3d2574b72e2a7c24e480bffff7cd6b9584fa4428) or tooling side change (https://github.com/kripken/emscripten/commit/f067c2ab762348d0017f115628c7778c719b9909) looks bit suspicious, but I wasn't able to setup my machine to build each commit of emscripten to bisect behavior by building libprotobuf for each.

**Comment by kripken** [comment]
I can try to bisect it then. Can you write up super-simple instructions for me to do everything I need in order to get to the point of seeing that different behavior on your codebase?

**Comment by kwonoj** [comment]
Let me try to split up from docker image instructions so you can try to run build locally. will /cc you with instructions.

**Comment by kwonoj** [comment]
@kripken this is mininal steps:

```
rm -rf ./protobuf

git clone https://github.com/google/protobuf ./protobuf
git clone https://github.com/kwonoj/protobuf-wasm ./protobuf/wasm-patch

cd protobuf
git checkout v3.5.1.1
git apply ./wasm-patch/*.patch
sh autogen.sh && emconfigure ./configure CXXFLAGS="-O2" && emmake make
ls -al ./src/.libs
```

Basically clones protobuf, apply patch, then `emmake`.

Not surprisingly, I try this on one of my Mac OS machine with 1.37.33 and it does correctly configure shared lib linking. It seems your theory around minor configuration thing is affecting. 

Fyi, I've been using linux image based on arch linux, installed dependencies are below.

base docker image:  `antergos/archlinux-base-devel`

```
sudo binutils  fakeroot  base-devel  python2  alsa-lib  desktop-file-utils gtk2 glibc
clang  cmake  libnotify libxtst libxkbfile libsecret nss gvfs gconf libgnome-keyring 
libxss  curl openssl c-ares http-parser xorg-server-xvfb unzip python python-setuptools 
python2-setuptools jre8-openjdk
```
(node.js installed via nvm, `8.9.4`)

**Comment by kripken** [comment]
What is the final instruction in those steps - am I looking to see if there is or isn't a `.so` in that `ls -al` output?

Running the line with autogen, it fails on
```
protobuf$ sh autogen.sh && emconfigure ./configure CXXFLAGS="-O2" && emmake make
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    407      0 --:--:-- --:--:-- --:--:--   408
100  362k  100  362k    0     0   524k      0 --:--:-- --:--:-- --:--:-- 1318k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    421      0 --:--:-- --:--:-- --:--:--   421
100  618k  100  618k    0     0   881k      0 --:--:-- --:--:-- --:--:-- 12.4M
+ autoreconf -f -i -Wall,no-obsolete
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by kwonoj** [comment]
Yes, ls -al is to verify build output. I haven't seen autogen failure yet :thinking_face:

**Comment by Kagami** [comment]
Have same issue on incoming fastcomp/emscripten with lame library. Configure script reports that shared libraries are not supported. Will try to investigate this.

**Comment by Kagami** [comment]
For some reason

```
python /path/to/emsdk/emscripten/incoming/emcc.py --help 2>&1 | /bin/grep -E ': supported targets:.* elf'
```

returns nothing in configure script. While in normal shell it's fine.

**Comment by Kagami** [comment]
```
+ python /home/kagami/code/tmp/emsdk/emscripten/incoming/emcc.py --help
Traceback (most recent call last):
  File "/home/kagami/code/tmp/emsdk/emscripten/incoming/emcc.py", line 2786, in <module>
    run()
  File "/home/kagami/code/tmp/emsdk/emscripten/incoming/emcc.py", line 352, in run
    ''' % (open(shared.path_from_root('site', 'build', 'text', 'docs', 'tools_reference', 'emcc.txt')).read()))
  File "/usr/lib/python-exec/python3.5/../../../lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 14377: ordinal not in range(128)
```

Ugh. Seems to be some issue with encoding.

**Comment by Kagami** [comment]
@kripken nailed it down to:

```
$ LC_ALL=C python2 /home/kagami/code/tmp/emsdk/emscripten/incoming/emcc.py --help 2>&1 | /bin/grep -E ': supported targets:.* elf'
emcc: supported targets: llvm bitcode, javascript, NOT elf
$ LC_ALL=C python3 /home/kagami/code/tmp/emsdk/emscripten/incoming/emcc.py --help 2>&1 | /bin/grep -E ': supported targets:.* elf'
<nothing>
```

Can only be reproduced with python3 and C locale.
