### ISSUE TITLE
WebIDL binder: Use [Const] on strings, changing them from char* to const char*

### ISSUE THREAD

**Issue by mochamo** [kripken/emscripten#6186]
webidl_binder script does not pass thru the entire "const char*" and drops the "const" in the resulting translation

seen in 1.37.33 EM tools (using Python 2.7.10 on mac) generating IDL glue file in which resulting EMSCRIPTEN_KEEPALIVE signature resulted in char* being used without the const

results in emcc compiler error: cannot initialize return object of type 'char *' with an rvalue of type 'const char *'

this can be worked around by manually correcting in the resulting glue.cpp

python ../../../src/emsdk/emscripten/1.37.33/tools/webidl_binder.py header.idl header_glue

header.idl is using "DOMString" corresponding to "const char*" in object header.

**Comment by kripken** [comment]
Does adding [Const](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#const) help? (It might not if strings are special cased.)

**Comment by mochamo** [comment]
No, I am not seeing [Const] DOMString resulting in const char* in the glue file, it is still resulting in char*.

**Comment by kripken** [comment]
Ok, thanks, then that sounds like what we should fix then, strings should obey the `[Const]` attribute.

**Comment by miguelsaldivar** [comment]
I'll fix this issue. :smile:

**Comment by miguelsaldivar** [comment]
I think we can close this issue now :+1:

**Comment by kripken** [comment]
Yes, thanks!
