### ISSUE TITLE
Standalone mode mistake

### ISSUE THREAD

**Issue by PawelekS** [kripken/emscripten#6196]
I used that command:
`emcc source.cpp -Os -s WASM=1` ([command from that page](https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone#let-the-optimizer-remove-the-runtime))

On the output i got `a.out.js` and `a.out.wasm` — all is good
Finally, i wanted see `wat` format of my new .wasm file. I saw bad things:
```
(module
  (type $t0 (func (param i32 i32) (result i32)))
  (import "env" "memory" (memory $env.memory 256 256))
  (import "env" "table" (table $env.table 0 0 anyfunc))
  (func $__Z3addii (export "__Z3addii") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    (i32.add
      (get_local $p1)
      (get_local $p0))))
```
Why my function is named **__Z3addii**? That's error of emcc?

---

Additionally:
![image](https://user-images.githubusercontent.com/28712303/35827070-fe00a46c-0aba-11e8-8114-8168bc31604a.png)
![image](https://user-images.githubusercontent.com/28712303/35827115-1d223a40-0abb-11e8-9957-48d500553ebb.png)

**Comment by kripken** [comment]
C++ name mangling adds the`_Z3` and `ii`. You can use `extern "C"` to avoid those (or put the code in a c file instead of cpp, and build with emcc and not em++).

**Comment by kripken** [comment]
I edited the wiki page to mention `source.c` instead of `source.cpp`, thanks, this could be confusing otherwise.

**Comment by PawelekS** [comment]
hah, i did that minute ago.
I wanted write that now ;p

Thank You so mutch

---

Full code for future embarrassed people:
```cpp
#include <emscripten/emscripten.h>

extern "C" {
  EMSCRIPTEN_KEEPALIVE
  int add(int x, int y) { return x + y; }
}
```
Command: `emcc source.cpp -s WASM=1 -Os -o source.js`

**Comment by kripken** [comment]
Great, glad it works now.
