### ISSUE TITLE
FPS degradation over time

### ISSUE THREAD

**Issue by dondido** [kripken/emscripten#6212]
Hey, I'm sorry if I am posting this in the wrong place, but I have come across an issue where FPS is stable at 60fps for about 10-15 seconds but then just drops down to 3-4fps in couple of minutes. I'm not sure if this is just an issue with the `emscripten_set_main_loop` function or something else. Here is a simplified code example of how to replicate the performance drop over time:

```
#include <stdio.h>
#include <time.h>
#include "SDL2/SDL.h"
#include <emscripten.h>

int numFrames = 0;
int startTime = 0;

void printFps() {
  int elapsedMS = SDL_GetTicks() - startTime; // Time since start of loop
  ++numFrames;
  if (elapsedMS) {
    double elapsedSeconds = elapsedMS / 1000.0; // Convert to seconds
    double fps = numFrames / elapsedSeconds; // FPS is Frames / Seconds
    printf("%s %f\n", "FPS: ", fps);
  }
}

int main() {
  startTime = SDL_GetTicks();
  emscripten_set_main_loop(printFps, -1, 1);
  return 0;
}

```
Compile with:
`emcc main.c -s USE_SDL=2 -s WASM=1  -o dist/index.html -O2`

**Comment by kripken** [comment]
An interesting puzzle! That is indeed very strange behavior that looks like a bug, but after some investigation I think the surprising answer is that it's the HTML textarea filling up. That is, each printf increases its size, and we add around 60 lines per second, so it gradually becomes very large. The browser overhead for rendering that text then increases slowing down the page.

Why I think that's the case is that if you add this before the printf:
```
    EM_ASM({
      document.getElementById('output').value = "";
    });
```
then it will only have 1 item in the textarea at a time, and even after several minutes the frame rate is almost exactly 60.

**Comment by dondido** [comment]
Brilliant - you are a genius! Problem solved. Thank you very much indeed!
