### ISSUE TITLE
emcc compiles to asm.js but fails when WASM=1

### ISSUE THREAD

**Issue by NeekSandhu** [kripken/emscripten#6246]
When `emcc` called without `-s WASM=1` flag everything works normally and the output (`index.html`) literally works. But fails with non-zero exit code when it's set to emit WASM

```bash
sweetslush@ubuntu:~/.../wasm-oniguruma$ emcc deps/oniguruma/src/.libs/libonig.so src/onigasm.c -Ideps/oniguruma/src -s WASM=1  -o index.html

...

other weird output here that looks like:

(func $b5 (; 464 ;)
  (call $nullFunc_v
   (i32.const 5)
  )
 )
 (func $b6 (; 465 ;) (param $p0 i32)
  (call $nullFunc_vi
   (i32.const 6)
  )
 )
)
...


Fatal: error in validating output
Traceback (most recent call last):
  File "/home/sweetslush/Documents/emsdk/emscripten/1.37.33/emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "/home/sweetslush/Documents/emsdk/emscripten/1.37.33/tools/python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/sweetslush/Documents/emsdk/emscripten/1.37.33/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/sweetslush/Documents/emsdk/emscripten/1.37.33/emcc.py", line 1878, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/home/sweetslush/Documents/emsdk/emscripten/1.37.33/emcc.py", line 2346, in do_binaryen
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/sweetslush/Documents/emsdk/clang/e1.37.33_64bit/binaryen/bin/asm2wasm', 'index.temp.asm.js', '--total-memory=16777216', '--trap-mode=allow', '--mem-init=index.html.mem', '--mem-base=1024', '--wasm-only', '-o', 'index.wasm']' returned non-zero exit status 1
```

**Comment by NeekSandhu** [comment]
> src/onigasm.c

```c
/*
 * simple.c
 */
#include <stdio.h>
#include <string.h>
#include "oniguruma.h"
#include <emscripten/emscripten.h>

EMSCRIPTEN_KEEPALIVE
int test()
{
  int r;
  unsigned char *start, *range, *end;
  regex_t* reg;
  OnigErrorInfo einfo;
  OnigRegion *region;

  static UChar* pattern = (UChar* )"I \\d\\d ..(?<=ni)ce";
  static UChar* str     = (UChar* )"I 23 nmce";

  OnigEncoding use_encs[] = { ONIG_ENCODING_ASCII };
  onig_initialize(use_encs, sizeof(use_encs)/sizeof(use_encs[0]));

  r = onig_new(&reg, pattern, pattern + strlen((char* )pattern),
	ONIG_OPTION_DEFAULT, ONIG_ENCODING_ASCII, ONIG_SYNTAX_DEFAULT, &einfo);
  if (r != ONIG_NORMAL) {
    char s[ONIG_MAX_ERROR_MESSAGE_LEN];
    onig_error_code_to_str((UChar* )s, r, &einfo);
    fprintf(stderr, "ERROR: %s\n", s);
    return -1;
  }

  region = onig_region_new();

  end   = str + strlen((char* )str);
  start = str;
  range = end;
  r = onig_search(reg, str, end, start, range, region, ONIG_OPTION_NONE);
  if (r >= 0) {
    int i;

    fprintf(stderr, "match at %d\n", r);
    for (i = 0; i < region->num_regs; i++) {
      fprintf(stderr, "%d: (%d-%d)\n", i, region->beg[i], region->end[i]);
    }
  }
  else if (r == ONIG_MISMATCH) {
    fprintf(stderr, "search fail\n");
  }
  else { /* error */
    char s[ONIG_MAX_ERROR_MESSAGE_LEN];
    onig_error_code_to_str((UChar* )s, r);
    fprintf(stderr, "ERROR: %s\n", s);
    return -1;
  }

  onig_region_free(region, 1 /* 1:free self, 0:free contents only */);
  onig_free(reg);
  onig_end();
  return 0;
}
```

If not enough I can create a shared Dropbox folder, so you see what I see. Precisely. 

Thanks.

**Comment by NeekSandhu** [comment]
This script should repro the problem from start to finish

```bash
#!/bin/bash

# start at ./
mkdir onigwasm-repro
cd onigwasm-repro

git clone https://github.com/kkos/oniguruma

# Jump inside cloned repo and lift off
cd oniguruma
git checkout develop

autoreconf -vfi
emconfigure ./configure --enable-posix-api=no
emmake make

# back to ./onigwasm-repro
cd ..

# copy a bare minimum code which uses oniguruma lib
cp oniguruma/sample/simple.c test.c

# Linking as asm.js works but fails with `-s WASM=1`
emcc oniguruma/src/.libs/libonig.so test.c -Ioniguruma/src -s WASM=1 -o index.html
```

**Comment by kripken** [comment]
Looks like the important command is the last one, which receives `libonig.so` as an input, can you please provide just that file, so that reproducing this is as easy as possible?

**Comment by NeekSandhu** [comment]
zip below contains all the files mentioned in stacktrace:

`emcc.py`
`python_selector.py`
`asm2wasm`

https://www.dropbox.com/s/w6zzb7rqzbn2efg/emcc_stacktrace_files.zip

Hope it helps, please let me know what else I can provide. 

Also I'm using Ubuntu 17 64 bit in a VM and today I'm gonna try to build on macOS

**Comment by kripken** [comment]
That is not enough. To debug this problem, I need to be able to run that asm2wasm command and see the error on my local machine. That means I need that `libonig.so` file (nothing else is necessary).

As I said before, if you are not able to share the `.so` file for legal reasons or something else, the full error message may be enough (sometimes it is, sometimes it isn't).

**Comment by NeekSandhu** [comment]
Excuse my misunderstanding/ignorance. Linked below is `libonig.so` as I understand. I hope this works.

https://www.dropbox.com/s/s2jgnw0t6jwwsm0/libonig.so

I really appreciate what you do and sincerely wanna send you a beer. How can I? (PayPal? Amazon/Steam Gift Card?)

**Comment by kripken** [comment]
No problem, and thanks for the file.

No need for beer, just doing my job ;)

Ok, the problem here is some old C definition rules. I'll work on a better error message in emcc, but this should be fixed in the source code. I'm afraid I am not a C language spec expert, so I can't fully explain the problem, but if in onigurama.h you change
```
ONIG_EXTERN
int onig_error_code_to_str PV_((OnigUChar* s, int err_code, ...));
```
to
```
extern int
onig_error_code_to_str(UChar* s, int code, ...);
```
then it will work. What happens is that something with the PV_ macro etc. ends up using the very old C declaration style, and clang turns that into a varargs call for all the arguments, versus having 2 normal arguments and then varargs. Possibly the library is built with an older C version than the test file, for example, but it also does depend on the declaration style. Anyhow, the problem is that clang compiles the library with one declaration for the function, and the test file with another, and when it links them it adds casts to get around the type difference, but I'm pretty sure that's undefined behavior, and it ends up with something incorrect.

**Comment by kripken** [comment]
Another possible factor is that in the library itself, the header says
```
ONIG_EXTERN
int onig_error_code_to_str PV_((OnigUChar* s, int err_code, ...));
```
and the implementation says
```
#ifdef HAVE_STDARG_PROTOTYPES
onig_error_code_to_str(UChar* s, int code, ...)
#else
onig_error_code_to_str(s, code, va_alist)
```
Those don't quite match in multiple ways (one has an ifdef; one has OnigUChar and the other just UChar, param names differ), which is probably best to harmonize.

**Comment by NeekSandhu** [comment]
Thank you so much for the help! 

I'm gonna notify the oniguruma author and let's see what can be done.

🍻 | 🙂
