### ISSUE TITLE
Question regarding DYNAMIC_BASE and STACKTOP stored in HEAP

### ISSUE THREAD

**Issue by Kagami** [kripken/emscripten#6247]
Hi. I have my own runtime for WebAssembly module compiled with Emscripten with my simple `sbrk` implementation. Everything seems to be working, though I noticed that Emscripten's JS runtime puts some values to the specific places in memory:

```
HEAP32[0] = 1668509029;
…
HEAP16[1] = 25459;
…
HEAP32[DYNAMICTOP_PTR >> 2] = DYNAMIC_BASE;
…
HEAP32[1024 >> 2] = STACKTOP;
```

So my question is: do I have to provide these values too? I mean, do some generated C/LLVM low-level code depend on presense of such values at specific regions in memory or it's purely `library.js` specific?

Thanks.

**Comment by tbfleming** [comment]
This may be off, so take it with a grain of salt. I noticed when using the wasm backend that the stack pointer at 1024 is the only location that matters to the wasm side. A lot of the [DYNAMIC_PTR] stuff is js library code reserving memory; if the js functions aren't called then the memory isn't needed. This might be different with the s2wasm backend.

**Comment by tbfleming** [comment]
oops. corrected my typo.

**Comment by Kagami** [comment]
Thank you for response. I haven't noticed issues with _not_ providing the `STACKTOP` though (I'm using wasm backend too). Maybe because my program is rather simple…

**Comment by kripken** [comment]
Those constants should all be part of the overall runtime (so library.js and related files). For example, DYNAMICTOP_PTR is set up in JS, depending on what else is in memory, and then the wasm module uses that for sbrk. So if you have your own sbrk, you should not need that one.

**Comment by Kagami** [comment]
Thanks. I just don't fully understand why these variables are stored in the HEAP if they're used only on JS side. Why not simple JS variables?

**Comment by kripken** [comment]
They need to be used both in JS and in wasm. We could import a number into wasm, but wasm doesn't have exported mutable globals yet. So to have a mutable value easily readable from both JS and wasm, we use a location in memory.

**Comment by Kagami** [comment]
Could you please explain how they're used in wasm? Or give a hint where to find that in sources.

**Comment by kripken** [comment]
sbrk() uses it in asm.js and in wasm (not yet in the wasm backend, though, I believe, we leave asm.js library functions on the outside). See https://github.com/kripken/emscripten/blob/incoming/src/library.js#L477 But really, all that's going on is that we have a pointer to a location in memory, and we have that pointer both in JS and in wasm. So both can read and write to there, and the other sees the current value.

**Comment by Kagami** [comment]
>not yet in the wasm backend, though, I believe, we leave asm.js library functions on the outside

Ah, I see now. Thanks.
