### ISSUE TITLE
[Enhancement] Wrap JS glue code in IIFE

### ISSUE THREAD

**Issue by NeekSandhu** [kripken/emscripten#6250]
ATM I see that `emcc`'s generated glue code exposes a global called `Module`. I believe it'd so much better if that entire file was wrapped in simple IIFE like so:

```javascript
(function (global, factory) {
    // NodeJS, Webpack (CommonJS)
    typeof exports === 'object' && typeof module !== 'undefined' ?
        module.exports = factory() :
        // RequireJS (AMD)
	typeof define === 'function' && define.amd ?
            define(factory) :
            // Default global object
            (global.Module = factory());
}(this, function () {

    // ...

    return Module;
});
```

That way when webpack is part of toolchain, everything stays in place and organized.

**Comment by curiousdannii** [comment]
Use the MODULARIZE option.

**Comment by NeekSandhu** [comment]
My bad 😳, I was expecting it to behave that way by default. But this also works.

**Comment by kripken** [comment]
That's a good point, it does seem like today MODULARIZE would be a nicer default. The reason it isn't is historical: JS VMs used to run code more slowly when it was in a function scope. That's improved a lot since then, and also it's not relevant for wasm anyhow. However, changing this default would be a large change, so we'd need to do it carefully, if we decide to.

**Comment by NeekSandhu** [comment]
Aha..

Also I don't wanna open another  issue, but I saw an issue yesterday talking about ES compatibility. What do you think of this:

> libpng.js (emcc emit)
```diff
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Module;
+  module.exports.default = Module;
} else if (typeof define === 'function' && define['amd']) {
  define([], function() { return Module; });
} else if (typeof exports === 'object')
  exports["Module"] = Module;
```

> app.js
```diff
const MyModule = require('./libpng')
+ import MyModule from './libpng'
```
^^^ both methods work

**Comment by kripken** [comment]
I don't know enough about ES modules myself. Perhaps open a PR or an issue with that for wider discussion?

**Comment by curiousdannii** [comment]
I don't think you should need to specifically set `.default`. Are you using native loading or a bundler?

**Comment by NeekSandhu** [comment]
> I don't think you should need to specifically set `.default`

It's because `import MyModule from './someModule'` expects a `default` property on exports object

> Perhaps open a PR or an issue with that for wider discussion?

I wish I was familiar enough with `emscripten`'s codebase and negative implications of this change, something I'm not confident enough myself : |

**Comment by curiousdannii** [comment]
> It's because import MyModule from './someModule' expects a default property on exports object

That's not true for Node, hence why I was asking if you were using a bundler.

**Comment by kwhitley** [comment]
Another vote for this... webpack simply doesn't play nice with the current structure.  As that's probably the most common client bundler for real-life projects (where we import/export at will), this is kind of a huge deal!
