### ISSUE TITLE
__declspec(selectany) is missing in Clang v5.0.0

### ISSUE THREAD

**Issue by am11** [kripken/emscripten#6251]
I am running into an issue building .NET CoreRT project with latest emscripten: https://github.com/dotnet/corert/issues/5388.

This bug emerged in Clang 5.0.0 and was fixed in Clang 5.0.1: https://bugs.llvm.org/show_bug.cgi?id=35080.

Please update Clang to v5.0.1, if it is feasible.

Related to this, LLVM v6.0 is scheduled to be released on 21<sup>st</sup> Feb, 2018.

Platform: Windows 10 x64

```cmd
C:\>emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.33
clang version 5.0.0  (emscripten 1.37.33 : 1.37.33)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\emsdk-portable-64bit\clang\e1.37.33_64bit
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by kripken** [comment]
Not sure when the next LLVM merge will be, it depends on finding someone interested to do the work. However, the patch for that fix could be backported to here pretty easily, if this is urgent?

**Comment by kripken** [comment]
Not sure what the status of that 5.0 PR is, I asked there.

I opened https://github.com/kripken/emscripten-fastcomp-clang/pull/22 for cherry-picking that commit.

**Comment by kripken** [comment]
That PR was merged, so this should now be fixed on incoming. For the emsdk, next time we tag a version this will be picked up.

**Comment by kripken** [comment]
We tagged a version since then, so I think we can close this.

**Comment by am11** [comment]
Sorry I was busy with other projects and couldn't get a chance to try out newer bits.  Will do so soon.
Thanks a lot @kripken! 🎉
