### ISSUE TITLE
Feat: Add command line argument `-dumpversion`

### ISSUE THREAD

**Issue by twwwt** [kripken/emscripten#6258]
Gcc as well as Clang support the command line option `-dumpversion` that only prints the version, as opposed to `--version`. Seems that emcc does not yet support that. If I'm not missing something, would it be possible to add this argument?

Thanks

**Comment by kripken** [comment]
Yes it should be pretty easy to add this. I'll add the tags for that, hopefully someone will want to do it.

**Comment by twwwt** [comment]
@kripken Could you give me a pointer where this would need to be implemented. If I find some time I can try.

**Comment by kripken** [comment]
Sure, this would go in `emcc.py`. You can search for `--version` in that file, it would probably go some place close to that. And a test for it would go in `tests/test_other.py`, also there you can search for `--version`, should be a test for that already which it could go alongside.

**Comment by twwwt** [comment]
Closing this issue as it has been implemented and merged into incoming.
