### ISSUE TITLE
EMSCRIPTEN_ALWAYS_INLINE

### ISSUE THREAD

**Issue by Sirozha1337** [kripken/emscripten#6261]
Hi,

I'm trying to build another project, which uses emscripten([pocketsphinx.js](https://github.com/syl22-00/pocketsphinx.js)). At first it said 'Including <emscripten/val.h> requires building with -std=c++11 or newer!', but I already have '-std=c++17', so I just replaced "__cplusplus < 201103L" with "1 < 1" to let my compiler do its work. And now I have around 100 errors in val.h. I tried passing different values to '-std', but they don't seem to have any effect at all. 

I believe all those errors are all connected to this line **EMSCRIPTEN_ALWAYS_INLINE** as every line, that has this, is marked as an error in Visual Studio, even though the error message says something about undefined variables or missing semi-colons. 

OS: Windows 10 x64
Visual Studio 2017 Community Edition
Cmake: 3.11.0-rc1
Emcsripten: 1.37.34
Clang version: 5.0.0

**Comment by Sirozha1337** [comment]
Removing all **EMSCRIPTEN_ALWAYS_INLINE** and **\_\_attribute\_\_** lines fixed those errors, but now there's an error on the linking stage. The Visual Studio produces a warning: 
> LNK4044 unrecognized option /-default-obj-ext .obj; ignored

And then there's an error
> LNK1104 cannot open file '.obj'

**Comment by froydnj** [comment]
Why are you trying to use emscripten, but compile headers for emscripten with Visual Studio?  Are you doing it for development convenience?  You need to be compiling with `em++.py` in the emscripten distribution or somesuch for things to work correctly.
