### ISSUE TITLE
unresolved symbol: glPopAttrib and glPushAttrib

### ISSUE THREAD

**Issue by rsoeldner** [kripken/emscripten#6278]
similar to https://github.com/kripken/emscripten/issues/2257
Even when building with `-s LEGACY_GL_EMULATION=1` I receive:

```
warning: unresolved symbol: glPopAttrib
warning: unresolved symbol: glPushAttrib
```

shouldn't this work with emulation ?

**Comment by kripken** [comment]
Emscripten's GL emulation is fairly limited so far as the amount of deprecated and legacy GL features is immense. I'm not aware of anyone actively working to improve it, but that would be welcome of course.

**Comment by rsoeldner** [comment]
thank you, I will close this.

**Comment by podsvirov** [comment]
Any news there?
