### ISSUE TITLE
Memory access out of bounds when using big numbers matrix multiplication

### ISSUE THREAD

**Issue by Mcilie** [kripken/emscripten#6292]
In my program, I make AxA multi-dimensional arrays. 
If its 10x10 it works.
100x100 works.
1000x1000 works.
However, If I use 10000 + it gives me an error : 
`index.js:1 exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds`
Note: I am multiplying matrices. 
Is there any way to allocate more memory or do something to fix this problem? thanks :D

**Comment by tbfleming** [comment]
You're trying to allocate ```4*10000*10000``` bytes (400 MB) off the stack, which defaults to 5 MB. The ```TOTAL_STACK``` option controls this.

**Comment by froydnj** [comment]
@kripken, could you please close this?  The proposed solution sounds reasonable, and since there was no example code provided (?), I guess we can assume the proposed solution fixes things?
