### ISSUE TITLE
Warning: Unresolved symbol

### ISSUE THREAD

**Issue by dudiko** [kripken/emscripten#6304]
Hi, 
I have noticed many similar issues here but none of them was solved so I'm trying my luck.

Anyway, I have a really simple case:
aes.c, aes.h (module that implements some calculations related to aes encryption)
and tests.cpp which implements a main function that calls two functions from aes module.

Of course, with gcc everything work just perfect but when I'm trying to do so with emscripten I'm getting the "Unresolved symbol" issue:

```
emscripten@dudi-Latitude-E7450:/ScapiLite$ emcc aes.c -o aes.bc
emscripten@dudi-Latitude-E7450:/ScapiLite$ emcc tests.cpp -o tests.bc -I.
emscripten@dudi-Latitude-E7450:/ScapiLite$ emcc aes.bc tests.bc -o 1.js -I.
warning: unresolved symbol: _Z12AES_init_ctxP7AES_ctxPKh
warning: unresolved symbol: _Z21AES_CTR_xcrypt_bufferP7AES_ctxPhj
```

I ran llvm-nm to troubleshoot the problem and that's what I have got:
```
emscripten@dudi-Latitude-E7450:/ScapiLite$ llvm-nm aes.bc
-------- T AES_CBC_decrypt_buffer
-------- T AES_CBC_encrypt_buffer
-------- T AES_CTR_xcrypt_buffer
-------- T AES_ECB_decrypt
-------- T AES_ECB_encrypt
-------- T AES_ctx_set_iv
-------- T AES_init_ctx
-------- T AES_init_ctx_iv
-------- t AddRoundKey
-------- t Cipher
-------- t InvCipher
-------- t InvMixColumns
-------- t InvShiftRows
-------- t InvSubBytes
-------- t KeyExpansion
-------- t MixColumns
-------- d Rcon
-------- t ShiftRows
-------- t SubBytes
-------- t XorWithIv
-------- d rsbox
-------- d sbox
-------- t xtime
emscripten@dudi-Latitude-E7450:/ScapiLite$ llvm-nm tests.bc
         U _Z12AES_init_ctxP7AES_ctxPKh
         U _Z21AES_CTR_xcrypt_bufferP7AES_ctxPhj
         U _ZNKSt3__221__basic_string_commonILb1EE20__throw_length_errorEv
         U _ZNKSt3__26locale9use_facetERNS0_2idE
         U _ZNKSt3__28ios_base6getlocEv
         U _ZNSt11logic_errorC2EPKc
         U _ZNSt12length_errorD1Ev
-------- W _ZNSt3__211char_traitsIcE11eq_int_typeEii
-------- W _ZNSt3__211char_traitsIcE11to_int_typeEc
-------- W _ZNSt3__211char_traitsIcE3eofEv
-------- W _ZNSt3__211char_traitsIcE6assignEPcjc
-------- W _ZNSt3__211char_traitsIcE6assignERcRKc
-------- W _ZNSt3__211char_traitsIcE6lengthEPKc
         U _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev
         U _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE3putEc
         U _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE5flushEv
         U _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_
         U _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev
         U _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEi
-------- W _ZNSt3__216__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_
-------- W _ZNSt3__224__put_character_sequenceIcNS_11char_traitsIcEEEERNS_13basic_ostreamIT_T0_EES7_PKS4_j
         U _ZNSt3__24cerrE
         U _ZNSt3__24coutE
-------- W _ZNSt3__24endlIcNS_11char_traitsIcEEEERNS_13basic_ostreamIT_T0_EES7_
         U _ZNSt3__25ctypeIcE2idE
         U _ZNSt3__26localeD1Ev
         U _ZNSt3__28ios_base33__set_badbit_and_consider_rethrowEv
         U _ZNSt3__28ios_base5clearEj
-------- W _ZNSt3__2lsINS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc
         U _ZSt9terminatev
         U _ZTISt12length_error
         U _ZTVSt12length_error
         U _Znaj
         U _Znwj
-------- W __clang_call_terminate
         U __cxa_allocate_exception
         U __cxa_begin_catch
         U __cxa_call_unexpected
         U __cxa_end_catch
         U __cxa_free_exception
         U __cxa_throw
         U __gxx_personality_v0
-------- T main
         U open
         U read
         U strlen
```

And it looks very legit that the linking is not working because tests.bc expects to link with **_Z12AES_init_ctxP7AES_ctxPKh** and **_Z21AES_CTR_xcrypt_bufferP7AES_ctxPhj** while aes.bc exports **AES_init_ct**x and **AES_CTR_xcrypt_buffer** (different symbols).

So if I'm must guessing, the problem is here. But I didn't success to disable the auto generated symbol name when I'm compiling tests.cpp (why does it add these strange prefixes(_Z...) and suffixes(P...)?)

Any help?
Thanks

**Comment by eclecticdave** [comment]
Hi @dudiko.

When you compile a program in C++ it 'mangles' the symbol names - adding the extra prefix and suffix characters.  This is done to allow for the fact that in C++ you can define multiple functions with the same name and different parameters, but linkers typically don't support that, so mangling is used to make the function names unique.

Here you're linking in ordinary C files which do not have mangled symbols with a C++ test file which is assuming they will be mangled.  To resolve this you need to tell the compiler that the symbols in aes.h will not be mangled.  Typically you do this by wrapping the #include in an extern "C" block like this...

    extern "C" {
    #include <aes.h>
    }

I think the reason GCC doesn't do the same may be because it expects you to use 'g++' explicitly to compile C++ files, whereas emcc/clang switches languages automatically based on the file extension.

**Comment by dudiko** [comment]
@eclecticdave, thank you very much! Problem was solved.

**Comment by dudiko** [comment]
Hi,
I reopened this thread because I have another similar issue.
I'm trying to compile a very simple program that uses NTL library which I compiled via emscripten:
`emscripten@dudi-Latitude-E7450:~/opt/src/ScapiLite$ emcc tests_ntl.cpp ${HOME}/opt/lib/libntl.a -o tests_ntl.js -I../../include
warning: unresolved symbol: _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
warning: unresolved symbol: _Z10_ntl_gfreeP17_ntl_gbigint_body
warning: unresolved symbol: _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
warning: unresolved symbol: _Z11_ntl_gintozlPP17_ntl_gbigint_body
warning: unresolved symbol: _Z9_ntl_gmulP17_ntl_gbigint_bodyS0_PS0_
warning: unresolved symbol: _ZN3NTLlsERNSt3__213basic_ostreamIcNS0_11char_traitsIcEEEERKNS_2ZZE
`

But as you can see, I'm receiving 'Unresolved issue'.
I ran llvm-nm again to troubleshoot the problem and that's what I have got:
`emscripten@dudi-Latitude-E7450:~/opt/src/ScapiLite$ llvm-nm tests_ntl.bc
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z11_ntl_gintozlPP17_ntl_gbigint_body
         U _Z9_ntl_gmulP17_ntl_gbigint_bodyS0_PS0_
-------- W _Z9_ntl_swapI17_ntl_gbigint_bodyEvRPT_S3_
-------- W _ZN3NTL10WrappedPtrI17_ntl_gbigint_bodyNS_2ZZ7DeleterEE4swapERS4_
-------- W _ZN3NTL10WrappedPtrI17_ntl_gbigint_bodyNS_2ZZ7DeleterEEC2Ev
-------- W _ZN3NTL10WrappedPtrI17_ntl_gbigint_bodyNS_2ZZ7DeleterEED2Ev
-------- W _ZN3NTL10WrappedPtrI17_ntl_gbigint_bodyNS_2ZZ7DeleterEEadEv
-------- W _ZN3NTL2ZZ7Deleter5applyEP17_ntl_gbigint_body
-------- W _ZN3NTL2ZZC2ERS0_RKNS_17INIT_TRANS_STRUCTE
-------- W _ZN3NTL2ZZC2Ev
-------- W _ZN3NTL2ZZD2Ev
-------- W _ZN3NTL2ZZaSERKS0_
-------- W _ZN3NTL2ZZaSEl
-------- W _ZN3NTL3addERNS_2ZZERKS0_l
-------- W _ZN3NTL3mulERNS_2ZZERKS0_S3_
-------- d _ZN3NTLL10INIT_TRANSE
         U _ZN3NTLlsERNSt3__213basic_ostreamIcNS0_11char_traitsIcEEEERKNS_2ZZE
-------- W _ZN3NTLmlERKNS_2ZZES2_
-------- W _ZN3NTLplERKNS_2ZZEl
-------- W _ZNK3NTL10WrappedPtrI17_ntl_gbigint_bodyNS_2ZZ7DeleterEEcvRKPS1_Ev
         U _ZNKSt3__221__basic_string_commonILb1EE20__throw_length_errorEv
         U _ZNKSt3__26locale9use_facetERNS0_2idE
         U _ZNKSt3__28ios_base6getlocEv
         U _ZNSt11logic_errorC2EPKc
         U _ZNSt12length_errorD1Ev
-------- W _ZNSt3__211char_traitsIcE11eq_int_typeEii
-------- W _ZNSt3__211char_traitsIcE11to_int_typeEc
-------- W _ZNSt3__211char_traitsIcE3eofEv
-------- W _ZNSt3__211char_traitsIcE6assignEPcjc
-------- W _ZNSt3__211char_traitsIcE6assignERcRKc
-------- W _ZNSt3__211char_traitsIcE6lengthEPKc
         U _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev
         U _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_
         U _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev
-------- W _ZNSt3__216__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_
-------- W _ZNSt3__224__put_character_sequenceIcNS_11char_traitsIcEEEERNS_13basic_ostreamIT_T0_EES7_PKS4_j
         U _ZNSt3__24coutE
         U _ZNSt3__25ctypeIcE2idE
         U _ZNSt3__26localeD1Ev
         U _ZNSt3__28ios_base33__set_badbit_and_consider_rethrowEv
         U _ZNSt3__28ios_base5clearEj
-------- W _ZNSt3__2lsINS_11char_traitsIcEEEERNS_13basic_ostreamIcT_EES6_PKc
         U _ZSt9terminatev
         U _ZTISt12length_error
         U _ZTVSt12length_error
         U _Znwj
-------- W __clang_call_terminate
         U __cxa_allocate_exception
         U __cxa_begin_catch
         U __cxa_call_unexpected
         U __cxa_end_catch
         U __cxa_free_exception
         U __cxa_throw
         U __gxx_personality_v0
-------- T main
         U strlen

emscripten@dudi-Latitude-E7450:~/opt/src/ScapiLite$ llvm-nm ${HOME}/opt/lib/libntl.a | grep _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
00002690 T _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
         U _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
emscripten@dudi-Latitude-E7450:~/opt/src/ScapiLite$ llvm-nm ${HOME}/opt/lib/libntl.a | grep _Z10_ntl_gfreeP17_ntl_gbigint_body    
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
00002640 T _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
         U _Z10_ntl_gfreeP17_ntl_gbigint_body
emscripten@dudi-Latitude-E7450:~/opt/src/ScapiLite$ llvm-nm ${HOME}/opt/lib/libntl.a | grep _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
00004840 T _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
         U _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
`

So, as you can see the 'problematic' symbols are exist in both bytecodes but still the linker fails to find them.
Any idea?
Dudi
