### ISSUE TITLE
option --post-js and MODULARIZE doesn't cat post the module function

### ISSUE THREAD

**Issue by flatmax** [kripken/emscripten#6311]
When using -s MODULARIZE=1 (with EXPORT_NAME) --post-js doesn't cat the js file to the end of the WASM.js script, it cats the --post-js file to the end of the EXPORT_NAME function.

A working example of this is available here like so :
```
git clone git@github.com:madChopsCoderAu/WASMAudio.git
git checkout fb1f2e965496c774491745b36d86e21b0e09f3f2
./tools/autotools.sh
emconfigure ./configure --prefix=$EMSCRIPTEN/system 
emmake make

```
You can then inspect the libwasmaudio.js file for the following lines (which are inside the libwasmaudio module function) :
```
console.log('in pre.js of WASM js script')
registerProcessor('audio-processor', AudioProcessor);

```

**Comment by kripken** [comment]
I'm not sure what you mean by "instantiate a module when it is modularized", but maybe `MODULARIZE_INSTANCE` is what you're looking for? (see details in src/settings.js)

**Comment by flatmax** [comment]
Yes- I think it may be what I am after - it puts the "()" at the end of the function definition :+1:  var libwasmaudio = function(libwasmaudio) {
...
}();

Where : -s MODULARIZE_INSTANCE=1 -s "MODULARIZE=1" -s EXPORT_NAME="'libwasmaudio'"

If I am not mistaken ?

**Comment by kripken** [comment]
Yeah, exactly, it should create an instance by calling that function, for you.
