### ISSUE TITLE
win32api module missing in packaged python

### ISSUE THREAD

**Issue by compudemon** [kripken/emscripten#6318]
C:\emscripten>emsdk activate latest
Writing .emscripten configuration file to user home directory C:\Users\Owner/
The Emscripten configuration file C:\Users\Owner\.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT='C:/emscripten/clang/e1.37.35_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='C:/emscripten/clang/e1.37.35_64bit/optimizer.exe'
BINARYEN_ROOT='C:/emscripten/clang/e1.37.35_64bit/binaryen'
NODE_JS='C:/emscripten/node/8.9.1_64bit/bin/node.exe'
PYTHON='C:/emscripten/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe'
JAVA='C:/emscripten/java/8.152_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='C:/emscripten/emscripten/1.37.35'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/owner/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Failed to read environment variable PATH:
No module named win32api
Traceback (most recent call last):
  File "C:\emscripten\\emsdk", line 2337, in <module>
    sys.exit(main())
  File "C:\emscripten\\emsdk", line 2273, in main
    tools_to_activate = set_active_tools(tools_to_activate, permanently_activate=arg_global)
  File "C:\emscripten\\emsdk", line 1814, in set_active_tools
    env_string = construct_env(tools_to_activate, False)
  File "C:\emscripten\\emsdk", line 1912, in construct_env
    newpath, added_path = adjusted_path(tools_to_activate)
  File "C:\emscripten\\emsdk", line 1875, in adjusted_path
    existing_path = win_get_environment_variable('PATH', system=True)
  File "C:\emscripten\\emsdk", line 222, in win_get_environment_variable
    win32api.RegCloseKey(folder)
UnboundLocalError: local variable 'win32api' referenced before assignment

C:\emscripten>

**Comment by compudemon** [comment]
I was able to install another python and check for win32api using pip, then run "python emsdk activate latest" avoiding the bat file but then the issue just comes back again because the path is changed the next time I run python its the broke version included with emscripten

**Comment by kripken** [comment]
Thanks for filing! Due to another issue with the bundled python (with github ssl, #6275), we are considering updating the docs to suggest people get python manually, see #6298. (That's not great, but until we figure out how to fix the bundled version, which I don't think anyone volunteered to work on yet, it seems best.) Do the updated instructions there work for you? ( http://kripken.github.io/emscripten-site/docs/getting_started/temp-downloads.html )

**Comment by compudemon** [comment]
I followed the updated instructions for getting the sdk and got this error, but so far as I can tell it works now

C:\emsdk>emsdk update
You seem to have bootstrapped Emscripten SDK by cloning from GitHub. In this case, use "git pull" instead of "emsdk update" to update emsdk. (Not doing that automatically in case you have local changes)
Alternatively, use "emsdk update-tags" to refresh the latest list of tags from the different Git repositories.
