### ISSUE TITLE
Incorrect function name when compiling cpp file to wasm

### ISSUE THREAD

**Issue by Humma4** [kripken/emscripten#6321]
Hi,

I couldn't find this reported anywhere, or an explanation in case I'm doing something wrong, so I thought I'd post it here.

I'm trying to compile/export the most basic standalone function, using the "emcc add.c -Os -s WASM=1" command. With this, I get good results, and am able to use the function "add" in JavaScript. I've found out that emscripten will add an underscore character "_" to the function name, but I guess that's just a convention.

What I find odd however is that if I try to run the same command with the same script, but have a cpp extension like so "emcc add.cpp -Os -s WASM=1", then the function "add" will no longer be added as "_add", but rather as "__Z3addii".

Am I missing something, or is this just a bug?

The source code is listed below:
```
#include <emscripten.h>

int EMSCRIPTEN_KEEPALIVE add(int x, int y) {
  return ((x + y) * 45);
}
```

**Comment by dtfinch** [comment]
C++ (in general, not specific to any implementation) mangles names to support overloading unless you surround it in an 'extern "C" { }' block.

**Comment by Humma4** [comment]
I appreciate the quick response. Thanks for the tip, it solved the issue. I actually read that on the Mozilla guide, but though it was meant the other way around, using C in C++ code, or something like that, so I though it wasn't relevant for my case.

Thanks again. I'll close the case.
