### ISSUE TITLE
'--llvm-lto 1 -Oz -g2' results in broken output

### ISSUE THREAD

**Issue by vvuk** [kripken/emscripten#6331]
Doing a "release" build with `--llvm-lto 1 -Oz -g2` (also with `-s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1` but I don't think those matter) results in output that includes this:

```
var asm = (/** @suppress {uselessCode} */ function(global,env,buffer) {
var asm = (function(global, env, buffer) {
```

This is obviously bogus and causes the result to not parse.

**Comment by kripken** [comment]
Confirmed with this:
```
$./emcc tests/hello_world.c -O2 -g2 -s ELIMINATE_DUPLICATE_FUNCTIONS=1
$js a.out.js
a.out.js:3175:0 SyntaxError: missing } after function body:
```
cc @achoudhury85 as this is related to duplicate function elimination.

**Comment by vvuk** [comment]
Ping -- any solutions or workarounds for this?

**Comment by kripken** [comment]
Fixed by that PR.
