### ISSUE TITLE
failed to build with -fshort-wchar

### ISSUE THREAD

**Issue by zhaijialong** [kripken/emscripten#6336]
hello_world.c:
```
#include <stdio.h>
#include <stddef.h>

int main() {
  printf("hello, world!\n");
  printf("sizeof(wchar_t) : %d\n", sizeof(wchar_t));
  return 0;
}
```

built it by:
```
emcc hello_world.c -o a.html -fshort-wchar
```

and it output the error:
```
error: linking module flags 'wchar_size': IDs have conflicting values
ERROR:root:Failed to run llvm optimizations:
```

What's wrong with it? I'm using emscripten 1.37.35. 
Thanks.

**Comment by aheejin** [comment]
This happens because the existing cached prebuilt library (in `~/.emscripten_cache`) was not built with the same flag, so the cached library asserts the size of `wchat_t` to be 4. This is not gonna work unless you build your own library with the same flag.

**Comment by dschuff** [comment]
If you really need this to work, you could link without the C stdlib, or hack embuilder.py to build the C stdlib (and all the other libs) with the -fshort-wchar as well.
