### ISSUE TITLE
Compiling NTL library using emscripten

### ISSUE THREAD

**Issue by dudiko** [kripken/emscripten#6338]
Hi,
I'm trying to compile NTL library using emscripten which is working with no special issues but I failed to link with the compiled library (receiving 'unresolved symbol' messages):
```
emscripten@dudi-Latitude-E7450:~/opt/src/ScapiLite$ emcc tests_ntl.cpp ${HOME}/opt/lib/libntl.a -o tests_ntl.js -I../../include
warning: unresolved symbol: _Z10_ntl_gcopyP17_ntl_gbigint_bodyPS0_
warning: unresolved symbol: _Z10_ntl_gfreeP17_ntl_gbigint_body
warning: unresolved symbol: _Z10_ntl_gsaddP17_ntl_gbigint_bodylPS0_
warning: unresolved symbol: _Z11_ntl_gintozlPP17_ntl_gbigint_body
warning: unresolved symbol: _Z9_ntl_gmulP17_ntl_gbigint_bodyS0_PS0_
warning: unresolved symbol: _ZN3NTLlsERNSt3__213basic_ostreamIcNS0_11char_traitsIcEEEERKNS_2ZZE
``` 

I ran `llvm-nm ${HOME}/opt/lib/libntl.a` and the reported symbols are within the library so it's strange. **but**, what I have discovered is that also `nm ${HOME}/opt/lib/libntl.a` works and I'm not getting `nm: xxx.o: File format not recognized` messages as happen for other libraries which I have already compiled using emscripten! which made me wonder maybe the NTL library I have compiled is **not an emscripten bytecode** but rather **a regular machine code** and that is why I can't link with it. 
What do you think? 

I compiled NTL library using emscripten by doing the following steps:
```
wget http://www.shoup.net/ntl/ntl-10.5.0.tar.gz
tar xf ntl-10.5.0.tar.gz
cd mpc-10.5.0
emconfigure ./configure DEF_PREFIX=${HOME}/opt NTL_GMP_LIP=off
Edit makefile:
   CXX=emcc
   WIZARD=off
   within setup 1-3 sections: use g++ compiler instead of emcc
make -j 6
make install
```

Any suggestions/tips will be very appreciated.
Thanks,
Dudi

**Comment by curiousdannii** [comment]
> within setup 1-3 sections: use g++ compiler instead of emcc

Does this mean that you've changed it from emcc to g++ or from g++ to emcc? If you've change it to g++ then it absolutely will not work with emscripten.

**Comment by dudiko** [comment]
@curiousdannii, I meant from emcc to g++. it's ok because it doesn't mean to compile NTL with g++ - if will look into NTL's makefile you will see that setups 1-4 responsible for generating some .h files and a bit more but not part of the library compilation.

Anyway, I solved my problem so I'm closing this issue but if anyone will ever want to compile GMP and NTL libraries using emscripten, here two great resources: 
1. https://stackoverflow.com/questions/41080815/compiling-gmp-mpfr-with-emscripten 
2. https://github.com/ftynse/iscc.js/wiki
