### ISSUE TITLE
invalid output constraint '=a' in asm

### ISSUE THREAD

**Issue by vadlis** [kripken/emscripten#6339]
test.cpp:
```
typedef unsigned long long uint64_t;

inline uint64_t rdtsc() {
	uint64_t a, d;
	__asm__ volatile ("rdtsc" : "=a" (a), "=d" (d));
	return (d << 32) | a;
}

int main() {
	uint64_t v = rdtsc();
	return 0;
}
```
command:
```
emcc test.cpp -s WASM=1 -o test.html
```
result:
```
test.cpp:5:30: error: invalid output constraint '=a' in asm
        __asm__ volatile ("rdtsc" : "=a" (a), "=d" (d));
```
environment:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.36
clang version 5.0.0 (https://github.com/kripken/emscripten-fastcomp-clang.git c8606950a97dea79eb578599bb13a48a1639661a) (https://github.com/kripken/emscripten-fastcomp.git 0d8129bb20f502b9ba26d54414f05120f5622b4b) (emscripten 1.37.36 : 1.37.36)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\innovation\emsdk\clang\fastcomp\build_incoming_vs2015_64\Release\bin
```
What I missed?
Thanks in advance

**Comment by kripken** [comment]
Native x86 assembly isn't supported in emscripten - only portable C and C++.

We should probably have a better error for inline asm like that, but I'm not sure how feasible that would be.

**Comment by vadlis** [comment]
@kripken Thanks for the answer. Can you tell a bit more:
- Is there native webassembly support in emscripten (i.e. can we write the same using webassembly instructions)?
- Or can you advice how to solve out such things?

**Comment by kripken** [comment]
WebAssembly can't do things like rdtsc (that reads the clock, I believe?) - it can only do pure computation.

To get the time, you can use `emscripten_get_now`, but it will not be as efficient as rdtsc - it calls out into JS to get the time. Or using that C++ API can work, that you mentioned.

**Comment by froydnj** [comment]
I guess we can just close this...or, if we're going to keep it open, retitle it so it's clear that we're trying to fix the poor inline asm messages.  I think trying to generate better inline asm messages is probably a losing battle, though.

**Comment by kripken** [comment]
Yeah, not sure it's practical to do better on those errors.
