### ISSUE TITLE
Document that WASM_BINARY_FILE is for internal use only

### ISSUE THREAD

**Issue by twwwt** [kripken/emscripten#6346]
What is the semantics of `WASM_BINARY_FILE` compiler parameter? According to my interpretation it allows defining the name of the additional WASM binary file when compiling with `-s WASM=1`. If that is correct, it doesn't seem to have an effect with latest version 1.37.36. For instance, adding `... -o foo.js -s WASM=1 -s SINGLE_FILE=0 -s WASM_BINARY_FILE="fooblah.wasm"` results in the files `foo.js` and `foo.wasm`, instead of `fooblah.wasm`. In addition, the generated JS file contains a variable declartion `var wasmBinaryFile = "foo.wasm";` in the body of the function `integrateWasmJs()`, which also appears not to be wrong.

The same behavior is observable for `WASM_TEXT_FILE` and `ASMJS_CODE_FILE`.

**Comment by kripken** [comment]
I think those are just for internal use, but looks like they aren't documented as such, which we should fix.

**Comment by kripken** [comment]
Fixed by that PR.
