### ISSUE TITLE
Further compilation issues with WASM=1

### ISSUE THREAD

**Issue by mdboom** [kripken/emscripten#6362]
Thanks for resolving #6309.  With that resolved, I updated my toolchain to try again.  However, I'm getting different behavior now when turning WASM=1 on.

First, I get this compiler error:

```
emcc -s EXPORT_NAME="'pyodide'" --bind -o build/pyodide.asm.html src/main.bc src/jsimport.bc src/jsproxy.bc src/js2python.bc src/pyimport.bc src/pyproxy.bc src/python2js.bc src/runpython.bc -O3 cpython/installs/python-3.6.4/lib/libpython3.6.a -s "BINARYEN_METHOD='native-wasm'" -s TOTAL_MEMORY=268435456 -s MAIN_MODULE=1 -s ASSERTIONS=2 -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s EXPORTED_FUNCTIONS='["_main"]' -s WASM=1 --memory-init-file 0 \
        --preload-file root/lib@/lib
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
emcc: warning: cannot represent a NaN literal '0x4370240' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   %. = select i1 %19, double 0xFFF8000000000000, double 0x7FF8000000000000 in _PyFloat_Unpack2() 
warning: unexpected return type i32 in call to '_PyTraceMalloc_Fini', should be void
emcc: warning: cannot represent a NaN literal '0x4370240' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   %. = select i1 %60, double 0xFFF8000000000000, double 0x7FF8000000000000 in _Py_parse_inf_or_nan() 
Traceback (most recent call last):
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emcc.py", line 2805, in <module>
    sys.exit(run())
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emcc.py", line 1632, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/tools/shared.py", line 2010, in emscripten
    call_emscripten(cmdline)
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emscripten.py", line 2365, in _main
    temp_files.run_and_clean(lambda: main(
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emscripten.py", line 2370, in <lambda>
    DEBUG=DEBUG,
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emscripten.py", line 2276, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emscripten.py", line 103, in emscript
    function_tables_and_exports(funcs, metadata, mem_init, glue, forwarded_data, settings, outfile, DEBUG))
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emscripten.py", line 292, in function_tables_and_exports
    asm_setup = create_asm_setup(debug_tables, function_table_data, metadata, settings)
  File "/home/mdboom/Work/builds/compiling/emsdk/emscripten/incoming/emscripten.py", line 1158, in create_asm_setup
    asm_setup += '\nvar debug_table_' + sig + ' = ' + json.dumps(debug_tables[sig]) + ';'
KeyError: u'd'
```

If I turn `ASSERTIONS` off (since this error seems related to assertions), it compiles, but then on load I get the message:

```
uncaught exception: BindingError: No dynCall invoker for signature: iii
```

Any ideas/suggestions on how to resolve this?

I have both EMULATED_FUNCTION_POINTERS and EMULATE_FUNCTION_POINTER_CASTS on, but unsetting them doesn't change the error.

**Comment by mdboom** [comment]
For reference, the project I'm building is here: iodide-project/pyodide

**Comment by kripken** [comment]
I don't remember the details of how that `debug_table` stuff works, but hopefully it's hitting the same bug you're seeing at runtime without assertions.

Can you attach the bitcode file so I can reproduce the bug locally? Probably we just need to handle the case of an indirect call existing without a function of that target present, or something like that.

**Comment by mdboom** [comment]
In trying to create a standalone build from .bc files to .wasm, I discovered that removing the errant `-O3` in the final link command gets me past this, and I can import the MAIN module without issue.

So, I'd consider this issue closed.  Sorry for the noise.  However, I've run into #6365 behind that.

**Comment by kripken** [comment]
`-O3` in the final link command is necessary, without the code won't be fully optimized. So let's reopen this, we really should fix it.

**Comment by kripken** [comment]
Can please you provide the bitcode, or otherwise full steps to reproduce this bug locally?

**Comment by mdboom** [comment]
I've posted a build with `-O3` in the *optimized* branch here: https://github.com/iodide-project/pyodide-demo/

It crashes with the message

```
uncaught exception: BindingError: No dynCall invoker for signature: iii
```

This is before any `dlopen` calls, so I don't think the side modules enter into play.

Here's the LDFLAGS:

```
	-O3 \
  --bind
  -s "BINARYEN_METHOD='native-wasm'" \
  -s TOTAL_MEMORY=268435456 \
  -s MAIN_MODULE=1 \
  -s EMULATED_FUNCTION_POINTERS=1 \
  -s EMULATE_FUNCTION_POINTER_CASTS=1 \
  -s EXPORTED_FUNCTIONS='["_main"]' \
  -s WASM=1 \
  --memory-init-file 0
```

The only difference between working and not working is the `-O3` flag.  I also tried other values for `-O`: `-O2` and `-Oz` have the same behavior as `-O3`.  `-O1` doesn't throw the exception, but also silently doesn't seem to run the `_main` function.

**Comment by kripken** [comment]
Hmm, that looks like an embind error?

Sadly embind is not currently maintained, no one with knowledge of the internals is active in the community :( So I'd recommend avoiding embind for your project. Would that be possible - what do you need it for?

**Comment by mdboom** [comment]
Interesting.  I currently use it to do the conversion between Python and Javascript objects.  Basically the code here: https://github.com/iodide-project/pyodide/tree/master/src

It's not a *ton* of code, so a rewrite isn't out of the question.  What's the recommended way to interact with Javascript objects from C currently?

**Comment by kripken** [comment]
There isn't something for the C++ => JS level, I'm afraid. For JS => C++, there is the WebIDL binder (wraps compiled C++ classes so they look like JS to JS code), and also [nbind](https://github.com/charto/nbind).

On the lower level, EM_ASM allows calling from C => JS, passing integers, floats, and pointers, and other stuff can be built on top of that. That's normally what I use.

Can you maybe summarize how you are using embind there? If it's not very complicated, maybe we can figure out that embind bug, or find a workaround. Another option is to reimplement a subset of embind in a simpler and more efficient way, which I've been thinking about for a while.

**Comment by mdboom** [comment]
I'm mainly using the `val` object that comes with embind to convert to/from C types.

Here's Python to JS:

https://github.com/iodide-project/pyodide/blob/master/src/python2js.cpp#L70

and JS to Python:

https://github.com/iodide-project/pyodide/blob/master/src/js2python.cpp#L11

The trickiest bit is creating a Javascript object that delegates to Python to call methods:

https://github.com/iodide-project/pyodide/blob/master/src/pyproxy.cpp

But it should be possible to rewrite that in Javascript with a bunch of C functions it calls under the hood.  I could probably get away with something that just worked like the wire protocol part of embind to set objects back and forth.

I'll play around with various options and the embind source code and get back to you here.

**Comment by mdboom** [comment]
As an experiment, I took all of the embind usage out and just mocked up its functionality.  While that resolves the initial import of the MAIN_MODULE, I ended up again with a problem of the missing `dynCall_XXX` (and `invoke_XXX`) symbols when I tried to load a SIDE_MODULE.  My hunch is that these `dynCall_XXX` and `invoke_XXX` symbols are getting eliminated by some optimization step, but they should be kept around when using dynamic modules.

So I spent some time trying to figure out where these symbols are getting eliminated, and doing the bare minimum to protect them.  My understanding is shaky, so everything below represents a hunch.  I share the diffs not because they are correct, but just to illustrate something that makes this work for me.

The `dynCall_XXX` functions are getting eliminated in the `wasm-metadce` step, I think because they are accessed through a dynamic lookup, i.e.:

```js
    return Module['dynCall_' + sig].call(null, ptr);
```

The full name of the method isn't known until runtime, so my hunch is this confuses the DCE.  `embind.js` does something like this, but so does `support.js`, so the problem doesn't seem to be limited to embind.

The quick hack to fix this was in binaryen:

```diff
diff --git a/src/tools/wasm-metadce.cpp b/src/tools/wasm-metadce.cpp
index 4f90ee61..dab21cb7 100644
--- a/src/tools/wasm-metadce.cpp
+++ b/src/tools/wasm-metadce.cpp
@@ -281,6 +281,9 @@ public:
     std::vector<Name> toRemove;
     for (auto& exp : wasm.exports) {
       auto name = exp->name;
+      if (name.startsWith("dynCall_")) {
+        continue;
+      }
       auto dceName = exportToDCENode[name];
       if (reached.find(dceName) == reached.end()) {
         toRemove.push_back(name);
```

The `invoke_XXX` methods aren't in wasm, just in the JS side, and were getting eliminated by the JS optimizer.  I fixed that by explicitly exporting them by adding them to the `Module` object in emscripten:

```diff
diff --git a/tools/shared.py b/tools/shared.py
index 511a7cfc7..fac329b03 100644
--- a/tools/shared.py
+++ b/tools/shared.py
@@ -2562,7 +2562,8 @@ class JS(object):
     if (typeof e !== 'number' && e !== 'longjmp') throw e;
     Module["setThrew"](1, 0);
   }
-}''' % ((' invoke_' + sig) if named else '', args, 'return ' if sig[0] != 'v' else '', sig, args)
+}
+Module["invoke_%s"] = invoke_%s''' % ((' invoke_' + sig) if named else '', args, 'return ' if sig[0] != 'v' else '', sig, args, sig, sig)
     return ret
 
   @staticmethod
```

Let me know if you think I'm on the right track, and I can formalize this in PRs.  At a minimum, I think these changes should probably be only in effect when using dynamic modules.

**Comment by mdboom** [comment]
Thanks.  I can confirm that #6444 resolves this issue in my specific case.

A related question: I see that the MAIN_MODULE I'm generating includes symbols for SDL, WebGL etc. which I'm not using and don't need.  I understand in the general case we can't predict if a SIDE_MODULE would need these, but is there any easy / standard way to remove those since I know I don't need them?

**Comment by mdboom** [comment]
Sorry, I spoke too soon.  #6444 doesn't quite fix it.  I'll add a note over there.

**Comment by kripken** [comment]
About SDL etc. they are linked in by default, and we don't have a way to prevent that recently. @juj wanted to eventually require "normal" `-lSDL` etc. flags, but I'm not aware of anyone working towards that now.

There is a `DEAD_FUNCTIONS` option which you can add `SDL` (or maybe you need `$SDL` since it's a special object), which should "kill" it.

**Comment by Keillion** [comment]
Hi, 
I have trouble using `EMSCRIPTEN_BINDINGS` with `MAIN_MODULE=1`.
A simple code modified from embind tutorial:
```
// mainModule.cpp
#include <emscripten/emscripten.h>
#include <emscripten/bind.h>
using namespace std;
using namespace emscripten;

EMSCRIPTEN_KEEPALIVE
float lerp(float a, float b, float t) {
    return (1 - t) * a + t * b;
}

EMSCRIPTEN_BINDINGS(my_module) {
    emscripten::function("lerp", &lerp);
}
```
```
// compile command
./em++ -O0 -s MAIN_MODULE=1 -s EXPORT_ALL=1 -s WASM=1 -s ABORTING_MALLOC=0 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=1 -s --bind -std=c++11 -o ~/mainModule.js ~/mainModule.cpp
```
Compile pass, but it reports `No dynCall invoker for signature: fifff` in browser. It might be the same problem as #6362. I use `1.38.45-upstream`. What is the correct way to not `dce` embind?

Thanks very much.

**Comment by scual** [comment]
@Keillion had similar issue and it seems it has to do with numerical values.
It appears that the binding translates numbers, from javascript to C++ as, `double`. So when the function is called in javascript, it's counterpart in C++ is not found, and therefore the `no dynCall` is raised.   
Try to see if by using `double` instead of `float` it works.
