### ISSUE TITLE
closure doesn't work with -Os and USE_GLFW=3

### ISSUE THREAD

**Issue by ILikeBigBoots** [kripken/emscripten#6363]
Hey there,

I can't seem to get the closure compiler to work, using the -s USE_GLFW3 and -Os(same with Oz, O2,..) flags. 
Without either of them, everything is fine. Am I missing something?

I'm using emscripten 1.37.36 and my OS is Linux Mint 18.2 Cinnamon 64-bit.

Using said flags together results in 2 errors and 41 warnings, which all seem to be related to GLFW.
Everything works fine if I don't use GLFW, or any of the other 2 flags. 

The errors are:
```
/tmp/tmpspMPXo.cl.js:2615: ERROR - variable eventButton is undeclared
        eventButton = GLFW.DOMToGLFWMouseButton(event);
        ^^^^^^^^^^^
/tmp/tmpspMPXo.cl.js:3064: ERROR - variable table is undeclared
        table = {
        ^^^^^
```

Some of the warnings:

```
/tmp/tmpspMPXo.cl.js:2377: WARNING - dangerous use of the global this object
        this.windowCloseFunc = null; // GLFWwindowclosefun
        ^^^^

/tmp/tmpspMPXo.cl.js:2378: WARNING - dangerous use of the global this object
        this.windowRefreshFunc = null; // GLFWwindowrefreshfun
        ^^^^

/tmp/tmpspMPXo.cl.js:2379: WARNING - dangerous use of the global this object
        this.windowFocusFunc = null; // GLFWwindowfocusfun
```

[Here is a gist with all errors/warnings, including the Traceback](https://gist.github.com/ILikeBigBoots/8e4650085f7aca6bb49834b5414a6739)

**Comment by kripken** [comment]
Is this the same as what was reported on the mailing list? If that was you in both places, please don't report a bug twice, once is enough, we'll see it in either place :)

Fix for this issue is in #6364 as I already mentioned on the mailing list.
