### ISSUE TITLE
Module._malloc is not a function

### ISSUE THREAD

**Issue by rhyst** [kripken/emscripten#6368]
Hello, 

I am attempting to get a demo project to run where I can pass arrays back and forth between c and js. The various guides I have found on the subject suggest adding directly to the c code's heap from js. I have tried to do this but get the error `Module._malloc is not a function`.

test.c:
```c++
#include <stdio.h>
#include <emscripten/emscripten.h>

EMSCRIPTEN_KEEPALIVE
float addNums (float *buffer, int bufSize) {
    float total = 0;

    for (int i=0; i<bufSize; i++) {
        total+= buffer[i];
    }

    return total;
}
```

I compile this with:

```
emcc -o public/test.html test.c -O3 -s WASM=1 --shell-file shell_minimal.html -s NO_EXIT_RUNTIME=1  -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall"]'
```

In shell_minimal.html (copied from the emsdk repo) I have defined the following function to be run when clicking a button. It is placed at the end of the script tag.

js:
```javascript
    document.querySelector('.mybutton').addEventListener('click', function () {
      const arrayDataToPass = [1, 2, 3, 4, 5]
      let buffer
      let error
      let result
      const typedArray = new Float64Array(arrayDataToPass.length)
      // Populate the array with the values
      for (let i = 0; i < arrayDataToPass.length; i++) {
        typedArray[i] = arrayDataToPass[i]
      }
      buffer = Module._malloc(typedArray.length * typedArray.BYTES_PER_ELEMENT)
      Module.HEAPF64.set(typedArray, buffer >> 2)
      result = Module.ccall("addNums", null, ["number", "number"], [buffer, arrayDataToPass.length])
    });
```
The error references this line:
```
buffer = Module._malloc(typedArray.length * typedArray.BYTES_PER_ELEMENT)
```

Any help would be much appreciated.

**Comment by kripken** [comment]
`malloc` is not exported by default, you need to explicitly export it. See https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-functions-in-my-c-c-source-code-vanish-when-i-compile-to-javascript-and-or-i-get-no-functions-to-process

(in the past our dead code elimination could not always remove core functions like malloc, so things may have happened to work without exporting it explicitly, but in recent versions dce has gotten a lot more powerful)

**Comment by rhyst** [comment]
Thanks for the quick response! You are right about needing to explicitly export. Compiling with the following works:
```
emcc -o public/test.html test.cpp -O3 -s WASM=1 --shell-file shell_minimal.html -s NO_EXIT_RUNTIME=1  -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall"]' -s "EXPORTED_FUNCTIONS=['_malloc']"
```

**Comment by kripken** [comment]
Great :)
