### ISSUE TITLE
SIDE_MODULE with WASM seems to have no static initializer

### ISSUE THREAD

**Issue by mdboom** [kripken/emscripten#6369]
Thanks for helping me resolve #6365.  Behind that, I found another issue using SIDE_MODULE with WASM.

It appears that SIDE_MODULEs don't have static initialization data, and I'm seeing zero'd data where I would expect static values to be.  (This is somewhat related to my PR #6355, but that was without WASM -- as far as I can tell that code path is irrelevant when WASM is turned on).

The resulting `.wasm` files for the `SIDE_MODULE` don't seem to contain any of the static strings I would expect.  Is there maybe just some flag I need to set to output the initialization data?

I have a minimal standalone here: https://github.com/mdboom/emscripten-side-module-no-static

**Comment by dschuff** [comment]
Possibly related: I discovered that https://github.com/kripken/emscripten/pull/5844 broke things so that static initializers are missing when using wasm+pthreads, so it might be the case that it broke side modules too. I'm working on a fix for pthreads, I can look at side modules after I get that in.

**Comment by kripken** [comment]
I can't reproduce this problem (using latest incoming - what version are you on? any local changes?), I see `Found static string` printed and I do see `Message` in the `.so` file properly.

This would surprise me if it were broken, as we have tests for it. Does `./tests-runner.py binaryen0.test_dlfcn* binaryen0.test_dylink*` pass for you locally?

**Comment by dschuff** [comment]
I built a side module with https://github.com/kripken/emscripten/pull/6370 applied and verified that it at least does have a data section (that was the intent of that PR).

**Comment by mdboom** [comment]
Sorry for wasting time, folks.  I think I had emscripten and binaryen out of sync (emscripten had been updated to a recent incoming and binaryen to an older master).  Updating both and rebuilding seems to have resolved the issue.  Closing.
