### ISSUE TITLE
strange initializer_list behaviour

### ISSUE THREAD

**Issue by pannous** [kripken/emscripten#6373]
The following little test program produces correct results when compiled with optimisation but produces strange results when compiled *without* optimisation:

```
#include <initializer_list>
extern "C" {
	void logi(int);
	int main(int argc, char**argv){
		for(int i : {1,2,3,4,5,6,7,8,9})
			logi(i);  		
	 	return 42;
	}
}
```

`emcc -g4 -O0 -std=c++1z -s WASM=1 -s SIDE_MODULE=1 -s -o test.wasm` 

prints
`1
2
3
4
0
9
7
8
9
`

My fault or genuine bug?

**Comment by kripken** [comment]
Looks like this is a side module and you wrote your own js to load and run it - there might be a bug there. Does this happen without SIDE_MODULE, using the normal js glue?

My guess would be that with optimizations, it unrolls that loop into 9 calls to `logi`. Without opts it reads from memory, and perhaps memory is not set up properly by the js (like maybe `memoryBase` is wrong).

**Comment by pannous** [comment]
genius remote bug detector: It was memoryBase indeed
