### ISSUE TITLE
Passing arguments to Closure Compiler

### ISSUE THREAD

**Issue by robfors** [kripken/emscripten#6385]
Can I pass arguments to *Closure Compiler* when I run emcc?
If I were to instead, run *Closure Compiler* separately after I am finished with emcc. What would I do with the `.mem` file? Can I run *Closure Compiler* on the .js file and leave the `.mem` file as is?

**Comment by kripken** [comment]
You can set the `EMCC_CLOSURE_ARGS` env var to add arguments.

Running closure yourself on the JS file is not recommended - it would modify the asm.js in ways that break validation and so make it slower.

**Comment by robfors** [comment]
Thanks, that's exactly what I was looking for.
I couldn't find `EMCC_CLOSURE_ARGS` anywhere in the docs, do you think it should be added to the bottom of https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html?

**Comment by kripken** [comment]
Good point, yeah, we should add docs for it, and that looks like the right place. Do you want to open a PR with that perhaps?

**Comment by robfors** [comment]
That sounds good
