### ISSUE TITLE
wasm.js/binaryen.js assume binaryen source directory

### ISSUE THREAD

**Issue by sbc100** [kripken/emscripten#6406]
These .js files currently live in bin/ directory of the binaryen source, but when installed they live in shared/binaryen.

I propose that we allow BINARYEN_ROOT to point to the install root, *or* the source root.  Unfortunately it can't point to the build root as these files never exist in the build root since they are copied directly from the source directory to the install directory.

**Comment by kripken** [comment]
Seems reasonable, we can detect if we are in the either of those two locations, and handle things for each.
