### ISSUE TITLE
Two different objects with the same pointer

### ISSUE THREAD

**Issue by Ekinoks** [kripken/emscripten#6410]
Hello !

When trying to port a C ++ application in javascript with Emscripten, I was confronted with unexpected behavior: two different objects with the same pointer.
Is this behavior normal? or that corresponds to a bug?

Here is a minimal example:
```
#include <iostream>

struct A {
	A() {
		std::cout << "constructor A : " << this << std::endl;
	}
};

struct B {
	B() {
		std::cout << "constructor B : " << this << std::endl;
	}
};

struct C {
	B b;
	A a;

	C() {
  		std::cout << "Constructor C : " << this << std::endl;
	}
};

int main(int argc, char const *argv[])
{
	C c;

	std::cout << "c = " << &c << std::endl;
	std::cout << "c.b = " << &(c.b) << std::endl;
	std::cout << "c.a = " << &(c.a) << std::endl;

	return 0;
}
```

For build:
`$ em++ bug.cpp --bind`

Result in a console when a charge a.out.js in a navigator:
```
constructor B : 0x6964
constructor A : 0x6965
Constructor C : 0x6964
c = 0x6964
c.b = 0x6964
c.a = 0x6965
```

As you can see object **c** and **b** have identical pointer. This is normal ?

**Comment by froydnj** [comment]
Yes, this is expected.  `b` is the first field of `C` and, in this case, is located at offset 0 inside an object of type `C`.  So the object and its first field would have identical pointers.

**Comment by Ekinoks** [comment]
Oh yes right! Sorry for this false bug :^/
