### ISSUE TITLE
Question: how do I make it give a beautified Javascript output with `-s WASM=1`?

### ISSUE THREAD

**Issue by wlzla000** [kripken/emscripten#6424]
With `-s WASM=1`, _Emscripten_ gives me a Javascript file that defines the module object, and a `.wasm` file. The Javascript code looks compressed (_uglified_). Are there any options for beautified one instead?

**Comment by kripken** [comment]
The debug level (`-g`, etc.), profliling (`-profiling`, etc.) options can control whether to minify names/whitespace/etc. See the [docs](file:///home/alon/Dev/emscripten/site/build/html/docs/tools_reference/emcc.html#emcc-closure).

**Comment by kripken** [comment]
(had a typo in the link; fixed)
