### ISSUE TITLE
Emscripten FS doesn't mount physical directories when running WASM in NW.js

### ISSUE THREAD

**Issue by gogins** [kripken/emscripten#6428]
This is in context of my port of the computer music system Csound to WebAssembly hosted at https://github.com/gogins/csound-extended.

The example code for mounting a directory in the JavaScript sandbox on the physical filesystem, documented by Emscripten for Node.js, does not work for NW.js even though I expected that it would.

This code:
```
FS.mkdir('/working');
FS.mount(NODEFS, { root: '/home/mkg' }, '/working');
```
asserts:
```
csound_extended.js:12924 Uncaught abort("Assertion failed: undefined") at Error
    at jsStackTrace (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/csound_extended.js:1378:13)
    at stackTrace (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/csound_extended.js:1395:12)
    at abort (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/csound_extended.js:12918:44)
    at assert (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/csound_extended.js:777:5)
    at Object.mount (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/csound_extended.js:3367:9)
    at Object.mount (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/csound_extended.js:4137:30)
    at onPlayClick (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/cmask_with_samples.html:22:12)
    at HTMLInputElement.onclick (chrome-extension://ongbfommcbfklnpgoalnfnliobnifhci/cmask_with_samples.html:47:76)
```
And the cause appears to be that in this code:
```
      },bufferFrom:function (arrayBuffer) {
        // Node.js < 4.5 compatibility: Buffer.from does not support ArrayBuffer
        // Buffer.from before 4.5 was just a method inherited from Uint8Array
        // Buffer.alloc has been added with Buffer.from together, so check it instead
        return Buffer.alloc ? Buffer.from(arrayBuffer) : new Buffer(arrayBuffer);
      },mount:function (mount) {
        assert(ENVIRONMENT_IS_NODE);
        return NODEFS.createNode(null, '/', NODEFS.getMode(mount.opts.root), 0);
      },createNode:function (parent, name, mode, dev) {
```
`ENVIRONMENT_IS_NODE` is false.

If, in my csound_extended.js script, I change:
```
  ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function'  && !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_WORKER;
```
to:
```
  ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function'  && !ENVIRONMENT_IS_WORKER;
```
then the mount succeeds.

I suggest you do not test for `ENVIRONMENT_IS_WEB` but instead test if `require('fs')'` succeeds. That should work for both Node.js and NW.js.

​

**Comment by kripken** [comment]
What is "NW.js"?

**Comment by kripken** [comment]
Interesting, thanks!

As a workaround, you can set `Module.ENVIRONMENT` to `"NODE"` to force detection of node as the environment. Otherwise, perhaps we should do more feature-testing as opposed to recognizing just a few canonical environments, but that's a complex topic for the long term. Would be good though if someone were interested to look into it.

**Comment by gogins** [comment]
Your suggestion worked fine, thanks.

Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kripken** [comment]
Great, closing as there's not much more we can do here.
