### ISSUE TITLE
String passing from c++ to js

### ISSUE THREAD

**Issue by WolverinDEV** [kripken/emscripten#6433]
Hey,
I have a small question.
I've currently this code:
```
extern "C" {
        inline const char* cstr(const std::string& message) {
		auto buffer = (char*) malloc(message.length() + 1);
		cout << "Allocating at " << (void*) buffer << endl;
		buffer[message.length()] = '\0';
		memcpy(buffer, message.data(), message.length());
		return buffer;
	}

	EMSCRIPTEN_KEEPALIVE
	const char* getAMessage() {
		return cstr("Hello World");
	};
}
```

Would the returned string pointer automatically get destroyed?
I'll call the methode like this:
```
let message = Module.cwrap("getAMessage", "string", [])();
```

**Comment by kripken** [comment]
Yes, see the note under https://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html#ccall - the stack is used for such temporary strings, so you don't need to free them manually.

**Comment by WolverinDEV** [comment]
Hey,
Thanks KS for your response. 
Well the fact is that I'm not allocating the string on the stack so I have to free it somehow. 
I currently just doing it by changing the return type to pointer, than stringify it and releasing it

**Comment by kripken** [comment]
Oh, I see, you manually malloc there. Then yes, you should manually free as well - emscripten won't do a `free()` automatically for something it didn't `malloc()`.

**Comment by WolverinDEV** [comment]
Okey thanks that's good to know. I thought there's may another trick or something killer that :)

**Comment by kovzol** [comment]
Thanks @WolverinDEV for this nice piece of code! Without this I sometimes ran into an "Invalid UTF-8 leading byte 0x?? encountered when deserializing a UTF-8 string in wasm memory to a JS string!" warning and the obtained string in JavaScript got messed. But this behavior was non-deterministic.
I tried my previous piece of code on Emscripten 2.0.15, 2.0.20 and 2.0.22 with no luck.
My former code looked like this:
```
extern "C" const char* EMSCRIPTEN_KEEPALIVE compute(char *input) {
return do_compute(string(input)).c_str();
}
```
Here do_compute(...) returns a C++ string after some more detailed computations.
I have no idea why this is unsafe. Maybe @kripken has an idea. Thanks in advance.

**Comment by sbc100** [comment]
If `do_compute` returns a std::string then you are not doing anything to keep the string live after returning the result of `c_str()`.  The result of `c_str()` is only valid a long as the `std::string` itself.

Assuming you are ok with only one result pointer at a time you could do something like:

```
static std::string s = do_compute(string(input));
return s.c_str();
```

Then the pointer you return is valid until the next call.

**Comment by wsd12345** [comment]
@kripken Hello, I have a similar problem.

```c++
char *f_r(char *path) {
    char *res = (char *) malloc(1000 * sizeof(char));
FILE *file;
file = fopen(path, "rb");
if (!file) {
    printf("cannot open file\n");
    char *r = (char *) malloc(1 * sizeof(char));
    r[0] = '\0';
    return r;
}
int idx = 0;
while (!feof(file)) {
    char c = fgetc(file);
    if (c != '\0') {

        if (c != EOF) {
            putchar(c);
            res[idx++] = c;
        }
    }
}

fclose(file);

char *r = (char *) malloc((idx - 1) * sizeof(char));
char *ret = r;

for (int i = 0; i < idx; i++) {
    *(ret + i) = res[i];
}
*(ret + idx) = '\0';

free(res);
return r;
}
```

and 

```js
f_r = Module.cwrap('f_r',  'string', ['string'])
 for (i = 0; i < 1000000; i++) {
 a =f_r("a.txt");
}
```

But,I see that the browser footprint continues to increase.I am new to js and use `emrun func.html` zone to run html files.

**Comment by WolverinDEV** [comment]
> you should manually free as well - emscripten won't do a free() automatically for something it didn't malloc().

```
char *r = (char *) malloc((idx - 1) * sizeof(char));
[...]
return r;
```
`r` never gets freed :)

**Comment by wsd12345** [comment]
> > you should manually free as well - emscripten won't do a free() automatically for something it didn't malloc().
> 
> ```
> char *r = (char *) malloc((idx - 1) * sizeof(char));
> [...]
> return r;
> ```
> 
> `r` never gets freed :)

Thank you for your reply. But , I add ` free()` and `delete a `, I also see that the browser footprint continues to increase.

```c++
char *r = nullptr;
 
int my_free() {
    if (r != nullptr) {
        free(r);
        r = nullptr;
        return 0;
    } else {

        return 1;
    }
}

```

and 

```js
f_r = Module.cwrap('f_r',  'string', ['string'])
for (i = 0; i < 1000000; i++) {
    a =f_r("a.txt");
    my_free();
    delete a;
}
```
![1](https://github.com/user-attachments/assets/5c2818af-bbbf-4f52-aaae-3d49cdc8912b)
![2](https://github.com/user-attachments/assets/55a2e91c-6c17-4393-b9c8-93a5e2615d8e)

When I finished running the for loop, the memory usage went from 770 to 838. The compile command I used

```
 emcc func.cpp -o func.html -sEXPORTED_FUNCTIONS=_int_sqrt,_f_w,_f_r,_my_free -sEXPORTED_RUNTIME_METHODS=ccall,cwrap
```
