### ISSUE TITLE
can't use emscripten to build Ffmpeg with  --enable-d3d11va --enable-dxva2     on Unbuntu16.04 TLS

### ISSUE THREAD

**Issue by myseemylife** [kripken/emscripten#6438]
I have successfully build ffmpeg without hwaccel support, when i use it to decode h264 (1080P)streams.The CPU is so high! so I turn to  build ffmpeg with hwaccel ,think it will lower the cpu costs.
Sadlly,i can't configure right. --enable-d3d11va --enable-dxva2  both configure error.
Any helps?how can i make it possible?

**Comment by kripken** [comment]
Emscripten code can only access APIs that can be implemented on the Web, so you might be able to get hardware acceleration if ffmpeg can use OpenGL to do that, or can be extended to do so.

**Comment by myseemylife** [comment]
@kripken thx for your response~As what you said, port MS libs like directx dxva or others  are impossible now with emscripten toolchain.  I found OpenCV and CUDA after i read your sugesstion,the OpenCV team make a js version.OpenCV.js,I will check that and deeo into it for my goal. at the end ,many thx to you guy
