### ISSUE TITLE
Exception thrown, see JavaScript console

### ISSUE THREAD

**Issue by dudiko** [kripken/emscripten#6441]
Hi,
I'm compiling my project using emscripten and everything is ok while I'm compiling it into JS and running via Nodejs, but when I'm trying to compile it into HTML and running via any browser (chrome/firefox) I'm getting "Exception thrown, see JavaScript console" without any more details:

![image](https://user-images.githubusercontent.com/11901800/38678565-101383da-3e6a-11e8-845e-27b5891e1783.png)

Any help here?
Thanks,
Dudi

**Comment by kripken** [comment]
You can open the JS console by doing control-shift-J in chrome or control-shift-K in firefox. Hopefully the info there makes this easy to fix.

**Comment by dudiko** [comment]
Thank you! It helped me a lot

**Comment by alysdexia** [comment]
The console doesn't help me:
https://www.roguetemple.com/z/hyper/online.php
HyperRogue by Zeno Rogue <zeno@attnam.com>, version 11.2e
released under GNU General Public License version 2 and thus
comes with absolutely no warranty; see COPYING for details
initgraph
115022   restartGraph
115024     (done)
000009   prepare_basics
000011     geom3::compute
000014       (done)

**Comment by kripken** [comment]
I do see errors in the console there, like
```
online.php:138 exception thrown: RuntimeError: remainder by zero,RuntimeError: remainder by zero
    at wasm-function[322]:0x21c19
    at wasm-function[4297]:0x3d8f39
    at Module.dynCall_vi (https://www.roguetemple.com/z/hyper/hyper.js:1:216907)
    at invoke_vi (https://www.roguetemple.com/z/hyper/hyper.js:1:254508)
    at wasm-function[383]:0x3cd11
    at wasm-function[4297]:0x3d8f39
    at Module.dynCall_vi (https://www.roguetemple.com/z/hyper/hyper.js:1:216907)
    at invoke_vi (https://www.roguetemple.com/z/hyper/hyper.js:1:254508)
    at wasm-function[1546]:0x1f1eef
    at wasm-function[1544]:0x1f1854
```
Maybe you need to scroll down to see them or something? Or maybe your console is set to filter out errors, may need to adjust the settings.

**Comment by alysdexia** [comment]
I can see those too, but I meant by the show/hide console button.
