### ISSUE TITLE
Where can I try the the new SIMD feature of WebAssembly?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6445]
Does Emscripten toolchain support this feature currently? 

FYI: https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md

**Comment by kripken** [comment]
Hmm, I'm not sure but I don't think any wasm VM has SIMD support yet. I do know wabt does in the toolchain space, but everything else still has a bunch more work to do, both browsers and LLVM etc.

**Comment by Becavalier** [comment]
@kripken Got it, thanks! ; )
