### ISSUE TITLE
Investigate speeding up 'other' test suite

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#6448]
The `other` test suite often times out on travis. Timing the tests, these are the slowest, and their times in seconds:
```
  412 test_single_file
  271 test_binaryen_opts
  206 test_vorbis
  203 test_eval_ctors
  165 test_embind
  164 test_emcc
  141 test_cmake
```
Perhaps we can speed them up by finding silly stuff there that we don't need to do.

**Comment by Ameobea** [comment]
Is this still timing out?  It looks like #6576 fixed this, or at least did enough to get rid of the timeout issue.

**Comment by kripken** [comment]
Thanks @Ameobea, yes, we can close this now.
