### ISSUE TITLE
Merge LLVM 6.0 to fastcomp

### ISSUE THREAD

**Issue by vadlis** [kripken/emscripten#6471]
Hi,

Is there any chance to get emcc to work with clang 6.0?

Thanks

**Comment by kripken** [comment]
Note that you can use LLVM 6.0 with wasm, using the LLVM wasm backend (just point emscripten's LLVM_ROOT in the config file to such a build of LLVM). We don't do that by default yet as there are some downsides, but it should work well for most things.

Would be good if someone had time to look into this for fastcomp, for our asm.js and asm2wasm support.

**Comment by kripken** [comment]
Being worked on in https://github.com/kripken/emscripten/issues/6544
