### ISSUE TITLE
embind: struct with raw pointer to struct

### ISSUE THREAD

**Issue by adamfk** [kripken/emscripten#6492]
I love emscripten! Super cool :)

I understand that raw pointers to primitive types are not bound, but what about a raw pointer to another struct? Below is a simple example I'm working on. 

```c++
#include <emscripten/bind.h>
using namespace emscripten;

extern "C" {
  typedef struct MyStruct {
    int x;
  } MyStruct;
  
  typedef struct MyStructTwo {
    int y;
    MyStruct* ptr;
  } MyStructTwo;
}

EMSCRIPTEN_BINDINGS(some_name) {
  value_object<MyStruct>("MyStruct")
    .field("x", &MyStruct::x)
    ;

  value_object<MyStructTwo>("MyStructTwo")
    .field("y",   &MyStructTwo::y)
    .field("ptr", &MyStructTwo::ptr)  //boom! "Implicitly binding raw pointers is illegal.  Specify allow_raw_pointer<arg<?>>"
    ;
}
```

It looks like I need to do `allow_raw_pointer<arg<?>>` somewhere, but I haven't been able to do so correctly yet.

Any pointers?

Thanks!

**Comment by brion** [comment]
There doesn't seem to be a place to put in the `allow_raw_pointers` bit for fields here, and I'm not sure it would really apply. But I think there's another way to do what you probably want here, which is to use a custom getter and/or setter:

```cpp
#include <emscripten/bind.h>
using namespace emscripten;

extern "C" {
  typedef struct MyStruct {
    int x;
  } MyStruct;
  
  typedef struct MyStructTwo {
    int y;
    MyStruct* ptr;
  } MyStructTwo;
}

static MyStruct MyStructTwo_ptr_getter(const MyStructTwo &ms2) {
    // Return a MyStruct by-val to be converted into a value object.
    return *ms2.ptr;
}

static void MyStructTwo_ptr_setter(MyStructTwo &ms2, const MyStruct &ms) {
    // Take a MyStruct marshalled in from a value object, and save
    // it somewhere, so we can keep the pointer around in this struct.
    // In a real program you'd want to manage pointer lifetime and such.
    ms2.ptr = new MyStruct(ms);
}

EMSCRIPTEN_BINDINGS(some_name) {

  value_object<MyStruct>("MyStruct")
    .field("x", &MyStruct::x)
    ;

  value_object<MyStructTwo>("MyStructTwo")
    .field("y",   &MyStructTwo::y)
    .field("ptr", &MyStructTwo_ptr_getter, &MyStructTwo_ptr_setter)
    ;
}
```

(compiled but not tested at runtime)

Since the getter returns the dereferenced MyStruct directly by value, the marshalling code will create a MyStruct-styled value object for it in the output object.

There's also a setter, used when passing a JS value object back into a C++ function that takes a MyStructTwo. This one's trickier potentially, because you need to allocate a new heap location and manage its lifetime. If you need to be able to share objects and retain their identity across the boundary, consider using `class_` instead of `value_object`.

**Comment by adamfk** [comment]
Thanks @brion. I'll see if I can get SWIG or something similar to generate my interfaces for me. All the best!

**Comment by adamfk** [comment]
FYI, this is the source of the error message I was receiving for my example above: https://github.com/kripken/emscripten/blob/incoming/system/include/emscripten/wire.h#L111

`"Implicitly binding raw pointers is illegal.  Specify allow_raw_pointer<arg<?>>"`

I'm fine resorting to the getters and setters, but it sure seemed that there was some way based on the static assert message. If there truly is no way to do it, then maybe the error message should be updated to avoid future confusion?

**Comment by hugoam** [comment]
This is a terrible solution to a really straightforward and common problem.
- the documentation of Embind should at least mention the case of member pointer to structs/classes
- from what I gather, this is simply unimplemented (there is no way to bind a pointer to struct member out of the box)

As to how should I proceed if I need to bind a codebase where I need to bind such constructs ? The documentation says Embind can bind more complex C++ programs, but correct me if I'm wrong, if such a simple feature seems to be supported by WebIDL, but not by Embind, WebIDL is probably the saner alternative for any moderately complex C++ codebase ? (I'm also biased to think that by the fact that a library such as bullet is bound using WebIDL, not Embind)

**Comment by Jagathishrex** [comment]
Hi 👋  , I want a function to return an vector of struct or array of struct.How can i do that,

Ex;
struct data {
   int x;
};

vector<data> returnCollectionOfStruct() {
    data struct1 , struct2,struct3;
    vector<data> dataVector;
    dataVector.push_back(struct1) ;
    dataVector.push_back(struct2) ;
    dataVector.push_back(struct3) ;
    return dataVector;
}
Like the above , can i Do that  ?  @kripken @brion

**Comment by shahzebweoptit** [comment]
@Jagathishrex Have you able to do what you needed? I need your help.

**Comment by sasmaster** [comment]
Same problem here.

**Comment by kripken** [comment]
I ran into this now when trying to use embind on Binaryen. Binaryen's core IR is basically a set of structs with raw pointers to other structs (the children of each expression).

@brendandahl do you think this might be practical to fix?

**Comment by brendandahl** [comment]
I can't think of any obvious reasons we couldn't support it.

FWIW, generally when pointers are involved a regular `class_` binding seems to be the better approach since they provide more options there.

**Comment by kripken** [comment]
@brendandahl 

Ah, to be clear, my case involves `class_` actually: `allow_raw_pointers` does not work on a `property`. I agree that pointing people to use `class_` over `value_object` makes sense, if we can make `allow_raw_pointers` work there.

In more detail, here is my code:

```cpp
  class_<If>("If")
    .property(condition, &id::condition, allow_raw_pointers())
  ;
```

Without `allow_raw_pointers` that errors on that being a raw pointer:
```cpp
emscripten/wire.h:116:19: error: static assertion failed due to requirement '!std::is_pointer<wasm::Expression *>::value': Implicitly binding raw pointers is illegal.  Specify allow_raw_pointer<arg<?>>
  116 |     static_assert(!std::is_pointer<T*>::value, "Implicitly binding raw pointers is illegal.  Specify allow_raw_pointer<arg<?>>");
```
But adding `allow_raw_pointers` errors so it seems to not be supported there,
```cpp
emscripten/bind.h:1805:22: error: implicit instantiation of undefined template 'emscripten::internal::GetterPolicy<wasm::Expression *wasm::If::*>'
 1805 |         auto gter = &GP::template get<ClassType>;
      |                      ^
src/wasm-delegations-fields.def:269:5: note: in instantiation of function template specialization 'emscripten::class_<wasm::If, emscripten::base<wasm::Expression>>::property<emscripten::internal::DeduceArgumentsTag, wasm::Expression *wasm::If::*, emscripten::allow_raw_pointers>' requested here
```

**Comment by kripken** [comment]
Sounds great @brendandahl , thanks!

I'll close this then, as it seems I misunderstood and the main issue here was about `value_object`. But the issue here will also get a better workaround once `class.property` supports raw pointers (by using `class` instead of `value_object`).

**Comment by GulgDev** [comment]
We still can't use `allow_raw_pointers` on properties, can we?

**Comment by brendandahl** [comment]
It should work https://github.com/emscripten-core/emscripten/pull/21935

**Comment by GulgDev** [comment]
It works fine, but when I try to use policies with getter & settee, I get an error.

**Comment by brendandahl** [comment]
Hmm...there are tests for that. Can you open a new issue with a reproducer and I'll look into it?
