### ISSUE TITLE
Handle big files in web worker using IDBS?

### ISSUE THREAD

**Issue by CodeFetch** [kripken/emscripten#6494]
As far as I understand using IDBFS a copy of my data remains in memory (in MEMFS). 
When I have very big files or a low memory situation this crashes my browser in the worst case.
Thus I'm thinking about writing a new filesystem similar to MEMFS which splits files into e.g. 4MB chunks and dynamically swaps the unused chunks to IDBStore. 
Is this possible or is there some workaround for my problem?
Where should I start? Do I need to consider that IDBStore is asynchronous or can I call e.g. idb_load_blob "synchronously" e.g. in a write function of the new FS?

**Comment by kripken** [comment]
I think @juj had plans to do related things in ASMFS, but not sure of the status of those.

Another thing to maybe look at is BrowserFS, which has a way to integrate with emscripten - maybe they have something similar?

**Comment by CodeFetch** [comment]
Thank you for the hint. Unfortunately neither ASMFS nor BowserFS can do what I'd like to achieve.
I have single files which can exceed 1 GB in size. On systems with enough memory it works with MEMFS. I could rewrite the C code and use e.g. persistFileToIndexedDB from ASMFS, but a better approach would be to create a new FS which virtually splits the MEMFS-like files into chunks and dynamically swaps them to IDB.
I try to be more precise with my question:
When I create e.g. library_idbcachefs.js... can I call asynchronous functions in a synchronous fashion just by using 
> idbcachefs_store_blob__deps: ['$EmterpreterAsync'],
or is this just to create functions which can be called from C?

**Comment by kripken** [comment]
The `EmterpreterAsync` stuff allows C code to call C functions that are asynchronous, but it looks like you are calling them synchronously. We don't have support for calling such methods from JS (could be done in principle, but the design is tricky).

**Comment by CodeFetch** [comment]
Thank you very much for the clarification. I'm going to try it with promises or I modify my code to use ASMFS...
