### ISSUE TITLE
ImportError: cannot import name python_selector

### ISSUE THREAD

**Issue by 740291272** [kripken/emscripten#6495]
Traceback (most recent call last):
  File "/home/gloomyghost/gtsu/emsdk/emscripten/1.37.38/emcc", line 6, in <module>
    from tools import python_selector
ImportError: cannot import name python_selector

**Comment by kripken** [comment]
That doesn't sound like a known issue. Perhaps did something go wrong with the install? If `tools/python_selector.py` was removed or not created somehow that could cause such an error.

**Comment by 740291272** [comment]
Thanks ! Fixed

**Comment by Yueeeeee** [comment]
How did you solve it

**Comment by chengjiantong1005** [comment]
@GloomyGhost-MosquitoCoil hello,how did you solove it, could you share us

**Comment by GloomyGhost-MosquitoCoil** [comment]
> @GloomyGhost-MosquitoCoil hello,how did you solove it, could you share us

You need reinstall it. it is a install error
