### ISSUE TITLE
FS.syncfs always fails with IDBFS on Firefox

### ISSUE THREAD

**Issue by phoenixx2** [kripken/emscripten#6499]
Using:
Emscripten 1.37.38
Firefox 59.0.3 (64-bit)

Simply doing this at the beginning (which I've been doing fine for years without issues) :

FS.mkdir('/IDBFS');
FS.mount(IDBFS, {}, '/IDBFS');
FS.syncfs(true, function (err) {
    console.log(err);
    assert(!err);
}

Always asserts, with the log containing:

DOMUnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.

With error name: UnknownError

Clearing Firefox cache did not resolve.  Uploading all files to a server (which is required for Chrome) did not resolve the issue either.

Flawless on Chrome 66.0.3359.139 (Official Build) (64-bit)

Any direction would be appreciated.  This is used in production.

**Comment by kripken** [comment]
Do the relevant tests pass for you, `./tests/runner.py  browser.test_*idbfs*`? If they fail, perhaps the firefox profile or it's IDB storage got corrupted somehow.

**Comment by phoenixx2** [comment]
Was just logging back on to actually mention my success... Refreshing Firefox / purging profile fixed the issue.  Thank you though, I was stuck on this for a while now!

**Comment by kripken** [comment]
Good, glad it worked out.

Yeah, I've seen IDB corruption on firefox too, in the past...
