### ISSUE TITLE
Compilation faliure - No package 'sdl2' found

### ISSUE THREAD

**Issue by UstymUkhman** [kripken/emscripten#6503]
Hi there! I'm new to emscripten; several days ago I've downloaded it just to try to make a port of a game to JS. Great project, by the way!

Anyway, after some steps, I'm having this issue now (on Ubuntu 16.04 STL).
By following build steps [here](https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#building-projects), first of all, I've set environment variables with
`source ./emsdk_env.sh` and then I've tried to configure the project with `emconfigure ./configure` in the project directory. When checking for tools emscripten needs, I've got this error:

checking for SDL... no
configure: error: Package requirements (sdl2 >= 2.0.1) were not met:

No package 'sdl2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SDL_CFLAGS
and SDL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
ERROR:root:Configure step failed with non-zero return code 1! Command line: ['./configure'] at ...

So I've tried to set that variable with the following command:
`export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/`
This is where actually `sdl2.pc` is located on my machine, but it didn't help.

So then I've set the following variables that `emconfigure` needed:
export SDL_PATH=/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h
export SDL_LIBS=/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h
export SDL_CFLAGS=/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h
export SDLNET_LIBS=/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h
export SDLNET_CFLAGS=/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h
export SDLMIXER_LIBS=/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h
export SDLMIXER_CFLAGS=/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h

and relaunched `emconfigure ./configure` which has completed well.
So the next step is `emmake make` that gives me the following error:

make  all-recursive
make[1]: Entering directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0'
Making all in textscreen
make[2]: Entering directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0/textscreen'
Making all in fonts
make[3]: Entering directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0/textscreen/fonts'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0/textscreen/fonts'
Making all in .
make[3]: Entering directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0/textscreen'
  CC       txt_conditional.o
Traceback (most recent call last):
  File "/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/emcc", line 11, in <module>
    python_selector.run(__file__)
  File "/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/emcc.py", line 1345, in run
    assert header.endswith(HEADER_ENDINGS), 'if you have one header input, we assume you want to precompile headers, and cannot have source files or other inputs as well: ' + str(headers) + ' : ' + header
AssertionError: if you have one header input, we assume you want to precompile headers, and cannot have source files or other inputs as well: ['/home/ustym/Documents/Projects/emsdk/emscripten/1.37.38/system/include/SDL/SDL.h', 'txt_conditional.c'] : txt_conditional.c
Makefile:447: recipe for target 'txt_conditional.o' failed
make[3]: *** [txt_conditional.o] Error 1
make[3]: Leaving directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0/textscreen'
Makefile:467: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0/textscreen'
Makefile:585: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ustym/Documents/Projects/chocolate-doom-3.0.0'
Makefile:438: recipe for target 'all' failed
make: *** [all] Error 2

that means, I assume, that `SDL_PATH`, `SDL_LIBS`, `SDL_CFLAGS`... variables weren't set correctly. Or maybe I just need to precompile that headers in the SDL directory.

One last thing: if I skip setting SDL variables and the configuration step and just launch `emmake make`, the compilation goes well, but then, `emcc` command gives me
`WARNING:root:    .o is not valid LLVM bitcode`
for all generated `.o` files. And that actually makes sense.

So I'm pretty stuck here. Somebody can tell me how to set correctly `PKG_CONFIG_PATH` for emscripten or if i really need to precompile those headers in the SDL directory? Thanks!

**Comment by kripken** [comment]
I don't know enough about how `PKG_CONFIG_PATH` stuff works. There might be a way to fix that - maybe `system/bin/sdl2-config` is relevant?

But in general, many configure scripts check for libraries like SDL in a system-specific way, and they don't work out of the box with cross-compilers like emscripten. In practice, it can be necessary to modify the configure script in those cases. In this example, you can just make it skip the SDL check, and use SDL by adding `-s USE_SDL=2` to the emcc arguments (which will fetch and build SDL2 for you, and set up the include paths etc.).

**Comment by brion** [comment]
I haven't tried this particular project yet, but in general with autoconf stuff env variables like CFLAGS and PKG_CONFIG_PATH need to be provided as parameters to configure, like this from one of ogv.js's library builds:

```bash
# finally, run configuration script
emconfigure ../../../libskeleton/configure \
	--prefix="$dir/build/js/root" \
	PKG_CONFIG_PATH="$dir/build/js/root/lib/pkgconfig"

# compile libskeleton
emmake make -j4
emmake make install
```

(in that case for letting pkg-config pick up libraries I'd earlier compiled and installed into a common directory)

**Comment by UstymUkhman** [comment]
So, after a while I've retried to recompile this project and, basing on @kripken's suggestion I've skipped the SDL check in the `configure` script and was able to run `emmake make` correctly. Thanks man! 👍
