### ISSUE TITLE
failure to parse metadata output from compiler backend

### ISSUE THREAD

**Issue by schoedl** [kripken/emscripten#6504]
There is a problem with processing escaped strings. This input does not compile, apparently because of the \\/ escape sequence:

#include <emscripten.h>

int main() {
	emscripten_asm_const_int(
		"document.URL.match(/^https:\\/\\/docs\\.google\\.com$/);"
	);
	return 0;
}

**Comment by kripken** [comment]
`emscripten_asm_const_int` is meant for internal use - it's how EM_ASM are implemented. Are you using it directly on purpose here, or is this reduced from something using EM_ASM?

I don't remember offhand how EM_ASM handles escaping stuff, but I think we have code to handle this kind of thing - perhaps this is a bug there though.

**Comment by schoedl** [comment]
I expanded EM_ASM. I actually just tried raw string literals, which seem to be well-suited for the job. But it does not work either:

#include <emscripten.h>

int main() {
emscripten_asm_const_int(R"(
	var a=document.URL.match(/^https:\/\/docs$/);
)");
return 0;
}

It compiles, but then I get:

ERROR:root:emscript: failure to parse metadata output from compiler backend. raw output is:

{
"staticBump": 1576,
"declares": ["sbrk", "emscripten_asm_const_int"],"redirects": {},"externs": [],"implementedFunctions": ["_main", "_malloc", "_free", "___errno_location"],"tables": {},"initializers": [],"exports": [],"aliases": {},"cantValidate": "","simd": 0,"simdUint8x16": 0,"simdInt8x16": 0,"simdUint16x8": 0,"simdInt16x8": 0,"simdUint32x4": 0,"simdInt32x4": 0,"simdFloat32x4": 0,"simdFloat64x2": 0,"simdBool8x16": 0,"simdBool16x8": 0,"simdBool32x4": 0,"simdBool64x2": 0,"maxGlobalAlign": 4,"namedGlobals": {},"asmConsts": {"0": ["
\\tvar a=document.URL.match(/^https:\/\/docs$/);
", ["i"], [""]]}
}

It looks like the text above double-escaped the tab I had in my source code as \\t, but it did not escape the backslash in the Javascript regexp (which itself is for escaping) at all.

**Comment by schoedl** [comment]
Help! This editor escapes by itself! I edited the above to make it look like what I got as the actual output.

**Comment by kripken** [comment]
Ok, if it's expanded from EM_ASM, then can you provide a testcase written that way? Easier to test on.

We should also test if this is a problem on both asm2wasm and the wasm backend - they have different code for this.

**Comment by schoedl** [comment]
Sorry for the fuzz, it does work when using EM_ASM and escaping the backslash:

#include <emscripten.h>

int main() {
EM_ASM(
	var a=document.URL.match(/^https:\\/\\/docs$/);
);
return 0;
}
