### ISSUE TITLE
IE11 x13 slower compared to chrome and firefox

### ISSUE THREAD

**Issue by DevGoslinga** [kripken/emscripten#6518]
LZ4 and ZSTD (very fast compression libraries)

File
original size 8mb 
compressed size 1.6mb

LZ4

project: https://github.com/lz4/lz4
JS: https://github.com/ukyo/lz4.js/blob/master/lz4.js 
firefox 20ms 
chrome 30ms
IE11 718ms
MS EDGE 44ms

ZSTD

project: https://github.com/facebook/zstd
ZSTD latest version emscripten
chrome 200ms
firefox 150ms
IE11 ...

Native decompression time for both libraries less then 10ms. Is this performance hit expected in IE?

UPDATE:
original size 8mb compressed 1-100kb  IE 44ms 
original size 8mb compressed ~600kb IE 718ms

Passing array to emscripten seems to be very expensive in IE

**Comment by DevGoslinga** [comment]
Make sure to allow blocked content IE when opening html file. 

[lz4-project.zip](https://github.com/kripken/emscripten/files/1991189/lz4-project.zip)

**Comment by curiousdannii** [comment]
IE 11 is rather old now, 4.5 years old in fact. I don't think it received any asm.js optimisations, so don't use it if performance is important.

**Comment by DevGoslinga** [comment]
Yes, true but unfortunately I am writing application for a big company which has a Citrix environment with IE11 and I cannot push them to change. I will have to look for another way to accomplish my performance target. Thank you for the response. I will close this ticket.

**Comment by curiousdannii** [comment]
Unfortunate if only IE11 is available, and not Edge or another modern browser. Sorry but I don't know if there's any other ways to improve performance.
