### ISSUE TITLE
64bit pointer casting different from linux gcc

### ISSUE THREAD

**Issue by codinguncut** [kripken/emscripten#652]
In the context of casting a pointer to a uint64_t llvm/emscripten acts differently from gcc.
For some reason gcc pads the pointer with leading 1s while llvm/emscripten does not.

I could easily do without making up these stupid fringe cases, but unfortunately this is from actual code ;(

gcc issues a warning on this code `warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]`, but `g++ -Wall` does not.

<pre>
$ g++ mask.c && ./a.out 
pointer      : ffffffffb525c008
unsigned long: b525c008
signed   long: ffffffffb525c008
pointer == unsigned long? no
pointer == signed long? yes
sizeof(unsigned long): 4, sizeof(long): 4, sizeof(void*): 4
</pre>

<pre>
$ emcc mask.c -o mask.js && node mask.js
pointer      : b525c008
unsigned long: b525c008
signed   long: ffffffffb525c008
pointer == unsigned long? yes
pointer == signed long? no
sizeof(unsigned long): 4, sizeof(long): 4, sizeof(void*): 4
</pre>

The output is the same with em++.

```
#include <stdio.h>
#include <stdint.h>

int main()
{
  void* pointer         = (void*) 0xb525c008;
  unsigned long iulong  = (unsigned long) pointer;
  long ilong            = (long)          pointer;

  printf("pointer      : %llx\n", (uint64_t)pointer);
  printf("unsigned long: %llx\n", (uint64_t) iulong);
  printf("signed   long: %llx\n", (uint64_t) ilong);
  printf("pointer == unsigned long? %s\n", ((uint64_t)pointer) == ((uint64_t)iulong) ? "yes" : "no");
  printf("pointer == signed long? %s\n", ((uint64_t)pointer) == ((uint64_t)ilong) ? "yes" : "no");
  printf("sizeof(unsigned long): %d, sizeof(long): %d, sizeof(void*): %d\n", sizeof(iulong), sizeof(ilong), sizeof(void*));
}
```

### System
<pre>
emscripten: kripken/emscripten git repo Mon Oct 15 13:54:48 2012 -0700
llvm: 3.1
node: v0.8.12
gcc: gcc (Ubuntu/Linaro 4.7.2-1ubuntu1) 4.7.2
uname -a
Linux Lorax 3.5.0-15-generic #22-Ubuntu SMP Wed Sep 19 20:06:19 UTC 2012 i686 i686 i686 GNU/Linux
Ubuntu quantal
cpu/system: Intel(R) Core(TM)2 Duo CPU     U9600  @ 1.60GHz
</pre>

**Comment by juj** [comment]
This behavior is discussed more e.g. in http://stackoverflow.com/questions/7677919/unexpected-sign-extension-of-int32-or-32bit-pointer-when-converted-to-uint64, essentially the result here is that this behavior is implementation defined.

For example, trying this on Visual Studio 2015 natively, I am getting a result that agrees with the above GCC behavior:

	C:\code\emsdk\emscripten\incoming>cl c.c /Fe:c.exe
	Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x86
	Copyright (C) Microsoft Corporation.  All rights reserved.

	c.c
	Microsoft (R) Incremental Linker Version 14.00.23506.0
	Copyright (C) Microsoft Corporation.  All rights reserved.

	/out:c.exe
	c.obj

	C:\code\emsdk\emscripten\incoming>c
	pointer      : ffffffffb525c008
	unsigned long: b525c008
	signed   long: ffffffffb525c008
	pointer == unsigned long? no
	pointer == signed long? yes
	sizeof(unsigned long): 4, sizeof(long): 4, sizeof(void*): 4

To get the unified treatment with respect to sign extension, one can cast to `uintptr_t` or `intptr_t` first, e.g.

	#include <stdio.h>
	#include <stdint.h>

	int main()
	{
	  void* pointer         = (void*) 0xb525c008;
	  printf("pointer      : %llx\n", (uint64_t)(intptr_t)pointer); // prints ffffffffb525c008
	}

or

	  printf("pointer      : %llx\n", (uint64_t)(uintptr_t)pointer); // prints b525c008

where the behavior should be the same for Visual Studio, GCC, Clang and Emscripten each. I'll close this, since it's not really a compiler bug.
