### ISSUE TITLE
Where do we use the content of "~/.emscripten" file in the source code of those python wrappers like "emcc.py" and etc?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6529]
Where do we use the content of "~/.emscripten" file in the source code of those python wrappers like "emcc.py" and etc?

**Comment by jgravelle-google** [comment]
https://github.com/kripken/emscripten/blob/6da5186c27f7a59e7a6d7e1ad200edc6e0052da3/tools/shared.py#L246-L247

**Comment by Becavalier** [comment]
Thanks!
