### ISSUE TITLE
fails to work on android - desktop firefox is fine.

### ISSUE THREAD

**Issue by shlomif** [kripken/emscripten#6531]
See http://www.shlomifish.org/1/js-fc-solve/find-deal/ - and the sources at https://github.com/shlomif/temp-fc-solve-site-dest and https://github.com/shlomif/fc-solve/tree/master/fc-solve/site/wml - the "Populate" button in the "Test find a numbered deal" tab works fine in firefox 60 on mga7 x86-64 but fails on android samsung galaxy s3. It seems to be a problem in ccall. I am using asm.js.

**Comment by shlomif** [comment]
Note that I am using emcc 1.38.0 from emsdk.

**Comment by kripken** [comment]
I'm not aware of any open bugs on android specifically, so no guess as to what this could be.

I don't have a device to test on myself. To debug this, I'd suggest adding some print statements in the relevant code, in a `-g` build. Hopefully that lets you quickly see what's going wrong. Perhaps android has a debugger tool that lets you see the error console somehow?

**Comment by shlomif** [comment]
After using `emcc -g` instead of `emcc -O3` I got an exception for missing LEGACY_VM_SUPPORT - https://github.com/kripken/emscripten/issues/6204 - adding it made it work there again. Thanks!

**Comment by kripken** [comment]
Great!
