### ISSUE TITLE
What's the difference between "use asm" and "almost asm"?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6541]
Two questions:

1. What kind of situation that the Emscripten toolchain will output a "almost asm" like JavaScript function instead of a standard ASM.js module function?

2. Does the "almost asm" symbol mean that the JavaScript engine will never do any optimizations on those ASM.js like JavaScript functions?

Thanks!

**Comment by kripken** [comment]
We emit "almost asm" when the code we emit isn't valid asm.js (some compiler modes like memory growth and split memory cause that). We also emit it when not optimizing, as asm.js optimizations in browsers are very slow on huge unoptimized files (it's better to not try to optimize them as asm.js).

Emitting "almost asm" means that browsers that have asm.js optimizations will not use them. But they still optimize the code like normal JS, which is often still fast, sometimes even just as fast.

**Comment by Becavalier** [comment]
@kripken I get it, thanks!
