### ISSUE TITLE
How dose "EMSCRIPTEN_KEEPALIVE" macro work in emcc?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6546]
How dose "EMSCRIPTEN_KEEPALIVE" macro work in emcc? 

I saw the following code in file "emscripten.h", but what the question is:  the "__attribute__((used))" symbol seems just used for GCC but not Clang.

I can't find any related docs about how to this symbol in Clang, can you please help? Thanks!

> #define EMSCRIPTEN_KEEPALIVE __attribute__((used))

**Comment by jgravelle-google** [comment]
From https://clang.llvm.org/docs/LanguageExtensions.html:
> This document describes the language extensions provided by Clang. In addition to the language extensions listed here, Clang aims to support a broad range of GCC extensions. Please see the [GCC manual](https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html) for more information on these extensions.

Which is to say, clang supports `__attribute__((used))`. This then avoids every form of dead code elimination, and gets turned into a wasm export.

**Comment by Becavalier** [comment]
@jgravelle-google I get it, thanks!
