### ISSUE TITLE
How dose Emscripten deal with the c++ code which using "C++ Standard Library"?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6550]
How dose Emscripten deal with the c++ code which using "C++ Standard Library"?

Something like directly compiling the whole "C++ Standard Library" into a single ".bc" file?

**Comment by brion** [comment]
Roughly yes -- the standard library is compiled to bitcode, and your program is compiled against the matching header files (under emscripten's system/includes/libcxx directory) and your code linked against the libcxx.bc file.

The first time you use em++ to compile a C++ source file, you'll see that it compiles the C and C++ libraries and caches them to use again next time. (Each time you upgrade emscripten it'll see that its cache is out of date and clear it.)

**Comment by Becavalier** [comment]
@brion Got it, thanks!
