### ISSUE TITLE
Seg Fault on Full Screen Select with Resize Canvas

### ISSUE THREAD

**Issue by blockulator** [kripken/emscripten#6558]
Hi,

On changing to full-screen mode with "resize canvas" selected i get a segfault. The issue seems to be that SDL.screen is undefined in the following code.

> segmentation fault loading 4 bytes from address 0

```
        // check if SDL is available   
        if (typeof SDL != "undefined") {
          var flags = ((SAFE_HEAP_LOAD(((SDL.screen)|0), 4, 1))|0);
          flags = flags | 0x00800000; // set SDL_FULLSCREEN flag
          SAFE_HEAP_STORE(((SDL.screen)|0), ((flags)|0), 4)
        }
```

**Comment by kripken** [comment]
Thanks for filing, yeah, it seems like if the screen might not exist then we should check for that first there. However, it should only not exist if not created yet or if it was destroyed, so it should not happen normally. In what specific circumstances do you see this?

**Comment by kripken** [comment]
Oh, perhaps for an SDL app not using a screen at all?

**Comment by blockulator** [comment]
I'm running my SDL game and I click here. 
<img width="935" alt="full" src="https://user-images.githubusercontent.com/4362451/40327134-bcddec02-5d39-11e8-8b59-36983636a26b.PNG">

**Comment by blockulator** [comment]
I forgot one thing, "resize canvas" is also selected, full screen without canvas resize works fine.

**Comment by kripken** [comment]
Interesting, I still can't reproduce this. For example
```
#include <SDL/SDL.h>
#include <emscripten.h>

void loop() {}

extern "C" int main(int argc, char** argv) {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Surface *screen = SDL_SetVideoMode(256, 256, 32, SDL_HWSURFACE);
  emscripten_set_main_loop(loop, 0, 0);
  return 0;
}
```
and building with
```
./emcc tests/hello_world_sdl.cpp -o a.html -s SAFE_HEAP=1
```
I can enter and leave fullscreen with or without resize canvas, without error.

Maybe you can create a testcase showing the issue?

**Comment by blockulator** [comment]
I changed from SDL_CreateWindow/SDL_OPENGL to SDL_SetVideoMode/SDL_OPENGL and there was no crash, the only issue seems to be SDL_WINDOWEVENT_RESIZED does not fire, is there a different event for that?

Not sure why I was using SDL_CreateWindow in the first place, maybe I got it from an example somewhere.

**Comment by blockulator** [comment]
I implemented emscripten_set_fullscreenchange_callback for the full screen events but the screen size  I'm running a 3840x2160 desktop, when I go full screen it reports the size as 2560x1440 (expecting 3840x2160). Is this configured with EmscriptenFullscreenStrategy?

**Comment by kripken** [comment]
Hmm, are you using SDL1 or 2? `SDL_CreateWindow` is 2, I think. But then, SDL.screen should not be called as that is SDL1 code.

So my guess is you somehow ended up with both SDL1 and 2 code in the same project. It would be good to verify that and see how it happened - we should add guards in the code to prevent it.
