### ISSUE TITLE
`onRuntimeInitialized` breaks with promises

### ISSUE THREAD

**Issue by surma** [kripken/emscripten#6563]
Once I understood the modularized Emscripten `Module` API, I found it quite natural to wrap it into a `Promise` like this:

```js
import myModule from './myModule.js'; // ← This is the file generated by Emscripten

const module = new Promise(resolve => {
  myModule({
    onRuntimeInitialized() {
      resolve(myModule);
    }
  });
});
```

However, it seems that this throws the module into an infinite loop. Looking at the pre/postamble, it seems like [the `then()` implementation calls itself with itself as a parameter](https://github.com/kripken/emscripten/blob/06c58d48f37a126e51b809f4ae17d9297b06a444/src/postamble.js#L129-L144). Over and over.

Considering `async/await` is becoming more and more standard, this is worth fixing imo.

**Comment by kripken** [comment]
This may be the same as #5820

**Comment by surma** [comment]
It is indeed the same root cause. Gonna close this in favor of #5820 then
