### ISSUE TITLE
Pointer_stringify() ignores length parameter when string contains values >= 128

### ISSUE THREAD

**Issue by ragfield** [kripken/emscripten#6578]
Pointer_stringify() takes an optional length parameter, which it honors if all the characters are < 128.  If any characters are >= 128 the pointer is passed to UTF8ToString() without the corresponding length parameter.  If the string is not null-terminated UTF8ToString() will continue to read bytes past the specified length.

**Comment by curiousdannii** [comment]
Sounds like a duplicate of #5936.

**Comment by ragfield** [comment]
You are correct.
