### ISSUE TITLE
Warning: Casting a function pointer type to another with a different number of arguments

### ISSUE THREAD

**Issue by ambrop72** [kripken/emscripten#659]
This test program demonstrates a strange warning related to putting function pointers into a union.

    union Foo {
        void (*func1) (int a);
        void (*func2) (int a, int b);
    };

    void my_func2 (int a, int b)
    {
    }

    __attribute__((used))
    void MakeFoo (union Foo *out)
    {
        out->func2 = my_func2;
    }

    int main ()
    {
    }

$ emcc test.c -O2 -s VERBOSE=1
Warning: Casting a function pointer type to another with a different number of arguments. See more info in the compiler source
Warning: Casting a function pointer type to another with a different number of arguments: void (i32, i32)* vs. void (i32)*, on _my_func2
path.exists is now called `fs.exists`.
path.exists is now called `fs.exists`.

**Comment by juj** [comment]
Tested this snippet on latest incoming, where it looks like the function pointer casts no longer appear. Yay, closing as fixed.

As an expanded test case below, looks like the function gets correctly called as well.

	#include <stdio.h>
	#include <stdlib.h>

	union Foo {
	    void (*func1) (int a);
	    void (*func2) (int a, int b);
	};

	void my_func2 (int a, int b)
	{
		printf("%d %d\n", a, b);
	}

	__attribute__((used))
	void MakeFoo (union Foo *out)
	{
	    out->func2 = my_func2;
	}

	int main ()
	{
		Foo f;
		MakeFoo(&f);
	    f.func2(1, 2);
	}

and the above prints `1 2`.
