### ISSUE TITLE
Pointer casting support

### ISSUE THREAD

**Issue by opichals** [kripken/emscripten#66]
This might be a bit going against the strategy outlined in the README. It is stated that different sized pointer casting code will not work properly in emscripten.

However I wanted to compile a specific file format parsing library (st-guilde .HYP hepertext files http://code.google.com/p/libhyp/) into javascript along with its LH5 decompression algorithm. That required the pointer casting to work properly.

After adding some aliases and methods to src/library.js I succeeded to build a working application available at http://opichals.github.com/hypview/ (.hyp file viewer, one can download some .hyp file from http://libhyp.atari.org for tests).

The pointer casting changes are available at https://github.com/opichals/emscripten/tree/correct-pointers branch (on top of the nodejs branch I posted about before elsewhere). The core of the idea is that the resulting generated code emulates bigendian HEAP access for different size datatypes like e.g. "HEAP[v+1]<<8 | HEAP[v]" for reading 16bit int. No performance or other optimizations were accounted for - just the result correct behaviour.

Just wanted to make this available. I tend to think that this is the closest we can get to real LLVM bytecode memory management. Not sure whether this is something to be merged to master later on (perhaps as an option?).

**Comment by juj** [comment]
Type punning pointers is guaranteed in the typed arrays=2 mode, which asm.js is based on, and we require little endian support (out of practicality and visibility on our dev platforms, not out of necessity really), so it looks like the items discussed here are implemented. If someone wants to champion to add big endian support, let's operate on that as a separate item.
