### ISSUE TITLE
How should I understand the meaning of the following macro definition?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6600]
I know its usage and result but don't know the implementation detail of the following piece of code, could anyone help explain it? thanks!
```
const char* __em_js__##name() {              \
  return #params "<::>" #__VA_ARGS__;        \
}    
```

https://github.com/kripken/emscripten/blob/22508870f1fb3b70a35f1f55248f1dfd6dbce4f8/system/include/emscripten/em_js.h#L12-L21

**Comment by jgravelle-google** [comment]
Thanks for asking! There's a few pieces of magic here that I don't think are written down anywhere.
Rather than answer that here I added documentation to em_js.h in https://github.com/kripken/emscripten/pull/6603 . Let me know if you still have questions and I'll improve said documentation.

And for completeness, if other people don't know the usage of EM_JS, there's user-facing docs here: https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#inline-assembly-javascript

**Comment by Becavalier** [comment]
@jgravelle-google thanks for your help!

**Comment by Becavalier** [comment]
I look into the implementation of the Fastcomp-backend, and I find the following piece of code which used to parse the function defined with "EM_JS" macro, the last thing what I want to figure out is where can I find the code parsing the "<::>" symbol to recognize the param list and the function body?Thanks!

```c++
void handleEmJsFunctions() {
      for (Module::const_iterator II = TheModule->begin(), E = TheModule->end();
           II != E; ++II) {
        const Function* F = &*II;
        StringRef Name(F->getName());
        if (!Name.startswith(EM_JS_PREFIX)) {
          continue;
        }
        std::string RealName = "_" + Name.slice(EM_JS_PREFIX.size(), Name.size()).str();
        const Instruction* I = &*F->begin()->begin();
        const ReturnInst* Ret = cast<ReturnInst>(I);
        const ConstantExpr* CE = cast<ConstantExpr>(Ret->getReturnValue());
        const GlobalVariable* G = cast<GlobalVariable>(CE->getOperand(0));
        const ConstantDataSequential* CDS = cast<ConstantDataSequential>(G->getInitializer());
        std::string Code = CDS->getAsString();
        EmJsFunctions[RealName] = escapeCode(Code);
      }
    }
```

**Comment by jgravelle-google** [comment]
1. Good point, added a description of how we use the `emJsFuncs` metadata in https://github.com/kripken/emscripten/pull/6603/commits/b583670be116e03df741b830f1b83c282e2c6692

2. No good reason as far as I know - it seems to work as-is, and that's as far as I went with it I guess.
