### ISSUE TITLE
emscripten_set_main_loop not working

### ISSUE THREAD

**Issue by JeffMushmo** [kripken/emscripten#6601]
I can get emscripten_set_main_loop to work on it's own. But as soon as I combine it with my code that has some EM_ASM_INT calls, WebGL calls (emscripten_webgl_create_context, emscripten_webgl_make_context_current, emscripten_webgl_get_current_context, emscripten_webgl_enable_extension, emscripten_set_webglcontextlost_callback, emscripten_set_webglcontextrestored_callback, emscripten_set_resize_callback), and the boiler-plate open gl stuff (glCreateProgram, glLinkProgram, etc.) I get the following error:

```
SCRIPT5007: Unable to set property '0' of undefined or null reference
```

Things I've tried:

- Calling the SML function before my code initializes WebGL: fail
- Calling the SML function after my code initializes WebGL: fail
- Calling the SML function from an async callback after a delay: fail
- Calling the _arg SML variant: fail
- Calling the SML function and not initializing WebGL: success (but no WebGL)

**Comment by kripken** [comment]
I don't have any idea what could cause such problems. It might help to take a look at examples in the test suite that combine WebGL with the main loop (e.g. a search finds `tests/gl_textures.cpp`). Those should all work, so comparing how they differ from your case might help. If nothing pops up, I'd try to create a small testcase showing the issue.

**Comment by JeffMushmo** [comment]
The issue seems to have gone away since I removed the LEGACY_GL_EMULATION compiler flag. Which makes me feel better that I'm not using an async callback for frame rendering.
