### ISSUE TITLE
Do we have any plan to support ES6 syntax?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6606]
It seems like the optimization phase is not support ES6 when compressing JavaScript code with "uglifyjs". I think we can have a pre-process to translate user side's ES6 code into ES5 or lower version JavaScript code since ES6 style JavaScript is widely used now.

**Comment by kripken** [comment]
Yes, we really need to do that, but so far no one has had the time. The main issue is #6000 

Closing this as a duplicate of that one.
