### ISSUE TITLE
Where can I find the implementation of this “emscripten_asm_const_int” function?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6610]
https://github.com/kripken/emscripten/blob/ac37dd06b640d0dd8992a53efd1bb6e9150bdb41/system/include/emscripten/em_asm.h#L153

**Comment by kripken** [comment]
Those methods are handled in a special way by the compiler, internally. The first part is

https://github.com/kripken/emscripten-fastcomp/blob/incoming/lib/Target/JSBackend/CallHandlers.h#L790

and the compiler emits metadata (in JSBackend.cpp) that is then received and processed by the calling script (emscripten.py).

**Comment by Becavalier** [comment]
@kripken  Make sense, thanks!
