### ISSUE TITLE
Webassembly configuring stack location when using emcc

### ISSUE THREAD

**Issue by anandanand84** [kripken/emscripten#6611]
I use the below emcc command with flags `STACK_START`

```emcc -O3 -s WASM=1 -s STACK_START=65536 -s TOTAL_STACK=131072 -s GLOBAL_BASE=10490 -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap"]'```

but that doesnt seem to be store the stack variables in those memory location. I also tried to configure using the below imports in js with no luck.

```
var imports = {
            env: {
                abortStackOverflow: () => { throw new Error('overflow'); },
                memory: memory,
                STACKTOP: 0,
                STACK_MAX: 128,
            },
            global : { NaN : 0, Infinity: Infinity }
        };
```

How should we configure the Stack location in the memory so that I wont accidentally update the stack location in the memory from javascript?

**Comment by kripken** [comment]
There will be a global STACKTOP inside wasm, which contains the stack pointer. In other words, the stack pointer is not stored in memory, but in a wasm global. You can call `stackAlloc()/stackSave()/stackRestore()` to get and free stack space for JS if you need that. Inside wasm, you can just read, increment and decrement STACKTOP directly.

Note that STACK_START is mostly a debugging setting, as mentioned in the comment in settings.js. It puts the stack there if it can, but if there is already something at that address, it won't. (And to avoid confusion, it would put the stack itself there, not the stack pointer itself, as mentioned before.)

**Comment by anandanand84** [comment]
ok, so this is what I am trying to do. I am trying to add an array of values in the imports.env.memory from javascript so I can do some calculation in wasm(c code). I was looking for stack start so I can be sure that I am not overwriting in the stack memory location from the javascript in this process. Basically I am trying to manage all the memory from the javascript. 

Looks like I have to allocate memory from the c code get the address and then update the values in that from javascript.

**Comment by kripken** [comment]
Yes, allocating from C is usually easiest. Otherwise, calling `stackAlloc` from JS is pretty easy too.
