### ISSUE TITLE
--use-preload-plugins is no-op?

### ISSUE THREAD

**Issue by Beuc** [kripken/emscripten#6622]
It seems there is a logic error in `--use-preload-plugins`, more precisely in `imagePlugin_handle`:

```
$ echo "int main(void) {}" > whatever.c
$ emcc --preload-file screenshot.jpg --use-preload-plugins whatever.c -o test.html

> FS.readFile('screenshot.jpg')
Uint8Array(50759) [ 255, 216, 255, 224, 0, 16, 74, 70, 73, 70, … ]
> Module.preloadPlugins[0].canHandle('screenshot.jpg')
true
> Module.preloadPlugins[0].handle(FS.readFile('screenshot.jpg'), 'screenshot.jpg', function(byteArray) {console.log(byteArray);})
Uint8Array(50759) [ 255, 216, 255, 224, 0, 16, 74, 70, 73, 70, … ]
```

The decoding function returns the original array (with the 255,216,255 JPEG header), rather than the raw RGBA pixel data from the canvas (or at least that's what I understand it should do).

This causes a `FS_createPreloadedFile -> createPreloadedFile -> createDataFile` with the exact original bytes, hence the no-op.

Note: the current testsuite uses `--use-preload-plugins` but only with "screenshot.not" filenames which are not processed, and with direct calls to `emscripten_run_preload_plugins`* in the C code, hence the transparent decoding offered by that option is not tested.

Can you confirm?

**Comment by kripken** [comment]
I think in the FS it will still contain the file data. That way, if you check the file size, or check the first few bytes to see what type it is, it all looks "normal" to the program. But when it does IMG_Load or some other method to get the image pixels, then we magically provide the pixels decoded by the browser's codecs.

I'm pretty sure we test this, for example `test_sdl_ogl` seems to use preload plugins with a PNG file. I didn't read more carefully than that, though - am I missing something?

Good idea to improve the docs here if they are confusing!

**Comment by Beuc** [comment]
I missed test_sdl_ogl - maybe I only checked SDL2 tests and not SDL1 :)
This one apparently tests --use-preload-plugins, unless STBI is used first.

Maybe it's best if --use-preload-plugins leaves the FS untouched, however there are 2 issues:

- There is no need to overwrite the original file with the exact original data; this code looks like the original intent was to write the decoded data on disk. If we keep the current behavior, I can instead patch to remove this no-op overwrite (and have the documentation point to `emscripten_get_preloaded_image_data`).

- Applications need to explicitely check Module['preloadedImages']/['preloadedAudios']; e.g. upstream SDL2_image does not do that (but we could push the port patch upstream). On the other hand, if the decoded data were written on the FS, applications would still need to handle raw RGBA, unless we transparently wrap it as a BMP (which is what I initially expected).
I didn't check how audio preload currently works though.

**Comment by kripken** [comment]
Oh, it writes the same data back to the FS? Yeah sounds like a good idea to avoid that unnecessary work.

I think C code can call `emscripten_get_preloaded_image_data` to get the pixels, instead of accessing `Module` directly? And looks like it is used in SDL2_image, 
https://github.com/emscripten-ports/SDL2_image/blob/cf14dc78dded8ffee3bc549469da10fbcb7d1b90/IMG.c#L134 - maybe that doesn't work for some reason?

**Comment by kripken** [comment]
I see. We should update from upstream, then. Would also be good to get our changes upstream if possible. Might be worth filing an issue on those in the emscripten-ports SDL2_image repo - could be relevant people would see it there better than here.

**Comment by Beuc** [comment]
I added documentation based on this conversation at #6716 .
I was mistaken, the file's original/non-decoded form is written just once on the FS (as part of the preloading); --use-preload-plugins is tested through test_sdl2_image and test_sdl2_image_jpeg. No patch needed. Apologizes for the confusion, hopefully the doc patch will make things clearer ^_^
Also referenced the SDL2_image patch upstream at https://bugzilla.libsdl.org/show_bug.cgi?id=4203 .

**Comment by kripken** [comment]
Great, thanks for the investigation and the PR! I think we can close this now.
