### ISSUE TITLE
How does the following piece of code interact with Emscripten's pre-built libc library?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6623]
As I known, Emscripten has a series of pre-built libc library which based on "musl", so how does the following piece of code interact with those pre-built libc libraries? Here you can see that I import "math.h" which is a part of standard C library file here. Sorry for this newbie question since I had never used "musl" before.

```c
#include <math.h>
#include <stdio.h>

int main (int argc, char **argv) {
  printf("%f\n", cos(10));
  return 0;
}
```

Also, here I find two folders:
https://github.com/kripken/emscripten/blob/incoming/system/include/libc/math.h
https://github.com/kripken/emscripten/tree/incoming/system/lib/libc/musl/src/math

Can I consider that the second folder contains the implementation of the function defined in the first folder's C header files?

**Comment by kripken** [comment]
In detail, the compiler will see that `cos()` call and also that it is not implemented in the source files you compiled. It finds that it is implemented in musl, and then builds musl if it wasn't already. That includes the `math/` dir you linked to, which indeed contains `cos()` there. And then the compiler links in musl, which brings in the musl code for that function.

**Comment by Becavalier** [comment]
@kripken Thanks! I get it.
