### ISSUE TITLE
How does the backend know the type of the function pointer which I use in "addFunction"？

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6630]
How does the Fastcomp backend know the function type I imported by "addFunction"? A specific case shows below:

"post-script.js": which the content will be appended to the end of the glue script: 
```JavaScript
var newFuncPtr = Module.addFunction(function(num) {
  console.log(`Hello ${num} from JS!`);
}, "vi");
```

"c++":
```c++
extern "C" void EMSCRIPTEN_KEEPALIVE wrapper (int fp) {
  using fpt = void (*)(int);
  fpt f = reinterpret_cast<fpt>(fp);
  f(7);
}
```

".wat":
I see the "wrapper" function redirect-call the function stored in table, which name is "jsCall_vi". As you can see, this function has the signature postfix indicate the called JavaScript function has value return and also has one "int" parameter. But how does the compiler backend know what kind of "jsCall_[sig]"  should to be called?

**Comment by aheejin** [comment]
I'm not sure if I understand your question. Your C++ code uses a function pointer of type `void (*)(int)`. Doesn't that have enough info to tell the compiler backend that the function type is 'vi'?

**Comment by Becavalier** [comment]
Thanks for you reply @aheejin  I think I misunderstand something, much clear for now. : )
