### ISSUE TITLE
Malloc.asm._malloc undefined

### ISSUE THREAD

**Issue by nikkolasg** [kripken/emscripten#6632]
Hi there,

I am running into the following error when I `Module._malloc`.This error has been making me crazy ...
```js
TypeError: Module.asm._malloc is undefined
```
When I tried to reproduce it with the same compiled code on a minimalistic example, it worked. I can't figure out why it does not work with my main code. 
The way I am using emscripten is 
1. Compiling the code with `emcc -s ASSERTIONS=1 -s WASM=1 -O2 -o gmp.js gmp.c libgmp.a`
2. Writing the base64 encoded wasm output file into a JS file like
```js
function _base64ToArrayBuffer(base64) {{
    var binary_string =  window.atob(base64);
    var len = binary_string.length;
    var bytes = new Uint8Array( len );
    for (var i = 0; i < len; ++i) {{
        bytes[i] = binary_string.charCodeAt(i);
    }}
    return bytes.buffer;
}}
var WasmBytes = _base64ToArrayBuffer(\"{}\");
```
3. Importing first the file containing the `WasmBytes` variable, then `gmp.js` then my file that uses the module in the following way:
```js
Module['wasmBinaryFile'] = WasmBytes;
Module['onRuntimeInitialized'] = function() {
    wasmModExpExponents = Module._modexpExponents;
    wasmInitDone = true
    console.log("WASM compiled !");
}
```
In the callback, I can't call `Module._malloc` without getting the error mentionned above.

Again, using almost the same settigs in my minimalistic experiment, I can't reproduce the error (I'm even using the same output from emscripten).

Any idea ? Could it be that another framework I am loading is messing up with emscripten ? I have no clue...

Thanks a lot.

**Comment by kripken** [comment]
It could be that the optimizer is removing it since it's not exported, see

https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-functions-in-my-c-c-source-code-vanish-when-i-compile-to-javascript-and-or-i-get-no-functions-to-process

You may need something like `-s "EXPORTED_FUNCTIONS=['_main', '_malloc']"`

**Comment by nikkolasg** [comment]
I re-started my project from scratch including every files one by one and it worked. No idea what was the reason, but I'm now going forward with this.

Thanks a lot for your answer though, I have learned something new :)
