### ISSUE TITLE
test_core.test_em_js failing in C-only mode

### ISSUE THREAD

**Issue by sbc100** [kripken/emscripten#6646]
The output of the llvm-backend generates a wasm file that doesn't validate so its probably actually an LLVM issue.  But I thought I post here in cast @jgravelle-google has any idea.

Also @binji might be able to see what the compiler has done wrong here.

**Comment by sbc100** [comment]
Here is the bad object file:
[emcc-llvm-backend-output.o.zip](https://github.com/kripken/emscripten/files/2074709/emcc-llvm-backend-output.o.zip)
```
wasm-validate /tmp/emscripten_temp/emcc-llvm-backend-output.o 
/tmp/emscripten_temp/emcc-llvm-backend-output.o:00000fe: error: mutable globals cannot be imported
/tmp/emscripten_temp/emcc-llvm-backend-output.o:000041f: error: type mismatch in call, expected [i32] but got []
/tmp/emscripten_temp/emcc-llvm-backend-output.o:000042b: error: type mismatch in i32.store, expected [i32, i32] but got [i32]
/tmp/emscripten_temp/emcc-llvm-backend-output.o:000056f: error: type mismatch in i32.store, expected [i32, i32] but got [i32]
/tmp/emscripten_temp/emcc-llvm-backend-output.o:00005a9: error: type mismatch in i32.store, expected [i32, i32] but got [i32]
/tmp/emscripten_temp/emcc-llvm-backend-output.o:00005d3: error: type mismatch in function, expected [] but got [i32]
```

**Comment by sbc100** [comment]
Looks like its causes by any EM_JS function that take no args.  

I guess its probably the (void) vs (...) function?

**Comment by sbc100** [comment]
Looks like this is an instance of: https://github.com/WebAssembly/tool-conventions/issues/16

I can repro the same issue with this simple code:
```
extern int foo();

int main() {
  return foo();
}
```
llvm generates bad wasm code in the case.

**Comment by jgravelle-google** [comment]
Yeah the correct C syntax here is `EM_JS(void, foo, (void), {...})`
But we should handle this sort of thing in general
