### ISSUE TITLE
'establishStackSpace is not defined' when running emcc with -s WASM=1 -s USE_PTHREADS=1 -Oz 

### ISSUE THREAD

**Issue by Auron52** [kripken/emscripten#6668]
See the attached basic sample. The problem can be reproduced using Firefox Nightly or Chrome Canary with the necessary options for threading and loading index.html. Also included a cmake file to make it simpler to reproduce by building with the latest Emscripten incoming branch.
Note that removing -Oz avoids the error, so I assume that is the first place to look. This is possibly related to the missing warning mentioned in https://github.com/kripken/emscripten/issues/6581, since that also is resolved by removing -Oz.
[SimpleWasmThread.zip](https://github.com/kripken/emscripten/files/2085962/SimpleWasmThread.zip)
Thanks,
David

**Comment by dschuff** [comment]
I think this is the same issue I found in #6405. I'll pick it up again.

**Comment by dschuff** [comment]
I think this is fixed with #6704, feel free to reopen if not.
