### ISSUE TITLE
What's the usage of "(register_vector()) and (register_map())" in "Emscripten Embind"?

### ISSUE THREAD

**Issue by Becavalier** [kripken/emscripten#6689]
@chadaustin Can you please help? The official wiki talks about these two methods does't make any sense.

FYI:
![image](https://user-images.githubusercontent.com/8282020/41457117-2d6715c8-70b5-11e8-97b0-9799ab8614f8.png)

**Comment by chadaustin** [comment]
@Becavalier To use any `std::vector<T>` or `std::map<K, V>` in a C++ API, you have to register it in your bindings. If you return a `std::vector<std::string>` from a function, perhaps, you need to call `register_vector<std::string>("vector<string>")` in your bindings.

Does that help?

**Comment by Becavalier** [comment]
@chadaustin This make sense! Thanks!
