### ISSUE TITLE
EMSCRIPTEN_KEEPALIVE seems to make no difference, as everything gets exported when compiling with SIDE_MODULE

### ISSUE THREAD

**Issue by boyanio** [kripken/emscripten#6709]
Hello,
I am writing a small C program with some functions I want to export to JS. I compile the program with `SIDE_MODULE=1`. Before I used to mark functions I want to export with `EMSCRIPTEN_KEEPALIVE`, but it seems everything gets exported anyway. If I remove the marker, my functions get exported anyway. Is there anything I am missing? How to limit the exported functions/variables?

**Comment by kripken** [comment]
SIDE_MODULE (and MAIN_MODULE) disable dead code elimination by default, assuming you may want code linked to it to want to access any of the contents. But there is a mode 2 for both, where dce works, see `src/settings.js`. So `-s SIDE_MODULE=2` should do what you want.

**Comment by boyanio** [comment]
Thanks, `-s SIDE_MODULE=2` works fine indeed. Now I run the following command:

`emcc -Os index.c -s SIDE_MODULE=2 -s ONLY_MY_CODE=1 -o index.wasm -g`

In the generated wast file, there is `__post_instantiate` exported too. Am I supposed to call this function after initializing the wasm module?

**Comment by kripken** [comment]
Yes, that method should be called by the loader. More details in https://github.com/WebAssembly/tool-conventions/blob/49c5b0d84a7177b279c81f85426b790c21fa7b62/DynamicLinking.md#L33 and you can also see the emscripten loader code which is here: https://github.com/kripken/emscripten/blob/incoming/src/support.js#L238

**Comment by boyanio** [comment]
Thanks, this gives me some more information. I just wonder, is it by design that Emscripten produces wasm dynamic library? In this scenario, I would have just expected the output wasm file to contain my exported functions and nothing else.

**Comment by kripken** [comment]
Not sure I understand the question, SIDE_MODULE is defined as producing a dynamic library?

If you just want your exported functions and nothing else, then normal compilation (without SIDE_MODULE) should achieve that, in fully optimized builds (-O3, -Os, etc. - otherwise, in less optimized builds there is runtime code that is not needed).

**Comment by boyanio** [comment]
I see. My idea was, as I only want to produce a wasm file (no .js/.html), the only way to do it, seems to be by using `SIDE_MODULE`. But this option will add other things to the output (`__post_instatiate`), that my source code does not contain. This behavior seems to be by design :)

**Comment by kripken** [comment]
I see. There are docs on standalone wasm like that, see here: https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone#let-the-optimizer-remove-the-runtime

In general, JS is needed alongside the wasm, but if you write only limited computational code, then as described there the optimizer can remove everything but your own code. That's generally going to be more efficient than SIDE_MODULE, which also does relocation etc. as a full dynamic library.

**Comment by boyanio** [comment]
Thank you! Now it makes more sense to me what is happening :)
