### ISSUE TITLE
Can't get OpenGL working

### ISSUE THREAD

**Issue by darkoverlordofdata** [kripken/emscripten#6710]
I've tried running opengl tests such as test_glew, test_glfw and test_gfw3. They compile ok, and it says on the command line that they passed the test, but none of the tests actually display any graphic activity. Several do get an error message in the browser "Exception thrown, see JavaScript console", and when I look at the console I see that it fails on _glfwCreateWindow with 'Cannot read property value of null'.

I tried the tests/glbook examples, and I get compile warnings about unresolved references. When I try to run, I get the "Exception thrown, see JavaScript console", and the comsole says "missing function esInitContext" ... which was one of the unresolved references I got a warning about.

I'm not having issues with any other emscripten tests that I've tried, and I can get SDL code working, but not anything that uses OpenGL.

I'm compiling my open gl code thusly:
emcc hello.c -s WASM=1 -s USE_GLFW=3 -s FULL_ES3=1 -o hello.html

I've tried every combination of USE_GLFW and FULL_ESn, with and without WASM, but it makes no difference. What am I missing? Is OpenGL just not ready yet?

**Comment by kripken** [comment]
Perhaps WebGL is disabled in your browser? Does https://get.webgl.org/ work?

OpenGL is stable in emscripten, and the tests you mention are known to pass in at least firefox and chrome.

**Comment by darkoverlordofdata** [comment]
Well, I found this example - http://forums.4fips.com/viewtopic.php?f=3&t=1201#
and cut and pasted it and it works perfectly. IIt's using glut, but that shouldn't make a difference, they all work in desktop apps.

This is what worked:
emcc hello.cpp -std=c++11 -s WASM=1 -s FULL_ES2=1 -o hello.html

I retried the triangle demo in tests/glbooks using those same options and it still fails. At any rate, I was just looking for something that works to get to a starting point.  I've got that.

The glerror thread had me wondering if it was stable. The tests do pass on the command line - they fail in the browser. But if their headless, I guess that makes sense :)

**Comment by darkoverlordofdata** [comment]
I found the real problem with glbook. turns out all these 'es' library functions, like esInitContext, are not really a library, they are a set of files in another folder that also have to be compiled:

emcc Hello_Triangle.c ../../Common/esShader.c ../../Common/esShapes.c ../../Common/esTransform.c ../../Common/esUtil.c -s WASM=1 -s FULL_ES2=1 -o hello.html


There are so many opengl spinoff libraries I can't keep track of them. I assumed esInitContext was some GLES standard library, and per this issue, https://github.com/kripken/emscripten/issues/2808, it sounded like those unresolved symbol warnings can be ignored. 

Of course there is a make file that doesn't work on Windows. Its for X11.
