### ISSUE TITLE
#if ENVIRONMENT in shell.js is incorrectly processed

### ISSUE THREAD

**Issue by dlunch** [kripken/emscripten#6713]
Looking at generated js file compiled with `-s ENVIRONMENT=web`, I can see `#else ENVIRONMENT` block from shell.js, which seems wrong. 

I dig into some source code, `#if ENVIRONMENT` in https://github.com/kripken/emscripten/blob/e2453e12edc0bd7283e446b2ab0b9a74bda12bd8/src/shell.js#L49 is incorrectly evaluated as false. 

Preprocessor parsing at https://github.com/kripken/emscripten/blob/c5a455873a5ee84ac07961e06a3a58204e5813b2/src/parseTools.js#L68 expects integer value for #if clause, but the value of  `ENVIRONMENT` is a string, which evaluates as false.

**Comment by kripken** [comment]
Thanks @dlunch ! Yes, that code was just broken. I opened a PR with a fix: #6718

**Comment by kripken** [comment]
Fixed by that PR.
