### ISSUE TITLE
[Bug] -s ENVIRONMENT=web doesn't seem to work?

### ISSUE THREAD

**Issue by kkimdev** [kripken/emscripten#6717]
version: 1.38.6
Reproducing steps:

main.cpp
```c++
int main() {
}
```
```bash
em++ main.cpp -s ENVIRONMENT=web
```

To my understanding, the generated code should strip all the code for handling non-web environment, but a.out.js still has the following block.

```javascript
...
// The environment setup code below is customized to use Module.
// *** Environment setup code ***
var ENVIRONMENT_IS_WEB = false;
var ENVIRONMENT_IS_WORKER = false;
var ENVIRONMENT_IS_NODE = false;
var ENVIRONMENT_IS_SHELL = false;

// Three configurations we can be running in:
// 1) We could be the application main() thread running in the main JS UI thread. (ENVIRONMENT_IS_WORKER == false and $// 2) We could be the application main() thread proxied to worker. (with Emscripten -s PROXY_TO_WORKER=1) (ENVIRONMENT$// 3) We could be an application pthread running in a worker. (ENVIRONMENT_IS_WORKER == true and ENVIRONMENT_IS_PTHREA$

if (Module['ENVIRONMENT']) {
  if (Module['ENVIRONMENT'] === 'WEB') {
    ENVIRONMENT_IS_WEB = true;
  } else if (Module['ENVIRONMENT'] === 'WORKER') {
    ENVIRONMENT_IS_WORKER = true;
  } else if (Module['ENVIRONMENT'] === 'NODE') {
    ENVIRONMENT_IS_NODE = true;
  } else if (Module['ENVIRONMENT'] === 'SHELL') {
    ENVIRONMENT_IS_SHELL = true;
  } else {
    throw new Error('Module[\'ENVIRONMENT\'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.');
  }
} else {
  ENVIRONMENT_IS_WEB = typeof window === 'object';
  ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';
  ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function' && !ENVIRONMENT_IS_WEB && !ENVIRO$
  ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;
}
...
```

**Comment by kkimdev** [comment]
It seems like this `#if ENVIRONMENT` block was stripped out https://github.com/kripken/emscripten/blob/e2453e12edc0bd7283e446b2ab0b9a74bda12bd8/src/shell.js#L49-L55 and instead the `#else` path is taken.

**Comment by kkimdev** [comment]
@kripken

**Comment by kripken** [comment]
Thanks @kkimdev! Yes, that code was just broken. I opened a PR with a fix: #6718

**Comment by kripken** [comment]
Fixed by that PR.

**Comment by kripken** [comment]
Thanks @klunko, I opened #6921 to update those docs.

**Comment by chase-moskal** [comment]
hello! i'm trying to fix chase-moskal/webp-hero#17

i've added `-s ENVIRONMENT=web` in attempt to stop emscripten from adding  node-specific checks into the javascript output (which is apparently breaking some angular/webpack build stuff regarding "fs" module environment checks)

however, emscripten gives me this error?

```
Traceback (most recent call last):
  File "/work/emsdk-portable/emscripten/1.37.22/emcc", line 13, in <module>
    emcc.run()
  File "/work/emsdk-portable/emscripten/1.37.22/emcc.py", line 882, in run
    exec 'shared.Settings.' + key + ' = ' + value in globals(), locals()
  File "<string>", line 1, in <module>
NameError: name 'web' is not defined
```

that error traces back to this line: https://github.com/emscripten-core/emscripten/blob/37b3124e757c1d5b2468d0137f01122fbef9d960/emcc.py#L882

what's wrong?

if i can't figure it out soon, i'll open a new issue about it

cheers

**Comment by kripken** [comment]
@chase-moskal - which version of emscripten is that? older versions used `exec` as on that line, but newer ones have new parsing code. The old code might need quotation marks (`ENVIRONMENT="web"` or something like that - but best to upgrade to latest).

**Comment by chase-moskal** [comment]
@kripken — emscripten sdk-1.37.22-64bit

thanks for the advice, i will attempt adding quotes, and will also reattempt an upgrade (google's libwebp had an issue with upgrading last i tried)

**Comment by chase-moskal** [comment]
@kripken —thanks to your help, i have now solved my problem :+1: :tada: 

the problem: i wasn't correctly escaping the value such that it included the necessary quotes

here's how i fixed my problem, by correctly setting the `ENVIRONMENT` to `web` in a [CMakeLists.txt](https://github.com/chase-moskal/webp-hero/blob/master/libwebp/source/CMakeLists.txt#L548) i'm working with:
- i had to take this funky bit
    ```js
    PROPERTIES LINK_FLAGS
               "-s EXPORTED_FUNCTIONS='[\"_WebpToSDL\"]' -s INVOKE_RUN=0 -s ENVIRONMENT=\"'web'\" -s TOTAL_MEMORY=67108864 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 0 \
       -s EXTRA_EXPORTED_RUNTIME_METHODS='[\"cwrap\"]'")
    ```
- and carefully add ` -s ENVIRONMENT=\"'web'\"` — notice the single quoted `'web'` wrapped in escaped double-quotes `\"`
    ```js
    PROPERTIES LINK_FLAGS
               "-s ENVIRONMENT=\"'web'\" -s EXPORTED_FUNCTIONS='[\"_WebpToSDL\"]' -s INVOKE_RUN=0 -s ENVIRONMENT=\"'web'\" -s TOTAL_MEMORY=67108864 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 0 \
       -s EXTRA_EXPORTED_RUNTIME_METHODS='[\"cwrap\"]'")
    ```

cheers!

**Comment by chase-moskal** [comment]
hmm.. despite all this, the output still contains the node-only code that is breaking webpack

it appears that the bug described by this issue does affect `emscripten sdk-1.37.22-64bit` that i am using, so i will be forced to hazard an upgrade

**Comment by chase-moskal** [comment]
upgrade to emscripten `sdk-1.38.30-64bit` was successful :tada: :+1: 

only change i had to make, was to add ` -s WASM=0 -s LEGACY_VM_SUPPORT=1` to my compilation options, to prevent the output from looking for a `.wasm` file -- i found this out by reading the emscripten release notes for breaking changes

thanks again for the help
