### ISSUE TITLE
[question] why is the minimum for TOTAL_MEMORY already 16MB?

### ISSUE THREAD

**Issue by gerdstolpmann** [kripken/emscripten#6719]
The background of my question is that this value is fairly large for my application - I'd rather have something like 1MB or so (I'm not targeting the browser but a wasm-backed application server with really many small instances which should better start small - using more CPU cycles for growing is completely acceptable). I found a check in `emcc.py` for the hard-coded value of 16MB, and this looks arbitrary at the first glance. Maybe inherited from asm.js? Can we remove or lower the minimum for wasm?

**Comment by kripken** [comment]
Thanks for filing, yeah, the 16MB limit comes from asm.js - we just forgot to remove it... Fix in #6720

**Comment by kripken** [comment]
(In wasm, the only requirement should be that the memory size is a multiple of 64K. You do also need to make sure the stack size is small enough to fit in the smaller memory, though, and the default stack size is 5MB for linux compatibility.)

**Comment by gerdstolpmann** [comment]
Thanks for the quick reaction. In the meantime, I also just commented the check in emcc.py out, and everything seems to run fine for me (also lowered the stack as you suggest).
