### ISSUE TITLE
./emsdk install latest : Installation failed

### ISSUE THREAD

**Issue by pierreglibert** [kripken/emscripten#6723]
Hi community :)
I have some loading error ...
I'm on mac osx 10.13.5 & python 2.7.15.
Can you help me please ?

```
$ ./emsdk install latest

Fetching all tags from Emscripten Github repository...
Done. 134 tagged releases available, latest is 1.38.6.
Fetching all tags from Binaryen Github repository...
Done. 61 tagged Binaryen releases available, latest is 1.38.6.
Fetching all precompiled tagged releases..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_32bit/index.txt': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/index.txt': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
Installing SDK 'sdk-1.35.0-64bit'..
Installing tool 'clang-e1.35.0-64bit'..
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten-clang_e1.35.0.tar.gz': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
Installation failed!

$ python --version

Python 2.7.15
```

**Comment by Becavalier** [comment]
@pierreglibert 

This error was caused by did't passing https certs related verifications, you can bypass this error by using default https context, add the following code into "emsdk", and try the same command again.

```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

These two lines of code will globally disabling the verification of https certs, though it's not recommend to use, it did work.

**Comment by kripken** [comment]
This may also be related to #6275 , if so then using a newer python may fix it.

**Comment by pierreglibert** [comment]
Hi @Becavalier & @kripken :)
The solution of @Becavalier works. 
Thanks ! 👍

**Comment by Becavalier** [comment]
@pierreglibert You're welcome, issue can be closed now.

**Comment by erik-larsen** [comment]
I just ran into this issue installing emsdk on a new Mac, even with Python 2.7.15 (the latest Python 2.7) pre-installed.  I think there is a better solution than disabling certificate verification.    Here is what worked for me:

1. Install Python 2.7.15 on Mac
2. **Go to /Applications/Python 2.7 and run "Install Certificates.command"**
3. Install emsdk following the normal steps at https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html.

Step 2 is the key, and the reasoning behind it is explained in /Applications/Python 2.7/ReadMe.rtf, under section [CHANGED in 2.7.15].  Essentially this will "install a curated bundle of default root certificates".

@kripken If someone else can confirm this fixes emsdk installs on fresh Macs, perhaps it could be added to https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#mac-os-x.

**Comment by kripken** [comment]
Thanks @erik-larsen, yeah, would be good if others can confirm this, and then we should add it to those docs.

**Comment by weewam** [comment]
@erik-larsen Thank you so much for this, worked perfectly for me 🥇

**Comment by AlohaWorld** [comment]
I found an easy way on windows to solve this problem.
1. Install anaconda with its default python build
2. open anaconda prompt
3. execute emsdk install latest

The default python build in anaconda suite is of version 3.x

**Comment by mvnrc** [comment]
> @pierreglibert
> 
> This error was caused by did't passing https certs related verifications, you can bypass this error by using default https context, add the following code into "emsdk", and try the same command again.
> 
> ```python
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
> 
> These two lines of code will globally disabling the verification of https certs, though it's not recommend to use, it did work.

I also had to replace the python version to **3** to bypass the problem:
`#!/usr/bin/env python3`

**Comment by hixus** [comment]
> I just ran into this issue installing emsdk on a new Mac, even with Python 2.7.15 (the latest Python 2.7) pre-installed. I think there is a better solution than disabling certificate verification. Here is what worked for me:
> 
> 1. Install Python 2.7.15 on Mac
> 2. **Go to /Applications/Python 2.7 and run "Install Certificates.command"**
> 3. Install emsdk following the normal steps at https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html.
> 
> Step 2 is the key, and the reasoning behind it is explained in /Applications/Python 2.7/ReadMe.rtf, under section [CHANGED in 2.7.15]. Essentially this will "install a curated bundle of default root certificates".
> 

I had also run the install with "python ./emsdk install latest" not just "./emsdk install latest" as it seems to default to system provided python.

**Comment by StupidZhe** [comment]
> @pierreglibert
> 
> This error was caused by did't passing https certs related verifications, you can bypass this error by using default https context, add the following code into "emsdk", and try the same command again.
> 
> ```python
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
> 
> These two lines of code will globally disabling the verification of https certs, though it's not recommend to use, it did work.

IT WORKS! THANKS!

**Comment by megamindbrian** [comment]
Worked with ```python ./emsdk install latest```.

**Comment by liushuaidi** [comment]
> @pierreglibert
> 
> This error was caused by did't passing https certs related verifications, you can bypass this error by using default https context, add the following code into "emsdk", and try the same command again.
> 
> ```python
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
> 
> These two lines of code will globally disabling the verification of https certs, though it's not recommend to use, it did work.

you should put the code into emsdk.py
