### ISSUE TITLE
Is EMTERPRETIFY_ASYNC + SIDE_MODULE supported?

### ISSUE THREAD

**Issue by Beuc** [kripken/emscripten#6730]
It does not look so, but I've been wrong, so I'm just making sure before updating
https://github.com/kripken/emscripten/wiki/Linking
:)

- WASM=0 + EMTERPRETIFY + EMTERPRETIFY_ASYNC + SIDE_MODULE : compiles, but when calling an async function from the MAIN_MODULE the emterpreter fails to save/load the stack (non-emterpreter functions such as `ftCall_v` are present).
- WASM=1 + EMTERPRETIFY + EMTERPRETIFY_ASYNC + SIDE_MODULE : compilation fails with "error in validating output"

**Comment by kripken** [comment]
Honestly I think no one has tried those combinations before :) From those errors it sounds like some work would be required for them.

**Comment by Beuc** [comment]
Thanks for confirming!
(I'm working on a nasty program with a complex control flow, this pushes me in uncommon situations.)
