### ISSUE TITLE
missing glGetInternalformativ

### ISSUE THREAD

**Issue by ryhor-spivak** [kripken/emscripten#6733]
Emscripten doesn't provide [glGetInternalformativ](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glGetInternalformativ.xhtml) gl es 3.0 function in USE_WEBGL2=1 mode, althorugh it is available in WebGL 2 as [getInternalformatParameter](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/getInternalformatParameter)

**Comment by kripken** [comment]
Hopefully this is easy to add. The location for the code is in `src/library_gl.js`.
