### ISSUE TITLE
enlargeMemory failed!

### ISSUE THREAD

**Issue by li20190** [kripken/emscripten#6736]
In my program,  it uses a lot of files and has frequent memory allocation and release actions. When I use dlmalloc(the default malloc option), the program will be a message indicating the failure of the enlargedMemory after   running for a period of time.  I think the memory action is too frequent, leading to memory fragmentation,  thus causing the call to enlargeMemory, but the actual memory required by the program is less than 1G.

Later I tried SPLIT_MEMORY, but in this mode we couldn't read the files in Packaging Files,  and this mode cann't compatible with wasm, We used file_packager.py to pack the files and use the --no-heap-copy flag.

Emmalloc also tried, but it does not work.

Is it possible to allocate memory directly on demand without using a memory pool? How can I do this in emscripten?

**Comment by li20190** [comment]
I also try TOTAL_MEMORY, but it has same issue like dlmalloc!

Is it possible to create an arraybuffer every time malloc is called, I don't know if this is possible, and if so, what should I do?

**Comment by kripken** [comment]
Emscripten behavior is similar to 32-bit C/C++/Rust, etc. - memory fragmentation can be a real problem in long-running programs.

dlmalloc is a pretty good allocator, so if it can't manage to avoid fragmentation, it's not clear a better allocator would, for your program. Often what people end up doing is just avoid malloc/free and use a custom arena allocator of some sort, but that usually requires redesigning the application.

**Comment by li20190** [comment]
@kripken  Thank you very much.

 It may take a month or more to redesign the application.

Can I directly allocate memory by the browser? This is better than allocating a large chunk of memory at once, and of course this may be slower than pooling method.

Is there any other way?

**Comment by kripken** [comment]
SPLIT_MEMORY is the closest option we have. You can use it with files - you might need a larger chunk size, though, or to split the files into separate packages (we may currently load the package all at once - that could easily be improved). But fragmentation remains a risk there (less with smaller chunks, more with larger).

Another option is to try [cheerp](https://www.leaningtech.com/cheerp/), which has a mode in which each C++ object is a JS object. The main costs there are: porting is harder (some C++ does not work), it's slower, and their licensing model (dual license: GPL2 or paid commercial).

**Comment by li20190** [comment]
@kripken   Thank you very much.

When I used emscripten, I found that programs compiled with g0 are running faster in Chrome than O2 or O3. Running fps with g0 is about 50, but fps is down to 10 with Ox, but in Firefox no problems,
Is this a Chrome bug or does Chrome require special compilation options?

Do you have a plan for a new approach to memory management, and if so, when does it begin?

**Comment by kripken** [comment]
If you see a program running faster without an optimization level specified (with or without `-g0`) compared to -O2 or above, that sounds like a serious bug in Chrome - can you create a testcase to file a bug with?

There may be some memory management changes over time, the wasm community has discussed standardizing stuff like
 * mmap for wasm Memories. That would let us free ranges of memory, like a native program. However, in 32-bit it is still not a complete solution for fragmentation, just like in a native program.
 * wasm64, a version of wasm with 64-bit pointers. That would avoid fragmentation in the same way that native 64-bit programs can.

**Comment by li20190** [comment]
@kripken Thank you very much.

Yes, I can, it takes some time to build the server and the environment, but I don't know if the site can be accessed abroad.

I will send you a link until I get it done, now I run it in LAN.

**Comment by li20190** [comment]
@kripken   I'm sorry for my reply about performance, I confused Chrome and Firefox, the fact is the program is faster in Firefox without optimization than in Chrome with Ox flag.  The program in Chrome is extremly slow, but in Firefox, it's almost as fast as native app.

**Comment by li20190** [comment]
@kripken Thank you very much!
According to your suggestion, I solved this performance problem:
I used the Chrome Profiler to analyze the program and found that it was actually caused by glGetError.
glGetError is slow in Chrome, and then I removed the glGetError call.

This link is our demo, it's a temp site on Alibaba cloud:
http://47.95.216.137

Main page loading is very slow, about 2 minutes or more,it must download a file package of about 30M ;
after main page loaded, you will see an elevator scene.
Clicking "Car[X]" button to load a new scene, you must wait for the scene loaded  before you can click another "Car[X]" button.
The "goto[X]" buttons are used to change camera position.

If you cann't access, please contact me: li20190@hotmail.com

**Comment by kripken** [comment]
Thanks for the link, seems to work well.

Anything left here, or can we close this?

**Comment by li20190** [comment]
Thank you for your replys!

I look forward to unlimited memory!
