### ISSUE TITLE
EMTERPRETIFY and % operator

### ISSUE THREAD

**Issue by Beuc** [kripken/emscripten#6738]
When trying to emterpretify Python 2.7, I got:
```
$ emcc main.c libpython2.7.a -s EMTERPRETIFY=1 ...
emscripten-incoming/tools/js-optimizer.js:2065
        default: throw 'yikes ' + node[1];
                 ^
yikes %
```

I could tame this error by supporting the '%' operator in function detectSign, e.g.:
```
        case '%': return ASM_FLEXIBLE;
```

Sadly I miss 2 items for a proper fix:
- reproduce with a simple test case; attempts with a trivial use of the C '%' operator (even with non-constants) does not trigger this case
- understand what ASM_FLEXIBLE/SIGNED/UNSIGNED/NONSIGNED exactly represent and pick the right one; the comments seem to indicate this depends on whether operands are of type 'double', which adds confusion, and the difference between UNSIGNED and NONSIGNED seems not intuitive :)
Any clue?

**Comment by kripken** [comment]
"Flexible" here means that something can be either signed or unsigned. Like say the constant "0" - it's ok to add that to either a signed or an unsigned value. "nonsigned" means not having a sign, that is, it's not an integer (which is either signed or unsigned).

For `%`, I think it should be like `/`, which is "nonsigned": that way it is properly not signed or unsigned for a float operation, and if it's an integer operation, there will be a signed or unsigned coercion on the outside which enforces that.

For a testcase, if it's hard to get one it's fine to fix this without one. But I'd take a look at the intermediate JS to see what's going on - perhaps the '%' doesn't arrive from compiled code, or arrives in a weird way? Seeing the surroundings might help clarify.

**Comment by Beuc** [comment]
The immediate surroundings (`node`) are:
```
binary,%,name,$393,unary-prefix,+,num,2
```
(`$393` may change depending on the code, e.g. `$202`)

The actual intermediate file seems to be removed on error and I don't see any instance of '%' in my /tmp/*.js.
I thought it was working on Emterpreter code rather than JS code - I'll have to look at this deeper.

Note: for completeness, I have had this warning for weeks when working with Python:
```
emcc: warning: cannot represent a NaN literal '0x5564756ccf20' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   %. = select i1 %68, double 0x7FF8000000000000, double 0xFFF8000000000000 in _Py_parse_inf_or_nan()
```
or
```
emcc: warning: cannot represent a NaN literal '0x56378e61de20' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   %. = select i1 %68, double 0x7FF8000000000000, double 0xFFF8000000000000 in _Py_parse_inf_or_nan() 
```
(even though Py_parse_inf_or_nan has no '%' in its code)
It shouldn't be related but there are 2 suspicious '%' occurrences in the error message.

**Comment by kripken** [comment]
Looks like it's doing `$var % (+2)` which is very odd.

Try EMCC_DEBUG=2 in the env, it should save all temp JSes in the temp dir (`/tmp/emscripten_temp`). Or, you can add more debugging in the js optimizer near the line that throws, like printing the function name etc.

**Comment by kripken** [comment]
(Those other warnings from LLVM with `%. = select` etc. are just `%` being used as an LLVM prefix, that's coincidental and unrelated.)

**Comment by Beuc** [comment]
I could find the code in xxx.js.orig.js, there are several occurrences of  `% +2;`.
```
 if ($200) {
  $201 = +Math_abs(+$$1128);
  $202 = $201 % +2;
  $203 = $202 == +1;
```

The functions in the Python source code that produce such a `% +2` output are float_pow, math_gamma, math_lgamma, math_pow.

**The minimal C test case I could get is:**
```
#include <math.h>
int main(int argc, char* argv[]) {
  return (fmod(argc, 2) == 1);
}
```
This needs to be compiled with `-s EMTERPRETIFY=1` and `-02` (or `-03`):
```
emcc test.c -s EMTERPRETIFY=1 -o test.html -O2
```

Result:
```
function _main(i1, i2) {
 i1 = i1 | 0;
 i2 = i2 | 0;
 return +(i1 | 0) % +2 == +1 | 0;
}
```

Without  `-02` there's no `+` in front of constants.
With `--js-opts 1` instead of  `-s EMTERPRETIFY=1` we can find `% +2` in the output but compilation succeeds.

This test case sounds dependent on earlier optimizations. Alternatively the test case could be an emterpretify-ready JavaScript file (with `// EXTRA_INFO`) fed to js-optimizer.js. What do you think?

-----

About signed/unsigned/nonsigned, I believe `%` **only works with integers operands** in C.
Do you confirm `ASM_NONSIGNED`?

**Comment by kripken** [comment]
Oh right, yeah, I think we were both confused. In JS it is valid to do a float % :) So it's not odd to see this. What's odd is we didn't notice this bug before...

Yeah, ASM_NONSIGNED, like for `/`.

**Comment by Beuc** [comment]
It's pretty rare for the compiler to output `% +2` or `% -2`, the sign is optimized out in both cases.

It seems this could be a decent test case:
```
// {{PRE_LIBRARY}}
// EMSCRIPTEN_START_ASM
// EMSCRIPTEN_START_FUNCS
// int main(int argc, char* argv[]) { return (fmod(argc, 2) == 1); }
function _main(i1, i2) {
 i1 = i1 | 0;
 i2 = i2 | 0;
 return +(i1 | 0) % +2 == +1 | 0;
}
// EMSCRIPTEN_END_FUNCS
// EMSCRIPTEN_END_ASM
// EMSCRIPTEN_GENERATED_FUNCTIONS: []
```
```
tools/emterpretify.py test.js.orig.js out.js '[]' '[]' '[]' 1 FROUND=1
```
I'll check if I can integrate it in the test suite.
