### ISSUE TITLE
Building NCurses. Emscripten Bug?

### ISSUE THREAD

**Issue by ilyaigpetrov** [kripken/emscripten#6766]
# Outdated
1. Install emscripten and download [NCurses 6.1](https://www.gnu.org/software/ncurses/).
2. Extract, cd to the archive root, run `emconfigure ./configure --enable-debug`, no significant errors.
3. `emmake make VERBOSE=1`
```sh-session
...
cd ncurses && make DESTDIR="" RPATH_LIST="/usr/lib" all
make[1]: Entering directory '/home/ilyaigpetrov/Repos/emsdk/hello/ncurses/src/ncurses-6.1/ncurses'
mawk -f ./tinfo/MKcodes.awk bigstrings=1 ./../include/Caps >codes.c
/home/ilyaigpetrov/Repos/emsdk/emscripten/1.38.6/emcc -o make_hash -DHAVE_CONFIG_H -DUSE_BUILD_CC -I../ncurses -I. -I../include -I./../include -DHAVE_CONFIG_H -I../ncurses -I. -I../include  -DNDEBUG   ./tinfo/make_hash.c -ldir
WARNING:root:emcc: cannot find library "dir"
/bin/sh -e ./tinfo/MKcaptab.sh mawk 1 ./tinfo/MKcaptab.awk ./../include/Caps > comp_captab.c
./tinfo/MKcaptab.sh: 55: ./tinfo/MKcaptab.sh: ./make_hash: Permission denied
Makefile:256: recipe for target 'comp_captab.c' failed
make[1]: *** [comp_captab.c] Error 126
make[1]: Leaving directory '/home/ilyaigpetrov/Repos/emsdk/hello/ncurses/src/ncurses-6.1/ncurses'
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
```
`vim ncurses/tinfo/MKcaptab.sh`
```
...
./make_hash 1 info $OPT1 <$DATA
...
```
Making as root doesn't help.
If you ignore this error and continue running `emmake make` then finally you will reach the end of build, but I couldn't get the output `ncurses.a` to work:
```sh-session
$ emcc hello.c -I./src/ncurses-6.1/include/ -L./src/ncurses-6.1/lib/ -lncurses
hello.c:1:10: fatal error: 'ncurses.h' file not found
#include <ncurses.h>
         ^~~~~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```
Any hints on compiling this are welcome.

**Comment by ilyaigpetrov** [comment]
It seems `make_hash` is created but can't be executed via `./make_hash` which gives permission denied. How to execute `make_hash`?
```sh-session
ncurses-6.1/ncurses$ file make_hash
make_hash: LLVM IR bitcode
ncurses-6.1/ncurses$ lli make_hash
lli: error creating EE: No available targets are compatible with this triple.

**Comment by ilyaigpetrov** [comment]
From `INSTALL`:
> BUILDING NCURSES WITH A CROSS-COMPILER
  Ncurses can be built with a cross-compiler.  Some parts must be built
  with the host's compiler since they are used for building programs
  (e.g., ncurses/make_hash and ncurses/make_keys) that generate tables
  that are compiled into the ncurses library.  The essential thing to do
  is set the BUILD_CC environment variable to your host's compiler, and
  run the configure script configuring for the cross-compiler.

>  The configure options --with-build-cc, etc., are provided to make this
  simpler.  Since make_hash and make_keys use only ANSI C features, it
  is normally not necessary to provide the other options such as
  --with-build-libs, but they are provided for completeness.

So what I did is replaced `$(BUILD_CC)` in `./ncurses/Makefile.in` for gcc for `make_hash` target, copied x86 `make_hash` to `make_hash_ex` and `make_keys` to `make_keys_ex`, replaced `./make_hash` on `./make_hash_ex` and `./make_keys` on `./make_keys_ex` in all the important scripts I found with `grep` and finally compiled it with some "cannot link" warnings.

My hello.c:
```c
#include <curses.h>

int main()
{
  initscr();      /* Start curses mode      */
  printw("Hello World !!!");  /* Print Hello World      */
  refresh();      /* Print it on to the real screen */
  getch();      /* Wait for user input */
  endwin();     /* End curses mode      */

  return 0;
}
```
Compiled with `emcc hello.c -L./lib -I./include -lncurses -s WASM=1 -o hello.html` and now I get:
`LinkError: WebAssembly Instantiation: Import #9 module="env" function="__nc_tinfo_fkeys" error: global import must be a number`

**Comment by ilyaigpetrov** [comment]
The bug is in the different implementation of `getenv`.
```c
#include <stdio.h>
#include <stdlib.h>

int main() {

  setenv("TERM", "xterm-new", 1);
  char* tname = getenv("TERM");
  printf("tname=%s\n", tname);
  getenv("HOME"); // BOOM!
  printf("tname=%s\n", tname);

  return 0;
}
```
The most expected output is:
> tname=xterm-new
tname=xterm-new

However the standard is tricky:
> The implementation of getenv() is not required to be reentrant.  The
string pointed to by the return value of getenv() may be statically
allocated, and can be modified by a subsequent call to getenv(),
putenv(3), setenv(3), or unsetenv(3). 

It means second `tname=` may be corrupted.
There are several issues about this on emscripten:

- https://github.com/kripken/emscripten/issues/4226 (getenv: Calling getenv deallocate string previously returned)
- https://github.com/kripken/emscripten/issues/5053 (getenv returns temporary strings?)

I wish emscripten adopted different implementation of getenv for better compatibility with other code bases.

**Comment by ilyaigpetrov** [comment]
# Journey Continues
This allows to override `getenv` and compile `hello.c` without that EVN.TERM garbling:
```bash
emcc ./hello.c -L ./ncurses-6.1-llvm/lib -I ./ncurses-6.1-llvm/include -lncurses_g --preload-file lib/terminfo@/home/web_user/.terminfo -o hello.html -s FORCE_FILESYSTEM=1 -Ugetenv -D"getenv(name)=(char*) EM_ASM_INT ( {var envar = JSON.stringify(name);var ret=allocate(intArrayFromString(envar), 'i8', ALLOC_NORMAL);return ret ;},NULL)"
cat hello.html | sed --expression='s/preRun: \[\]/preRun: \[function(){ENV.TERM="xterm"}\]/g' > out.html
```

**Comment by ilyaigpetrov** [comment]
I uploaded the compiled ncurses library together with compile scripts here: https://github.com/ilyaigpetrov/ncurses-for-emscripten

**Comment by wmealing** [comment]
Not sure if it matters, but I'm working on similar request, but i have taken a slightly different path, i'm not getting the errors like you are, but maybe i've done it wrong.

I use ncurses built in fallback.

fallback:
        # now we build a 'falback terminfo to be embedded in the lib'
        cd ./deps/ncurses-6.1/ncurses && tinfo/MKfallback.sh \
                                        $(TERMINFO) " " \
                                        ../misc/terminfo.src \
                                        `which tic` \
                                        linux vt100 xterm xterm-color >fallback.c

And include those terminals, (i'm using xterm-color)

        cd ./deps/ncurses-6.1 && emconfigure ./configure --host none \
                                 --without-cxx-binding CFLAGS="$(CFLAGS) "  \
                                 --disable-database --disable-gnat-projects \
                                 --disable-home-terminfo \
                                 --build none --prefix=$(DEPS_OUT) \
                                 --with-fallbacks=linux,vt100,xterm,xterm-color

The problem that i'm getting is nothing at all, in the terminal.  I do see it appear in console though..  I'll keep trying to figure out whats going on.  Has anyone else made a working curses example with xtermjs ?
