### ISSUE TITLE
Installation error: incoming branch

### ISSUE THREAD

**Issue by liorbiu** [kripken/emscripten#6808]
Hi,

I tried to install the latest version by running: `./emsdk install sdk-incoming-64bit`.

At the end of the installation I received this error:
```
[91%] Linking CXX executable ../../bin/llc
collect2: error: ld returned 1 exit status
tools/llc/CMakeFiles/llc.dir/build.make:146: recipe for target 'bin/llc' failed
make[2]: *** [bin/llc] Error 1
CMakeFiles/Makefile2:16759: recipe for target 'tools/llc/CMakeFiles/llc.dir/all' failed
make[1]: *** [tools/llc/CMakeFiles/llc.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Build failed due to exception!
Working directory: /home/emscripten/emsdk-portable/clang/fastcomp/build_incoming_64
Command '['make', '-j1']' returned non-zero exit status 2
Installation failed!
```

I'm running on Ubuntu 16.04 server at AWS.

**Comment by kripken** [comment]
There might be more info earlier in the log. If not, then it may have run out of memory - linking LLVM can take a lot of resources.

However, you can do `./emsdk install latest` which will install a binary build of the latest tag - that avoids needing to compile everything. Or do you intentionally want to compile it?

**Comment by liorbiu** [comment]
I want to compile it, in order to support working with pthreads.  
 I'm using [libevent](https://github.com/libevent/libevent) that needs pthreads.

**Comment by liorbiu** [comment]
I manage to compile it by increasing the size of the RAM memory of the machine.
