### ISSUE TITLE
Problem with browser execution

### ISSUE THREAD

**Issue by Milerius** [kripken/emscripten#6812]
Hello

I got this error when i launch in the web ->

<img width="1680" alt="capture d ecran 2018-07-05 a 10 46 11" src="https://user-images.githubusercontent.com/21139416/42312489-b4a84be8-8040-11e8-98e7-05e8509dec45.png">

There is my command line:
<img width="1163" alt="capture d ecran 2018-07-05 a 10 47 34" src="https://user-images.githubusercontent.com/21139416/42312572-ecf1193a-8040-11e8-9312-02ce7dd92d9d.png">

my CMake:
```cmake
if (EMSCRIPTEN)
    set(CMAKE_EXECUTABLE_SUFFIX ".html")
    set_target_properties(script-lua-test PROPERTIES LINK_FLAGS "-s EXPORT_ALL=1 -s DISABLE_EXCEPTION_CATCHING=0 -s FORCE_FILESYSTEM=1 -s SINGLE_FILE=1 -s BINARYEN_ASYNC_COMPILATION=0 --embed-file /Users/romansztergbaum/Documents/shiva/bin/assets")
endif ()
```

how i invoke cmake with emscripten:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/Users/romansztergbaum/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake  -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/romansztergbaum/Documents/emscripten/emsdk/emscripten/1.38.6/cmake/Modules/Platform/Emscripten.cmake -DSHIVA_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug ..

^
This work like a charm
```

when i run in local without webpage just with node it's works:
<img width="763" alt="capture d ecran 2018-07-05 a 10 49 26" src="https://user-images.githubusercontent.com/21139416/42312634-1ed36fa2-8041-11e8-9af9-565f937604cb.png">

did i miss something ?

help would be greatly appreciated, i just started using emscripten

All dependencies have been statically compiled with emscripten

**Comment by kripken** [comment]
Looks like the error is on `process` not being defined. Is that in JS that you wrote, or that emscripten generated for you?

If you wrote it, perhaps it's code intended to run in node.js, where `process` exists?

If you didn't write it, can you paste that line and a few lines around it, might help to figure out why emscripten would emit it (offhand, I have no guess)?

**Comment by Milerius** [comment]
@kripken Hey thank's for your answer!

Emscripten generate javascript for me except this:

```cpp
#ifdef __EMSCRIPTEN__
                EM_ASM({
                FS.chdir(process.cwd());
            });
#endif
```

there is some of my code if you want:
https://gist.github.com/Milerius/5111c94203465f8b9b0d76290497b5b0

I really do not know where it can come from! Once again thanks for help, if there is need for more information tell me!

**Comment by Milerius** [comment]
Ok i understand i don't have the command 'process' in my brower, but how can i go to my wanted directory ?

**Comment by kripken** [comment]
Web browsers are sandboxed - you can't actually go to a local directory like that. (In node.js, not in a browser, you actually can, using the `process` API.)

The FS API that emscripten provides is a **virtual** filesystem, see https://kripken.github.io/emscripten-site/docs/porting/files/file_systems_overview.html - it helps port applications, you can preload files there so the application thinks it's running "normally". But browsers wouldn't let it directly access files on the machine.

**Comment by Milerius** [comment]
@kripken Thank's i fixed the problem with your help ! Thank's a lot !
