### ISSUE TITLE
WASM=0 causes Python Traceback when used with EMTERPRETIFY=1

### ISSUE THREAD

**Issue by hostilefork** [kripken/emscripten#6813]
A minimal C program builds fine with EMTERPRETIFY=1 when WASM=1:

    // test.c
    #include <stdio.h>
    int main(int argc, char *argv[]) {
        printf("Works with WASM=1, not with WASM=0\n");
        return 0;
    }

    $ emcc -s WASM=1 -s EMTERPRETIFY=1 test.c -o test.js 
    $ node test.js
    Works with WASM=1, not with WASM=0

However, changing to WASM=0 leads to a Python failure:

    $ emcc -s WASM=0 -s EMTERPRETIFY=1 test.c -o test.js
    Traceback (most recent call last):
      File ".../emsdk/emscripten/1.38.6/emcc", line 11, in <module>
        python_selector.run(__file__)
      File ".../emsdk/emscripten/1.38.6/tools/python_selector.py", line 38, in run
        sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
      File ".../emsdk/emscripten/1.38.6/tools/python_selector.py", line 13, in 
    run_by_import
        return getattr(importlib.import_module(os.path.basename(filename)), main)()
      File ".../emsdk/emscripten/1.38.6/emcc.py", line 1945, in run
        shutil.move(final, js_target)
      File "/usr/lib/python2.7/shutil.py", line 316, in move
        copy2(src, real_dst)
      File "/usr/lib/python2.7/shutil.py", line 144, in copy2
        copyfile(src, dst)
      File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
        with open(dst, 'wb') as fdst:
    IOError: [Errno 71] Protocol error: 'test.js'

Using version from today's install process on GitHub, under Linux:

    $ emcc --version
    emcc (Emscripten gcc/clang-like replacement) 1.38.6 (commit 
    4c8ac8755d3e19673a14c30c20c02f23f22f9eb2)

*(It has a 2014 copyright date and cites a [commit that doesn't exist](https://github.com/kripken/emscripten/commit/4c8ac8755d3e19673a14c30c20c02f23f22f9eb2), but I believe it is current...I was concerned because I had an old version installed that it might have found that somehow.  So I'd suggest "updating the date shown in --version" probably should be a ticket, too...)*

**Comment by kripken** [comment]
I don't see an error when I try those commands. Odd, that `IOError: [Errno 71] Protocol error: 'test.js'` error is not one I've ever seen. Perhaps the temp dir has the wrong permissions or such? `EMCC_DEBUG=1` in the env might show something useful in the logging.

**Comment by hostilefork** [comment]
> Odd, that IOError: [Errno 71] Protocol error: 'test.js' error is not one I've ever seen. 

Hm, now that you mention it and call out that particular line from it all, I think I *have* seen it before.  Looking it up, it seems it's something related to [virtualbox shared folders](https://stackoverflow.com/questions/31756495/ioerror-errno-71-protocol-error-when-reading-a-file-with-python-in-a-virtua).  (Windows host, Linux VM)

I reinstalled emsdk to a non-shared-folder and it works...so closing it.

Thanks for the quick response!!
