### ISSUE TITLE
Call global-scope-js-function from threads

### ISSUE THREAD

**Issue by benogel** [kripken/emscripten#6826]
Hi,
I like to call some global-scope-js-function from a thread, but that's not possible. I can imagine that the main reason for this problem is that WebWorker does not have access to the global JS context (eg window). 

Is there a way to get access to the global Js context  from a thread? Or at least to use a kind of event-bus between threads and the global scope? Is there any way to communicate?

Thanks,

Benedikt.
```cpp
#include <pthread.h>
#include <emscripten.h>

EM_JS(void, jsFunc, (int msg), {
    // some function in global js context
    myCustomLog(msg);
});


void* perform_work(void*) {
  printf("in thread \n");

  // this call of some global scope js function fails
  // ReferenceError: jsFunc is not defined
  jsFunc(1);
}

int main(int argc, char** argv) {
  pthread_t thread;
  printf("in main\n");

  // this call of some global scope js function works fine
  jsFunc(0);

  pthread_create(&thread, NULL, perform_work, NULL);
}
```

repost on [stackoverflow]( https://stackoverflow.com/questions/51280209/access-js-context-from-emscripten-threads)

**Comment by kripken** [comment]
There is a wip PR on something close, https://github.com/kripken/emscripten/pull/6189

There is also a `__proxy` option in JS library functions, I'm not sure how that works offhand, but search for `__proxy: 'sync'` in `src/library*.js` for examples.

**Comment by benogel** [comment]
I’m still looking for a way to use function-calls from Threads to the js-main-loop. 
At the moment i’m polling from js-main-loop some variables changed by threads. I hope there's a better way.

Is there any plan to merge #6189 soon? 

I looked for examples by searching` __proxy: 'sync'` in `src/library*.js` but i have no idea how to setup function-calls from threads into js-main-loop with the examples i found. Maybe i need some more hints?

**Comment by kripken** [comment]
@benogel There is new activity in that PR, hopefully it will land soon.

**Comment by benogel** [comment]
@kripken thanks for your hint.
I ran the example i gave above with the current sdk-incoming-64bit version. It is still not possible to access functions outside threads from threads. I would be very happy about any workaround for this problem.

**Comment by benogel** [comment]
I've found a way.
```cpp
MAIN_THREAD_ASYNC_EM_ASM('myCustomLog(3);')
```
see https://github.com/kripken/emscripten/blob/ccbc3ec51bb905c024e83de7add950dc49345918/system/include/emscripten/em_asm.h#L204-L209

**Comment by benogel** [comment]
since the solution approach only works for asm, it would be interesting to know how it works for wasm.
