### ISSUE TITLE
alignment error

### ISSUE THREAD

**Issue by DavidHamburg** [kripken/emscripten#6832]
Hi,

after upgrading emscripten from 1.38.5 to 1.38.8 wasm does not run anymore due to an abort("alignment fault") error. I tried to find any commit between these versions which could give me a hint what happened. Now I'm not sure if this is an error in my code or in the latest emscripten release. Do you have an idea, what happened?

**Comment by kripken** [comment]
There are actually no major changes in 1.38.6, 7 or 8 that I would guess are related (like an LLVM or major system library update). Given that, I'd recommend brute force, that is, bisecting on emscripten to find which commit changed things for you - you can bisect just on the emscripten repo itself using git bisect, keeping the llvm and clang repos fixed, should be pretty fast.

**Comment by DavidHamburg** [comment]
@kripken 

> Given that, I'd recommend brute force, that is, bisecting on emscripten to find which commit changed things for you

Thanks for your idea! Indeed I was able to find the commit. 

https://github.com/kripken/emscripten/commit/563e137e3fe506c5689f3835aa3518ee54d089fb

After looking at the commit, I'm still unsure why this would break my app and how to fix it. Do you have any idea?

**Comment by DavidHamburg** [comment]
> Maybe the stack trace makes it obvious what's going on here? 

I guess the patch made a mistake on my side visible. The error seems to be here:

```c++

void Editor::run(){
	TestClass t;
        emscripten_set_main_loop_arg(loop, reinterpret_cast<void *>(&t), 0, 1);
}

void Editor::loop(void *args){
	TestClass &t = *reinterpret_cast<TestClass *>(args);
	t.run();
}

void TestClass::run(){
	// ...
       // abort("alignment fault")
}
 
```
After declaring TestClass t{}; as member variable the error does not happen anymore. But I can't explain why this code snippet would lead to an error.  Does the variable t get lost when calling emscripten_set_main_loop_arg?

**Comment by kripken** [comment]
That might be it, yeah. When you set up a main loop, it will be called asynchronously multiple times - but the function `run()` is exited for that to happen (on the web, we can't do an "infinite loop" for the main event loop). So stuff on the stack, like `t`, becomes invalid there.

**Comment by DavidHamburg** [comment]
Many thanks for your help!

Btw, emscripten is a great tool. Really love your idea, i think it has a big influence in development.
