### ISSUE TITLE
Compiling post.js with >O1 leads to extra parentheses

### ISSUE THREAD

**Issue by Polevata** [kripken/emscripten#6847]
define(function (require) {
  "use strict";
  return Module;
});

turns into

define((function(require){"use strict";return Module}))

This is using version 1.38.8 and the compile command:
"em++ -Os --bind a.cpp b.cpp -o src/cpp/gen/out.js --post-js src/cpp/post.js --memory-init-file 0 -s WASM=0"

**Comment by kripken** [comment]
The Uglify1 JS AST that our optimizer currently uses does seem to add extra parentheses in some cases. If you build with `--closure 1` for closure compiler it should optimize away such things. Otherwise, to fix this we'd need to update our underlying JS AST, #6000.

**Comment by Polevata** [comment]
Perfect! I use minimal pre and post-js, so enabling closure compiler was just the solution I was looking for. Thanks!
