### ISSUE TITLE
Bug in page:Module object 

### ISSUE THREAD

**Issue by fcojavmc** [kripken/emscripten#6852]
REPLACE THIS TEXT WITH BUG DESCRIPTION 

URL: ../../docs/api_reference/module

var Module = {
  'print': function(text) { alert('stdout: ' + text) }
  'printErr': function(text) { alert('stderr: ' + text) }
};

Missing a comma (,) in 2nd line:

var Module = {
  'print': function(text) { alert('stdout: ' + text) },
  'printErr': function(text) { alert('stderr: ' + text) }
};

**Comment by kripken** [comment]
Thanks @fcojavmc! I added a fix for this in #6872

**Comment by kripken** [comment]
Fixed by that PR.
