### ISSUE TITLE
Returning a pointer to a file in MEMFS to javascript

### ISSUE THREAD

**Issue by athei** [kripken/emscripten#6858]
I am trying to return a C string back to javscript that was read from MEMFS. My steps are:

**C++**
Read from MEMFS to char*
Return char*
**Javascript**
Call _free() on the pointer

Is there a way to directly return a pointer to the MEMFS memory location? Did not found it im **emscripten.h**. This way I could avoid the alloc/copy/free cycle.

**Comment by kripken** [comment]
How MEMFS stores in memory may depend on various things, see the `--no-heap-copy` argument to the file packager. But if you keep the default behavior, then `mmap` should just return a pointer to the memory location, which is efficient and I think close to what you want?

**Comment by kripken** [comment]
You can add `_munmap` to `EXPORTED_FUNCTIONS` (`free()` is there by default, others need to be added).

**Comment by athei** [comment]
Thanks for your reply! I have problems making `munmap` available in javascript. Mind that I only call it from places invisible to emscripten.

I added the following. Do not mind the escapes. It is copied from a cmake file:
```
"-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE='[\"memcpy\", \"memset\", \"malloc\", \"free\", \"munmap\"]'"
"-s EXTRA_EXPORTED_RUNTIME_METHODS='[\"_free\", \"_munmap\", \"allocateUTF8\", \"UTF8ToString\"]'"
```

The build yields this error and `_munmap` is not available:
`warning: unresolved symbol: munmap`

This is my js code invisible to emscripten. Every line works except for the _munmap:
```
const ptr_in = this.simc.allocateUTF8(this.state.profile);
const ptr_out = this.simc._simulate(ptr_in);
this.simc._free(ptr_in);
const result = this.simc.UTF8ToString(ptr_out);
this.simc.munmap(ptr_out);
```

**Comment by kripken** [comment]
This is a little tricky, because munmap is implemented in a combination of C (in libc) and JS (in FS, through the syscall ABI). Worse, on the C side a macro is used, pointing to `__munmap`. The simplest way to get it is to use munmap in a function in your C code, which acts as a wrapper for it. Then export that to JS and call it.

**Comment by athei** [comment]
Ahh okay thanks for the tip. That actually worked.
