### ISSUE TITLE
Embind quick example in docs fails due to async startup

### ISSUE THREAD

**Issue by angupt** [kripken/emscripten#6859]
I am trying the basic example from https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html but it seems not working as I am getting 
`TypeError: Module.lerp is not a function` . I am running the index.html from python SimpleHTTPServer and using the same  `quick_example.cpp`. Please help.

```
// quick_example.cpp
#include <emscripten/bind.h>

using namespace emscripten;

float lerp(float a, float b, float t) {
    return (1 - t) * a + t * b;
}

EMSCRIPTEN_BINDINGS(my_module) {
    function("lerp", &lerp);
}
```

my index.html

```
<!doctype html>
<html>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <script src="quick_example.js"></script>
  <script>
    console.log('lerp result: ' + Module.lerp(1, 2, 0.5));
  </script>
</html>
```

**Comment by kripken** [comment]
Does it work if you also run emcc with `-s WASM=0`? If so, then maybe async wasm compilation is the issue, it seems like the example assumes synchronous startup, which we probably need to fix.

**Comment by angupt** [comment]
Yes, with WASM=0 is also not working.

**Comment by kripken** [comment]
I tested the instructions in the docs now - for me it works with `-s WASM=0`. Is it possible you didn't add it to the emcc compile that emits the JS, or maybe you forgot the `-s`?

We should update the docs so that they handle async startup.

**Comment by sletz** [comment]
With `-s WASM=1`, are we supposed to setup "onRuntimeInitialized" then, so that the async compilation is finished before actually using the Module ?

**Comment by kripken** [comment]
@sletz yes, exactly, can use `onRuntimeInitialized` to wait for async compilation to finish.
