### ISSUE TITLE
No apparent way to specify Module.wasmBinary (or any other such params) with Node-style 'require'

### ISSUE THREAD

**Issue by paulshapiro** [kripken/emscripten#6871]
Many things which users would like to pass to Module as initialization parameters are generally presently deduced at program runtime, such as a replacement implementation for `locateFile`, or, more specifically, data for `wasmBinary`. For browser environments, we pack our code with the frequently used library webpack so that we can keep our code in a single JS module inclusion format, `require(…)`. With this method of including the emscripten module JS file, is there any way to pass initialization parameters to Module?

**Comment by kripken** [comment]
I guess `require` doesn't have a way to pass parameters to the loaded module?

Maybe one option is to create a helper module, which you require and then add the options to there. Then the main emscripten code could have been compiled with a `--pre-js` where that extra JS `require()`s that helper module and copies the options from there onto `Module`.

**Comment by paulshapiro** [comment]
Ordinarily what you would do is just export, say, a class or a function, which your consumer would then initialize (with options) or call (with parameters). You already have something like that with `MODULARIZE` where you call the exported object which returns a promise you subscribe to. The only thing missing is in that exported object call there are no options being passed in. Using pre-compiled --pre-js won't work because these values are determined at run-time rather than compile-time.

**Comment by paulshapiro** [comment]
@kripken want to make sure you saw my reply that you can pass options via a require since you already have a function call via modularize. Passing options would be a simple fix for the author, as far as I can tell. The issue is I really want to avoid manually modifying emscripten's env detection because, for starters, modifying it means that any beneficial edits made by third parties will not be available to all library consumers.. so emscripten would benefit, and I thought it would ease maintenance too. Please do let me know if there's additional information that would help you come to a view on this. We're very eager to roll out our usage of emscripten but this is a blocker for us in making the lib available to our audience.

**Comment by paulshapiro** [comment]
OH, awesome! I completely missed that in the code. (fwiw I didn't see it in any docs) Will try it out. 

Much appreciated. 💥
