### ISSUE TITLE
Assertion failed: you need to wait for the runtime to be ready (e.g. wait for main() to be called)

### ISSUE THREAD

**Issue by Mukundan314** [kripken/emscripten#6883]
I compiled C code from [here](https://github.com/Block-Lab/kNight.js/tree/master/lib/cryptonight) to create cn.js, then `require`d it from node.js and called it with this code:
```node
let Module = require('./cn.js')

var cn = Module.cwrap('hash_cn', 'string', ['string', 'string', 'number', 'number']);

function zeroPad(num, places) {
  var zero = places - num.toString().length + 1;
  return Array(+(zero > 0 && zero)).join("0") + num;
}

function int2hex(i) {
  return (zeroPad(i.toString(16), 8)).match(/[a-fA-F0-9]{2}/g).reverse().join('');
}

console.log(cn(int2hex(0), int2hex(0), 0, 0))
```

 It produces the following error:
```
(function (exports, require, module, __filename, __dirname) { var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){var nodeFS;var nodePath;Module["read"]=function shell_read(filename,binary){var ret;ret=tryParseAsDataURI(filename);if(!ret){if(!nodeFS)nodeFS=require("fs");if(

TypeError: Cannot read property 'apply' of undefined
    at Module.stackSave (/home/mukundan/cn.js:1:1044579)
    at ccall (/home/mukundan/cn.js:1:7083)
    at /home/mukundan/cn.js:1:7512
    at Object.<anonymous> (/home/mukundan/test.js:25:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

But when I call it through my browser, I do not get any errors, and the correct output.

Any help in the right direction on how to fix this would be great, thanks.

**Comment by kripken** [comment]
Which options did you compile with? It might help to build without optimizations, as then the code won't be minified (easier to read in that quote) and also in unoptimized builds there are assertions which might catch a problem.

**Comment by Mukundan314** [comment]
All options available in this [Makefile](https://github.com/Block-Lab/kNight.js/blob/master/lib/cryptonight/Makefile). I removed the `-o3` flag then ran my program and it produces the following error:
```
abort("Assertion failed: you need to wait for the runtime to be ready (e.g. wait for main() to be called)") at Error
    at jsStackTrace (/home/mukundan/cn.js:1032:13)
    at stackTrace (/home/mukundan/cn.js:1049:12)
    at abort (/home/mukundan/cn.js:24330:44)
    at assert (/home/mukundan/cn.js:437:5)
    at Module.stackSave (/home/mukundan/cn.js:24000:3)
    at ccall (/home/mukundan/cn.js:500:34)
    at /home/mukundan/cn.js:515:12
    at Object.<anonymous> (/home/mukundan/test.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by kripken** [comment]
Ok, that's one of those asserts. You can search for that error message in the FAQ, I think this is the right entry: https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions

**Comment by Mukundan314** [comment]
Thanks, I defined `onRuntimeInitialized` as follows:
```node
Module.onRuntimeInitialized = function() {
  var cryptonight = cn.cwrap('hash_cn', 'string', ['string', 'string', 'number', 'number']);
  module.exports = {
    cryptonight: cryptonight,
    int2hex: int2hex,
    zeroPad: zeroPad
  }
}
```

but when I `require` this module from another file there are no exports.

**Comment by Mukundan314** [comment]
No. Instead, you can do something like this:

a.js
```js
let Module = require('./cn.js')

var cryptonight = cn.cwrap('hash_cn', 'string', ['string', 'string', 'number', 'number']);

module.exports = {
  cryptonight: cryptonight,
  Module: Module
}
```

b.js
```js
let a = require('./a.js')

a.Module.onRuntimeInitialized = function() {
  a.cryptonight()
}
```

**Comment by jasonkolodziej** [comment]
Thank you so much! 
I am making a game that took initial c++ bindings and I am trying to figure out the best way to return the value given from a function called by these bindings. Do you have any thoughts on this?

Cheers!

let Module = require('./return_index');
var flippedIndexWrapper = function(typedArray,diff){
    var r;
    Module.onRuntimeInitialized = function() {
        r = Module.returnIndexFlip(typedArray, diff);
        console.log(r);
    };
    return r;
};
module.exports = flippedIndexWrapper;


Invoking flippedIndexWrapper from another js file is consoling “undefined”… while this file consoles out the value of the index. I am somewhat rough on JS. So I do appreciate any advice you might have to make this work well!


Jason Kolodziej

Computer Science UG, '20 | Engineering IT

Texas A&M | College of Dwight Look Engineering

jasonkolodziej97@gmail.com <mailto:jasonkolodziej97@gmail.com> | jasonkolodziej@exchange.tamu.edu <mailto:jasonkolodziej@exchange.tamu.edu>
cell +1 830.391.4180 | +1 347.644.9750

**Comment by Mukundan314** [comment]
Sorry, for the late reply

you could probably use the [`--pre-js`](https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html#emcc-pre-js) and [`--post-js`](https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html#emcc-post-js) options in emcc
