### ISSUE TITLE
Pass multiple pointers into wasm

### ISSUE THREAD

**Issue by yahsaves** [kripken/emscripten#6893]
I have a c++ function that accepts 2 arrays and adds them together.

```
void addData(unsigned char *arr1, unsigned char *arr2) {
   for(i=0;i<10;i++){
    arr1[i] = arr1[i] + arr2[i];
   }
}
```

When I compile it I allocate space for both arrays in the heap using malloc.

```
var mallocBuff = Module._malloc(arr1.length); 
var mallocBuff2 = Module._malloc(arr2.length); 
```

Then I populate the newly malloced data with set

```
secondPart.Module.HEAPU8.set(arr1, 0);
secondPart.Module.HEAPU8.set(arr2, mallocBuff);
```

Then I try to call the function like this:

`Module.ccall('addData', null, ['number'], [mallocBuff], [mallocBuff2]);`

However after some testing I realize that only the first array is receiving the malloc pointer. The second array is just a bunch of 0's.

Is there anyway to pass 2 arrays into a wasm compiled function?

**Comment by kripken** [comment]
The `ccall` method has an array argument for the parameters to the call, so try to replace `[mallocBuff], [mallocBuff2]` with `[mallocBuff, mallocBuff2]` (one array with both arguments).

**Comment by yahsaves** [comment]
Thank you that worked very well!
