### ISSUE TITLE
Regression in modularize mode (currentSrc issue)

### ISSUE THREAD

**Issue by brion** [kripken/emscripten#6903]
Compiling ogv.js with emscripten sdk 1.38.10, I'm seeing a new failure mode with my demuxer module, which is loaded asynchronously into the web page context:

```
[Error] TypeError: null is not an object (evaluating 'ca.src')
```

This is in the (minified) setup code:

```
        if (n) {
            var da = this._currentScript || document.currentScript;
            0 !== da.src.indexOf("blob:") && (t = da.src.split("/").slice(0, -1).join("/") +
            "/")
        } else
```

source:

```
   if (ENVIRONMENT_IS_WEB) {
#if MODULARIZE
    // When MODULARIZE, this JS may be executed later, after document.currentScript is gone, so we send it
    // using this._currentScript.
#else
    var currentScript = document.currentScript;
#endif
     if (currentScript.src.indexOf('blob:') !== 0) {
       scriptDirectory = currentScript.src.split('/').slice(0, -1).join('/') + '/';
     }
```

Something about this isn't doing what I expect...

I notice at the end of the .js file is this which appears to be an attempt to capture the currentSource:

```
OGVDemuxerWebMW = OGVDemuxerWebMW.bind({
    _currentScript: typeof document !== 'undefined' ? document.currentScript : undefined
});
```

But that syntax for the Function.prototype.bind function doesn't appear to be documented on MDN, and it doesn't seem to do anything that I can tell on Safari 11.1.2.

**Comment by brion** [comment]
That bit appears to have come from d1f303adf643a614ce55d45e38544fc81c5781b2

**Comment by nazar-pc** [comment]
I suspect it is called, but asynchronously as part of a bigger bundle. You may want to adjust your build process or override `Module.locateFile`. On Emscripten side we should probably add a check whether `currentScript` is an object at all to avoid this error.

**Comment by kripken** [comment]
Hmm, we do the `bind` right after defining the function, so it seems like that has to happen.

And we do check if `this['_currentScript']` exists, so I think that should handle the case of not having `document` or `document.currentScript` defined during binding.

Maybe another binding happens later, overriding this one?

**Comment by kripken** [comment]
Btw, this code slightly changed since the original landing - @brion is this still an issue on latest incoming?

**Comment by brion** [comment]
(document and document.currentScript are defined at the time that bind() is called, I checked in the debugger)

**Comment by brion** [comment]
Ah, I understand what the bind() call is doing now -- it's putting the _currentScript property on the hidden this, not on the Module object... investigating further on my end.

**Comment by brion** [comment]
AHA!

My call to the OGVDemuerWebMW module function was made like this:

```
return new global[className](options);
```

which used to work fine. That "new" replaces the "this" parameter from the bind() call with a copy of the prototype, which has no _currentScript property.

Removing the "new" from the calls *should* get it working... recompiling now. :)

**Comment by brion** [comment]
Aaaaand it works now. :) As far as I know following documentation correctly in the initial call would have saved me here. :D

**Comment by kripken** [comment]
Great, thanks for the update @brion!

I added a commit to #6894 to avoid crashing in either the case of `document.scriptDirectory` not existing (as @nazar-pc mentioned), or doing `new Module()` which overrides the object containing the helper property. In both cases we can't access the scriptDirectory but we should at least not crash.

**Comment by tgds** [comment]
@kripken this introduces a new problem. `document.currentScript.src` is undefined if you import the script in SVG using `<script href="a.out.">` and the script crashes with `Cannot read property 'indexOf' of undefined`

**Comment by kripken** [comment]
Thanks @tgds. I hadn't realized that could be an issue. I filed #7494

What's the use case for loading in an SVG, by the way?

**Comment by tgds** [comment]
Honestly, I only came across it in this [Google codelab](https://codelabs.developers.google.com/codelabs/hour-chipmunk/index.html?index=..%2F..%2Fio2018#0) and that's how I found the issue. I suppose the use case is interactive SVGs sharable without HTML glue?

**Comment by kripken** [comment]
Interesting, thanks @tgds
