### ISSUE TITLE
How can i use libzip?

### ISSUE THREAD

**Issue by admanV** [kripken/emscripten#6906]
I wanna unzip ".zip" file in memory and ".zip" file is already in memory.
and i wanna extract one file.
So  i tried to use "libzip" library.
And i tried to build libzip and compile with my code but failed.
i failed to build "libzip" using emcmake.
 +  I failed to use only "zlib" library for unzip ".zip" file and extract particular file. 

How to build "libzip"?
or,, Is there any nice solution to use libzip?

**Comment by admanV** [comment]
success to build libzip. let's close

**Comment by alienself** [comment]
Do you have instructions to do build libzip with emscripten?
