### ISSUE TITLE
Using -s SINGLE_FILE results in 450mb file.

### ISSUE THREAD

**Issue by TrevorSundberg** [kripken/emscripten#6912]
We were previously just outputting the html, js, wasm and data files separately, and in total it was around 36mb. I know that base64 encoding multiplies your data size by 4/3, but I'm unsure how it got that large.

Our command line is approximately:
```
-DEMSCRIPTEN=1 -D__EMSCRIPTEN__=1  -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ABORTING_MALLOC=0 --memory-init-file 1 -s SINGLE_FILE=1 -s ALLOW_MEMORY_GROWTH=1 --no-heap-copy -s DEMANGLE_SUPPORT=1 -s FORCE_FILESYSTEM=1 -s WASM=1 -s USE_SDL=2 -s USE_WEBGL2=1 -s FULL_ES2=1 -s FULL_ES3=1 -s BINARYEN_TRAP_MODE='clamp' -msse -msse2 -std=c++11 -O3 -fstack-protector -fdelayed-template-parsing -fexceptions -fno-omit-frame-pointer -frtti -DZeroExportDll --shell-file ZeroShell.html
```

I say approximately because we're using CMake.

**Comment by kripken** [comment]
Oh wow, thanks for filing @TrevorSundberg! This was a bad oversight, we were bundling the wasm text file too, not just the binary, and it is huge...

Fix in https://github.com/kripken/emscripten/commit/6424bc9d7f0947b195c744ff6901eaf792106cd9 Makes hello world in SINGLE_FILE 8x smaller...

**Comment by TrevorSundberg** [comment]
Thanks again for such a quick response!
