### ISSUE TITLE
Emcc EMSCRIPTEN_ROOT path error in 1.38.9 onwards

### ISSUE THREAD

**Issue by abcthomas** [kripken/emscripten#6915]
When trying to compile with Emscripten 1.38.9 onwards I receive the following error:

`ERROR:root:Incorrect EMSCRIPTEN_ROOT in config file: C:\Program Files\Emscripten\emsdk\emscripten\incoming (Expected C:\PROGRA~1\EMSCRI~1\emsdk\EMSCRI~1\incoming)`

This is being invoked from a CMake built nmake file. It appears CMake is shortening the path names and the latest versions of emcc don't like it. If I change my EMSCRIPTEN_ROOT entry in my config to the shortened path then this works.

I can run this fine with version 1.38.8 and previous versions. There are quite a few commits between 1.38.8 and 1.38.9 so I haven't tested which actual commit this regression appeared on, although I can do that if really needed.

**Comment by kripken** [comment]
Thanks @abcthomas!

From the error, I am guessing the breaking commit is 56dd57e0d05013b97ea5aa98dbfafd25b38aedf5 which was indeed between 1.38.8 and 1.38.9. cc @sbc100 

Perhaps we need an `os.abspath` in that comparison? Although I'm not sure expanding windows short names is done there - this is a windows thing I don't know much about.

**Comment by kripken** [comment]
I tried and abspath is not enough. Some searching finds [we'd need something like this:](https://stackoverflow.com/a/2161652)
```
import win32file
print win32file.GetLongPathName(r'C:\progra~1')
```
Seems weird it's this hard to do this in python?

**Comment by kripken** [comment]
@sbc100 makes sense. Actually this may happen with symbolic links too on other platforms, I worry - so I opened #6924 to remove the assertion, seems not worth the effort.
