### ISSUE TITLE
identical condition 

### ISSUE THREAD

**Issue by maddin200** [kripken/emscripten#6932]
[C:/Data/Download/Open Source/emscripten-incoming/system/lib/al.c: line 91

else if (!strcmp(name, "alIsSource")) { return alIsSource; } // same as line 90

also line 118
else if (!strcmp(name, "alBufferData")) { return alBufferData; } // same as line 117

**Comment by kripken** [comment]
Thanks @maddin200!

I opened #6956 to fix these.

(I wonder if these are the result of a merge, or a bad copy-paste... not sure.)
