### ISSUE TITLE
macos problem

### ISSUE THREAD

**Issue by wengxianxun** [kripken/emscripten#6940]
Last login: Fri Aug  3 10:05:44 on ttys000
wxx:~ wengxianxun$ emcc
ERROR:root:Incorrect EMSCRIPTEN_ROOT in config file: /Users/wengxianxun/Downloads/emsdk-portable/emscripten/1.38.10 (Expected /usr/local/Cellar/emscripten/1.38.10/libexec)

**Comment by wengxianxun** [comment]
i can,t find tools/shared.py in my macos

**Comment by wengxianxun** [comment]
what is the full path?

**Comment by wengxianxun** [comment]
how to use use the previous version

**Comment by wengxianxun** [comment]
@kripken

**Comment by wengxianxun** [comment]
# exit_with_error('Incorrect EMSCRIPTEN_ROOT in config file: %s (Expected %s)', EMSCRIPTEN_ROOT, __rootpath__)

i Notes this row,
but new error:

wxx:js wengxianxun$ emconfigure
Traceback (most recent call last):
  File "/usr/local/Cellar/emscripten/1.38.10/libexec/emconfigure.py", line 22, in <module>
    from tools import shared
  File "/usr/local/Cellar/emscripten/1.38.10/libexec/tools/shared.py", line 310
    def hint_config_file_location():
      ^
IndentationError: expected an indented block

@kripken

**Comment by wengxianxun** [comment]
can you  builds 1.38.11 for macos? please

**Comment by kripken** [comment]
You may need to replace the assert with `pass` so that python is happy (it doesn't like empty lines where it expects indentation).

I am doing everything I can to get 1.38.11 built on macos. The bot is run by a volunteer, and it's down - I've pinged him.

**Comment by kripken** [comment]
The macos bot now reports it successfully built 1.38.11.
