### ISSUE TITLE
WASM and MODULARIZE_INSTANCE / EXPORT_ES6

### ISSUE THREAD

**Issue by ThorstenBux** [kripken/emscripten#6943]
That might be a silly question but I couldn't get my head around it so I thought I ask anyway.

I would like to use wasm and MODULARIZE_INSTANCE. I'd like to load the wasm file from a configured URL and because of that I try to implement 
```mymodule.instantiateWasm()```
or
```mymodule['wasmBinary']```.

However as the wasm loading already runs when I import the wasm accompanied .js file using
```import mymodule from './mymodule.js';```

The code I write to implement ```instantiateWasm``` or ```mymodule['wasmBinary']``` is being called too late. So I'm wondering what would be the best way to do it?

Many thanks

**Comment by kripken** [comment]
You can configure the URL of the wasm file using [`locateFile`](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.locateFile) (that still handles compilation for you, but you tell it where to find the file).

**Comment by ThorstenBux** [comment]
I've found a solution that works for me. I created a script that I add in during the build using ```--pre-js``` containing this code:

```
/** Web assembly support */

if(window.artoolkitX_wasm_url) {
    function downloadWasm(url) {
        return new Promise(function(resolve, reject) {
        var wasmXHR = new XMLHttpRequest();
        wasmXHR.open('GET', url, true);
        wasmXHR.responseType = 'arraybuffer';
        wasmXHR.onload = function() { resolve(wasmXHR.response); }
        wasmXHR.onerror = function() { reject('error '  + wasmXHR.status); }
        wasmXHR.send(null);
        });
    }

const wasm = downloadWasm(window.artoolkitX_wasm_url);
artoolkitXjs['wasmBinary'] = wasm;

    // Module.instantiateWasm is a user-implemented callback which the Emscripten runtime calls to perform
    // the WebAssembly instantiation action. The callback function will be called with two parameters, imports
    // and successCallback. imports is a JS object which contains all the function imports that need to be passed
    // to the Module when instantiating, and once instantiated, the function should call successCallback() with
    // the WebAssembly Instance object.
    // The instantiation can be performed either synchronously or asynchronously. The return value of this function
    // should contain the exports object of the instantiated Module, or an empty dictionary object {} if the
    // instantiation is performed asynchronously, or false if instantiation failed.
    artoolkitXjs.instantiateWasm = function(imports, successCallback) {
        console.log('instantiateWasm: instantiating synchronously');
        wasm.then(function(wasmBinary) {
            console.log('wasm download finished, begin instantiating');
            var wasmInstantiate = WebAssembly.instantiate(new Uint8Array(wasmBinary), imports).then(function(output) {
            console.log('wasm instantiation succeeded');
            successCallback(output.instance);
        }).catch(function(e) {
            console.log('wasm instantiation failed! ' + e);
            });
        });
        return {}; // Compiling asynchronously, no exports.
    }
}
```

This way I only need to define one global variable ```artoolkitX_wasm_url``` to define the path to the wasm file before I load my emscripten compiled .js file which in turn loads the .wasm file. 

I think it is a good solution for now. It just needs a global variable which I have to live with atm. 

Thanks for your help anyways 👍
