### ISSUE TITLE
Embind call fails at equivalent of createElement

### ISSUE THREAD

**Issue by Jendker** [kripken/emscripten#6948]
Encouraged by the good opinions of the cross-talking abilities with embind I wanted to run some Javascript in C++ to make my code a bit cleaner.

I am trying to run something as simple as Javascript:
```
var canvas=document.createElement("canvas");
```
in C++.

I have found one example: https://github.com/kripken/emscripten/issues/1296#issuecomment-19567650
But my code:
```
val canvas = val::global("document").call<val>("createElement", "canvas");
// (had to specialise the template)
```
gives me following errors:
```
In file included from /home/ben/Development/Camera_processing_wasm/main.cpp:147:
In file included from /home/ben/Documents/Builds/emsdk/emscripten/1.38.10/system/include/emscripten/bind.h:14:
In file included from /home/ben/Documents/Builds/emsdk/emscripten/1.38.10/system/include/emscripten/val.h:8:
/home/ben/Documents/Builds/emsdk/emscripten/1.38.10/system/include/emscripten/wire.h:354:24: error: array 'new' cannot have initialization arguments
                return new T(v);
                       ^     ~
/home/ben/Documents/Builds/emsdk/emscripten/1.38.10/system/include/emscripten/val.h:219:62: note: in instantiation of member function 'emscripten::internal::GenericBindingType<char [7]>::toWireType' requested here
            writeGenericWireType(cursor, BindingType<First>::toWireType(std::forward<First>(first)));
                                                             ^
/home/ben/Documents/Builds/emsdk/emscripten/1.38.10/system/include/emscripten/val.h:227:17: note: in instantiation of function template specialization 'emscripten::internal::writeGenericWireTypes<char const (&)[7]>' requested here
                writeGenericWireTypes(cursor, std::forward<Args>(args)...);
                ^
/home/ben/Documents/Builds/emsdk/emscripten/1.38.10/system/include/emscripten/val.h:243:39: note: in instantiation of member function 'emscripten::internal::WireTypePack<char const (&)[7]>::WireTypePack' requested here
                WireTypePack<Args...> argv(std::forward<Args>(args)...);
                                      ^
/home/ben/Documents/Builds/emsdk/emscripten/1.38.10/system/include/emscripten/val.h:463:56: note: in instantiation of member function 'emscripten::internal::MethodCaller<emscripten::val, char const (&)[7]>::call' requested here
            return MethodCaller<ReturnValue, Args...>::call(handle, name, std::forward<Args>(args)...);
                                                       ^
/home/ben/Development/Camera_processing_wasm/main.cpp:193:41: note: in instantiation of function template specialization 'emscripten::val::call<emscripten::val, char const (&)[7]>' requested here
    dc.canvas = val::global("document").call<val>("createElement", "canvas");
```
Then I've tried a different approach: https://groups.google.com/forum/#!topic/emscripten-discuss/aPCqlEG4Jx4
Here Chad Austin proposes to create the struct with canvas and context as members with the function:
```
struct DCImplementation {
    val canvas;
    val context;
};

DCImplementation createCanvas() {
    // corresponds to
    // var canvas = document.createElement("canvas");
    // var context = canvas.getContext("2d");

    DCImplementation dc;
    dc.canvas = val::global("document").call<val>("createElement", "canvas");
    dc.context = dc.canvas.call<val>("getContext", "2d");
    return dc;
}
```
I am also defining value object:
```
    value_object<DCImplementation>("DCImplementation")
        .field("canvas", &DCImplementation::canvas)
        .field("context", &DCImplementation::context)
        ;
```
But the error is well self-explainatory:
`note: default constructor of 'DCImplementation' is implicitly deleted because field 'canvas' has a deleted default constructor`
It seems, that I cannot create structs with val (at least not in such a way).

-----------------------------------------------------------
Could anyone give me some feedback on that matter? The given examples does not seem to work.

**Comment by cwoffenden** [comment]
Your embind sample will work as:

`val canvas = val::global("document").call<val>("createElement", val("canvas"));`

(C-string `val` conversion is explicit in `val.h`.)

**Comment by Jendker** [comment]
Thank you!

**Comment by dicecko** [comment]
@cwoffenden How can we add this now to the body? I tried the following:

```
    val body = val::global("document").call<val>("getElementByTagName", val("body"));
    body.call<void>("appendChild", canvas);
```

Then I get the console error: exception thrown: TypeError: handle[name] is not a function,TypeError: handle[name] is not a function.
I'm guessing this is because getElementByTagName returns a collection of elements.
So I tried:

```
    val body = val::global("document").call<val>("getElementByTagName", val("body"));
    val body1 = body.call<val>("item", val(0));  // also tried val("0")
    body1.call<void>("appendChild", canvas);
```
But that gives the same error.

If I do:

```
    val test = val::global("document").call<val>("getElementById", val("test1"));
    test.call<void>("appendChild", canvas);
```

It does work. But when starting with a new blank page or if there are no elements with id's (I'm guessing I'll get the same error when using getElementsByClassname) I cannot do this.

How can one access a specific element from the collection?

**Comment by cwoffenden** [comment]
As you point out, in your first example the return  value is a collection, so you need to access its elements:
```
val elements = val::global("document").call<val>("getElementsByTagName", val("body"));
val body = elements[0];
```
I think you'd be better off writing this in JavaScript directly using `EM_JS` like so:
```
EM_JS(void, my_example_function, (), {
    var elements = document.getElementsByTagName("body");
    var body = elements[0];
});
```
They do the same thing except `EM_JS` doesn't require you to transliterate the syntax.

**Comment by dicecko** [comment]
Thanks for the response. 
When I read it I immediatly saw "getElementByTagName", no "s" feeling pretty stupid. 

As for the inline JS. This works for creating the element, but as far as I know I need embind to pass the getContext object to other functions.

**Comment by cwoffenden** [comment]
You could store the context in a `Module` property. Here's a contrived example of doing this with a shared audio context:
```
EM_JS(void, audio_preinit, (), {
	if (Module.audio_audCtx === undefined) {
		if (window.AudioContext) {
			Module.audio_audCtx = new AudioContext();
		} else {
			if (window.webkitAudioContext) {
				Module.audio_audCtx = new webkitAudioContext();
			}
		}
	}
});
```
Any calls needing the same context can grab it from other `EM_JS` functions. For multiple contexts you could store them in an array and pass around the index.

This even works after Closure, with all the `audio_audCtx ` properties in different functions getting the same minified name.
