### ISSUE TITLE
Zero init section of module not zero initialized

### ISSUE THREAD

**Issue by mkujawa** [kripken/emscripten#6969]
I have a project (with @missmah)  which uses many side modules, and both loads and unloads them.  In going through a loop, it loads a module, calls some functions, then unloads that module.

Several of these modules end up getting the same address back from the `getMemory` call (which it got from `_malloc`.)  This memory is not zeroed out by `getMemory` or `alignMemory`, and seems that anything beyond what the `/* memory initializer */ allocate` writes to is left alone.  In my case, this is detected by an integer that should be zero having instead the bytes from an ascii string of a previously loaded module.

For example, going to my module's .js file and adding the following after `var fb=env.fb|0;`:

    var testsrc = gb + 7152 | 0;
    console.log("HEAP8[bg+7152] is " + HEAP8[testsrc >> 0] );

prints `99` .  (If I hack out the unloading of modules from our app, then it correctly prints `0`.)

The comment in https://github.com/kripken/emscripten/issues/3907 seems to imply that the type arrays were going to be zeroed out.  I suspect the belief was that Int8Array (et al) were going to 0-initialize (and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array even says it will do that.)  However, I'm glad it doesn't since `buffer` is both huge (512M at this point) and has other module's data in it!

My guess is that another `allocate` should be in the memory initializer which sets the remaining memory to 0.  (Putting in such an allocate by hand does indeed fix the issue, albeit only until the next compile.)

**Comment by kripken** [comment]
Is this with asm.js or wasm?

For wasm, the code for zeroing out that memory is here:

https://github.com/kripken/emscripten/blob/incoming/src/support.js#L165

We used to have a bug there, which was fixed in the last few months - are you perhaps on an older version? If that's not it, maybe adding some debug statements around that loop might show what the problem is.

(For asm.js, I'm not sure offhand where the relevant code is.)

**Comment by mkujawa** [comment]
Thank you for the prompt reply!

We are on 1.37.36 (sorry for leaving that out of the initial report), so we will try again with latest. I'm pretty sure we're using asm.js, though.  

I thought the relevant code was in src/jsifier.js `finalCombiner()`

**Comment by mkujawa** [comment]
Seems like this was fixed by https://github.com/kripken/emscripten/pull/6355 and included in 1.37.37... the very next version after what we had (figures!)
