### ISSUE TITLE
Static memory initialization fails for side module when value=0

### ISSUE THREAD

**Issue by jb-pol** [kripken/emscripten#6991]
Emscripten version: 1.37.21

Problem: When using side modules and global variables in those side modules are the variables not properly initialized if the value they should have equals zero (or NULL). Variables with other values are properly initialized.

Occurs in debug version, release not yet tested.

Guess: Memory are expected to be 0 already and therefore not initialized, but isn't when other code have been running using this memory (malloc/free) before the side module is loaded.

**Comment by jb-pol** [comment]
This (or another?) but also seem to affect empty string literals "" and L"". Those are not as empty as they should be...

**Comment by kripken** [comment]
I remember we fixed a bug regarding this - it may well have been after 1.37.21. Please test on the latest version (1.38.11).

If that's not it, is this in asm.js or wasm? And a testcase would be helpful if possible.

**Comment by jb-pol** [comment]
Yes, it seems to bo be solved in the current version. 

For archival purposes: I use asm.js both in the old and the new version.

Since it isn't a problem for me anymore I won't build a testcase. If anyone is interesting in building  one I guess the following would work, or rather not work in the 1.37.21 version::
Create a project with a main module and a side module.
In the side module:
Create some global (static) variables of simple types (int or similar). Initialize at least one with 0 and one with some other value. Also remember that uninitialized global variables should have a implicit initialization to 0 in C and C++.
Create a function displaying the values of those global variables (prinf for example) and displaying the value of strlen("")
In the main module:
Allocate a (large) block of memory using malloc
Fill the memory with some value other than 0.
Free the memory
Load the side module
Call the function in the side module.
