### ISSUE TITLE
emscripten::val - how do I pass functions to things like "addEventListener", etc?

### ISSUE THREAD

**Issue by sortofsleepy** [kripken/emscripten#7025]
👋  Howdy!

Trying to explore adding video to something I'm building. Seems like making use of HTML5 video is the ideal solution and the Embind val api seems like the best API for someone like me that's more used to Javascript than C++. 

I'm having quite a wild ride trying to add a function onto the `addEventListener` prop of the `<video>` tag. For example, one thing I've tried:
```c++
video.call<void>("addEventListener",std::string("onload"),val((*func)()));
```

Basically, it seems that the only way I can get things to compile and run is if I have some kind of functional pointer wrapped inside a call to `val`, everything else either fails at compilation or I get an error in the browser saying the class can't grab the value. 

What is the correct way to pass in a function to the api so that it gets executed properly.  Right now the issue is that things are getting executed way too early. Is there an alternate solution that would work that I haven't thought of? 

Apologies ahead of time for my lack of knowledge on pointers, c++, etc

Any help is greatly appreciated!

**Comment by sortofsleepy** [comment]
Ok - I think I can close this for now, I've figured out a no-so-elegant, but workable api for the time being. Essentially it involves adding some global static functions in-place of trying to call the `addEventListener` property of the element itself within the Javascript. Happy to share code if anyone is having trouble with this as well.

**Comment by cwoffenden** [comment]
The onload has probably fired before your event listener is added.

As for calling a method, I don't know of any way other than passing a pointer as one of your arguments (a `val` will happily hold a `uintptr_t`).

**Comment by gerald-dotcom** [comment]
> Ok - I think I can close this for now, I've figured out a no-so-elegant, but workable api for the time being. Essentially it involves adding some global static functions in-place of trying to call the `addEventListener` property of the element itself within the Javascript. Happy to share code if anyone is having trouble with this as well.

@sortofsleepy Hiya, Could you share the code with me?

**Comment by sortofsleepy** [comment]
> 
> 
> > Ok - I think I can close this for now, I've figured out a no-so-elegant, but workable api for the time being. Essentially it involves adding some global static functions in-place of trying to call the `addEventListener` property of the element itself within the Javascript. Happy to share code if anyone is having trouble with this as well.
> 
> @sortofsleepy Hiya, Could you share the code with me?

@gerald-dotcom 

I don't exactly remember what the solution I came up with here at this point and it's likely changed since I filed this issue, but this should work. 

First off, you need to create a binding to a version of the `std::function` class like so 

```c++
EMSCRIPTEN_BINDINGS( MyBindings ) {
	emscripten::class_<std::function<void(emscripten::val e)> >( "ListenerCallback" )
	.constructor<>()
	.function("onload", &std::function<void(emscripten::val e)>::operator() );
};

``` 

After that, you can generate an instance of that `std::function` like this 

```c++
emscripten::val cb = emscripten::val( functor )[ "onload" ].call<emscripten::val>( "bind", emscripten::val(functor) );
```

`functor` refers to a lambda function that you want to run in the callback. You can pass that to your Javascript through the `val` interface

```c++
 helpers.call<void>( "loadAssetAsync", cb );  
```

**Comment by gerald-dotcom** [comment]
> > > Ok - I think I can close this for now, I've figured out a no-so-elegant, but workable api for the time being. Essentially it involves adding some global static functions in-place of trying to call the `addEventListener` property of the element itself within the Javascript. Happy to share code if anyone is having trouble with this as well.
> > 
> > 
> > @sortofsleepy Hiya, Could you share the code with me?
> 
> @gerald-dotcom
> 
> I don't exactly remember what the solution I came up with here at this point and it's likely changed since I filed this issue, but this should work.
> 
> First off, you need to create a binding to a version of the `std::function` class like so
> 
> ```c++
> EMSCRIPTEN_BINDINGS( MyBindings ) {
> 	emscripten::class_<std::function<void(emscripten::val e)> >( "ListenerCallback" )
> 	.constructor<>()
> 	.function("onload", &std::function<void(emscripten::val e)>::operator() );
> };
> ```
> 
> After that, you can generate an usable `emscripten::val` object like this like this
> 
> ```c++
> emscripten::val cb = emscripten::val( functor )[ "onload" ].call<emscripten::val>( "bind", emscripten::val(functor) );
> ```
> 
> `functor` refers to a lambda function that matches the above binding description that you want to run in the callback. You can pass that to your Javascript through the `val` interface
> 
> ```c++
>  helpers.call<void>( "loadAssetAsync", cb );  
> ```

I'm not using class but thanks anyway. Just have one more question and would be great if you can sort that out for me.

How would one pass plain JS object to the exported function? 
Do I have to use Val as function parameter? 

JS Callback with Object you know it's not array, string, int or any kind of simple stuff... ...

**Comment by sortofsleepy** [comment]
> How would one pass plain JS object to the exported function?
> Do I have to use Val as function parameter?

I'm not totally sure what you're asking, are you asking how to pass back a JS object to your callback function?

To give a quick example - assuming you have all the callback passing set up  already, if this is your javascript function 
```javascript

function myJS(cb){
  cb({
   name:"Jane Doe",
   Age:"none"
});
}
``` 

Your object would come back as an `emscripten::val` object. You would then access keys like 
```c++
emscripten::val obj;

auto personName = obj["name"];
auto personAge = obj["Age"];

```

Note that those two variables would still be `emscripten::val` objects, you would have to use the appropriate conversion method to get those to their C++ counterparts.
