### ISSUE TITLE
Unity Demos / Dead Trigger 2: Broken link at best, phishing page at worst

### ISSUE THREAD

**Issue by n2liquid** [kripken/emscripten#7048]
Just noticed the link https://beta.unity3d.com/jonas/DT2/ (from the wiki: https://github.com/kripken/emscripten/wiki/Porting-Examples-and-Demos) takes me to a Facebook-clone page of sorts. Weird.

**Comment by kripken** [comment]
Thanks, yeah, something weird is going on with that old link. Replaced with the much more recent Tanks demo.
