### ISSUE TITLE
Running tests leaks temp files and directories.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#706]
I added the Windows bot to report the number of items in the temp folder before and after the test run. 

Looking at the recent runs of win-emcc-incoming-tests at http://clb.demon.fi:8112/waterfall shows the temp folder is still growing. From the three most recent Windows runs that all succeeded all the tests (so I think there shouldn't be a leak caused by an exception):

Note: Before starting test run, temp folder G:\tmp contains this many files: 582
 -- run tests --
Note: After test run finished, temp folder G:\tmp contains this many files: 859

Note: Before starting test run, temp folder G:\tmp contains this many files: 1136
 -- run tests --
Note: After test run finished, temp folder G:\tmp contains this many files: 1413

Note: Before starting test run, temp folder G:\tmp contains this many files: 1413
 -- run tests --
Note: After test run finished, temp folder G:\tmp contains this many files: 1690

At each run, the delta is exactly 277 items. The difference between 859 and 1136 is when the bot did a run on the master branch, and that delta is too exactly 277 items.

The current contents of the temp folder looks like this:
https://dl.dropbox.com/u/40949268/emcc/bugs/temp_directory_files.txt

**Comment by juj** [comment]
For a while, this issue disappeared, but I am now seeing this again on all of the Windows, Linux and OSX bots. I actually hard to format and reinstall the Linux system after the HDD got full, since it would not boot (!) anymore.

The problem we have is that in the global scope of `tools/shared.py`, we have code that creates the temp directories: https://github.com/kripken/emscripten/blob/incoming/tools/shared.py#L669

Since that code is in the global scope, it gets executed immediately when `import shared` is called from any script, i.e. importing shared.py immediately creates a temp directory, and registers an atexit handler to delete it.

The way that `multiprocessing` works to fork the child processes is that it spawns new python interpreters on the same main script as the parent, so when the parent has imported shared, then all the children also import shared, and all the children also create temp directories of their own. The bug(?) in python is that when these child processes join, the atexit handlers are not called.

However I'm not sure if this is actually a bug, since python does document that the scripts should play nice to be import safe, and shared.py behavior by creating a temp directory immediately on import is a bit evil. This behavior is similar to what was being handled in https://github.com/kripken/emscripten/pull/2903 , although in this case the behavior seems to not be restricted on Windows only. I've reported this issue to python as http://bugs.python.org/issue23489 , let's see what they say.

Is it necessary to create a temp directory immediately when shared.py is imported? Or would we have good locations to create the temp directory before any operation that needs it, and synchronously tear it down instead of using atexit?

**Comment by juj** [comment]
Actually, found a good way to create the temp dir on demand, see the above PR. After that, running `asm2` and `other` still leak 35 files and 6 folders on Windows, but that is a lot less than before.

**Comment by kripken** [comment]
Fixed by that PR, thanks.
