### ISSUE TITLE
USE_PTHREAD is not work

### ISSUE THREAD

**Issue by kokawa2003** [kripken/emscripten#7061]
I want to work my souce(FFMPEG+SDL and output video,audio) and compile it with USE_PTHREAD .

But not work
in Firefox it said in console:
ReferenceError: SharedArrayBuffer is not defined[詳細] SimpleFFPlayer.js:1163:3
detail is this:
if (!ENVIRONMENT_IS_PTHREAD) {
  Module['wasmMemory'] = new WebAssembly.Memory({ 'initial': TOTAL_MEMORY / WASM_PAGE_SIZE , 'maximum': TOTAL_MEMORY / WASM_PAGE_SIZE, 'shared': true });
  buffer = Module['wasmMemory'].buffer;
  assert(buffer instanceof SharedArrayBuffer, 'requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag');
}
Why ENVIRONMENT_IS_PTHREAD is off?
emscripten ver is 1.38.11

**Comment by kripken** [comment]
Firefox currently has SharedArrayBuffer off by default, because of the Spectre attacks. You can manually turn it on, though, by going to `about:config` and switching on `javascript.options.shared_memory`.

**Comment by kokawa2003** [comment]
i chaged  ver 1.38.9 and try about:config and switching on javascript.options.shared_memory in firefox
bit I got new error
  TypeError: invalid array type for the operation
detail 
`
var __pthread_is_main_browser_thread=0; var PThread={MAIN_THREAD_ID:1,mainThreadInfo:{schedPolicy:0,schedPrio:0},unusedWorkerPool:[],runningWorkers:[],initMainThreadBlock:function () {
        if (ENVIRONMENT_IS_PTHREAD) return undefined;
        PThread.mainThreadBlock = allocate(244, "i32*", ALLOC_STATIC);
  
        for (var i = 0; i < 244/4; ++i) HEAPU32[PThread.mainThreadBlock/4+i] = 0;
  
        // The pthread struct has a field that points to itself - this is used as a magic ID to detect whether the pthread_t
        // structure is 'alive'.
        HEAP32[(((PThread.mainThreadBlock)+(24))>>2)]=PThread.mainThreadBlock;
  
        // pthread struct robust_list head should point to itself.
        var headPtr = PThread.mainThreadBlock + 168;
        HEAP32[((headPtr)>>2)]=headPtr;
  
        // Allocate memory for thread-local storage.
        var tlsMemory = allocate(128 * 4, "i32*", ALLOC_STATIC);
        for (var i = 0; i < 128; ++i) HEAPU32[tlsMemory/4+i] = 0;
        Atomics.store(HEAPU32, (PThread.mainThreadBlock + 116 ) >> 2, tlsMemory); // Init thread-local-storage memory array.
        Atomics.store(HEAPU32, (PThread.mainThreadBlock + 52 ) >> 2, PThread.mainThreadBlock); // Main thread ID.
        Atomics.store(HEAPU32, (PThread.mainThreadBlock + 56 ) >> 2, PROCINFO.pid); // Process ID.
`
and stop in
        Atomics.store(HEAPU32, (PThread.mainThreadBlock + 116 ) >> 2, tlsMemory); // Init thread-local-
storage memory `array.`

**Comment by varun-elear** [comment]
pthread works for me after I followed these two steps:

1. Install Firefox Nightly and by going to about:config and switching on javascript.options.shared_memory.
2. Use the below mentioned flags while compiling to wasm 
-s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2

**Comment by thomasjammet** [comment]
I think you should update firefox to firefox nightly last version (see [the comment here](https://github.com/WebAssembly/binaryen/issues/1419#issuecomment-408434526))

**Comment by kokawa2003** [comment]
Ok It worked ,thank you
