### ISSUE TITLE
Cross-compiling meson with emscripten

### ISSUE THREAD

**Issue by Eric-Ryan** [kripken/emscripten#7070]
I am cross compiling meson using the emscripten compiler  and when I run it I get an error telling me I need a 32-bit version of the Emscripten compiler:
```
    meson.build:17:0: ERROR:  Unknown compiler(s): [['../../../emsdk/emscripten/1.38.11/em++.py']]
    The follow exceptions were encountered:
    Running "../../../emsdk/emscripten/1.38.11/em++.py --version" gave "[WinError 193] %1 is not a valid Win32 application"
```
I read that emscripten stopped supporting 32-bit on Windows. So this means I have to manually build it from source using this page: https://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_windows.html
Does this seem correct?

**Comment by kripken** [comment]
Yeah, we don't have 32-bit windows builds any more, so you'd need to build yourself. However, in addition I think that error is a separate issue: I think it's trying to execute `em++.py` and failing, as that's a python script, not an executable. You might need to get the build system to run `python em++.py` instead (with python in the path, or a full path to it).
