### ISSUE TITLE
Incorrect parsing EXPORTED_FUNCTIONS as response file

### ISSUE THREAD

**Issue by binji** [kripken/emscripten#7073]
If you pass a response file to `-s EXPORTED_FUNCTIONS`, and give it json like this:
```
[
"_name1",
"_name2"
]
```

Then `name2` is ignored. See https://github.com/WebAssembly/wabt/issues/904, for an example of this.

It looks like `parse_string_list_members` doesn't properly handle the case where the final name ends with a newline instead of a comma.

**Comment by kripken** [comment]
Ah, I think I opened a PR for that just yesterday, #7067. Not on response files specifically, but I verified it fixes that too. I'll add a test there.
