### ISSUE TITLE
emcc created executables are not runnable 

### ISSUE THREAD

**Issue by Eric-Ryan** [kripken/emscripten#7086]
Currently trying to build meson using emscripten compiler. It uses NodeJS as an exe wrapper. This is my cross-file:
```
[binaries]
c = ['C:/Program Files/Python36/python.exe', 'C:/Users/eric/emsdk/emscripten/1.38.11/emcc.py']
cpp = ['C:/Program Files/Python36/python.exe', 'C:/Users/eric/emsdk/emscripten/1.38.11/em++.py']
ar =['C:/Program Files/Python36/python.exe', 'C:/Users/eric/emsdk/emscripten/1.38.11/emar.py']
exe_wrapper = 'node'
```
When I run I get this error saying that emcc.py created executables are not runnable:
```
meson.build:17:0: ERROR:  Executables created by cpp compiler C:/Program Files/Python36/python.exe C:/Users/eric/emsdk/emscripten/1.38.11/em++.py are not runnable.
```

**Comment by kripken** [comment]
If a build system expects to execute programs it created itself, that can be tricky for cross compilers like emscripten, see

http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#build-system-self-execution

In general, you may need to modify the build system in that case.

However, I'd first see exactly what "are not runnable" means in that build system. If you told it to use node to run the program, perhaps it just has a typo in the path, or something else is going wrong?
