### ISSUE TITLE
MODULARIZE_INSTANCE: Missing EXPORT_NAME argument in IIFE call

### ISSUE THREAD

**Issue by MikeMcl** [kripken/emscripten#7101]
Emscripten 1.38.11
`emcc libfoo.a -s WASM=1 -s EXPORT_NAME="Foo" -s MODULARIZE_INSTANCE=1 -o foo.js`

Emitted:
```js
var Foo = (
function(Foo) {
  Foo = Foo || {};
  var Module = typeof Foo !== 'undefined' ?  Foo : {};
  // .. all rest of the emitted code from emscripten ..
  return Module;
}
)(/* Foo could be passed here, but isn't. */);
```

The immediately-invoked function expression (IIFE) includes the `EXPORT_NAME` parameter, `Foo`, but no argument is passed when the IIFE is called, so the parameter shadows a `Foo` in the global scope. This means that, for example, any existing assignment to `Foo.onRuntimeInitialized` will be lost when the emitted code is executed.

A fix:

```js
var Foo = (
function(Foo) {
  var Module = Foo || {};
  // .. all rest of the emitted code from emscripten ..
  return Module;
}
)(typeof Foo !== 'undefined' ? Foo : {});
```

**Comment by kripken** [comment]
Interesting question!

I tend to think we don't want to allow people modifying things on `Foo` before that call. At least that wasn't my intention here, and it adds complexity. But open to other opinions here.

**Comment by MikeMcl** [comment]
Currently if we do

```bash
emcc libfoo.a -s WASM=1 -s MODULARIZE_INSTANCE=1 -o index.html
```

then the emitted script in `index.html` defines and adds properties to `Module` before the generated `index.js` is loaded. 

The problem is that `index.js` contains its own definition of `Module` which overwrites the original, so all the properties defined below are lost. This means that `index.html` does not currently work, the page just hangs at the message `"Downloading..."` and inspection of the `Module` object in the console shows that the originally defined properties are not present.  



```html
<script type='text/javascript'>
  var statusElement = document.getElementById('status');
  var progressElement = document.getElementById('progress');
  var spinnerElement = document.getElementById('spinner');

  var Module = {
    preRun: [],
    postRun: [],
    print: (function() {
      var element = document.getElementById('output');
      if (element) element.value = ''; // clear browser cache
      return function(text) {
        if (arguments.length > 1) text = Array.prototype.slice.call(arguments).join(' ');

    // ...       

    monitorRunDependencies: function(left) {
      this.totalDependencies = Math.max(this.totalDependencies, left);
      Module.setStatus(left ? 'Preparing... (' + (this.totalDependencies-left) + '/' + this.totalDependencies + ')' : 'All downloads complete.');
    }
  };
  Module.setStatus('Downloading...');
  window.onerror = function(event) {
    // TODO: do not warn on ok events like simulating an infinite loop or exitStatus
    Module.setStatus('Exception thrown, see JavaScript console');
    spinnerElement.style.display = 'none';
    Module.setStatus = function(text) {
      if (text) Module.printErr('[post-exception status] ' + text);
    };
  };
</script>
<script async type="text/javascript" src="index.js"></script>
```

The solution I advocated in the post above, would fix this problem because the original `Module` gets passed to the IIFE.

It would make things more flexible as users could define propertries on a `Module` or an `EXPORT_NAME` object in a script within the HTML before the Emscripten-emitted code gets asynchronously loaded. 

Currently, the line in the code shown below

```js
var Module = (
function(Module) {
  Module = Module || {};    // <--
`` 
makes little sense because `Module` will always be undefined as nothing is passed to the IIFE.

**Comment by kripken** [comment]
I see what you mean. However, the case of defining Module in the HTML is typical for apps that run on the entire page, while modularize is usually used for things that are components in something bigger. So while I agree that it's a bug that they don't work together, perhaps we should differentiate the use cases in a better way to avoid this.

Specifically, perhaps HTML output should not be allowed when modularize_instance is used - as we have `Module` hard-coded in the HTML anyhow there?

**Comment by kripken** [comment]
@MikeMcl Good point, yeah. Thinking more on this, I agree that we want MODULARIZE_INSTANCE to notice the Module object. I opened #7293 to fix this.
