### ISSUE TITLE
Emscripten CUDA Compiler integration

### ISSUE THREAD

**Issue by Merg1255** [kripken/emscripten#711]
I'd like to ask if it's possible, and in your plans, to add support for cuda code to be able to have gpu acceleration. I think CSS already does that, so can there be an API or something that will enable this? https://developer.nvidia.com/cuda-llvm-compiler

Thanks

**Comment by juj** [comment]
Closing this as unresolvable, CUDA is not an API we could support likely without extensive emulation. I don't think CUDA is translatable to WebCL. OpenCL though should be translatable to WebCL, so if someone wants to champion OpenCL -> WebCL compilation support, that sounds feasible, like @jroweboy mentioned in the earlier comment. Pull requests for that are welcome! Although I'm not sure what the activity status of WebCL itself is even, and how feature capable that is in comparison with OpenCL.
