### ISSUE TITLE
wasm is not generated on Windows 7 32 bit

### ISSUE THREAD

**Issue by stasoid** [kripken/emscripten#7124]
I installed Emscripten on Windows 7 32 bit as described [here](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html) and tried [this example](https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm). That is, I compiled like this:
```
emcc hello.c -s WASM=1 -o hello.html
```
It creates `hello.html` and `hello.js`, but not `hello.wasm`.

The same sequence of actions on Fedora 26 64 bit works as expected, creates `hello.wasm`.

Is it by design? Is wasm generation supported on 32 bit Windows?

**Comment by kripken** [comment]
It should work the same across platforms. I'd check which version you installed, maybe an older one was in the path or something like that, run `emcc -v`.

**Comment by stasoid** [comment]
`emcc -v` prints:
```
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.12.0
clang version 3.2 (tags/RELEASE_32/final 170916)
Target: i686-pc-win32
Thread model: posix
```
The version corresponds to what is in `emsdk`: `emsdk\emscripten\1.12.0`.
`where emcc` reports correct `emcc` location.
Paths in `C:\Users\<user>\.emscripten` are also correct.

**Comment by kripken** [comment]
1.12.0 is very old, it's from 4.5 years ago - before wasm existed.

As I said before, one possibility is you have another version in the path. Otherwise, look for the emscripten subdir under the emsdk folder, it should contain the version, and if you install `latest` it should be 1.38.12 or so.

**Comment by kripken** [comment]
If the emsdk folder shows 1.12.0, then perhaps the emsdk didn't update properly (git pull failed?). Installing `latest` as in the docs should get you 1.38.12 or so. You can also try to manually request that version.

**Comment by stasoid** [comment]
Yes, I installed latest (`emsdk install latest`), but it pulled this old version for some reason.

**Comment by stasoid** [comment]
How can I request exact version?

**Comment by kripken** [comment]
`emsdk list` shows all the versions and builds etc., then you can `emsdk install [..]` one of those (like `emscripten-1.38.12` which I see in the list for my machine here).

**Comment by kripken** [comment]
See `emsdk --help` for more options.

**Comment by stasoid** [comment]
I was able to install emscripten-1.38.12, but it still fails because all other tools are old and incompatible with the new emscripten. `emsdk list` shows that precompiled clang and sdk-1.38.12 are available only for 64 bit. So I tried to use `sdk-tag-1.38.12-32bit` which is compiled from source, and it failed while trying to build clang. I am not sure I want to dig so deep.

I believe the reason why `emsdk install latest`  installed version 1.12.0 is because `sdk-1.12.0-32bit` is the last available 32 bit precompiled distro, see `emsdk list --old`.

I don't understand how sdk-1.38.12 is supposed to work on 32 bit if there is no precompiled sdk-1.38.12 and clang-e1.38.12 for 32 bit. 

Going to sleep now...

Output of `emsdk list`:
```

The following precompiled tool packages are available for download:
           clang-e1.30.0-64bit      
           clang-e1.34.1-64bit      
           clang-e1.35.0-64bit      
           clang-e1.37.1-64bit      
           clang-e1.38.11-64bit     
           clang-e1.38.12-64bit     
           node-4.1.1-32bit         
           node-4.1.1-64bit         
           node-8.9.1-32bit         
           node-8.9.1-64bit         
           python-2.7.13.1-32bit    
           python-2.7.13.1-64bit    
           python-3.5.4-32bit       
           python-3.5.4-64bit       
           java-7.45-32bit          
           java-7.45-64bit          
           java-8.152-32bit         
           java-8.152-64bit         
           spidermonkey-37.0.1-64bit
           spidermonkey-nightly-2015-04-12-64bit
           git-1.9.4                
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        
           emscripten-1.37.1        
           emscripten-1.38.11       
           emscripten-1.38.12       
           vs-tool-0.9.4            
           crunch-1.03              
           gnu-2.5.4                
           mingw-7.1.0-64bit        

The following tools can be compiled from source:
           clang-tag-e1.38.11-32bit 
           clang-tag-e1.38.12-32bit 
           clang-tag-e1.38.11-64bit 
           clang-tag-e1.38.12-64bit 
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
           clang-master-64bit       
           upstream-clang-master-32bit
           upstream-clang-master-64bit
           emscripten-tag-1.38.11-32bit
           emscripten-tag-1.38.12-32bit
           emscripten-tag-1.38.11-64bit
           emscripten-tag-1.38.12-64bit
           binaryen-tag-1.38.11-32bit
           binaryen-tag-1.38.12-32bit
           binaryen-tag-1.38.11-64bit
           binaryen-tag-1.38.12-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
           emscripten-master-64bit  
           binaryen-master-32bit    
           binaryen-master-64bit    

The following precompiled SDKs are available for download: (Run "git pull" followed by "./emsdk update-tags" to pull in the latest list)
         sdk-1.30.0-64bit         
         sdk-1.34.1-64bit         
         sdk-1.35.0-64bit         
         sdk-1.37.1-64bit         
         sdk-1.38.11-64bit        
         sdk-1.38.12-64bit        

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
         sdk-master-64bit         
         sdk-tag-1.38.11-32bit    
         sdk-tag-1.38.12-32bit    
         sdk-tag-1.38.11-64bit    
         sdk-tag-1.38.12-64bit    

Items marked with * are activated for the current user.

To access the historical archived versions, type 'emsdk list --old'

```

**Comment by kripken** [comment]
Oh, yes, we may no longer have prebuilt 32-bit windows builds. So you would need to build from source (or use a VM or some other option).

**Comment by stasoid** [comment]
Got it, thank you.
