### ISSUE TITLE
asm2wasm error when trying to use emterpretify_async with emterpretify_whitelist

### ISSUE THREAD

**Issue by Sgeo** [kripken/emscripten#7146]
Not sure how to get a reduced code sample, I'm trying to port VICE

<code>
asm2wasm: /home/ubuntu/emslave/buildslave/ubuntu-tagbuilder/emsdk/binaryen/tag-1.38.11/src/asm2wasm.h:2247: wasm::Asm2WasmBuilder::processFunction(cashew::Ref)::<lambda(cashew::Ref)>: Assertion `target[0] == SUB && target[1]->isString() && target[2][0] == BINARY && target[2][1] == AND && target[2][3]->isNumber()' failed.
</code>

**Comment by Sgeo** [comment]
Possibly relevant: The asm.js build sometimes causes this error in Firefox:
`TypeError: asm.js type error: function-pointer table index expression needs & mask`

**Comment by kripken** [comment]
To get a reduced sample, build with `EMCC_DEBUG=1` in the env. That will create a temp file `/tmp/emscripten_temp/*.asm.js` file that can be used to reproduce the issue. Or, you can provide the bitcode file + command, that's good enough.

Is that asm.js error in the second comment when building just to asm.js, or when building to wasm in some form? If just asm.js, that's definitely a bug (if it's intermediate asm2wasm output, that is not expected to be valid asm.js).

**Comment by Sgeo** [comment]
[x64.temp.asm.zip](https://github.com/kripken/emscripten/files/2399027/x64.temp.asm.zip)
Attached is temp result from EMCC_DEBUG=1. There are a LOT of bitcode files, not sure its practical to provide them.

The asm.js was from building just to asm.js.

**Comment by Sgeo** [comment]
Compilation to WASM works fine on -O1, and not -O2 (or -O3, which is where the attached file comes from)

**Comment by kripken** [comment]
Thanks, looks like this has hit an interesting corner case in the localCSE JS optimizer pass. Fix in #7157
