### ISSUE TITLE
Wrong behavior on iOS 11 + Safari after update from 1.38.8 to 1.38.12

### ISSUE THREAD

**Issue by MarcelKlammer** [kripken/emscripten#7147]
After upgrading from 1.38.8 to v1.38.12 I noticed wrong behavior.

But only on iOS 11 Safari. All desktop browsers and Android Chrome are fine.

I've uploaded the same app as

a.html (compiled with v1.38.12)
b.html (compiled with v1.38.8)

Loads quite a lot, just wait for it to start the camera after load finishes:
[version a](https://tastenkunst.s3.amazonaws.com/demos/tk/artov4/emcc_test/a.html)
[version b](https://tastenkunst.s3.amazonaws.com/demos/tk/artov4/emcc_test/b.html)

On my iPhone X + Safari version a doesn't work as it should (like version b). 
So something did went probably wrong with the types update.

Any hint on what were to look first? Since it's not totally broken, but moves into the correct direction it might be related to my image types (all uint8_t grayscale types).

It get's compiled with those (partly redacted)

python "${EXEC_EMSCRIPTEN}" \
...
-O3 \
-g0 \
-s EXPORTED_FUNCTIONS="[ \
'_main', \
'_malloc', \
...
]" \
-s EXTRA_EXPORTED_RUNTIME_METHODS="['stringToUTF32', 'lengthBytesUTF32', 'cwrap', 'Pointer_stringify', 'dynCall']" \
-s "EXPORT_NAME='brfv4SDK'" \
-s MODULARIZE=1 \
-s TOTAL_MEMORY=268435456 \
-s TOTAL_STACK=2097152 \
-s ALLOW_MEMORY_GROWTH=1 \
-s DISABLE_EXCEPTION_CATCHING=1 \
-s USE_PTHREADS=0 \
-s NO_FILESYSTEM=1 \
-s NO_EXIT_RUNTIME=1 \
-s AGGRESSIVE_VARIABLE_ELIMINATION=1 \
-s ASSERTIONS=0 \
-s STRICT=1 \
-s WASM=1 \
-s "ENVIRONMENT='web'" \
-s BINARYEN_ASYNC_COMPILATION=1 \
-s "BINARYEN_TRAP_MODE='clamp'" \
-s "BINARYEN_METHOD='native-wasm'" \
-o "${FILE_JS_LIBRARY_TARGET}.js"

**Comment by MarcelKlammer** [comment]
Testing both on again on Android I noticed a FPS drop on Chrome on Android.

On a Samsung Galaxy S9:
version a is only 14 to 15 FPS where as version b is 20 to 23 FPS. So there is a degeneration there as well.

**Comment by kripken** [comment]
I'm not aware of any bugs that could explain that, so I'd recommend brute force (bisecting to find the breaking commit or at least version).

**Comment by MarcelKlammer** [comment]
version d (compiled with v1.38.11, working as normal)

[version d](https://tastenkunst.s3.amazonaws.com/demos/tk/artov4/emcc_test/d.html)

So it must be a commit leading from 1.38.11 to 1.38.12.

**Comment by MarcelKlammer** [comment]
@kripken: Not as obvious, so I'm asking whether it's true: Setting a specific commit in a repo fork will include a emcc that was built with all changes up until this commit? Or do I need to generate my own emcc once I checkout that specific commit?

**Comment by kripken** [comment]
Which repo do you mean?

For bisecting something like this, you might be able to avoid building llvm+clang from source. You can check out emscripten from source using git, and do git bisect on it, and for each version of emscripten you can get the llvm+clang using the emsdk. (However, if you do need to bisect into llvm+clang, then you would need to build those from source.)

**Comment by MarcelKlammer** [comment]
hmm... so I tried every commit up to incomming in the forked repos... then went back to my usual emscripten setup, activated 1.38.12 on both, clang and emscripten... set the paths and now its working on iOS like normal...

I will keep an eye on that, but I can't seem to reproduce it.
