### ISSUE TITLE
NO_EXIT_RUNTIME=1 is broken

### ISSUE THREAD

**Issue by kumpera** [kripken/emscripten#7148]
Building with -s NO_EXIT_RUNTIME=1 seems to be broken with incoming.
I'm building with -s NO_EXIT_RUNTIME=1 , yet calling `exit(0)` from a shell program produces this:

```
exit(0) called, but NO_EXIT_RUNTIME is set, so halting execution but not exiting the runtime or preventing further async execution (build with NO_EXIT_RUNTIME=0, if you want a true shutdown)
```

**Comment by kripken** [comment]
That is the expected behavior (when ASSERTIONS is on, which is the case in `-O0` by default). But perhaps this is not documented well (in particular, the `NO_` prefix may be confusing)? What specifically does not make sense to you?

**Comment by kumpera** [comment]
The warning message makes little sense, it contradicts the compilation flags I passed.

 I'm tracking down on what looks like a subtle change in how loading happens and ran into this.

**Comment by kripken** [comment]
Sorry, I don't understand? You say you built with `NO_EXIT_RUNTIME=1`, and the error message mentions `NO_EXIT_RUNTIME is set` which is consistent with that, and also suggests changing that to `NO_EXIT_RUNTIME=0` if instead you want different behavior - ?

**Comment by kumpera** [comment]
I see your point 🤦‍♂️, yes, the message is not the clearest, but it's correct.
