### ISSUE TITLE
Build instructions generate incomplete build

### ISSUE THREAD

**Issue by osen** [kripken/emscripten#7161]
Hi all,
After a fresh compile of Emscripten I am greeted with the following error:

`WARNING:root:retrieving port: binaryen from https://github.com/WebAssembly/binaryen/archive/version_51.zip
ERROR:root:a problem occurred when using an emscripten-ports library. try to run    emcc --clear-ports    and then run this command again`

This obviously only occurs when I am running emscripten offline (which is quite a common usecase). Is there a reason why Emscripten requires this runtime dependency to be dragged in via the internet? For example Clang, GCC, Microsoft C++ do not fetch runtimes from the internet in this manner. It feels a little bit sloppy and non-deterministic to me. One of the reasons why I use C++ rather than JavaScript NPM and Python PIP is to get away from potential versioning mess that this kind of dependency handling can cause.

Perhaps two solutions?
1) Provide a fixed version of the binaryen "emscripten port" with the main build
2) Since this is only required for webassembly, perhaps have a flag to compile only for asm.js?

Many thanks for your consideration!

**Comment by osen** [comment]
Ugh, ignore my noise, I have just seen "BINARYEN_ROOT" in the .emscripten config file.

Apologies.

Would you perhaps like me to update the build instructions on the Wiki to include the binaryen component?

**Comment by kripken** [comment]
Thanks, yes, we should document that in relevant places.
