### ISSUE TITLE
JS output when using Main_Module uses synchronous WebAssembly calls

### ISSUE THREAD

**Issue by chrjohnson** [kripken/emscripten#7173]
I've been trying to get a Main_Module and Side_Module working for a while and was finally able to get it going in Firefox. The following is the command line I used for the side_module: 
`emcc side.cpp -s SIDE_MODULE=2 -s WASM=1 -O1 -o side.wasm -s LINKABLE=1`

The following is the command line I used for the main_module to get an html template:
`emcc main.cpp -s MAIN_MODULE=2 -s WASM=1 -O1 --pre-js pre.js -o main.html -s LINKABLE=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['UTF8ToString']"`

The pre.js file holds: `Module.dynamicLibraries = ['side.wasm'];`

The main method in main.wasm calls a method that is in side.wasm returning a string. The main method then does an EM_ASM macro call to console.log the string. This works fine in Firefox but Chrome is complaining that WebAssembly.Compile is disallowed on the main thread.

Looking through the generated JavaScript of main.js and it differs from a non-MAIN_MODULE generated file. Here it uses WebAssembly.Instance and WebAssembly.Module while a non-MAIN_MODULE generated JS file uses WebAssembly.instantiate and WebAssembly.instantiateStreaming.

Is there a flag that I'm missing to instruct Emscripten to use the asynchronous WebAssembly JS API calls rather than the synchronous ones when compiling as a MAIN_MODULE?

I've tried using the `-s BINARYEN_ASYNC_COMPILATION=1` flag but the command line says that it was disabled due to user options.

**Comment by kripken** [comment]
Which version is that on? We improved this fairly recently, I think async compilation for the main module should not be disabled, and for side modules there is a new API (see #6663).

**Comment by chrjohnson** [comment]
emscripten 1.38.5

**Comment by kripken** [comment]
Makes sense, yeah, those were more recent additions. Should be ok on latest tag (1.38.12).

**Comment by chrjohnson** [comment]
I haven't quite got it working yet but I see the changes in the JS with the latest version of emscripten. 

Is dlopen the recommended way to do dynamic linking with side_modules renamed from .wasm to .so or is the following acceptable too but just won't be async (loadWebAssemblyModule has a new 2nd param for loadAsync that isn't included when using the following approach unless I'm missing something)? 
Module.dynamicLibraries = ['side.wasm'];

**Comment by kripken** [comment]
Both ways can work - just like with native dynamic linking, you can either link it to the program before running, or you can dlopen it at runtime. We have test coverage on both, neither is preferred.

**Comment by chrjohnson** [comment]
Thank you. Very helpful.

Do you know if the Module.dynamicLibraries approach will eventually use the async JS methods like with dlOpen? (perhaps a flag of some sort could be set by the developer when specifying the list of modules to load so that using async doesn't break existing apps.)

**Comment by kripken** [comment]
It could be extended that way, I think. The code in `preamble.js` allows doing the whole process asynchronously (see the comment `if we can load dynamic libraries synchronously, do so, otherwise, preload`), but it doesn't do it asynchronously internally yet.

**Comment by chrjohnson** [comment]
ok. Thank you.
