### ISSUE TITLE
Occasional python crash in multiprocessing\forking.py on Windows.

### ISSUE THREAD

**Issue by SiggyBar** [kripken/emscripten#718]
With the latest version of Emscripten from the incoming branch, I get this crash maybe one out of three times when compiling with emcc:

```
Exception WindowsError: WindowsError(5, 'Access is denied') in <Finalize object, dead> ignored
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\tools\Python26\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\tools\Python26\lib\multiprocessing\util.py", line 277, in _exit_function
    p._popen.terminate()
  File "C:\tools\Python26\lib\multiprocessing\forking.py", line 274, in terminate
    _subprocess.TerminateProcess(int(self._handle), TERMINATE)
WindowsError: [Error 5] Access is denied
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\tools\Python26\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\tools\Python26\lib\multiprocessing\util.py", line 277, in _exit_function
    p._popen.terminate()
  File "C:\tools\Python26\lib\multiprocessing\forking.py", line 274, in terminate
    _subprocess.TerminateProcess(int(self._handle), TERMINATE)
WindowsError: [Error 5] Access is denied
```

**Comment by juj** [comment]
This should have been fixed some time ago, and also another call site with the same kind of issue should also be fixed (#4404), so we should no longer be seeing Access is Denied errors on Windows (when tearing down multiprocessing pools).

**Comment by pemryan** [comment]
still happening occasionally on Python 3.8.5 @ Windows10

**Comment by jeffRTC** [comment]
@juj I hit this problem  on Python 3.9

Since you guys removed msi installer, I had to restore manual jargon :((

**Comment by sbc100** [comment]
You mean an MSI installer for emsdk?   I don't remember emsdk ever having such a thing but it could just be before my time (in which case we stopping a long time ago).    Or perhaps there was an MSI build that was maintained outside the core project?
If you like windows installers maybe you will like recent chocolaty package that was recently added.

**Comment by kripken** [comment]
I think @juj maintained an MSI installer many years ago, but I'm not aware of anyone using one currently.

Chocolatey as mentioned is an option, and also the [normal download instructions](https://emscripten.org/docs/getting_started/downloads.html).

**Comment by jeffRTC** [comment]
@sbc100  @kripken  MSI installer was on your Docs on 2020 

It had green logo on left side when launched.

**Comment by jeffRTC** [comment]
I'm 99% sure I didn't time travel

**Comment by kripken** [comment]
It's possible the docs were outdated, sorry about that. They look accurate now at least.
