### ISSUE TITLE
MAIN_MODULE=3 to Whitelist Exported Functions

### ISSUE THREAD

**Issue by awtcode** [kripken/emscripten#7189]
@kripken , one of the reasons why the number of exported functions is large for a main module is because we cannot differentiate between a system module and a user-implemented module. Thus, we end up exporting everything. 

Would it make sense to introduce a MAIN_MODULE=3 whereby all functions are hidden by default and only those that are exported explicitly will be exposed? We can always get the list of C++ std functions by building a dummy main module with MAIN_MODULE=1 and add that list to the whitelist. This would be similar to DISABLE_EXCEPTION_CATCHING where we have a mode 2 to specify functions that should have exceptions enabled.

Can you let me have your thoughts on this proposal? Thanks.

**Comment by kripken** [comment]
> we cannot differentiate between a system module and a user-implemented module

What do you mean here specifically?

> Would it make sense to introduce a MAIN_MODULE=3 whereby all functions are hidden by default and only those that are exported explicitly will be exposed?

How does that differ from the currently-existing mode 2?

**Comment by awtcode** [comment]
I was thinking of the following code:

`def get_exported_implemented_functions(all_exported_functions, all_implemented, metadata):
  funcs = set(metadata['exports'])
  export_bindings = shared.Settings.EXPORT_BINDINGS
  export_all = shared.Settings.EXPORT_ALL
  for key in all_implemented:
    if key in all_exported_functions or export_all or (export_bindings and key.startswith('_emscripten_bind')):
      funcs.add(key)`

whereby both std C++ functions and user-implemented functions are exported by default when using MAIN_MODULE because shared.Settings.EXPORT_ALL is always set to True for MAIN_MODULE. The reason being that we cannot differentiate between std C++ and user functions at this point of the compilation.

We could set shared.Settings.EXPORT_ALL to False even for MAIN_MODULE and use EXPORTED_FUNCTIONS to specify the std C++ functions we want to export. The list could be obtained by building a program with MAIN_MODULE=1 if necessary.

The difference with MAIN_MODULE=2 is that user-implemented functions will not be exported by default.

@kripken , please let me know if the above needs more clarifications. Thanks.

**Comment by awtcode** [comment]
@kripken , by the way, the motivation for having MAIN_MODULE=3 is to reduce the inter-wasm calls between the main module (which contains only the std c++ functions) and the side module because the performance is rather slow and it would also help to reduce the code size if we did not have to export all the std C++ functions as well.

**Comment by awtcode** [comment]
@kripken , sorry to trouble you again. did you get the chance to look at this?
