### ISSUE TITLE
Extending an Embind CPP class to a JS class

### ISSUE THREAD

**Issue by robfors** [kripken/emscripten#7200]
It would be nice if I could extend a CPP class to JS classes.

Example:
In this case I have ```CPPBaseClass``` that has been exposed to JS with Embind.
I don't need the CPP envirmonment to know about any of the JS subclasses.
```js
C = class extends Module.CPPBaseClass {}
c = new C; // => Uncaught BindingError {name: "BindingError", message: "Use 'new' to construct CPPBaseClass" ...
```
After making a replacment to ```embind.js``` it seems to do what I want:
```diff
- if (Object.getPrototypeOf(this) !== instancePrototype) {
+ if (this instanceof registeredClass.constructor) {
    throw new BindingError("Use 'new' to construct " + name);
  }
```

What are your thoughts? Is this a reasonable change or will it break something?

I can make a PR and add some tests, but i`m not sure how to run the test for ```embind.test.js```.

**Comment by kripken** [comment]
cc @chadaustin

**Comment by chadaustin** [comment]
That check dates back to https://github.com/kripken/emscripten/commit/d53d8001aaa3666eb6de40fec25dbec338a75c81

The check seems fine to me - instanceof just walks the prototype chain, right?

I'd be fine with a PR and some pull requests.

I'd suggest checking the various combinations of deriving twice and calling super or not at each level and verifying they all behave as you'd expect.

Thanks!

**Comment by robfors** [comment]
Can someone tell me how to run the tests in `embind.test.js`? I forced one of the tests to fail and ran `python tests/runner.py test_*` but nothing relevant came up.

**Comment by kripken** [comment]
Looks like that test is references in `tests/test_other.py`, and it's used when running `other.test_embind`.

**Comment by robfors** [comment]
I tried running `python tests/test_other.py other.test_embind` and `python tests/test_other.py` but it tells me `ImportError: No module named tools.shared`.
The `tools` directory, it's `__init__.py` and `shared.py` all exist. Do you have any ideas why it would not run?
I also tried `python3 tests/test_other.py other.test_embind` and it gave me `ModuleNotFoundError: No module named 'tools'`.

**Comment by kripken** [comment]
Yes, sorry, to run it do `python tests/runner.py other.test_embind`. (in other words, `other.test_embind` is an argument to the main test runner)

**Comment by robfors** [comment]
I attempted to implement this change in by branch [js_extend](/robfors/emscripten/tree/js_extend). But it seems that there is more to the problem than that prototype check. I found that the prototype of the instance of any derived class is set to the baseclass's prototype. So I can set static methods on derived classes but instance methods are of the baseclass's.
This feature is beyond my capability so I think I will leave is alone.

**Comment by chadaustin** [comment]
Thanks for the attempt, @robfors. I got my Emscripten environment up and running again and thought I'd take a look myself.

It's been a long time since I've looked at embind in depth. (And it's more complicated than I remember. :joy:) 

This test passes without any changes to embind itself:

```
        test("pass derived object to c++", function() {
            class Implementation extends cm.AbstractClass.extend("Implementation", {}) {
                abstractMethod() {
                    return "abc";
                }
            }
            var instance = new Implementation;
            var result = cm.callAbstractMethod(instance);
            instance.delete();
            assert.equal("abc", result);
        });
```

I know that's not exactly what you were trying to do here, but it's worth noting.

If you're up for another shot, feel free to ask about any embind details.

**Comment by shrinktofit** [comment]
Same question here :(
