### ISSUE TITLE
WASM + USE_PTHREADS doesn't work with SAFE_HEAP

### ISSUE THREAD

**Issue by VirtualTim** [kripken/emscripten#7208]
Compiling an empty cpp file with `emcc blank.cpp -s WASM=1 -s USE_PTHREADS=1 -s SAFE_HEAP=1 -o blank.html` fails with 
> ERROR:root: '/binaryen/bin/wasm-opt blank.wasm.pre -o blank.wasm --safe-heap' failed

This occurs with Emscripten 1.38.12. Compiling with -v doesn't return any useful information.

**Comment by kripken** [comment]
Thanks, looks like SafeHeap was emitting some invalid code. Fix in https://github.com/WebAssembly/binaryen/pull/1693
