### ISSUE TITLE
alcGetString is not defined in emscripten_alcGetStringiSOFT?

### ISSUE THREAD

**Issue by lamelizard** [kripken/emscripten#7210]
Peace,

I'm trying to get the HRTF specifiers like this:
```	
ALCint specifierAmount = 0;
alcGetIntegerv(aldevice, ALC_NUM_HRTF_SPECIFIERS_SOFT, 1, &specifierAmount);
hasError();
for (ALCint i = 0; i < specifierAmount; i++) {
	const ALCchar *specifier = alcGetStringiSOFT(aldevice, ALC_HRTF_SPECIFIER_SOFT, i);
	if (specifier)
		specifiers.push_back(specifier);
}     
```
But I get the error 
> ReferenceError: alcGetString is not defined

in

> _emscripten_alcGetStringiSOFT

[(it apparently gets called if the index is 0) ](https://github.com/kripken/emscripten/blob/20602efb955a7c6c20865a495932427e205651d2/src/library_openal.js#L2674)
Calling `alcGetString` myself works fine.

I'm using Firefox 62 and Emscripten 1.38.12

**EDIT**: [apparently](https://github.com/kripken/emscripten/blob/20602efb955a7c6c20865a495932427e205651d2/src/library_openal.js#L2662) `alcGetString` shouldn't get called? I do have `#define ALC_HRTF_SPECIFIER_SOFT                     0x1995`...

**Comment by kripken** [comment]
That should be fixed by #7270, but without a testcase I'm not 100% sure - @lamelizard, can you please confirm?

**Comment by lamelizard** [comment]
I manually patched my library_openal.js according to your patch.
The ReferenceError is gone, but...
alcGetStringiSOFT seems to set the ALC error for invalid enum.
I used `EM_ASM_({ console.log('ALC_HRTF_SPECIFIER_SOFT: ' + $0); }, ALC_HRTF_SPECIFIER_SOFT);` and I got that `ALC_HRTF_SPECIFIER_SOFT = 6549 (= 0x1995)` (`aldevice = 1`, `i = 0`)...
alcGetStringiSOFT returns `0` instead of an string.

**Comment by kripken** [comment]
I'm not familiar with this API - is that a separate bug? Or does it mean my PR should not be landed?

**Comment by lamelizard** [comment]
The PR managed to let me call the function without resulting in an (Javascript) error.
Now that I can call the function it doesn't seem to behave as the specification tells it to.
Since this PR solves the initial issue I would call this a seperate bug.

**Comment by kripken** [comment]
Ok, thanks. I'll land that PR then. For the other issue you filed, that will require someone that understands the OpenAL API to take a look.
