### ISSUE TITLE
sourceMappingURL missing when using WASM_BACKEND

### ISSUE THREAD

**Issue by aseemgarg89** [kripken/emscripten#7216]

**Comment by dschuff** [comment]
I had thought this worked before, but when I tried it, I found that the output wasm file has the `.debug_line` section but not the sourceMappingURL. Looking back at #6648 it looks like @yurydelendik added the DWARF to sourcemap converter but it's not actually hooked up in emscripten to run when using debug info. We should make the driver run that after generating the wasm file.
