### ISSUE TITLE
No way to specify source map co-located with wasm file other than using source-map-base "./"

### ISSUE THREAD

**Issue by aseemgarg89** [kripken/emscripten#7217]
For source maps co-located with wasm file, we should be able to specify source-map-base "". It also might be a good idea to assume source map in the same location in case of missing source-map-base (when -g4 is used),

**Comment by kripken** [comment]
cc @yurydelendik

**Comment by yurydelendik** [comment]
I'm not sure what is the best way to fix the option here: sourceMappingURL section needs to stay optional (user may choose to use HTTP headers instead). Currently --source-map-base acts as a flags to enable sourceMappingURL section. IMHO specifying "./" is the best workaround to this particular use case.

I would expect `--source-map-base=` to work, but getting "Invalid parameter (do not use "=" with "--" options)".

**Comment by yurydelendik** [comment]
Okay, while fixing and test creation of https://github.com/kripken/emscripten/pull/7229, I found the WASM_BACKEND=1 always have sourceMappingURL section created (when -g4 specified), and assumes `--source-map-base` to be "" by default.

**Comment by yurydelendik** [comment]
Fixing the emcc logic in #7229 for non-WASM_BACKEND to create  sourceMappingURL section regardless of `--source-map-base` presence. Probably in the future we can add something like `--no-source-map-ref` to support HTTP header use case.
