### ISSUE TITLE
Exception due to trying to access document from a worker

### ISSUE THREAD

**Issue by cobarx** [kripken/emscripten#7222]
We are seeing an exception coming from shell.js because the worker accesses document.currentScript. 

From src/shell.js#231
```
if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
  if (ENVIRONMENT_IS_WEB) {
    if (document.currentScript) {
      scriptDirectory = document.currentScript.src;
    }
  } else { // worker
    scriptDirectory = self.location.href;
  }
```

I've tested and at least in our environment, the worker has ENVIRONMENT_IS_WEB and ENVIRONMENT_IS_WORKER true. If this is always the case, the else clause is a no-op. I'm not completely familiar with this code but would suggest this becomes:
```
if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
  if (ENVIRONMENT_IS_WORKER) {
    scriptDirectory = self.location.href;
  } else if (document.currentScript) { // web
    scriptDirectory = document.currentScript.src;
  }
```

The other approach would be:
```
if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
  if (ENVIRONMENT_IS_WEB) {
    if (typeof document !== 'undefined' && document.currentScript) {
      scriptDirectory = document.currentScript.src;
    }
  } else { // worker
    scriptDirectory = self.location.href;
  }
```

The code was introduced in #6894, maybe @kripken can provide some insight on the right approach. Let me know if you'd like me to open a PR.

**Comment by kripken** [comment]
> I've tested and at least in our environment, the worker has ENVIRONMENT_IS_WEB and ENVIRONMENT_IS_WORKER true.

Interesting, that should not be the case. But we do define
```
ENVIRONMENT_IS_WEB = typeof window === 'object';
```
which means that if `window` is defined in a worker (for polyfill purposes, perhaps) then that would become true. So yes, we do need to fix this.

I think your first proposal is a good solution here, thanks, please open a PR with that if you can.

**Comment by kitten23** [comment]
Hello,
I'm tring to call the .js from a worker. The file path is like:
'`.../workers/api-worker.js`' (the worker)
'`.../wasm/api.js`' (created by emcc)
'`.../wasm/api.wasm`' (created by emcc)

when i call `importScripts('.../wasm/api.js');` in 'api-worker.js'
`self.location.href` points to '`.../workers/api-worker.js`' and`scriptDirectory`  was set to '.../workers'.
then function `locateFile` set `wasmBinaryFile` to '`.../workers/api.wasm`' and can not fetch the binary file (the real path is '`.../wasm/api.wasm`').
so i move 'api-worker.js' to '`.../wasm/`' to make it work.

is this the correct way?
