### ISSUE TITLE
GL attributes (e.g. alpha) are not processed

### ISSUE THREAD

**Issue by Beuc** [kripken/emscripten#7227]
Hi,

Currently library_egl.js/eglCreateContext creates the WebGL context using a fixed set of attributes:
```_glutInitDisplayMode(0xB2 /* GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH | GLUT_MULTISAMPLE | GLUT_STENCIL */);```

I ran into an issue when porting software that needed GL_ALPHA_SIZE, which I quick-patched with:
```_glutInitDisplayMode(0xBA /* GLUT_RGBA | GLUT_ALPHA | GLUT_DOUBLE | GLUT_DEPTH | GLUT_MULTISAMPLE | GLUT_STENCIL */);```

(incidentally it's funny to see egl implemented on top of glut rather than the other way around ;))

library_glut.js itself only seem to know about antialias(=multisample)/depth/stencil/alpha though.
I'm not sure it makes sense to try and supprot the other webgl attributes (premultipliedAlpha/preserveDrawingBuffer/failIfMajorPerformanceCaveat).

Was there any reason for the hard-coding, or do we need to implement a bit of attributes parsing there?

**Comment by kripken** [comment]
I think it's just not implemented yet, yeah - each graphics system (SDL, glut, etc.) needs to do it's own parsing for those, and people just didn't get around to it. PRs very welcome :)

**Comment by Beuc** [comment]
(fix merged)
