### ISSUE TITLE
Cannot force browser library to be included

### ISSUE THREAD

**Issue by boyanio** [kripken/emscripten#7238]
Hello,

I am trying to build a project that needs to use the file system, without having any code referencing I/O. I try to force the file system, but I then get "Browser is not defined" when instantiating the wasm. I try to force it by including it in the list of libs to include, but with no success. My build script looks like this:

```
-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="['$Browser']" \
-s MODULARIZE=1 \
-s FORCE_FILESYSTEM=1 \
```
You can see the complete script [here](https://github.com/boyanio/DotNetAnywhere/blob/master/native/build.sh).

I am using emscripten 1.38.12. Do you have any idea what could be wrong?

Best,
Boyan

**Comment by kripken** [comment]
When I run a command with `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="['$Browser']"` with `EMCC_DEBUG=1` in the env, I see that `$Browser` is parsed as a shell argument, and the shell doesn't have it defined, so it replaces it with an empty string. If I switch the single quotes with double quotes, so there is `"$Browser"` in the internal part, it parses ok and I see Browser in the output. (But, this will depend on the shell and how escaping works there.)

**Comment by boyanio** [comment]
Oh, you are right! I ended up escaping the dollar character and it works brilliant. I need to use `EMCC_DEBUG` more often. Thank you!
