### ISSUE TITLE
Allow smart pointers to vectors by default

### ISSUE THREAD

**Issue by voodooattack** [kripken/emscripten#7275]
Just thought I'd share this snippet I wrote. It works as expected:

```cpp
template<typename T>
class_<std::vector<T>> register_vector_with_smart_ptrs(const char* name) {
    typedef std::vector<T> VecType;
    void (VecType::*push_back)(const T&) = &VecType::push_back;
    void (VecType::*resize)(const size_t, const T&) = &VecType::resize;
    return class_<VecType>(name)
        .template constructor<>()
        .template smart_ptr<std::shared_ptr<VecType>>(name)
        .template smart_ptr<std::auto_ptr<VecType>>(name)
        .function("push_back", push_back)
        .function("resize", resize)
        .function("size", &VecType::size)
        .function("get", &internal::VectorAccess<VecType>::get)
        .function("set", &internal::VectorAccess<VecType>::set);
}
```

Usage:

```cpp
register_vector_with_smart_ptrs<char>("vector<char>");
```

Now your code can return smart pointers to vectors and they'll work like normal.

Can this be included by default, or are there any reasons that make this bad practice? (Other than the data remaining inside the address space)

**Comment by kripken** [comment]
cc @chadaustin

**Comment by chadaustin** [comment]
@voodooattack Nice. You may even simplify that with something like:

```
template<typename T>
class_<std::vector<T>> register_vector_with_smart_ptrs(const char* name) {
    typedef std::vector<T> VecType;
    return register_vector<T>(name)
        .template smart_ptr<std::shared_ptr<VecType>>(name)
        .template smart_ptr<std::auto_ptr<VecType>>(name)
}
```

This sounds like a useful snippet, though I don't think it's a good idea to enable it by default. Not all projects use shared_ptr (and auto_ptr was removed in C++17) and there would be an increase in code size for projects.

Do you want to submit a PR to update the documentation to demonstrate this technique, perhaps?
