### ISSUE TITLE
Shortcutting setjmp/longjmp

### ISSUE THREAD

**Issue by nepx** [kripken/emscripten#7285]
I'm writing an x86 emulator and porting it with Emscripten. I've reached the point where I'm about to implement exceptions (i.e. page fault, etc.). Currently, the only way to "unwind" the stack is using `setjmp`/`longjmp`, but I've read in multiple places that it can slow code down. [There's a proposal to add exception handling to WebAssembly](https://github.com/WebAssembly/exception-handling), but it hasn't been added to the official spec, and no browser supports it, as of yet. I only need to unwind the stack, as I call individual functions as needed in JavaScript (i.e. to run the CPU for `n` cycles, I call `Module.cwrap("cpu_exec", "void", [])`) rather than encapsulating all the logic within the C source. 

What I've been doing is bypassing `setjmp` and `longjmp` altogether and throw an exception from JavaScript-Land that would be caught by the function that invoked the WebAssembly code in the first place, which would then reset the stack. It looks something like this:

```javascript
var cpu_exec = Module.cwrap("cpu_exec", "void", []);
CPU.prototype.exec = function() { 
    var stackPtr = Module["asm"].stackSave();
    try {
        cpu_exec();
    } catch (e) {
        if(typeof e === "number") {
            Module["asm"].stackRestore(stackPtr);
            this.handle_exception(e); // This eventually calls CPU.prototype.exec again
        }
        else throw e;
    }
};
CPU.prototype.unwind_stack = function() {
    throw 0x12345678; // Called by the WebAssembly module
};
```

Performance is better with this version. But manually accessing Emscripten stack functions seems like a bit of a kludge. Is this a safe optimization to make, or am I breaking generated code in subtle ways? Should I stick with the regular `setjmp`/`longjmp` functions?

Thank you for your help.

**Comment by kripken** [comment]
Nice idea! This looks safe to me, assuming that your `handle_exception` can get control flow back to the right place again.

This is a simplified/optimized version of what emscripten does for setjmp/longjmp, the differences are

1. Emscripten has a general mechanism for getting control flow to the right place, and this requires us to rewrite functions with a setjmp in them (to add more control flow paths). With your specialized mechanism you can do a lot better I think.
2. A longjmp is an exception, like with you, but it can be caught by any setjmp. So we must do a try-catch on every call that might reach a longjmp, which is done by the invoke functions - calling out into JS for those, and back in again, adds a lot of overhead that you are avoiding.

**Comment by nepx** [comment]
Will there be any problem with optimizations or is it guaranteed to be safe? I'm worried about edge cases like global variables being cached in local variables, etc.

**Comment by kripken** [comment]
It should be optimization safe, assuming `handle_exception` is safe - I'm not sure how you implemented that part.

**Comment by nepx** [comment]
`handle_exception` just resets some state (mostly dealing with segment prefixes, etc.) and calls `CPU.prototype.exec` again. Nothing fancy. 

Anyways, @kripken, thank you for your help!

**Comment by dschuff** [comment]
Just saw this; another option would be to just use `setjmp` and `longjmp` in C, and you can get around most of the performance penalty by putting the setjmp in its own function:
```
void cpu_exec(int foo, char* bar) {
  jmp_buf env;
  if (!setjmp(env)) {
    do_real_cpu_exec(foo, bar);
  } else {
    handle_exception();
  }
}
```
This is basically equivalent to your JS version but in C, if that's more convenient. You could even put that in a while loop if you want to avoid having handle_exception call cpu_exec again.
