### ISSUE TITLE
.emscripten_cache is removed on every invocation

### ISSUE THREAD

**Issue by adevaykin** [kripken/emscripten#7289]
Hello.

Anybody else having a problem with broken libs caching? Every time I run emcc and it has what to do (at least one change in a source file), cached binaries in ~/.emscripten_cache are deleted and compiled from scratch again.

Emscripten 1.38.11, Windows 10.

**Comment by kripken** [comment]
Does it say anything in the shell? If not, does `emcc -v` show anything? An error in the setup can cause things like this.

**Comment by adevaykin** [comment]
Thank you for the reply!
I think the problem is that I activate emsdk every time before building - ```.emscripten_cache``` is removed at this step.
