### ISSUE TITLE
Growing Arrays Invalidates TypedArray

### ISSUE THREAD

**Issue by bhelyer** [kripken/emscripten#7294]
So I've been called to work on a rather decently sized C++ project that's using Emscripten, compiling C++ code to a library and calling into the functions from JavaScript. There was a comment in some of the glue code that mystified me:

```
        if (this._sendArray.length == 0) {
            // it is unclear why this happens; the send buffer appears to become invalid once
```

Where `_sendArray` is a `Uint8Array` looking at a portion of Emscripten's memory, allocated by `Module._malloc`. The [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/length) has this to say on `TypedArray.prototype.length`:

>The value is established when a TypedArray is constructed and cannot be changed.

So this 'unchangeable' value changing was confusing to me. The old code reallocated it as a workaround. But it bugged me. While trying to resolve some other memory corruption issues by playing around with `emcc` flags, I discovered something. Setting `ALLOW_MEMORY_GROWTH` to `0`, and making `TOTAL_MEMORY` suitably large made the TypedArray not change.

The project I'm working on is proprietary, and also large, so I spent 5 minutes throwing together a test case that I could share, and sure enough, the behaviour occurs. Is this a bug? Or is the fact that memory growth invalidates TypedArrays documented somewhere? 

# Steps to reproduce.

1. Compile the given files with `emcc main.c -o swole.js -s ALLOW_MEMORY_GROWTH=1 --pre-js pre.js`
2. Open a web browser on `swole.html`
3. Open the dev console (F12, usually).
4. Observe the two integers displayed.

# Expected result

```
2048
2048
```

# Actual result

```
2048
0
```

## main.c

```
#include <stdlib.h>
#include <emscripten.h>

void* g_Pointer;

EMSCRIPTEN_KEEPALIVE
void becomeSwole()
{
    g_Pointer = malloc(20000000);
}
```

## pre.js

```
var Module = {
    onRuntimeInitialized: function ()
    {
        Run();
    }
}
```

## client.js

```
function Run()
{
    let buffer = Module._malloc(2048);
    let view   = new Uint8Array(Module.HEAPU8.buffer, buffer, 2048);
    console.log(view.length);
    _becomeSwole();
    console.log(view.length);
}
```

## swole.html

```

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
</head>

<body>
    <script type="text/javascript" src="client.js"></script>
    <script type="text/javascript" src="swole.js"></script>
</body>


</html>
```

**Comment by kripken** [comment]
Memory growth will replace the typed arrays, yes - as you said, it's the only way to do it, we can't grow them directly. See `enlargeMemory()` in `src/preamble.js`. We basically create a new buffer of a larger size, copy the data, and create new typed array views on that buffer. I opened #7297 to document this better now.

(In wasm, this is slightly different since we can grow a Memory. However, we still need to replace the JS typed array views on it.)

**Comment by bhelyer** [comment]
I thought it might be something like that, thank you for the clarification. The current behaviour of the stored TypedArray (which I guess is the real bug in our code, as squirreling those away is wrong) just becoming .length == 0 seems a little odd given that the underlying ArrayBuffer becoming invalid is not mentioned at all in any of the TypedArray documentation I've seen. But I guess that would be a spec bug, or an MDN bug, or... at any rate, it's not *your* problem, so I'll close this.
