### ISSUE TITLE
error: undefined symbol: popen

### ISSUE THREAD

**Issue by brijmohan** [kripken/emscripten#7302]
Hi folks,

I am trying to compile pocketsphinx.js using Emscripten which use to work perfectly till a few months back. Now I am getting the following error when I `make` the project. 

[Installation instructions](https://github.com/brijmohan/pocketsphinx.js#2-compilation-of-pocketsphinxjs)

```
error: undefined symbol: popen
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
ERROR:root:'/home/brij/pocketsphinx-js/emsdk/node/8.9.1_64bit/bin/node /home/brij/pocketsphinx-js/emsdk/emscripten/1.38.13/src/compiler.js /tmp/tmpzoLUAX.txt /home/brij/pocketsphinx-js/emsdk/emscripten/1.38.13/src/embind/emval.js /home/brij/pocketsphinx-js/emsdk/emscripten/1.38.13/src/embind/embind.js /home/brij/pocketsphinx-js/emsdk/emscripten/1.38.13/src/library_pthread_stub.js' failed (1)
CMakeFiles/pocketsphinx.js.dir/build.make:57: recipe for target 'CMakeFiles/pocketsphinx.js' failed
make[2]: *** [CMakeFiles/pocketsphinx.js] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/pocketsphinx.js.dir/all' failed
make[1]: *** [CMakeFiles/pocketsphinx.js.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Kindly suggest alternatives.

Thanks
-Brij

**Comment by kripken** [comment]
This is because we changed the default on undefined symbols, from a warning to an error. The error message's suggestion should work around it, add `-s ERROR_ON_UNDEFINED_SYMBOLS=0` to the flags passed to emcc

**Comment by brijmohan** [comment]
Thanks @kripken , I modified my CMakeLists.txt to add this flag. It works perfectly!

**Comment by fwasim** [comment]
> Thanks @kripken , I modified my CMakeLists.txt to add this flag. It works perfectly!

Can you please post what you added? I added the same, but my error remains.

**Comment by syl22-00** [comment]
@fwasim if you were also experiencing it on pocketsphinx.js, I pushed the fix.

**Comment by rrodri1971** [comment]
@syl22-00 : I have the same error, the pocketsphinx.js file is not generated, can you tell me what changes you made ?, Greetings

**Comment by syl22-00** [comment]
@rrodri1971 not sure what error you are referring to, if it is the popen error, it is a warning and it is safely ignored by the build. I you can't build, maybe you can give the output of your build command, probably better in the pocketsphinx.js issues rather than emscripten.

**Comment by rrodri1971** [comment]
@syl22-00 Dear 

Reviewing the contents of the file, I realized that I had already done the update, a thousand apologies.

Greetings Mexico CONALEP
