### ISSUE TITLE
wasm-only with shared modules

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#7304]
Currently in a MAIN_MODULE or SIDE_MODULE we disable wasm-only mode, with this comment:
```
    if Settings.RELOCATABLE and Settings.EMULATED_FUNCTION_POINTERS:
      # FIXME emulation function pointers work properly, but calling between
      #       modules as wasm-only needs more work
      return False
```
The issue isn't actually emulated function pointers, though (they are on by default anyhow in shared modules). Looking into this, there are 2 issues:

 * First, the legalize-js-interface pass in binaryen doesn't handle the case of the `get/setTempRet0` functions being imported. (We need them to be imported in a shared module, so the high bits can be communicated to JS and between modules.) By coincidence there is a PR in progress for that, https://github.com/WebAssembly/binaryen/pull/1703#discussion_r226020415
 * Second, in asm2wasm + wasm only mode, if we return an i64, this happens: we import the `get/setTempRet0` helpers as we should. They are never used, though, as the return looks like `return i64(..)` as in wasm-only mode we allow returning 64-bit values. So the helpers are never used. asm2wasm sees imports without uses and ignores them. Later when legalize runs, we see we have no helpers, so we create them in the module, which means we don't communicate those values to JS or other modules. I'll look into fixing that, should be simple.

cc @awtcode @dschuff

**Comment by awtcode** [comment]
@kripken , can I just confirm that moving forward, we will be removing get/setTempRet0 permanently? If this is the case, then how will we pass i64 between Wasm modules then?

**Comment by kripken** [comment]
No, getTempRet0 will still be needed for returning an i64 to JS. Maybe JS bitints will let us avoid that eventually.

**Comment by awtcode** [comment]
Sorry @kripken , can I just clarify as to what will be fixed by the following point? e.g. is removing get/setTempRet0 helpers the same as removing get/setTempRet0?

Second, in asm2wasm + wasm only mode, if we return an i64, this happens: we import the get/setTempRet0 helpers as we should. They are never used, though, as the return looks like return i64(..) as in wasm-only mode we allow returning 64-bit values. So the helpers are never used. asm2wasm sees imports without uses and ignores them. Later when legalize runs, we see we have no helpers, so we create them in the module, which means we don't communicate those values to JS or other modules. I'll look into fixing that, should be simple.

**Comment by kripken** [comment]
> is removing get/setTempRet0 helpers the same as removing get/setTempRet0?

Yes.

Regarding the second issue: yeah, something needs to be done there. We should be legalizing everything that JS can call, even in wasm-only mode. That is, `return i64(..)` should only be valid for calls we know are internal wasm calls, and for inter-module calls, we have to assume those might be to JS (unless we define that otherwise somehow).

**Comment by awtcode** [comment]
@kripken , sorry to trouble you again but my profiling shows that the get/setTempRet() calls are taking a significant amount of time and this is slowing down my application for dynamic linking.

Would you be able to work on this soon? Thanks for your help.

**Comment by kripken** [comment]
@awtcode I won't have time to work on this myself soon, sorry. Happy to help out with questions and stuff if you or someone else wants to look at it.

There may be a general question here though, of whether we legalize calls so they work in JS, or we assume they are just to wasm. Right now I'm not sure how we'd do that. On the other hand, once JS gets BigInt support, i64s will work there, so this problem will go away.

In any case, once we start to work on proper dynamic linking in the LLVM wasm backend, we'll need to make decisions on those things.
