### ISSUE TITLE
GenericWireType size

### ISSUE THREAD

**Issue by yjjnls** [kripken/emscripten#7314]
In val.h, there's code,
```c
        union GenericWireType {
            union {
                unsigned u;
                float f;
                const void* p;
            } w[2];
            double d;
        };
        static_assert(sizeof(GenericWireType) == 8, "GenericWireType must be 8 bytes");
        static_assert(alignof(GenericWireType) == 8, "GenericWireType must be 8-byte-aligned");
```
but in 64-bit system, `sizeof(GenericWireType)` will be 16, why should it note that 
>GenericWireType must be 8 bytes

**Comment by kripken** [comment]
Emscripten currently assumes a 32-bit system (because that fits well with JS). In the future, wasm64 may change that, and we'd need to change things like this.
