### ISSUE TITLE
wrong command in editing compiler config file documentation

### ISSUE THREAD

**Issue by opheliagame** [kripken/emscripten#7315]
![llvm_wrong_command](https://user-images.githubusercontent.com/21999998/47231954-fd955e00-d3eb-11e8-857b-95c7f2b7cfe8.png)
The command for setting the LLVM_ROOT path is enclosed in commas when it shouldn't be.

**Comment by kripken** [comment]
Thanks! I opened #7316 for this.

**Comment by opheliagame** [comment]
@kripken hey I am new to github and open source contributing, plus I am taking part in Hacktoberfest! Could you point me towards ways I could help using a PR? Would be extremely helpful

**Comment by kripken** [comment]
@opheliagame Sure! There are issues tagged ["good first bug"](https://github.com/kripken/emscripten/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22) and ["help wanted"](https://github.com/kripken/emscripten/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+) (a lot of overlap between the tags). Help and PRs are always welcome, and let me know if you have questions about any of those.
