### ISSUE TITLE
can't build with UTF-8 characters in EM_JS block

### ISSUE THREAD

**Issue by Sevenops** [kripken/emscripten#7323]
When my EM_JS code contains some UTF-8 characters i get this result
`func = 'function {}({}){}'.format(name, ','.join(arg_names), body)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u015f' in position 821: ordinal not in range(128)
make[2]: *** [a.js] Error 1
`
my args is here:
`--bind  -s WASM=1 -O3 -s SINGLE_FILE=1 -o a.js`

**Comment by Becavalier** [comment]
@Sevenops Could you please show us your c/cpp source code?

**Comment by Sevenops** [comment]
example code:
`EM_JS(void,testCode,(),{
    console.log("ççüğişiş.");
});`

**Comment by Sevenops** [comment]
#7380
