### ISSUE TITLE
fflush does not work on stdout

### ISSUE THREAD

**Issue by TonyLianLong** [kripken/emscripten#7360]
My C program is:
```
#include <stdio.h>
int main()
{
printf("Hey1\nHey");
fflush(stdout);
return 0;
}
```
And when executed in a real unix environment is outputs both `Hey1` and `Hey`, but on the browser only `Hey1` is printed. When I call `stream.tty.ops.flush(stream.tty)` in the browser console, the `Hey` is printed. So clearly the problem is that `fflush` is not working although the `flush` function in the JavaScript does work.

I saw an issue about this (https://github.com/kripken/emscripten/issues/2770) but in the issue the code is very different from the one that I have from the latest version and it seems that in that issue `flush` was not yet implemented in JavaScript.

**Comment by Becavalier** [comment]
@TonyLianLong Yes, I have tried at my local environment and get the same result. Currently you can use "-s NO_EXIT_RUNTIME=0" to avoid this issue. Compiling command like this:
`emcc fflush.c -s WASM=1 -s NO_EXIT_RUNTIME=0 -o fflush.html`

And I will take a look at this issue recently.
Thanks.

**Comment by kripken** [comment]
Interesting, it looks like musl's `fflush` is implemented by doing a write with a NULL buffer of size 0,

https://github.com/kripken/emscripten/blob/6e4b98636618989bcd99308391e51aa1b81f4c61/system/lib/libc/musl/src/stdio/fflush.c#L7

I can't seem to find any official linux syscall docs explaining that.

I opened #7376 with an implementation of that, which should fix this issue, but maybe I'm missing something about the syscall?

**Comment by kripken** [comment]
Fixed by that PR.
