### ISSUE TITLE
Invalid asm.js: Expected ;

### ISSUE THREAD

**Issue by Kukunin** [kripken/emscripten#7370]
I try to compile `libopus` library with emscripten.  I compile to asm.js since it's synchronous, that works better. 

In the compiled output I get an `Invalid asm.js: Expected ;` warning in Chrome 70.0.3538.67

The library is compiled with simple 

```
$(LIBOPUS_OBJ): $(LIBOPUS_DIR)/autogen.sh
	cd $(LIBOPUS_DIR); ./autogen.sh
	cd $(LIBOPUS_DIR); emconfigure ./configure --disable-extra-programs --disable-doc --disable-intrinsics --disable-rtcd
	cd $(LIBOPUS_DIR); emmake make
```

the JS file is compiled with 

```
emcc -O3 --closure 1 -s NO_FILESYSTEM=1 \
	-s EXPORTED_FUNCTIONS="['_opus_decoder_create', '_opus_decode_float', '_opus_decoder_destroy']" \
	-s WASM=0 --memory-init-file 0 -s MODULARIZE=1 \
	-o build/libopus.js libopus/.libs/libopus.a
```

Nothing special. I use emscripten `1.38.13-64bit`

I happens also for `-O2`, but doesn't for `-O0`. If I add `--llvm-lto 1` it works fine.

The compiled JS you can find here: https://pastebin.com/169c0MFM

**Comment by kripken** [comment]
It validates ok in firefox, so this could be a chrome bug.

Chrome's error doesn't mention the column, though, so it's hard to debug in your minified build - can you please provide a build with `-g1` (non-minified whitespace)?

**Comment by Kukunin** [comment]
Here, please. 

It finds this line invalid:

```js
    if ((c[C >> 2] | 0) > 8192) ea = 32767 / (P | 0) | 0; else ea = -32767 / (P | 0) | 0;
```

[libopus.js.txt](https://github.com/kripken/emscripten/files/2520018/libopus.js.txt)

**Comment by kripken** [comment]
Thanks, I reduced that and filed https://bugs.chromium.org/p/v8/issues/detail?id=8377

**Comment by kripken** [comment]
Looks like that was fixed in v8, closing.

https://bugs.chromium.org/p/v8/issues/detail?id=8377#c4

(will take time to reach release chrome, though).
