### ISSUE TITLE
WASM_BACKEND selected but could not find lld (wasm-ld)

### ISSUE THREAD

**Issue by helperShang** [kripken/emscripten#7378]
EMCC_WASM_BACKEND=1 emcc -s WASM=1 main.cpp

**Comment by dschuff** [comment]
The wasm backend is not yet included by default with emsdk. Currently you have to build it yourself (right now only the trunk version is really tested). So if you do that, you need to make sure you include lld along with LLVM and clang.

**Comment by saadson** [comment]
> EMCC_WASM_BACKEND=1 emcc -s WASM=1 main.cpp

If you build it you need to link it to llvmbuild/bin.

**Comment by aaaristo** [comment]
./emsdk install latest-upstream
./emsdk activate latest-upstream
. ./emsdk_env.sh

seems to work as mentioned here: https://emscripten.org/docs/compiling/WebAssembly.html

**Comment by aaaristo** [comment]
./emsdk install latest-upstream
./emsdk activate latest-upstream
. ./emsdk_env.sh

seems to work as mentioned here: https://emscripten.org/docs/compiling/WebAssembly.html
