### ISSUE TITLE
After c++ is compiled into wasm, the internal methods are not found and need to be imported by “imports”

### ISSUE THREAD

**Issue by ChenGuanglin0924** [kripken/emscripten#7389]
**C++ Code：**
````
#include <iostream>
using namespace std;

extern "C" {
    void ReadHead(char *path)
    {
        if ((m_ShpFile_fp = fopen(path, "rb")) == NULL)
        {
            return;
        }
        fread(&file_Head.FileCode, sizeof(int), 1, m_ShpFile_fp);
        fread(&file_Head.FileLength, sizeof(int), 1, m_ShpFile_fp);
        file_Head.FileLength = OnChangeByteOrder(file_Head.FileLength);
        fread(&file_Head.ShapeType, sizeof(int), 1, m_ShpFile_fp);
        ...
    }
}
````

> here, the functions "fopen" and "fread" can not be found。

**emcc：**
`emcc shp.cpp -Os -s WASM=1 -s SIDE_MODULE=1 -o shp.wasm` 

**wasm file：**

````
...
(import "env" "_fopen" (func $env._fopen (type $t0)))
(import "env" "_fread" (func $env._fread (type $t8)))
...
````

**Error：**

- Uncaught (in promise) LinkError: Import #1 module="env" function="_fopen" error: function import requires a callable at fetch.then.then.then.module (http://127.0.0.1:5500/index.html:126:36)
- Uncaught (in promise) LinkError: Import #1 module="env" function="_fread" error: function import requires a callable at fetch.then.then.then.module (http://127.0.0.1:5500/index.html:126:36)

Here are some of the errors listed. I think it may be that `emcc` compiles without introducing the required `lib`, which is the header file (`.h`).

**Comment by kripken** [comment]
In a side module, system libraries are not linked in, so it calls out to things like `fopen` etc. And then you need to provide them as imports. (A main module will provide them to the side module; if you load the module yourself, you need to handle it.)

**Comment by ChenGuanglin0924** [comment]
Thank you very much for your reply. And how to import the required resources? @kripken

**Comment by kripken** [comment]
You can look at a main module to see how it does it (compile it, run it to see that it works, then look at the code). There isn't much more in terms of docs for this - some of it is the normal libc API, some is internal APIs.

**Comment by ChenGuanglin0924** [comment]
Where is the main module, and how to find it? @kripken

**Comment by kripken** [comment]
See https://github.com/kripken/emscripten/wiki/Linking

**Comment by ChenGuanglin0924** [comment]
Thanks for your help very much, and I will close this case. @kripken
