### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by Manthan0911** [kripken/emscripten#7393]
Hello,

I am facing this issue.I am pasting here the error message. 

error: undefined symbol: sqlite3_close
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: sqlite3_errmsg
error: undefined symbol: sqlite3_exec
error: undefined symbol: sqlite3_free
error: undefined symbol: sqlite3_open
Error: Aborting compilation due to previous errors

I tried running emcc <file name> -s ERROR_ON_UNDEFINED_SYMBOL=0
But still issue is there. While I try to do emrun I get nothing in the browser

**Comment by kripken** [comment]
Does the error change to a warning with that flag?

You may not have sqlite linked in to your code, and need to add it as an input.

**Comment by Manthan0911** [comment]
no.

I linked the sqlite file to the original file. As well as I also created the same header file and included that file in the code.

My code generate output in the Eclipse.

**Comment by kripken** [comment]
Linking in emscripten does not always work like native toolchains. What exact commands did you issue?

(See https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html for docs on this)

**Comment by Manthan0911** [comment]
Firstly I used 
$ emcc filename.c -s WASM=1 -o filename.html

then I got this error message and tried 
 $emcc -s ERROR_ON_UNDEFINED_SYMBOL=0
