### ISSUE TITLE
Issues running Emscripten with std::function: Invalid function pointer X called with signature X.

### ISSUE THREAD

**Issue by Querijn** [kripken/emscripten#7402]
Hey there guys! I have a bit of code that runs a specialised file class that wgets the file requested and calls a callback when the file is loaded.

The Emscripten implementation can be found here: https://github.com/Querijn/LeagueModel/blob/master/src/file/emscripten_file.cpp

It works fine for the most part, assumably, but it crashes on [line 86](https://github.com/Querijn/LeagueModel/blob/master/src/file/emscripten_file.cpp#L86): 
![image](https://user-images.githubusercontent.com/3397066/47674763-5cab5d80-dbb8-11e8-867e-5e119fe8f8da.png)

`t_FileData` is an `EmscriptenFile*`
`m_LoadFunction` is the std::function callback for file status (`std::function<void(EmscriptenFile* a_File, LoadState)>`)

Full log can be found here: 
[shader_loading.log](https://github.com/kripken/emscripten/files/2526742/shader_loading.log)

I've seen some other topics about emulated function pointers, and they looked interesting, so I've tried those out, but they did nothing in non-wasm builds, but I get a different error in a wasm build, found here: [emulated_function_pointers.log](https://github.com/kripken/emscripten/files/2526784/emulated_function_pointers.log)

I've uploaded builds of the project here:
http://irule.at/emscripten/js
http://irule.at/emscripten/efp (emulated function pointers bug)
http://irule.at/emscripten/wasm

I build the project with `node helper/build dev` or `node helper/build no-wasm` from the root of the project. You can find the build script I use here: https://github.com/Querijn/LeagueModel/blob/master/helper/build.js

Might be a bit confusing, there's a lot going on, but the arguments I use for most builds are ```std=c++11 -s FULL_ES2=1 -Werror -g4 -s ASSERTIONS=2 -s DEMANGLE_SUPPORT=1 --source-map-base http://localhost:8080/ -s ALLOW_MEMORY_GROWTH=1```, if that is of any relevance.

**Comment by FrancoisChastel** [comment]
Hello !

I think your issue is not related (?) to any bugs of EmScripten. Posting it on stackoverflow would provide you more result ! :)
