### ISSUE TITLE
glReadBuffer not registered with emscripten_GetProcAddress

### ISSUE THREAD

**Issue by DerRM** [kripken/emscripten#7406]
For a project I'm currently working on I need access to glReadBuffer but it is not correctly initialized by our GL Loader. I came across, that your implementation of glGetProcAddress is missing the return case for [emscripten_glReadBuffer](https://github.com/kripken/emscripten/blob/incoming/system/lib/gl.c#L70) although it is defined. Is there another way to call glReadBuffer in my code?

**Comment by kripken** [comment]
That will be fixed by https://github.com/kripken/emscripten/pull/7403 , which adds all the missing functions there.

**Comment by DerRM** [comment]
Tested with 1.38.18. Works and can be closed now
