### ISSUE TITLE
getaddrinfo and other blacklisted functions in EmScripten

### ISSUE THREAD

**Issue by FrancoisChastel** [kripken/emscripten#7417]
Hello,

When trying to use EmScripten with version `1.38.12` (got unresolved symbol for `htons` in later version) `getaddrinfo` is not working properly.

I found out that `getaddrinfo` was part of the blacklisted functions in the libc, but the code is actually compiling and no warning / error is appearing.

Is that a bug ? (the code is working fine when the target is not wasm or asm.js) If not: 

* Do you suggest any work-around ? (HumbleNet seem to use `getaddrinfo` and working fine) ;
* It would be great to change the `system_libs.py` to actually throw an error at compiling when using a blacklisted functions. What do you think about that ?

**Comment by kripken** [comment]
Looks like there are some missing things in deps_info.json - I opened #7420 to fix them and add testing on CI. That should fix at least the `htons` issue with `gethostbyname` which I saw was broken in the tests we have.

What do you mean by `getaddrinfo was part of the blacklisted functions in the libc`?

**Comment by FrancoisChastel** [comment]
Thank you for fixing that and for your reply @kripken !

When I am using `getaddrinfo`the code is not running properly when I am targeting WebAssembly but fine with a linux target. 

I was suggesting that it may occur because it's part of the blacklisted function inside [`system_libs.py`](https://github.com/kripken/emscripten/blob/incoming/tools/system_libs.py) (see `create_libc` function) ! 

My question, is : does the actual WebAssembly version support `getaddrinfo`? What about the others blacklisted functions ?

**Comment by FrancoisChastel** [comment]
To precise the problem, if you execute this code for example :
```C++
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>

struct addrinfo hints, *infoptr;

int main() {
    hints.ai_family = AF_INET; 

    int result = getaddrinfo("www.mozilla.org", NULL, &hints, &infoptr);
    if (result) {
        fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(result));
        exit(1);
    }

    struct addrinfo *p;
    char host[256];

    for (p = infoptr; p != NULL; p = p->ai_next) {

        getnameinfo(p->ai_addr, p->ai_addrlen, host, sizeof (host), NULL, 0, NI_NUMERICHOST);
        puts(host);
    }
    
    freeaddrinfo(infoptr);
    return 0;
}
```bash
In C++ you will obtain :
```
104.16.40.2
104.16.40.2
104.16.41.2
104.16.41.2
```

In WASM you will obtian :
```bash
172.29.1.0
```

**Comment by kripken** [comment]
Networking works oddly on the web, so we blacklist those functions in musl and implement them in JS ourselves as best we can. Look in `src/library.js` for that function.

I don't remember the specific limitations now, but there are issues with host resolution, that operations are async, etc.

**Comment by FrancoisChastel** [comment]
By the way, the behavior is explained by the following comment : 
```js
// We can't actually resolve hostnames in the browser, so instead
// we're generating fake IP addresses with lookup_name that we can
// resolve later on with lookup_addr.
// We do the aliasing in 172.29.*.*, giving us 65536 possibilities.
```
