### ISSUE TITLE
ENVIRONMENT='web' not automatically set for html files, but docs say it is

### ISSUE THREAD

**Issue by ad8e** [kripken/emscripten#7436]
According to https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html:

>The ENVIRONMENT flag ... (When you tell emcc to emit an HTML file, it automatically sets the output to web-only.)

I made a new file, main.cpp:

    int main() { return 0; }

Compile with:

    emcc main.cpp -o index.html

Then try again with:

    emcc main.cpp -o index.html -s ENVIRONMENT='web'

Note that passing `-s ENVIRONMENT='web'` is necessary to receive `ENVIRONMENT_IS_WEB=true` in index.js, even though I specified an html output file. Otherwise detection code is emitted.

**Comment by ad8e** [comment]
Here's the compiled results to save you some time:
[environment web.txt](https://github.com/kripken/emscripten/files/2541107/environment.web.txt)
[no environment web.txt](https://github.com/kripken/emscripten/files/2541108/no.environment.web.txt)

**Comment by kripken** [comment]
Thanks @ad8e, I can confirm this. I thought I added code for that, but don't see it now.

Should be easy to add to emcc.py though, could be a good first bug for someone.
