### ISSUE TITLE
Embind Class Constructors Taking std::vector<T>

### ISSUE THREAD

**Issue by gblikas** [kripken/emscripten#7440]
I thought I would cross post a question I made on StackOverflow: https://stackoverflow.com/questions/53108165/emscripten-class-constructor-taking-stdvectort.  

I hope someone can help me answer it. There is _some_ documentation on how to us `std::vector` objects with JavaScript. However, nothing about classes which have constructors taking `std::vector` objects. I am primarily interested in the case where we have a primitive vector, such as `std::vector<float>`.

**Comment by brion** [comment]
I don't think there's a significant difference between class constructors and other methods here. The key thing is to ensure that you've defined a mapping for `std::vector<float>` using [register_vector](https://kripken.github.io/emscripten-site/docs/api_reference/bind.h.html#_CPPv215register_vectorPKc) so you can pass the vector your copy function has created back to JavaScript and then back into C++.

This code seems to work for me, if I understand your problem correctly:

```cpp
#include <vector>

#include <emscripten.h>
#include <emscripten/bind.h>

class test_class {
    float x;

public:
    test_class(std::vector<float> arr);
    float get_x() const;
    void set_x(float val);
};

test_class::test_class(std::vector<float> arr) {
    x = 0;
    for (size_t i = 0; i < arr.size(); i++) {
        x += arr[i];
    }
    x = x / arr.size();
}

float test_class::get_x() const {
    return x;
}

void test_class::set_x(float val) {
    x = val;
}

EMSCRIPTEN_BINDINGS(my_class) {

    emscripten::register_vector<float>("VectorFloat");

    emscripten::class_<test_class>("test_class")
        .constructor<std::vector<float>>()
        .property("x", &test_class::get_x, &test_class::set_x)
        ;
}

int main() {
    EM_ASM(
        var arr = new Float32Array([1.0, 2.0, 0.5]);
        var vec = new Module.VectorFloat();
        for (var i = 0; i < arr.length; i++) {
            vec.push_back(arr[i]);
        }
        var obj = new Module.test_class(vec);
        console.log('obj.x is ' + obj.x);
    );
}
```

This sample code does an inefficient copy from the Float32Array to the std::vector<float> (represented as the VectorFloat proxy object in JS), assuming you've got that part working, and concentrates on passing the vector into the constructor.

**Comment by gblikas** [comment]
@brion I think I found what I was looking for in [`emscripten::value_array`](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#value-types). This would allow a call like 

    int main() {
         EM_ASM(
            var arr = new Module.FunNameHere([1.2312, 1.0, 34234234]);
        );
     }

Instead of creating the `Float32Array`, and then grabbing the `VectorFloat()`. If someone like @kripken could verify this, it would be nice.

**Comment by kripken** [comment]
@brion knows much better than me about this stuff :)

**Comment by gblikas** [comment]
Thanks for the response! Then, if @brion could verify this, it would awesome!

**Comment by brion** [comment]
If you have a fixed-size array mapping for a class/struct like a 3-d point or matrix, then yes using value_array should be a great solution here -- it provides a nice idiomatic JavaScript constructor and handles the consumption of the JS array for you.

I believe the bindings for the elements need to be able to modify the instance as it iterates through the items, so might require refactoring your C++-side constructor if that's not possible with your current code (eg if the constructor takes a std::vector<float> and doesn't allow modification of the fields) but that should be easy to do.
