### ISSUE TITLE
Rename pthread-main.js?

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#7521]
Right now we always emit that name for the file, which means two projects can't exist in the same directory. Perhaps it should be `NAME.pthread.js` where `NAME` is the name we use for `NAME.js` etc.?

This would be a breaking change, and people would need to change deployment scripts.

cc @juj

**Comment by brion** [comment]
In my earlier attempts at using pthreads in ogv.js I used a shared copy of pthread.js but this only worked because all modules were built with the same compiler version etc. Agree it's safer to use a file named per build/project, as that assumption may not always hold.

**Comment by juj** [comment]
Big +1 on this. Let's change (and break), before use becomes more widespread. This was always in the back of my mind, but never got to it.

**Comment by kripken** [comment]
Sounds good, opened #7539
