### ISSUE TITLE
 A way to re-initialize all global variables?

### ISSUE THREAD

**Issue by shooshx** [kripken/emscripten#7527]
I'm compiling some C project that is originally a command line tool and I'd like to able to invoke it repeatedly again and again. The one problem I'm having is that after the first run, global variables retain their value and are not being re-initialized on the second run. One example is "optind" used by getopt().
Of course, a workaround would be to re-initialize all of these globals on my own but that is extremely tedious and error prone and it feels like the compiler has already done this job and that there should be a function somewhere that just does initialize_all_global_variables().
Is there something like that?

**Comment by kripken** [comment]
I'm not aware of one. But you can use MODULARIZE and create a new instance, so a fresh memory is used and it's like you're running the tool from scratch.
