### ISSUE TITLE
error: undefined symbol: glCompressedTexImage1D

### ISSUE THREAD

**Issue by ValSergey** [kripken/emscripten#7546]
error: undefined symbol: glCompressedTexImage1D,
but it have in the /home/serega/.emscripten_ports/sdl2/SDL2-version_15/include/SDL_opengl.h

GLAPI void GLAPIENTRY glCompressedTexImage1D( GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data );

**Comment by kripken** [comment]
I think this came up in another issue you filed - that method does not seem to be in the WebGL2 spec.
