### ISSUE TITLE
emcc wasm option deletes existing asm.js output

### ISSUE THREAD

**Issue by laverdet** [kripken/emscripten#7567]
This is pretty surprising behavior.. emcc will delete an existing *.asm.js file when invoking with WASM=1. The reverse is not true, that is emcc will leave an existing *.wasm file alone when invoking with WASM=0. This behavior was observed on emcc 1.38.20, OS X 10.14.

```
> emcc -c -o foo.bc foo.c
> emcc -o foo.asm.js foo.bc -s SIDE_MODULE=1 -s WASM=0
> ls
foo.asm.js foo.bc     foo.c
> emcc -o foo.wasm foo.bc -s SIDE_MODULE=1 -s WASM=1
> ls
foo.bc   foo.c    foo.wasm
> emcc -o foo.asm.js foo.bc -s SIDE_MODULE=1 -s WASM=0
> ls
foo.asm.js foo.bc     foo.c      foo.wasm
> emcc -o foo.wasm foo.bc -s SIDE_MODULE=1 -s WASM=1
> ls
foo.bc   foo.c    foo.wasm
```

**Comment by kripken** [comment]
Thanks @laverdet. I'd guess that in emcc.py we write to that file temporarily, when we should be using a proper temp file that is not in the current directory etc.

**Comment by kripken** [comment]
This was fixed by https://github.com/kripken/emscripten/pull/7601#issuecomment-444315804
