### ISSUE TITLE
MODULARIZE behaves oddly with `EM_JS`

### ISSUE THREAD

**Issue by jkbbwr** [kripken/emscripten#7583]
Given this C code
```
#include <emscripten/emscripten.h>

EM_JS(int, setup, (char* raw), {
    var ptr = allocate(intArrayFromString(raw), 'i8', ALLOC_NORMAL);
    var out = _actual_setup(ptr);
    _free(ptr);
    return out;
});

EMSCRIPTEN_KEEPALIVE
int actual_setup(char* message) {
    printf("%s\n", message);
    return 1;
}
```

Compiled with `emcc -o test.html test.c -s MODULARIZE=1 -s 'EXPORT_NAME=libtest'`

WIth the following test snippet.

```
var lib = require("./test.js");

lib().then(function(Module) {
  Module._setup("testing");
});
```

The expected output is "testing" on the console. 
The actual output is

```
failed to asynchronously prepare wasm: TypeError: Module._setup is not a function
TypeError: Module._setup is not a function
    at /home/jakob/tmp/run.js:4:10
    at Object.Module.onRuntimeInitialized (/home/jakob/tmp/test.js:2295:7)
    at doRun (/home/jakob/tmp/test.js:2352:71)
    at run (/home/jakob/tmp/test.js:2368:5)
    at runCaller (/home/jakob/tmp/test.js:2319:29)
    at removeRunDependency (/home/jakob/tmp/test.js:1445:7)
    at receiveInstance (/home/jakob/tmp/test.js:1624:7)
    at receiveInstantiatedSource (/home/jakob/tmp/test.js:1649:7)
TypeError: Module._setup is not a function
    at /home/jakob/tmp/run.js:4:10
    at Object.Module.onRuntimeInitialized (/home/jakob/tmp/test.js:2295:7)
    at doRun (/home/jakob/tmp/test.js:2352:71)
    at run (/home/jakob/tmp/test.js:2368:5)
    at runCaller (/home/jakob/tmp/test.js:2319:29)
    at removeRunDependency (/home/jakob/tmp/test.js:1445:7)
    at receiveInstance (/home/jakob/tmp/test.js:1624:7)
    at receiveInstantiatedSource (/home/jakob/tmp/test.js:1649:7)
node.js exiting due to unhandled promise rejection
```

Version information

```
> emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.38.12 ((unknown revision))
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
> node --version
v11.1.0
```

**Comment by kripken** [comment]
cc @jgravelle-google

**Comment by jgravelle-google** [comment]
So this gets translated to
```js
function _setup(raw){ var ptr = allocate(intArrayFromString(raw), 'i8', ALLOC_NORMAL); var out = _actual_setup(ptr); _free(ptr); return out; }
```
in the output, which is itself scoped inside the modularize closure, and so isn't available outside.
`Module._foo` functions are C functions that are exported, so `Module._actual_setup` is available to be called (although you need to manually convert the string, `Module._actual_setup("testing")` does not work).
The purpose of EM_JS is to declare JS functions in C, and also expose them to C. If you want to call them from JS, it's probably easier to declare the function in JS. https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-c-in-javascript has instructions for hooking up JS functions to be callable from C as well. (I think of EM_JS as being basically a shorthand for that)

**Comment by jkbbwr** [comment]
Thanks for the input. It seems like we are leaning towards embind as that does auto converting between `std::string` and javascript land. You can close this at your leasure if you feel it is resolved.
