### ISSUE TITLE
basic_streambuf symbols missing

### ISSUE THREAD

**Issue by jariseon** [kripken/emscripten#7584]
hi, after upgrading to the latest toolchain (1.38.20) i'm unable to build this [repo](https://github.com/jariseon/webOBXD). with an ancient 1.37.21 it compiles and links fine. there are some undefined symbols related to basic_streambuf plus couple of weird ones which to me read like a newspaper from mars:

```
error: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE6setbufEPci
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE6xsgetnEPci
error: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE6xsputnEPKci
error: undefined symbol: _Znaj
error: undefined symbol: _Znwj
```

i will try to bisect the issue, but to save time, can someone with better insight see straight away what's bothering the linker? thanks!

**Comment by kripken** [comment]
Bisection is a good idea to give us a definite answer, but one possibility is that we recently switched `ERROR_ON_UNDEFINED_SYMBOLS` to on by default, which would break code that always had missing symbols. You can flip it off if you want, if that's the case, but it may be good to find out why those are missing.

**Comment by jariseon** [comment]
thanks, i was able to resolve the issue via bisection: 1.38.10 was the first version to report missing symbols. in that release "size_t and friends were changed from int to long", which seems to impact some (but not all ?) symbols defined in a static bc library file.

the repo i was building was linking against such a static bc library, compiled with 1.37.21 and thus incompatible with toolchains from 1.38.10 onwards. i simply recompiled the library, and now the build is all clean again with the latest toolchain. this was my own error, can't believe i forgot to recompile dependencies when switching to a new toolchain.

**Comment by kripken** [comment]
Oh good, glad it was easy to fix.

Sorry we don't have a better error/warning on that, but it's hard to add one for such ABI changes.
