### ISSUE TITLE
Update emscripten pages

### ISSUE THREAD

**Issue by Merg1255** [kripken/emscripten#759]
A few suggestions:

- Some bugs on github are like ancient, and many refer to much different versions of emscripten. Please review and keep the github bugs as much relevant as possible to the current version.
- The Tutorial page needs some more info about installing emscripten on different platforms.
- Add pics/video to the tutorial page
- Update to llvm 3.2

Thanks

**Comment by juj** [comment]
Let me close this, the above are either resolved or don't apply any more.
