### ISSUE TITLE
Invalid Enum error on glGetIntegerv(GL_VERTEX_ARRAY_BINDING,...) with Webgl 1.0

### ISSUE THREAD

**Issue by larsbohn** [kripken/emscripten#7597]
I just stumbled upon this issue in the current ( 46afd23 ) version of emscripten.

glGetIntegerv(GL_VERTEX_ARRAY_BINDING, &aGLInt);

gives INVALID_ENUM in WebGL 1.0 contexts with OES_vertex_array_object present and activated.

This is not expected behaviour, as the rest of the VAO APIs are working correctly.

This seems to be because in

https://github.com/kripken/emscripten/blob/incoming/src/library_gl.js

#if USE_WEBGL2
case 0x85B5: // GL_VERTEX_ARRAY_BINDING
case 0x8919: // GL_SAMPLER_BINDING
case 0x8E25: // GL_TRANSFORM_FEEDBACK_BINDING
#endif

--> only if WebGL2 is used the call is actually executed, but not if just the extension is present...

**Comment by kripken** [comment]
Interesting, thanks for filing. Indeed that constant is defined in WebGL2 but also in WebGl1 + that extension.

We should probably add it to the `automaticallyEnabledExtensions` list in `library_gl.js`, but would need to confirm that it has no downsides (see comment there).

Another option might be in the default of that switch (where it's present for WebGL2) to check if the context has that value defined at runtime.

cc @juj

**Comment by larsbohn** [comment]
Thanks for commenting - OES_vertex_array_object is part of automaticallyEnabledExtensions, which is good.

It's just the glGetIntegerv(GL_VERTEX_ARRAY_BINDING, ...) which does not care about the extension.

Regards,
Lars

**Comment by juj** [comment]
Thanks @larsbohn, fix in PR #7645.
