### ISSUE TITLE
Unaligned memory question

### ISSUE THREAD

**Issue by gabrielcuvillier** [kripken/emscripten#7607]
I am currently porting a big program to WebAssembly that heavily uses unaligned memory reads (necessary due to many packed structures being used)
Indeed, when I am using SAFE_HEAP=1, there is a lot of alignment issues, and fixing them all would be a big task. When not using SAFE_HEAP, the code seems to run, but I am wondering if it is really running correctly, or if it is silently doing bad things behind the doors.

The documentation says several things on this topic:
"Performing a normal load or store on an unaligned address can fail."
and
"Emscripten supports unaligned reads and writes, but they will be much slower, and should be used only when absolutely necessary. 
and
"To force an unaligned read or write you can: <...>"
and
I also see there is a "UNALIGNED_MEMORY" flag in settings.js, but does not seems to be used

Well, in the end, this is a little bit confusing :)

Does it mean that when we are compiling in wasm mode, unaligned loads are working transparently (no silent memory read corruption or failure), just at the cost of performance impact ? Or we have to do something explicitly in the code (like using the emscripten_align* types when necessary)?

Thanks for this precision!

**Comment by kripken** [comment]
In asm.js, unaligned loads may fail if the compiler did not anticipate them, and will be slow if it did. In wasm, they will always work, but may be slower if unaligned and especially if unaligned and not anticipated as such.

Which pages were those on? We should update those docs.

**Comment by gabrielcuvillier** [comment]
Ok, this is clear now. Thanks.

Pages involved are:
http://kripken.github.io/emscripten-site/docs/porting/Debugging.html#memory-alignment-issues
http://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html#other-issues

I think they are correct, but the exact behavior is not 100% clear while reading

**Comment by kripken** [comment]
Thanks @gabrielcuvillier, I opened #7689 now.
