### ISSUE TITLE
USB Library

### ISSUE THREAD

**Issue by MelbourneDeveloper** [kripken/emscripten#7610]
Would it be possible compile a C USB library like https://github.com/libusb/libusb to wasm?

**Comment by MelbourneDeveloper** [comment]
https://github.com/libusb/libusb/issues/501

**Comment by kripken** [comment]
Yes, but it would depend on [WebUSB](https://wicg.github.io/webusb/) to actually access USB (at least on the web).

**Comment by MelbourneDeveloper** [comment]
Question answered. Thanks.
