### ISSUE TITLE
Emscripten returns with error code 0 if python2 is not found.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#763]
After the recent mods that require manually setting up a link to python2, if the user has not set up a link, running emscripten tests finish with an exit code 0 (success).

Expected that in such case a failure error code is returned.

See the recent buildbot results on OSX http://clb.demon.fi:8112/waterfall , where the build reports success, even though the output was this http://clb.demon.fi:8112/builders/osx-emcc-master-tests/builds/17/steps/OSX%20test%20emscripten%20master/logs/stdio

(Btw, would it be possible to look at this again if it is possible to automate the 'python' vs 'python2' somehow so that user does not need to do this manually?)

**Comment by edwardmp** [comment]
Similar issue, had to do this to fix:
`sudo ln -s /usr/bin/python2.7 /usr/bin/python22.7`

**Comment by wyudong** [comment]
For people who encountered the error: `python2 command not found` when installing Emscripten in OS X 10.11 El Capitan, you need to make some changes based on this [Platform-specific notes for
Mac OS X](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html).

Before type the following commands in the terminal, refer to [this post](http://stackoverflow.com/questions/32590053/copying-file-under-root-got-failed-in-os-x-el-capitan-10-11/32590885#32590885) to disable System Integrity Protection first. Then use the _new_ commands which at least solved my python2 command not found problem.

```
cd /usr/bin
sudo ln -sf python python2
sudo ln -sf ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 python22.7
```

**Comment by juj** [comment]
Fixes in incoming, so closing.
