### ISSUE TITLE
Best practice to make an async JS function to behave like a sync one from C++ code ?

### ISSUE THREAD

**Issue by gabrielcuvillier** [kripken/emscripten#7632]
Here is my problem:

I have a C++ funtion that does file operations on an IDBFS mounted filesystem. After the files operations are done, I need to call FS.syncfs in order to have the changes effectively written in IDBFS, and I want this sync to be completed **before** my C++ code can continue. But FS.syncfs is asynchronous, and the sync will not be done until my C++ code yields to the browser...

So, what are the best practices here to make an async call appears to be sync, but without blocking the whole program. I mean, the call would simply yield to the browser so that everything on JS side runs smoothly, and inside the completion callback of the async method it would resume the C++ program ?

For info, I have already a set up emscripten_set_main_loop, and I am somewhere in the middle of this main loop.

Thanks for advices, if any !

**Comment by gabrielcuvillier** [comment]
Well I guess there is no easy way to do this. I close the the issue.

**Comment by dschuff** [comment]
Yeah the short answer is that there's no really easy way. In the near-ish future you should be able to use a pthread build with `-s PROXY_TO_PTHREAD` and use the proxying feature to proxy calls to the main thread. This actually will allow the worker thread to block while it waits for the promise to resolve on the main thread.

**Comment by curiousdannii** [comment]
It's pretty straightforward to do this in C with the Emterpreter. I don't know about C++ though.
