### ISSUE TITLE
wasm-backend object files build of sqlite is 5% larger than wasm-backend bitcode build

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#7638]
STR: run sqlite in the benchmark suite, `./tests/runner.py  benchmark.test_zzz_sqlite`, and the builds are in the `/tmp/emscripten_temp` dir.

Looking at this, nothing obvious pops out. Many functions are just bigger. This is *not* due to binaryen opts - do we run different LLVM opts between the modes?

cc @sbc100

**Comment by sbc100** [comment]
This is to be expected I think, since using a bitcode build allows/triggers LTO.    So for release builds we would always suggest people use LTO (i.e. bitcode objects).

Or do you think this something more?  Perhaps we are not passing the right flags to clang in wasm object file case?

**Comment by kripken** [comment]
Ah, maybe the issue is I don't understand what `wasm-ld --lto-O2` etc. do.

 * In the bitcode object file mode, does this actually run full LLVM LTO? (i.e. something like `opt -std-link-opts`?)
 * What does it do in the wasm object file mode?

**Comment by sbc100** [comment]
`--lto-O2` has no effect iwht wasm object file mode since there is not LTO in this case.

You can see the code that sets up on the LTO for the bitcode linking case: 

https://github.com/llvm-mirror/lld/blob/2e03185a96c21832d116e4a734d7b99c9c1f85cc/wasm/LTO.cpp#L55

I think that `--lto-O2` basically means compile from bitcode as if -O2 was passed, but I could be wrong.

**Comment by kripken** [comment]
I see, thanks. So this is not a bug then - the wasm backend path has been enabling LTO for bitcode object files, basically? It's not surprising the results differ from asm2wasm and the wasm object files, both of which don't do LTO (but they do some form of LTDCE).

This means that comparing asm2wasm to wasm bitcode files is not a useful comparison. I'd recommend we make it more like asm2wasm so users are not surprised, however, as wasm object files are the future anyhow, I think we can just leave it. And I'l focus on wasm object files for comparisons to asm2wasm (which is a direct comparison).
