### ISSUE TITLE
better C api like node.js N-API?

### ISSUE THREAD

**Issue by navigator117** [kripken/emscripten#7688]
node.js's NAPI is simple and easy to use. Compare to emscripten C++ api like emscripten:val, they have 'napi_create_reference' to direct reference javascript object in C code. If Emscripten can adopt these APIs, things may make easier, as Embind & WebIDL can't use to export C library. return struct function in C with no 'cwrap' like api too.

**Comment by toyobayashi** [comment]
I made [a subset of NAPI (emnapi)](https://github.com/toyobayashi/emnapi) for emscripten. All Node.js official tests passed!

**Comment by kripken** [comment]
@toyobayashi Nice, very interesting!

Adding the "embind" label here, as if/when we do embind improvements I wonder if there might be a connection here.
