### ISSUE TITLE
Is there anything wrong with using the apt version of emscripten?

### ISSUE THREAD

**Issue by hokuco** [kripken/emscripten#7725]
I was wondering if I should install emscripten on ubuntu with the sudo apt-get install emscripten command, does it lack anything manually compiled emscripten has?

**Comment by hokuco** [comment]
Don't know if it helps, But I tried ./configure with it and this is the output:
https://pastebin.com/NpLgxs5k
(sidenote, why does ./configure not work[look at the bottom of the file]?)

**Comment by curiousdannii** [comment]
1. It's at least 3 years old.
2. There will be many bugs.
3. New features you see recommended in the docs or in tutorials won't be supported.
4. If you run into trouble, everyone will just tell you to upgrade, so you might as well just do that now.

**Comment by hokuco** [comment]
alright, I'll use that. thanks! 
by the way is there a list anywhere of all of emscripten's precompiled libraries?
