### ISSUE TITLE
WebAssembly instantiation error

### ISSUE THREAD

**Issue by waywardmonkeys** [kripken/emscripten#7735]
I'm trying to run some WebAssembly output via `node` (11.5.0) and get this:

```
failed to asynchronously prepare wasm: LinkError: WebAssembly Instantiation: table import 127 has no maximum length, expected 16164
[LinkError: WebAssembly Instantiation: table import 127 has no maximum length, expected 16164]
[LinkError: WebAssembly Instantiation: table import 127 has no maximum length, expected 16164]
```

With a big project, I'm getting these and then it fails to start up ... any idea?

**Comment by kripken** [comment]
The node version looks recent enough that I doubt it's a problem there, but to make sure I'd try it in a web browser.

The error does look odd - like node doesn't allow table growth. Perhaps the JS was generated declaring the table as not growing, and the wasm declares that it does? I don't think we have any bugs there. What version and what args was this built with?

**Comment by waywardmonkeys** [comment]
Current `incoming` (48464437f8e39d18caebe79d8dfc1ed95eb60277) and `incoming` for fastcomp.

The args were:

```
    "-Os"
    "-s ALLOW_MEMORY_GROWTH=1"
    "-s DISABLE_EXCEPTION_CATCHING=0"
    "-s ERROR_ON_UNDEFINED_SYMBOLS=1"
    "-s ASSERTIONS=1"
```

This also happened when using the wasm backend with a build of a recent version of clang from upstream LLVM.

**Comment by kripken** [comment]
Thanks - there doesn't seem to be anything special with those flags, building hello world with them I don't see a problem.

Do you get the same error in a browser? Is this code you can share publicly?

**Comment by waywardmonkeys** [comment]
Okay, if you clone my fork of Z3 and use the `tentative-emscripten` branch with `emcmake cmake .. -GNinja` and so on ... then you should end up with the problem that I'm describing here.

https://github.com/waywardmonkeys/z3/tree/tentative-emscripten

**Comment by kripken** [comment]
Hmm, I don't see the problem,
```
$ nodejs z3.js
Error: input file was not specified.
For usage information: z3 -h
$ nodejs --version
v10.13.0
```

**Comment by waywardmonkeys** [comment]
Crazy. I will dig into it more tomorrow!

**Comment by waywardmonkeys** [comment]
wow, I must've been tired before. I had modified my `~/.emscripten` incorrectly and it was pointing at the wrong build of LLVM. :(

**Comment by waywardmonkeys** [comment]
The perils of multiple builds and versions :( Sorry about that!
