### ISSUE TITLE
Copy/Assignment of struct produces strange results

### ISSUE THREAD

**Issue by mikeb01** [kripken/emscripten#7738]
I've found if I try to assign variable of a struct type (i.e. copying the value), when compiled using emscripten and run in Chrome I get strange results.  With the code listed below I get the output (when clicking the "swap" button - "swap fields" works fine):

```
1,a Expected 1 Actual 3
1,b Expected 2 Actual 4
```

In other less contrived examples I've seen a variety issues including data corruption and page crashes.  The code works when run via a standard c compile.

Version information below.

```c

struct foo
{
    double a;
    double b;
};

struct foo foos[2];

void swap(int a, int b)
{
    struct foo temp;

    temp = foos[a];
    foos[a] = foos[b];
    foos[b] = temp;
}

void swap_fields(int a, int b)
{
    struct foo temp;

    temp.a = foos[a].a;
    temp.b = foos[a].b;

    foos[a].a = foos[b].a;
    foos[a].b = foos[b].b;

    foos[b].a = temp.a;
    foos[b].b = temp.b;
}

void set_foo(int index, double a, double b)
{
    foos[index].a = a;
    foos[index].b = b;
}

double get_foo_a(int index)
{
    return foos[index].a;
}

double get_foo_b(int index)
{
    return foos[index].b;
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Struct Assignment</title>
    <script>
        let ex = null;
        load();

        function load() {
            let memory = new WebAssembly.Memory({initial: 256, maximum: 512});
            fetch('test.wasm')
                .then(response => response.arrayBuffer())
                .then(bytes => WebAssembly.instantiate(bytes, {env: {__memory_base: 0, memory: memory}}))
                .then(results => {
                    ex = results.instance.exports;
                })
                .then(a => console.log("Loaded"));
        }

        function assert(message, expected, actual) {
            if (expected !== actual) {
                console.log(message, "Expected", expected, "Actual", actual);
            }
        }

        function swap() {
            const initial_0_a = 1;
            const initial_0_b = 2;
            const initial_1_a = 3;
            const initial_1_b = 4;

            ex._set_foo(0, initial_0_a, initial_0_b);
            ex._set_foo(1, initial_1_a, initial_1_b);
            ex._swap(0, 1);

            assert("1,a", initial_0_a, ex._get_foo_a(1));
            assert("1,b", initial_0_b, ex._get_foo_b(1));
            assert("0,a", initial_1_a, ex._get_foo_a(0));
            assert("0,a", initial_1_b, ex._get_foo_b(0));
            console.log("Swap complete");
        }

        function swapFields() {
            const initial_0_a = 1;
            const initial_0_b = 2;
            const initial_1_a = 3;
            const initial_1_b = 4;

            ex._set_foo(0, initial_0_a, initial_0_b);
            ex._set_foo(1, initial_1_a, initial_1_b);
            ex._swap_fields(0, 1);

            assert("1,a", initial_0_a, ex._get_foo_a(1));
            assert("1,b", initial_0_b, ex._get_foo_b(1));
            assert("0,a", initial_1_a, ex._get_foo_a(0));
            assert("0,a", initial_1_b, ex._get_foo_b(0));
            console.log("Swap fields complete");
        }
    </script>
</head>
<body>
<form>
    <input type="button" onclick="swap()" value="swap">
    <input type="button" onclick="swapFields()" value="swap fields">
</form>
</body>
</html>
```
Compiled:
```
$ emcc test.c -o test.wasm -Oz -s SIDE_MODULE=1 -s WASM=1 -s "EXPORT_ALL=1"
```

```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.21
clang version 6.0.1  (emscripten 1.38.21 : 1.38.21)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/barkerm/sources/wasm/emsdk/clang/e1.38.21_64bit
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
```

**Comment by kripken** [comment]
It looks like you're using your own JS to load and run the wasm, instead of what emcc emitted for you. Does it work with emcc's JS code?

(It's possible to use your own JS, but you need to be very careful, and this is an area we are currently looking to improve. We don't recommend it yet. See e.g. https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone and https://github.com/kripken/emscripten/pull/7733 )

**Comment by brion** [comment]
I think what's going on is that the temporary variables on the stack are overwriting the static global variables. If I set the __memory_base to 512 instead of 0, I don't get the unexpected values when running it.

**Comment by mikeb01** [comment]
I've been looking at the generated wasm and I'm a little confused.  If I look at the swap_fields function (which works as expected), I see the following definition.
```
(func $_swap_fields (export "_swap_fields") (type $t0) (param $p0 i32) (param $p1 i32)
  (local $l0 i32) (local $l1 f64) (local $l2 f64)
  (set_local $l1
    (f64.load
      (tee_local $l0
      ...
```
The key thing is that this function reserves space for the for the local variable ($l1, $l2) and these variables don't interfere with the linear memory.  Comparing this to the swap function.
```
(func $_swap (export "_swap") (type $t0) (param $p0 i32) (param $p1 i32)
  (local $l0 i32) (local $l1 i32)
  (set_local $l0
    (get_global $g1))
  (set_global $g1
 ```
The swap function only appears to reserve 2 i32 local variables, so it looks like it does the swap in linear memory.  Where as I would expect the compiler to have unpacked the `struct foo temp` and generated code that would have been very similar to the `swap_fields` function.  It looks like the compiler is not treating the `temp` variable as a local variable.  I don't think this is an issues with stack variable interfering with the linear memory, but that it is not using stack variables at all.

**Comment by mikeb01** [comment]
I think that would work fine if the 4 32 bit integers were reserved as local variables, however this uses linear memory to store the temporary variable.  Is this because emscripten is trying to be as conservative as possible with it's use of the stack as the available stack size is non-deterministic?

**Comment by mikeb01** [comment]
I've been playing a bit more with some of the other compilation options (e.g. the LLVM wasm backend) and it is definitely something that LLVM is doing.  Mostly just interested in why (rather than an actual issue), so I'll close this now.
