### ISSUE TITLE
-s ENVIRONMENT=web disables worker detection

### ISSUE THREAD

**Issue by surma** [kripken/emscripten#7801]
Setting `-s ENVIRONMENT=web` sets `ENVIRONMENT_IS_WORKER=false`.

I found this surprising. I think it’s reasonable to consider workers to be part of the web. WDYT?

**Comment by kripken** [comment]
I think the original idea was that workers may need different code (for proxying), so separate options was better for code size etc.

We should probably add an option for `ENVIRONMENT=web,worker` which would support more than one, for that use case.
