### ISSUE TITLE
[Feature request] Allow override of filesystem emulation

### ISSUE THREAD

**Issue by surma** [kripken/emscripten#7804]
The filesystem emulation is quite heavy in terms of file size. My glue code’s total size (140K) is 50%for filesystem-related: `FS`, `PATH`, `NODEFS`, `MEMFS`, etc.

In my case, I don’t actually need them and I am not sure why they are included in the first place. I’m sure that there is some piece of code that technically could use filesystem calls, but in practice it doesn’t happen. Stripping those variables from the glue code saves 70K, which is quite considerable.

In light of this, I think it’d be great if there was a flag to override the inclusion of filesystem emulation. Basically the opposite of `-s FORCE_FILESYSTEM=1` — maybe  `-s FORCE_NO_FILESYSTEM=1`?

**Comment by kripken** [comment]
There is an option for this, `-s FILESYSTEM=0`. Perhaps we should documented it better, though, was there a place in the docs you looked that this was missing from?

**Comment by surma** [comment]
I’d have expected to find this [here](https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html)

**Comment by kripken** [comment]
Thanks, opened #7807
