### ISSUE TITLE
"memory access out of bounds" Exception thrown when allocating memory in C++ code

### ISSUE THREAD

**Issue by nnarain** [kripken/emscripten#7817]
Hi.

I've been having some trouble passing an array buffer to C++ and using it. Now the data does make it to the C++ code, however, this exception ends up being thrown.

I use the following code to load the binary file.

```
            var openFile = function(event) {
                var input = event.target;
                var reader = new FileReader();
                reader.onload = function(e) {
                    var buffer = reader.result;
                    var length = buffer.byteLength;

                    var ptr = Module._malloc(length);
                    Module.HEAPU8.set(buffer);

                    console.log("Loading GameboyCore with ROM file data");
                    console.log(core.loadROM(ptr, length));
                    Module._free(ptr);
                };

                console.log(input.files[0]);
                reader.readAsArrayBuffer(input.files[0]);
```

`core.loadROM` being the relevant C++ function.

Which look like:

```
class GameboyCoreJS {
        ...
        std::string loadROM(const uintptr_t handle, size_t length)
        {
            try
            {
                const auto buffer = reinterpret_cast<const uint8_t*>(handle);
                core_->loadROM(buffer, length);
            }
            catch(const std::runtime_error& e)
            {
                const std::string message{e.what()};
                return message;
            }

            return std::string{"Success"};
        }
```

`GameboyCoreJS` is the emscripten wrapper for `GameboyCore` here.

The `ptr` passed from JS is reinterpreted as an actual pointer and passed to the underlying library for loading.

However, it fails at the first line of this function:

```
        void loadROM(const uint8_t* rom, uint32_t size)
        {
            mmu.reset(new MMU(rom, size));
            ...
```

Now I've uncommented the contents of the `MMU` classes constructor but the exception is still thrown.
So it seems to not like that allocation.

I'm hoping there is something stand out here that I'm doing wrong.

Any advice appreciated.

**Comment by brion** [comment]
```
                    Module.HEAPU8.set(buffer);
```
I think you're missing "`, ptr`" here. Without the pointer offset, you're overwriting the beginning of memory which is likely to damage global state for the stack, allocator etc.

**Comment by nnarain** [comment]
Hey brion, thanks for the response.

I copied the above from some other attempts at loading the binary file. I have tried `Module.HEAPU8.set(buffer, ptr);` as well. I get the same exception thrown in the same place.

```
                reader.onload = function(e) {
                    var buffer = reader.result;
                    var length = buffer.byteLength;

                    var ptr = Module._malloc(length);
                    Module.HEAPU8.set(buffer, ptr);

                    console.log("Loading GameboyCore with ROM file data");
                    console.log(core.loadROM(ptr, length));
                    Module._free(ptr);
                };
```

**Comment by brion** [comment]
Try also `Module.HEAPU8.set(new Uint8Array(buffer), ptr);` -- in my testing it doesn't actually copy any data if you just pass an ArrayBuffer in directly.

However this should not affect an allocation, assuming other data structures remain intact... Can you post an example somewhere where it can be debugged?

**Comment by nnarain** [comment]
Tried `Module.HEAPU8.set(new Uint8Array(buffer), ptr);` with no unluck. Same issue.

This branch contains the code I'm using: https://github.com/nnarain/gameboycore-web/tree/issue7-gameboycorejs

**Comment by nnarain** [comment]
Well, I feel silly. Looks like I was prematurely releasing the object's memory which obviously caused some bad things to happen.

Anyways I appreciate your help here @brion. No issue here, so I'll go ahead and close this.
