### ISSUE TITLE
Optimization breaks SHELL env (Can't find variable: read)

### ISSUE THREAD

**Issue by zpalmtree** [kripken/emscripten#7841]
I'm compiling some C++ to work in react native. This works near perfectly if you just set the environment to 'SHELL', and export 'Module'.

Using default optimizations, and -O1 works fine, however, when I use -O2 or -O3, I'm getting the error in the title. 

Specifically, the code is failing here:

```
if (typeof read != "undefined") {
  Module["read"] = function shell_read(f) {
   return read(f);
  };
 }
 Module["readBinary"] = function readBinary(f) {
  var data;
  if (typeof readbuffer === "function") {
   return new Uint8Array(readbuffer(f));
  }
  data = read(f, "binary"); // this line causes fail
  assert(typeof data === "object");
  return data;
 };
```

I tried to manually patch the code, however, I can't see where 'read' is defined in the working, unoptimized code. If it's expected to be in the shell environment, I'm not sure why it's working in the unoptimized build.

Here's what I think is the relevant code from the unoptimized build (-O1):

```
if (typeof read != 'undefined') {
    Module['read'] = function shell_read(f) {
      var data = tryParseAsDataURI(f);
      if (data) {
        return intArrayToString(data);
      }
      return read(f);
    };
  }

  Module['readBinary'] = function readBinary(f) {
    var data;
    data = tryParseAsDataURI(f);
    if (data) {
      return data;
    }
    if (typeof readbuffer === 'function') {
      return new Uint8Array(readbuffer(f));
    }
    data = read(f, 'binary');
    assert(typeof data === 'object');
    return data;
  };
```

I assumed it was using tryParseAsDataURI and never reaching the `read` code, however copying and pasting that into the optimized code didn't work...

Oh, and here's my compilation script:

Working:

```
emcc -O3 ../src/*.c -o c.bc
emcc -O3 -std=c++17 ../src/crypto.cpp ../src/StringTools.cpp
emcc -g1 -O1 -s WASM=0 -s POLYFILL_OLD_MATH_FUNCTIONS=1 --bind -std=c++17 -o "turtlecoin-crypto.js" c.bc cpp.bc ../src/turtlecoin-crypto.cpp
```

Not working:

```
emcc -O3 ../src/*.c -o c.bc
emcc -O3 -std=c++17 ../src/crypto.cpp ../src/StringTools.cpp
emcc -g1 -O3 -s WASM=0 -s POLYFILL_OLD_MATH_FUNCTIONS=1 --bind -std=c++17 -o "turtlecoin-crypto.js" c.bc cpp.bc ../src/turtlecoin-crypto.cpp
```

(Only change is the last line)

Hopefully you can provide some advice.

Thanks for the project :)

**Comment by kripken** [comment]
I believe `read` is defined by shells (d8 and js, for example). So it's not expected to appear in the emitted code. Perhaps something in react native defines it? A simple way to check is to do `alert(read)` right before it's called, then it'll print out what the function contains, and hopefully it's easy to figure out how it works in the unoptimized case.

**Comment by zpalmtree** [comment]
Sorry, I guess I was just tired when I made this bug report. Read *was* undefined in react native, however, because -O1 didn't use a memory init file, it never got to that codepath.

After using -O3 without a separate file, it worked fine. Thanks!
