### ISSUE TITLE
Wrong `if` evaluation with bitwise operations

### ISSUE THREAD

**Issue by FiloSottile** [kripken/emscripten#785]
C code:
```
	if ((N & (N - 1)) != 0) {
		errno = N & (N - 1);
		goto err0;
	}
```

And what I get is a `errno = 0`, can't be right...

**Comment by juj** [comment]
Closing as resolved, this reads like there was not a compiler codegen problem. If there's some trouble with the latest compiler version, let's reopen with a new focused test case.
