### ISSUE TITLE
Recognize `.mjs` the same as `.js`

### ISSUE THREAD

**Issue by surma** [kripken/emscripten#7853]
`.mjs` is the file extension that is used for ES6 modules.

Emscripten should probably output an `.mjs` file when `-s EXPORT_ES6=1` is set.

//edit: Emscripten currently outputs LLVM IR code when specifying `-o file.mjs`.

**Comment by sbc100** [comment]
Should be an easy fix..

**Comment by surma** [comment]
To load an ES6 module in Node, an `.mjs` extension is _required_. Since that decision has been made, we are making an effort to make all tooling understand this and behave similarly.

I’d _prefer_ to automatically output `.mjs` when `EXPORT_ES6` is set, but at the very least Emscripten should not output LLVM IR when `-o something.mjs` is specified 😄 

cc @mathiasbynens to keep me honest.

**Comment by mathiasbynens** [comment]
@surma nailed it:

> I’d prefer to automatically output `.mjs` when `EXPORT_ES6` is set, but at the very least Emscripten should not output LLVM IR when `-o something.mjs` is specified 😄

**Comment by kripken** [comment]
Thanks, makes sense. Ok, sgtm to emit `.mjs` in that case, and I see @sbc100 is already assigned here.

**Comment by dasa** [comment]
Should the output then work as a ES Module in Node?

I'm getting an error when I try that.

I compiled the sample shown at https://v8.dev/features/wasm-bigint using: `emcc example.c --js-library example.js -o out.mjs -s WASM_BIGINT`

I then started Node 14.15 using `node --experimental-wasm-bigint` and entered `import("./out.mjs").then(m => { console.log(m.default()) })` and the output error is:

```
Promise { <pending> }
> (node:93802) UnhandledPromiseRejectionWarning: ReferenceError: __dirname is not defined
    at Module.<anonymous> (file:///Users/dasa/test/out.mjs:162:5)
    at REPL1:1:54
```

**Comment by wltsmrz** [comment]
Ran into that recently myself @dasa . I think the ES modules are meant to not contain Node-specific features like __dirname. The trick to get it to work apparently is:

```js
import path from 'path'
const __dirname = path.dirname(new URL(import.meta.url).pathname)
```

**Comment by sbc100** [comment]
Looks like something we should fix.  Would you mind opening a separate issue specifically about `__dirname`?

**Comment by curiousdannii** [comment]
Already raised: #11792
