### ISSUE TITLE
How to remove prefix on exported functions and classes?

### ISSUE THREAD

**Issue by prsolucoes** [kripken/emscripten#7864]
Hi,

Im exporting some functions and classes using emascripten, but everything is with "_" prefix.

How can i export without this prefix "_"?

My working samples:
https://github.com/ezored/sample-wasm

Thanks.

**Comment by kripken** [comment]
Emscripten exports stuff that way as a convention (similar to some assembly languages). There isn't an option to export without it. (But the exported name will be minified anyhow in higher optimization levels, together with the JS that connects to it.)

**Comment by prsolucoes** [comment]
Ok. thanks.
