### ISSUE TITLE
emcc fails if /usr/bin/python is python3

### ISSUE THREAD

**Issue by Midar** [kripken/emscripten#792]
Although the documentation says that python2 needs to be in the path, it is still looking for python it seems and thus fails to do anything, aborting with SyntaxErrors.

**Comment by meawoppl** [comment]
Apologies for dropping this thread.  People using python 3.* now outweigh people on 2.6.  Now that boto finally moved over, this is the last dependency causing me to keep py 2.7 around.  

Lemme get back to this.

**Comment by juj** [comment]
This has been fixed quite a bit time ago in #3872, so closing.
