### ISSUE TITLE
Linker reports symbol multiply defined for non-header includes

### ISSUE THREAD

**Issue by sbalko** [kripken/emscripten#831]
Hi,

I tried to compile a large C application, comprising multiple object files which I ultimately want to link into a single Javascript file. However, in the final Javascript generation/LLVM bitcode linking stage, I am getting the ill-famous "symbol multiply defined" error for a variable (here: ```mysymbol```) that is defined in a first source file (here: ```definition.c```) and also imported into another source file (here: ```usage.c```). Using the ```--remove-duplicates``` switch is to no avail and is apparently deprecated anyways. The two source files are:

```
#include <stdio.h>

const int mysymbol[3] = {1, 2, 3};

void myfunc() {
	printf("%i\n", mysymbol[0]);
}
```

and

```
#include <stdio.h>

#include "definition.c"

int main(int argc, char **argv) {
	printf("%i\n", mysymbol[0]);
}
```

I then compile the two source files without error:

```
emcc definition.c -o definition.o.bc
emcc usage.c -o usage.o.bc
```

However, collectively generating Javascript out of them fails with the "symbol multiply defined" error:
```
emcc definition.o.bc usage.o.bc -o test.js
```

On a side note: I agree that including non-header files is a bad practice. In fact, merely delcaring ```mysymbol``` in an additional header file ```definition.h``` which is imported in both other files solves the linker's colliding symbol problem for good. So I guess the root cause really is the non-header include (which is valid C nonetheless).

Any ideas?

Thanks,
Soeren

**Comment by juj** [comment]
Let me close this, since I think the original test case is incorrect code. Replacing `const int mysymbol[3] = {1, 2, 3};` with `static const int mysymbol[3] = {1, 2, 3};` should make it compile.

Alternatively linking via .a instead of via .bc might resolve the issue, though not sure. Perhaps that was the discrepancy all along between native and Emscripten (native used .a linking, but Emscripten .bc)
