### ISSUE TITLE
Miscompilation?

### ISSUE THREAD

**Issue by waywardmonkeys** [kripken/emscripten#873]
I've put a file up at https://gist.github.com/waywardmonkeys/5037344 ...

If you compile it with no flags, it works: ``em++ includes.pass.cpp``

If you compile it at -O1 or  -O2, it goes into an infinite loop:  ``em++ -O2 --closure 0 includes.pass.cpp``

**Comment by juj** [comment]
Yay, +1 for rigid easily verifiable test cases @waywardmonkeys. Tested now with latest Emscripten incoming which has llvm 3.9, and there it builds and runs correctly. I'll close this as resolved, not sure if the issue still persists in LLVM side (the llvm.org bug conversation history makes it unclear) and if it was the disabling of LTO that made this work for Emscripten, though tried with `--llvm-lto 1` and `--llvm-opts 3` on emcc command line, but couldn't find the hang.
