### ISSUE TITLE
toNiceIdent() doesn't handle exclamation marks

### ISSUE THREAD

**Issue by brk** [kripken/emscripten#896]
It's really just a one line patch:

    -  return ident.replace('%', '$').replace(/["&\\ \.@:<>,\*\[\]\(\)-]/g, '_');
    +  return ident.replace('%', '$').replace(/["&\\ \.!@:<>,\*\[\]\(\)-]/g, '_');

but this also includes a new test case (probably not the right way to do it?) etc.

    diff --git a/AUTHORS b/AUTHORS
    index 3a7ceb3..be32733 100644
    --- a/AUTHORS
    +++ b/AUTHORS
    @@ -50,4 +50,5 @@ a license to everyone to use it as detailed in LICENSE.)
    * Bruce Mitchener, Jr. <bruce.mitchener@gmail.com>
    * Michael Bishop <mbtyke@gmail.com>
    * Roger Braun <roger@rogerbraun.net>
    +* Ben Karel <eschew@gmail.com>
    
    diff --git a/src/parseTools.js b/src/parseTools.js
    index 357d33a..6dd3b39 100644
    --- a/src/parseTools.js
    +++ b/src/parseTools.js
    @@ -78,7 +78,7 @@ function toNiceIdent(ident) {
      assert(ident);
      if (parseFloat(ident) == ident) return ident;
      if (ident == 'null') return '0'; // see parseNumerical
    -  return ident.replace('%', '$').replace(/["&\\ \.@:<>,\*\[\]\(\)-]/g, '_');
    +  return ident.replace('%', '$').replace(/["&\\ \.!@:<>,\*\[\]\(\)-]/g, '_');
    }
    
    // Kind of a hack. In some cases we have strings that we do not want
    diff --git a/tests/hello_world_bang.ll b/tests/hello_world_bang.ll
    new file mode 100644
    index 0000000..a5dbf56
    --- /dev/null
    +++ b/tests/hello_world_bang.ll
    @@ -0,0 +1,18 @@
    +; ModuleID = 'tests/hello_world.bc'
    +target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:32:32-n8:16:32-S128"
    +target triple = "i386-pc-linux-gnu"
    +
    +@.str = private unnamed_addr constant [15 x i8] c"hello, world!\0A\00", align 1 ; [#uses=1 type=[15 x i8]*]
    +
    +; [#uses=0]
    +define i32 @main() {
    +entry:
    +  %"!retval" = alloca i32, align 4                   ; [#uses=1 type=i32*]
    +  store i32 1, i32* %"!retval"
    +  %call = call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([15 x i8]* @.str, i32 0, i32 0)) ; [#uses=0 type=i32]
    +  %rv = load i32* %"!retval"
    +  ret i32 %rv
    +}
    +
    +; [#uses=1]
    +declare i32 @printf(i8*, ...)
    diff --git a/tests/runner.py b/tests/runner.py
    index 96a2dab..23a98dc 100755
    --- a/tests/runner.py
    +++ b/tests/runner.py
    @@ -8407,6 +8407,12 @@ Options that are modified or new in %s include:
            assert os.path.exists('a.out.js'), '\n'.join(output)
            self.assertContained('hello, world!', run_js('a.out.js'))
    
    +        self.clear()
    +        output = Popen([PYTHON, compiler, path_from_root('tests', 'hello_world_bang.ll')], stdout=PIPE, stderr=PIPE).communicate()
    +        assert len(output[0]) == 0, output[0]
    +        assert os.path.exists('a.out.js'), '\n'.join(output)
    +        self.assertContained('hello, world!', run_js('a.out.js'))
    +
            # emcc [..] -o [path] ==> should work with absolute paths
            try:
              os.mkdir('a_dir')

I'm not sure if `runner.py` has hit the new testcase yet -- still grinding away -- but I ran emcc/node by hand to verify that the .ll is fixed by the patch.

**Comment by juj** [comment]
Looks like this was left dangling as open, closing as per https://github.com/kripken/emscripten/pull/935#issuecomment-34813185.
